### ISSUE TITLE
"falsey" property values defined in languages are overridden by base properties

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#1000]
e.g. if you set `needsMulti` to false in the language settings (`c++.local.properties`) it still gets read as `true` as the falseness is enough to cause fallback to the compiler-explorer.properties.

**Comment by RabsRincon** [comment]
Unrelated to the issue described here, but:
This was the one thousandth issue!
 🎉

**Comment by mattgodbolt** [comment]
Haha! I know. I had a little grin to myself too.
