### ISSUE TITLE
Add {go,rust}fmt tools

### ISSUE THREAD

**Issue by RubenRBS** [compiler-explorer/compiler-explorer#1009]
It shows my total lack of knowledge that it took so long for me to find out gofmt (Working on improving it tho!) and rustfmt. 

It should be easy enough using the code used for clang-tidy + the additional "Which formatter to use" which could be moved to the server instead of the hardcoded clang-tidy that is currently used.

Maybe take a look and see if rustfmt is also implementable?

**Comment by Artoria2e5** [comment]
I think one thing we can try to make it more extensible is to ask for `/api/format/${this.currentLanguage}` instead of looking for clang-format by name.
