### ISSUE TITLE
Filter msvc filename output

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#1034]
MSVC outputs the filename of the file it's compiling. That means things like the conformance view go yellow, assuming it's a warning. We should fix that, probably by filtering wine output.

See also #1017

**Comment by JC3** [comment]
Also vote on https://developercommunity.visualstudio.com/t/allow-having-clexe-not-print-the-compiled-source-f/717761

**Comment by JC3** [comment]
So.... I'm not familiar with the codebase here *at all*, so I might be way off base, but after some digging it looks like `utils.js` handles compiler message parsing, right?

So maybe the workaround is here:

https://github.com/compiler-explorer/compiler-explorer/blob/711ffdb041159265bd184421fb53dda9359fde48/lib/utils.js#L101-L129

Just some hack like if it's the first line and it exactly matches the input filename then drop it? I don't know if that'd interfere with anything else though. If the compiler in use is available to `parseOutput` then it could only do that for msvc.

Or not, lol. 🤷‍♂️

**Comment by RubenRBS** [comment]
Done clientside where it matters, I think we can call it closed
