### ISSUE TITLE
MOTD issues

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#1057]
The new ads/MOTD system seems to cause some issues:

https://sentry.io/compiler-explorer/compiler-explorer/issues/629735356/

```
Stacktrace (most recent call first):

  at handler (./static/motd.js:80:1)
```

**Comment by mattgodbolt** [comment]
Could be ad-blocker related, perhaps?

**Comment by mattgodbolt** [comment]
```javascript
    $.getJSON(url)
        .then(function (res) {
            handleMotd(res, motdNode, defaultLanguage, adsEnabled, onHide);
        })
        .catch(function (xhr, error, exc) {
            Raven.captureException(exc);
        });
```

I suspect the parameters to `catch` are wrong, so we're doing `Raven.captureException(undefined)`. Maybe it's a timeout?

**Comment by mattgodbolt** [comment]
Fiddled with this and hopefully fixed in 423f6688efca7a11dd7f5f21281f2e1c82de794c

**Comment by mattgodbolt** [comment]
I changed the function signature but it's still not right :)

```
MESSAGE
Non-Error exception captured with keys: abort, always, catch, done, fail…
```

**Comment by mattgodbolt** [comment]
Sentry issue: [COMPILER-EXPLORER-47W](https://sentry.io/compiler-explorer/compiler-explorer/issues/797502668/?referrer=github_plugin)

**Comment by mattgodbolt** [comment]
Maybe fixed it again...we'll see :-)

**Comment by mattgodbolt** [comment]
This has never gone away. We should either swallow it up, or work out what on earth is going on here :)

**Comment by mattgodbolt** [comment]
`MOTD error for /motd/motd-prod.json - error - ` is what it shows up - that is, textStatus is "error" and the "errorThrown" is undefined or empty. Breadcrumbs show a normal `GET` to the right URL goes out. Could be ad blockers etc though?

**Comment by mattgodbolt** [comment]
Dear me I hope I find out what this is. It's really annoying me :)

**Comment by mattgodbolt** [comment]
With latest info:
```
MOTD error for /motd/motd-prod.json - error - no error - readyState=0 - status=0
```

so, looks like we get MOTD canceled without even fetching anything, if I'm reading it right. Which I'm probably not.

Anyone with an ad blocker able to repro this?

**Comment by RubenRBS** [comment]
Got it to trigger (No adblocker needed) by navigating to another page/refreshing when the page is loading, before the reponse gets thru. The request gets cancelled and that's what we see as a status 0 (so at least in that way, this is not an error!)

But, it might be being triggered by something else too, who knows!
Sentry sadly does not save enough information to confirm if every instance of this is because of what I descirbed though

**Comment by mattgodbolt** [comment]
Thanks Ruben! Deploying shortly...

**Comment by mattgodbolt** [comment]
@RubenRBS and I spoke and I think we should probably just ignore these. I think we have accepted that page cancels, navigations, slow page loads, ad blockers etc are all completely sensible and valid errors we'll see.
