### ISSUE TITLE
[Proposal] Add Java to the list

### ISSUE THREAD

**Issue by oskidan** [compiler-explorer/compiler-explorer#1058]
Hi Matt,

Would you please conisder adding Java to the list of languages? This article explains how to do this: https://www.beyondjava.net/show-assembly-code-generated-jvm

The only thing that may be a show stopper is this:

> To reveal the actual Assembly code, you **_need to start the Java application_** with the PrintAssembly option

Although it should be possible to run JVM in a sandbox mode. I found this guide on how to do that:
https://github.com/alibaba/jvm-sandbox/blob/master/doc/JVM-SANDBOX-USER-GUIDE-English.md

BR,
Oleksii

P.S. Java9 and latter has AOT compiler. Maybe that compiler supports ASM dump generation.

P.P.S. In C++ community we talk alot about how our language is superior than Java. Compiler Explorer could be the tool to convince Java folks that we are right. ;-)

**Comment by ArsenArsen** [comment]
You could also make it output Java bytecode, that might be useful.

**Comment by mattgodbolt** [comment]
As a matter of (my personal...) policy we have so far not done JITted languages. Most of these languages require you to run a representative data set long enough to "warm up" the JIT to get output comparable to static compile output, and I'd hate for CE to become a "look how bad JITted language output is compared to static compiled".

AOT in these languages is typically not representative of real-world performance. At least part of my last decade of day-job experience has been in trying to compare JITted languages with compiled languages, and/or make them perform at the peak of their performance under particular conditions. It's a difficult area.

I could be swayed on this, provided we have a big banner saying "This assembly output is not representative".

In particular - and I know you put a winking smiley in your PPS - this is exactly what I DON'T want to happen: "language X is superior to Y". It often isn't. If we were to put in naïve Java output and use CE to compare with equivalents in C++ we'd be opening up a debate with a total straw-man argument. We have enough "holy wars" between languages without adding more to the mix.

**Comment by mattgodbolt** [comment]
The bytecode output might be useful, but I don't know. There's already java bytecode viewers (See #12 although these seem to be dead now, so maybe we should pick this up?).

When we have robust execution support (#429) we can also consider more representative inputs and then show ASM output from those. I'd feel a lot better about things then :)

**Comment by oskidan** [comment]
I agree that AOT does not represent the real world performance of JITted languages. I did not stated my intention clearly perhaps. The big idea is to be able to optimize AOT code. For example, AOT compiler is the only way to get Java running on iOS. Big thumbs up for bytecode viewer as well =)

**Comment by mattgodbolt** [comment]
The bytecode version of this is now live on the site.

**Comment by matsjla** [comment]
Closing this in favor of #3299 which can be used to track the AOT/JIT assembly output part of this request now that bytecode is live
