### ISSUE TITLE
Add SIMD Crate for Rust

### ISSUE THREAD

**Issue by superfunc** [compiler-explorer/compiler-explorer#1068]
I was looking into some vectorization comparisons in Rust, and it would be helpful if the SIMD crate was available as an external library: https://crates.io/crates/simd. I'd be happy to take a crack at this one myself as well.

**Comment by RabsRincon** [comment]
Hi @superfunc!

By all means, please feel free to contribute, we would very much appreciate it :)
If you need any help of have any questions, let us know so we can help as much as possible.

**Comment by RubenRBS** [comment]
Hi! Sorry about the lack of general updates on this topic and letting it get stale of 3 years. This turned out to be extremelly hard to implement, and is still in fact not supported. We're actively looking into it in the linked issue, so I'll close this in favour of that one :)
