### ISSUE TITLE
Blurring of share window & spacing comments

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#1121]
https://twitter.com/olafurw/status/1053737941380616192?s=19 some comments here

**Comment by RabsRincon** [comment]
@olafurw what browser do you use?

**Comment by olafurw** [comment]
Chrome Version 69.0.3497.100 on Windows 7, this appears at zoom levels 110%, 125%, 150% and anything below 100%

Also happens in Opera 56.0.3051.52, same zoom levels.

**Comment by mattgodbolt** [comment]
I see this on my phone, but not on my laptop. Laptop has high res display but even zoomed to 200% :
![screenshot from 2018-10-22 08-01-13](https://user-images.githubusercontent.com/633973/47294023-730e5380-d5d1-11e8-9bba-242f4698c6a2.png)

I'm on Chrome 69.0.3497.100 too, but on Linux. I wonder if it's a DPI thing?

**Comment by mattgodbolt** [comment]
Maybe a bit blurry at 125%: 
![screenshot from 2018-10-22 08-09-00](https://user-images.githubusercontent.com/633973/47294140-c84a6500-d5d1-11e8-87c6-fe9c306fae18.png)

**Comment by RabsRincon** [comment]
Can confirm that I can repro on a 1080p screen, but not on a 4k one. This seems like a Bootstrap issue to me

**Comment by mattgodbolt** [comment]
Just re-checking. 125% still looks a bit blurry. I feel bad in saying I don't have a 1080p screen around any more to test with (!!)

**Comment by olafurw** [comment]
![image](https://user-images.githubusercontent.com/103783/68689784-3b25d580-0571-11ea-882e-2aa0c0f4d975.png)

Still blurry at 110% when other stuff around it isn't. Tested on both a 1080p screen and a 1440p screen.

**Comment by apmorton** [comment]
can confirm this is an issue with bootstrap, but is ultimately a bug in the browser according to them - https://github.com/twbs/bootstrap/issues/22610

 110% on my machine
![image](https://user-images.githubusercontent.com/63636/68694447-2df3f100-0547-11ea-9b58-43e026bf08a2.png)

disable the CSS `transform` that bootstrap uses to position the popover:
![image](https://user-images.githubusercontent.com/63636/68694429-23d1f280-0547-11ea-889d-654f37ae84a4.png)

Seems like the only workaround is to disable GPU acceleration - some people mention being able to do that specifically for the popover, but I don't know how to accomplish that.

**Comment by mattgodbolt** [comment]
Thanks @apmorton ... this is starting to sound like more work than it "ought" to be :D

**Comment by RabsRincon** [comment]
I can no longer repro this. Can you check if it still happens for you? There have been some changes that might have inadvertedly worked around this issue

**Comment by olafurw** [comment]
![image](https://user-images.githubusercontent.com/103783/71414959-a8b82d80-2616-11ea-8045-8d0221f28016.png)

110% zoom on chrome on fedora 30. 

Sorry, yeah this isn't the biggest issue around but thanks for keeping a focused eye on it :P

**Comment by olafurw** [comment]
Quick comment, why isn't the share dropdown made the same way the other drop downs are made? No blur there.

![image](https://user-images.githubusercontent.com/103783/71415063-427fda80-2617-11ea-9978-f1ac04cb45c0.png)

110% zoom on chrome fedora 30.

**Comment by apmorton** [comment]
The TLDR of why they are different is "because bootstrap".

Basically the other menus are "Dropdowns" in bootstrap, which are really only allowed to contain lists of links or buttons.

Because the share drop-down contains some more custom layout it uses a "Modal" in bootstrap. The modal is where the bug is that causes the blurring when zoomed.

**Comment by olafurw** [comment]
If you wanna close this sucker, put your fingers in your ears and say "I don't care right now lalala" then I don't mind haha :D

**Comment by olafurw** [comment]
Does not happen any more and the design of the site doesn't look like this anymore.
Can close.
