### ISSUE TITLE
Comment filter eliminates cuda/ptx predicated instructions

### ISSUE THREAD

**Issue by RedBeard0531** [compiler-explorer/compiler-explorer#1128]
https://godbolt.org/z/YMp7ge

Line 23 in the middle column is *very* important but is filtered out of the default view (right column). I think this is also causing the `BB0_2` label to be considered unused and filtered out, but that could be a different bug.

Ideally the syntax highlighting wouldn't show predicated lines as comments, but showing them at all it the most important fix.

**Comment by apmorton** [comment]
In link you provided the code now appears identical (besides broken demangling on the right, and the unused labels filter also being broken).

I would say the bug reported here has been fixed sometime over the last two years - but there are definitely still some issues with other filters on cuda.
