### ISSUE TITLE
Timeout at gateway occurs before code compilation times out

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#1130]
For example: https://godbolt.org/z/Sexc9S times out with a 504 Gateway Timeout (which appears as `<Compilation failed: Error sending request>`). In theory the compilation should time out on the server and return a document that says "This timed out"

**Comment by mattgodbolt** [comment]
(Confirmed still happens)

**Comment by apmorton** [comment]
here is a fixed link (catch2 include url changed): https://godbolt.org/z/rjnTqM

but in any case, I am closing this as "fixed" - it compiled in about 54 seconds for me.

This is likely a dup of #1336 anyway.
