### ISSUE TITLE
GDC compiler

### ISSUE THREAD

**Issue by DesWurstes** [compiler-explorer/compiler-explorer#1138]
GDC compiler is [now shipped with GCC trunk](https://github.com/gcc-mirror/gcc/commit/03385ed3d679cd8125f282697a1c7cf46f8361cc) The latest GDC compiler on Compiler Explorer has version 5.2.0, after GCC 9 release, GDC 9 should be added too.

**Comment by mattgodbolt** [comment]
We'll need to update our build scripts to build GDC too, and then we can deploy it as part of our daily builds.

**Comment by mattgodbolt** [comment]
Building docker image now. Remaining:
* [ ] build gcc trunk and check D gets built
* [ ] rebuild 9.x.x and ditto
* [ ] update the config

**Comment by mattgodbolt** [comment]
```
Nov/12 05:48 admin-node~/compiler-explorer-image (master|✔) $ /opt/compiler-explorer/gcc-9.2.0/bin/gdc --version
gdc (Compiler-Explorer-Build) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by ibuclaw** [comment]
@mattgodbolt anything more to do here?  It looks like it can be closed.
