### ISSUE TITLE
Additional windows compilers support

### ISSUE THREAD

**Issue by apex-omontgomery** [compiler-explorer/compiler-explorer#1149]
With the addition of the new windows compilers I'd like to add a few more to support those who use cygwin and mingw for compiling gcc on windows. 

I'm not sure what versions of cygwin and mingw would be helpful. Ideally parity for the [x86 versions](https://github.com/mattgodbolt/compiler-explorer/blob/42c79d3c7927b6422d37d550245a66a3e96eaf2c/etc/config/c%2B%2B.amazon.properties#L7) would be awesome.

**Comment by mattgodbolt** [comment]
CC @Rastaban - any thoughts on how we might handle these kinds of request?

**Comment by Rastaban** [comment]
We have talked internally about eventually adding clang-cl, but I don't remember discussing mingw or Cygwin ports.

**Comment by ubsan** [comment]
We could absolutely do it, but it'd require quite a bit more effort than clang-cl :/

**Comment by wimo7083** [comment]
Why would there be more difficulty or effort?

**Comment by partouf** [comment]
Mingw doesn't really have a single up-to-date source of binaries, I suggested a distribution in https://github.com/mattgodbolt/compiler-explorer/pull/1074 to get objdump, but that's definitely different from the compilers.

Can Cygwin gcc run outside of the Cygwin environment?

**Comment by wimo7083** [comment]
No it appears you need the cygwin environment to bind to the windows [environment](https://stackoverflow.com/questions/27678988/run-cygwin-built-exe-in-windows-without-cygwins-environment).

**Comment by wimo7083** [comment]
Are you using the same build process or have you starting using a new build chain?

**Comment by wimo7083** [comment]
Thank you for adding this [documentation](https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/WindowsNative.md) 

I'll look into adding cygwin.

**Comment by mstorsjo** [comment]
For mingw compilers, GCC cross compilers provided by any distribution should work just fine (if that helps in any way). For clang, one can already use the existing clang instances by just adding `-target <arch>-mingw32` to the command lines, so it's primarily GCC that's missing.

**Comment by partouf** [comment]
we've supported mingw64 for a while now, closing this issue
