### ISSUE TITLE
Source code links in Clang AST output should not expand to the entire line

### ISSUE THREAD

**Issue by steveire** [compiler-explorer/compiler-explorer#1175]
Compiler explorer currently turns source locations which appear at the start of a line into a link to that line in the source code. That is done with `parseOutput` currently:

 https://github.com/mattgodbolt/compiler-explorer/blob/bdc447f/lib/utils.js#L58

The AST output in 

 https://godbolt.org/z/6C-Y5f

shows multiple source ranges and source locations. The fact that 

1) The source location is not at the start of the line
2) There are multiple source locations on a single line

means that source locations do not become links which direct the cursor to the specified line/column.

The source ranges and source locations could be parsed from the output. Here is how source ranges and source locations work in clang (I have no idea if GCC works similarly)

1) Source locations have 3 components - &lt;filename&gt;:line:column

The source location &lt;filename&gt;:3:4 means column 4 on line 3 in filename.

2) If multiple source locations are printed, deduplication of unchanged components occurs. For example, given the two printed locations

* &lt;filename&gt;:3:4
* col:5

the second location is equivalent to &lt;filename&gt;:3:5, but the filename and line were omitted and the `col` prefix is used.

Similarly

* line:4:5

means that the filename is unchanged since the last location printed, ie it is equivalent to &lt;filename&gt;:4:5

3) Ranges are bounded in angle brackets `<>`.

The following are valid ranges which might appear in output

* &lt;&lt;filename&lt;:3:4, col:5&gt;
* &lt;&lt;filename&gt;:3:4, line:4:5&gt;
* &lt;line:3:4, line:4:5&gt;
* &lt;line:3:4, col:5&gt;
* &lt;col:4, col:5&gt;

4) A range can extend backward

See

 https://godbolt.org/z/3aZ9RG 

which contains the range `<col:9, line:2:14>`. The `col:9` part refers to col 9 in line 4.

5) Ranges end at the end of C++ tokens.

See for example the block

```
<source>:2:1: note: SourceRanges here <<source>:2:1, col:15>

auto foo() -> int

^~~~~~~~~~~~~~~~~

 * "getTypeSourceInfo()->getTypeLoc().getSourceRange()"
```

Column 15 is the 'i' in 'int'.

http://ec2-52-14-16-249.us-east-2.compute.amazonaws.com:10240/z/XIvrS_

In theory, CE should highlight the range to the end of the token too, but that it likely impossible to implement in javascript.

6) Ranges can contain just one source location

* &lt;line:5:4&gt;

is a valid range which could be in output. It means that the beginning and the end of the range is at line 5 column 4. However, because the end should be extended to the end of the token, this could indicate more than one column in the source code.

See 

 http://ec2-52-14-16-249.us-east-2.compute.amazonaws.com:10240/z/1c3vCZ

which marks the 'int' return type range as `<<source>:2:1>`, and carets show the entire range.

**Comment by jeremy-rifkin** [comment]
I think we can close this, we now highlight sub-line tokens better (I think this is relatively recent, within the last year)
