### ISSUE TITLE
"Preprocess" tool

### ISSUE THREAD

**Issue by AlexAltea** [compiler-explorer/compiler-explorer#1177]
I'm using Compiler Explorer to analyze convoluted macros by specifying the `-E` flag in the compiler options. However, the corresponding output generated by the preprocessor can become unreadable at times since new lines are lost in translation (everything gets squashed into a single huge line).

Is there any way of applying `clang-format` to the output window (in the case of preprocessor output)? Although I'm aware I could just copy the output to the editor and press Ctrl+F9, this is too annoying to do manually all the time. An automated approach would be really convenient. :-)

**Comment by mattgodbolt** [comment]
Not at present, no. This sounds like a separate tool; the output window is optimized for assembly. If we knew the output was C++ we could enable this. There are other tools whose output is C++, which are also not supported well at present.

Sounds like the kind of thing you're doing might be easier locally for now using pipes or similar. But we may wish to support this use case in future.

**Comment by partouf** [comment]
Definitely sounds like a Preprocess Tool we could create, then we can include the formatting, (and perhaps even do syntax highlighting).

**Comment by RubenRBS** [comment]
This was added 6 months ago :)
