### ISSUE TITLE
[feature request] make the assembly flavor a drop down

### ISSUE THREAD

**Issue by robinmoussu** [compiler-explorer/compiler-explorer#1209]
Instead of having a simple "Intel" checkbox, I think it should better if it was a drop down. Currently we have:
- Intel
- AT&T

This list could be expended in the future, so I think it makes sense to use a drop-down.

An alternate solution is too have the mouse-over tooltip displaying "[OFF] AT&T syntax" when the checkbox in unchecked.

The modification has to be done in the `templates.pug` file, but I wasn't able to do it myself, sorry. No PR :(

**Comment by partouf** [comment]
AT&T is not a default thing for every compiler and intel an option, this is too complicated and finicky to figure out for every single compiler. Let's close this up.
