### ISSUE TITLE
Change working directory / support for json compilation-databases

### ISSUE THREAD

**Issue by ph03** [compiler-explorer/compiler-explorer#1237]
In a local installation, is there a way to change the working directory of the compiler "before" executing the compilation command? Asking because I'd like to run compiler-explorer on a particular file of a large local cmake-based project, and relative include-paths won't work if the working directory is not set. 

Effectively, I'd like to be able to instruct compiler-explorer to analyze a particular cpp file from the definitions outputted, e.g., by cmake's `CMAKE_EXPORT_COMPILE_COMMANDS`, which generates `compile_commands.json` files similar to LLVM/clang's definitions. Their definition is

```
...
{
  "directory": "/home/janickm/sdk/build-Release",
  "command": "/usr/bin/g++-4.9  -DEIGEN_DEFAULT_DENSE_INDEX_TYPE=std::int64_t -DEIGEN_NO_AUTOMATIC_RESIZING -DLINUX -isystem /usr/local/cuda-10.0/include -isystem ../3rdparty/src/imgui   -rdynamic -gsplit-dwarf -fstack-usage -fopenmp -O3 -DNDEBUG -fPIC   -std=gnu++14 -o 3rdparty/src/imgui/CMakeFiles/imgui.dir/imgui.cpp.o -c /home/janickm/sdk/3rdparty/src/imgui/imgui.cpp",
  "file": "/home/janickm/sdk/3rdparty/src/imgui/imgui.cpp"
},
...
```

and I'd like to analyze a compilation defined this way.

**Comment by RabsRincon** [comment]
There currently is not a way to do this other than editing the code that executes the compilers, but there is no reason for us not to add some kind of config you can use.
As it might take a bit before we get to implement it (Or someone opens a PR!) you might want to add a workaround yourself. I'd start by looking into https://github.com/mattgodbolt/compiler-explorer/blob/master/lib/base-compiler.js#L106 and the exec function it calls, as you can edit most of the stuff there by hand.
Sorry about the vague description of what to do. Hopefuly someone with a bit more of free time can help you further

**Comment by partouf** [comment]
Through the above mentioned you can set execOptions.customCwd to the directory you want when running the compile command

**Comment by partouf** [comment]
It's been a long time that this issue was posted, but I hope that the introduction of multifile/CMake offers a way to solve this. Albeit not exactly what this issue request is. I think we're more flexible with the CMake integration than a compile_commands json.
