### ISSUE TITLE
add branch of 1.0beta of range-v3 library (C++)

### ISSUE THREAD

**Issue by denchat** [compiler-explorer/compiler-explorer#1248]
It seems there is a new ahead-of-master branch of range-v3
https://github.com/ericniebler/range-v3/tree/v1.0-beta

**Comment by JeffGarland** [comment]
Was about to add this same issue.  This is important for looking at c++20 ranges.  Below is the response to an issue with supporting c++20 view behavior.

https://github.com/ericniebler/range-v3/issues/1087

range-v3's master branch doesn't support many of the C++20-required behaviors, notably including deduction guides for the XXX_view types. This does compile successfully on the v1.0-beta branch.

**Comment by partouf** [comment]
I think this branch was merged a while ago and is available through the trunk version.
A couple of (gcc) compilers also support some of the ranges features out of the box.

https://godbolt.org/z/h649cn
