### ISSUE TITLE
Copying out of compiler-explorer inserts extra newlines

### ISSUE THREAD

**Issue by BRevzin** [compiler-explorer/compiler-explorer#1260]
This is a really minor, low priority issue. Just a nuisance. When I copy output from Compiler Explorer, it always inserts extra newlines. The output is displayed properly, but a ctrl+c/ctrl+v later and I end up with:

```
<source>:8:24: error: static_assert expression is not an integral constant expression

    static_assert(size(a) == 4);

                  ~~~~~^~~~~~~

<source>:12:5: note: in instantiation of function template specialization 'f<char const[4]>' requested here

    f("foo");

    ^

1 error generated.

Compiler returned: 1
```

instead of, ideally:

```
<source>:8:24: error: static_assert expression is not an integral constant expression
    static_assert(size(a) == 4);
                  ~~~~~^~~~~~~
<source>:12:5: note: in instantiation of function template specialization 'f<char const[4]>' requested here
    f("foo");
    ^
1 error generated.
Compiler returned: 1
```

**Comment by mattgodbolt** [comment]
I wonder if we ought to just use an edit box for output (CC @RabsRincon ... can you remember why we don't do that instead of roll our own thing?). Though the fix might still be easy (perhaps we have a `\n` on each element?)

**Comment by RabsRincon** [comment]
Do you mean a textarea? We use "our own thing" because it allows us to link back to the corresponding source code lines. And fixing it might not be trivial, because as stated here https://bugzilla.mozilla.org/show_bug.cgi?id=1273836, HTML clipboard copying is not standarized and each implementation is free to do different things :(

**Comment by mattgodbolt** [comment]
Ahhh! Of course, yes. I do mean either a `textarea` or monaco thing. But you're right; the current allows us to make things clickable!

**Comment by partouf** [comment]
Fix is now live
