### ISSUE TITLE
Constant tooltips don't decode MASM 'H' suffix correctly

### ISSUE THREAD

**Issue by davidben** [compiler-explorer/compiler-explorer#1281]
MSVC's assembly output encodes unwind codes (`xdata` section, so disable the `.text` filter) in hexadecimal, using MASM's `H` suffix for hexadecimal. For example, in the link below, hover the cursor over the `010801H` constant.
https://godbolt.org/z/V6-qgL

The tooltip says `010801 = 0x2A31`, but the value is actually `67585 = 0x010801`.

I wasn't able to find a description of the syntax in the online MASM documentation, but this link describes "MASM expressions" in the context of the debugger:
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/masm-numbers-and-operators

**Comment by RabsRincon** [comment]
Hi! Thanks for the report. It seems to be a Monaco editor issue, as it reports the H as being another different word from the numeric bit. We will try to find a way to fix it (Either a workaround or reporting it to Microsoft so they can fix it, if in the end it turns out to be their problem)

:)

**Comment by RubenRBS** [comment]
If I'm seeing this right, this was fixed by #3280 but we never closed the issue, sorry!
