### ISSUE TITLE
Fully Demangle compiled CUDA code

### ISSUE THREAD

**Issue by eyalroz** [compiler-explorer/compiler-explorer#1294]
CUDA name mangling is an extension (or a slight modification) of C++ name mangling, so that just running C++ name demangling on the compiled PTX code still leaves some gibberish. In fact, your very own  CUDA example experiences this:
```
.visible .entry _Z6squarePii(
        .param .u64 _Z6squarePii_param_0,
        .param .u32 _Z6squarePii_param_1
)
```
That's not what we should be seeing.

**Comment by mattgodbolt** [comment]
Any ideas on how to demangle CUDA gratefully appreciated.

**Comment by eyalroz** [comment]
I'm not demangling expert, but it is [said](https://stackoverflow.com/questions/52307764/how-to-interpret-ptx-function-names) 

> CUDA uses the Itanium C++ ABI. What you see are standard g++ style mangled function names. Every host toolchain ships with a demangler which can parse mangled function names (c++filt is most typical). 

... except my c++filt doesn't demangle the names in PTX files :-(

**Comment by Staff-d** [comment]
I recently invested some time into researching options to demangle ptx, as I thought that this problem would be a "low hanging fruit". 

It turns out that Nvidia apparently has a demangleingtool which ships with `cuda-memcheck` (https://docs.nvidia.com/cuda/cuda-memcheck/index.html#command-line-options) but it cannot be used as a stand-alone tool or adopted easily.

The only other options I see is extending a existing c++ demangler. As I cannot find any specification on how cuda mangles function names, this would have to be done through reverse engineering their algorithm.

Taking all of this into account I don`t think that the gain would justify the effort one would have to put into this (rather small) features.

**Comment by eyalroz** [comment]
@Staff-d : The fact that they have a closed-source demangler in cuda-memcheck doesn't mean that the demangling is difficult. I'm sure it's pretty straightforward. In the example I gave above, we just need to add a space before the `_param_0` and `_param_1`, to get:
```
.visible .entry square(int*, int)(
        .param .u64 square(int*, int) param_0,
        .param .u32 square(int*, int) param_1
)
```
which is kind of silly but that's it's much more readable than before.  And this could be done with a `sed` command. A few of those should really spruce up the demangled PTX.

**Comment by sethrj** [comment]
@eyalroz As of [version 11.2](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/), the CUDA toolkit includes [the cu++filt](https://docs.nvidia.com/cuda/cuda-binary-utilities/index.html#cuplusplusfilt) for fully demangling CUDA symbols.

**Comment by partouf** [comment]
Might be plug and play by using that tool, thanks for the heads up!

**Comment by eyalroz** [comment]
@sethrj : I knew this was coming down the pipe at some point since I'm the one who filed the formal bug report at developer.nvidia.com about this :-P  ... didn't know it was out already. Would be great to see it in Compiler Explorer.

**Comment by SunsetQuest** [comment]
I wrote an app called CudaPAD that might have some helpful code for this. It is nearly identical to Compiler-explorer but just did worked on Cuda c++. It was mostly built in 2008 so the code might be a bit dated.  Code here: https://github.com/SunsetQuest/CudaPAD

**Comment by eyalroz** [comment]
This needs to be reopened, for two reasons:

1. It looks like no demangling is happening whatsoever...
2. cu++filt does not actually fully demangle PTX code: all parameter names are left mangled. 

See [this example](https://godbolt.org/z/aecoc9375):

```
.visible .func  (.param .b32 func_retval0) _Z3fooii(
        .param .b32 _Z3fooii_param_0,
        .param .b32 _Z3fooii_param_1
)
{

        ld.param.u32    %r1, [_Z3fooii_param_0];
        ld.param.u32    %r2, [_Z3fooii_param_1];
        add.s32         %r3, %r2, %r1;
        st.param.b32    [func_retval0+0], %r3;
        ret;

}
```
which should look like
```
.visible .func  (.param .b32 func_retval0) foo(int, int) (
        .param .b32 foo(int, int)_param_0,
        .param .b32 foo(int, int)_param_1
)
{

        ld.param.u32    %r1, [foo(int, int)_param_0];
        ld.param.u32    %r2, [foo(int, int)_param_1];
        add.s32         %r3, %r2, %r1;
        st.param.b32    [func_retval0+0], %r3;
        ret;

}
```

**Comment by partouf** [comment]
Looks like the demangling starts working again after switching off the comments filter. Obviously we've broken this somewhere along the line.

**Comment by eyalroz** [comment]
@benbarsdell : Please reopen this bug, compiled CUDA code is _not_ fully demangled.  You've only addressed point (1.), not point (2.).
