### ISSUE TITLE
[LLVM IR] Filter @llvm.dbg statements

### ISSUE THREAD

**Issue by bugwelle** [compiler-explorer/compiler-explorer#1314]
As per https://www.reddit.com/r/programming/comments/b44bhh/llvm_ir_line_highlighting_now_available_on/ej4az0u/

It should be possible to filter the debug function calls (e.g. call void `@llvm.dbg.declare(metadata i32* %4, metadata !14, metadata !DIExpression()), !dbg !15`). We could either add a filter to the IR pane or use the `lib.f` ("Filter functions from other libraries") button/filter for that.

**Comment by jeremy-rifkin** [comment]
This is closed by #5045 and #5078 🎉
