### ISSUE TITLE
Add library Itertools to Rust compiler

### ISSUE THREAD

**Issue by ronniec95** [compiler-explorer/compiler-explorer#1326]
It would be great to add this library to the set of available ones

Thank you

**Comment by RubenRBS** [comment]
Hi! It seems we forggot about this when we were compiling a list of all the requested Rust libraries, so sorry about that! (Also, sorry about not gettig back to you at any point during this!)
As you can see, support for Rust libraries is not yet implemented still after all this time.

I have added this request to said list, so I'll close this in favour of that one :)
