### ISSUE TITLE
"Query of death"

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#1336]
A couple of times recently we've had timeout events coupled with CPU autoscaling. I wonder if we're hitting some kind of super slow query that's wedging a node,
![Screenshot from 2019-04-03 10-50-09](https://user-images.githubusercontent.com/633973/55466124-d7acf000-55fe-11e9-937a-7de2c3ffcac7.png)

**Comment by mattgodbolt** [comment]
Timeline of recent occurrance:

2019-04-03T10:09:56 Launching a new EC2 instance due to CPU alarm (1->2) 066173ef45c38f698
2019-04-03T10:21:19 Terminating that instance (due to ELB system check failure) 066173ef45c38f698
2019-04-03T10:21:53 Launching a new EC2 instance as still want 2, but only have 1 0425ea926155cddf6
2019-04-03T10:26:37 Terminating instance due to ELB health check 08ca51409a7485204 (apparently the original instance)
2019-04-03T10:26:03 Launching new EC2 (still want 2...)
2019-04-03T10:27:08 Lanching another (CPU alarm)

So, several things to unpack there:

* Seems our nodes don't always start up OK. Maybe this is a timing things still - I know @partouf experimented with different warm up times but I think we reverted them in the end. Filing a new bug #1338 to track this.
* A busy CPU event caused us to fire up more nodes. That's probably OK but the graphs above suggest we were 5xx-ing, and eventually the original node was killed due to ELB failure. Will use this bug to track that, and will dig in some more now.

**Comment by mattgodbolt** [comment]
CPU usage stats of the original node before it was killed (NB it has two CPUs so 50% represents a pegged CPU core).
![Screenshot from 2019-04-03 11-08-12](https://user-images.githubusercontent.com/633973/55467110-e1cfee00-5600-11e9-82d7-c9124b7fdde9.png)

**Comment by mattgodbolt** [comment]
Some `nginx` logs from one of the two nodes that was serving content before the issues happened:

```
Apr 03 03:20:50 ip-172-30-1-29 unified: info: 122.11.149.0 "POST /api/compiler/g83/compile" 200
Apr 03 03:20:53 ip-172-30-1-29 unified: info: 188.254.169.0 "POST /api/popularArguments/arm64g730" 200
Apr 03 03:21:18 ip-172-30-1-29 snapd: storehelpers.go:441: cannot refresh: snap has no updates available: "amazon-ssm-agent", "core"
Apr 03 03:21:18 ip-172-30-1-29 snapd: autorefresh.go:379: auto-refresh: all snaps are up-to-date
Apr 03 03:21:53 ip-172-30-1-29 all.err: 2019/04/03 08:21:53 [error] 7#7: *60956 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 216.137.58.14, server: , request: "POST /api/compiler/gsnapshot/compile HTTP/1.1", upstream: "http://172.17.0.3:10240/api/compiler/gsnapshot/compile", host: "godbolt.org"
Apr 03 03:21:54 ip-172-30-1-29 all.err: 2019/04/03 08:21:54 [error] 7#7: *60448 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 34.195.252.195, server: , request: "GET /dist/assets/cppinsights16.1363436f8d785a6dd51b89e20085af37.png HTTP/1.1", upstream: "http://172.17.0.3:10240/dist/assets/cppinsights16.1363436f8d785a6dd51b89e20085af37.png", host: "godbolt.org"
...

```

The other node (172.30.1.176) stopped at T10:25:55 with similar errors before it was killed:

```
Apr 03 03:21:51 ip-172-30-1-176 unified: info: 217.198.150.0 "POST /api/popularArguments/cclang700" 200
Apr 03 03:21:51 ip-172-30-1-176 unified: info: 217.198.150.0 "GET /" 200
Apr 03 03:22:52 ip-172-30-1-176 all.err: 2019/04/03 08:22:52 [error] 6#6: *60439 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 13.59.250.41, server: , request: "GET /api/asm/ChangePrivateI HTTP/1.1", upstream: "http://172.17.0.3:10240/api/asm/ChangePrivateI", host: "godbolt.org"
Apr 03 03:22:53 ip-172-30-1-176 all.err: 2019/04/03 08:22:53 [error] 6#6: *61097 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 35.167.191.152, server: , request: "GET /dist/assets/Google-Groups-20px.68f30c7dbd8e0235cf1c52bb2ae11736.png HTTP/1.1", upstream: "http://172.17.0.3:10240/dist/assets/Google-Groups-20px.68f30c7dbd8e0235cf1c52bb2ae11736.png", host: "godbolt.org"
```

Curious....

**Comment by mattgodbolt** [comment]
The 172.30.1.29 node was shut down at 03:24:46. I wonder if one or other was the spot instance? In which case both the prod node and the spot instance got whacked, possibly by the same type of compilation/request. Argh.

Both had just successfully processed `popularArguments`, but as we log out the request *after* we process this is likely to be the one-before-it-went-wrong.

The first noted nginx timeouts were for different things too, but there's no guarantee nginx will log these in any particular order. Mystery continues :/

**Comment by mattgodbolt** [comment]
possibly https://www.javascriptjanuary.com/blog/nodejs-postmortem-debugging-for-fun-and-production of use too (if we dump core on long queries)

**Comment by mattgodbolt** [comment]
Might be worth adding both watchdog timer and core handling, plus `--abort-on-uncaught-exception` too

**Comment by mattgodbolt** [comment]
Interestingly, I just fired up beta, and it was otherwise quiet but still:

```
Oct 22 20:07:02 ip-172-30-5-188 amazon.beta info: OPTIONS HASH: 6ac3188e4722a6b0dc77ed6eaf9466ad2f36c974347875ef6bf71a9c61e53899 
Oct 22 20:07:02 ip-172-30-5-188 amazon.beta info: Rescanning compilers every 3600 secs 
Oct 22 20:07:02 ip-172-30-5-188 amazon.beta info: ======================================= 
Oct 22 20:07:02 ip-172-30-5-188 amazon.beta info:   git release 62292fddafb220d65fba8e431a0b5255717b44f7 
Oct 22 20:07:02 ip-172-30-5-188 amazon.beta info:   serving static files from 'out/dist' 
Oct 22 20:07:02 ip-172-30-5-188 amazon.beta info:   Listening on http://localhost:10240/ 
Oct 22 20:07:02 ip-172-30-5-188 amazon.beta info:   Startup duration: 46343ms 
Oct 22 20:07:02 ip-172-30-5-188 amazon.beta info: ======================================= 
Oct 22 20:07:02 ip-172-30-5-188 amazon.beta warn: Event Loop Lag: 348.326556 ms 
Oct 22 20:07:03 ip-172-30-5-188 amazon.beta warn: Event Loop Lag: 223.490904 ms 
Oct 22 20:09:21 ip-172-30-5-188 amazon.beta warn: Event Loop Lag: 251.025888 ms 
```

**Comment by apmorton** [comment]
The two right after startup are pretty common - not sure what the one two minutes later is about.

**Comment by mattgodbolt** [comment]
Like you said in chat: it could be GCs. It was quiet for a while but we had another GC:

```
Oct 22 20:09:21 ip-172-30-5-188 amazon.beta warn: Event Loop Lag: 251.025888 ms 
Oct 22 20:11:42 ip-172-30-5-188 amazon.beta warn: Event Loop Lag: 494.903132 ms 
```

Who knows: but this wasn't query-of-death, at least this time.

**Comment by mattgodbolt** [comment]
May be unrelated but spotted this in the papertrail logs:

```
Jan 23 07:45:44 ip-172-30-0-235 amazon error: Event Loop Lag: 4839.530493 ms 
Jan 23 07:45:44 ip-172-30-0-235 amazon info: 2001:6a0:5001:1:529a:0:0:0 "GET /" 304 
Jan 23 07:45:44 ip-172-30-0-235 amazon info: 46.229.168.0 "GET /z/uFmZvC" 200 
Jan 23 07:45:44 ip-172-30-0-235 amazon info: Sandbox execution via firejail {"command":"/tmp/compiler-explorer-compiler120023-1661-16wu5zk.6l7o/output.s","args":[]} 
Jan 23 07:47:46 ip-172-30-0-235 amazon error: Event Loop Lag: 122167.876853 ms 
Jan 23 07:47:47 ip-172-30-0-235 amazon warn: Timeout for /usr/local/bin/firejail --quiet,--deterministic-exit-code,--terminate-orphans,--profile=etc/firejail/sandbox.profile,--private=/tmp/compiler-explorer-compiler120023-1661-16wu5zk.6l7o,--private-cwd,--env=LD_LIBRARY_PATH=/opt/compiler-explorer/gcc-9.2.0/lib:/opt/compiler-explorer/gcc-9.2.0/lib32:/opt/compiler-explorer/gcc-9.2.0/lib64,./output.s after 2000ms 
Jan 23 07:47:47 ip-172-30-0-235 amazon warn: Timeout for /usr/local/bin/firejail --quiet,--deterministic-exit-code,--terminate-orphans,--rlimit-cpu=22,--profile=etc/firejail/execute.profile,--private=/tmp/compiler-explorer-compiler120023-1661-1tyrqqa.ee3z,--private-cwd,/opt/compiler-explorer/gcc-snapshot/bin/g++,-g,-o,./output.s,-masm=intel,-S,-fdiagnostics-color=always,-O0,-std=c++17,./example.cpp after 20000ms 
Jan 23 07:47:47 ip-172-30-0-235 amazon warn: Timeout for /usr/local/bin/firejail --quiet,--deterministic-exit-code,--terminate-orphans,--rlimit-cpu=22,--profile=etc/firejail/execute.profile,--private=/tmp/compiler-explorer-compiler120023-1661-1tx1xt9.s76i,--private-cwd,/opt/compiler-explorer/clang-trunk/bin/clang++,-g,-o,./output.s,--gcc-toolchain=/opt/compiler-explorer/gcc-9.2.0,-fcolor-diagnostics,-fno-crash-diagnostics,-isystem/opt/compiler-explorer/libs/rangesv3/trunk/include,-isystem/opt/compiler-explorer/libs/fmt/trunk/include,-Wl,-rpath,/opt/compiler-explorer/clang-trunk/lib,-Wl,-rpath,/opt/compiler-explorer/clang-trunk/lib32,-Wl,-rpath,/opt/compiler-explorer/clang-trunk/lib64,-fcoroutines-ts,-stdlib=libc++,-std=c++17,-O2,./example.cpp after 20000ms 
```

**Comment by apmorton** [comment]
Dropping some observations here so they don't get lost in slack

https://sentry.io/share/issue/07e6279b84784895be768fb589fcb9c0/

https://upload.clinicjs.org/public/a58d8ae6c8e742fa6a47f0ddbc3553eac8fd9d348c84401536bb226e110518a5/4811.clinic-flame.html#selectedNode=1710&zoomedNode=&exclude=8fff-ffff-ffff-ffff-ffff-ffff-ffff-ffff-ffff-c000&merged=true

https://godbolt.org/z/37-yYh (this link is safe to click, it takes around 9 seconds to compile)
if you check the demangle tick box on that link (for the love of god don't do so on the live site) it will probably time out client side, but server side you will observe a ~45 second event loop lag.

The core of the problem is here: https://github.com/mattgodbolt/compiler-explorer/blob/master/lib/demangler.js#L172-L185

For sufficiently large inputs this loop takes an incredibly long time, meanwhile the event loop is blocked.

```
15039 lines, 1317 translations,  1270412914 ns
51287 lines, 3915 translations, 13461523641 ns
```

From the profiles above, the string replacements are the bulk of the runtime.

As a thought experiment I threw the following code above the loop in `processOutput` so I could time a theoretical alternative implementation based on a single large buffer, rather than working on an array of strings.

```javascript
// convert to buffers, but don't time it
// presumably the input would already be a buffer object (or at least a single string)
let text = Buffer.from(_.pluck(this.result.asm, 'text').join('\n'));
for (const translation of translations) {
    translation[0] = Buffer.from(translation[0]);
    translation[1] = Buffer.from(translation[1]);
}

var start = process.hrtime.bigint();
for (const [oldValue, newValue] of translations) {
    const outputBuffers = [];
    let outputBuffersTotalLength = 0;

    while (text.length > 0) {
        const idx = text.indexOf(oldValue);
        if (idx === -1) {
            outputBuffers.push(text);
            outputBuffersTotalLength += text.length;
            break;
        }

        // push the chunk before the match if there is one
        if (idx > 0) {
            const chunk = text.subarray(0, idx);
            outputBuffers.push(chunk);
            outputBuffersTotalLength += chunk.length;
        }

        // push the replacement value from the match
        outputBuffers.push(newValue);
        outputBuffersTotalLength += newValue.length;

        // seek past the end of the match in the input
        text = text.subarray(idx + oldValue.length);
    }

    // update buffers
    text = Buffer.concat(outputBuffers, outputBuffersTotalLength);
}
var end = process.hrtime.bigint();
logger.info(`${this.result.asm.length} lines, ${translations.length} translations, ${end - start} ns`);
```

```
before: 13461523641 ns
after:   4706955351 ns
```

This isn't a perfect comparison, but it does roughly the same thing (replace all occurrences of many input strings in a large buffer of text), and is several times faster.

There is still some room for improvement there, but even with a lot more optimization I don't think we will be able to get this down to a level acceptable to have it run synchronously on the main event loop thread.

The demangling stuff needs to happen in a worker thread, or an actual subprocess to fully mitigate these queries of death.

Also, I do think fundamentally we are running things somewhat out of order here. Maybe just due to historical reasons, or perhaps I am missing something fundamental, but I can't see any reason the demangling happens _after_ we process the asm into lines.

As far as I can tell it should be possible to demangle things first, and then parse out the asm - it would certainly cut down on the amount of string copying we end up doing.

**Comment by mattgodbolt** [comment]
Not scientific but apparent drop in errors of the form "Event Loop Lag:" ![Screenshot from 2020-02-05 07-30-14](https://user-images.githubusercontent.com/633973/73846090-86a2f500-47e9-11ea-887e-c91da147fa0f.png)

Deployment happened at 23:00 last night

**Comment by mattgodbolt** [comment]
We have some event loop lags still, but....

I'm closing this :tada: as it's not been half as bad as it used to!
