### ISSUE TITLE
Nodes don't always come up in time

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#1338]
In a recent bug (#1336) we noticed nodes don't always make it up before ELB kills them.

**Comment by apmorton** [comment]
I don't think we have seen this issue in a long time (although admittedly I don't know if anyone has been monitoring for it).

There have also been a lot of changes to our aws scaling configuration and instance startup since this was filed, so it probably doesn't apply anymore.
