### ISSUE TITLE
Add some kind of presentation mode

### ISSUE THREAD

**Issue by RubenRBS** [compiler-explorer/compiler-explorer#1350]
There is some stuff that cluters the view of the site that is probably not needed for presentations and such, which could be hidden away.
I have some ideas on mind that I'll try to implement over easter's break

**Comment by partouf** [comment]
I think last year we improved the embedding somewhat, and recently someone made extensions to reveal.js to send code to CE https://github.com/dvirtz/reveal-compiler-explorer
I know I've tried to make a presentation mode, but failed miserably - though did manage to use the code for mobile-view.

I'm sure there's plenty to do, but perhaps better to have a real-world example of a problem that needs fixing and fix that to achieve something like this.
