### ISSUE TITLE
MS MSVC compilers to support C

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#1371]
We're toying with removing the WINE compilers, and one notable missing feature on the windows compilers is their support for the C language.

See also #969 which added support for WINE C.

**Comment by AaronBallman** [comment]
You should be able to use the same MSVC as the C++ side, but pass the /Tc flag (or simply use a .c extension for the source file), no?

https://docs.microsoft.com/en-us/cpp/build/reference/tc-tp-tc-tp-specify-source-file-type?view=vs-2019

**Comment by mattgodbolt** [comment]
Thanks @AaronBallman - we will ping MS and see if they can add them to www.godbolt.ms -> paging @ubsan and @Rastaban

**Comment by mattgodbolt** [comment]
Paging @dan-shaw

**Comment by partouf** [comment]
Closed by PR, but is not yet live

**Comment by partouf** [comment]
now live!
