### ISSUE TITLE
Add Oracle Compiler

### ISSUE THREAD

**Issue by gsauthof** [compiler-explorer/compiler-explorer#141]
Another free (as in beer) available compiler is the Oracle C/C++ compiler (aka Oracle Developer Studio, previously Solaris Studio) is derived from the Sun compiler line, cf. https://en.wikipedia.org/wiki/Oracle_Developer_Studio .

Adding it to the GCC explorer would be convenient for comparison purposes.

Nowadays, the compiler is also available for Linux:

http://www.oracle.com/technetwork/server-storage/developerstudio/downloads/index.html

The license seems to be free-as-in-beer-ish:

```
Download Options for Oracle Developer Studio
Current Release - Oracle Developer Studio 12.5
Provides perpetual no-cost license for production use and the development of
commercial applications.
```

The IMHO most convenient install method is to use the provided tar files:

http://www.oracle.com/technetwork/server-storage/solarisstudio/downloads/solaris-studio-2333112.html

The x86 tar file is 445 MB big. An Oracle account  is needed for the download. The account is relatively easy to create - Mailinator throw away email addresses do work.

The install steps basically are:

```
$ sha256sum OracleDeveloperStudio12.5-linux-x86-bin.tar.bz2
0989078e1025cca88ac30324896c820eb9ea0fa6cc9554867a6c068585d47554
*OracleDeveloperStudio12.5-linux-x86-bin.tar.bz2
$ tar xf /mnt/ex/OracleDeveloperStudio12.5-linux-x86-bin.tar.bz2
$ # the install prefix doesn't matter much because libraries are reference
$ # relative to the $ORIGIN
$ mv OracleDeveloperStudio12.5-linux-x86-bin/developerstudio12.5/ /opt
$ # delete some GUIs
$ rm -rf /opt/developerstudio12.5/lib/netbeans/
$ # delete the Oracle DB 'instant' client - saves some hundreds MiB
$ rm -rf /opt/developerstudio12.5/OIC/
$ du -sh /opt/developerstudio12.5/
774M    /opt/developerstudio12.5/
```

First test:

```
$ cat hello.c
#include <stdio.h>

int main(int argc, char **argv)
{
  printf("Hello %s!\n", argv[1]);
  return 0;
}
$ /opt/developerstudio12.5/bin/cc hello.c
$ ./a.out foo
Hello foo!
```

The Oracle Studio C++ compiler (CC) uses a bundled GNU STL version - a small C++
test programs also compiles and works as expected.

```
$ /opt/developerstudio12.5/bin/CC hello.cc
$ ldd a.out
    linux-vdso.so.1 (0x00007ffdbe7d5000)
    libstdc++.so.6 => /opt/developerstudio12.5/lib/compilers/CC-gcc/lib/amd64/libstdc++.so.6 (0x00007fd600f4b000)
    libgcc_s.so.1 => /opt/developerstudio12.5/lib/compilers/CC-gcc/lib/amd64/libgcc_s.so.1 (0x00007fd600d33000)
    libCrunG3.so.1 => /opt/developerstudio12.5/lib/compilers/rtlibs/usr/lib/amd64/libCrunG3.so.1 (0x00007fd600b2c000)
    libm.so.6 => /lib64/libm.so.6 (0x00007fd60080f000)
    libc.so.6 => /lib64/libc.so.6 (0x00007fd60044d000)
    libstatomic.so.1 => /opt/developerstudio12.5/lib/compilers/atomic/amd64/libstatomic.so.1 (0x00007fd600246000)
    /lib64/ld-linux-x86-64.so.2 (0x0000556915425000)
```

**Comment by mattgodbolt** [comment]
Sounds great: if it supports GCC-like flags (like `clang` and `icc` do) it'll be a drop-in addition, else I'll have to do some work to drive it remotely.

**Comment by gsauthof** [comment]
Ok, the chances are good because since version 12 this compiler gets more and more GCC compatibility bits with each release (options, pragmas, builtins ...).

Btw, it probably doesn't hurt to define following environment variables when running the compiler:

    export UT_NO_USAGE_TRACKING=1
    export SUNW_NO_UPDATE_NOTIFY=1

The compiler forks/execs an update-checker binary on each run and those variables should reduce this  activity to a minimum.

**Comment by mattgodbolt** [comment]
Fantastic stuff: thanks for investigating. I'll take a look at adding this!

**Comment by mattgodbolt** [comment]
Hasn't gone as well as I'd hope.

The install is giant (1.6GB) and doesn't respond well to my usual trick of `strip` and/or `upx` ing. Not a dealbreaker but worth noting. As a comparison each GCC is ~100MB.

The assembly output is *very* different too:

```
{           }   .align 32,.simple_nop


/================================================================================
/ FUNCTION square(int)

/             %rbp - used as frame pointer.

/             arg0 "num":    %rdi,

square(int):

{           } .CG0.45:
{           }   push        %rbp


{           }   movq        %rsp,%rbp             

{           }   subq        $16,%rsp                
{           }   movl        %edi,-8(%rbp)         / sym=num
{           } .L1.39:.L1:
{           } .L2.40:.L2:
{           } .L4.41:.L4:
{        2  } .L5.42:.L5:
/ FILE /tmp/gcc-explorer-compiler116812-326-8dll7g/example.cpp

/    1            !// Type your code here, or load an example.
/    2            !int square(int num) {
/    3            !  return num * num;


{        3  }   leaq        -8(%rbp),%rdi         / sym=num
{        3  }   movl        -8(%rbp),%eax         / sym=num
{        3  }   imul        (%rdi),%eax       
{        3  }   movl        %eax,-4(%rbp)         / sym=return
...
Dlrodata.lrodata: / Offset 0
```

...which makes the output and parser a lot more tricky. I parse the output to filter out a lot of the junk generated. I'll have to update the parser appropriately (and possibly come up with another type of parser altogether).

Finally, when I try and output binary, CC complains that "wrong suffix"... apparently it is opinionated about what suffix the output has (!):

`CC: illegal suffix of output file: /tmp/gcc-explorer-compiler116812-691-11wwfog/output.s`

temporarily hacking around that gives the next problem, even with the `export UT_*` stuff you say above, it tried to access `/etc` and `/etc/hosts` (which are blocked by the security settings I run gcc explorer in)... I can probably allow that, in fairness. So, disabling the security, I get:

```CC: Warning: failed to detect system linker version, falling back to custom linker usage
/opt/gcc-explorer/OracleDeveloperStudio12.5-linux-x86-bin/developerstudio12.5/lib/compilers/amd64/ld: cannot find -lm```

and at this point I have stopped for now. Ideas welcomed, I'm sure this is all surmountable but it sadly isn't as straightforward as I would have hoped.

**Comment by mattgodbolt** [comment]
...and apologies I've just seen the stuff I can do to dramatically reduce the install size (netbeans etc). Will definitely help!

**Comment by gsauthof** [comment]
Yes, the assembler output looks funny.

But you can make it look less different via supplying `-Wu,-as_info=no`, e.g.:

    $ cat hello.c
    #include <stdio.h>
    int main(int argc, char **argv)
    {
      printf("Hello %s!\n", argv[1]);
      return 0;
    }
    $ /opt/developerstudio12.5/bin/cc hello.c -c -Wu,-as_info=no -S -o hello.s
    $ sed '/.cfi_gnu_args_size/Id' hello.s  -i
    $ sed 's/\(\.section .*\)h"/\1"/' -i hello.s
    $ as hello.s  -o hello.o
    $ gcc hello.o -o hello
    $ ./hello foo
    Hello foo!

I can reproduce the `/etc/hosts` access - but only with `CC`, not with `cc` - perhaps this is due to some IPC calls.

The `UT_NO_USAGE_TRACKING=1` environment setting has an effect - it prevents the spawning of the `check_update` executable, at least.

I can also confirm that `CC ... -o foo.s` errors out with this `illegal suffix` error - iff the `-S` option the omitted, as well.

Linking, when compiling a simple C++ program, works for me. Looking at the strace output I see that `CC` first calls `/usr/bin/ld --version`. And later, it calls `/usr/bin/ld` for real.

I am running Fedora 23 on this test system and `ld --version` prints the following:

    $ /usr/bin/ld --version
    GNU ld version 2.25-17.fc23
    Copyright (C) 2014 Free Software Foundation, Inc.
    This program is free software; you may redistribute it under the terms of
    the GNU General Public License version 3 or (at your option) a later version.
    This program has absolutely no warranty.

I can only speculate - perhaps you get this error because a) /usr/bin/ld can't be accessed or b) the compiler cannot parse the specific version string.

**Comment by mattgodbolt** [comment]
Being asked about this by some others now; so bumping this up my internal priority list. With the new code setup, putting any bespoke work into parsing the output should be easier (should it prove necessary after all).

**Comment by macxfadz** [comment]
Looking forward to have this compiler on "Compiler-Explorer".

**Comment by chusAB** [comment]
First of all, thank you very much for the Compiler Explorer service. It is a very powerful tool.
It would be great the Oracle C/C++ compiler support. It generates high quality code and gives nice reports. Its comparison with icc/gcc would be very interesting.

**Comment by mattgodbolt** [comment]
Thanks @chusAB . I'll see if I can find some time to resurrect this compiler.

**Comment by mattgodbolt** [comment]
I've really not had much time. I'd welcome someone else taking a look at this. We have some docs in the `docs/` directory that might help someone else finish the work here.

**Comment by mattgodbolt** [comment]
@chusAB / @gsauthof / @macxfadz  do any of you still want or need this compiler? I still haven't had time and so I'm looking for someone to champion this (with help from me and the rest of our team, of course).

**Comment by gsauthof** [comment]
Well, having the compiler available would still be interesting - e.g. to see how much better GCC/Clang codegen is. Probably a lot since the Oracle compiler probably hasn't changed much in the last years and thus doesn't implement the state of the art. But I'm not interested enough to champion this.

I don't really need it, since, thankfully, I don't have to deal with that compiler anymore, professionally.

Of course, Oracle compilers a pretty irrelevant nowadays, especially because the last Solaris users are busy migrating away from Solaris.

**Comment by mattgodbolt** [comment]
I'm going to close this: without a real champion for Oracle, plus the potential license issues, and the general feeling I have about Oracle...

Would happily take a patch to support it, but will not track it here any more.

**Comment by chusAB** [comment]
El 1/4/21 a las 21:37, Matt Godbolt escribió:
>
> I'm going to close this: without a real champion for Oracle, plus the 
> potential license issues, and the general feeling I have about Oracle...
>
> Would happily take a patch to support it, but will not track it here 
> any more.
>
Dear Matt

Completely agree.
As of today, I think it is of no interest to add this compiler.

Kind regards

-- 

**************************************************************
Jesús Alastruey Benedé - Profesor Contratado Doctor
http://webdiis.unizar.es/~chus/
Tel: +34 976 762339 fax: +34 976 761914
gaZ - Grupo de Arquitectura de Computadores
Dpto. de Informática e Ingeniería de Sistemas
EINA (Edificio Ada Byron) - Universidad de Zaragoza
***************************************************************
