### ISSUE TITLE
Add a MSVC (latest) moving compiler choice

### ISSUE THREAD

**Issue by ChopsII** [compiler-explorer/compiler-explorer#1413]
This is a suggested feature.
I use trunk for gcc and clang to use whatever the latest version is.
It'd be nice to have a moving "latest" release for MSVC too.

I suppose a "latest release" might be good for the other compilers as well, which is a little different to trunk.

**Comment by mattgodbolt** [comment]
Thanks for the suggestion. Microsoft are in charge of the list of MS compilers; we've been told to file issues on their tracker (e.g. https://developercommunity.visualstudio.com/idea/541911/library-support-for-compiler-explorer.html ) to get support here :)

(CC @ubsan @TartanLlama :)

**Comment by mattgodbolt** [comment]
CC @Rastaban too (sorry to keep mentioning you on this; we should perhaps have a better way to ask for these?)

**Comment by mattgodbolt** [comment]
Paging @dan-shaw

**Comment by Trass3r** [comment]
vote @ https://developercommunity.visualstudio.com/idea/710424/provide-preview-versions-on-compiler-explorer.html

**Comment by partouf** [comment]
this has been live for a while and is regularly updated
