### ISSUE TITLE
Demangling does not work in the Clang optimization report

### ISSUE THREAD

**Issue by TiborGY** [compiler-explorer/compiler-explorer#1433]
I think this speaks for itself: (not a rickroll I promise)
[https://imgur.com/a/LrUl0s5](https://imgur.com/a/LrUl0s5)

**Comment by partouf** [comment]
It would be extremely useful if you could share a short link of an example that shows this result

**Comment by TiborGY** [comment]
I tried to strip this down as much as possible, but if I remove any more code the issue disappears.
[](https://godbolt.org/z/v6Xt66)

**Comment by partouf** [comment]
This was I think fixed with the new demangling method implemented in 2019
