### ISSUE TITLE
Implement z88dk

### ISSUE THREAD

**Issue by luketrevorrow** [compiler-explorer/compiler-explorer#1474]
Having just seen the support for the 6502 processor, I would love to see similar for the Z80 family of CPUs - a classic in computing history, and featuring in the ZX Spectrum Next.

Any chance of getting something like [z88dk](https://github.com/z88dk/z88dk) included as a way of implementing Z80 support in the marvelous Compiler Explorer project?

**Comment by hippietrail** [comment]
There seem to be three C compilers that support Z80:

**SDCC** (Small Device C Compiler) supports a bunch of processors, including Z80.

**z88dk** apparently comes with two compilers. **sccz80**, which is just about C9 and doesn't optimize; and **zsdcc** which is an advanced fork of SDCC.

https://retrocomputing.stackexchange.com/questions/6095/why-do-c-to-z80-compilers-produce-poor-code/6108#6108

**Comment by partouf** [comment]
SDCC is now live

**Comment by partouf** [comment]
z88dk is now live
