### ISSUE TITLE
TBB not linking properly

### ISSUE THREAD

**Issue by allopislozano** [compiler-explorer/compiler-explorer#1475]
Looks like tbb is not linking properly

https://godbolt.org/z/KoJYGG

**Comment by apmorton** [comment]
Godbolt doesn't currently (and afaik has no plans to) support libraries that require linking for execution.

Header only libraries are supported for execution.

**Comment by allopislozano** [comment]
What's the point of having tbb then? It needs linking for the most basic
example

**Comment by apmorton** [comment]
If I had to guess, tbb was added at the request of a user. Quite a few of the libraries on godbolt require linking, and are thus not supported under execution.

Without linking the libraries are still useful for inspection of user code generation when using various library API's.

I'm sure you can imagine the absolutely insane support matrix that would arise from turning on linking support for all these libraries. Having to compile every library for every compiler (and in some cases probably multiple times per compiler to support things like LTO) would conservatively result in over 1000 build variants to maintain.

**Comment by mattgodbolt** [comment]
Yes, exactly this. People ask for libraries, we add them. We don't really question what people want them for! And until recently, no complaints about lack of linking as execution wasn't possible. It's _feasible_ some of the libraries might be made linkable-with, if the vendors ship precompiled libs (which might be the case with TBB? I'm not sure).

**Comment by kikaxa** [comment]
There seems to be an issue with c++ runtime due to this bug

```#include <execution>```

->

```
In file included from <source>:5:

In file included from /opt/compiler-explorer/gcc-9.2.0/lib/gcc/x86_64-linux-gnu/9.2.0/../../../../include/c++/9.2.0/execution:32:

In file included from /opt/compiler-explorer/gcc-9.2.0/lib/gcc/x86_64-linux-gnu/9.2.0/../../../../include/c++/9.2.0/pstl/glue_execution_defs.h:52:

In file included from /opt/compiler-explorer/gcc-9.2.0/lib/gcc/x86_64-linux-gnu/9.2.0/../../../../include/c++/9.2.0/pstl/algorithm_impl.h:25:

In file included from /opt/compiler-explorer/gcc-9.2.0/lib/gcc/x86_64-linux-gnu/9.2.0/../../../../include/c++/9.2.0/pstl/parallel_backend.h:14:

/opt/compiler-explorer/gcc-9.2.0/lib/gcc/x86_64-linux-gnu/9.2.0/../../../../include/c++/9.2.0/pstl/parallel_backend_tbb.h:19:10: fatal error: 'tbb/blocked_range.h' file not found

#include <tbb/blocked_range.h>

         ^~~~~~~~~~~~~~~~~~~~~

1 error generated.
```

**Comment by mattgodbolt** [comment]
@kikaxa :
> There seems to be an issue with c++ runtime due to this bug
> 
> `#include <execution>`
> [rest cut for brevity]

This seems to be unrelated to linking: can you file a separate bug with a short link demonstrating the issue you're seeing please? Thanks!

**Comment by partouf** [comment]
closing this as original issue is fixed due to support linking to tbb
