### ISSUE TITLE
[REQUEST] Incorporate Catch2 using its single header rather than its include directory

### ISSUE THREAD

**Issue by studoot** [compiler-explorer/compiler-explorer#1479]
**Is your feature request related to a problem? Please describe.**
[Catch2](https://github.com/catchorg/Catch2) is advertised as a 'header-only' library - which leads one to expect it to be usable within executable code on Compiler Explorer, using the 'a.out' option.

However, Compiler Explorer incorporates Catch2 using its `include` directory, which contains all the component header/source files that make up Catch2. These files are glued together with a Python script when a Catch2 release is built. Including Catch2 with 

```c++
#include <catch.hpp>
```

brings in all the declarations needed by Catch2, but not all the definitions. This leads to linker errors.

**Describe the solution you'd like**
Rather than Catch2's `include` directory, add the directory `single_include/catch2` to the include path. This directory contains the generated single-include version of Catch2. 

**Describe alternatives you've considered**
One workaround is to `#include` the 69 `.cpp` files that are part of Catch (see [this example](https://www.godbolt.org/z/VlW2dO)). That's not an easy list to remember, however :smirk:

**Comment by mattgodbolt** [comment]
Good spot: we should be able to update this as you suggest. ( e.g. this [example](https://www.godbolt.org/z/Hdq43r) should work when we use the single_include header).

As an aside, this is an interesting case: `Catch2` combined in one header with a main runner takes rather a long time to compile. Your example often times out during compilation (>30s), though once in file cache on the server it builds in 20s.

**Comment by studoot** [comment]
Yes, I did notice that - it made me realise that while Catch2 is header only, there's actually a lot less compiling done when neither of the `CATCH_CONFIG_RUNNER` or `CATCH_CONFIG_MAIN` macros are defined; that means that when you use it as [suggested in the documentation](https://github.com/catchorg/Catch2/blob/master/docs/tutorial.md#scaling-up), you're effectively compiling the majority of Catch2 into a single object file which you then link against your test case files, which have compiled a lot, lot less of Catch2.

**Comment by cor3ntin** [comment]
Any new on that ?

**Comment by partouf** [comment]
More information is available here https://github.com/mattgodbolt/compiler-explorer/pull/1535

But current status is: neither include styles will allow execution.

So as it stands we're stuck until we figure out an alternative solution.

**Comment by partouf** [comment]
Catch2 v3 can be linked against, this is now live. And considered the solution for this problem in the case of Compiler Explorer. (as multiple header-only variants could not be made to work with the website)
