### ISSUE TITLE
[REQUEST] Add compiler ARM64 gcc9.1

### ISSUE THREAD

**Issue by HardFour22** [compiler-explorer/compiler-explorer#1505]
This is probably already in the plans, but could you add support for ARM64 gcc9.1? That would be helpful for evaluating auto-vectorization for the scalable vector extensions (SVE).

**Comment by mattgodbolt** [comment]
This is still on the todo list but to see some of this you can pick the new ARM armclang++ compiler too.

**Comment by HardFour22** [comment]
Great, thanks for the heads up! armclang++ will work well for my purposes.

**Comment by Quuxplusone** [comment]
Could this issue be extended to "Support GCC trunk for the ARM64 target"?  We have `x86-64 gcc (trunk)` and `ARM64 gcc 8.2` but somehow no `ARM64 gcc (trunk)`.

**Comment by gquintin** [comment]
Is it possible to add GCC 10.2 ?
GCC <10 add support for SVE but do not provide intrinsics whereas GCC >= 10 also provide intrinsics via `#include <arm_sve.h>`

**Comment by Mistuke** [comment]
@mattgodbolt Arm provides cross compiler releases for GCC, could those be used to get GCC unstuck? https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads and https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads

**Comment by dkm** [comment]
I think this is now ok, with recent version of GCC being made avail for aarch64.
Closing this, but feel free to reopen if I'm wrong!
