### ISSUE TITLE
[REQUEST] Paste text from iPhone into compiler explorer

### ISSUE THREAD

**Issue by AraHaan** [compiler-explorer/compiler-explorer#1507]
**Is your feature request related to a problem? Please describe.**
It makes me mad when I copy some of my code into my iPhone’s clipboard and compiler explorer does not let me paste it because it is missing said option.

**Describe the solution you'd like**
A option to paste the stuff into the code editor.

**Describe alternatives you've considered**
Manually typing the ling stuff in which takes a long time (sometimes an hour for a 25 line function).

**Comment by RabsRincon** [comment]
Hi! As you might have noticed, our UI is not the best when used on a phone. We are sorry that you have had to endure it. We do take some small steps to try to make it less horrible where we can, but we are limited by the editor solution we use (Monaco Editor by Microsoft) which is itself not mobile friendly, and the layout system, which is not mobile friendly either.

This does not mean you should not be able to paste into the editor from a phone, so I'll take a look. It's not the first time we have reports about broken copy & paste functionality

Thanks for taking the time to open an issue :)

**Comment by RubenRBS** [comment]
3 years later, Monaco has not improved in this regard, and we are not able to path it in our side, so sadly I'm going to close this as `wont-fix`, and maybe _one day_, Microsoft adds this feature and we get it for free

**Comment by AraHaan** [comment]
Sad we cant link this issue to Microsoft so that way they know that their mobile layout needs work (and copy and paste).

**Comment by RubenRBS** [comment]
Oh they know, no worries!

Over on the monaco repo there are more than a few issues requesting this already, and have been for quite some time

It does not help that they explicitly list mobile view as a non-goal for the project :/

**Comment by AraHaan** [comment]
Seriously, they have standards for "accessibility" and yet mobile is not a goal for the project? That defeats the whole purpose of having accessibility standards.
