### ISSUE TITLE
[BUG] **Getting include errors when using very old versions of clang**

### ISSUE THREAD

**Issue by arnemertz** [compiler-explorer/compiler-explorer#1557]
**Describe the bug**
It seems that for very old clang versions (3.0.0 through 3.2) the installed STL is misconfigured or incomplete. It results in errors "/usr/lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/string:37:10: fatal error: 'bits/c++config.h' file not found"

**Expected behavior**
Compiles or gives compiler errors I can do something about.

**Link**
https://godbolt.org/z/lE0yL9

**Comment by arnemertz** [comment]
okay, seems to be a duplicate of that one.

**Comment by mattgodbolt** [comment]
Reopening as @valiko-ua points out that #1414 is just for execution. clang 3.0 doesn't compile anything at all even without execution: https://godbolt.org/z/PoUoZ6
