### ISSUE TITLE
[REQUEST] Build LLVM tools (at least trunk) with assertions enabled

### ISSUE THREAD

**Issue by danilaml** [compiler-explorer/compiler-explorer#1561]
LLVM tools have lots of useful debug info and checks that are only enabled when LLVM is build with assertions (or debug). Furthermore, in such mode LLVM tries to assign meaningful names to the IR variables/BBs making it much easier to understand what's going on.

**Describe the solution you'd like**
Provide LLVM binaries built with LLVM_ENABLE_ASSERTIONS=ON

**Additional context**

It'd be good to have this enabled at least for trunk build, since they are built from scratch anyway.

**Comment by partouf** [comment]
This is now live (for C/C++/LLVMIR/Analysis/ASM)
