### ISSUE TITLE
[REQUEST] Assembler support for ARM architecture.

### ISSUE THREAD

**Issue by ankushjqc** [compiler-explorer/compiler-explorer#1582]
Can'nt find ARM assembler in options to assemble code for arm target.
Request you to consider adding support for the same.

**Comment by mattgodbolt** [comment]
Worth tracking: https://github.com/google/EXEgesis which looks like it has some support for ARM.

**Comment by DavidSpickett** [comment]
@mattgodbolt I think this can be closed now that there is GNU as for Arm: https://godbolt.org/z/cYxvzjPh4

**Comment by dkm** [comment]
Thanks!
