### ISSUE TITLE
[REQUEST] Respect the system dark mode setting

### ISSUE THREAD

**Issue by porglezomp** [compiler-explorer/compiler-explorer#1627]
I went to godbolt in the middle of the night and found it extremely bright and started wondering if it could respect the system setting.

There is a CSS media feature `prefers-color-scheme` which indicates whether the user prefers light or dark mode. It might be nice to make the default dark mode if the user hasn't explicitly picked one yet be "System" and using the `prefers-color-scheme` setting to select how it should display.

This might be annoying for some people for it to switch to the system setting and become dark mode if they've never set it before, or it might be too hard with the current implementation to determine if it's been never set.
On the other hand, it might defeat the purpose if it's a non-default setting, since the majority of users don't frequently switch back and forth between light and dark mode.
On the other hand, maybe people don't care what it defaults to as long as they can set it to what they want.

**Comment by porglezomp** [comment]
I might be interested in implementing this if it's judged worthwhile-to-have.

**Comment by RabsRincon** [comment]
Hi! Thanks for taking the time to open this issue :)

Te behaviour you mention was at some point implemented, but I never got it to properly work (https://github.com/mattgodbolt/compiler-explorer/blob/master/static/settings.js#L149)

By all means, please feel free to fix my mess and implement it correctly! We'd love that. 
If you need any help while doing so, just ask away, and we'll be more than happy to help you out :)

**Comment by porglezomp** [comment]
I see that this dynamically updates page CSS—is there some reason that loading all the styles and selecting them with a selector causes trouble (for instance, making `.example` into `.theme-dark .example` and setting a global `.theme-dark`).

**Comment by apmorton** [comment]
I actually wondered the same thing myself last time I had to touch the theme CSS - I don't see a reason why each theme CSS couldn't just be entirely enclosed in

```css
body.theme-dark {
    <existing content here>
}
```

and then always loaded

**Comment by RabsRincon** [comment]
The answer is simple: I had little idea what I was doing back then (Not that I still do :P)

If anyone feels like changing it, please go ahead, it should not be too hard :)

**Comment by apmorton** [comment]
I'm going to close this, because it appears to work for me now - not sure what (if anything) changed?

If I clear my local storage and load godbolt.org on my machine it defaults to dark theme.
