### ISSUE TITLE
[REQUEST] CORS headers for POSTs

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#1659]
@FredTingaud of quick bench would like to be able to POST to the REST API to get a short URL to allow site<->site linking.

CORS headers current prevent him from doing this on the client side. 

**Describe the solution you'd like**
Enable CORS headers (after discussion about the implications).

**Describe alternatives you've considered**
POSTing from the server itself woudl work, but is more effort and I don't think it's a useful compromise.

**Additional context**

Helps #581 along

**Comment by partouf** [comment]
I guess this is needed for /shortener , but is doing shortener the smart thing here? or is it a conscious choice that users make to create a permalink of the sourcecode?

**Comment by FredTingaud** [comment]
Thanks @partouf .
I was wondering whether getting an URL from shortener or using GET clientstate with the full encoded state was the better solution.
Matt noted that there might be a limit to the size in the url, for clientstate, although it seems more of a theoretical problem at the moment.
If you think clientstate is better, I can definitely go with this one. I know that's what C++ Insight does.

**Comment by partouf** [comment]
I think it's mostly theoretical, I don't think CE explicitly has a limit set somewhere. But I don't know the statistics on this, really.

I'm looking at some of the errorcodes we're getting, maybe http status 413 might be related to this. It might be there's a limit of 4k bytes in POST's (compile and shortener) at least? The last error was monday, 2 days before that, 2 days before that. So I guess it does happen every few days.

So even if we allow it through CORS, there will still be limits it seems.

**Comment by partouf** [comment]
Cloudfront has a hard max length of an url of 8k, which also applies to /clientstate unfortunately, because the payload is part of the url instead of a request parameter.

**Comment by partouf** [comment]
I can't figure out where this 4k post limit is coming from

**Comment by partouf** [comment]
Let's reopen this when we can place this question in a context where it's needed
