### ISSUE TITLE
[BUG] Some ANSI codes crash the browser

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#1666]
Some ANSI sequences cause a hard hang in the client-side javascript.

**To Reproduce**
* head to https://godbolt.org/z/kfd0zJ
* replace the `draw_buffer` line with: `char const draw_buffer[] = "\033[38;5;999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999\"mTest";`
* Observe the window hangs

**Expected behavior**
We see a message (albeit with broken control codes)

**Comment by partouf** [comment]
Looks fixed, no idea when that happened.

**Comment by mattgodbolt** [comment]
Hmm, I was just able to repro it

**Comment by mattgodbolt** [comment]
(it crashes the browser as the ANSI code goes into an infinite loop)

**Comment by cpplearner** [comment]
It seems that the following regexp pattern can cause [catastrophic backtracking](https://javascript.info/regexp-catastrophic-backtracking):
https://github.com/compiler-explorer/compiler-explorer/blob/b3f50c875c80333e1e7f7f71b2a753202ee7032f/static/ansi-to-html.js#L418

Rewriting to something like `/^\x1b\[((?:\d{1,3};)*\d{1,3}|)m/` should probably fix this (note: untested).

**Comment by partouf** [comment]
Would like to point out that this script is in need of a refresh, but the original version on which we based this script seems no longer maintained.

(see https://github.com/compiler-explorer/compiler-explorer/issues/2315)

I'm not sure how to approach this situation. It might also be good to be able to unittest this despite this being a clientside script.

**Comment by mattgodbolt** [comment]
Absolutely, I'll take a look at something better. Thanks all.
