### ISSUE TITLE
[QUESTION] Should added compiler executables respect LD_LIBRARY_PATH?

### ISSUE THREAD

**Issue by wohlbier** [compiler-explorer/compiler-explorer#1678]
Hi, I added a compiler locally but it isn't working just yet. It appears that the compilers are being interrogated with `ldd`, and something is not finding what it needs. `LD_LIBRARY_PATH` indeed has and entry where the requirement resulting in the error would be satisfied, but compiler explorer does not appear to be looking in that path first. See below for output. Any advice? Thanks!

```
/local/devel/packages/emu-19.10/bin/clang: /lib64/libtinfo.so.5: no version information available (required by /local/devel/packages/emu-19.10/bin/clang)

/local/devel/packages/emu-19.10/bin/clang: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /local/devel/packages/emu-19.10/bin/clang)

/local/devel/packages/emu-19.10/bin/clang: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /local/devel/packages/emu-19.10/bin/clang)

Compiler returned: 1
```

**Comment by mattgodbolt** [comment]
Hi there!

When you run the compiler locally, do you get the same error? CE doesn't do anything clever with `ldd`, it just runs the compiler.

So, if you run:
```
$ /local/devel/packages/emu-19.10/bin/clang --version
```

What happens?

**Comment by mattgodbolt** [comment]
Worth saying, we _do_ keep `LD_LIBRARY_PATH` and `HOME` environment variables (as of e63645cda anyway).

**Comment by wohlbier** [comment]
It works locally, see below. When I add this compiler on Ubuntu it works fine, when I add it on RHEL it gives the failure.

Note that I load a compiler via module before running. Loading that module is what puts the glibc into `LD_LIBRARY_PATH`.

I will check my git hash to see if it at least as recent as the one you give.

```
(base) [jgwohlbier@lx-peppercorn compiler-explorer]$ module load gcc-9.1.0-gcc-9.1.0-kiftrt5 
(base) [jgwohlbier@lx-peppercorn compiler-explorer]$ /local/devel/packages/emu-19.10/bin/clang --version
/local/devel/packages/emu-19.10/bin/clang: /lib64/libtinfo.so.5: no version information available (required by /local/devel/packages/emu-19.10/bin/clang)
clang version 6.0.0 (git@github.com:emusolutions/clang.git 731d9298754020fd7b046a4a623dd27e6eecdb9c) (git@github.com:emusolutions/llvm.git 9e14d21723c5f5b4fd23bbd9d8dda0b1f44137a6)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/devel/packages/emu-19.10/bin
```

**Comment by wohlbier** [comment]
Indeed, my checkout is older than the one you reference. I will update and test it again next week.

**Comment by mattgodbolt** [comment]
Thanks, I'm not aware of any RHEL/Ubuntu differences that would matter here. I use Fedora at work with no issues, and Ubuntu at home and on the godbolt.org site.

**Comment by partouf** [comment]
A while back we broke LD_LIBRARY_PATH for local CE installations, but recently we fixed that again in https://github.com/compiler-explorer/compiler-explorer/commit/5687e01a6841dc9973ac57b9a38cdd89a9b7a64a

Hope you got things to work in the meanwhile, otherwise try the latest version of CE.
