### ISSUE TITLE
[REQUEST] An option in the UI to request latest dialect of the language (particularly C++)

### ISSUE THREAD

**Issue by AlisdairM** [compiler-explorer/compiler-explorer#1694]
I am often testing code snippets using the experimental support of different compilers for the pending C++ standard.  It is very simple to switch between different compilers, but the command line switch to select the latest dialect changes from compiler to compiler.

**Describe the solution you'd like**
It would be nice to have a simple checkbox for "C++Next" (this is the tersest meaningful label I could come up with) to automatically add to any command line that appropriate switch for the latest experimental language support in that compiler.  E.g., for Clang/Gcc this would be '-std=c++0x/1x/17/1z/2a' depending on vintage.  For MSVC, there is no switch for older compilers, and '/std:c++latest' will work for all compilers from MSVC 2017 onwards.  I don't know the recipe for the other compilers, and it may be that '-std=c++17' is the latest standard supported for Intel, for example?

**Describe alternatives you've considered**
Suggesting a broader UI feature to explicitly request the specific language dialect in a compiler independent manner.  I rejected this as needed too much screen real estate, and still not solving the problem of "latest" in a portable manner.  I similarly do not suggest adding experimental support for in-progress features that are not covered by the main 'std' switch (e.g., I believe experimental coroutines support is landed on gcc trunk, or is imminent, but will not immediately be part of the -std=c++2a switch - the -f flag to enable that should still be explicitly requested as a separate flag in this case).

**Additional context**
I am concerned about trying to get too deep into portable compiler options, as this is a natural scope creep - e.g., portable warning level coverage.  Not sure how best to design scope creep out of this request, but it is intended to NOT open that can of worms (or bugs?) if possible.

**Comment by sandorex** [comment]
It's a good feature, also to correct flags availability for MSVC
> The `/std:c++14` and `/std:c++latest` options are available beginning in Visual Studio 2015 Update 3

> The `/std:c++17` option is available beginning in Visual Studio 2017 version 15.3

[Source](https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=vs-2019)

**Comment by AlisdairM** [comment]
Updated suggestion: the Source pane has a drop-down for the selected language.  To avoid further UI clutter, simply add C++98/03/11/14/17/20/Next as different language dialects, that implicitly supply the appropriate command line arguments to select that dialect on the chosen compiler.  Retain the default 'C++' language option as simply giving the default language dialect (no option selected) for a given tool chain.  This also reflects real-world use.

Downside: the list of compilers may need to the maintained/filtered separately for each dialect.

The C and Python folks might be interested in a similar feature.

**Comment by jeremy-rifkin** [comment]
I think this can now be closed thanks to the compiler override button
