### ISSUE TITLE
[REQUEST] Frontend/UI testing.

### ISSUE THREAD

**Issue by porglezomp** [compiler-explorer/compiler-explorer#1723]
As I'm starting to work on doing some mobile UI changes, I was thinking that it would be nice to have some frontend/UI testing. I'm not particularly experienced in how this testing is done, so I don't have much to suggest here but wanted to open the conversation about it since I don't see an issue about it.

**Comment by mattgodbolt** [comment]
Agreed. In my experience frontend testing is very brittle, but would happily add it if we can find a decent way to do it.

**Comment by partouf** [comment]
We have implemented some basics for frontend unit testing using cypress, more about that here https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/internal/FrontendTesting.md
