### ISSUE TITLE
[REQUEST] Allow the user to define and include header files

### ISSUE THREAD

**Issue by akrzemi1** [compiler-explorer/compiler-explorer#1724]
**Is your feature request related to a problem? Please describe.**
I want to test a library on GitHub. It is  header-only, but composed of multiple headers, where one header includes another. thus including by URL will not work. So, for the purpose of testing, I have prepared my own single header that contains the entire library. But I have no place to put it. So I would like my Compiler-Explorer "worksheet" to also be able to contain additional header files. 

**Describe the solution you'd like**
I would like compiler explorer to allow me to define one cpp file (as today), and a number of header files whose names I would control; and then in the cpp file I would be able to #include by name the header files. Something that WandBox does: https://wandbox.org/permlink/T9pfkpSNhaJcXC2e

**Describe alternatives you've considered**
I do not know how to achieve this today other than copy pasting the contents of my headers directly into the single cpp file. I guess a more clever `#include <https://url>` that is able to include files recursively would also work.

**Additional context**

Suc thing works in WandBox: WandBox does: https://wandbox.org/permlink/T9pfkpSNhaJcXC2e

**Comment by partouf** [comment]
This can basically work by using the IDE mode and loading the zip file from the github library and adding your own code to it. So closing
