### ISSUE TITLE
[PROPOSAL] Collapse layouts to tab views on mobile

### ISSUE THREAD

**Issue by porglezomp** [compiler-explorer/compiler-explorer#1727]
## Concept

I think the most promising direction for having good mobile support in the short-term is using the tab layout more heavily, to save screen real-estate.
This can be handled more conveniently, but it would be nice to not have to manually rearrange the layout to tabs when you first look at a new screen.

To solve this, I would propose automatically collapsing arbitrary layouts down into a tab view.
There's a lot of variabilty for how this can be handled, and factors to be considered.

## When and how to collapse?

Should layouts be automatically collapsed down into the tab layout, or should there be a button to request this manually?
I think this is influenced somewhat by how layouts are expanded again.

- Should the collapsing be automatic or manual?
- If the collapsing to tabs is automatic, how should mobile devices be detected? Just screen dimensions, to match the navigation?
- If the collapsing to tabs is manual, should the button always be available, or should it only show on mobile? How should it be presented?
- Should collapsing only use tab layouts, or are there any other layouts that are usable on mobile that should be considered?

## Dealing with sharing and expanding

Because sharing embeds the layouts of the windows, sharing things created in the mobile tab view comes with some additional complexities.

- Should sharing be disabled in mobile view? This matches the "read-only" concept discussed elsewhere.
- If sharing is allowed, should it be shared with the tab layout embedded, or should it use an automatically expanded layout.
- When collapsing the layout, should the original layout be saved for expanding it back? This is particularly relevant if the collapsing is automatic, since you could accidentally collapse your layout while adjusting window sizes.
- If we expand the layout, what algorithm should this use? Predictability seem like an important criteria.

## Other considerations

Should anything be done to prevent rearranging the layout on mobile?
It seems like it might be more beneficial to continue to allow rearranging things, since you can't know better than the user what they want.

Does this design seem effective?
Is it a good engineering investment, if we want to replace it with a custom UI scheme that's specifically designed for mobile?
Does that mean that it's best to focus on the most minimal implementation that makes things better, if it will be replaced later?

Writing this, I think I advocate for a very minimal implementation:
- On mobile, display a button which lets you collapse the layout to tabs.
- Make no attempt to re-expand the layout.
- Don't prohibit sharing, and directly share the current layout.

What do you think? Is this a useful plan?

**Comment by mattgodbolt** [comment]
Thanks for filing this thoughtful bug and rundown of the options. 2020 is the year we want to improve mobile experience, so this is great.

**Comment by mattgodbolt** [comment]
Update on this: I'm going to be starting to take a look at this (and other mobile things) over the next few months. Thanks again for the ideas!

**Comment by partouf** [comment]
I don't think I ever read this issue before, but we implemented this mostly as suggested and this is now live.
So it would be great if you would have a look at the current situation and let us know what you think!

**Comment by porglezomp** [comment]
Sure looks like it lines up with what I specc'd here! It seems like some window configurations end up losing tabs, however? I tested with this layout and I end up with only one source tab and one assembly tab: https://godbolt.org/z/XVRMzE

**Comment by partouf** [comment]
> Sure looks like it lines up with what I specc'd here! It seems like some window configurations end up losing tabs, however? I tested with this layout and I end up with only one source tab and one assembly tab: https://godbolt.org/z/XVRMzE

So different sources, for clarity, are divided up into new pages, if you open the menu or hold the phone horizontal, you'll be able to go to the next source by clicking on the arrow buttons.

**Comment by mattgodbolt** [comment]
So excited this is live now. A long time coming, thanks @porglezomp and @partouf !
