### ISSUE TITLE
[BUG] Colorful problem

### ISSUE THREAD

**Issue by olafurw** [compiler-explorer/compiler-explorer#1728]
**Describe the bug**
![image](https://user-images.githubusercontent.com/103783/70580041-b9968700-1bb2-11ea-93ca-76a6d6dfea5a.png)

**To Reproduce**
Type
```cpp
#include <C++>
```

Get the rainbow effect, switch language.

**Expected behavior**
No rainbow.

**Comment by mattgodbolt** [comment]
This is a feature!!!1111!!! :grinning: 

I knew there'd be some bugs from this heheh! It's such a dreadful hack...
