### ISSUE TITLE
Rust crate recommendations

### ISSUE THREAD

**Issue by andy-thomason** [compiler-explorer/compiler-explorer#1731]
When performance testing Rust it would at least be a good idea to have the basic numeric traits
as well as the standard library in "libraries".

I would suggest:

The **num** crate which contains **num_traits** amongst other goodies (float conversion etc.)
**packed_simd** (only in nightly at the moment) tests the corners of **LLVM**
**ndarray** - **numpy**-alike for rust.

These are relatively pure libraries - although **ndarray** has optional parallel deps to **rayon** and friends.

**Comment by RubenRBS** [comment]
Hi! Sorry about our lack of communication on this and that you never got a proper response! We still have no support for crates 2 years later, but we're actively looking into adding it.

We're moving all the crate related issues over to the linked issue, so I'll close this in favour that one (But I have recorded your suggestions as not to lose them)
Thanks for your patience :)
