### ISSUE TITLE
[BUG] Incorrect demangling of some functions

### ISSUE THREAD

**Issue by Alcaro** [compiler-explorer/compiler-explorer#1732]
**Describe the bug**
If function a(int) calls function a(int,int), where the first one's mangled name (_Z1ai) is a prefix of the latter (_Z1aii), the latter is incorrectly demangled.

**To Reproduce**
```
void a(int, int);
void a(int b) { a(b, b); }
```

**Expected behavior**
```
a(int):
        mov     esi, edi
        jmp     a(int, int)
```

**Actual behavior**
```
a(int):
        mov     esi, edi
        jmp     a(int)i
```

**Link**
https://godbolt.org/z/rr3DWS
More elaborate/silly example: https://godbolt.org/z/V76aZQ

**Desktop (please complete the following information):**
 - OS: Lubuntu 18.04, x64
 - Browser: Firefox 71
 - Version [e.g. 22]: of what?

**Additional context**
If I'm reading the code correctly, bug is in [lib/demangler.js line 184](https://github.com/mattgodbolt/compiler-explorer/blob/master/lib/demangler.js#L184), and the proper fix would be finding or writing a words-only string replacement function.

The easy fix would be sorting `translations` by e.g. descending length before that loop. Won't fix the silly one, but it'll do the right thing for all realistic inputs. Your choice.

**Comment by mattgodbolt** [comment]
Thanks for the clear report, and for taking the time to look at the code!

**Comment by partouf** [comment]
This seems to be happening because the (int,int) symbol isn't in the assembly. Replacements do happen sorted by length, largest length symbol first, so if it was in the assembly, it would be replaced properly.

Not sure what to do about this situation. Maybe somehow add _Z1aii to the list of things to demangle despite it not being a label?

**Comment by partouf** [comment]
I just realized the symbol is probably there, but it's not sorted in the entire set, but appended sorted. 

https://github.com/mattgodbolt/compiler-explorer/blob/master/lib/demangler.js#L176

Not entirely remember why this was done. We can probably sort the entire set here.

**Comment by Noviv** [comment]
Hello! I was looking at this bug to pick it up, but it seems like the linked examples (https://godbolt.org/z/rr3DWS and  https://godbolt.org/z/V76aZQ) show `a(int, int)`, the expected behavior. I believe this issue can be closed, can you confirm @partouf?

**Comment by partouf** [comment]
Correct, thanks! @mattgodbolt accidentally fixed this by a rewrite of the demangling functions.
