### ISSUE TITLE
Add clang arm64 bit compiler support libraries

### ISSUE THREAD

**Issue by obfuscated** [compiler-explorer/compiler-explorer#174]
It will be useful to compare clang and GCC's code generators for arm 64bit code.

**Comment by nico** [comment]
FWIW you can already add a `-target` arg to the x86 clang to get arm64 output: https://godbolt.org/g/WJQWhe

**Comment by Ferdi265** [comment]
@nico: the `-target` hack doesn't work with C++ standard library includes though: https://godbolt.org/z/G7cb4P

**Comment by rengolin** [comment]
would be good to have at least these options for "arm clang":
- armv7a-linux-gnueabi (32-bits)
- armv8a-linux-gnueabi (32-bits)
- aarch64-linux-gnu (64 bits)

Thumb support (#1271) can be done, I suppose, by adding `-mthumb` and fiddling with `march/mcpu`.

This could be a wrapper for @nico's solution, but it would also have to know where the headers and libraries are, as per @Ferdi265's comment, which users don't.

**Comment by mattgodbolt** [comment]
See also #915

**Comment by apmorton** [comment]
This is fixed by #2262

https://godbolt.org/z/Yrff7G
