### ISSUE TITLE
[Object object] in the logs

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#1747]
```
amazon warn: Unable to find compiler for request body [object Object] with lang undefined 
```

and, perhaps separately just:

```
Dec 20 14:35:45 ip-172-30-4-97 compiler-explorer [object Object]
```

**Comment by partouf** [comment]
I think/assume this is no longer happening, I seem to remember another bugreport about this last year

**Comment by partouf** [comment]
Oh maybe not - https://github.com/compiler-explorer/compiler-explorer/issues/1931

**Comment by partouf** [comment]
but still closing in favor of newer issue
