### ISSUE TITLE
[BUG] [Rust] all monomorphisation of a given function demangle to the same name

### ISSUE THREAD

**Issue by robinmoussu** [compiler-explorer/compiler-explorer#1754]
**Describe the bug**

When a function is monomorphized in rust, the demangled name is the same for all demangled monomorphisation of that function. If someone wants to know witch monomorphised version is called where, it needs to look are the non-demangled assembly.

**To Reproduce**

If you look in the assembly, the function `sum_print_and_skip` can be found two times. It also looks like both `caller` and `caller2` calls the same function (they don't). If you untick the `demangle` option, you can see that the full name are different for both monomorphisation.

- Rust version with `impl Trait`: https://godbolt.org/z/hr5rTM
- Rust version with generic: https://rust.godbolt.org/z/r_Amag

**Expected behavior**

It should display the generic type in the demangled name, just like what is done in C++ with template: https://rust.godbolt.org/z/YahqGR

**Comment by robinmoussu** [comment]
Note: as bandage, it could be possible to just include the hash in the demangled name, like what the `--hash` option of [rustfilt](https://github.com/luser/rustfilt/blob/master/src/main.rs) does.

**Comment by RabsRincon** [comment]
For reference, this is code that handles Rust demangling https://github.com/mattgodbolt/compiler-explorer-tools/blob/master/rust/src/main.rs afaik

**Comment by robinmoussu** [comment]
I tried to understand how the current rust-ABI and mangling works. I think that currently there is not enough information in the mangled name, and the [RFC 2603](https://github.com/rust-lang/rust/issues/60705) is trying to solve that (among other issue). If it's the case, the best we can do until that RFC is accepted is to display the hash.

I also noticed that when using the nightly compiler with the option `-Zsymbol-mangling-version=v0`, the demangled names are correct: https://godbolt.org/z/bbYIux

**Comment by eddyb** [comment]
@robinmoussu The RFC was accepted, and implemented, with `-Zsymbol-mangling-version=v0` turning it on (although I regret not getting @michaelwoerister to replace `v2` with `v0` in the RFC title).

The new mangling will remain behind an unstable flag until we can finish upstreaming the demangler to GNU toolchain (which has taken me an *unreasonable* amount of time, despite the C implementation being ready since late January 2019 - it didn't help that this was my first contribution to a GNU project - most of the patches so far have tweaked the old demangler in several steps, to allow merging the two).

**Comment by eddyb** [comment]
I added the upstreaming effort status to https://github.com/rust-lang/rust/issues/60705, and I'll post updates as comments on there, so you can subscribe to it if you want to track my progress.

**Comment by RabsRincon** [comment]
Thanks for keeping us updated on the issue, we really appreciate it :)

**Comment by jeremy-rifkin** [comment]
Is there anything we can do on our end to move this forward?

**Comment by narpfel** [comment]
I tried to implement a solution to this in #6265: A checkbox that lets the user chose whether to show hashes or not.
