### ISSUE TITLE
[BUG] Vim mode not saved across sessions

### ISSUE THREAD

**Issue by mhammerc** [compiler-explorer/compiler-explorer#1757]
**Describe the bug**
Vim mode status (enable/disabled) is not saved across sessions, default to disabled.

**To Reproduce**
- Open Compiler Explorer
- Enable Vim mode
- Quit Compiler Explorer
- Open back Compiler explorer

**Expected behavior**
Vim mode should be enabled. I am almost sure it did in the past, sounds like a regression.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox and Safari

**Comment by RabsRincon** [comment]
Thanks for the report. Have you checked the checkbox on the settings popup under More > Settings in the Keybinding section? If I mark it, all editors get vim mode enabled by default

**Comment by mhammerc** [comment]
Yes! The checkbox in settings save it across sessions!
But not the button on top of the text editor.

**Comment by mattgodbolt** [comment]
Ah: so the `vim` mode is not kept as part of the state (else it would be persisted into URLs that you shared). We took this view as the editor keybindings are a personal preference not something we want to have persist onto others' machines.

I _think_ this is working as intended, though I'm willing to discuss further options if the settings doesn't cover your needs @mhammerc :)

**Comment by apmorton** [comment]
going to close, as I agree this is working as intended.

Perhaps the first time a user clicks the vim mode button in the editor menu they should be informed this is not persistent (and to change it in their settings if they want it to be), but: PR's welcome on that front.
