### ISSUE TITLE
[BUG] Disabled tweet link text is unreadable in Share menu

### ISSUE THREAD

**Issue by sivaraam** [compiler-explorer/compiler-explorer#1759]
### Describe the bug
In the share menu, the twitter and reddit share links are disabled when switching to "Embedded" mode. The color of the text used when they are disabled make it unreadable which is probably because of the lack of proper contrast with the background color of the text.

### To Reproduce
1. Visit https://godbolt.org
2. Click on the "Share" menu
3. Click on the "Embedded" option in the menu
4. Click on 'x' in the overlay menu
5. Click on the "Share" menu

### Expected behavior
The text "Twitter" and "Share on Reddit" should be readable even though they are disabled.

### Screenshots
**Readable share link text when enabled**
![image](https://user-images.githubusercontent.com/12448084/71627500-c558f480-2c18-11ea-84d0-14d7676cd748.png)

**Un-readable share link text when disabled**
![image](https://user-images.githubusercontent.com/12448084/71627484-abb7ad00-2c18-11ea-9c0a-1fe38969fa0a.png)

**Desktop (please complete the following information):**
 - OS: Lubuntu 18.04
 - Browser: Firefox
 - Version: 71.0

**Comment by RabsRincon** [comment]
@partouf why do the buttons get disabled in this case? I could not find the reason after checking the code

**Comment by partouf** [comment]
Embedded are no valid links, they can only be added in a html page?

**Comment by sivaraam** [comment]
It is right that sharing HTML embed code doesn't make sense. That said, as clicking on the "Embedded" (may be rename to just "Embed"?) button brings up an overlay with the HTML code, I think we can just show the embed code in the overlay alone instead of also showing it in the place of short/long URL when the "Share" button is clicked again. IOW, we could just treat the "Embedded" as a button which brings an overlay that shows the HTML code for the embed. And when the "Share" button is clicked after closing the overlay we just show the short/long URL. The embed code can accessed again by tapping on the "Embedded" button. This would avoid the need for disabling the share links.

**Comment by RubenRBS** [comment]
We have moved away from from this layout for a bit now so that this is no longer a problem, but never got around closing this issue, sorry!
