### ISSUE TITLE
Mobile experience is pretty dire

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#176]
Compiler Explorer is pretty much unusable on mobile browsers.

**Comment by mattgodbolt** [comment]
Also, since the latest update: "Recent changes to the compiler explorer seem to have made arrow keys and cmd-key cursor movement not work from iOS Safari" via twitter user @jckarter)

**Comment by mattgodbolt** [comment]
Suggestion from Slack: 

```
e.g.to display that on mobile you start by showing a list that says "C++ Source #1", "C++ Soruce #2", "x86-64 gcc 7.2 (Editor #2, Compiler #1)", etc.  then when the user clicks one you transition to a page that displays only the contents of that window

i mean, whether your framework supports that is a different story, but that's how i'd expect something like that to be displayed on mobile just in principle
```

(thanks Zachary Turner on slack for the thoughts).

**Comment by mattgodbolt** [comment]
See also #443

**Comment by mattgodbolt** [comment]
See also #641 and #443

**Comment by randomphrase** [comment]
Hi, just to confirm that cursor keys are still not working on safari/ios.

**Comment by mattgodbolt** [comment]
More thoughts (I see similar to those from Slack in 2017...) in this twitter thread: https://twitter.com/mcclure111/status/1162769112201879553

**Comment by porglezomp** [comment]
I think I have some incremental improvements that can be made by changing mobile styling (for bigger tap targets) and collapsing layouts to tabs. Would having incremental improvements like this be valuable, or is it better to leave it alone until a more complete solution can be developed?

**Comment by RabsRincon** [comment]
It would be super valuable! Anything anyone can do to help in this area is great

**Comment by mattgodbolt** [comment]
Great stuff. Thanks @porglezomp ! Any help appreciated, as I'm sure the full solution will include many improvements like this. Be aware that our editor, Monaco, doesn't support mobile and they don't plan to, so any issues specific to the editor may be a lost cause. Our plan to solve that is to switch it for a read-only view, but in the mean time any improvements to the rest of the UI are very welcome! :)

**Comment by partouf** [comment]
I declare this issue closed!

**Comment by mattgodbolt** [comment]
Agreed! @partouf yay!!
