### ISSUE TITLE
[BUG] boost takes a while to rsync at startup

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#1771]
Although we bake boost into the images, newer versions of boost still `rsync` at image start. Trying to use them before things are ready leads to errors.

See: mattgodbolt/compiler-explorer-image#207

**Comment by apmorton** [comment]
Currently `/opt/compiler-explorer/libs/boost.tar.xz` needs to be manually updated whenever a new boost version is installed and then a new packer image created.

I cobbled that whole thing together manually and given the frequency of updates to boost I chose not to give it more thought at the time - maybe its time to revisit things.

At the very least I will throw a comment in `install_libraries.sh` as a warning

**Comment by apmorton** [comment]
I think this is largely a "solved issue" now that the boost.tar.xz creation is scripted and we are in the habit of creating a new AMI when boost is updated.
