### ISSUE TITLE
Filename should be consistent for a saved source

### ISSUE THREAD

**Issue by benwitman** [compiler-explorer/compiler-explorer#1787]
There are compilers that name/output things dependent on the source file names.  It looks like MSVC's lambda names are changing in this way so I believe the file names change each time it compiles.  If they stayed the same upon refresh (or across computers/people) then it can more deterministic and cause less confusion?

**Comment by mattgodbolt** [comment]
We don't have much control about what the compilers do I'm afraid. Do you know of any way to make MSVC's lambda names consistent?

**Comment by mattgodbolt** [comment]
Ah: I misread - do you mean the temporary generated filename of the source? (which should be `example.cpp` each time?) Is there some path component (we use a temporary directory each time, though for WINE-based compilers I can't vouch for how that works).  Ideally if you have a URL you can show to demonstrate the issue that would be great.
