### ISSUE TITLE
Support FLANG fortran compiler (LLVM 10)

### ISSUE THREAD

**Issue by Diazonium** [compiler-explorer/compiler-explorer#1793]
There will finally be an official Fortran compiler that uses LLVM, coming with LLVM 10.
https://www.phoronix.com/scan.php?page=news_item&px=LLVM-10.0-FLANG-Next-Week
Note that this is not the old FLANG project that has been floating around for a while, but a project previously called "f18" getting renamed and merged as FLANG.

**Comment by Diazonium** [comment]
Merge delayed:
https://www.phoronix.com/scan.php?page=news_item&px=Flang-Fortran-Landing-Delayed

**Comment by Diazonium** [comment]
It looks like F18 got merged into the LLVM trunk, and will be coming out with LLVM 11. It is not finished yet, especially from the library side, but code generation should probably be fine.

**Comment by partouf** [comment]
It seems this fork is still active https://github.com/flang-compiler/f18-llvm-project - and it's partially merged in the llvm repo?

So (until new llvm release) what would be preferred, to have a llvm flang trunk build from llvm/llvm or from f18-llvm-project ?

**Comment by Sameeranjoshi** [comment]
Hi thanks for the detailed discussion on this.
Let me clear a bit.
There are 2 places of the project.
1. Llvm-project - This is the merged flang project
The compiler here doesn't produce LLVM IR, but the parsing and semantic analysis are almost done.
It also supports openmp constructs as well.

The f18-llvm-project link above and specifically fir-dev branch in it is the one which does the next part from semantic analysis till LLVM IR.
It generates FIR(an MLIR dialect) some constructs are still WIP.
Using some tools in the same branch we can generate LLVM IR from the FIR.

So the later branch is somewhat of interest as it can help to generate FIR and this can help to do some high level optimization analysis.
The fir-dev branch pulls in changes from llvm-project so the semantic and parsing are present here with FIR generation.

So I think if the second branch could be built as experimental target that would be great. 
The plan is the code from fir-dev branch would be in parts merged into llvm-project.

See issue
[REQUEST] **Support FIR generation for the new fortran frontend(flang) in llvm** #2050
For some more details.

**Comment by partouf** [comment]
To build this branch, do we require additional buildparameters like we do here for example -> https://github.com/compiler-explorer/clang-builder/blob/master/build/build.sh#L64 and if so, do you know what they are?

**Comment by Sameeranjoshi** [comment]
Yes you need mlir along with flang as a dependency also cpp17 if something
fails incase.

The build process is similar the way we have any intree project in
llvm-project.

Thanks.
If you need any more details please let me know.

**Comment by Sameeranjoshi** [comment]
@partouf are the details sufficient are are you facing any blockers?

**Comment by partouf** [comment]
I am facing the blocker of time. But, yes, I think this is enough information for someone to make this happen.

If you or someone else has the time, feel free to send PRs.

The basic parts of making this happen:
* Add an extra version in https://github.com/compiler-explorer/clang-builder/blob/master/build/build.sh
* Call to build the extra version https://github.com/compiler-explorer/infra/blob/master/admin-daily-builds.sh
* Enable downloading of the newly built version https://github.com/compiler-explorer/infra/blob/master/bin/yaml/cpp.yaml#L344
* Enable the compilers in CE https://github.com/compiler-explorer/compiler-explorer/blob/master/etc/config/fortran.amazon.properties

Testing these things are a bit harder to do, but if someone sends us a PR we can pick it up and test it.

**Comment by Sameeranjoshi** [comment]
@partouf I have a friend @Joshi-Tejas(https://github.com/Joshi-Tejas)  who is interested to work on it.
We need some help here, he is facing a problem of processing power on his laptop, as the branch is a clone of LLVM, so do have to build everytime the llvm? Is there a way we can get these artifacts/link to the binaries of compiler on servers where these compilers are running.

**Comment by Joshi-Tejas** [comment]
@partouf Hello. I am currently playing with the CE code locally and will surely ask if any query for the task. Let me correct @Sameeranjoshi here, what I meant is I have limited internet resources right now to clone llvm-flang repos, I'll manage that somehow. But servers are helpful for sure :)

**Comment by Sameeranjoshi** [comment]
I have pushed in  some PR's in `infra` `clang-builder` and `CE` this would be the basic support for LLVM flang, but there is still a lot to do for the other branch which has FIR and codegen in it.
Thanks @partouf for suggestions.

**Comment by partouf** [comment]
> I have pushed in some PR's in `infra` `clang-builder` and `CE` this would be the basic support for LLVM flang, but there is still a lot to do for the other branch which has FIR and codegen in it.
> Thanks @partouf for suggestions.

PR's are looking good, thanks!

Will have a look later if this builds alright and get back to you.

**Comment by partouf** [comment]
The build returns an error;

https://godbolt.org/admin/builds.html

```
FAILED: tools/flang/lib/Evaluate/CMakeFiles/obj.FortranEvaluate.dir/tools.cpp.o 
/usr/bin/c++  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/flang/lib/Evaluate -I/root/llvm-project/flang/lib/Evaluate -I/root/llvm-project/flang/include -Itools/flang/include -Iinclude -I/root/llvm-project/llvm/include -isystem /root/llvm-project/llvm/../mlir/include -isystem tools/mlir/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -Werror -Wno-deprecated-copy -fno-strict-aliasing -fno-semantic-interposition -O3 -DNDEBUG    -fno-exceptions -fno-rtti -std=c++1z -MD -MT tools/flang/lib/Evaluate/CMakeFiles/obj.FortranEvaluate.dir/tools.cpp.o -MF tools/flang/lib/Evaluate/CMakeFiles/obj.FortranEvaluate.dir/tools.cpp.o.d -o tools/flang/lib/Evaluate/CMakeFiles/obj.FortranEvaluate.dir/tools.cpp.o -c /root/llvm-project/flang/lib/Evaluate/tools.cpp
c++: internal compiler error: Killed (program cc1plus)
```

**Comment by Sameeranjoshi** [comment]
Looks like a ICE in gcc version 7.
```
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
```
Can you please upgrade the gcc here, the supported versions are 
```
gcc= 7.2.0 to 9.3.0.
clang = clang version 7.0, 8.0, 9.0 and 10.0
```
https://github.com/llvm/llvm-project/tree/master/flang#supported-c-compilers

**Comment by partouf** [comment]
hmm, we're using this dockerfile and gcc https://github.com/compiler-explorer/clang-builder/blob/master/Dockerfile
I think that should be gcc 7.5.0

**Comment by Sameeranjoshi** [comment]
Pushed gcc-7 version changes.

**Comment by Sameeranjoshi** [comment]
Does below PR look fine @partouf ?
https://github.com/compiler-explorer/clang-builder/commit/020ff4c097856f7aa076311557d0a31bee8b4171

**Comment by partouf** [comment]
> Does below PR look fine @partouf ?
> [compiler-explorer/clang-builder@020ff4c](https://github.com/compiler-explorer/clang-builder/commit/020ff4c097856f7aa076311557d0a31bee8b4171)

I don't know the implications of this change, maybe @apmorton or @mattgodbolt knows

This is the current GCC version running in the docker container:
```
ubuntu@ip-172-30-5-209 ~> sudo docker exec -ti clang_llvmflang.build gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
```

**Comment by mattgodbolt** [comment]
Thanks for the ping @partouf . I'll take a look at the PR on clang building. My guess is the change is OK though (and we can always find out the "hard way" :)

**Comment by mattgodbolt** [comment]
@Sameeranjoshi :
> Does below PR look fine
> [compiler-explorer/clang-builder@020ff4c](https://github.com/compiler-explorer/clang-builder/commit/020ff4c097856f7aa076311557d0a31bee8b4171)

I don't see this as a PR, and it doesn't seem to be merged (I'm actually a bit confused as to where this change has come from! :)) -- it should be ok to bump us to gcc-7 if you want to open a PR.

**Comment by Sameeranjoshi** [comment]
@partouf @mattgodbolt thanks for reviews.
@mattgodbolt I missed to push to review. 
The PR comes from the older [PR](https://github.com/Sameeranjoshi/clang-builder/commit/b051643be4f1fa2aebf9ffd5941591b9ba68ff9d) merged in the rational to support #2066  and we started seeing [ICE](https://github.com/compiler-explorer/compiler-explorer/issues/1793#issuecomment-654802574) when building with older gcc versions.

**Comment by partouf** [comment]
I'm a bit confused though for what it would do, because we already have gcc 7.5.0. What's the difference?

**Comment by partouf** [comment]
Not sure if this is related, but I built the same thing on a different docker container with extra debugging info, and an error occurs somewhere else:

```
[1236/4753] Building CXX object lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/EnumTables.cpp.o
FAILED: lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/EnumTables.cpp.o 
/usr/bin/c++  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/DebugInfo/CodeView -I/root/llvm-project/llvm/lib/DebugInfo/CodeView -Iinclude -I/root/llvm-project/llvm/include -v -save-temps -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG    -fno-exceptions -fno-rtti -std=c++14 -MD -MT lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/EnumTables.cpp.o -MF lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/EnumTables.cpp.o.d -o lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/EnumTables.cpp.o -c /root/llvm-project/llvm/lib/DebugInfo/CodeView/EnumTables.cpp
Using built-in specs.
COLLECT_GCC=/usr/bin/c++
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-D' 'GTEST_HAS_RTTI=0' '-D' '_GNU_SOURCE' '-D' '__STDC_CONSTANT_MACROS' '-D' '__STDC_FORMAT_MACROS' '-D' '__STDC_LIMIT_MACROS' '-I' 'lib/DebugInfo/CodeView' '-I' '/root/llvm-project/llvm/lib/DebugInfo/CodeView' '-I' 'include' '-I' '/root/llvm-project/llvm/include' '-v' '-save-temps' '-fPIC' '-fvisibility-inlines-hidden' '-Werror=date-time' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wwrite-strings' '-Wcast-qual' '-Wno-missing-field-initializers' '-Wpedantic' '-Wno-long-long' '-Wimplicit-fallthrough=3' '-Wno-maybe-uninitialized' '-Wno-noexcept-type' '-Wdelete-non-virtual-dtor' '-Wno-comment' '-ffunction-sections' '-fdata-sections' '-O3' '-D' 'NDEBUG' '-fno-exceptions' '-fno-rtti' '-std=c++14' '-MD' '-MT' 'lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/EnumTables.cpp.o' '-MF' 'lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/EnumTables.cpp.o.d' '-o' 'lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/EnumTables.cpp.o' '-c' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/7/cc1plus -E -quiet -v -I lib/DebugInfo/CodeView -I /root/llvm-project/llvm/lib/DebugInfo/CodeView -I include -I /root/llvm-project/llvm/include -imultiarch x86_64-linux-gnu -MD lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/EnumTables.cpp.d -MF lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/EnumTables.cpp.o.d -MT lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/EnumTables.cpp.o -D_GNU_SOURCE -D GTEST_HAS_RTTI=0 -D _GNU_SOURCE -D __STDC_CONSTANT_MACROS -D __STDC_FORMAT_MACROS -D __STDC_LIMIT_MACROS -D NDEBUG /root/llvm-project/llvm/lib/DebugInfo/CodeView/EnumTables.cpp -mtune=generic -march=x86-64 -std=c++14 -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wpedantic -Wno-long-long -Wimplicit-fallthrough=3 -Wno-maybe-uninitialized -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color=always -fPIC -fvisibility-inlines-hidden -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -O3 -fpch-preprocess -fstack-protector-strong -Wformat-security -o EnumTables.ii
ignoring duplicate directory "/usr/include/x86_64-linux-gnu/c++/7"
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/7/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 lib/DebugInfo/CodeView
 /root/llvm-project/llvm/lib/DebugInfo/CodeView
 include
 /root/llvm-project/llvm/include
 /usr/include/c++/7
 /usr/include/x86_64-linux-gnu/c++/7
 /usr/include/c++/7/backward
 /usr/lib/gcc/x86_64-linux-gnu/7/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-D' 'GTEST_HAS_RTTI=0' '-D' '_GNU_SOURCE' '-D' '__STDC_CONSTANT_MACROS' '-D' '__STDC_FORMAT_MACROS' '-D' '__STDC_LIMIT_MACROS' '-I' 'lib/DebugInfo/CodeView' '-I' '/root/llvm-project/llvm/lib/DebugInfo/CodeView' '-I' 'include' '-I' '/root/llvm-project/llvm/include' '-v' '-save-temps' '-fPIC' '-fvisibility-inlines-hidden' '-Werror=date-time' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wwrite-strings' '-Wcast-qual' '-Wno-missing-field-initializers' '-Wpedantic' '-Wno-long-long' '-Wimplicit-fallthrough=3' '-Wno-maybe-uninitialized' '-Wno-noexcept-type' '-Wdelete-non-virtual-dtor' '-Wno-comment' '-ffunction-sections' '-fdata-sections' '-O3' '-D' 'NDEBUG' '-fno-exceptions' '-fno-rtti' '-std=c++14' '-MD' '-MT' 'lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/EnumTables.cpp.o' '-MF' 'lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/EnumTables.cpp.o.d' '-o' 'lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/EnumTables.cpp.o' '-c' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/7/cc1plus -fpreprocessed EnumTables.ii -quiet -dumpbase EnumTables.cpp -mtune=generic -march=x86-64 -auxbase-strip lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/EnumTables.cpp.o -O3 -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wpedantic -Wno-long-long -Wimplicit-fallthrough=3 -Wno-maybe-uninitialized -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -std=c++14 -version -fdiagnostics-color=always -fPIC -fvisibility-inlines-hidden -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fstack-protector-strong -Wformat-security -o EnumTables.s
GNU C++14 (Ubuntu 7.5.0-3ubuntu1~18.04) version 7.5.0 (x86_64-linux-gnu)
	compiled by GNU C version 7.5.0, GMP version 6.1.2, MPFR version 4.0.1, MPC version 1.1.0, isl version isl-0.19-GMP

GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
GNU C++14 (Ubuntu 7.5.0-3ubuntu1~18.04) version 7.5.0 (x86_64-linux-gnu)
	compiled by GNU C version 7.5.0, GMP version 6.1.2, MPFR version 4.0.1, MPC version 1.1.0, isl version isl-0.19-GMP

GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: 3eb3dc290cd5714c3e1c3ae751116f07
COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-D' 'GTEST_HAS_RTTI=0' '-D' '_GNU_SOURCE' '-D' '__STDC_CONSTANT_MACROS' '-D' '__STDC_FORMAT_MACROS' '-D' '__STDC_LIMIT_MACROS' '-I' 'lib/DebugInfo/CodeView' '-I' '/root/llvm-project/llvm/lib/DebugInfo/CodeView' '-I' 'include' '-I' '/root/llvm-project/llvm/include' '-v' '-save-temps' '-fPIC' '-fvisibility-inlines-hidden' '-Werror=date-time' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wwrite-strings' '-Wcast-qual' '-Wno-missing-field-initializers' '-Wpedantic' '-Wno-long-long' '-Wimplicit-fallthrough=3' '-Wno-maybe-uninitialized' '-Wno-noexcept-type' '-Wdelete-non-virtual-dtor' '-Wno-comment' '-ffunction-sections' '-fdata-sections' '-O3' '-D' 'NDEBUG' '-fno-exceptions' '-fno-rtti' '-std=c++14' '-MD' '-MT' 'lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/EnumTables.cpp.o' '-MF' 'lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/EnumTables.cpp.o.d' '-o' 'lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/EnumTables.cpp.o' '-c' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 as -v -I lib/DebugInfo/CodeView -I /root/llvm-project/llvm/lib/DebugInfo/CodeView -I include -I /root/llvm-project/llvm/include --64 -o lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/EnumTables.cpp.o EnumTables.s
GNU assembler version 2.30 (x86_64-linux-gnu) using BFD version (GNU Binutils for Ubuntu) 2.30
EnumTables.s: Assembler messages:
EnumTables.s:1: Error: invalid character '"' in mnemonic
```

Considering (even though this is llvm trunk) nothing has changed since 2019 in this file, I'm not sure what's going on here.

I'm going to retry with gcc-8

And if that fails I'll try to downgrade the binutils maybe?

**Comment by partouf** [comment]
I tried it with gcc-8, which seemed to be fine, up until we got linking errors.

Would be good to know if anyone could check it actually compiles for them on their system.

**Comment by Sameeranjoshi** [comment]
Any updates on this?
Did anyone get this working?

**Comment by partouf** [comment]
I retried the docker image 2 times today and it failed at something. Currently retrying without docker and with just running cmake and make (no ninja) on revision e32469a140374737ad0ece395d5b52444bd94cd1 (commits are pouring in these few days so its hard to figure out whats what) - and it's taking For-Ever to build (I guess ninja is faster?).

Llvm plain master and no projects enabled is fine, that I can say.

Maybe it's something to do with the amount of work that it needs to do, but then again it might just be a faulty commit that hasn't been tested with the mlir+flang.. Will let you know as soon as it finishes building to 100%.. which might be in about 8 hours..

**Comment by Sameeranjoshi** [comment]
8 hours why does it take so long? I could build on a normal 16 cores ryzen in 20minutes.

**Comment by partouf** [comment]
I don't think make does multicore.. I'll restart with ninja I guess

**Comment by partouf** [comment]
Ok so with ninja it failed again (1436/4151) at some AARCH64 thing, which in and about that area the docker environment has been failing as well.

So I don't think there's much to do for me.

This issue is on hold until someone makes a stable tag or branch or this. Let us know. I'm open to all of this, but not as long as there is so much volatility in building it.

**Comment by Sameeranjoshi** [comment]
Can you point me what the bug is exactly?
When building on local machine I use below commands.
```
cmake -GNinja -DCMAKE_BUILD_TYPE=Debug  -DLLVM_TARGETS_TO_BUILD=host -DLLVM_INSTALL_UTILS=on -DLLVM_ENABLE_PROJECTS="mlir;flang" -DCMAKE_CXX_STANDARD=17 ../llvm/
```

**Comment by partouf** [comment]
"mlir;flang" is not what you sent as a PR, it included Clang

**Comment by partouf** [comment]
We (@apmorton mostly) are currently working on something that involves expanding the working memory for the compiler, which might result in a better build. No guarantees, all exotic earlier attempts have failed.

**Comment by partouf** [comment]
Spoiler alert, @apmorton has solved this problem by expanding memory swapping magic on the builder instance. As requested in slack, @Sameeranjoshi can you confirm 'clang' can be removed from the enabled projects? (to alleviate a bit of compilation time)

**Comment by Sameeranjoshi** [comment]
Yes it's ok to remove `clang`, may be if that was a `debug` build and given 4 bug projects(llvm,clang,mlir,flang) to build might have consumed lots of memory.
Thanks @apmorton and @partouf for debugging this.
I hope to see `flang` soon on `godbolt.org.`

**Comment by partouf** [comment]
Having a couple issues with testing flang.

It's installed, seems to be fine.

Problem 1; flang only has +x on root (0700), I changed it to 0766 and then that seemed to be ok

Problem 2; default square example with -v gives:

```
pgf90 -g -S -v -Mbackslash -c -o example.o /tmp/f18-b.f90
execvp(pgf90) failed: Permission denied
Compiler returned: 1
```

Where can I find pgf90? (or what is supposed to be happening here instead?)

**Comment by partouf** [comment]
This is now live on the website. Thanks everyone for the help!

It's configured with -fparse-only  - should this situation change, please submit a PR and we'll happily change it. We applied it here -> https://github.com/compiler-explorer/compiler-explorer/blob/master/etc/config/fortran.amazon.properties#L125
