### ISSUE TITLE
Default args restrict NASM usage

### ISSUE THREAD

**Issue by khakionion** [compiler-explorer/compiler-explorer#1804]
I want to do assembly for Mach-O 64, but I cannot change the default args to NASM, which specify “-F stabs”.  That is not compatible with “-f macho64.” Specifying the -f option overrides the default ELF option, but there is no way to override the “-F stabs” option when targeting Mach-O 64.
![6A4973D6-3C23-4621-9BFF-FC864A0C2C23](https://user-images.githubusercontent.com/277155/72974878-2c7e5900-3e13-11ea-93ff-ab6ed46cacd6.jpeg)

**Comment by partouf** [comment]
This is now live in the form of: if you don't supply any `-f ...` parameter, the default is `-g -f elf -F stabs` - otherwise you're in control of the options
