### ISSUE TITLE
[REQUEST] Add support for GCC C66x architecture

### ISSUE THREAD

**Issue by hlandau** [compiler-explorer/compiler-explorer#1806]
GCC includes support for the TI TMS320C66x DSP architecture. Adding this to the list of compilers would be nice.

https://gcc.gnu.org/onlinedocs/gcc/C6X-Options.html

**Comment by mattgodbolt** [comment]
GCC includes support when it's cross-compiled for this. Anyone interested in this should take a look at  https://github.com/compiler-explorer/gcc-cross-builder and https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/AddingACompiler.md for some hints.

**Comment by dkm** [comment]
I'll give it a try!

**Comment by dkm** [comment]
I have a working C/C++ bare config working, will push that in the coming days

**Comment by dkm** [comment]
Compiler build: https://github.com/compiler-explorer/infra/actions/runs/3405903425

**Comment by dkm** [comment]
Compiler correctly built, should be installed shortly :)

**Comment by partouf** [comment]
this is now live
