### ISSUE TITLE
[BUG] Boost fails for Windows Compiler

### ISSUE THREAD

**Issue by kunaltyagi** [compiler-explorer/compiler-explorer#1816]
**Describe the bug**
```
C:/data/libraries/installed/x64-windows/include\boost/config.hpp(30): fatal error C1083: Cannot open include file: 'boost/config/user.hpp': No such file or directory
```

**To Reproduce**
https://www.godbolt.ms/z/lNv2EB

Same error on main site as well as ms specific site

**Comment by partouf** [comment]
Can you make the example and share the link from the main site? The MS side doesn't retain links.

**Comment by kunaltyagi** [comment]
https://godbolt.org/z/ni5o_K

This should do the trick 😄 

> The MS side doesn't retain links.

That's weird.

**Comment by mattgodbolt** [comment]
Thanks for this. We aren't directly responsible for either the godbolt.ms site itself, or the API service we use. Calling on @strega-nil for any comments.

**Comment by RabsRincon** [comment]
Also note that the MS site not retaining links is the expected behaviour here :)

**Comment by strega-nil** [comment]
We generally expect people to use https://godbolt.org; godbolt.ms is a simple API endpoint, and therefore there's no reason to store links.

**Comment by mattgodbolt** [comment]
Makes perfect sense, thanks @strega-nil :)

**Comment by mattgodbolt** [comment]
@strega-nil any thoughts on the original issue (https://godbolt.org/z/ni5o_K) - fails with:

```

x64 msvc v19.16 (Editor #1, Compiler #1) C++
x64 msvc v19.16
Compiler options...
1
<Compilation failed>
x64 msvc v19.16 - 10671ms
#1 with x64 msvc v19.16
example.cpp

C:/data/libraries/installed/x64-windows/include\boost/config.hpp(30): fatal error C1083: Cannot open include file: 'boost/config/user.hpp': No such file or directory

Compiler returned: 2
```

**Comment by strega-nil** [comment]
@mattgodbolt ooh, that's weird. Lemme check it out

**Comment by mattgodbolt** [comment]
Not wishing to be a nag, assigning you for now @strega-nil but of course if you can't get to this let us know and we'll look for someone else :)

**Comment by mloskot** [comment]
The original MWE from https://github.com/mattgodbolt/compiler-explorer/issues/1816#issuecomment-582972911 can be simplified to just https://godbolt.org/z/4Y3Z8f

```cpp
#include <boost/config.hpp>
int main () { return 0; }
```
throwing 
```
C:/data/libraries/installed/x64-windows/include\boost/config.hpp(30): 
   fatal error C1083: Cannot open include file: 'boost/config/user.hpp': No such file or directory
```

Interestingly, I'm only observing this on the `x64 msvc v19.NN` while on `x86 msvc v19.NN` it compiles just fine.

**Comment by partouf** [comment]
This seems fixed
