### ISSUE TITLE
[REQUEST] Add XTensa compiler to live website

### ISSUE THREAD

**Issue by maxgerhardt** [compiler-explorer/compiler-explorer#1817]
I'd be great to add the GCC compilers for the ESP8266 and ESP32 microcontroller platforms, both of which are based on the XTensa architecture (dual core Xtensa LX6 and Xtensa L106 respectively), to the website. 

I've read https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/AddingACompiler.md and think I'd be an easy task to add another GCC version locally, but I'm sure you guys can do that way more efficiently than me 😅. 

The compiler can be obtained by using crosstool-ng (https://github.com/espressif/crosstool-NG), or see [Linux release](https://docs.espressif.com/projects/esp-idf/en/release-v3.0/get-started/linux-setup.html#toolchain-setup) and [Windows release](https://docs.espressif.com/projects/esp-idf/en/release-v3.0/get-started/windows-setup-scratch.html#alternative-setup-just-download-a-toolchain). For ESP8266 see https://github.com/SuperHouse/esp-open-rtos#quick-start.

**Comment by JosuGZ** [comment]
I would also like to see this!

**Comment by CelliesProjects** [comment]
Agreed, would be really nice to compare generated XTensa asm.

You can compare through the terminal as explained in the YT videos for ESP. 
On Linux Mint you can use this script to produce asm. Just open a c++ snippet with it and it will show the asm
`-O2` on line 4 sets the optimization level.

```bash
#!/bin/bash
output="$(mktemp /tmp/profile.XXXXXX)"
~/Arduino/hardware/espressif/esp32/tools/xtensa-esp32-elf/bin/xtensa-esp32-elf-c++ \
$1 -O2 -c -S -o $output
grep -v "	\." $output
rm -f $output
```

```c++
void test(int i) {
  i++;
}
```
This will produce:
```asm
_Z4testi:
.LFB0:
	entry	sp, 32
.LCFI0:
	retw.n
.LFE0:
```

And

```c++
float sqr(float f) {
  return f * f;
}
```
Produces:
```asm
.LFB0:
	entry	sp, 32
.LCFI0:
	wfr	f0, a2
	mul.s	f0, f0, f0
	rfr	a2, f0
	retw.n
.LFE0:

```

**Comment by partouf** [comment]
Several of these compilers are now live for c++
