### ISSUE TITLE
[REQUEST] C++ / Circle compiler

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#1845]
**Is your feature request related to a problem? Please describe.**
Circle seems to be a C++-like language and compiler.
https://www.circle-lang.org/
https://github.com/seanbaxter/circle
https://cppcast.com/circle-language/

**Describe the solution you'd like**
Add Circle as a C++ compiler (as long as it keeps being compatible with C++, I guess?)

**Describe alternatives you've considered**
Add a new Circle language?

**Additional context**
Doesn't seem to be based on Clang or GCC, but uses GCC's libstdc++ and LD.

**Comment by partouf** [comment]
I believe (it's been a while) this compiler requires a newer glibc version to be able to run (and the compiler source is not open, so we can't compile it ourselves). Maybe possible when we have upgraded Ubuntu https://github.com/compiler-explorer/infra/issues/376

**Comment by partouf** [comment]
Since Ubuntu 20 is on the instances now, maybe we can get this to work now

**Comment by mattgodbolt** [comment]
Good idea! Should be easy to do....exactly as you've noted in the project. Also I guess pinging @seanbaxter as a headsup :)

**Comment by mattgodbolt** [comment]
Looks like it can be installed from a tarball, and then run pretty easily. Looking for a Circle volunteer to drive this forward!

* https://github.com/compiler-explorer/compiler-explorer/blob/master/docs/AddingALanguage.md and
* https://github.com/compiler-explorer/compiler-explorer/blob/master/docs/AddingACompiler.md

Anyone interested, please let me know, and I can help. Feel free to join us on the [Discord channel](https://discord.gg/B5WacA7) to chat more too
