### ISSUE TITLE
Handle cross compilation in clang

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#185]
Can specify `--target` but it doesn't like `--gcc-toolchain`. https://godbolt.org/g/emWpGe for example.

Would be great to have libstdc+ too so ARM etc could use it (doesn't want to use gcc)

**Comment by partouf** [comment]
Considering we've had separately configured clang compilers for other architectures, I suggest we let this one rest unless we discover more need for this.
