### ISSUE TITLE
[BUG] Graph viewer slowly drifts to top left

### ISSUE THREAD

**Issue by the-emerald** [compiler-explorer/compiler-explorer#1855]
**Describe the bug**
When the graph viewer is left alone for a while, the graph slowly drifts to the top left.

**To Reproduce**
1. Open up a Graph Viewer for any compiler output
2. Wait. The graph will slowly drift to the top left corner

**Expected behavior**
It should stay in the same place.

**Link**
If applicable, please provide a link to Compiler Explorer to help explain your problem.

**Screenshots**
![Peek 2020-02-24 19-26](https://user-images.githubusercontent.com/12746683/75184233-fac31f80-573b-11ea-8449-b9bb161fe3f6.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version 73.0

**Additional context**

**Comment by mattgodbolt** [comment]
Interesting one: thanks! @cppchedy I know you're super busy at the moment, but any thoughts?

**Comment by cppchedy** [comment]
@mattgodbolt sorry for the late reply, I only saw the github notification(email) now.
@the-emerald  I couldn't  reproduce it  on my machine, maybe I am missing something?
I am using firefox 73.0.1 on fedora 31.

I checked for changes of version, but from what I saw it appears that there were no upgrades to vis.js. Also, looked at the cfg network configuration and compared it to previous state, nothings seems suspicious. 

I think most likely that  it has to do with the library it self, not with something we have control over.

As can be seen from https://github.com/visjs/vis-network/releases, the libraries is now actively maintained and many bugs are being fixed. @the-emerald feel free to open an issue.

**Comment by apmorton** [comment]
Not directly related to this bug, but since you are here...

I looked at the vis library not too long ago when bumping other dependencies. It seems the project is under new management and has restructured into a collection of smaller libraries.

Have you used the newer versions? Do you think upgrading would be painful?

**Comment by cppchedy** [comment]
@apmorton the last time I used vis.js was for compiler explorer cfg feature so my knowledge is pretty old. but reading through the release I spot many breaking change but I am not certain how (or if it affects) the way we are handling it.

>Do you think upgrading would be painful?
if they changed the way nodes and edges are encoded, yes I think it will be painfull.

**Comment by the-emerald** [comment]
@cppchedy cheers. For some reason I couldn't reproduce it again either. Something's up. If you'd like I can open an issue in vis-network as well?

**Comment by cppchedy** [comment]
@the-emerald yes that will be awesome. please note that we are using version 4.20 of vis.js.
