### ISSUE TITLE
[BUG] Python "execution only" mode errors

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#1859]
**Describe the bug**
While you can't elect to execute a python pane (the `11010` button), you _can_ open an "execute only". This has surprising results.

**To Reproduce**
* https://godbolt.org/z/SvzZGS

**Expected behavior**
Maybe either disable the "add exec only" or support python :)

**Link**
https://godbolt.org/z/SvzZGS

**Comment by partouf** [comment]
Has been fixed now to not show the compilers that we don't support execution on. In the case of python here, no compilers will be selectable, and it won't try either.

If there are still links out there for other languages it will show the selected compiler, but will usually result in a message like 'Compiler did not produce executable' or something similar.
