### ISSUE TITLE
[REQUEST] Show how to include or use library

### ISSUE THREAD

**Issue by olafurw** [compiler-explorer/compiler-explorer#1876]
When adding a library to CE, you pick from a dropdown the library and then what?

![image](https://user-images.githubusercontent.com/103783/76000839-91de6300-5f04-11ea-9e1f-0d1825b1162c.png)

What is the include path?
Do I need any compile arguments?
Even something simple as an icon you can hover over to see hints on what you have to do.

Cheers!
<3

**Comment by partouf** [comment]
Except that you don't need to do anything...

**Comment by apmorton** [comment]
I've had the thought for a while that it would be nice if adding a library chucked the `#include <whatever>` at the top of the source file for you in cases where it makes sense.

For libraries that aren't so simple, just adding a commonly used (and hopefully lightweight - we don't want to `#include` the entirety of boost for example) header from the library would be a nice starting point.

**Comment by olafurw** [comment]
> Except that you don't need to do anything...

What do you mean? You need the include.

![image](https://user-images.githubusercontent.com/103783/76004404-b852cd00-5f09-11ea-8cfa-33d8012222e7.png)

With some libraries, sure, this might be easy. But is it fmt/fmt.h? fmt.h? I don't want to have to remember for every single library.

**Comment by partouf** [comment]
In the spirit of this, maybe we should have examples per library usage. Would be quite the UI challenge. Not sure how to. Similarly readme's for libraries usually don't include what you should #include before being able to use the specific library functions for the example.

Maybe a 'showcase' feature for libraries that offers shortlinks to library usage examples?

**Comment by olafurw** [comment]
Yes, I think something as small as a link to an example would be perfectly good. You can read up on the documentation of the library somewhere else, but something to "kickstart" you here would be nice.

**Comment by partouf** [comment]
With the new library selection window, we may have addressed this issue, at least for some of the libraries. Have a look and see if it's to your liking.

For fmt for example we added the examples that they now also provide in their readme:
![image](https://user-images.githubusercontent.com/442630/94875080-f8ecd780-0453-11eb-8541-99772116d8b2.png)

**Comment by olafurw** [comment]
Brilliant!
