### ISSUE TITLE
[REQUEST] Providing interactive editing mode

### ISSUE THREAD

**Issue by neckutrek** [compiler-explorer/compiler-explorer#1888]
I'd like to share a URL with people that brings up an interactive editable version of compiler explorer to anyone who accesses the URL. That way I could reason about stuff with colleagues remotely, or with strangers from freenode etc.

It would be good to be able to share with others an interactive URL where anyone who accesses it can edit the same session, and also an read-only URL to let others peek in on coding in real time but not be able to alter anything. Good for remote live coding with many spectators.

**Comment by mattgodbolt** [comment]
It's a great idea and has been brought up a number of times. It's a potentially big thing - we would need to support interactive communications between server and client (websockets probably), then ensure that our load balancing supports it (which it wouldn't right now). Then of course there's a big deal of how to handle the privacy considerations, and the editor experience...it's a big job :) Just think how many engineers Google must have working on their shared word processor.

I love the idea, but it's a big one :)  Having one main session and many occasionally updating read-only views could be a step in this direction, but even that's a big ask (backing storage, sharing state across load balanced nodes etc).

**Comment by RubenRBS** [comment]
Closing in favour of #173
