### ISSUE TITLE
Add itoa crate for Rust

### ISSUE THREAD

**Issue by 95th** [compiler-explorer/compiler-explorer#1904]
I was looking into some integer to ascii conversion comparisons in Rust. 
It would be helpful if the `itoa` crate was added was available.

**Comment by mattgodbolt** [comment]
We don't have any crates yet, we don't have the infrastructure as yet! Thanks for this idea: we welcome someone with Rust experience able to help.

**Comment by alex** [comment]
Cross-referencing to #1925

**Comment by RubenRBS** [comment]
Hi! Sorry about the lack of updates on this. We're moving all the crate stuff to the linked issue (Where I have recorded the crate suggestion here as to not to lose it), so I'll close this issue in favour of that one.

Also, thanks for initially taking the time to open up a request for the crate :)
