### ISSUE TITLE
[BUG] ctre library can run us out of virtual memory space

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#1905]
**Describe the bug**
Running complex regexes can run us out of virtual memory.

**To Reproduce**
Hit the link and see the error

**Expected behavior**
For "fairly complex" regexes, it should probably still work.

**Link**
https://godbolt.org/z/Tcz39Q

**Comment by partouf** [comment]
This seems to be working for gcc, did we change anything about this?

**Comment by mattgodbolt** [comment]
Hmm. You're not wrong! I don't think we did but if we can't repro it... will close.

**Comment by apmorton** [comment]
This still fails for me on GCC 10.2 - it seems GCC trunk just got more efficient
https://godbolt.org/z/Gev71r

**Comment by mattgodbolt** [comment]
Oh nice! Caught out by our own "trunk" behaviour! :P Thanks for re-checking.

**Comment by partouf** [comment]
I think this is fine
