### ISSUE TITLE
[REQUEST] "favourite" compilers options

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#1917]
Having a way to "pin" favourite compilers to put them at the top of the dropdown would be super useful to many people. Requested from a Patron; I wonder if we can torture `selectize` into helping us here.

**Comment by partouf** [comment]
I believe this has been requested a couple of times before. The UI part is the hardest part, not sure whats a good way of doing it.

**Comment by mattgodbolt** [comment]
See also #142

**Comment by oyejorge** [comment]
I have an idea for this. I'll make some change and post back when I have something to show.
