### ISSUE TITLE
[BUG] Hedley not showing in MSVC compiles

### ISSUE THREAD

**Issue by travisdowns** [compiler-explorer/compiler-explorer#1976]
Hedley (added in #1807) very much supports MSVC: in fact cross-compiler portability is the reason it exists: but it doesn't show in MSVC build. E.g., if you go here it doesn't show in the list:

https://godbolt.org/z/3VLeF9

cc @nemequ

**Comment by mattgodbolt** [comment]
CC @strega-nil - what's the best way to get libraries into the MS site? Thanks!

**Comment by timmy-ms** [comment]
Added and will be deployed Friday.
