### ISSUE TITLE
[REQUEST] Allow user to input the specific tab size, instead of only predefined values

### ISSUE THREAD

**Issue by 7keo** [compiler-explorer/compiler-explorer#1977]
**It would be nice to be able to use any arbitrary tab size.**
Currently, in the settings one can only choose from a list three given values, 2, 4, and 8.

**Suggestion: make it so that the list of values also allows input like a text box.**
for example: tab size 3, 7, 1, 6, or any other value the user desires, etc.

**Comment by RabsRincon** [comment]
Hi! Thanks for the suggestion. I've implemented the changes so it should be live once the page gets updated in the next few days :)

**Comment by 7keo** [comment]
Works like a charm, thanks!
