### ISSUE TITLE
[REQUEST] Option to specify an external theme via url

### ISSUE THREAD

**Issue by 7keo** [compiler-explorer/compiler-explorer#1978]
**Suggested change:**
Under settings, where the user is able to choose between the Default and Dark theme, also allow the user to input a url where an external theme to be loaded is defined.

**Comment by jeremy-rifkin** [comment]
I don't think this is something we can really support at the moment. The work required to implement a CE theme is substantial (see https://github.com/compiler-explorer/compiler-explorer/pull/4916), however maybe in the future it'll be more possible.
