### ISSUE TITLE
[BUG] some version numbers parsed as float

### ISSUE THREAD

**Issue by vcabbage** [compiler-explorer/compiler-explorer#1980]
**Describe the bug**
Versions in properties files that have a trailing zero in the minor component and no patch component are parsed as floats, resulting in an incorrect version.

Examples:
https://github.com/compiler-explorer/compiler-explorer/blob/df27a15b575a0d93332724583b9a6c43cde07d95/etc/config/c%2B%2B.amazon.properties#L972
https://github.com/compiler-explorer/compiler-explorer/blob/df27a15b575a0d93332724583b9a6c43cde07d95/etc/config/c%2B%2B.amazon.properties#L1025
https://github.com/compiler-explorer/compiler-explorer/blob/df27a15b575a0d93332724583b9a6c43cde07d95/etc/config/c%2B%2B.amazon.properties#L1224
https://github.com/compiler-explorer/compiler-explorer/blob/df27a15b575a0d93332724583b9a6c43cde07d95/etc/config/c%2B%2B.amazon.properties#L1224
https://github.com/compiler-explorer/compiler-explorer/blob/df27a15b575a0d93332724583b9a6c43cde07d95/etc/config/go.amazon.properties#L46

**To Reproduce**
Visible in UI. Example showing Go 1.10 mislabeled as 1.1.

![image](https://user-images.githubusercontent.com/10789027/82154073-6f2fcb00-9820-11ea-9532-93adf192a177.png)

**Expected behavior**
Versions should retain trailing zeros.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: firefox
 - Version: 76.0.1

**Additional context**

Possible option to avoid this would be to change
https://github.com/compiler-explorer/compiler-explorer/blob/df27a15b575a0d93332724583b9a6c43cde07d95/lib/utils.js#L205
to
```js
if (prop.match(/^-?[0-9]*\.[0-9]+[^0]$/)) return parseFloat(prop);
```
so that it does not match numbers with a trailing zero. This may result in missing some numbers that should be parsed as floats. In my limited testing I didn't find any properties other than versions being excluded.

**Comment by partouf** [comment]
There's code to handle semvers, but I think the code where it gets parsed first   https://github.com/compiler-explorer/compiler-explorer/blob/f5c199a196f41f221485f1256046f0f2c298926e/lib/properties.js#L71 it can't know all the ins and outs about that I guess.

I don't think there's any floats really, but I'm not sure we want that a trailing zero to be the factor in that.

Maybe a hack that checks the keyname if its version or semver could work, but it won't be pretty either.
