### ISSUE TITLE
[REQUEST] Show a compressed tab if there are more than 1 tab but no space to show them.

### ISSUE THREAD

**Issue by olafurw** [compiler-explorer/compiler-explorer#1984]
**Is your feature request related to a problem? Please describe.**
In this link, there are actually 2 compilers, but you don't notice them because the space to show 2 tabs isn't big enough.

Here's a screenshot as well.

![image](https://user-images.githubusercontent.com/103783/82230164-a6d76980-992b-11ea-88ef-c4b6b85a7805.png)
(not enough space, 2nd tab not shown)

![image](https://user-images.githubusercontent.com/103783/82230215-b951a300-992b-11ea-9c9e-e8fd36caa02f.png)
(enough space, 2nd tab shown)

**Describe the solution you'd like**
Here's a beautiful mockup.

![image](https://user-images.githubusercontent.com/103783/82230334-e43bf700-992b-11ea-9dcd-34833d5bc42a.png)

Where it would just indicate that there are more tabs but no space to show them, and when you click on that [...] thing, you'd swap to the next tab and the [...] thing would appear on the left side.

Just a thought. Have fun out there!

**Comment by partouf** [comment]
I've been very confused about this in the past as well. The indicator for this is the little down arrow, but it's quite annoying either way. Considering this is all controlled by GoldenLayout, I'm not sure if and how much we can change about this.

**Comment by olafurw** [comment]
Ahh, I thought the down arrow was to minimize the thing. Yeah then you can just close this sucker :)
