### ISSUE TITLE
[BUG] Clang 10 for ARM does not have <atomic> header

### ISSUE THREAD

**Issue by ilyapopov** [compiler-explorer/compiler-explorer#1986]
**Describe the bug**
Including `<atomic>` header produces an error message with Clang 10.0.0 on ARM-v7 and ARM-v8a

**Link**
https://www.godbolt.org/z/6Bi2Wg

**Comment by RabsRincon** [comment]
Hi! Sorry that you didn't hear from us for a week. This is a somewhat known issue, so we'll track it in the original issue, but thank you for taking the time to report the issue to us :)

Duplicate of #523
