### ISSUE TITLE
[BUG] Missing symbol names for functions on alpha and sparc

### ISSUE THREAD

**Issue by baryluk** [compiler-explorer/compiler-explorer#1989]
https://explore.dgnu.org/z/jCZ1e9

This is with gdc compiler for all targets.

On alpha-linux-gnu and sparc64-linux, it produces this:

alpha:
```
        addl $16,$17,$0
        cmplt $16,$0,$0
        ret $31,($26),1
        cmplt $17,0,$1
        cpys $f31,$f31,$f31
        ldah $0,-32768($31)
        bne $1,$L6
        ornot $31,$0,$0
        subl $0,$17,$0
        cmplt $0,$16,$0
        ret $31,($26),1
$L6:
        subl $0,$17,$0
        cmplt $16,$0,$0
        ret $31,($26),1
```

sparc64:
```
        add     %o1, %o0, %o1
        mov     0, %g1
        cmp     %o1, %o0
        movg    %icc, 1, %g1
        jmp     %o7+8
         mov    %g1, %o0
        cmp     %o1, 0
        bl,pn   %icc, .L6
         mov    0, %g1
        sethi   %hi(2147482624), %g2
        or      %g2, 1023, %g2
        sub     %g2, %o1, %g2
        cmp     %g2, %o0
        movl    %icc, 1, %g1
        jmp     %o7+8
         and    %g1, 1, %o0
.L6:
        sethi   %hi(-2147483648), %g2
        sub     %g2, %o1, %g2
        cmp     %g2, %o0
        movg    %icc, 1, %g1
        jmp     %o7+8
         and    %g1, 1, %o0
```

Where it should be:

alpha:
```
example.overflows!(int).overflows(int, int):
        addl $16,$17,$0
        cmplt $16,$0,$0
        ret $31,($26),1
example.overflows2!(int).overflows2(int, int):
        cmplt $17,0,$1
        cpys $f31,$f31,$f31
        ldah $0,-32768($31)
        bne $1,$L6
        ornot $31,$0,$0
        subl $0,$17,$0
        cmplt $0,$16,$0
        ret $31,($26),1
$L6:
        subl $0,$17,$0
        cmplt $16,$0,$0
        ret $31,($26),1
```

sparc64:
```
example.overflows!(int).overflows(int, int):
        add     %o1, %o0, %o1
        mov     0, %g1
        cmp     %o1, %o0
        movg    %icc, 1, %g1
        jmp     %o7+8
         mov    %g1, %o0
example.overflows2!(int).overflows2(int, int):
        cmp     %o1, 0
        bl,pn   %icc, .L6
         mov    0, %g1
        sethi   %hi(2147482624), %g2
        or      %g2, 1023, %g2
        sub     %g2, %o1, %g2
        cmp     %g2, %o0
        movl    %icc, 1, %g1
        jmp     %o7+8
         and    %g1, 1, %o0
.L6:
        sethi   %hi(-2147483648), %g2
        sub     %g2, %o1, %g2
        cmp     %g2, %o0
        movg    %icc, 1, %g1
        jmp     %o7+8
         and    %g1, 1, %o0
```

**Comment by partouf** [comment]
Considering that this CE version is rather old, I'm not sure how it would appear if CE were to be upgraded here.

The compilers do however have some out of the ordinary way of printing its assembly, and the functions disappear because of the .LX0 (unused functions) filter, so a workaround for this website is to uncheck .LX0. But I realize that ain't a convenient solution.

Will throw this asm into our unittesting and see if its improved, but obviously since this isn't our website, I can't comment on the timeline of a fix.

**Comment by RabsRincon** [comment]
Hi! https://explore.dgnu.org is run by @ibuclaw (sorry about pinging you!) as far as I can tell, so we have no control over its behaviour. You should open a report on the gdc forums. Sorry that we can't be more helpful.

**Comment by partouf** [comment]
Right, so the Alpha one defines the function without telling us it's part of the user's sourcecode.

```
$_D7example16__T9overflowsTiZ9overflowsFNaNbNiNfiiZb..ng:
_D7example16__T9overflowsTiZ9overflowsFNaNbNiNfiiZb:
        .frame $30,0,$26,0
$LVL0:
$LFB0:
        .file 1 "/srv/gdcexplorer/tmp/compiler-explorer-compiler120420-15636-1kru61b.0435/example.d"
        .loc 1 4 6 view -0
```

That's a rather tricky situation. We have _some_ custom code for those situations, but there's too much junk in between for us to make reasonable code from it, I think. Will investigate further later this week.

**Comment by ibuclaw** [comment]
> Note that https://explore.dgnu.org is run by @ibuclaw (sorry about pinging you!) as far as I can tell, so  as @partouf said, we have no control over its behaviour.

Not a problem, I think it's about a year since I last did a rebase on master, so I'll try again sometime soon (shortly after I rebuild all gcc-10 targets).

**Comment by ibuclaw** [comment]
FYI, I've rebased explore.dgnu.org on master - the only blocker was getting firejail working granted that the work directory and compiler binaries are kept in /srv rather than /opt.

Any proposed fixes should be easy to apply and test.
