### ISSUE TITLE
[BUG] Binary/objdump support not working for Kalray MPPA compilers

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#1990]
https://godbolt.org/z/GvCprR

@dkm I don't see any stderr messages coming from this on the website, but I haven't tested this locally. Though objdumper  has been added and supportsBinary=true, objdump returns 1 and nothing.

Is this supposed to work, or should we disable supportsBinary for these compilers?

**Comment by dkm** [comment]
On May 20, 2020 11:47:22 PM UTC, Patrick Quist <notifications@github.com> wrote:
>https://godbolt.org/z/GvCprR
>
>@dkm I don't see any stderr messages coming from this on the website, but I haven't tested this locally. Though objdumper  has been added and supportsBinary=true, objdump returns 1 and nothing.
>
>Is this supposed to work, or should we disable supportsBinary for these compilers?
>
>

This should work. It works in our local instance of CE. I'll have a look, thanks for reporting

**Comment by dkm** [comment]
Sorry for taking so long to fix this very stupid copy/paste from my previous commit

**Comment by partouf** [comment]
Fix is live
