### ISSUE TITLE
[BUG] x86->6502 translation is broken

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#1996]
Trying to convert x86 to 6502 using the tool yields an empty document: https://godbolt.org/z/y-36mC

**Comment by partouf** [comment]
ohno... I know you need at least -m32 -march=i386 to make it work better, but that doesn't help either. I guess we broke something

**Comment by partouf** [comment]
Change is live, -O3 is also recommended to get rid of registers that the tool doesn't support
