### ISSUE TITLE
Standard C++ cout reports error "cannot find crt1.o" when run for x86-64 gcc 4.9.4 and a couple of other versions

### ISSUE THREAD

**Issue by hvdbrand** [compiler-explorer/compiler-explorer#2006]
```cpp
#include <iostream>

int main()
{
    std::cout << "Hello world" << std::endl;
    return 0;
}
```

The code above fails to run on x86-64 gcc 4.9.4 and produces the following error:

> Could not execute the program
> Compiler returned: 1
> Compiler stderr
> /usr/bin/ld: cannot find crt1.o: No such file or directory
> /usr/bin/ld: cannot find crti.o: No such file or directory
> collect2: error: ld returned 1 exit status

The same error is seen for the following versions 4.9.4, 4.7.2, 4.7.1, 4.5.3, 4.4.7 and 4.1.2.
For all other version of x86-64 gcc 4.* the program runs as expected.

**Comment by partouf** [comment]
This is a know issue #1414

Suggestions on how to fix it are welcome

**Comment by OfekShilon** [comment]
Closing as duplicate
