### ISSUE TITLE
[BUG] Weird internal version text MSVC (microsoft url)

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2014]
**Describe the bug**
        `"version": "/Ox optimizations (favor speed)         Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28314 for x64",`

Does not affect helptext for /Ox nor anything else

**Comment by jeremy-rifkin** [comment]
Does this still occur?

**Comment by partouf** [comment]
I don't really remember what was going on here.

The version text looks ok, except when you click on `Toggle full version output`, then you don't see the version anymore until you refresh.

**Comment by jeremy-rifkin** [comment]
I think we can probably close this, the version stuff looks ok to me too
