### ISSUE TITLE
[BUG] Short links get replaced by godbolt.org shortly after loading

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2016]
**Describe the bug**
After clicking a short link, the URL bar continues to show /z/blah, but then will shortly revert to just godbolt.org. This makes it tricky to (e.g.) copy paste having opened on one device and send to another.

**To Reproduce**
Open a short link. wait... tab away, etc. Note the URL loses the /z/blah

**Expected behavior**
The /z/blah should remain until something changes in the page to invalidate it.

**Additional context**
Reported over twitter: https://twitter.com/Donzanoid/status/1270321725205553152

**Comment by mattgodbolt** [comment]
Maybe I misremembered how we did this?

**Comment by partouf** [comment]
I think this was the case, yes. But we probably introduced something that triggered this sooner than expected.

**Comment by apmorton** [comment]
the shortlink goes poof as soon as you click into one of the monaco editors because the following gets added to the serialized state:

```json
"selection": {
    "startLineNumber": 1,
    "startColumn": 21,
    "endLineNumber": 1,
    "endColumn": 21,
    "selectionStartLineNumber": 1,
    "selectionStartColumn": 21,
    "positionLineNumber": 1,
    "positionColumn": 21
},
```

**Comment by mattgodbolt** [comment]
Good spot @apmorton - it's the selection stuff, of course. Thanks; that's a great steer towards a fix.

**Comment by partouf** [comment]
Seems this was added in https://github.com/compiler-explorer/compiler-explorer/pull/1702

There should probably be a tiny condition that URL doesn't get updated on cursor/selection changes, but still be saved in the state...
