### ISSUE TITLE
[BUG] Missing STL for arm clang

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2018]
**Describe the bug**
Including stl headers on arm clangs fails.

**To Reproduce**
`#include <vector>` with arm-clang-8a selected (for example)

**Expected behavior**
No errors!

**Link**
https://godbolt.org/z/4HtLZh

**Comment by partouf** [comment]
To clarify, targets needed are aarch64-none-linux-android (arm64) and armv7-none-linux-androideabi (arm32)

**Comment by RedBeard0531** [comment]
FYI, using explicit `-I` to point clang at the gcc libstdc++ seems to work: https://godbolt.org/z/A7pqb8. I haven't been able to clang libc++ to work the same way, but a working libstdc++ seems better than nothing. Is it possible to configure the arm builds of clang to use a working libstc++ path?

**Comment by partouf** [comment]
> FYI, using explicit `-I` to point clang at the gcc libstdc++ seems to work: https://godbolt.org/z/A7pqb8. I haven't been able to get libc++ to work the same way, but a working libstdc++ seems better than nothing. Is it possible to configure the arm builds of clang to use a working libstc++ path?

This also doesn't work for things like <memory>

Linking definitely does not work, that might be because of it using a x86 gcc toolchain. Maybe using a gcc arm toolchain could fix some more problems.
But I think these gcc's are still using slightly different targets, so not sure how that will work out. Will have to experiment.

> This is "just" clang trunk run with a `-target`. Probably need to read https://clang.llvm.org/docs/CrossCompilation.html and see what w're missing from the install

This doc talks about using --sysroot, but not sure how that would work vs --gcc-toolchain - or if it would matter much.

**Comment by partouf** [comment]
I got this to work locally using the latest android-ndk (including linking and objdump), but it took a lot of command line parameters.

properties:
```
compiler.armv8-clang-trunk.objdumper=/opt/compiler-explorer/android-ndk-r21d/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-objdump
compiler.armv8-clang-trunk.options=-target aarch64-none-linux-android
```

parameters:
```
--gcc-toolchain=/opt/compiler-explorer/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64
--sysroot=/opt/compiler-explorer/android-ndk-r21d/platforms/android-30/arch-arm64
-I/opt/compiler-explorer/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aarch64-linux-android
-I/opt/compiler-explorer/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1
-I/opt/compiler-explorer/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
-L/opt/compiler-explorer/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android
-L/opt/compiler-explorer/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1
-L/opt/compiler-explorer/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/30
```

Tried to eliminate some things, but this seems to be the minimum. Not entirely sure why clang doesn't know how to solve this equation by itself...

In any case, we should probably not be using android ndk on the live website. I will see if I can copy paste and apply this method to a current gcc arm version...

**Comment by partouf** [comment]
Although it seems we don't have a valid bits/c++config.h for aarch64.

The prebuilt gcc's for arm do have them https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads - we could maybe install those targets and get them to work this way.

But still, we would be mixing different abi's. Would it be an option to change the target ABI for the Clang arm compilers? to gnu or eabi? What was our initial reason to target the android abi?

**Comment by kedartal** [comment]
Seems like the LLVM installation does include the c++ standard library, so this seems to works for looking at the generated assembly: `-stdlib=libc++ -I/opt/compiler-explorer/clang-trunk-20200628/include/c++/v1 -std=c++2a --target=aarch64-none-linux-gnu` (e.g. https://godbolt.org/z/EgAv6g) -- but obviously the include path would change quite often. Perhaps add in the UI a hint to the current path?

**Comment by partouf** [comment]
From https://github.com/compiler-explorer/compiler-explorer/pull/1796 pinging @daverodgman @mattgodbolt 

Would like input as to why Android ABI's were chosen, is this strictly necessary? (we could make it work, but we would have to install Android NDK)

**Comment by partouf** [comment]
This is now fixed live
