### ISSUE TITLE
[BUG] UI - The sponsors/patreon-popup could be bigger in a maximized Browser on a horizontal FullHD-screen

### ISSUE THREAD

**Issue by Chaosmeister** [compiler-explorer/compiler-explorer#2020]
Heyo!

So I just spent way too much time figuring out the source of the sponsors-content-root height since the "no bugs" logo caught my attention....
It looks like the pop up could use another sizing step as it leaves a lot of free space in a maximized browser on a horizontal FullHD-screen:

![image](https://user-images.githubusercontent.com/13346344/84319193-ea5e7580-ab6f-11ea-9e3f-820d5c866c16.png)

I suggest adding "max-height: 600px;" for "min-height: 900px"

![image](https://user-images.githubusercontent.com/13346344/84319146-d450b500-ab6f-11ea-9472-6cc9792bfcc3.png)

If possible, it should even be resized automatically to the bodys height.

Also I just noticed the black cross icon to close the sponsors popup is harder to find in dark themed compiler explorer. It is highlighted in grey, and there are several other ways to close it, so that's only a minor detail!

**Comment by mattgodbolt** [comment]
I _think_ this is closed now. Can you reconfirm please @Chaosmeister -- and if it's still problematic can you post your screen resolution so I can repro exactly! Thanks so much :)

**Comment by Chaosmeister** [comment]
I've seen that something has changed 😅 

![image](https://user-images.githubusercontent.com/13346344/84512047-b4340980-acc7-11ea-99c3-34c3d937ffaa.png)

I think It's not optimal, yet.

My chrome window is 1920 x 937 which comes from 1920 x 1080 minus chrome tabs, -adress and bookmarks on top and the windows taskbar at the bottom.

When I resize vertically, a scrollbar appears from 781px to 700px and then the popup resizes on 699px.

![image](https://user-images.githubusercontent.com/13346344/84512866-e6923680-acc8-11ea-915a-1eae1b3a5cd2.png)

Definitely avoid the vertical scrollbar. ✌️

**Comment by partouf** [comment]
@Chaosmeister did you do the vertical resize before or after opening the popup? basically none of our popups work with resizing after opening them

**Comment by Chaosmeister** [comment]
Yes!  I can resize the Tab and the popup resizes horizontally and vertically as defined in https://github.com/compiler-explorer/compiler-explorer/commit/e6a4302399ced00d01879b505884790ba8582b51#diff-89f2729161a084098630e63708c315dd

**Comment by Chaosmeister** [comment]
Horizontally it's pretty good now. Leaves just enough space to be able to leave the pop comfortably.
Vertically could still be improved.

I did not try it on mobile, yet.

**Comment by Chaosmeister** [comment]
My Browser btw:
![image](https://user-images.githubusercontent.com/13346344/84513953-8603f900-acca-11ea-8769-8390c1a789d4.png)

**Comment by mattgodbolt** [comment]
Mobile is...a different issue :grinning: though we _are_ trying to improve things there. Last time I looked at this window it was a catastrophe, despite trying to fiddle things. We're learning...

**Comment by Chaosmeister** [comment]
I created a pull-request with values, that work for me

#2024

**Comment by Chaosmeister** [comment]
I just added some code that dynamically computes the height of the popup with [css-calc()](https://developer.mozilla.org/de/docs/Web/CSS/calc)

**Comment by Chaosmeister** [comment]
So after a little more twiddling and experimenting with the css for the modals, I might be able to make them all super responsive.

Is this something you'd like to achieve? I'd rework the PR then
