### ISSUE TITLE
Clang Cuda output missing some target labels

### ISSUE THREAD

**Issue by baxissimo** [compiler-explorer/compiler-explorer#2021]
**Describe the bug**
Seems like some labels are missing from clang cuda output compiled with -O2.
I see things like this:
```
@%p1 bra        LBB6_2;
```
But there's no `LBB6_2:` in the dissasembly.

**To Reproduce**
Open this example:
https://cuda.godbolt.org/z/nD47PF
Or open cuda.godbold.org, set compiler to "clang trunk", options to -O2, and put this in the code editor:
```
__global__ void square(int num, int num2, float *out) {
    float f = num * num;
    if (num < num2) {
        __builtin_trap();
    }
    *out = f;
}
```

**Expected behavior**
If there's a `bra {label}` in the code, that label should be in the dissasembly somewhere.

**Link**
If applicable, please provide a link to Compiler Explorer to help explain your problem.
https://cuda.godbolt.org/z/nD47PF

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 83.0.4103.97

**Additional context**

**Comment by zbjornson** [comment]
This happens with NVCC also. A workaround is to uncheck "Filter > Unused Labels".

**Comment by baxissimo** [comment]
Nice! Thanks for the tip.

**Comment by OfekShilon** [comment]
Fixed, probably by recent label-filtering enhancements
