### ISSUE TITLE
[BUG] no output on msvc compilers

### ISSUE THREAD

**Issue by Kashio** [compiler-explorer/compiler-explorer#2022]
**Describe the bug**
Can't get msvc output compilers

**To Reproduce**
Set the compilers to any of the x64 msvc

**Link**
https://godbolt.org/z/eRp9EW

**Screenshots**
![Compiler Explorer - Google Chrome](https://user-images.githubusercontent.com/16501683/84388732-baf64a00-abfd-11ea-9806-88309322784f.jpg)

**Desktop (please complete the following information):**
 - OS: windows 10 x64
 - Browser: chrome x64
 - Version: 83.0.4103.97

**Additional context**
Sometimes I get it to work by resetting UI and code option but most of the time I can't get it to output anything

**Comment by partouf** [comment]
None of the MSVC compilers support execution, so I'm curious how you would "sometimes" to get it to work.

**Comment by Kashio** [comment]
Well that's a bug in itself I guess because I literally got output yesterday on msvc

**Comment by mattgodbolt** [comment]
Thanks both: @Kashio if you can screenshot getting execution output on MSVC the next time you see it that would help enormously. As @partouf says we don't support it (and indeed can't!) so we need to work out what's happening! Thanks!

**Comment by Kashio** [comment]
@mattgodbolt Thanks, will try to screenshot it next time.
Also, any plans on supporting execution output on msvc in the  future?

**Comment by mattgodbolt** [comment]
@Kashio please do let me know if it happens again (will close this, but please reopen if you get it happening).

I'm afraid no plans to support execution on MSVC. We don't have the skills to support this - we rely on Microsoft for their support of MSVC and compilation (see https://www.godbolt.ms/ - we proxy to this).

**Comment by danra** [comment]
How about signaling more explicitly when output is not supported? As a non-experienced godbolt user, I spent a good 10 minutes confused, thinking I'm doing something wrong when examining a godbolt link to an msvc-compiled program in an SO answer.
