### ISSUE TITLE
[BUG] Error with compilation/execution and confusing error message

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2026]
Seen on twitter: https://twitter.com/Doomed_Daniel/status/1271860881127804929?s=20

> Seems like Wine+MSVC compilation+execution is currently broken, I get "Command line error D8021 : invalid numeric argument '/Wl,-rpath,/opt/compiler-explorer/windows/19.10.25017/lib/native/bin/lib'"
(I guess cl.exe or windows in general doesn't support RPATH?) 
@mattgodbolt

Possibly relating to #2022 where the poster there is seemingly able to mostly execute on windows?

**Comment by mattgodbolt** [comment]
Link: https://godbolt.org/z/dQmWjX

**Comment by partouf** [comment]
1. known; the Executor pane doesn't look at supportsBinary/supportsExecution 
2. to at least fix the compilation error; on native windows base class (win32.js) there are correct overrides for /LIBPATH and the like, should be copied into wine-vs.js (this ofc doesn't fix the not-executing)

**Comment by partouf** [comment]
Perhaps for pt 1, we can do something similar like https://github.com/compiler-explorer/compiler-explorer/pull/1992
But anything else will be fine too, as this issue has come up a frustrating amount of times

**Comment by partouf** [comment]
For what it's worth, the -Wl,-rpath bit has been fixed. And with the filtering change this compiler should no longer be selectable. You can still click on the link here, but it will show the actual error that happened during linking (runtime sdk libraries that cant be linked against) and it will show there's nothing to execute.
