### ISSUE TITLE
[BUG] Popups not centered anymore

### ISSUE THREAD

**Issue by RabsRincon** [compiler-explorer/compiler-explorer#2030]
**Describe the bug**
Modal popups used to be centered.

**To Reproduce**
More > Settings

**Expected behavior**
Centered popups

**Screenshots**
![imagen](https://user-images.githubusercontent.com/5364255/84764787-8e13af80-afce-11ea-9357-9c8326d9f158.png)

**Additional context**
Im guessing https://github.com/compiler-explorer/compiler-explorer/pull/2025 has something to do with it - But it didn't look like this when I reviewed the changes locally

**Comment by mattgodbolt** [comment]
Fixed by #2072. Will deploy later
