### ISSUE TITLE
[BUG] Can't view opcode doc for Intel CET instructions

### ISSUE THREAD

**Issue by josephcsible** [compiler-explorer/compiler-explorer#2031]
**Describe the bug**
Viewing the opcode doc for Intel's Control-flow Enforcement Technology instructions doesn't work. It gives this error: `Compiler #1: This token was not found in the documentation. Sorry!`

**To Reproduce**
1. Compile a program that uses Intel CET instructions, such as by passing `-fcf-protection=full` to GCC or Clang.
2. Right-click an Intel CET instruction, such as `endbr64` at the beginning of any function.
3. Select "View x86-64 opcode doc".

**Expected behavior**
I expect to be shown documentation for the instruction.

**Link**
https://godbolt.org/z/bCaNJk

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83

**Additional context**
Here's a link to an Intel PDF about them: [Control-flow Enforcement Technology Specification](https://software.intel.com/sites/default/files/managed/4d/2a/control-flow-enforcement-technology-preview.pdf)

The `-fcf-protection=full` flag has been supported since GCC 8 and Clang 7.

**Comment by partouf** [comment]
`endbr64` documentation does work now, no idea when that was fixed or how, but it is
