### ISSUE TITLE
[BUG] boost/predef/platform/windows_uwp.h(37): fatal error C1083: Cannot open include file: 'ntverp.h': No such file or directory

### ISSUE THREAD

**Issue by andry81** [compiler-explorer/compiler-explorer#2035]
**Describe the bug**
simple `boost/date_time/posix_time/posix_time.hpp` header include

**To Reproduce**
```
#include <boost/date_time/posix_time/posix_time.hpp>
```
Enable library: boost `1.73.0` or lower

Compiler: Any `MSVC 2017` version

**Expected behavior**
no compilation error

**Link**
https://godbolt.org/z/PbtwuB

**Comment by partouf** [comment]
This should probably be issued under https://github.com/microsoft/vcpkg (the package mgr Msvc compilers use)

**Comment by mattgodbolt** [comment]
This is somewhat related to #1816 I think. That said; the WINE compilers definitely don't have support for libraries, and the link above seems to fail with "ntverp.h" only on the WINE compilers. The MSVC compilers fail with a `<source>(1): fatal error C1083: Cannot open include file: 'boost/date_time/posix_time/posix_time.hpp': No such file or directory` error instead.

Either way, we don't support libraries in Windows compilers very well:
* For the WINE compilers we will almost certainly never support libraries; sorry. They are a very dodgy hack and getting them to generate viable binaries is not likely, and installing libraries for them is fraught with trickiness.
* The non-WINE compilers are installed and administrated by MS volunteers (see www.godbolt.ms for example); they occasionally look at this forum but the main place to get support there is by writing on their forums. I'll try and find a link for this.

**Comment by andry81** [comment]
I don't know, but ms variant does not work eitherr: https://www.godbolt.ms/z/lJStc5

**Comment by partouf** [comment]
I'm not very knowledgable about their setup, but they may have forgotten to install the right vcpkg for this.
I think the boost libraries are separate packages (https://github.com/microsoft/vcpkg/tree/master/ports).

**Comment by mattgodbolt** [comment]
CC @strega-nil in case she can help us here.

**Comment by partouf** [comment]
Works on the Microsoft instances now, so closing this issue
