### ISSUE TITLE
[REQUEST] Add PTX to SASS

### ISSUE THREAD

**Issue by Saitama10000** [compiler-explorer/compiler-explorer#2038]
[CUDA] to [PTX or SASS] option already exists, and I think we should have [PTX] to [SASS] option as well for handwritten PTX.

The ptxas assembler outputs SASS [-cubin option] and that SASS binary file can be listed using cuobjdump.

**Comment by partouf** [comment]
I don't know anything about any of this. But I did some googling.

So I think what this means is, to add ptxas as an assembler, and we can use cuobjdump to disassemble the output binary

**Comment by partouf** [comment]
* Using ptxas seems pretty straight-forward `ptxas  -arch=sm_20 -m64  "t266.ptx"  -o "t266.sm_20.cubin` (https://stackoverflow.com/questions/20012318/how-to-compile-ptx-code)
* Example code applied inline in cuda https://docs.nvidia.com/cuda/inline-ptx-assembly/index.html
* How to output ptx (to use as input for ptxas) https://godbolt.org/z/eTGaix

**Comment by Saitama10000** [comment]
I’m referring to adding _**PTX as an editor** _and output SASS code. You can output code from the CUDA editor -> NVCC output as binary. I was wondering if we could get a PTX **editor** and output SASS code without having to go through the semantics of a CUDA editor.

**Comment by partouf** [comment]
> I’m referring to adding _PTX as an editor_ and output SASS code. You can output code from the CUDA editor -> NVCC output as binary. I was wondering if we could get a PTX **editor** and output SASS code without having to go through the semantics of a CUDA editor.

That's what I meant, we have an Assembly editor -> https://asm.godbolt.org/

**Comment by partouf** [comment]
This is now live https://godbolt.org/z/EzTPPx

**Comment by Saitama10000** [comment]
OMG! Thank you! This is insanely great!!!
