### ISSUE TITLE
[REQUEST] Add trunk gcc for more targets

### ISSUE THREAD

**Issue by GabrielRavier** [compiler-explorer/compiler-explorer#2041]
I think it would be great if the trunk version of GCC was available for more targets, like ARM/ARM64/RISC-V/PowerPC/MIPS/AVR. Most likely they'd be somewhat broken a lot of the time (alike to LLVM), but they'd be very useful for optimization comparison purposes (would be especially helpful for me, I spend a lot of time using Godbolt for the purpose of searching for optimization bugs in GCC and LLVM) and seem rather easy to set up considering x86 trunk is already present and built regularly.

**Comment by mattgodbolt** [comment]
Thanks! Right now GCC versionsare built using some sister repos:

* https://github.com/compiler-explorer/gcc-builder
* And currently cross compilers built with https://github.com/compiler-explorer/gcc-cross-builder which uses `crosstool-ng`

We only build nightly trunk versions from the former link as that's the one I know how to get working. I rely on `crosstool-ng` to do the heavy lifting of getting the build environment working for cross-compilation. I don't know how (or if it's possible) to coax that to build from github. Any thoughts welcomed on this: unlike `clang`, GCC's build is not as straightforward for cross-compilers.

**Comment by GabrielRavier** [comment]
For clang, isn't it essentially as simple as prefixing a `-target aarch64` (with the desired target instead of aarch64) ? I just do that when I want to check a backend without having to go through the UI to change the compiler.

**Comment by mattgodbolt** [comment]
Yes: that works for clang (but we're not talking about clang here?)

**Comment by mattgodbolt** [comment]
I guess I brought up clang above: clang is already built for all targets (as by its nature clang is an out-of-the-box cross compiler). We have all the trunk builds for clang in the dropdown as they all run clang-trunk but with different canned command-line options (as you say, they just add `-target ...` etc)

**Comment by GabrielRavier** [comment]
But so for GCC wouldn't it essentially just be adding an extra version of existing cross compilers that builds the trunk version instead of 5.4/8.2/7.3/whatever version that cross compiler is normally built for ? The only problem I could see with that is the extra resources required to build GCC several times every few days, the only reason I'm not trying to make a PR myself is that my only Linux machine is a laptop with a 32 GiB SSD, an Intel Atom and 2 GiB of RAM.

**Comment by mattgodbolt** [comment]
Hi @GabrielRavier . Unfortunately not. If you check the links to the sister repos above you'll see that cross-compiling for GCC is considerably more complex. We use `crosstool-ng` which is a third-party script (see https://crosstool-ng.github.io/ ) able to manage the build for GCC for cross-compilation (which includes downloading the target OS's system headers and libc...). crosstool-ng works for specific, tailored versions of GCC and their attendant per-platform configuration (see, for example this example [script[(https://github.com/compiler-explorer/gcc-cross-builder/blob/master/build/1.24.0/powerpc64le-at13.config) ). It doesn't work in general (to the best of my understanding) with an arbitrary git SHA, but I also haven't looked in to it for a long time.

If anyone watching knows a good way to cross compile I'd be all ears.

**Comment by Mistuke** [comment]
@mattgodbolt You just need GCC right? not a full toolchain? What distro do you usually use for cross compiling?

**Comment by partouf** [comment]
@Mistuke as mentioned, we use this https://github.com/compiler-explorer/gcc-cross-builder Docker image and scripts to create cross gcc builds (I have no idea how it works)

**Comment by topperc** [comment]
@mattgodbolt Is it possible to get gcc trunk for RISCV or gcc 11 for RISCV?

**Comment by zhongjuzhe** [comment]
Can we have GCC trunk in compiler explorer ? Like we already have Clang trunk in compiler explorer.

**Comment by dkm** [comment]
Oh missed last 2 messages. Yes we can probably add a daily build for riscv as it's a major target.

**Comment by dkm** [comment]
I'll close this issue, as it's a bit vague. If some targets are needed, you can open a dedicated issue/PR and we'll start from there. For example, I'm currently adding ppc64(le).
