### ISSUE TITLE
Mobile experience thread

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2042]
**About the current state of mobile support**

We recently (2020-06-20) pushed a change so that shortlinks (godbolt.org/z/...) are handled differently in mobile webclients:
* Various panes that you would have on your desktop will be redisplayed as tabs instead,
* If there are multiple editors, you will have extra buttons in the main menu to scroll through those different sources
* The editors will be read-only
* You can always switch back to desktop mode by using your browser settings for the website

Local installations should not be affected.

Please leave any complaints, suggestions or opinions here.

Twitter thread: https://twitter.com/CompileExplore/status/1276142037742620672

**Comment by mattgodbolt** [comment]
I'm _so excited_ about this!

I tried a quick link on my phone (`z/_jQFKq`) which was a random link that autocompleted in my address bar, , and then tried `/z/3cceeE` (another random one in my history) . Both looked great! This is a huge improvement.

Thoughts:
* the dropdown to switch between panes (I think coming from Golden Layout) is tricky to use on a cellphone. Tapping it pretty much toggles to the next view without being obvious that you can hold to see more options. That might be ok, just an initial reaction
* We probably need a cookie-remembered intro popup saying "Hey you're in mobile view!" with some explanation about what people can do and how to interact (and get the old site back). Possibly a link to this issue too.

So good. I honeslty can't believe how much of a difference this makes!

**Comment by partouf** [comment]
Multiple reports of not being able to see or scroll to the last line. Seems to affect both iPhone and Android.

**Comment by partouf** [comment]
Right-click (hold finger for a couple seconds) - menu that shows monaco editor contextual menu, does not disappear when you tap outside of the menu.

**Comment by partouf** [comment]
Wondering if there's a way in GL to force tabs to be used, even if they won't fit. And maybe have more of a <> menu like in most IDE's

**Comment by lethal-guitar** [comment]
This is excellent, thanks so much for the effort! :+1: My only issue is the menu mentioned in https://github.com/compiler-explorer/compiler-explorer/issues/2042#issuecomment-649628135. This also prevents me from selecting/copying any of the code.

**Comment by biocomp** [comment]
I'm using Firefox on Android. Can't edit source code (cursor is not visible, keyboard does not pop up). After using triangle to switch to assembly for the first time, menu with source/assembly file list does not disappear and just covers the part of the screen.

**Comment by mattgodbolt** [comment]
Thanks @biocomp - I should have said in the tweet that the code is also read only. Our editor choice (MS's Monaco) doesn't support mobile at all, we're lucky it works (just about) read only!

**Comment by mattgodbolt** [comment]
Other notes:
* Android gesture for zooming (seems to work on iPhone) https://twitter.com/KonanM5/status/1276184959452143623
* Policy documents are unreadable on mobile: https://twitter.com/noop_dev/status/1276224929646731266

Perhaps we should consolidate any futrher feedback over the next day or so, then bust out some sub issues to track on the project.

Thanks @partouf for kick-starting this project! I'm so thrilled as to how well it's going.

**Comment by partouf** [comment]
Android zooming should be working now

**Comment by jmr** [comment]
> The editors will be read-only

I noticed not being able to edit starting around this time, but had blamed it on chrome / android keyboard.

Editing on mobile used to mostly work, which is much better than never working.

**Comment by apmorton** [comment]
if you "request desktop site" in your browser you will get the old behavior

**Comment by jmr** [comment]
Ok, thanks.

**Comment by dgutson** [comment]
Can't see the cursor, keyboard doesn't show up, can't edit.

**Comment by partouf** [comment]
> Can't see the cursor, keyboard doesn't show up, can't edit.

This is as-intended

**Comment by MajorPainTheCactus** [comment]
Why on earth is it intended that you cant edit the code on a mobile phone?

**Comment by apmorton** [comment]
@MajorPainTheCactus did you read this thread at all? The editors are read only because Monaco (the editor used) doesn't support mobile devices. The choices were:
- do nothing and leave the site completely broken on mobile
- make the editors read only so you can at least view links from others

You are more than welcome to go try and fix this upstream with Monaco - we would gladly support editing on mobile if there was a feature complete editor that worked on a phone.

**Comment by MajorPainTheCactus** [comment]
I did read the thread and have no idea about 'Monaco', I just want to paste code in from GPT4 and see the results I dont want to have to jump through hoops reading issues as ungrateful as that sounds in my behalf (I know you guys have worked hard to produce a fantastic tool here Im just frustrated)

**Comment by jeremy-rifkin** [comment]
We hope to have better mobile support one day but unfortunately monaco really does tie our hands. For now https://godbolt.org/noscript is the best mobile option, if you're not familiar with it yet :)
