### ISSUE TITLE
Redeploy the site to automatically update the version of PVS-Studio

### ISSUE THREAD

**Issue by GeorgeGribkov** [compiler-explorer/compiler-explorer#2043]
Hi guys!

We had a release of the new version of PVS-Studio on Friday, but the new features still haven't got to the Compiler Explorer. The new version has been uploaded to the link from which Infra does the analyzer install. Could you please redeploy? This is all that is needed to update PVS-Studio.

Thanks in advance!

**Comment by mattgodbolt** [comment]
Hi George; I'll ensure this is done by the end of the day today! I'm not sure what's going on right now.

**Comment by mattgodbolt** [comment]
I checked and @GeorgeGribkov I see this:

```
Installing tools/pvs-studio/latest
2020-06-22 16:57:12,827 lib.installation ERROR    Failed to fetch https://files.viva64.com/pvs-studio-latest.tgz: <Response [404]>
2020-06-22 16:57:12,827 lib.installation INFO     tools/pvs-studio/latest failed to install: Fetch failure for https://files.viva64.com/pvs-studio-latest.tgz: <Response [404]>
Traceback (most recent call last):
  File "/home/ubuntu/infra/bin/lib/ce_install.py", line 174, in main
    if installable.install():
  File "/home/ubuntu/infra/bin/lib/installation.py", line 625, in install
    self.stage()
  File "/home/ubuntu/infra/bin/lib/installation.py", line 608, in stage
    self.install_context.fetch_url_and_pipe_to(f'{self.url}', self.tar_cmd, self.untar_to)
  File "/home/ubuntu/infra/bin/lib/installation.py", line 104, in fetch_url_and_pipe_to
    self.fetch_to(url, fd)
  File "/home/ubuntu/infra/bin/lib/installation.py", line 81, in fetch_to
    raise RuntimeError(f'Fetch failure for {url}: {request}')
RuntimeError: Fetch failure for https://files.viva64.com/pvs-studio-latest.tgz: <Response [404]>

0 packages installed OK, 0 skipped, and 1 failed installation
```

I can't hit the URL https://files.viva64.com/pvs-studio-latest.tgz from my desktop machine either:

```
/tmp $ curl -sL https://files.viva64.com/pvs-studio-latest.tgz
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

Have you removed the "latest" link?

**Comment by mattgodbolt** [comment]
@GeorgeGribkov as a temporary fix I've hardcoded the current latest version in 6ee4c9df2001b374eb3511b8e4e49ebf10593b62) - but once the endpoint for "current" is back I'll be ready to change this back.

**Comment by GeorgeGribkov** [comment]
Hi Matt!
Thank you for the fast fix!
Sorry for this problem - the link is fixed and ready-to-use now.

**Comment by RabsRincon** [comment]
I've reverted the change and we now look for the latest version at the specified link. Thanks for fixing it so quickly :)

**Comment by GeorgeGribkov** [comment]
Thank you all, guys, for help!
