### ISSUE TITLE
[BUG] Can't run static PIE binaries

### ISSUE THREAD

**Issue by josephcsible** [compiler-explorer/compiler-explorer#2049]
**Describe the bug**
When you try to run a static PIE binary, it segfaults before the beginning of main.

**To Reproduce**

1. Create a C program with a main method
2. Add `-static-pie` as a command line option to GCC
3. Enable "Run the compiled output"
4. In the output window, note the message "Program returned: 139", corresponding to a segfault

**Expected behavior**
I expected my program to be able to run its main method.

**Link**
https://godbolt.org/z/fESShr

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 77.0.1

**Additional context**
The same source file and command line produce a working binary when I try locally, both on Ubuntu 20.04 and CentOS 8.2.

I think this is somehow related to glibc. If I write my program without it, then it works fine: https://godbolt.org/z/RwDbSE

It also works fine if it's dynamic and PIE, or static and non-PIE. It's only the combination of static and PIE that's broken.

**Comment by partouf** [comment]
Tbt, I had no idea one could actually run this, it seems this was flag was introduced in GCC 8.

It seems to work with just gcc -g -static-pie etc, but the rpath's seem to throw a wrench in the mix (tested locally without nsjail). 

I'm guessing it tries to statically link some system libraries into it indeed (libs, linux-vdso, ld-linux?), but that somehow doesn't mix with the gcc 10 libraries?
I also don't think we have those libraries built as a static library for most x86/64 compilers except for the default system .a's. So it kind of makes sense that they don't mix.

Not sure we can make this happen without building libc ourselves for the various compilers to support this.
