### ISSUE TITLE
[REQUEST] **Support FIR generation for the new fortran frontend(flang) in llvm**

### ISSUE THREAD

**Issue by Sameeranjoshi** [compiler-explorer/compiler-explorer#2050]
**Is your feature request related to a problem? Please describe.**
As the new fortran frontend is WIP in llvm and with the introduction of MLIR (which would help in analysis of the new optimizations) . I always needs to use the fortran IR (FIR) a dialect of MLIR to analyze the IR generated and do some code changes or verify the compiler.

**Describe the solution you'd like**
So I would like to see the new FIR generation, i.e fortran code on left and FIR on right.

**Describe alternatives you've considered**
I don't have any still now. I use the same compile file see FIR generated file. Again open the file change code do the same.

**Additional context**
none

**Comment by partouf** [comment]
I think this request is similar to https://github.com/compiler-explorer/compiler-explorer/issues/1793
