### ISSUE TITLE
Includes fail in Clang ARM versions after 9.0.0

### ISSUE THREAD

**Issue by nispio** [compiler-explorer/compiler-explorer#2055]
There appears to be an issue with all of the most recent Clang compilers for ARM.  Both of the version 9 compilers (`armv8-a clang 9.0.0` and `armv7-a clang 9.0.0`) are working fine, but any newer versions of the compiler for those architectures fail at the first `include` statement.  The Clang compilers for x86 do not seem to have this issue.

To reproduce:
https://godbolt.org/z/ZuxyUd

**Comment by partouf** [comment]
Thanks for the example!
This is a known problem, you can follow the progress here https://github.com/compiler-explorer/compiler-explorer/issues/2018
