### ISSUE TITLE
[REQUEST] Add sol2 library

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2057]
Requested via discord: https://github.com/ThePhD/sol2

**Comment by mattgodbolt** [comment]
If anyone's interesting in trying this: https://github.com/compiler-explorer/compiler-explorer/blob/master/docs/AddingALibrary.md

**Comment by partouf** [comment]
Considering the size and header-only, I fear the worst for compilation time

**Comment by mattgodbolt** [comment]
Good point. Will be interesting to see. One day maybe we'll move to a faster network storage solution....

**Comment by McKillroy** [comment]
Sol makes no sense without Lua. But since you have beasts like Boost or Fmt available I doubt it will be a major problem.

**Comment by partouf** [comment]
> Sol makes no sense without Lua since it just provides C++ bindings to Lua.
> But since you already have compile time beasts like Boost or Fmt available I doubt this will be a major problem.

Right, that too. But lua probably shouldn't be a problem, we can handle that like we do OpenSSL.

**Comment by mattgodbolt** [comment]
Thanks both! I'll add an issue for lua too.

**Comment by partouf** [comment]
This is now live on prod
