### ISSUE TITLE
[REQUEST] Add lua

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2059]
Add lua as a library. See #2057

**Comment by partouf** [comment]
So it's not as easy it seems.
The supplied makefile only supports gcc, native/64bits, static library (though on mingw it supports building shared library)

So we have a couple of options:
* Patch the makefile after downloading to remove the setting of CC and CFLAGS
* Create a new CMakeLists to build a whatever we want (new version new file required though)
* And if CMake, do we just build a shared .so and save in buildtimes, or do we really need it to be a static library?
