### ISSUE TITLE
Nim Language Support

### ISSUE THREAD

**Issue by Varriount** [compiler-explorer/compiler-explorer#206]
How much work would it take to support [Nim](http://nim-lang.org/)? The main language backend can use pretty much any C compiler, and it would be interesting to observe the assembly output.

**Comment by mattgodbolt** [comment]
If it's a simple call to a NIM compiler, it'll fit straight in. If it's a two-step process (NIM->C, C->asm) then that'd be a bunch more work, though a hacky solution would be to specify a shell script that does both.

If you have thoughts, the scripts to install all the compilers used by CE are in https://github.com/mattgodbolt/gcc-explorer-image/ (`update_compilers` and whatnot), and the configuration for CE is in `etc/config`. 

https://github.com/mattgodbolt/gcc-explorer-image/pull/7 is an example of a pull request that added LDC

**Comment by Varriount** [comment]
Well, the Nim compiler calls the C backend automatically (although it's possible to manually compile as well). It also has the ability to put `#line` directives in the C source code which correspond to lines in the Nim source code.

**Comment by mattgodbolt** [comment]
That's great: then the code<->asm highlighting would work.  Of course, the backend compiler gives another degree of freedom (nim vX with GCC Y as back end) but I guess we can manage that with just "latest GCC Y"

**Comment by mattgodbolt** [comment]
Anyone interested in nim support please do have a look at adding it yourself. Since this bug was raised we've had haskell, ispc, and pascal support all added by contributors.

**Comment by superfunc** [comment]
I have some free time coming up in the next two weekends; I'll be taking a look at this and #1068

**Comment by RabsRincon** [comment]
That's great news! Let us know if you need any help getting it to work :)

**Comment by travisstaloch** [comment]
matt said on stream he wasn't sure about what gcc version should be paired with nim.  I asked about it on nim irc.  Here's the feedback I got:

> `<jrfondren>` latest gcc, latest g++, done. that's the kind of options Nim wants.
> `<narimiran>` agreed with @jrfondren
> <`narimiran>` btw, v0.19.6 and v0.20 are around the corner, so maybe wait until they are released so we have the latest and greatest right from the start?

**Comment by alehander42** [comment]
what is the state of this? 0.20 is out

**Comment by superfunc** [comment]
Unfortunately, life ended up getting in the way for me. If someone else has time to poke at this that would be great. If not, I may have a chance during the fall breaks in November.

**Comment by mattgodbolt** [comment]
I'm gonna call this closed! Yay!

**Comment by superfunc** [comment]
:) awesome work @DaemonSnake ! 
Sorry life got crazy and I never got a chance to attempt this @mattgodbolt.

**Comment by mattgodbolt** [comment]
Never a problem @superfunc ! This is all volunteer stuff :) Appreciate the offer, maybe next time :)
