### ISSUE TITLE
Leading underscored functions label-filtered in MIR mode

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2064]
e.g. https://godbolt.org/z/6U7CBt filters out some important-seeming lines if you enable label filtering.

Not quite sure how best to fix this.

H/T https://twitter.com/barrelshifter/status/1280277075530678272 for clueing us in :)

**Comment by mattgodbolt** [comment]
In fact, seems the MIR is YAML! So perhaps this whole thing should be "if it parses as YAML, then switch to YAML mode and don't do any filtering" ?

**Comment by OfekShilon** [comment]
Seems to have been resolved since.
