### ISSUE TITLE
[BUG] Missing demangling of C++ names containing lambdas

### ISSUE THREAD

**Issue by Alcaro** [compiler-explorer/compiler-explorer#2068]
**Describe the bug**
C++ names containing lambda types aren't demangled.

**To Reproduce**
```
int fib(int x)
{
    auto inner = [](int x, auto inner) {
        if (x <= 1) return 1;
        return inner(x-1, inner) + inner(x-2, inner);
    };
    return inner(x, inner);
}
```

**Expected behavior**
The symbol `_ZZ3fibiENK3$_0clIS_EEDaiT_` should be demangled to `auto fib(int)::$_0::operator()<$_0>(int, $_0) const`, not left as is.

**Link**
https://godbolt.org/z/6Ha4Fo

**Screenshots**

**Desktop (please complete the following information):**
Lubuntu 18.04 x86_64, Firefox 78.0.1

**Additional context**

**Comment by apmorton** [comment]
This is likely a c++filt version issue since the demangling works as expected for clang trunk.

On clang-trunk we use c++filt from our nightly gcc, on all the other clangs we pull it from our gcc 9.2.0 build.

**Comment by partouf** [comment]
If I click the link again, it looks fixed in the new demangler, am I correct in concluding that?

**Comment by apmorton** [comment]
yep - looks like 4b374609be4027095b64d9184135c1789be19f26 takes care of this.
