### ISSUE TITLE
[BUG] ARM assembly code is directed to x86 opcode documentation

### ISSUE THREAD

**Issue by VivekChugh** [compiler-explorer/compiler-explorer#2070]
linking opcode document with assembly code is very helpful feature. 
But even ARM assembly code is also directed to x86 opcode documentation.

**Comment by FlashSheridan** [comment]
Also RISC-V; both it and ARM are particularly confusing with the default example, `int square(int num)`, since the one significant operation is `mul`, which is glossed by the popup text as “unsigned multiplication” — without a warning that the documentation is only for x86, and that for the other two, `mul` is not necessarily unsigned.  (The context menu _does_ note that it’s x86; as an interim mitigation, I’d suggest a similar note in the popup text.)

**Comment by mattgodbolt** [comment]
Thanks both. The fact that it's not clearly labeled as x86_64 is misleading I agree. Will see if we can minimally do something about that!

**Comment by mattgodbolt** [comment]
https://developer.arm.com/architectures/cpu-architecture/a-profile/exploration-tools might be handy here

**Comment by jovere** [comment]
It has bothered me for a while that the ARM instructions don't show up when using the ARM compilers.

I have started working on a ARM version of the `docenizer.py` file to get an equivalent version of the `asm-docs.js` file using the link Matt posted above.  I presently have them called `docenizer-arm.py` and `asm-docs-arm.js` respectively.

So far, the one thing I see as a problem is the multiple definitions for instructions such as "immediate", "register", "register-shifted register", etc.  For now, I just plan to use the fist one that shows up in the directory (most likely immediate).

After I have that tool completed, I think the next required step is determining which instruction set to use, based on the compiler.

**Comment by mattgodbolt** [comment]
Sounds great, thanks @jovere !

**Comment by saagarjha** [comment]
Would it be possible to not show this for non-x86 architectures as a stopgap?

**Comment by mattgodbolt** [comment]
@saagarjha Not easily unforutnately. We don't "know" the architecture a compiler generates at the moment -- part of the puzzle @jovere is fixing in #2463 is to detect that. e.g. some compilers we know are "arm" compilers, but others can be retargeted with command-line switches. We're working on it though!

**Comment by partouf** [comment]
This was merged recently and very much live!
