### ISSUE TITLE
[BUG] shorturl cleared when there is an output pane

### ISSUE THREAD

**Issue by apmorton** [compiler-explorer/compiler-explorer#2077]
**Describe the bug**
When you click on a shortlink that contains a compiler output pane and then click into one of the monaco editors (simply to trigger a config rehash) the shortlink is removed from the address bar.

**To Reproduce**
- reset code and ui
- type some blank lines to make a unique shortlink
- click the "Output (0/0)" button to display the compiler output pane
- click share and copy the shortlink
- open a new tab and navigate to the shortlink
- select some code in the source window
- watch the shortlink go poof

**Expected behavior**

**Link**
https://godbolt.org/z/ozh4vr

**Additional context**
This is caused by the output pane title being changed after the window is initialized, shown in config dumps in the screenshot below:
![image](https://user-images.githubusercontent.com/63636/87486500-65043000-c609-11ea-8752-3c5ecc54ac0a.png)

**Comment by mattgodbolt** [comment]
Darn it. This whole thing is so fragile; perhaps we need to banlist some of the values in the hash? Once upon a time it seemed like a good idea to store the whole state, but @partouf has a more general format. Perhaps we should build one from the other now? One for the mid-long term I guess more...I wonder if there's a quick practical solution...

**Comment by partouf** [comment]
The "problem" in this case with the general format is that it doesn't store layout information. So it would only be useful if it would be used to compare two situations. It is however only a server-side transformation back and forth, we'd have to copy/makework it to be clientside before it would be useable in this case I think.

**Comment by mattgodbolt** [comment]
Got it Partouf. Do you think we could shim in layout? (maybe even as a separate, optional, part of the document?)

**Comment by RubenRBS** [comment]
Can't repo anymore (Or I'm missing some repo step). I think we ended up doing what Partouf suggested with
> Perhaps the only thing to do is to code more 'ignore this' things like the change with cursor position.
