### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by resynth1943** [compiler-explorer/compiler-explorer#2078]
**Is your feature request related to a problem? Please describe.**

## Remove Google Analytics

This commit removes the Google Analytics 'functionality' from this page. Following on
from the previous commit, this change also greatly improves the privacy of 
unsuspecting users.

If you must have an analytics system, might I suggest either:
- Plausible: https://plausible.io (offers a 50% discount for FOSS projects)
- Goatcounter: https://goatcounter.com
- Matomo: https://matomo.org
- Fathom: https://usefathom.org

These solutions are all well-tested and open-source. This, of course, means they
can be independently audited for privacy and security. Instead of using a proprietary
nonfree system such as Google Analytics, perhaps we could work together to replace
it with something slightly more ethical?

Furthermore, the majority of privacy features in evergreen browsers *block* Google
Analytics from being run. I can not say the same for solutions such as Plausible,
which suggests they are trusted for their privacy by independent persons.

If you need any more information, please contact me!

**Comment by apmorton** [comment]
I can't speak for @mattgodbolt, and ultimately this would be his decision - so I will leave this open for now.

However, I can provide a little context and background into exactly how GA is used on compiler explorer.

- we have a privacy policy that discusses the use of cookies and is displayed prominently to all users visiting the site
- users much explicitly consent to the use of cookies
- GA is not initialized unless the user explicitly consents to the cookie policy

As a result, unless a user reads our cookie policy (which clearly indicates the use of GA) and consents to it they will not be subject to any client side analytics.  The website will function identically regardless of the users cookie consent status.

**Comment by mattgodbolt** [comment]
Thanks @resynth1943 for filing this, and @apmorton for replying. I agree with everything @apmorton says here. GA was a great choice for us in the early days, and is still not a bad solution. I disagree that removing GA "greatly improves the privacy"; like Austin says, it's pretty much opt-in. When we moved from default settings to opt-in, our GA counters dropped to 20% of their prior values, so many people are choosing not to use it.

That said: for reasons other than privacy, we may choose to move to a different analytics solution. Some of the things you mention (like browser blocking etc) are an issue. I'll leave this bug open both for discussion and for an eventual place to track if  we decide to move.

We already use other proprietary things like AWS, StatHat, PaperTrail, Sentry, StatusCake, and moving away from proprietary systems in general is not a goal of ours.

As a final point; I'll admit the sneer-quotes around " 'functionality' " initially riled me a little in your filing; as did the allusion that GA is somehow unethical.  Disclosure: I worked at Google 2010-2012ish and so have a pretty solid understanding of what went on at least then, and I trust in my friends who still work there and are involved with some of this stuff.

**Comment by mattgodbolt** [comment]
> This commit removes the Google Analytics 'functionality' from this page. Following on
> from the previous commit, this change also greatly improves the privacy of
> unsuspecting users.

Just checking: was there a commit associated with this that I missed, or is this a copy paste from another repo?

**Comment by resynth1943** [comment]
Ahh, I have worded that wrongly. What I meant was I would be happy to submit a comment. My humble apologies :-)

**Comment by resynth1943** [comment]
> When we moved from default settings to opt-in, our GA counters dropped to 20% of their prior values, so many people are choosing not to use it.

That's an interesting point you've raised. Over 10 million people use something like uBlock Origin too, and that blocks Google Analytics by default...

**Comment by resynth1943** [comment]
> As a final point; I'll admit the sneer-quotes around " 'functionality' " initially riled me a little in your filing; as did the allusion that GA is somehow unethical. Disclosure: I worked at Google 2010-2012ish and so have a pretty solid understanding of what went on at least then, and I trust in my friends who still work there and are involved with some of this stuff.

Apologies for the sarcastic tone. In retrospect, that was rude.

Nevertheless, while I can appreciate that there are good people working at Google, the overall actions from the company are shocking. In my opinion, Google is a devious and unethical company.

There's a good website that sums this up. Mind the expletives: [it's here](https://fuckoffgoogle.de)

---

> That said: for reasons other than privacy, we may choose to move to a different analytics solution.

Thanks for being so open to suggestions! :-)

**Comment by mattgodbolt** [comment]
> Apologies for the sarcastic tone. In retrospect, that was rude.

I understand folks feel strongly about this :) No harm done at all, and in fairness I could be just a little biased towards my alma mater.

> Nevertheless, while I can appreciate that there are good people working at Google, the overall actions from the company are shocking. In my opinion, Google is a devious and unethical company.
> 
> There's a good website that sums this up. Mind the expletives: [it's here](https://fuckoffgoogle.de)

Thanks: I'll take a look.

> > That said: for reasons other than privacy, we may choose to move to a different analytics solution.
> 
> Thanks for being so open to suggestions! :-)

No problem at all: no promises, but it happened to come up in conversation recently with friends to switch away, so I'm more receptive than perhaps I would have been otherwise :)

**Comment by mattgodbolt** [comment]
(re other choices, the one that came up with my friend was clicky.com -- have not looked at that, but recording it here for completeness' sake).

**Comment by resynth1943** [comment]
Can't say I've heard of it. Is it FOSS?

**Comment by mattgodbolt** [comment]
No; I don't believe so (but not looked at it yet properly)
