### ISSUE TITLE
Library linking experience thread

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2079]
**About the current state of library linking support**

_This is still mostly experimental an experimental feature, and we would like input on things that either don't work or "would be nice if"._

* We now _try_ to build a couple of C++ libraries for all _working_ compilers and for a small number of variations
  - Variants currently are a mix of x86_64/x86/defaultcompilertarget and if Clang stdlibc++ or libc++

* You can find a complete list at https://conan.compiler-explorer.com/libraries.html
  - Before submitting a bugreport about linking errors, please check this list first. If it is missing, and you're absolutely positive it should be building for the compiler of your choice, please check https://conan.compiler-explorer.com/failedbuilds.html for the logging for the failed builds. If it has an unreasonable error you cannot reproduce locally, please do submit a bug report.

* Be aware that libraries are mostly built for the default std version the compiler assumes and not for any other versions (of course, anything >= C++11 _should_ be compatible, but there might be specific examples of where ABI cross-compatibility is broken. If there's any specific use case that you would like to see supported, please make sure you supply the needed examples with any bug report you make and your motivation of why this is a common use-case.

* There are always special compiler flags that break ABI compatibility between library and compiler. If there's a common use-case that you can provide, please do including motivation and examples.

* CE should automatically download and add the right libraries to the command line for linking, save for some exceptions with libraries that provide extra "main" binaries (see Catch2 and Google Test)
  - Note that when you use the "Compile to binary" option, you will need to circumvent our feature that injects `int main() {}` into your code, you can do this with just a comment like `// int main() {}` somewhere in your code.

* Unchanged: All the C shared libraries (openssl, cs50 and now also libuv) are built as usual with just one x86_64 and one x86 version

**About trunk versions**
* Trunk version of libraries aim to build every night if there are new commits on the library branch - but this is no way guaranteed - we would ask you to please mostly just use tagged versions.
* None of the libraries are rebuilt when it's the _compiler's trunk_ that's changing, please don't send a bug report about this.

**About submitting new libraries**
* If you're a library developer, please note the section about linking here https://github.com/compiler-explorer/compiler-explorer/blob/master/docs/AddingALibrary.md#adding-a-library-that-needs-to-be-compiled-to-a-or-so-binaries
 - (TLDR: please use CMake and don't ignore the contents of CXX, CXXFLAGS, etc)
* There's currently no support for generated header files based on the build-environment, and this is hard to make compatible with CE regardless. If you're a library developer and think you really do need these and if you can help us support it, feel free to contact us.

**About Catch2**
* Known issue: Catch2 only really supports linking binaries from v3, and there are no working variants of earlier versions in any way. (as in, you can compile to assembly, but you can't link or run code using Catch2)
* If you want the Main function supplied by this library, add -lCatch2Main to your compiler arguments
* There's a 10s limit for execution, if you use the benchmark functionality of Catch2 you will probably hit that limit after 1 or 2 benchmarks. https://github.com/compiler-explorer/compiler-explorer/issues/2079#issuecomment-679275025

**About Google Test**
* If you want the Main function supplied by this library, add -lgtest_maind to your compiler arguments

**About Google Benchmark**
* We have a limit for 10s on execution, so your benchmarks might not always complete if you combine them all in one program. But if all fails, you can still always use https://quick-bench.com/ for this.

**About TBB**
* Known issue: https://github.com/compiler-explorer/compiler-explorer/issues/2075

**Be kind**
* Even though linking and executing with libraries is new and exciting, it's not going to be lightning-fast. So be patient, and perhaps leave the automatic compiling feature off if you don't want to be interrupted while typing.
![image](https://user-images.githubusercontent.com/442630/87491455-7587cb00-c648-11ea-9b3d-1703926a67f9.png)
* If you have an example that consistently fails to compile or execute due to time limits, let us know, maybe we can help.

**Have fun executing!**

**Comment by horenmar** [comment]
You might want to add a note about the runtime limit to Catch2 as well - it also provides benchmarking
