### ISSUE TITLE
[BUG] Google Benchmark only shows 1 mark before failing

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2080]
Could be because of execution time, but seems strange as it's usually done fast.
It's cut off somewhere by NSJail, but unknown why.

Example: https://www.godbolt.org/z/nEndcb

**Comment by apmorton** [comment]
Google says:
> 27.2 * 43652639 nanoseconds to seconds
> 1.18735178 seconds

If we assume the second benchmark is taking roughly the same time, it makes perfect sense.

We allow 2s wall clock time for user executions, so its getting cut short sometime just before printing out the results for the second benchmark.

**Comment by partouf** [comment]
Ah ok. And it doesn't really seem like we can change the way the library behaviour here.
So just a thing that can't be helped, I guess?

**Comment by apmorton** [comment]
We can always increase the execution timeout - 2s was a fairly arbitrary choice afaik, and under nsjail users are limited to 50% of a single core.

I don't see much harm in increasing the timeout to something like 10s.

We do need to worry about hard upper limits on cloudfront/elb timeouts eventually, but that's something for another day.

IE, if we increase the timeouts too high and a user gets worst case execution time in the compiler _and_ user code, we might timeout downstream anyway.

**Comment by partouf** [comment]
Sounds reasonable. @mattgodbolt what do you think about this?

**Comment by mattgodbolt** [comment]
100% up for bumping to 10s. And yeah, all arbitrary! :) Let's increase and see what breaks!

**Comment by partouf** [comment]
I'm looking at our config places, but actually not sure where we can set that up to be 10s ?

**Comment by apmorton** [comment]
It's a trick question - the option is used in code, but never actually defined in any of our config files. We have been relying on the hardcoded default value this whole time.

I can't remember exactly what it's called, but if you search for 2000 it should be there somewhere.

**Comment by partouf** [comment]
Oh found it!

**Comment by partouf** [comment]
Fixed
