### ISSUE TITLE
[REQUEST] C++ include Agner Fog's vector class library

### ISSUE THREAD

**Issue by Saitama10000** [compiler-explorer/compiler-explorer#2099]
Include Agner Fog's vector class library: https://github.com/vcoda/vectorclass. It's a really useful library for vector optimisations in scientific computing. It forces the compiler to use vector instructions.

**Comment by partouf** [comment]
This library is already available in CE, it's called VCL in the library dropdown

**Comment by Saitama10000** [comment]
Found it in gcc compiler! Thank you!
