### ISSUE TITLE
[BUG] Fortran adds space at the start of stdout when executing

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2100]
**Describe the bug**
When executing Fortran code:
```
program hello
      print *, "hello world"
      call exit(123)
end program hello
```

The API returns the following:
```
  code: 123,
  okToCache: true,
  stdout: [ { text: ' hello world' } ],
  stderr: [],
  didExecute: true,
```

Note the extra space in the stdout text. In the assembly, the space character is not there in the string, so it's unlikely coming from the code. When I do add an extra space to the string, there will be 2 spaces in stdout (and only 1 in the assembly).

**Link**
https://compiler-explorer.com/z/bqrv6h

**Comment by awvwgk** [comment]
I don't think this is actually a bug. The output of list directed IO is implementation dependent in Fortran. See https://fortran-lang.discourse.group/t/list-directed-output/317 for a comparison between different formats chosen by different Fortran compilers.

Most Fortran compilers choose to add a leading space in list directed IO which is than found in the standard output as well. To get a deterministic output across compilers the format string should be specified explicitly.

**Comment by partouf** [comment]
Thanks for the comment. Indeed I see that's just how formatting works in Fortran.
It seems you can't even avoid it even. Bit crazy.

Anyway, thanks!

**Comment by awvwgk** [comment]
You can by specifying a format string instead, in your example this would be

```f90
program hello
      print "(a)", "hello world"
      call exit(123)
end program hello
```

**Comment by partouf** [comment]
Got it, thanks!
