### ISSUE TITLE
Support "think-cell/range" library

### ISSUE THREAD

**Issue by Quuxplusone** [compiler-explorer/compiler-explorer#2101]
It might be nice to support https://github.com/think-cell/range , a C++ header-only library that provides a "post-C++20" idea of ranges.

It's intended to be included as `#include <tc/range.h>`.

[lang-c++] [new-libs]

**Comment by partouf** [comment]
Unfortunately it looks like the example can't be compiled with either gcc or clang and it doesn't look like anyone is maintaining it anymore. So I'm closing this issue for now.

**Comment by Quuxplusone** [comment]
Yeah, you're right. I noted the breakage on their repo here: https://github.com/think-cell/range/pull/22#issuecomment-690681165

**Comment by treh** [comment]
Hi, I've updated the think-cell/range library. Could we give it another try?
