### ISSUE TITLE
[BUG] clang compiler using the gcc source code when I test std::vector<bool>

### ISSUE THREAD

**Issue by hewillk** [compiler-explorer/compiler-explorer#2105]
**Describe the bug**
When I test the `sizeof std::vector<bool>`, both gcc and clang all say that size is [`40`](https://godbolt.org/z/as1MKa), but this is not true for clang since I look up the implementation, so I try to access the protected member variable `_M_impl` of gcc implementation:

  ```
std::vector<bool> v;
  std::cout << sizeof(v._M_impl) << '\n';
```

 [**then clang output the same compiler error message as the gcc**:](https://godbolt.org/z/76oj9b)

```
<source>:7:23: error: cannot cast 'std::vector<bool>' to its protected base class 'std::_Bvector_base<std::allocator<bool> >'
  std::cout << sizeof(v._M_impl) << '\n';
                      ^
/opt/compiler-explorer/gcc-9.3.0/lib/gcc/x86_64-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/stl_bvector.h:592:34: note: declared protected here
    class vector<bool, _Alloc> : protected _Bvector_base<_Alloc>
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:7:25: error: '_M_impl' is a protected member of 'std::_Bvector_base<std::allocator<bool> >'
  std::cout << sizeof(v._M_impl) << '\n';
```

**Expected behavior**
`std::cout << sizeof(std::vector<bool>) << '\n';`
gcc will print `40`, but clang will print [`24`.](https://wandbox.org/permlink/TUtU93NJOPr6VgCS)

**Comment by apmorton** [comment]
On linux clang uses libstdc++ by default. In order to use libc++ with clang you need to specify `-stdlib=libc++`

https://godbolt.org/z/PjqEaj
