### ISSUE TITLE
[rust] Add rand to allow evaluating const fn with const parameter vs constfn with variable parameter

### ISSUE THREAD

**Issue by eddyp** [compiler-explorer/compiler-explorer#2106]
The Rust compiler optimizes const fn to a hardcoded value, if the parameter(s) are constant or compile time evaluable.
But this means that if the const fn function is called with a variable, because the compiler is smart enough, the compiler will still generate a hardcoded value, as the expression can be evaluated at compile time, preventing the godbolt user to understnad what will be the proper generated code in real-life situations.

See example code here: https://godbolt.org/z/8xnEae

**Comment by mattgodbolt** [comment]
This seems like a rust compiler feature: Compiler Explorer shows what the compiler does, and indeed most of the time this is the feature users want: to understand the kinds of transformations the compiler is capable of doing.

If you want to see the compiler generate code for an unknown value, ensure it's not known to the compiler: https://godbolt.org/z/EWsvrx

There's no need to invoke `rand()`, just ensure the value is a unknown parameter. If you want `main()`, then use the number of arguments (I'm not good enough at rust to know how to do this!)

**Comment by partouf** [comment]
I was going to mention that you could also make it depend from a command line argument (https://godbolt.org/z/jv1a1r), but it seems Rust generates a whole bunch of library code for that to be possible so it's less readable than just having an unknown argument as a function parameter.

**Comment by eddyp** [comment]
> This seems like a rust compiler feature: Compiler Explorer shows what the compiler does, and indeed most of the time this is the feature users want: to understand the kinds of transformations the compiler is capable of doing.
> 
> If you want to see the compiler generate code for an unknown value, ensure it's not known to the compiler: https://godbolt.org/z/EWsvrx
> 
> There's no need to invoke `rand()`, just ensure the value is a unknown parameter. If you want `main()`, then use the number of arguments (I'm not good enough at rust to know how to do this!)

Fair enough. The only problem I still sort of have is the inlining aspect of it, but I guess that should be obvious to some degree, in spite of the repetition: https://godbolt.org/z/165WhT
