### ISSUE TITLE
[BUG] Linking to Catch2 with compiler "arm gcc 8.2" takes forever

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2107]
The binaries are stored on the Conan server, so I'm not sure why this is taking forever, will need to test locally

https://godbolt.org/z/z7rj7f

**Comment by partouf** [comment]
Tested locally;
- Compilation works fine and is pretty fast
- The resulting binary is 3.3 MB
- The ASM from the objdump is 25 MB and takes 48 seconds to dump to a file
- Fill in the rest

Removing -l from the objdump command seems to improve the dump speed massively to a mere 1 second execution (while the output is 18 MB), but of course, then you miss the .loc annotations. (tested with this change in CE and it's not great, but at least it's faster)

So to conclude - I have no idea what to do about this.

**Comment by apmorton** [comment]
maybe in general a max binary size for objdump would be a good start?
It won't fix things, but it should prevent us (and users) from wasting cycles waiting for a result that will probably never come

```
if (binarySize > x)
    bail('https://i.imgur.com/9A3JOEv.gif')
```

**Comment by partouf** [comment]
Oh that's not a bad idea.
I was already wondering really complicated streaming technologies that stream in more details when they're available 😅 but size check would be a better solution

**Comment by partouf** [comment]
Funny thing, I can't reproduce linked example, because I'm getting a libstdc++ error (iosfwd missing).
Tried to install bunch of apt packages that we do on live, but expect something is different between ubuntu 18 and 20 that produces this.
Of course to be expected, because the standard c++ lib isn't actually available specifically for this arm target. But it "works" in our current production env.

Ping #2018 for relevance to this.

**Comment by partouf** [comment]
Have tested with gcc 10.1 x86-64, which produces a 3MB+ executable as well, and produces 34MB of assembly through objdump, but is processed way quicker by both objdump and CE.

So I don't think checking for size is the answer here.

**Comment by partouf** [comment]
> Funny thing, I can't reproduce linked example, because I'm getting a libstdc++ error (iosfwd missing).
> Tried to install bunch of apt packages that we do on live, but expect something is different between ubuntu 18 and 20 that produces this.

With the new Ubuntu instances, this still has the same behaviour as before on CE. So this was not the difference after all.
