### ISSUE TITLE
[REQUEST] New release of ISPC compiler, please update to v1.14.0.

### ISSUE THREAD

**Issue by pbrubaker** [compiler-explorer/compiler-explorer#2112]
Hey CE team.

We have a new release of the ISPC compiler.  Would you be so kind to add it to CE?  Thank you!

https://github.com/ispc/ispc/releases/tag/v1.14.0

Cheers!

Pete

**Comment by apmorton** [comment]
ispc 1.14.0 is now live

**Comment by pbrubaker** [comment]
Thanks Austin!
