### ISSUE TITLE
font error for

### ISSUE THREAD

**Issue by hgedek** [compiler-explorer/compiler-explorer#2118]
**Describe the bug**
If you enter multiple 'f' character its width changes and sometimes 'ff f' an not-exist space occurs

**To Reproduce**
Using multiple 'f' character side by side

**Expected behavior**
No width change

Font: Consolas, "Liberation Mono", Courier, monospace
Mode: dark

<img width="188" alt="Screenshot 2020-08-03 at 18 22 17" src="https://user-images.githubusercontent.com/876881/89209976-339ed480-d5b7-11ea-82e5-0d6b17af63e0.png">

**Comment by partouf** [comment]
Which Browser and OS are you using?

**Comment by apmorton** [comment]
also, do you have the "Enable font ligatures" option checked right below the font textbox in the settings modal?

**Comment by hgedek** [comment]
Which Browser and OS are you using? safari

also, do you have the "Enable font ligatures" option checked right below the font textbox in the settings modal? Yes

**Comment by apmorton** [comment]
"Enable font ligatures" is a non-default option (afaik?), and it seems to be working as intended here.

See #1653 for more information
