### ISSUE TITLE
[BUG] llvm-mca Intel options not being passed to tool

### ISSUE THREAD

**Issue by RabsRincon** [compiler-explorer/compiler-explorer#2119]
**Describe the bug**
Currently, the extraArgs calculated on the llvm-mca tool are not merged with the passed arguments to the tool

**Link**
https://github.com/compiler-explorer/compiler-explorer/blob/master/lib/tooling/llvm-mca-tool.js#L47

**Additional context**
Found with the new ESLint plugin rules :)

**Comment by partouf** [comment]
Commit history leads me to believe these extraArgs were never in use.
They do seem to be valid command line arguments for llvm-mca.

It doesn't seem like it has any issues with AT&T assembly; https://godbolt.org/z/jMYzvP
And when switching to Intel on the same source, the simulation is exactly the same.
So I'm guessing llvm-mca has builtin detection for this, and there's no need to pass it to the tool.

**Comment by partouf** [comment]
Oh wait, we still need to remove these lines. Should work without problems (have checked and tested earlier) -> remove lint commit push.

**Comment by partouf** [comment]
should be fixed by https://github.com/compiler-explorer/compiler-explorer/commit/3a5420f3d2ffb6a714dba7cd381fa3fdee99fbf8
