### ISSUE TITLE
[REQUEST] Add more {clang,CUDA} versions to CUDA compilation.

### ISSUE THREAD

**Issue by Artem-B** [compiler-explorer/compiler-explorer#2122]
Sometimes it's useful to see the differences produced by different clang versions during CUDA compilation. Currently godbolt has multiple NVCC versions, but only trunk clang, even though clang has been supporting CUDA for quite a few versions now.

Unlike NVCC clang is not tied to particular CUDA version, so, ideally, we'd need a full cartesian product of {clang, CUDA} versions, but that would probably be an overkill. 

The most useful set would probably include multiple clang versions running with the latest CUDA. This would allow debugging regressions in clang. Second tier would be to run trunk clang with multiple CUDA versions. This would help telling the differences between CUDA versions.

Alternatively, selection of the CUDA version may be implemented by allowing user to specify --cuda-path=X/Y/Z. I.e stage symlinks to CUDA under `/sandbox` and document that users can use `--cuda-path=/sandbox/cuda-11.0` 

Clang will currently produce a warning about 'unsupported CUDA version' is used w/ CUDA newer than 10.1, but that can be safely disabled in this case. The warning is to indicate that despite being able to use CUDA-10.2/11, clang does not support news instructions/intrinsics/builtins introduced by the new CUDA versions. Anything it could compile with CUDA-10.1 it is expected to compile with the newer CUDA.

**Comment by jeremy-rifkin** [comment]
We now have some more clang cuda versions
