### ISSUE TITLE
[BUG] Cannot browse the whole editor screen(mobile)

### ISSUE THREAD

**Issue by 0gap** [compiler-explorer/compiler-explorer#2126]
When browsing at my samsung android device, I cannot see the whole screen.

**Expected behavior**
I would expect to see the whole screen. 

**Screenshots**
This is after pressing the consent button. The consent area didn't go away. 
![20200807_075704.jpg](https://user-images.githubusercontent.com/11653149/89611067-da6bc500-d884-11ea-98d9-350f75209de8.jpg)

This is the bottom of my screen after reloading. The area has gone but still cannot browse the whole code. 
![SmartSelect_20200807-080747_Chrome.jpg](https://user-images.githubusercontent.com/11653149/89611161-2585d800-d885-11ea-86df-df07650665d3.jpg)

**Comment by partouf** [comment]
I think we fixed the screen height / blanking issues a while ago. Closing until I hear otherwise
