### ISSUE TITLE
[BUG] all clang arm compilers fail when including/using cmath

### ISSUE THREAD

**Issue by Hoernchen** [compiler-explorer/compiler-explorer#2131]
**Describe the bug**
Merely including cmath to use fabs with clang-arm leads at best to a linker error with clang-9, assembly error with clang-9 with -O1 or higher opt level, or inability to find the header with clang-10

**Expected behavior**
I'd expect at least one usable clang arm version...

**Link**
https://godbolt.org/z/58r5dK - try -O1 instead of -O0 to get asm errors with clang-9

**Comment by partouf** [comment]
Related to https://github.com/compiler-explorer/compiler-explorer/issues/2018 due to incompatible x86 bits being used

**Comment by partouf** [comment]
This is now fixed!
