### ISSUE TITLE
[REQUEST] Make "Sum over array (Optimized)" example for Rust equivalent to the C++ version

### ISSUE THREAD

**Issue by redzic** [compiler-explorer/compiler-explorer#2133]
Currently, the "Sum over array (Optimized)" example for C++ assumes that `input`'s length is a multiple of 64, however the Rust version of the example does not.

The Rust example should be changed to something like:

```rust
// Compile with -C opt-level=3 -C target-cpu=native to see autovectorization
// assumes input's length is a multiple of 64
pub fn sum_array(input: &[i32]) -> i32 {
    if input.len() & 63 != 0 {
        unsafe { std::hint::unreachable_unchecked() }
    }

    input.iter().sum()
}
```

The generated assembly with `-C opt-level=3 -C target-cpu=native` on rustc 1.45.2 is then very similar to clang 10 on x86 with `-O3 -march=native` on the optimized sum over array example for C++.

Alternatively, the following example might be arguably more equivalent to the C++ version, however it is not really idiomatic Rust.

```rust
// Compile with -C opt-level=3 -C target-cpu=native to see autovectorization
// assumes input's length is a multiple of 64
pub fn sum_array(input: &[i32]) -> i32 {
    let len = input.len();
    let input = input.as_ptr();

    if len & 63 != 0 {
        unsafe { std::hint::unreachable_unchecked() }
    }

    let mut sum = 0;
    for i in 0..len {
        sum += unsafe { *input.add(i) };
    }

    sum
}
````
As of rustc 1.45.2, this generates slightly fewer instructions than the idiomatic Rust version, but I think if the Rust example were to be changed, it should use the idiomatic version that was previously listed.

Another version which aligns `input`:
```rust
// Compile with -C opt-level=3 -C target-cpu=native to see autovectorization

#[repr(align(64))]
pub struct Aligned<T: ?Sized>(T);

// assumes input is aligned on 64-byte boundary and that
// input's length is a multiple of 64.
pub fn sum_array(input: &Aligned<[i32]>) -> i32 {
    let len = input.0.len();
    let input = input.0.as_ptr();

    if len & 63 != 0 {
        unsafe { std::hint::unreachable_unchecked() }
    }

    let mut sum = 0;
    for i in 0..len {
        sum += unsafe { *input.add(i) };
    }

    sum
}
```

**Comment by partouf** [comment]
I have no knowledge or opinion about this, but I do know the examples used to be different and that they were changed to be more rusty and less c++y

https://github.com/compiler-explorer/compiler-explorer/commit/91a35e65d4990d05165849c274a7ba261d0a54da#diff-20cc867123eb91883fd19901cbaef81d

So I don't know if we want to change it back again. But I am open to adding more examples. Just give it a nice name, add it to the examples/rust folder and send us a PR.

**Comment by partouf** [comment]
examples are now live
