### ISSUE TITLE
[QUESTION] Is there reading from standard input supported?

### ISSUE THREAD

**Issue by peterschussheim** [compiler-explorer/compiler-explorer#2139]
Thank you Matt and all contributors for this project; it is such a valuable tool.

I tried searching the issues , wiki, and a few google searches but still didn't find a conclusive answer regarding support for reading data from standard input.

**Comment by partouf** [comment]
If you click the "Add new" button where your editor is, you can click on "Execution only". There will be a Stdin option there.
![image](https://user-images.githubusercontent.com/442630/90292270-e3aaf200-de81-11ea-9a22-f75eb4bb2d9a.png)

**Comment by peterschussheim** [comment]
Thank you @partouf for the fast response, I will close this issue now.
