### ISSUE TITLE
[REQUEST] Add Go compiler support for WebAssembly (js/wasm)

### ISSUE THREAD

**Issue by finnbear** [compiler-explorer/compiler-explorer#2145]
**Is your feature request related to a problem? Please describe.**
I compile Go to Wasm but I don't see that combination in compiler explorer

**Describe the solution you'd like**
Please add at least one version of the Go compiler that supports `js/wasm` to compiler explorer.

**Additional context**
- https://github.com/compiler-explorer/compiler-explorer/issues/125#issuecomment-546612485
- I requested this feature in an email, and just discovered I could post a request here

**Comment by partouf** [comment]
Apparently we need to pass environment variables to Go to get this https://golangbot.com/webassembly-using-go/

**Comment by finnbear** [comment]
Yes, just like any other non-default go arch. Here's the command I compile my project with:
```sh
GOOS=js GOARCH=wasm go build -o output.wasm *.go
```

**Comment by partouf** [comment]
This is now live https://godbolt.org/z/WM48sb
