### ISSUE TITLE
Simple convenience Bug: Scrolling all the way down in code editor

### ISSUE THREAD

**Issue by nuuSolutions** [compiler-explorer/compiler-explorer#2149]
Every other Editor since ca. 1990:
**Scrolling down is allowed until the last line is _at the top_ of the view**

Godbolt 😉:
Let's not do this. It's probably undefined behavior.
**Last line remains at the very bottom.**

**Comment by NUU-Solutions** [comment]
Wow, working great, thanks. 
At first I thought my request was just put in the bin, but actually it was resolved in no time.
