### ISSUE TITLE
[BUG] threads.h is missing

### ISSUE THREAD

**Issue by GabrielRavier** [compiler-explorer/compiler-explorer#2151]
**Describe the bug**
threads.h seems to be missing from Godbolt : Trying to use results in it not being found

**To Reproduce**
1. Go [here](https://godbolt.org/z/a3McGh)
2. Observe and be in awe of the wonderful `fatal error: 'threads.h' file not found` error

**Expected behavior**
Having the header be found and work properly

**Comment by apmorton** [comment]
CE currently runs on ubuntu 18.04, and we use system provided glibc - [which is 2.27 on ubuntu 18.04](https://godbolt.org/z/earr6z)

[threads.h didn't land in glibc until 2.28](https://sourceware.org/bugzilla/show_bug.cgi?id=14092#c10)

This will get fixed "for free" when we upgrade to 20.04 LTS: https://github.com/compiler-explorer/infra/issues/376

**Comment by partouf** [comment]
Ubuntu has been upgraded and so this issue has been resolved.
