### ISSUE TITLE
[REQUEST] Please add msvc v19.27 to https://godbolt.org

### ISSUE THREAD

**Issue by N-Dekker** [compiler-explorer/compiler-explorer#2155]
It would be very helpful to me to have access to the latest released Visual C++ compiler at https://godbolt.org/  At the moment, that is Visual Studio 2019 Version 16.7.2 Compiler Version 19.27.29111, but any "19.27.*" would be fine to me. (As far as I can see, the latest version at https://godbolt.org is still msvc v19.24.)

At the moment I'm specifically interested to access msvc v19.27 online, as I encountered a [recently introduced Visual C++ compiler bug](https://developercommunity.visualstudio.com/content/problem/1145942/vs2019-internal-compiler-error-using-restrict-keyw.html ) that I would like to try to reproduce at https://godbolt.org

**Comment by partouf** [comment]
Updating these compilers is part of godbolt.ms which is in the hands of Microsoft. And subsequently handled through the vs websites; https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+idea&type=question+OR+problem+OR+idea&c=&redirect=search%2Fsearch&sort=relevance&q=%22compiler+explorer%22

**Comment by N-Dekker** [comment]
@partouf Thanks for the information, Patrick. I just added a comment to https://developercommunity.visualstudio.com/idea/1103658/provide-latest-c-compiler-versions-on-compiler-exp.html and now I'll just close this compiler-explorer issue!
