### ISSUE TITLE
[REQUEST] cc65 "trunk" freshness

### ISSUE THREAD

**Issue by jmr** [compiler-explorer/compiler-explorer#2158]
Using "6502 cc65 trunk", --version says `cc65 V2.17 - Git f95481f`
https://godbolt.org/z/avsMrM

This is from 2019-03-30, 1.5 years ago.
https://github.com/cc65/cc65/commit/f95481f

Would it be possible to keep this up to date more like every month?

**Comment by partouf** [comment]
I agree that this would be nice. I think at the time it was just a matter of putting it up and waiting for someone to actually use it. But if there's active development and people are using it, I'm all for making this a nightly build.

**Comment by jmr** [comment]
Yes, there's definitely active development:
https://github.com/cc65/cc65/commits/master

**Comment by mrdudz** [comment]
+1 please

**Comment by jmr** [comment]
There's also now a [2.19 release](https://github.com/cc65/cc65/releases/tag/V2.19), vs 2.17 which is currently used.

**Comment by partouf** [comment]
V2.18 and V2.19 are now up, and the trunk is now being built daily
