### ISSUE TITLE
"All rights reserved." in License

### ISSUE THREAD

**Issue by qlcom** [compiler-explorer/compiler-explorer#2159]
Do you really want that?

**Comment by qlcom** [comment]
The license used for new code in OpenBSD doesn't have this sentence.

**Comment by apmorton** [comment]
"All rights reserved." was historically required to be stated in order to assert your copyright - it's a lingering relic of the past, but is ultimately harmless.

It does not change your rights to use the code here in any way.

**Comment by qlcom** [comment]
Then how does OpenBSD do it?

**Comment by apmorton** [comment]
As stated, it is no longer strictly required - it's just pretty innocuous, and as such there is no benefit to remove it.
See https://en.wikipedia.org/wiki/All_rights_reserved#Obsolescence

For the record, I am not a copyright lawyer.

**Comment by qlcom** [comment]
having this sentence made the license look bad.

**Comment by qlcom** [comment]
> there is no benefit to remove it.

There is no benefit in having it.

**Comment by apmorton** [comment]
Githubs own template for BSD 2 clause contains the phrase

![image](https://user-images.githubusercontent.com/63636/91460349-b5e88480-e855-11ea-8062-55b56c14358c.png)

🤷

**Comment by qlcom** [comment]
Github has nothing to do with open source. It's a proprietary sh*t.

**Comment by qlcom** [comment]
https://git.sr.ht/~sircmpwn/core.sr.ht/tree/master/LICENSE

Another one. BSD style, without that sentence.

**Comment by apmorton** [comment]
I doing this this is going anywhere productive, so I am locking as off-topic for now.
I will leave this open so @mattgodbolt can take a look himself and decide what to do.

**Comment by mattgodbolt** [comment]
Thanks for your concern @qlcom but this is not something we're looking to fix. We have super limited resources and no will to deeply look in to this.
