### ISSUE TITLE
[BUG] **msvc support slow and not up to date**

### ISSUE THREAD

**Issue by nuuSolutions** [compiler-explorer/compiler-explorer#2163]
Not sure about your priorities, but this can't be right:

Compiling a simple test:
clang: under 0.5sec
msvc: over 10sec   --- can it really be that slow or is there some bottleneck?
It's not just today, last week was the same.

Why is the version stuck at 19.24? (about 9 month old i think)

**Comment by mattgodbolt** [comment]
We rely on Microsoft to administrate and update a separate server running Windows that provides compilation for Compiler Explorer (it's directly viewable at https://www.godbolt.ms/ if you want to try it there).  If the issues are visible on the godbolt.ms, we'll need to take this up with Microsoft.

**Comment by mattgodbolt** [comment]
CC @strega-nil - www.godbolt.ms does indeed seem very slow.

**Comment by strega-nil** [comment]
Yeah, we've got someone working on it right now. I haven't had the time to go and look at it seriously, but we now have a specific person who is actually taking care of it as their primary duty right now.

**Comment by simevo** [comment]
keep it up ! I'm looking forward to getting msvc 19.27 in godbolt because of: https://stackoverflow.com/questions/63288453/visual-studio-2019-c-not-recognizing-template-friends

**Comment by PwndDepot** [comment]
Also the x86 version of msvc has been missing for months.

**Comment by partouf** [comment]
I'm closing this issue. New versions including v19.27 have been in there for a while. x86 was never added, we can do something about that some other time.
