### ISSUE TITLE
[REQUEST] Exempt `.inst` directive from directive filter

### ISSUE THREAD

**Issue by ketsuban** [compiler-explorer/compiler-explorer#2164]
**Is your feature request related to a problem? Please describe.**
Compilers may insert a deliberately-invalid instruction using the `.inst` assembly directive in some contexts, such as after no-return functions or with builtins like gcc/clang's `__builtin_trap` and rustc's `core::intrinsic::abort`. This gets filtered out by the directive filter, but more often than not I actually want to see it.

**Describe the solution you'd like**
I'd like the `.inst` directive to not be filtered out with other directives.

**Describe alternatives you've considered**
Turning off the directive filter makes the `.inst` directive visible, but since directives are a large source of noise in the assembly output this is suboptimal. Another option would be trying to make use of objdump for assembly output, since it renders intentionally-invalid instructions more sensibly (e.g. Rust's abort intrinsic on ARM ends up being `udf #254`), but I imagine this is a larger undertaking.

**Comment by partouf** [comment]
Do you have a link with an example that emits this directive?

**Comment by ketsuban** [comment]
Sure, [here's one](https://godbolt.org/z/qe8rj7) in C and [here's one](https://rust.godbolt.org/z/WM57c6) in Rust.

**Comment by partouf** [comment]
https://sourceware.org/binutils/docs/as/ARM-Directives.html
```
.inst opcode [ , ... ]
.inst.n opcode [ , ... ]
.inst.w opcode [ , ... ]
Generates the instruction corresponding to the numerical value opcode. .inst.n and .inst.w allow the Thumb instruction size to be specified explicitly, overriding the normal encoding rules.
```

I think, considering this results in an unnamed opcode, and the objdump is not available for a lot of arm targets, that there should probably be an exception for this directive.

**Comment by mattgodbolt** [comment]
Agreed @partouf

**Comment by partouf** [comment]
This change is now live
