### ISSUE TITLE
[BUG] Rust nightly with llvm-ir output tab, "could not copy" error

### ISSUE THREAD

**Issue by justanotherdot** [compiler-explorer/compiler-explorer#2165]
**Describe the bug**

Hi there!

Possibly related to https://github.com/compiler-explorer/compiler-explorer/issues/942, I seem to be able to compile any Rust code in the playground with assembly output under nightly just fine, but if I try to add `llvm-ir` output I get "<compilation failed>" under the assembly pane with the compiler output pane showing:

```
error: failed to remove ./output.example.3a1fbbbh-cgu.0.rcgu.s: No such file or directory (os error 2)


error: aborting due to previous error


Compiler returned: 1
```

**To Reproduce**

1. (almost) Any rust code should do it, here's a minimal example:

```
pub fn main() {
    println!("hello");
}
```

2. Attach an assembly output pane if not already present
3. Select `Rust nightly` from the dropdown
4. From the assembly pane, click on `+ Add new` and select `IR output`

**Expected behavior**

I expect it to compile just as it would without the `IR output` pane present. 

**Link**
https://godbolt.org/z/33fnoo

**Screenshots**
![image](https://user-images.githubusercontent.com/5350032/91775075-8c50a400-ec2d-11ea-8049-cb39b952c4b0.png)

**Desktop**

- OS

```
$ cat /etc/issue
Debian GNU/Linux bullseye/sid \n \l
$ uname -a
Linux <snip> 5.7.0-1-amd64 #1 SMP Debian 5.7.6-1 (2020-06-24) x86_64 GNU/Linux
```
 - Browser 
firefox
 - Version 
78.0.2

**Additional context**
If I muck around a bit (say, dropping all the content from the `println!` macro's format string) I can get the compiler to run, but all I see is assembly output rather than the additional llvm-ir output:

![image](https://user-images.githubusercontent.com/5350032/91775418-57911c80-ec2e-11ea-9c73-093f46d170af.png)

I'd be happy to try to take a crack at fixing this if it isn't too intricate.

**Comment by partouf** [comment]
Issue seems to appear from v 1.45.2, still works in 1.45.0

**Comment by partouf** [comment]
This appears to be fixed live, but I do not understand why - we have not changed anything...

**Comment by justanotherdot** [comment]
1.45.2 still cannot emit llvm-ir, albeit the compiler output is empty this time around. That said, 1.45.0, 1.46.0, and nightly seem to work fine. 

![image](https://user-images.githubusercontent.com/5350032/92336090-56556900-f0e0-11ea-9d91-4ea7ecd1c759.png)

**Comment by jeremy-rifkin** [comment]
Looks like this is working fine now https://godbolt.org/z/n7Mh7fa1r
