### ISSUE TITLE
[REQUEST] Alternative /api/compilers call with less noise (and less size)

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2168]
Current /api/compilers response is about 8 MB.
The /api/compilers needs to stay the same as we use that to get information about remote compilers.
However, that includes way more info than other API users would need to list for example the possible compilers id's, group, type and names.

Suggest a new get call that only returns things like:
* id
* groupname
* name
* version
* compilertype
* languageid
* supportsBinary
* supportsExecute
* what else?

**Comment by mattgodbolt** [comment]
Sounds great. We can feasibly add query params to pick the fields the clients need?

**Comment by mattgodbolt** [comment]
Happy to make it `compilers?all` for the remote compilers, and just pare it down for all other users

**Comment by partouf** [comment]
oh that would make sense and would also still be valid for older CE instances
