### ISSUE TITLE
[REQUEST] How can I configure the build options?

### ISSUE THREAD

**Issue by fintechee** [compiler-explorer/compiler-explorer#2171]
This repository is really amazing!

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

How can I configure the build options?
Can I set up a customized build options?
Such as:
emcc testUTF8.cpp -o testUTF8.js -s EXTRA_EXPORTED_RUNTIME_METHODS='["cwrap", "addFunction", "UTF8ToString"]' -s RESERVED_FUNCTION_POINTERS=100 -s MODULARIZE=1 -s 'EXPORT_NAME="API"' -s ENVIRONMENT=web -s ASYNCIFY -s 'ASYNCIFY_IMPORTS=["test"]' -O3

**Describe alternatives you've considered**

**Additional context**

**Comment by partouf** [comment]
In the properties file there are .options for your compiler where you should be able to enter default options. For example like https://github.com/compiler-explorer/compiler-explorer/blob/master/etc/config/c%2B%2B.amazon.properties#L303

Of course for things like -O3 I would leave it up to the user arguments that you can enter in the UI.

**Comment by fintechee** [comment]
Amazing!
Let me try and revert to you.
Many thanks for your fast response and help!

**Comment by fintechee** [comment]
@partouf 
I think I misunderstood.
Is this repository supporting emscripten?

**Comment by fintechee** [comment]
@partouf
Understood.
Thank you. No problem.
