### ISSUE TITLE
[REQUEST] Rust Library suggestions: Generic_Array, Wide

### ISSUE THREAD

**Issue by ronniec95** [compiler-explorer/compiler-explorer#2172]
https://crates.io/crates/wide
https://crates.io/crates/generic-array

Thank you

**Comment by RubenRBS** [comment]
Hi! Sorry for taking so long to update this, and also not having crate support yet, but we're actively looking into it.

I've recorded your suggestion in the linked issue, and will close this one to keep crate stuff in one place.
