### ISSUE TITLE
Add exe field defaultfields for /api/compilers

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2173]
The clion plugin uses it, mostly for hashing reasons I'm guessing for local installations. I think we can just add it to not break the plugin.

**Comment by partouf** [comment]
Filed an issue so exe field might be removed from the plugin https://github.com/ogrebenyuk/compilerexplorer/issues/12

We'll keep it in as long as needed, but I would like it removed from the default fields eventually.

**Comment by mattgodbolt** [comment]
Thanks @partouf and to @ogrebenyuk too :)
