### ISSUE TITLE
[BUG] **ARM64 gcc 8.2 with Eigen/trunk fails for most simple program**

### ISSUE THREAD

**Issue by tellenbach** [compiler-explorer/compiler-explorer#2174]
**Describe the bug**
Compiler explorer fails with the following error when including `Eigen/trunk`:

```
Program returned: 255
Program stderr
[F][2020-09-02T23:15:04+0000][1] bool subproc::runChild(nsjconf_t*, int, int, int)():449 Launching child process failed
```

**To Reproduce**
1. Include `Eigen/trunk`
2. Choose `ARM64 gcc 8.2` as compiler
3. Use the following code:

```
int main() { return 0; }
```

**Expected behavior**
The program should compile successfully with return code `0`.

**Link**
[https://godbolt.org/z/b5MrPa](https://godbolt.org/z/b5MrPa)

**Desktop**

 - OS: macOS 10.15.6
 - Browser: Firefox 
 - Version: 80.0.1 (64-Bit)

**Comment by partouf** [comment]
The problem here is that you're using the Executor. This will mess up the results of the compilation, because we have no ARM hardware to execute on.

You can use the normal Compiler window to test ARM compilers https://godbolt.org/z/zzrx8b

**Comment by tellenbach** [comment]
Oh, that makes sense! Thanks so much!
