### ISSUE TITLE
[BUG] "Executor from this" doesn't copy flags.

### ISSUE THREAD

**Issue by konstantinua00** [compiler-explorer/compiler-explorer#2182]
**Describe the bug**
When pressing "Add new..." -> "Executor from this" on compiler, it copies the compiler, but not its flags.

**To Reproduce**
1) Open any compiler.  
2) Add flags.  
3) Press "Add new..." on it.  
4) Select "Executor from this"

**Expected behavior**  
It should copy whole visible compiler state, including flags.

**Link**  
Before: https://godbolt.org/z/f3KsG1  
After: https://godbolt.org/z/KTxTPh  
Expected: https://godbolt.org/z/chvcoM

**Comment by mattgodbolt** [comment]
Great point: thanks for raising this.

**Comment by partouf** [comment]
This is is now live
