### ISSUE TITLE
[REQUEST] Strings tool

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2192]
I have used a tool called `strings` before on Windows, which dumps all the string literals in an executable. (https://docs.microsoft.com/en-us/sysinternals/downloads/strings)
I'm sure there is linux equivalent.

You can use `readelf` for this, but that takes effort looking up the right sections first. (https://gcc.godbolt.org/z/n4fs3W)
If all else fails, I guess we could make something that reads out the sections from `readelf` and dumps the strings in for example all the `.rodata` sections, but I'm sure there are more and it might get more complicated than that.

It would be a nice thing to have, I think, although the use-cases are rare of course. But it's not less rare to be used than a lot of our other tools.

**Comment by mattgodbolt** [comment]
100% there's `strings` for linux too :) part of binutils

**Comment by partouf** [comment]
Now live, huray!
