### ISSUE TITLE
[REQUEST] Lager+zug library support

### ISSUE THREAD

**Issue by arximboldi** [compiler-explorer/compiler-explorer#2195]
I would like to have Immer integrated in Compiler Explorer
https://github.com/arximboldi/immer

I'd be happy to do it myself if given some pointers :slightly_smiling_face: 

Other libraries of mine that would be nice to have but somewhat less relevant:
https://github.com/arximboldi/lager
https://github.com/arximboldi/zug

**Comment by partouf** [comment]
I have added immer https://godbolt.org/z/681YM6
But due to the growing amount of libraries, I will hold on to adding any more until we have a solution for that.

We can keep this issue open until then.

**Comment by arximboldi** [comment]
Oh nice, that was quick! Thank you so much @partouf !

**Comment by claremacrae** [comment]
I believe this can be closed now - both lager and mug are added to the relevant files in GitHub.

**Comment by partouf** [comment]
Yes, these will be live on a next update, soonish
