### ISSUE TITLE
[REQUEST] New library widget needed due to amount of libraries

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2196]
The current library widget is 800x620 pixels of size with 3 columns.
I reckon we can ride it out further by using 4 columns (as monitors are grower wider and wider)
But it doesn't seem an elegant or futureproof solution.

**Current situation**
![image](https://user-images.githubusercontent.com/442630/92894827-347b1f80-f41b-11ea-9b59-834fb9deffe0.png)

**Possible solutions**

1. We could go for a tiered solution, so we'll have a window like conformance view where you first click Add, then select a Library, and if you want something else than latest, you select a version.
2. We could go for a search solution, where you can type and search for a library and select the version when you found it. And perhaps for quick access, we could have a top 5 most used libraries and 5 random ones.
3. Something else?

I think in either solution, we should probably accommodate more of the information that we have on the libraries, like description and URL. And eventually, maybe we could squeeze in examples of how to use the examples here as well?

**Comment by partouf** [comment]
@mattgodbolt @RabsRincon any thoughts on this?

**Comment by mattgodbolt** [comment]
Good question! Will have a think more tonight: I wonder if we can somehow coerce selectize.js to do this for us? This is actually more in the selectize sweet spot than the compiler dropdown (multiple selections)..but I know we've had problems with discoverability with those! (also I'm not sure if there's a "radio" group thing for selectize, like, pick zero or one from "Abseil" category etc...)

**Comment by mattgodbolt** [comment]
I spent a couple of hours playing about with selectize. I don't really like the results but some screenshots:
![Screenshot from 2020-09-17 22-42-50](https://user-images.githubusercontent.com/633973/93552818-25becc00-f937-11ea-8d07-a2d2f984c368.png)

![image](https://user-images.githubusercontent.com/633973/93552859-4424c780-f937-11ea-8899-181ec0080707.png)

![Screenshot from 2020-09-17 22-44-11](https://user-images.githubusercontent.com/633973/93552883-57379780-f937-11ea-9356-6d2b100ca10e.png)

issues:
* fighting the default behaviour of popups. Maybe the library list should be a whole new separate bar like the "stdin" etc on execute only
* selectize has no "radio" functionality (e.g. I need to make it so if you select another version of the same library, the old version vanishes"
* it's still a *massive* list!
* it's still selectize so even though searching through it is "nice", it's hard to find.

So...very much out. I'll keep the code (it's super hacked) in case we want to investigate further but... I think we need a different solution. Might also be something that could fix #257 . Maybe a plugin to selectize to have hierarchical groups could be written? Maybe a whole new UI/component? One we make ourselves?

**Comment by partouf** [comment]
I hadn't even thought about this kind of solution, it does have some appeal visually. Thanks for putting effort into this either way.
But yeah, still massive list. (I mean the compiler list is a massive list as well, but everyone's used to that by now :D)

I'm gonna make some sketches in some UI sketching thing and see where my ideas end up.

**Comment by partouf** [comment]
So my main idea is something like this:

![image](https://user-images.githubusercontent.com/442630/93583947-e3cc6f00-f9a4-11ea-986c-6e759a402f2d.png)
_(used https://bootstrapstudio.io/ for this, so I'm hoping it's possible)_

I'm hoping that in reality the Results section can be compressed to fit more text and things, and that there be a scrollbar for when everything/more results are shown for example.

And more text in terms of: these are the versions that we support, comments like "Add -lCatch2Main to your compiler options if you're too lazy to create your own main function."

And when we have a solution for it; here are some example links (opened in new tabs?)

**Comment by partouf** [comment]
I guess the inspiration mostly comes from https://www.npmjs.com/
Except that we need a box to list the currently selected libraries and versions, and we need less information on the libraries themselves.

**Comment by partouf** [comment]
Needs final testing in staging and release to prod + tweet

**Comment by mattgodbolt** [comment]
Very cool! Can't wait to get this out!

**Comment by partouf** [comment]
Now live, huray!
