### ISSUE TITLE
[BUG] CPPX example  "Interface" doesn't compile

### ISSUE THREAD

**Issue by xKubo** [compiler-explorer/compiler-explorer#2201]
The CPPX example "Interface" doesn't compile.

https://cppx.godbolt.org/z/7K7M38

Would it be possible to update it ? 
Possibly with a link to some documentation ?

Thank you.

**Comment by partouf** [comment]
Right... I wouldn't have a clue what the recent version would want. @mattgodbolt who can we ask for this?

**Comment by mattgodbolt** [comment]
Oh good question! We might just have to retire this unless @hsutter, or someone from lock3 (@DarkArc , @sdgoodrick ?) has an idea?

**Comment by DarkArc** [comment]
How was this example reached?

This is a rough equivalent I just "threw together": https://cppx.godbolt.org/z/a9jc56

**Comment by mattgodbolt** [comment]
Oh wow that was quick!

There's a "load example" button (the save/load disk icon) and this was the original example from Herb.

Would you mind if I replaced it with your example? Thanks!

**Comment by mattgodbolt** [comment]
`s/replace/add/` -- the original "interface" works on the CPpCon 2017 (I'll rename "interface" to something like "Interface (CppCon2017)" and add this as interface

**Comment by DarkArc** [comment]
This would probably be better, I made it a bit closer to Herb's original, since it's going to be so readily accessible: 

https://cppx.godbolt.org/z/bjsWMn

**Comment by mattgodbolt** [comment]
Thanks!

**Comment by mattgodbolt** [comment]
re: documentation @xKubo I think it's ever-evolving: does anyone on the CC happen to have some docs for what's around? (Also NB there's Cppx-Gold and Cppx-Blue in the language dropdown...)

**Comment by DarkArc** [comment]
This doesn't cover blue and gold, but reflection and metaprogramming documentation can be found here; it's generally speaking, kept up to date with the latest state of the code: https://github.com/lock3/meta/wiki

**Comment by mattgodbolt** [comment]
Thanks again @DarkArc !

**Comment by mattgodbolt** [comment]
@DarkArc I tried to get the default "value type" of herb';s to compile with the latest... I didn't get (too) far: https://cppx.godbolt.org/z/sEP17c -- any ideas what I might be doing wrong?

**Comment by DarkArc** [comment]
While I appreciate the assumption, looks like you're doing everything right, and this is in fact our bug :(

We do have a test for the basic value example, but it does not include the virtual member `foo`.

**Comment by mattgodbolt** [comment]
Got it! Thanks again... in 33b996 I just made it so the default is at least a compiling "comment" that tells you to pick an appropriate example...if you have a value thing I can drop in its place I'll happily do that. Don't want to rock any boats before tomorrow either way.

**Comment by DarkArc** [comment]
After further experimentation, this seems to be an issue with the way user created errors are handled in meta classes. I've opened an issue for this https://github.com/lock3/meta/issues/260

**Comment by partouf** [comment]
Changes related to this are now live

**Comment by exoticus** [comment]
@DarkArc @mattgodbolt First so sorry to directly @ you, but i am really curious about that `cppx-gold` and `cppx-blue`, what is that i can't find anything about it anywhere, cppx-gold seems to be a python like c++. Can you shed some light on this, also i'd really love to know if there's any public place where devs working on these hangout. Thanks in advance!

**Comment by sdgoodrick** [comment]
> @DarkArc @mattgodbolt First so sorry to directly @ you, but i am really curious about that `cppx-gold` and `cppx-blue`, what is that, I can't find anything about it anywhere, `cppx-gold` seems to be a python like c++ implemented as a clang fork. Can you please shed some light on this, also i'd really love to know if there's any public place where devs working on these hangout. Thanks in advance!

They are both languages that spawned out of C++'s experimental metaprogramming features, but the designers had some disagreements and they split into two separate languages. Thanks for reminding me I need to actually document them publicly lol. You can view the github repo for them [here](https://github.com/lock3/cppx/), but it is a very experimental work-in-progress. If you have questions about it, you can contact me, [bbartman](https://github.com/bbartman) or [asutton](https://github.com/asutton).

**Comment by exoticus** [comment]
@sdgoodrick sweet, i have been looking at the unittests and i see very interesting things in the gold language, haven't quite figured anything about blue yet, I am very interested already and want to start fiddling around with them and perhaps get updated with new things, participate with testing or suggestions even? Also i wonder if you have an IRC/Discord/Gitter or some sort of communication where i can see what's new etc

**Comment by sdgoodrick** [comment]
@exoticus sorry, it's an in-house project for a client so the development is not super-public. However, I am hoping to have an in-depth tutorial written later this month. If you'd like, I can contact you when that's live.

**Comment by exoticus** [comment]
sure i'd love that, and thanks for your help!

**Comment by exoticus** [comment]
@sdgoodrick sorry for popping up again 😂  but i compiled cppx from source and tried to compile the gold snippet from compiler explorer using my locally built `clang-gold` and it's failing probably not recognizing the language for some reason, so i tried using `clang -x gold main.gld` but still. PS: i can't find anyway i can contact you beside this :D

```log
main.cc:1:3: error: invalid preprocessing directive
# Type your code here, or load an example.
  ^
main.cc:2:1: error: C++ requires a type specifier for all declarations
square(num : int) : int!
^
main.cc:2:8: error: use of undeclared identifier 'num'
square(num : int) : int!
       ^
main.cc:2:19: error: expected ';' after top level declarator
square(num : int) : int!
                  ^
                  ;
main.cc:2:24: error: expected unqualified-id
square(num : int) : int!
                       ^
```

**Comment by sdgoodrick** [comment]
@exoticus make sure you're using a `.usyntax` file extension for Gold, otherwise it will assume you're using C++.

You are free to open issues in the Cppx repo or email me (in my bio). The maintainers of this repo are likely getting notifications for every comment.
