### ISSUE TITLE
[BUG] Using std::filesystem with GCC 8 requires linking with stdc++fs

### ISSUE THREAD

**Issue by valiko-ua** [compiler-explorer/compiler-explorer#2211]
If you try to build [the following C++17 program](https://godbolt.org/z/rz8j31) with GCC 8.3:
```
#include <filesystem>
int main() {
  return std::filesystem::exists(std::filesystem::path("some/path"));
}
```
you will get:
```
ASM generation compiler returned: 0
/tmp/ccLUuIgL.o: In function `std::filesystem::exists(std::filesystem::__cxx11::path const&)':
/opt/compiler-explorer/gcc-8.3.0/include/c++/8.3.0/bits/fs_ops.h:121: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/tmp/ccLUuIgL.o: In function `std::filesystem::__cxx11::path::path<char [10], std::filesystem::__cxx11::path>(char const (&) [10], std::filesystem::__cxx11::path::format)':
/opt/compiler-explorer/gcc-8.3.0/include/c++/8.3.0/bits/fs_path.h:184: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
collect2: error: ld returned 1 exit status
Execution build compiler returned: 1
```
This is because GCC 8 put `std::filesystem` symbols into separate static library `libstdc++fs.a`. Newer versions of GCC do not have this problem.

I fixed it in my CMake project by adding `stdc++fs` **before** `stdc++`:
```
target_link_libraries(my_target ... stdc++fs stdc++ ...)
```
More info [here](https://bugs.launchpad.net/ubuntu/+source/gcc-8/+bug/1824721).

**Comment by mattgodbolt** [comment]
Thanks for filing this, but this is not an issue with compiler explorer - we reflect what happens if you run the compiler yourself, we don't try to fix up differences between them.

**Comment by valiko-ua** [comment]
So, no way to use std::filesystem on Compiler Explorer with GCC8?
