### ISSUE TITLE
[REQUEST] Add python2.7/3.x as library in C++

### ISSUE THREAD

**Issue by MichaelSuen-thePointer** [compiler-explorer/compiler-explorer#2217]
It would be convenient if I can include <python2.7/Python.h> and compile a piece of code like that.

**Comment by partouf** [comment]
Hi, can you provide an example of how code using python.h would look like?
And where we can find these python header files?

**Comment by MichaelSuen-thePointer** [comment]
@partouf 

Mostly the use case is when you need to write C/C++ extension (.so) for python, the document is [here](https://docs.python.org/2.7/extending/extending.html)

a example code is like below:

```c
#include <Python.h>

typedef struct {
    PyObject_HEAD
    /* Type-specific fields go here. */
} noddy_NoddyObject;

static PyTypeObject noddy_NoddyType = {
    PyVarObject_HEAD_INIT(NULL, 0)
    "noddy.Noddy",             /* tp_name */
    sizeof(noddy_NoddyObject), /* tp_basicsize */
    0,                         /* tp_itemsize */
    0,                         /* tp_dealloc */
    0,                         /* tp_print */
    0,                         /* tp_getattr */
    0,                         /* tp_setattr */
    0,                         /* tp_compare */
    0,                         /* tp_repr */
    0,                         /* tp_as_number */
    0,                         /* tp_as_sequence */
    0,                         /* tp_as_mapping */
    0,                         /* tp_hash */
    0,                         /* tp_call */
    0,                         /* tp_str */
    0,                         /* tp_getattro */
    0,                         /* tp_setattro */
    0,                         /* tp_as_buffer */
    Py_TPFLAGS_DEFAULT,        /* tp_flags */
    "Noddy objects",           /* tp_doc */
};

static PyMethodDef noddy_methods[] = {
    {NULL}  /* Sentinel */
};

#ifndef PyMODINIT_FUNC	/* declarations for DLL import/export */
#define PyMODINIT_FUNC void
#endif
PyMODINIT_FUNC
initnoddy(void) 
{
    PyObject* m;

    noddy_NoddyType.tp_new = PyType_GenericNew;
    if (PyType_Ready(&noddy_NoddyType) < 0)
        return;

    m = Py_InitModule3("noddy", noddy_methods,
                       "Example module that creates an extension type.");

    Py_INCREF(&noddy_NoddyType);
    PyModule_AddObject(m, "Noddy", (PyObject *)&noddy_NoddyType);
}
```
It should be compiled and linked with proper compiler flags and python libs (in real project automatically done by python tool called distutils), but in compiler explorer only assembly output is needed, so compilation is no big deal, a typical command line is like:

`gcc -pthread -fno-strict-aliasing -O0 -g -ggdb -fPIC -I/usr/include/python2.7 -c demo.c`

The header files are stored right in `/usr/include/python2.7` (or "path_to_python/Include" on windows), you can install it (on linux) by `apt install python-dev` or something like these

**Comment by partouf** [comment]
> The header files are stored right in /usr/include/python2.7 (or "path_to_python/Include" on windows), you can install it (on linux) by apt install python-dev or something like these

This is a bit more complicated for us. But I'm sure we can figure it out.

Thanks for the info and example!
