### ISSUE TITLE
[BUG] "unused labels" removes the unreferenced labels

### ISSUE THREAD

**Issue by MFTabriz** [compiler-explorer/compiler-explorer#2218]
**Describe the bug**
The “unused labels” filter removes the asm code with unreferenced labels too.

**To Reproduce**
https://godbolt.org/z/d47Gdc

For example, while compiling with gprof functionality (-pg), part of the instrumentation is done by adding a call to mcount in each function. This call is labeled but not referenced and currently the “unused labels” filter removes it completely.  

**Expected behavior**
Labelled asm codes which are in the execution path should not be filtered by the “unused labels”.

**Comment by mattgodbolt** [comment]
Thanks! This looks like a bug in our label parsing:

```
square(int):
.LFB0:
        push    rbp
        mov     rbp, rsp
        sub     rsp, 8
1:      call        mcount
        mov     DWORD PTR [rbp-4], edi
        mov     eax, DWORD PTR [rbp-4]
        imul    eax, eax
        leave
        ret
```

is the code itself. We seem to be dropping the label *and* the instruction on the same spot as the label.

**Comment by mattgodbolt** [comment]
See also #2034

**Comment by partouf** [comment]
Considering there's no subsequent label, if we considered them separately, it would probably look like this:
```
square(int):
        push    rbp
        mov     rbp, rsp
        sub     rsp, 8
```

So I think there would need to be a special exception for these kinds of labels combined with an opcode, to just always show them.

**Comment by mattgodbolt** [comment]
One thing would be 'just" to insert a fake line break after every macro definition

**Comment by mattgodbolt** [comment]
(or...actually, you know, parse the asm properly instead of use a giant blob of regexes.../but...)

**Comment by OfekShilon** [comment]
@partouf this is fixed now too
