### ISSUE TITLE
Problem accessing CE through API

### ISSUE THREAD

**Issue by slzatz** [compiler-explorer/compiler-explorer#2222]
Looking to see if someone has encountered (and I hope solved) the following problem:

using the cpr c++ curl wrapper library I cannot successfully execute code and get the "expected unqualified-id before {" which I generally take to mean it isn't correctly parsing the source code at all.  I am using the "Execution Only" example from the api docs and the code I am using to place a post request is the following:

    auto r = cpr::Post(cpr::URL("https://godbolt.org/api/compiler/g82/compile",
                                 cpr::Body{js.dump()},
                                 cpr::Header{{"Content-Type", "application/json"}},
                                 cpr::Header{{"accept", "application/json"}});

I am using the json provided in the Execution Only example and using nlohmann json library to deal with it.

When I access the api with the same example using the python requests module, it all works as expected.

I did test whether I can access another online compiler (Coliru) using the cpr library and that works fine, which is great but I'd really like to be able to access CE.

If anyone has any suggestions, I'd be very interested.

**Comment by mattgodbolt** [comment]
If possible can you snag a wireshark capture of the exact request that goes out?

**Comment by slzatz** [comment]
Thanks for the suggestion - with wireshark I am seeing that although I am setting the header to `application/json`, wireshark reports the header is `x-www-form-urlencoded`.  Not sure that is the issue but for a next step let me address that with the cpr folks.

**Comment by slzatz** [comment]
This was a cpr library issue that could be worked around and so am closing this issue

**Comment by mattgodbolt** [comment]
Thanks for taking the time to update us here!
