### ISSUE TITLE
[BUG] Go lang compiler output not showing

### ISSUE THREAD

**Issue by happygiraffe** [compiler-explorer/compiler-explorer#2228]
**Describe the bug**

I am investigating to see if the Go compiler inlines a trivial function.

```
package main

import "fmt"

func microDays(us int64) int64 { return us/1e6/86400 }

func X() {
    x := microDays(123)
    fmt.Println(x, "days")
}

func main() {}
```

Normally, to produce inlining diagnostics, you pass the `-m` flag to the Go compiler. e.g.

```
% go build -gcflags=-m main.go
# command-line-arguments
./main.go:5:6: can inline microDays
./main.go:8:16: inlining call to microDays
./main.go:9:13: inlining call to fmt.Println
./main.go:12:6: can inline main
./main.go:9:13: x escapes to heap
./main.go:9:17: "days" escapes to heap
./main.go:9:13: []interface {} literal does not escape
<autogenerated>:1: .this does not escape
```

**To Reproduce**

Add `-m` to the Go compiler options.

(I'm using amd64 gc 1.15)

**Expected behavior**

I would like to see the stdout/stderr of the compiler.

When I click on the compiler output, I just see "Compiler returned: 0" and nothing else.

**Link**

https://go.godbolt.org/z/1KnojM

**Comment by mattgodbolt** [comment]
Hey Dom!

By default we don't run the executable -- to do so you need to tick the "Run the compiled output" off the "Output" button: https://go.godbolt.org/z/fdzej8

to get the actual output you'll need to call X() from main() too:  https://go.godbolt.org/z/1nM369

Hope that helps :)

**Comment by mattgodbolt** [comment]
Also if you're just interested in program output and not the assembly there's an "Execution only" view you can create (from the dropdown on the editor "Add new..."). That would look like: https://go.godbolt.org/z/WovzWb

**Comment by happygiraffe** [comment]
Hi Matt! Thanks so much for compiler explorer :)

I'm not interested in running the executable — the flag triggers the compiler to produce extra output, and I can't see that in the console?

**Comment by mattgodbolt** [comment]
Got it! If you pass `-m` on the command line you get: https://go.godbolt.org/z/6YMzYK which shows the output you want I think :)

**Comment by happygiraffe** [comment]
That is exactly what I want, and I *thought* I had done that. I apologise for wasting your time!

**Comment by partouf** [comment]
There was something special about Go compiler output, although I can't quite remember. It is quite inconsistent to not show with the normal compiler panel but does show with the execution panel...

**Comment by partouf** [comment]
Ah, ok

So with compilation we do:
`build -o /tmp/compiler-explorer-compiler2020824-1040-4ndyc0.m3c1/output.s -gcflags -S -m /tmp/compiler-explorer-compiler2020824-1040-4ndyc0.m3c1/example.go`

And with execution we do:
`build -o /tmp/compiler-explorer-compiler2020824-1045-1izms8s.2x12/output.s -gcflags=-m /tmp/compiler-explorer-compiler2020824-1045-1izms8s.2x12/example.go`

There was something about -S throwing a wrench in the works, but there's probably a way to get the correct result when compiling as well.

**Comment by happygiraffe** [comment]
@partouf is it a matter of adding quotes to the command? i.e.

```
build -o /tmp/compiler-explorer-compiler2020824-1040-4ndyc0.m3c1/output.s -gcflags '-S -m' /tmp/compiler-explorer-compiler2020824-1040-4ndyc0.m3c1/example.go
```

**Comment by happygiraffe** [comment]
I think I'm barking up the wrong tree: according to the [code](https://github.com/compiler-explorer/compiler-explorer/blob/28df4b38db6a69337afc8ec6f9975016ee367293/lib/compilers/golang.js#L197), we are already sending the `-gcflags` as a single parameter.

**Comment by happygiraffe** [comment]
The help for `go build` says:

> The -asmflags, -gccgoflags, -gcflags, and -ldflags flags accept a
> space-separated list of arguments to pass to an underlying tool
> during the build. To embed spaces in an element in the list, surround
> it with either single or double quotes. The argument list may be
> preceded by a package pattern and an equal sign, which restricts
> the use of that argument list to the building of packages matching
> that pattern (see 'go help packages' for a description of package
> patterns). Without a pattern, the argument list applies only to the
> packages named on the command line. The flags may be repeated
> with different patterns in order to specify different arguments for
> different sets of packages. If a package matches patterns given in
> multiple flags, the latest match on the command line wins.
> For example, 'go build -gcflags=-S fmt' prints the disassembly
> only for package fmt, while 'go build -gcflags=all=-S fmt'
> prints the disassembly for fmt and all its dependencies.

([source](https://golang.org/cmd/go/#hdr-Compile_packages_and_dependencies))

Which points to the real problem: the first argument after `-S` appears to be swallowed as a package name, rather than being interpreted as a flag. Which makes [this code](https://github.com/compiler-explorer/compiler-explorer/blob/28df4b38db6a69337afc8ec6f9975016ee367293/lib/compilers/golang.js#L200) misbehave. I think the correct answer is to supply the user options as a separate `-gcflags`?

**Comment by happygiraffe** [comment]
I'm still barking up the wrong tree. :) 

Perhaps the problem is that the output is intermingled with the compiler output?

```
% go build -o /tmp/main.a -gcflags '-S -m' >/tmp/stdout 2>/tmp/stderr
% head /tmp/stdout
% head /tmp/stderr
# _/home/hdm
./main.go:5:6: can inline microDays
./main.go:8:16: inlining call to microDays
./main.go:9:13: inlining call to fmt.Println
./main.go:12:6: can inline main
./main.go:9:13: x escapes to heap
./main.go:9:17: "days" escapes to heap
./main.go:9:13: []interface {} literal does not escape
<autogenerated>:1: .this does not escape
os.(*File).close STEXT dupok nosplit size=26 args=0x18 locals=0x0
```

**Comment by partouf** [comment]
Fix is now live
