### ISSUE TITLE
WebAsm compilers missing from C

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2229]
Sometimes the WebAssembly entry does not show. Check out https://godbolt.org/z/sq8G6d

Here's the screenshot. Usually WebAssembly comes between RISC-V and X86-64.

![image](https://user-images.githubusercontent.com/633973/94152000-af433200-fe40-11ea-974c-4fc9d905715c.png)

https://twitter.com/pocmatos/status/1309055289124163586?s=20

**Comment by mattgodbolt** [comment]
Definitely seems intermittant. Nothing obvious in the logs that suggests we have a problem running the compiler, maybe a more general problem with our "update while things are going" ?

```
~ $ curl https://godbolt.org/api/compilers | grep wasm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0wasm_gltip                | WASM gc (tip)
wasm_gl114                | WASM gc 1.14
wasm_gl115                | WASM gc 1.15
wasm32clang               | WebAssembly clang (trunk)
```

it's there now, but I definitely didn't see it earlier in the UI. Unless it's a UI display issue

**Comment by mattgodbolt** [comment]
Ahh! I'ts missing form "C"!!!!

**Comment by pmatos** [comment]
Thanks for opening this. Now it sounds obvious that it was the language set that was different. 

You have no idea how many times I scrolled that list to make sure I was not going insane.

**Comment by mattgodbolt** [comment]
Hahah no worries @pmatos :) I do it all the time. It's a shame we don't (maybe can't?) generate the C config entirely from the C++ config -- we often forget to keep them up to date.

**Comment by RubenRBS** [comment]
Closing in favour of #2559
