### ISSUE TITLE
[REQUEST] Setup experiment to async/await during the JS part of demangling

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2239]
Steps to take;
1. Setup something that can do API calls in parallel
2. Create 1 or 2 /compile JSONs that produces a lot of assembly and things to demangle
3. Measure throughput + concurrency
4. Experiment with async/awaits to allow better concurrency during the long demangling sessions

**Comment by mattgodbolt** [comment]
Thanks @partouf !
