### ISSUE TITLE
[REQUEST] Default output (intel vs att) does not match gcc. 

### ISSUE THREAD

**Issue by ryn1x** [compiler-explorer/compiler-explorer#2240]
The `-masm=att` option is needed to match default gcc output. Normally it is the other way around, where `-masm=intel` is needed to output intel format and att is default.

I'm sure this was intentional, but when using the site as an educational tool this does not match default gcc behavior or popular textbooks like CSAPP.

**Comment by partouf** [comment]
Hi, in Compiler Explorer this is influenced by the checkbox in the compiler Output menu, Intel is the default format as long as a compiler supports it.
![image](https://user-images.githubusercontent.com/442630/94793795-4ed16900-03db-11eb-8925-ae20654cbf2d.png)

You can always see the flags used when you click on the icon next to the compiler selection
![image](https://user-images.githubusercontent.com/442630/94794076-ab348880-03db-11eb-8770-191f83321519.png)

I totally realize this isn't the default when you try it out manually, but having Intel format as a default cross-compiler (as long as they support it) - is a lot more user-friendly for the website.

**Comment by ryn1x** [comment]
That makes sense. Thanks for pointing out these UI features!

**Comment by mattgodbolt** [comment]
It's also mainly my fault as I find AT&T syntax so confusing :D, so chose to default it to intel wayyy back :)
