### ISSUE TITLE
[BUG] Link to Cpplang Slack leads to 404

### ISSUE THREAD

**Issue by Bu11etmagnet** [compiler-explorer/compiler-explorer#2241]
**Describe the bug**
https://cpplang.now.sh/ shows:

404: NOT_FOUND Code: DEPLOYMENT_NOT_FOUND ID: cdg1::vt8fb-1601556067639-b3de61d7cd16
Note: cpplang.now.sh might be available. Click here to learn how to assign it to a project.

**To Reproduce**
Click on the "Discuss C++ on the Cpplang Slack" link

**Expected behavior**
Cpplang Slack opens. ( https://cpplang.slack.com/ )

**Link**
https://godbolt.org/z/jsdbKz

**Screenshots**

**Comment by partouf** [comment]
Fixed, thanks!

**Comment by mattgodbolt** [comment]
I'll update the "ad" database too.

**Comment by partouf** [comment]
Oh didn't realize there was an Ad, was wondering why a /z/ link was linked haha
