### ISSUE TITLE
[BUG] Compiler status success tick icon is sometimes a confusing red-orange

### ISSUE THREAD

**Issue by marzer** [compiler-explorer/compiler-explorer#2262]
**Describe the bug**
See title. Not sure what it's supposed to represent, since red generally means bad. My guess is bug?

**Expected behavior**
A green tick like normal.

**Link**
https://godbolt.org/z/qoW635

**Screenshots**
![image](https://user-images.githubusercontent.com/3958019/95257342-daf4ed80-082c-11eb-95e5-2bcbca139fb4.png)

**Additional context**
Seems to only happen on MSVC instances (that I checked, anyway). Tick HTML shows the colour is set inline:
`<span class="status-icon fas fa-check-circle" style="color: rgb(255, 101, 0);"></span>`

**Comment by mattgodbolt** [comment]
This means the compiler generated output. For MSVC this is "always" unfortunately, as try as we might it can't help itself from printing the *@#$# name of the file being compiled. We should probably filter that somehow, but it's frustrating!

The intention is to indicate when there's warnings or notes or other valuable compiler output that the user might not notice if they were only looking at the compiler output. See #1034

**Comment by marzer** [comment]
Ohhhh, that makes sense. Thanks for the clarification @mattgodbolt.

It doesn't seem to contrast very well in dark mode, so a simple workaround could be to make it more yellow, or use a different symbol?

**Comment by apmorton** [comment]
I'm going to close this as a dup of #1034 for now - as filtering the filename output from msvc is probably the correct resolution to the confusion here.

If anyone wants to make changes to the dark theme for better contrast please send a PR 😃
