### ISSUE TITLE
[BUG] Not getting back `defaultCompiler` in languages responses anymore

### ISSUE THREAD

**Issue by SecurityInsanity** [compiler-explorer/compiler-explorer#2263]
**Describe the bug**

Previously when calling: `https://godbolt.org/api/languages` you would receive an array of languages which contained at least an: `id`, `name`, and `defaultCompiler` (there are more, but these are all I'm really concerned about).

Unfortunately calling that endpoint now, results in _no_ default compilers. It's unclear how _long_ this has been happening (the application built ontop of compiler explorer (which is now broken for the default case) hasn't really be used in awhile, and when it has been it's usually providing a specific compiler anyway).

**To Reproduce**

The simplest way to verify is to try and call the API Endpoint, with curl:

```
$ curl -H 'User-Agent: Local-Debugging' -H 'Accept: application/json' -H 'Content-Type: application/json' -sSL -XGET https://godbolt.org/api/languages | grep default
$ 
```

You'll see nothing returns a defaultCompiler. [Contrary to what the code is trying to do?](https://github.com/compiler-explorer/compiler-explorer/blob/master/lib/handlers/api.js#L112)

**Expected behavior**

A default compiler is returned for languages that have one. I'm unclear if this is all languages, but things like C/C++ are what I'm used to seeing.

**Comment by partouf** [comment]
Interesting, thanks for the bugreport. I don't think we actually changed something about /languages, but we did with /compilers. Maybe something went wrong there.

**Comment by mattgodbolt** [comment]
I was just going to say, I wondered if it was our filtering - which it does seem to be:

```
$ curl -H 'User-Agent: Local-Debugging' -H 'Accept: application/json' -H 'Content-Type: application/json' -sSL -XGET 'https://godbolt.org/api/languages?fields=all' | grep default
```
finds it :)

**Comment by partouf** [comment]
AH.. Ooops :D no idea it permeated through that API call as well

**Comment by mattgodbolt** [comment]
Sorry we didn't contact you; we didn't know of your app (which is of course fine!) -- the code that filters is here: https://github.com/compiler-explorer/compiler-explorer/blob/99d575b98d8146b1345e0c4dc84110a9f7c612c1/lib/handlers/api.js#L126-L147 if you want to make a more nuanced decision of the fields you want. We added filtering to reduce the amount of data we sent to web pages.

**Comment by SecurityInsanity** [comment]
That makes total sense, and it's okay you didn't contact me! I don't expect a contact anytime you want to make a change :sweat_smile: . I'll go ahead, and update my code to use this new filtering! Thanks so much for the quick response!
