### ISSUE TITLE
[BUG] objdump returns error on Clang Arm targets

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2274]
Example:
https://godbolt.org/z/hWqv6e

We might need to use the relevant gcc toolchain's objdump instead of the default.

**Comment by partouf** [comment]
Perhaps related https://github.com/compiler-explorer/compiler-explorer/issues/2718 - it might be a good idea to actually start exposing stderr from objdump so we can more easily debug these things.

**Comment by OfekShilon** [comment]
@partouf  This was fixed, probably with #2718. Can close.

**Comment by partouf** [comment]
aah yes, thanks
