### ISSUE TITLE
[REQUEST] Public stats

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2287]
Stathat is _ok_ but things like https://headlinedev.xyz/discord-compiler/ would be cooler to publish (thanks to @Headline for the link).

**Comment by mattgodbolt** [comment]
Would need something actually catching per-language stats etc

**Comment by Headline** [comment]
Not sure if this is out of scope but tracking API usage would also be nice, although probably not a priority for the initial implementation of this feature.

It'd be neat to allow programs hitting the API to specify their own user agent to differentiate what requests are coming from where, adding this identifier would make it easier to interpolate how people are sending requests in, be it as a first-class request via the web interface or an external source.

**Comment by mattgodbolt** [comment]
Great idea; thanks :)

**Comment by mattgodbolt** [comment]
Additionally tracking "safe" (tbd what that means) aggregate stats as per things suggested on slack:

> I think those kind of aggregate metrics could be really useful. Also with stuff like resulting binary size, etc. Particularly with some anonymized feature extraction from the source (like “uses concepts”, etc). I’m sure there are grad students around who would love to do that.

**Comment by jeremy-rifkin** [comment]
Implemented at https://stats.compiler-explorer.com/
