### ISSUE TITLE
[REQUEST] Show more metainfo in IR view (for llvm compilers)

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2297]
So not the IR language mode or via -emit-llvm, but the viewer old-style-tool

Example:
https://godbolt.org/z/Es1K94

There is no filter like that is applied with -emit-llvm

Question is how to make something that remains backwards compatible with how it now works.

**Comment by jeremy-rifkin** [comment]
I think this is now resolved. Backwards compatibility is slightly broken by default filters and options, however, I think that is ok. A user can turn off filters if needed.
