### ISSUE TITLE
[REQUEST] Show multiline "full version" information about compiler

### ISSUE THREAD

**Issue by JohanEngelen** [compiler-explorer/compiler-explorer#2298]
I don't know about the other compilers, but LDC's `--version` output shows more useful information on the lines after the first line (like the D-language spec that it implements, which LLVM version it is built with, and which targets it supports).
Currently, the "i" button next to the compiler name on the bottom right only shows the first line of `--version` output. It would be more convenient if it would show the full output.
(of course the user can already put `--version`  as cmdline option and see it in the compiler output: https://d.godbolt.org/z/3EW156)

Thanks!
  Johan

**Comment by RubenRBS** [comment]
Hi Johan, sorry that this fell thru the cracks and we did not get back to you sooner.

I love your idea, so I've implemented it. Sorry that it took so long, but unless I broke something, this should be live "shortly". Let me know what you think once it's there! :)

**Comment by JohanEngelen** [comment]
Hi @RubenRBS , some feedback:
- the "full version" toggle is great, good idea :)
- the full version output doesn't look so nice. See the full version output of the LDC compiler: tough to read. Suggestions: Newlines should not be removed, and the textbox should also be made wider. 

thanks!

**Comment by RubenRBS** [comment]
Thanks! I've done as you suggested and now it's much better I think. Let me know what you think once it's live (soon _ish_)

**Comment by JohanEngelen** [comment]
> Thanks! I've done as you suggested and now it's much better I think. Let me know what you think once it's live (soon _ish_)

Looks great, thanks
