### ISSUE TITLE
[REQUEST] **Intel icpx/-qnextgen compilers**

### ISSUE THREAD

**Issue by ldalessa** [compiler-explorer/compiler-explorer#2305]
**Is your feature request related to a problem? Please describe.**
Intel compilers now provide an LLVM-based infrastructure in parallel with their traditional EDG-based solution. They refer to this as their "Next Generation" infrastructure, or `nextgen`. This infrastructure seems to be where much of their modern compiler development is happening, including work on the ParallelSTL as well as their OneAPI stuff. It is automatically installed in parallel to their existing framework.

**Describe the solution you'd like**

Access to the `nextgen` compiler framework. The `nextgen` compiler should be accessed via the `icpx` and `icx` binaries, and can also be accessed with `icc -qnextgen` and `icpc -qnextgen`, however I don't really see a benefit to the `-q` method. I think that exporting a compiler stack for these two binaries would make the most sense and be useful to the community.

**Describe alternatives you've considered**

I've tried using the `-qnextgen` flag with the `icc` installs, but there appear to be weird pathing problems or and/or incompatibilities in the way that CE exports `icc`.

**Additional context**

This will become more and more important going forward as intel continues to work on its oneAPI infrastructure. There is also the "data-parallel C++" compiler variant `dpc++`, but that's still pretty beta.

**Comment by ldalessa** [comment]
Sounds like a great start. One thing I find with the intel infrastructure is that sourcing the `compilervars.sh` script solves all of my pathing issues.

```
$ source /opt/intel/bin/compilervars.sh -arch intel64 -platform linux
```

The only other thing that sometimes causes trouble is that the gcc libstdc++ paths need to be correct as well, but I assume that's common for you guys.

**Comment by mattgodbolt** [comment]
Got it: thanks. We can use the `compilervars` as a starting point.

**Comment by mattgodbolt** [comment]
Or...not
```
$ find /opt/compiler-explorer/intel-2021.1.9.2205/ -name compilervars.sh
```

I think the unusual installation process leaves it without the shell scripts.

**Comment by ldalessa** [comment]
Okay, I've never really seen it with a non-standard install. Sorry that I can't be more helpful.

**Comment by partouf** [comment]
We only need to know the contents, it not being there is not a big deal as long as we can replicate its behaviour.

**Comment by ldalessa** [comment]
It's customized for all of the different subcomponents of intel parallel studio that you may have installed (mkl, tbb, mpi, etc...), and just sets what you'd expect. Various BIN,CPATH, LIBRAY_PATH, and ROOT environment variables. For example, I just have mkl installed on my local machine, and this is what it does to my environment.

```
ldalessa@portland:~$ diff pre.txt post.txt
2a3
> PKG_CONFIG_PATH=/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/bin/pkgconfig
12a14
> LIBRARY_PATH=/opt/intel/compilers_and_libraries_2018.1.163/linux/tbb/lib/intel64_lin/gcc4.1:/opt/intel/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64_lin
15a18
> LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64:/opt/intel/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.1.163/linux/tbb/lib/intel64_lin/gcc4.1:/opt/intel/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64_lin
---
> MKLROOT=/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl
> NLSPATH=/opt/intel/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64/locale/%l_%t/%N:/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64_lin/locale/%l_%t/%N
> PATH=/opt/intel/compilers_and_libraries_2018.1.163/linux/bin/intel64:/home/ldalessa/.local/bin:/opt/emacs/27/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
20a26,27
> INTEL_LICENSE_FILE=/opt/intel/compilers_and_libraries_2018.1.163/linux/licenses:/opt/intel/licenses:/home/ldalessa/intel/licenses
> CPATH=/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/include
```

I think it's safe to take Matt's `LD_LIBRARY_PATH` path from above and start with that... hopefully the compiler itself can find what it needs w.r.t. headers and link-time libraries.

**Comment by jcranmer-intel** [comment]
The icx/icpx/ifx binaries are the entry point that we plan to use for the new frontend infrastructure, corresponding to icc/icpc/ifort respectively. Don't worry about supporting `-qnextgen`.

**Comment by jeffhammond** [comment]
This was addressed in https://github.com/compiler-explorer/compiler-explorer/pull/2450 and https://github.com/compiler-explorer/compiler-explorer/pull/2480, so this issue should be closed.

**Comment by partouf** [comment]
You're right! Thanks!
