### ISSUE TITLE
[REQUEST] FreeBSD support

### ISSUE THREAD

**Issue by lichray** [compiler-explorer/compiler-explorer#2307]
**Is your feature request related to a problem? Please describe.**

A compiler developer should be able to diagnosis his or her compiler with compiler-explorer on the platform they are building the compiler.  But one who works on FreeBSD will find that b632915 (almost 3 years older than master) is roughly the last version that runs on FreeBSD.

**Describe the solution you'd like**

Use npm packages that support FreeBSD, please.

**Describe alternatives you've considered**

Make certain features optional.

**Additional context**

![image](https://user-images.githubusercontent.com/433009/97774953-36fc1a80-1b2a-11eb-8ca2-f33b9d6d76d5.png)

**Comment by partouf** [comment]
If you could try and npm remove <package> until at least npm installs everything, that would be quite helpful. Then we can see if we can make those packages optional or something like it.

**Comment by mattgodbolt** [comment]
Here it looks like `@sentry` is the culprit. I'm not sure how to make `npm` packages optional - does anyone have any ideas? I'm actually pretty surprised this doesn't work on FreeBSD, as it runs on Mac and windows without issue.

That said: getsentry/sentry-cli#672 seems to be the culrptis?

**Comment by mattgodbolt** [comment]
@lichray can you try removing the `@sentry/cli` line in the `package.json` and see if that fixes things for you?

**Comment by mattgodbolt** [comment]
(if so we can potentially use `npx` to run the cli when needed instead of forcing its install)

**Comment by lichray** [comment]
After dropping `@sentry/cli`, the server runs fine.

![Screenshot 2020-10-31 120613](https://user-images.githubusercontent.com/433009/97785192-89acf500-1b71-11eb-829a-04209e92ee7a.png)


I got another warning when installing packages though:

![image](https://user-images.githubusercontent.com/433009/97785097-f83d8300-1b70-11eb-9194-d07c48c11296.png)

**Comment by mattgodbolt** [comment]
Thanks: we will try and drop the `@sentry/cli` dependency. The warnings you see are apparently OK - thanks for the info!

**Comment by apmorton** [comment]
The only thing we use sentry-cli for is tagging releases as part of the travis dist.

We could remove sentry-cli from our deps and install it manually as part of travis-dist makefile target.

**Comment by apmorton** [comment]
This should be fixed now - you should be able to clone and run the latest master on FreeBSD without any changes.
