### ISSUE TITLE
[BUG] ranges v3 on windows is not set up correctly

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2308]
As best we can see, range v3 is a supported library but: https://godbolt.org/z/xYG7dh indicates it's not being found.

**Comment by RubenRBS** [comment]
Besides a deprecation message, https://godbolt.org/z/38E6K7WP9 shows that it works (as far as I can tell!)

**Comment by partouf** [comment]
Seems indeed fixes
