### ISSUE TITLE
[REQUEST] please support absl::StrFormat, which requires linking an additional library

### ISSUE THREAD

**Issue by ddopson** [compiler-explorer/compiler-explorer#2313]
**Is your feature request related to a problem? Please describe.**

From the Abseil library, I wish to use absl::StrFormat for printing diagnostic strings in the Godbolt executor (for example: https://godbolt.org/z/Tb47oW).

Unfortunately, this doesn't work because str_format is one of the Abseil optional libraries. Godbolt has the header file, but using any of the non-default library methods (eg, absl::StrFormat) results in an "undefined reference" linker error.

See https://github.com/abseil/abseil-cpp/issues/145 for an explanation of how str_format is a separate library that must be linked in. Godbolt currently only has a single monolithing "Abseil" library option, and that only includes the Abseil components in the default library.

I use this absl::StrFormat ubiquitously in my professional work, and it's annoying to have to back-translate things to printf to get them working in Godbolt. Sometimes, I paste small snippets of (generic / non-sensitive) code into Godbolt for rapid exploration / prototyping.

It would be convenient to be able to use ALL of the Abseil libraries, and not just the ones that are compiled in by default.

**Describe the solution you'd like**

One simple solution would be to link in substantially ALL Abseil components whenever the user adds the "Abseil" library. That seems simpler than exposing more configuration state for selecting the individual sub-components of Abseil.

**Additional context**

FWIW, I happen to work at the company that develops Abseil. My work focuses on the retrieval systems known externally as [ScaNN](https://ai.googleblog.com/2020/07/announcing-scann-efficient-vector.html), which make heavy use of SIMD intrinsics. By my oblique reference to my employer, you can conclude that I'm NOT representing them in an official capacity.

As a show of my appreciation for all the hard work you've put into making Godbolt such a fantastic free tool, I just sent you a donation via PayPal (significantly more than a coffee, but nowhere near enough to qualify as a quid-pro-quo for implementing a feature request!). What a fantastic tool! Thanks for your efforts!

**Comment by mattgodbolt** [comment]
Thanks @ddopson :) I'm aware of your company (indeed used to be `moog@yourcompany.com`). I'm not sure if we ever got abseil in the list of non-header-only libraries. For the longest time we didn't support building binaries/executing against non-header-only libraries, but then the amazing @partouf worked hard on a solution to build all the various components for many compilers and flag combos and link against them.

I'm embarrassed to say I can't remember how to get to our binary library list (the header-only is at https://godbolt.org/admin/libraries.html but that is probably out of date too). I'm hoping Partouf can help us both here!

**Comment by partouf** [comment]
https://conan.compiler-explorer.com/libraries.html ;)

I'm not entirely sure how this will work out, as they have cmake targets - but not I'm not sure if that builds anything if you're not using a cmake file yourself. But I'll play around with it and see. Otherwise maybe we have to do something with the basel build thing.

**Comment by partouf** [comment]
Ah ok, good news, make all just builds all static libraries. So we can build this. It's just a lot of files to link against, let's see if I can make it work without having CE link against everything always.

**Comment by partouf** [comment]
Ok, with some effort I managed to add abseil to the builds. I'll let that stir for the night so it will produce binaries for all our compilers.
Then we'll need something to add this to Compiler Explorer. I'm not sure how, yet, though.

**Comment by partouf** [comment]
Update; the binaries are uploaded to our conan server. https://conan.compiler-explorer.com/libraries.html

**Comment by ddopson** [comment]
Woohoo!

**Comment by partouf** [comment]
This is now live
