### ISSUE TITLE
[BUG] Output panel handles 256-color background escape sequences incorrectly

### ISSUE THREAD

**Issue by lunasorcery** [compiler-explorer/compiler-explorer#2315]
**Describe the bug**
The Output panel supports common ANSI escape sequences for bold/italic/colored/etc text. However, despite supporting the sequences for basic foreground/background colors, and 256-color foregrounds, it misinterprets 256-color backgrounds as other escape commands.

**To Reproduce**
Write code that prints a 256-color background escape sequence - of the form `ESC[48;5;Nm`, where N is a decimal integer from 0..255 - and some text afterwards, and enable 'Run the compiled output'.

**Expected behavior**
The output text is drawn with the correct background colors.

**Link**
https://gcc.godbolt.org/z/T55z1c

**Screenshots**
<img width="743" alt="Screen Shot 2020-11-03 at 23 52 38" src="https://user-images.githubusercontent.com/2166769/98053560-b80c2800-1e30-11eb-9e71-e996fd7c0ade.png">

**Desktop**
 - OS: macOS 10.14.6
 - Browser: Chrome 86.0.4240.183

**Comment by partouf** [comment]
According to putty it's supposed to look like this:
![image](https://user-images.githubusercontent.com/442630/98054610-ac722e80-1e3b-11eb-91c5-0c4efedde279.png)

Seems also the text gets cut off at 7 in CE while it's supposed to go on until 255

**Comment by lunasorcery** [comment]
Looking at the `ESC[48;5;Nm` compound escape sequence, my _guess_ is it doesn't know how to handle the 48 and starts treating the following parameters as raw SGR commands. So the 5 gets interpreted as SGR 5 "Slow Blink" which would explain the output being wrapped in <blink> tags. And then it treats the color specifier as a raw SGR parameter - so in this case we get the following:

- 0 "Reset"
- 1 "Bold"
- 2 "Faint or decreased intensity"
- 3 "Italic"
- 4 "Underline"
- 5 "Slow Blink"
- 6 "Rapid Blink"
- 7 "Reverse video"
... and then we hit 8 "Conceal" which is presumably why the rest of the output goes missing.

reference: https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_parameters

**Comment by partouf** [comment]
Right, the code actually seems to ignore 48 things

https://github.com/compiler-explorer/compiler-explorer/blob/5136152d367887c295d2c3cca04085c01c119b34/static/ansi-to-html.js#L284

This code came from https://github.com/rburns/ansi-to-html but they haven't updated the code in this regard either. I wonder what 49 even is.

**Comment by partouf** [comment]
OH, there's a pull request for it https://github.com/rburns/ansi-to-html/pull/84

**Comment by lunasorcery** [comment]
49 is 'reset background to default' FYI 🙂

**Comment by mattgodbolt** [comment]
Some progress (in an upcoming fix):

![Screenshot from 2021-04-01 14-05-12](https://user-images.githubusercontent.com/633973/113341869-5672bb80-92f3-11eb-88e9-630bb5f3541b.png)
