### ISSUE TITLE
[BUG] "Filter unused labels" removes a label that's used

### ISSUE THREAD

**Issue by josephcsible** [compiler-explorer/compiler-explorer#2323]
**Describe the bug**
The option to filter out unused labels will sometimes incorrectly filter out used labels too.

**To Reproduce**
Compile this C code with Clang with the option to filter unused labels turned on:

```c
__asm__(
    ".globl x\n"
    "x:\n\t"
    ".quad 0\n\t"
    ".quad ."
);
```

**Expected behavior**
I expect `.Ltmp0` to not be filtered out, since it's used.

**Link**
https://godbolt.org/z/jsYKb8

**Comment by mattgodbolt** [comment]
You're not wrong there; that's surprising. Thanks for the fantastic small repro case!

**Comment by partouf** [comment]
related to https://github.com/compiler-explorer/asm-parser/issues/4
(not entirely sure a pointer like this should constitute as usage though, a lot of things would be used in that case)

**Comment by dkm** [comment]
Also found a case of badly filtered label : https://godbolt.org/z/Khq6n7abx
```
1:
copyd $r62 = $r2
;;
acswapw 0[$r0], $r62r63
;;
cb.dnez $r62? 2f
;;
;;
lws $r63 = 0[$r0]
;;
compw.ne $r62 = $r63, $r1
;;
cb.deqz $r62? 1b
;;
2:
```
The `1b` and `2f` are referring to `1:` and `2:`, but these are filtered out. Not sure if it's related to this one, or maybe only to KVX assembly. If you suspect it's something different, I'll open a separate issue.

**Comment by partouf** [comment]
@dkm that one is I think related to https://github.com/compiler-explorer/compiler-explorer/issues/2034

**Comment by dkm** [comment]
Ah thanks, didn't see this obvious one when searching!

**Comment by Maykeye** [comment]
Today stumbled on the same issue in "normal" c++ code(no manual__asm__ or .quads) that ​uses std::copy in for loop: 
https://godbolt.org/z/vGcnWM575

   ​for(int i = 0; i < arr[0]; i++)    
       ​std::copy(&arr[i-1],&arr[i],&arr[i]); 

in gcc 11.2 -O3 there is `jg .L2`, but .L2 is gone.

**Comment by partouf** [comment]
> Today stumbled on the same issue in "normal" c++ code(no manual__asm__ or .quads) that ​uses std::copy in for loop:
> https://godbolt.org/z/vGcnWM575
> 
> ```
> ​for(int i = 0; i < arr[0]; i++)    
>     ​std::copy(&arr[i-1],&arr[i],&arr[i]); 
> ```
> 
> in gcc 11.2 -O3 there is `jg .L2`, but .L2 is gone.

That's a bug that we can actually fix for sure. I'll make sure that we do.

**Comment by mattgodbolt** [comment]
I just split that bug out as a separate one as it seems unrelated to the `1f` / `2b` forward-backwards this bug is mostly about.

**Comment by OfekShilon** [comment]
This happens because this code: https://github.com/compiler-explorer/compiler-explorer/blob/e19d6ef24ba5d14a3148e5868612204c71f2a51d/lib/parsers/asm-parser.ts#L273

restrics the addition to `labelsUsed` to just `inFunction` cases. If you place the same snippet in a function it filters properly: https://godbolt.org/z/o6hhcxPf3

Before I just make a PR with `inFunction` removed let me ask - does anyone know why was it put there in the first place? This is its sole usage so it was certainly intentional.

@mattgodbolt  @partouf

**Comment by partouf** [comment]
There's always a reason, but it's also always a weighing of options among many different kinds of asm dialects, compilers and usecases. I think we should not be too fast in changing something to help inline asm that isnt formatted in a way that compilers would unless there is very little impact on other scenarios. So I would not be a fan of said change, as it would impact too much code (I think)

**Comment by OfekShilon** [comment]
@partouf  I agree completely. @josephcsible is this a simplification of some non-contrived scenario?  Can you paste it here?

**Comment by josephcsible** [comment]
> is this a simplification of some non-contrived scenario?

It definitely was, since that's how I found the bug in the first place.

> Can you paste it here?

It's been so long that I can't remember what it was :(

**Comment by OfekShilon** [comment]
Closing until some concrete repro arises.
