### ISSUE TITLE
[REQUEST] Add movfuscator compiler

### ISSUE THREAD

**Issue by bence42** [compiler-explorer/compiler-explorer#2325]
Chris Domas's movfuscator compiler can generates assembly for C with mov instructions only.
I could be added just for fun.

movfuscator repo:
https://github.com/xoreaxeaxeax/movfuscator

**Comment by mattgodbolt** [comment]
Oh excellent idea! :grinning:

**Comment by partouf** [comment]
https://github.com/compiler-explorer/compiler-explorer/issues/985

**Comment by mattgodbolt** [comment]
Oh my! Closing in favour of that  :)

**Comment by bence42** [comment]
Oh, sorry for the duplication. I was actually surprised that github didin't give me a warning about an existing similar issue, I figured somebody else must have thought about this. I'll try doing this myself.
