### ISSUE TITLE
[REQUEST] Shader languages: GLSL, HLSL, SPIR-V...

### ISSUE THREAD

**Issue by ojeda** [compiler-explorer/compiler-explorer#2331]
Currently we have compilers for a lot of general purpose programming languages, as well as specialized compilers like ispc and CUDA. It would be great to support shader/graphical languages and their many compilers, too.

Non-exhaustive list:

  - GLSL
    + glslangValidator/glslc (to AST / SPIR-V): https://github.com/KhronosGroup/glslang, https://github.com/google/shaderc
    + LunarGOO (optimize): https://github.com/LunarG/LunarGLASS
    + shader_translator (to ESSL/GLSL compat/GLSL xyz/Vulkan GLSL/HLSL 9/HLSL 11): https://github.com/google/angle

  - HLSL
    + FXC (to DXBC): the older one for SM <= 5, included in SDK/VS.
    + DXC (to DXIL / SPIR-V): https://github.com/microsoft/DirectXShaderCompiler
    + glslangValidator/glslc (to AST / SPIR-V): https://github.com/KhronosGroup/glslang, https://github.com/google/shaderc
    + FXC + HLSLcc (to GLSL/ESSL/Vulkan GLSL/MSL): https://github.com/Unity-Technologies/HLSLcc
    + hlsl2glsl (to GLSL): https://github.com/aras-p/hlsl2glslfork
    + hlslparser (to HLSL 10/MSL/GLSL): https://github.com/Thekla/hlslparser

  - SPIR-V
    + spirv-as/opt/val (assemble/optimize): https://github.com/KhronosGroup/SPIRV-Tools
    + spirv-cross (to GLSL/HLSL/MSL): https://github.com/KhronosGroup/SPIRV-Cross
    + llvm-spirv (to LLVM IR): https://github.com/KhronosGroup/SPIRV-LLVM-Translator

  - LLVM IR
    + llvm-spirv (to SPIR-V): https://github.com/KhronosGroup/SPIRV-LLVM-Translator

I would prioritize setting up Khronos' glslang/SPIRV-Tools/SPIRV-Cross and Microsoft's FXC/DXC.

Related to #2244, although the first step would be getting the compilers installed and working on their own.

**Comment by partouf** [comment]
A lot of things have been implemented, let's close this until something specific comes up

**Comment by ojeda** [comment]
I intended this as a meta-issue since it groups many things that could be added. So far, as far as I understand, HLSL via DXC (and RGA) was added, but GLSL as a language is missing, as well as major compilers like FXC for HLSL which is required for shader models < 6.
