### ISSUE TITLE
[REQUEST] MSVC as C compiler

### ISSUE THREAD

**Issue by Wirtos** [compiler-explorer/compiler-explorer#2335]
MSVC 16.8 now supports standalone non-cpp C11 and C17 compilation, could you add them to the list of the C compilers regarding the ability to view generics-based flow compilation result? C++ also has no proper designated initilizers, so rewriting such code in order to launch it as C++ can be quite a challenging task. Currently on the site I only see VS2017 wine MSVC as a C compiler.

**Comment by partouf** [comment]
This has been a long-standing request -> https://github.com/compiler-explorer/compiler-explorer/issues/1371
