### ISSUE TITLE
[LIB REQUEST] Vector Class Library(VCL) - missing from MSVC

### ISSUE THREAD

**Issue by JeffFlinn** [compiler-explorer/compiler-explorer#2344]
**Describe the bug**
Agner Fog's Vector Class Library is accessible from gcc, clang, icc but not any msvc compiler selections.

**To Reproduce**
Select any of gcc, clang, icc compilers. Select library and add Vector Class Library
Select any msvc compiler and Vector Class Library is not accessible

**Expected behavior**
Expected to select Vector Class Library for msvc

**Comment by timmy-ms** [comment]
Added and will be deployed Friday.
