### ISSUE TITLE
[REQUEST] dlang DMD compiler versions (stable and nightly) are outdated

### ISSUE THREAD

**Issue by baryluk** [compiler-explorer/compiler-explorer#2348]
Hi,

I love godbolt, and often use it for C, C++, D.

I noticed that the latest DMD compiler for dlang is 2.092.0, but the https://dlang.org/ has 2.094.2 for example.

Also selecting DMD nightly, selects a build DMD64 D Compiler v2.091.0-beta.2-master-ec39fe5 , which is older than 2.092 even.

Granted, it is not too old, DMD 2.092.0 was released in 2020-05-10, but 2.093 and 2.094, has some important bug fixes (handling of always inline fixes, better support for `@live` and new handling of `in` paramters (with `-preview=in`), which are rather revolutionary new features in D (making it almost like Rust in many regards, at least allow you to write Rust style code).

The update to 2.094 with new `in`, might require updating D demangler ( see https://dlang.org/changelog/2.094.0.html#in-identity ) using Phobos from 2.094.

Thanks.

**Comment by mattgodbolt** [comment]
Hi there! We encourage users to submit pull requests to update compilers they're interested in. We try to make it as [easy as possible](https://github.com/compiler-explorer/compiler-explorer/blob/master/docs/AddingACompiler.md). That said; I'll do this and link the changes here so you can see how it's done!

**Comment by mattgodbolt** [comment]
The nightly being out of date is more puzzling, and I'll investigate.

**Comment by mattgodbolt** [comment]
@baryluk -- the nightly install comes from us running `install.sh` from the dlang.org website. That installs the version you mention above. Is there another way we can get a "nightly" DMD compiler?

**Comment by mattgodbolt** [comment]
that is, we run:

```
../install.sh install dmd-nightly -a -p $(pwd)
```

(via https://dlang.org/install.html#switchdmd-nightly)

**Comment by mattgodbolt** [comment]
The 2.094.2 compiler will be available on the next restart; I don't know how to test the demangler. We build a demangler using gdc -> https://github.com/compiler-explorer/tools/blob/master/d/demangle.d - currently built using gdc 5.2 ( https://github.com/compiler-explorer/tools/blob/master/get_compilers.sh#L56 )

**Comment by partouf** [comment]
this was added a while ago
