### ISSUE TITLE
[BUG] MSVC fails to include "arm_neon.h"

### ISSUE THREAD

**Issue by obfuscated** [compiler-explorer/compiler-explorer#2349]
Use:
```
#include <arm_neon.h>
```
Select `ARM64 msvc v19.14 WINE` and the compiler fails with this message:

```
/opt/compiler-explorer/windows/19.14.26423/include/arm_neon.h(17): fatal error C1189: #error:  This header is specific to ARM targets
Internal Compiler Error in Z:\opt\compiler-explorer\windows\19.14.26423\bin\Hostx64\arm64\cl.exe.  You will be prompted to send an error report to Microsoft later.
INTERNAL COMPILER ERROR in 'Z:\opt\compiler-explorer\windows\19.14.26423\bin\Hostx64\arm64\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
```

It seems the compiler is too old and broken and needs updating.

**Comment by mattgodbolt** [comment]
Hi: the MSVC compiler doesn't target the arm neon architecture: `#error:  This header is specific to ARM targets`. It's not expected that an x86 compiler can include ARM code.

**Comment by obfuscated** [comment]
In fact it works if you add `/D_M_ARM=1`. Probably changing this as default flag might help.

**Comment by obfuscated** [comment]
Also searching for this error leads to this link https://developercommunity.visualstudio.com/content/problem/201662/arm-neonh-doenst-support-arm64-compiler.html where MS people mention there is a fix for this. Unfortunately they don't mention which version contains the fix. :(

**Comment by mattgodbolt** [comment]
Setting that definition doesn't change the fact that the compiler is not an ARM compiler. You're just working around a specific check in the header itself. Unless I'm really missing something, that's not a default definition we can add (the compiler will define it itself).

**Comment by mattgodbolt** [comment]
I can't access that link (it uses an invalid certificate).

Are you picking the "ARM64 msvc" compiler? Your bug didn't include a Compiler Explorer link (which we ask for); and refers only to "MSVC" which I interpreted as the x86 compiler

**Comment by obfuscated** [comment]
There you go: https://godbolt.org/z/aGzv8M
I clearly have stated: Select `ARM64 msvc v19.14 WINE` :)

**Comment by mattgodbolt** [comment]
Our WINE-based compilers are very old and _extremely_ hacky, so I'm not surprised they're broken unforunately

**Comment by obfuscated** [comment]
This is the broken link: `https://godbolt.org/z/PM7z8K`

**Comment by mattgodbolt** [comment]
And apologies, you did state that. It's early and I haven't had coffee...but this is why I ask for links, :D

**Comment by mattgodbolt** [comment]
Thanks! So....like you said, adding _D_ARM etc would be a workaround, after all!

Ideally we'll get "official" MSVC compilers (instead of these WINE workaround). but for now I'll look at adding the `/D` exactly as you originally suggested :blush: Thanks for your patience...

**Comment by obfuscated** [comment]
Seems to be working with the latest arm msvc compilers. No need for defines also.
