### ISSUE TITLE
Error running `npm start`

### ISSUE THREAD

**Issue by amfogor** [compiler-explorer/compiler-explorer#2354]
Cloned the repo, run `npm install`. But running `npm start` gives the following error:

> error: Top-level error (shutting down): (intermediate value).flat is not a function {"stack":"TypeError: (intermediate value).flat is not a function\n    at CompilerFinder.find (D:\\dev_stuff\\compiler-explorer\\lib\\compiler-finder.js:403:53)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n    at D:\\dev_stuff\\compiler-explorer\\node_modules\\esm\\esm.js:1:34535\n    at D:\\dev_stuff\\compiler-explorer\\node_modules\\esm\\esm.js:1:34176\n    at process.<anonymous> (D:\\dev_stuff\\compiler-explorer\\node_modules\\esm\\esm.js:1:34506)\n    at Function.<anonymous> (D:\\dev_stuff\\compiler-explorer\\node_modules\\esm\\esm.js:1:296856)\n    at Function.<anonymous> (D:\\dev_stuff\\compiler-explorer\\node_modules\\esm\\esm.js:1:296555)\n    at Function.<anonymous> (D:\\dev_stuff\\compiler-explorer\\node_modules\\esm\\esm.js:1:284879)\n    at Object.apply (D:\\dev_stuff\\compiler-explorer\\node_modules\\esm\\esm.js:1:199341)\n    at startup (internal/bootstrap/node.js:283:19)"}

Am I missing some steps?

OS Windows 10

**Comment by apmorton** [comment]
what version of node are you running?

**Comment by amfogor** [comment]
@apmorton `v10.17.0`

**Comment by apmorton** [comment]
We require 12.18 or higher - not sure why npm install didn't warn you, as it is listed in the package.json requirements

**Comment by amfogor** [comment]
Would be nice to have this requirement in https://github.com/compiler-explorer/compiler-explorer/blob/master/docs/WindowsNative.md

**Comment by amfogor** [comment]
@apmorton thanks, got it working.  Though it complains about python

> error: Unable to resolve 'python3.7'
error: Unable to resolve 'python3.5'
error: Unable to resolve 'python3.8'
error: Unable to resolve 'python3.6'

Should I care? What's python for?

**Comment by partouf** [comment]
Thats a default properties mistake we made and is still in there, you can just ignore it

**Comment by amfogor** [comment]
Also, off-topic question. Do config files support variables, such that I could compose strings? Is there even documentation for syntax of the config files? Also, would be nice to automatically find all the compilers. At least to have a way to write such a function myself.

**Comment by partouf** [comment]
No variables, no documentation. But if you wanna sketch the scenario here concerning "all the compilers", we're all ears

**Comment by amfogor** [comment]
Not all at once. Just to have separate script files that fill in some groups. Something, anyone can extend.

**Comment by amfogor** [comment]
Oh, I could just write a script that generates a the groups and appends the text to the config.

**Comment by partouf** [comment]
Separate script files isn't really compatible with the live website as we have a humongous amount of compilers and the way the "properties" files work. They accept per language compilers, but they override every time a newer file gets introduced (order is default -> environment (e.g. amazon) -> local).

**Comment by partouf** [comment]
> Oh, I could just write a script that generates the groups and appends the text to the config.

Right, this is what the MSVC instances currently do, source for that is at https://github.com/compiler-explorer/infra/pull/448/files for reference

**Comment by amfogor** [comment]
Nice, thanks
