### ISSUE TITLE
[BUG] low severity vulnerability 'minimist'

### ISSUE THREAD

**Issue by caioaamaral** [compiler-explorer/compiler-explorer#2355]
**Describe the bug**
npm detected [a small vulnerability](https://www.npmjs.com/advisories/1179) when installing 'minimist' package

**To Reproduce**
```shel
git clone https://github.com/compiler-explorer/compiler-explorer
cd compiler-explorer
npm install
```

**Desktop**

 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: master branch

**Comment by OfekShilon** [comment]
Patched in minimist 1.2.3, current installed dependency is 1.2.8
