### ISSUE TITLE
Rust output always __rustc_debug_gdb_scripts_section__:      .asciz  "\001gdb_load_rust_pretty_printers.py"

### ISSUE THREAD

**Issue by gww-parity** [compiler-explorer/compiler-explorer#2356]
For rust I get :
```
__rustc_debug_gdb_scripts_section__:
        .asciz  "\001gdb_load_rust_pretty_printers.py"
```

Even for simple programs like this:

```
#[inline(never)]
fn loop1(n: i64) -> i64 {
  let mut r: i64 = 0;
  let mut a: i64 = 1;
  let mut b: i64 = 1;
  for _ in 0..n {
    r += a * b;
    a = a+1;
    b = b+2;
  }
  return r;
}

fn main() {
    println!("Hello, world!");
    let r = loop1(100_000_000_000);
    println!("loop1(100_000_000_000): {}", r);
}
```

Or parts of that program.

I tried changing to few different rust compiler versions from menu and it looks like it happens to all of them.

**Comment by partouf** [comment]
Seems to be the case since 1.21.0 , but also seems to be normal behaviour as far as I can tell from what google is telling me

**Comment by mattgodbolt** [comment]
We have some hacky regex filters for binary (`binaryHideFuncRe` in the options), perahsp we need to have a similar thing here.

**Comment by gww-parity** [comment]
Maybe this will help https://github.com/rust-lang/rust/blob/master/src/etc/rust-gdb ?

**Comment by zaneduffield** [comment]
If any other idiots end up here, try making the `main` function public to see more than just this in the assembly.
