### ISSUE TITLE
[BUG] Changelog not displaying anything

### ISSUE THREAD

**Issue by peterschussheim** [compiler-explorer/compiler-explorer#2357]
**Describe the bug**

"Changelog" feature in the "Other" dropdown menu, no information is shown.

**To Reproduce**

Select "Other"->"Changelog".

**Expected behavior**

It should display a commit log of this project.

**Link**

https://godbolt.org/z/d6P6hb

**Screenshots**

![2020-12-14 11_17_41-Compiler Explorer and 4 more pages - Peter - Microsoft​ Edge](https://user-images.githubusercontent.com/3654683/102106143-37145900-3dfe-11eb-880b-154aeca9ad6c.png)

**Desktop**

 - OS: windows 10 pro
 - Browser: chrome, edge
 - Version: stable

**Additional context**

**Comment by apmorton** [comment]
Dup of #2340 

I think we just haven't deployed since that was merged

**Comment by peterschussheim** [comment]
OK, thanks for clarifying and feel free to close.
