### ISSUE TITLE
[REQUEST] Allow users to toggle text wrapping in "Execution Only" panel

### ISSUE THREAD

**Issue by peterschussheim** [compiler-explorer/compiler-explorer#2358]
**Is your feature request related to a problem? Please describe.**

When using Compiler Explorer, I often only need to execute the code and to keep the screen with minimal clutter, I use an editor panel with an execution only panel.  Currently, it seems the "Wrap" text option is only available when using the default compiler view.

**Describe the solution you'd like**

Add a checkbox to toggle output text wrapping in "Execution Only" panels.

**Additional context**

- Example link: https://godbolt.org/z/8zWxjG
- Below is a screenshot to make this clear:

![2020-12-14 16_55_08-](https://user-images.githubusercontent.com/3654683/102141618-1a444980-3e2f-11eb-9bfd-87abdf4b0a61.png)

I'd be happy to send a patch if this request is approved.

**Comment by partouf** [comment]
Sounds good to me!
Feel free to ask away in the discord for help as to where and how, but it shouldn't be too hard to find. (Though when we made the panel we ran into an issue I think, but it was probably mostly laziness about fixing it)

**Comment by partouf** [comment]
This is now live
