### ISSUE TITLE
Build boost binary libraries

### ISSUE THREAD

**Issue by Spongman** [compiler-explorer/compiler-explorer#2364]
i added boost 1.71.0 in 'Libraries', but it can't find the libs.

**To Reproduce**
https://godbolt.org/z/KfedEs

````
#1 with x86-64 gcc 7.3
/opt/compiler-explorer/gcc-7.3.0/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -lboost_regex
collect2: error: ld returned 1 exit status
Compiler returned: 1
````

**Comment by partouf** [comment]
We don't build anything from the boost library. If you don't compile to binary and leave out -lboost_regex, you'll still be able to see the assembly.

I don't think we can support linking to boost, but I'm open to suggestions how to configure their custom build scripts to build for all our compilers.

**Comment by AmeyaVS** [comment]
@Spongman, If you are looking for linking with shared/shared libraries, one can run a local configured instance of compiler-explorer with the built shared boost binary libraries.
I currently got the environment set up locally with custom shared/static libraries linking working in the local instance with execution support.

**Comment by Spongman** [comment]
seems weird to me that _some_libs (like random xml libraries nobody's ever heard of) are supported, but _not_ boost.

**Comment by partouf** [comment]
> seems weird to me that _some_ libs (like random xml libraries nobody's ever heard of) are supported, but _not_ boost.

Like I said, if you have any suggestions on how to do it, please do. All the libraries that we do build support CMake, Boost does not.

**Comment by partouf** [comment]
From Boost 1.85 we're starting to build the binary libraries, but boost_regex does not appear to require linking anymore
So this works without issues https://godbolt.org/z/GKWqMcb5n
