### ISSUE TITLE
[BUG] Not working in Brave Browser anymore

### ISSUE THREAD

**Issue by webloft** [compiler-explorer/compiler-explorer#2372]
Shows other tabs than Firefox: Wrap Lines / Libraries / Compilation / Arguments / Stdin / Compiler output

C++ demo output:

/opt/compiler-explorer/gcc-10.2.0/bin/../lib/gcc/x86_64-linux-gnu/10.2.0/../../../../x86_64-linux-gnu/bin/ld: /lib/x86_64-linux-gnu/crt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status

**Comment by webloft** [comment]
I have reset code and UI layout. It's working again.

**Comment by mattgodbolt** [comment]
Hi there; if you see this again please share a short link to the code. My guess here is you had the "run the code" flag ticked, but didn't provide a `main()`.

**Comment by webloft** [comment]
No. The demo code provided by the c++ example just produced that.

**Comment by mattgodbolt** [comment]
We only perform linking (the error you mention above) if the "run code" or "display binary" is ticked. So I'd have loved to have had a URL to debug this with, if that wasn't the case. If you see it again please do share a short URL if you can.

**Comment by webloft** [comment]
Sorry, I cannot provide this. I just went to https://godbolt.org and yes there was a last code stored but I could not ran any other code too. Even the C++ example did not work. The mentioned options were not set and I never saw this kind of layout before.

I cleared local storage and cache in the browser - it does not help.
Then I used the restore UI layout function and it worked again.

**Comment by mattgodbolt** [comment]
Thanks for the info. That's very puzzling indeed. If you see it again please create a "short URL" and post that as it will capture all the settings you have.

**Comment by webloft** [comment]
I have played a little. 

It seems somehow the Executor tab was activated and the Compiler tab closed and I did not realize it was the wrong tab since I never used it before. And the tab appears by clicking on 'Add new Pane' + 'Executor from this'.
