### ISSUE TITLE
[BUG] the "artificial" attribute on a function is not respected

### ISSUE THREAD

**Issue by eyalroz** [compiler-explorer/compiler-explorer#2373]
**Describe the bug**
See this example.

**To Reproduce**
See [this example](https://godbolt.org/z/7o8se7). The `add` instruction is mapped to the statement resulting in it directly,  i.e. to the line within the `bar()` function.

**Expected behavior**
The `add` instruction should be mapped to the point of inlining, i.e. to the line within the `foo()` function.

**Additional context**
I've been told that the attribute makes the compiler emit a `DW_AT_artificial` debug info tag (a DWARF tag I guess?) and that this is what Compiler Explorer is ignoring.

**Comment by partouf** [comment]
If you disable all the filters you can see the (dwarf) debug tags the assembly output generaties, we use the .loc directives for the source line reference (.loc first parameter is file (1 = example.cpp), second is the line)

We use -g for the debugging info. There might be other dwarf or stabs options (I just tried -gstabs and -gstabs+ which add debugging info at slightly different spots, but also seems to make less sense)

**Comment by eyalroz** [comment]
Hmm. It seems that if I compile with `-gstabs`, the `artificial` tag does have the appropriate impact on the compiler explorer's choice of line to highlight. Weird that there doesn't seem to be an appropriate DWARF directive being emitted.
