### ISSUE TITLE
[BUG] Wrong word in ADDSS opcode description

### ISSUE THREAD

**Issue by phip1611** [compiler-explorer/compiler-explorer#2380]
Hi, there is a typo in the ADDSS opcode description. It seem like compiler-explorer just includes the value from https://www.felixcloutier.com/x86/addss - I contacted felix and he told me to forward the issue to Intel. So I contacted Intel by email and by Twitter; hopefully they'll fix it soon in the original documentation. 

If you just include the content from his website - fine, nothing to do here, this can be closed.

Otherwise please make the following change:

**Is**

> Adds the low single-precision floating-point values from the second source operand and the first source operand, and stores the **double**-precision floating-point result in the destination operand.

**Should be**
> Adds the low single-precision floating-point values from the second source operand and the first source operand, and stores the **single**-precision floating-point result in the destination operand.

**Comment by partouf** [comment]
This description is also not changed in the updated version of May 2020 https://software.intel.com/content/dam/develop/public/us/en/documents/325462-sdm-vol-1-2abcd-3abcd.pdf

**Comment by RubenRBS** [comment]
As the script does not get automatically executed, we can edit the asm docs - We'll just have to remember to check it when updating it. Thanks for the heads-up!

**Comment by Midas847** [comment]
Is this issue still open? I am a new contributor and this would be a good start.

**Comment by Midas847** [comment]
Oh thanks @mattgodbolt I'll look for some other issues.

**Comment by partouf** [comment]
Rechecked the Intel pdf which was updated December 2021, but that line is still the same.

**Comment by partouf** [comment]
Pdf was updated December 2022, but has not changed on this front. Don't think it's ever going to happen

**Comment by OfekShilon** [comment]
Oct 2024, still unfixed.
