### ISSUE TITLE
[REQUEST] support arm assembly

### ISSUE THREAD

**Issue by gengjiawen** [compiler-explorer/compiler-explorer#2387]
**Is your feature request related to a problem? Please describe.**
Currently looks like only x86 assembly is supported.
![image](https://user-images.githubusercontent.com/3759816/104404019-c2ffd900-5594-11eb-8e6b-06eddb4abbe9.png)

**Describe the solution you'd like**

gcc has toolchain for arm. Maybe we can use this to achieve.

**Describe alternatives you've considered**

**Additional context**

This will be nicely to have since arm gains great popularity on mobile platforms.

**Comment by partouf** [comment]
Can you indicate if adding the compilers that are currently available for C++ are a good enough addition? I think most - at least the recent versions - are complete enough to be made available for direct Assembly.

**Comment by gengjiawen** [comment]
> Can you indicate if adding the compilers that are currently available for C++ are a good enough addition? I think most - at least the recent versions - are complete enough to be made available for direct Assembly.

Yeap. But currently compiler-explorer only support x86-64 assembly.

**Comment by mattgodbolt** [comment]
See also #1582
