### ISSUE TITLE
[BUG] Compilation with DMD does not work

### ISSUE THREAD

**Issue by deadalnix** [compiler-explorer/compiler-explorer#2391]
As per title, it seems like there is some piece broken in the pipeline. Other D compilers seems to work as expected.

**Describe the bug**
When trying to compile a D sample using the DMD compiler, any version, one gets the following error:

```
Could not execute the program
Compiler returned: 1
Compiler stderr

cc: Permission denied
Error: linker exited with status 255
```

**To Reproduce**
1/ Open compiler explorer.
2/ Select D as a language using the dropped menu in the source document.
3/ Write a simple D program, for instance:

```d
int main() { return 0; }
```

**Expected behavior**
The programs compiles and usual compile explorer features can be used.

**Link**
https://godbolt.org/z/rdKbbM

**Comment by RubenRBS** [comment]
Acclaration: This refers to executing the D code. DMD does compile fine, but does not execute

**Comment by deadalnix** [comment]
@RubenRBS You can check the provided link, this seems to be a linker error because access to cc gets denied.
