### ISSUE TITLE
[REQUEST] configuration of default/suggested command line arguments for tools

### ISSUE THREAD

**Issue by melven** [compiler-explorer/compiler-explorer#2395]
**Is your feature request related to a problem? Please describe.**

I run a local compiler-explorer instance on an HPC cluster and I have a few helpful tools configured in e.g. `etc/config/c.defaults.properties`.
Example: run the binary using a scheduler like SLURM (uses the readelf-tool class)
I would like to provide default command line arguments for the tool but 
```
tool.name.options=...
```
does not seem to have an effect here.
The tool `>_Arguments` (provided by the user in the browser) work fine.

**Describe the solution you'd like**

Use the tool `options` as command line arguments if the user does not specify arguments.
Or fill the arguments input box with the "default" options from the configuration file.

For tools where the user should not be able to change the arguments, the `>_Arguments` field could still show them ->
would make it more transparent what happens in the background...

**Describe alternatives you've considered**

Provide a wrapper shell script for the tool that fills in arguments if none are given - or users just need to know useful arguments.

**Additional context**

I assumed this could be implemented quite easily but couldn't figure out where to set this (I'm not really experienced in node.js etc)
Or this already works but I didn't know how to use it...

**Comment by RubenRBS** [comment]
Hi! Sorry that this took so long to get addressed, thanks for your patience!
I've added an args field to the tools that can be used for this pourpose.

The PR should get merged in a bit if everything goes ok :)

**Comment by melven** [comment]
Hi

thanks for looking into that!

I tried your branch and `args` works really great!

I obtain the default arguments (as expected) and can change them in the ui:
![compiler-explorer-tool-args](https://user-images.githubusercontent.com/3668878/106364041-70f8da80-632c-11eb-836e-1028ca26cc92.png)
configured with
```
tools.srun.exe=/usr/bin/srun
tools.srun.name=srun (SLURM)
tools.srun.type=postcompilation
tools.srun.class=readelf-tool
tools.srun.options=-N 1 -n 1 - c 1 --cpu-bind=core
```


However, when I specify `options` instead, there seems to be no effect and changing the argument field still sets tool options...

Tool configuration:
```
tools.srun.exe=/usr/bin/srun
tools.srun.name=srun (SLURM)
tools.srun.type=postcompilation
tools.srun.class=readelf-tool
tools.srun.options=--help
```

**Comment by partouf** [comment]
I'm thinking that the base-tool (and so also readelf-tool) doesn't support .options yet.
@RubenRBS I suspect that should probably be used here https://github.com/compiler-explorer/compiler-explorer/blob/master/lib/tooling/base-tool.js#L122

**Comment by partouf** [comment]
@melven I think the PR is complete now on the .options front, can you verify?

**Comment by melven** [comment]
The `.options` field now has an effect in my tests.

The complete command-line arguments are now composed of the options and any additional user input in the arguments field.

For me, this works fine now.

Thanks!

**Comment by RubenRBS** [comment]
I've now merged this branch, so you can use it from master now.
Thanks for taking the time to open your request, and again, sorry that it took so long to get adressed :)
