### ISSUE TITLE
Some asm mnemonics on aarch64 doesn't have tooltips

### ISSUE THREAD

**Issue by baryluk** [compiler-explorer/compiler-explorer#2400]
Example: https://godbolt.org/z/87Gs81

bic, orr, ldr, stp, adrp

doesn't have tooltip with help.

No idea where these are defined.

**Comment by mattgodbolt** [comment]
We don't currently support anything but x86. Closing in favour of #507

**Comment by baryluk** [comment]
@mattgodbolt Makes sense!

Thank you.
