### ISSUE TITLE
Is there an API usage limit?

### ISSUE THREAD

**Issue by kangalioo** [compiler-explorer/compiler-explorer#2404]
Hi, first of all, _thank you_ for this fantastic website! I've been playing around with godbolt integration for a Rust bot, and it was lightning fast and super pretty.

Someone pointed out to me that it may be abuse of the API to direct a Discord bot at it. I couldn't find any information about API usage limits or usage rules in the documentation though.

Is it okay to use the API in a public Discord bot?

It may potentially be useful to add this information to the API docs for future reference

**Comment by apmorton** [comment]
I think as a general rule so long as you haven't built a cmake backend based on our API to compile all your code it's likely fine.

FWIW, there are already several third party IDE plugins and whatnot that use our API.

**Comment by kangalioo** [comment]
Thank you!

**Comment by mattgodbolt** [comment]
Thanks both! Like @apmorton says no limit as such, just be sensible :) There's a discord bot that uses CE already at https://github.com/Headline/discord-compiler-bot if that's helpful.

Right now the API is totally free with no limits. We've had it for many years and so far haven't had to make any limiting type stuff. If we ever do we'll do our best to give notice first :)
