### ISSUE TITLE
[REQUEST] Language drop-down should allow typing for filtering

### ISSUE THREAD

**Issue by ojeda** [compiler-explorer/compiler-explorer#2410]
**Is your feature request related to a problem? Please describe.**
Now that we support a lot of languages, scrolling through them becomes tedious.

**Describe the solution you'd like**
When the language drop-down list is open after clicking on it, typing in the keyboard should go to the matching language. This matches the behavior in other GUIs (e.g. a typical file browser).

Alternatively, showing a bigger list in the drop-down would also partially alleviate the problem.

**Comment by partouf** [comment]
I'm confused, you can already type to find the language you want... (after hitting backspace)

**Comment by ojeda** [comment]
Ah, didn't know about that, thanks! Then the request is about removing the requirement of hitting backspace :-)

**Comment by supergrecko** [comment]
Looking into this, it seems it's actually possible to search on top of what is already filled into the box

![image](https://user-images.githubusercontent.com/42585241/145024963-db6111a9-3ea6-4028-a5c2-ca13fd68c54d.png)

Will be looking for a fix for this.

**Comment by supergrecko** [comment]
Closed by 0b32c7e9167188438d6437969de543d060de423f in #3162

**Comment by ojeda** [comment]
Thanks!
