### ISSUE TITLE
[REQUEST] Add Header only library units.hpp

### ISSUE THREAD

**Issue by okkenator** [compiler-explorer/compiler-explorer#2414]
Add Header only library units.hpp from Calum Grant
This library can be found here: https://github.com/r-lyeh-archived/units 
The single file is here: https://github.com/r-lyeh-archived/units/blob/master/units.hpp

**Comment by AwesomeCookieButter** [comment]
Unless you prefer to not add a library that has a single header file in favor of using #include "https://raw.githubusercontent.com/r-lyeh-archived/units/master/units.hpp"

**Comment by RubenRBS** [comment]
Hi! Thanks for the suggestion. We already have a pretty similar library, https://github.com/mpusz/units - I'm not against the idea of adding your requested library, but it does seem like it does not receive much support nowadays. I'll let others decide tho

**Comment by AwesomeCookieButter** [comment]
I see what you mean.  Since it is one file it is easy enough to #include "https://raw.githubusercontent.com/r-lyeh-archived/units/master/units.hpp".  I was considering doing this myself to get familiar with the process but maybe this would just clutter the library list.

**Comment by RubenRBS** [comment]
Sorry that I let this slip thru.
Please! Do not let me stop you from opening a PR for this library. We would gratefully merge it even with the mentioned overlap.

We would love to help you if needed if you end up implementing this! :)

**Comment by okkenator** [comment]
No Man, this is no problem.  I should have looked at existing units libs.  You were right that this lib is not maintained.  I will look at mpusz when I get a chance.
