### ISSUE TITLE
[BUG] Default Rust to binary rather than library

### ISSUE THREAD

**Issue by jonathandturner** [compiler-explorer/compiler-explorer#2416]
**Describe the bug**

Currently, godbolt expects Rust input to be a library. While handy, this isn't the default for either `cargo` or `rustc`, the two main tools for building Rust code. Rust programmers will have muscle memory and expect the default source they write to target binaries rather than libraries.

**To Reproduce**
Write a bit of Rust with a main, and notice how nothing useful is produced on the right hand side.

**Expected behavior**
Including the main function should be sufficient to see useful output on the right hand side.

**Link**
https://godbolt.org/z/q3YEY3

**Comment by partouf** [comment]
I think by now most people know that main needs to be marked as `pub fn main()`, but maybe it requires an appropriate initial code example and extra code example to demonstrate this on the website.

**Comment by mattgodbolt** [comment]
Thanks! Changing defaults can be tricky for us as it essentially invalidates previously saved URLs.  That might be worth doing in this case, I'm not sure how to judge the risk.

For now you can add `--crate-type bin` into the params. (e.g. https://godbolt.org/z/4z9v44 )  For the default example of "square function" this yields a compilation error (in all our other languages we don't expect the user to provide a main() function as that's usually unnecessary to show the compiler output). Adding a `main()` fixes the problem: https://godbolt.org/z/qP3G8K but then exposes the user to a lot of rust internals (e.g. compare the output here: https://godbolt.org/z/GrxT31 ) 

So, compared to other languages on compiler explorer, that would be a surprising change. I'm not sure what to do here: this would make Rust the exception on CE, but maybe rust folks tend to put code in main more? I don't know.

**Comment by mattgodbolt** [comment]
Some random internet dude (@lefticus ) pointed out in Discord:

> Keeping that in mind, if you click the "run this program" button for that rust example, it runs and shows you the output as expected, but the ASM is basically empty
> that's definitely a disconnect

e.g. taking @jonathandturner 's example and clicking the "Run output" ( https://godbolt.org/z/8TETdo ) you get the same output (e.g. no actual `main` function), but the code executes.

I'm not sure how to square this circle; if we detect "and run" we could switch to `--crate-type bin` (https://godbolt.org/z/o6sn5K ) but for all the reasons above that looks worse, IMO. That is, the output is 99% rust standard library gook, and not the function the user wrote.

**Comment by jonathandturner** [comment]
@mattgodbolt I wonder if putting `--crate-type lib` in the default arguments would be enough to visually cue people in that lib is the default and how they might change it.

**Comment by mattgodbolt** [comment]
By default arguments do you mean pre-populating the user arguments with `--crate-type lib` ? We've not supported that, as it's a bit dependent on the compiler version(s) in general, but for this one it does actually make sense I suppose.

**Comment by jonathandturner** [comment]
@mattgodbolt - yeah, exactly

**Comment by ojeda** [comment]
I'd say most people don't expect to build binaries in CE. On the other hand, it is true that many reductions in issues in rust-lang/rust are presented with `main()` (perhaps due to Rust's playground server).

I think the easiest approach is to add a comment to the example, something like:

    // Type your code here, or load an example.
    pub fn square(num: i32) -> i32 {
        num * num
    }
    
    // If you use `main()`, declare it as `pub` to see it in the output:
    // pub fn main() { ... }

**Comment by partouf** [comment]
I agree with @ojeda 's comments, I think this is much simpler and transparant

**Comment by partouf** [comment]
example with commented out main is now default and I have added an extra executable example in the load/save dialog

**Comment by ojeda** [comment]
Thanks a lot! :-)

**Comment by lolbinarycat** [comment]
@partouf i want to inspect the generated `_start` symbol, which is obviously only generated with `--crate-type bin`, and the workaround of specifying it manually no longer works with new rustc versions, as it will conflict with the earlier `--crate-type lib` statement instead of overriding it, is there any chance this issue could be reopened?
