### ISSUE TITLE
How to disable coloring? (in Rust output)

### ISSUE THREAD

**Issue by kangalioo** [compiler-explorer/compiler-explorer#2420]
Is it possible to disable the pretty colors produced by Godbolt for Rust compilations? I tried passing `--color=never`, but since Godbolt already passes a `--color=always` flag on its own, rustc complains: `error: Option 'color' given more than once`.

Can you prevent Godbolt from passing the `--color=always` flag?

**Comment by mattgodbolt** [comment]
Hi: there's currently no way to disable colouring on Compiler Explorer, sorry.
