### ISSUE TITLE
[BUG] **Doesn't work on mobile phones**

### ISSUE THREAD

**Issue by Carpall** [compiler-explorer/compiler-explorer#2422]
**Describe the bug**
the website in unusable from the phone (with or without desktop mode)

**To Reproduce**
open the website on the smartphone (every browser)

**Expected behavior**
it should work like works on a pc

**Desktop**

 - OS: ANDROID
 - Browser: e.g. edge, chrome
 - Version: ?

**Comment by partouf** [comment]
Hi, we're unable to make our editor (https://microsoft.github.io/monaco-editor/) work for mobile phones.

So we have a thread about the changes we made https://github.com/compiler-explorer/compiler-explorer/issues/2042
