### ISSUE TITLE
[BUG] Issues with compilling and running LLVM snippet on Clang/GCC and MSVC

### ISSUE THREAD

**Issue by danilaml** [compiler-explorer/compiler-explorer#2425]
**Describe the bug**
When attempting to compile a snippet using LLVM library, it works fine for GCC/Clang, but fails linking (so can't be run) and MSVC version (LLVM from vcpkg) fails to find includes.

**To Reproduce**
Add LLVM library and compile a sample code using LLVM includes and functions.

**Expected behavior**
It compiles and runs on all compilers.

**Link**
https://godbolt.org/z/3rqMWb

**Desktop**

 - OS: Windowx 10 x64
 - Browser: Firefox
 - Version 84.0.1

**Additional context**
It's likely missing some linker/CFLAGS.

**Comment by partouf** [comment]
So these are 2 separate issues:

* MSVC not having LLVM installed correctly? We can check this. I think it's configured correctly (https://github.com/compiler-explorer/infra/blob/main/windows/msvce-config.json#L208), but in the vcpkg/installed folder that I built back in December on my machine doesn't contain llvm. Might it not actually be supported and should it be removed @strega-nil ? 

* For Clang & GCC, we don't build binaries for the llvm library. I wasn't aware this was needed. We will have to figure out if this is possible with the infrastructure we have for binaries. So no promises, but I will look into it.

**Comment by danilaml** [comment]
@timmy-ms appears to be in the same state as before: https://godbolt.org/z/xfePq5s5b

**Comment by mgood7123** [comment]
llvm libraries dont seem to link either https://godbolt.org/z/vPqj496x9

**Comment by partouf** [comment]
llvm library binaries are now available for llvm 19.1.0 and trunk. (though the original link won't work because it relies on things that llvm 19 does not have anymore)

For MSVC, I will close this issue in favor of https://github.com/compiler-explorer/compiler-explorer/issues/7194
