### ISSUE TITLE
[REQUEST] Add `zig cc` as a C compiler

### ISSUE THREAD

**Issue by ojeda** [compiler-explorer/compiler-explorer#2427]
The Zig compiler has a C frontend invoked with `zig cc` which would be nice to add to the C compilers list.

**Comment by mattgodbolt** [comment]
Just curious here: how does `zig cc` differ from invoking the compiler directly?

..answering my own question... https://andrewkelley.me/post/zig-cc-powerful-drop-in-replacement-gcc-clang.html - interesting :)

**Comment by partouf** [comment]
this is live since yesterday

**Comment by ojeda** [comment]
Thanks a lot!
