### ISSUE TITLE
[REQUEST] clang/opt/llc 11.0.1 are not available for LLVM IR input

### ISSUE THREAD

**Issue by topperc** [compiler-explorer/compiler-explorer#2430]
**Is your feature request related to a problem? Please describe.**
11.0.1 is supported for C and C++ input, but not LLVM IR

**Describe the solution you'd like**
Add clang/opt/llc for 11.0.1 to the version drop down for LLVM IR

**Describe alternatives you've considered**

**Additional context**

**Comment by RubenRBS** [comment]
Hi! Thanks for the heads up :)
I've added the missing versions, and they should appear on the site  shortly.
