### ISSUE TITLE
Privacy policy typo

### ISSUE THREAD

**Issue by Pokechu22** [compiler-explorer/compiler-explorer#2432]
https://github.com/compiler-explorer/compiler-explorer/blob/2aaf9038917f910f846895a6b83f51e17db98dd7/static/policies/privacy.html#L103

This should be changed to say <q><del>Thy</del> <ins>They</ins> are kept for no more than one month</q>.  (Or it could say "thy data are kept", but I don't think the archaic second person determiner was intended.)

**Comment by mattgodbolt** [comment]
Ah! Yes. Blast! The spellchecker didn't catch that of course... I did not mean _thy_ :D hahah

Thanks...we will probably leave it until we have a substantive change unless anyone thinks it's particular confusing. A change causes a pop-up on everyone's next login, so we try to minimize.

**Comment by Pokechu22** [comment]
I did a more thorough reading and found a few more typos (but overall, it's a very readable privacy policy; good job!)

https://github.com/compiler-explorer/compiler-explorer/blob/2aaf9038917f910f846895a6b83f51e17db98dd7/static/policies/privacy.html#L128

This should probably say <q>Local storage is used to remember <ins>the</ins> user's settings</q>.

https://github.com/compiler-explorer/compiler-explorer/blob/2aaf9038917f910f846895a6b83f51e17db98dd7/static/policies/privacy.html#L56-L57

I at least would use a comma instead of a semicolon; I generally avoid semicolons before conjunctions (but I'm not sure if this is actually a rule or some personal style I invented).

https://github.com/compiler-explorer/compiler-explorer/blob/2aaf9038917f910f846895a6b83f51e17db98dd7/static/policies/privacy.html#L77

There's a space before the period here.

**Comment by mattgodbolt** [comment]
Thanks @Pokechu22 !
