### ISSUE TITLE
[BUG] It's impossible to create a long link without a short one being created

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2436]
If for privacy or compliance reasons you don't want to have your code stored in CE, you can create a "long link" or an embed link or similar. However, just bringing up the "share" box stores the short link. This is surprising and potentially worrying for some people.

We should ensure the "short a short link" is still quick and easy to do, but need a way to ensure people who _don't_ want a short link created can still share things.

**Comment by RubenRBS** [comment]
I've sketched a possible solution in the linked commit, but I don't know if the extra clicks are worth the trouble in the solution I came up with. Any ideas?
