### ISSUE TITLE
[REQUEST] Add support for foonathan/type_safe

### ISSUE THREAD

**Issue by daantimmer** [compiler-explorer/compiler-explorer#2441]
**Describe the solution you'd like**
Add foonathan/type_safe as an optional library

**Describe alternatives you've considered**
joboccara/NamedType provides the same-ish functionality. But by only juding by stars and forks foonathan/type_safe is "used" and supported "twice" as much.
Additionally, foonathan/type_safe does everything that joboccara/NamedType does, but it has additional features that joboccara/NamedType does not provide.

**Additional context**
N/A

**Comment by RubenRBS** [comment]
Hi! Thanks for the request. I've pushed the necesary changes to get the library installed in the site, so it should show up in a couple of days :)
