### ISSUE TITLE
[REQUEST] Build arm gcc trunk

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2444]
Since https://github.com/compiler-explorer/gcc-cross-builder/commit/a6c755d1922bfca04f61a3816093c40d06d544b6 we have a cross build for ARM trunk. We should get it running and installing daily.

**Comment by willlovett-arm** [comment]
Hey @mattgodbolt .  Tamar and I were just discussing this internally.  This ticket _sounds_ like Tamar's given you everything you need for now, and there's work on your side (or one of the other maintainers) to switch it on.  Give us a shout if that isn't true.

Thanks!

W.

**Comment by mattgodbolt** [comment]
Hey @willlovett-arm - yes I think we have everything but the time to have set this up. I"ll look at doing this :)

**Comment by regularnoobie** [comment]
Hey do I need to download the GitHub app or can I just use the website GitHub on my iPhone safari

**Comment by mattgodbolt** [comment]
> Hey do I need to download the GitHub app or can I just use the website GitHub on my iPhone safari

I think you're replying to the wrong place here - this is a specific email address for a particular project on github, unaffiliated with GitHub itself. Please take a look at www.github.com for help.

**Comment by mattgodbolt** [comment]
These are now live! CC @willlovett-arm
