### ISSUE TITLE
msvc x86 or x64 leads to internal compiler error

### ISSUE THREAD

**Issue by lnw** [compiler-explorer/compiler-explorer#2447]
At the moment any trivial program, compiled with msvc x86 or x64 leads to the following error.  That looks like some general windows setup problem.
(The rest works as great as always :))

Internal Compiler Explorer error: Error: spawn C:\data\msvc\14.28.29828-Pre\bin\Hostx64\x64\undname.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Compiler returned: -1

**Comment by mattgodbolt** [comment]
Thanks @lnw - CC @strega-nil

**Comment by mattgodbolt** [comment]
Can you include a specific link @lnw ? I can't repro now but I've definitely had folks ping me on twitter about similar

**Comment by mattgodbolt** [comment]
I have one I think: https://gcc.godbolt.org/z/Tcfjr9

**Comment by lnw** [comment]
Yes, with your link I get the described error, or just with the default example function: https://gcc.godbolt.org/z/7GqWs6 .

**Comment by partouf** [comment]
I mentioned this elsewhere, but the reason for this error is the fact that Latest is broken and Latest's's undname is used (aiming to fix this in PR https://github.com/compiler-explorer/infra/pull/469).

If you uncheck Demangle identifiers, it will still work. (https://gcc.godbolt.org/z/5doTsK)
![image](https://user-images.githubusercontent.com/442630/109177210-d7381800-7787-11eb-8df8-6bcd935df2ce.png)

**Comment by lnw** [comment]
Indeed!  That helps me for the moment!

**Comment by partouf** [comment]
Resolved by fixed latest
