### ISSUE TITLE
Paths with spaces in compiler options

### ISSUE THREAD

**Issue by jovere** [compiler-explorer/compiler-explorer#2451]
I've spent way too long trying to figure this out.  I'm trying to run a custom compiler explorer instance in Windows.  In the compiler options in the `c++.local.properties` files, I need to add a list of include directories.  As I'm running in Windows, spaces in paths are inevitable.  I've tried a dozen different ways to get it to keep the spaces to no avail. (backslashes before spaces, putting everything in quotes, puttin everything in doublequotes, trying escaping with backquotes, a combination of all of these)  Is there any way to get it to not separate the parameters by spaces?

```
compiler.iar8.42.2.options=--enable_restrict -I `"C:/Program Files (x86)/IAR Systems/Embedded Workbench 8.42.2/arm/inc"` -I '"C:/Program Files (x86)/IAR Systems/Embedded Workbench 8.42.2/arm/inc/c"' -I '"C:/Program Files (x86)/IAR Systems/Embedded Workbench 8.42.2/arm/inc/cpp"' --dlib_config '"C:/Program Files (x86)/IAR Systems/Embedded Workbench 8.42.2/arm/inc/c/DLib_Config_Full.h"' --c++ -e --no_exceptions --no_rtti --no_static_destruction --cpu Cortex-M4 --fpu VFPv4_sp --endian little --cpu_mode thumb
```

Everything I'm trying gets me the following, with the quotes getting passed through:
```
Fatal error[Su011]: More than one source file specified:
            Files
            (x86)/IAR
            Systems/Embedded
            Workbench
            8.42.2/arm/inc"`
            Files
            (x86)/IAR
            Systems/Embedded
            Workbench
            8.42.2/arm/inc/c"'
            Files
            (x86)/IAR
            Systems/Embedded
            Workbench
            8.42.2/arm/inc/cpp"'
            Files
            (x86)/IAR
            Systems/Embedded
            Workbench
            8.42.2/arm/inc/c/DLib_Config_Full.h"'
```
What magic incantation am I missing?

Thanks for any help,
Jeremy

**Comment by partouf** [comment]
I think this is a bug.

There are a couple of places we're using the wrong method to split options.
Like this line https://github.com/compiler-explorer/compiler-explorer/blob/53416b91baf1e6a5b6f615bd406a9ba7f7c125e3/lib/base-compiler.js#L407
Should probably use `utils.splitArguments()` instead of using `.split(' ')`

If you could try that out manually and see if that helps (and then surround the paths with double quotes)?

There are a bunch of other places we'll need to do that probably as well

**Comment by jovere** [comment]
Thank you!

Changing that line to the following and then putting double quotes around the paths did indeed fix it.
```js
            options = options.concat(utils.splitArguments(this.compiler.options));
```
```js
compiler.iar8.42.2.options=--enable_restrict -I"C:/Program Files (x86)/IAR Systems/Embedded Workbench 8.42.2/arm/inc" -I"C:/Program Files (x86)/IAR Systems/Embedded Workbench 8.42.2/arm/inc/c" -I"C:/Program Files (x86)/IAR Systems/Embedded Workbench 8.42.2/arm/inc/cpp" --dlib_config "C:/Program Files (x86)/IAR Systems/Embedded Workbench 8.42.2/arm/inc/c/DLib_Config_Full.h" --c++ -e --no_exceptions --no_rtti --no_static_destruction --cpu Cortex-M4 --fpu VFPv4_sp --endian little --cpu_mode thumb
```
I very much appreciate the quick response.
-Jeremy

**Comment by partouf** [comment]
Officially fixed in latest main (commit https://github.com/compiler-explorer/compiler-explorer/commit/56e64c1fafef90b7e279463f2cd2f17dcee901dd)

Thanks again for the report and testing!
