### ISSUE TITLE
[BUG] Tokenizer incorrectly flagging ADD as a label

### ISSUE THREAD

**Issue by jovere** [compiler-explorer/compiler-explorer#2454]
**Describe the bug**
When using the IAR ARM compiler, all the assembly instructions are in CAPS.  The ADD and ADDS instructions are incorrectly flagged as labels rather than an opcode.

**To Reproduce**
View an assembly output file with the opcodes capitalized and have the ADD instruction in the assembly.

**Expected behavior**
ADD and ADDS should be marked as the ADD/ADDS opcode.

**Screenshots**
![image](https://user-images.githubusercontent.com/10420943/109431543-c88e7280-79cc-11eb-880f-8d00c8957ca4.png)

**Additional context**
I've narrowed down the issue to the following line.  The `DD` part of the regex, combined with the leading `[.a-zA-Z0-9_$|]`, is swallowing up the ADD instruction.  I changed the regex to `/^\s*[.a-zA-Z0-9_$|]*\s+(PROC|ENDP|DB|DD)/` (at least one whitespace between the words and the two sections) and it fixes my problem, but I have a feeling it will break other things.  I'm an amateur at best when it comes to regexes, so hopefully somebody else will have a good idea how to fix it.

https://github.com/compiler-explorer/compiler-explorer/blob/066e4ec5c393cda9cf5c0df8cfafdfba5b2eaa54/static/modes/asm-mode.js#L49

**Comment by partouf** [comment]
I think your suggestion makes sense. At least one space should be there and it should not trigger on random bits of text. It should fall down to the opcode regex.
