### ISSUE TITLE
[BUG] Strange disassembly or code generation

### ISSUE THREAD

**Issue by hlewin** [compiler-explorer/compiler-explorer#2456]
This program https://gcc.godbolt.org/z/K1xxj5
seems to produce code that prints the float before the int (at least with -O2).
This does not seem to happen with the "real" compilers, just on the website.

```
struct Test {
   int m_x;
   float m_y;

   template<class Callable>
   void withMembers(Callable&& callable) {
     callable(m_x, m_y);
   }
};


extern void print(int&&i);
extern void print(float&&i);

int main()
{
    Test t{ .m_x=1, .m_y=2.0f};


    t.withMembers([](const auto&... args){
        (  print(args), ...);
    });
    return t.m_x;
}
```

**Comment by partouf** [comment]
I took the liberty of doing a simple implementation for both print functions.
https://gcc.godbolt.org/z/aYn3d4

As you can see the code for main is the same in both cases, and though the right variables are printed in order - the types are interpreted differently.

If you however use "normal types" and not ref-ref - https://gcc.godbolt.org/z/7ha4d6 - it's a very different story.

I don't think the site's to blame here. This is just C++ things, imo.

**Comment by hlewin** [comment]
I am sorry - how can the call to `print(float&&)` come before the int-call?
The compiler does not know the implementation and cannot do fancy things with it. Or can it?
I am unsure - VC++ gives an error compiling the program. I am not proficient enough to be sure
if the conversion done there is valid.
```
main:                                   # @main
        push    rax
        mov     dword ptr [rsp + 4], 1065353216
        lea     rdi, [rsp + 4]
        call    print(float&&)
        mov     dword ptr [rsp], 2
        mov     rdi, rsp
        call    print(int&&)
        mov     eax, 1
        pop     rcx
        ret
```

**Comment by hlewin** [comment]
Yupp - this prints "floatint" even with my local clang

```
#include <tuple>


struct Test {
   int m_x;
   float m_y;

   template<class Callable>
   void withMembers(Callable&& callable) {
     callable(m_x, m_y);
   }
};


#include <iostream>
extern void print(int&&i) {
	printf("int");
}

extern void print(float&&i)  {
	printf("float");
}



int main()
{
    Test t{ .m_x=1, .m_y=2.0f};
    auto f = [](const int& arg) {
        print(arg);
    };


    t.withMembers([](const auto&... args){
        (  print(args), ...);
    });
    return t.m_x;
}
```

**Comment by hlewin** [comment]
I have (re-)opened a report over at bugs.llvm.org
Feel free to close this issue.

**Comment by partouf** [comment]
Note that GCC does the exact same, it's not just Clang.

The problem does not lie in knowing or not knowing the implementation, more in rules about overloading functions with rvalue references.

Stackoverflow will probably better inform you about this. But my advice would be to not use that where it's not needed. Regular types really don't need copying.

If you try it out with templates you can see what the compiler actually wants based on the types https://gcc.godbolt.org/z/o3qnPh

https://en.cppreference.com/w/cpp/language/reference and https://foonathan.net/2018/03/rvalue-references-api-guidelines/ also talk about std::move() being somewhat of a requirement for the && parameter functions to work properly.
