### ISSUE TITLE
#include <C++>: "Cannot open include file"

### ISSUE THREAD

**Issue by HBelusca** [compiler-explorer/compiler-explorer#2461]
As being suggested by the Compiler Explorer interface, I tried to include the C++ file with `#include <C++>`, but the compiler environment failed to find the included file. A suspect colouring is also applied to it.

**To Reproduce**
Adding `#include <C++>` amongst the included files in source code.

**Expected behavior**
No error, the file being found and no particular colouring applied to the code line.

**Screenshots**
![image](https://user-images.githubusercontent.com/1969829/110026107-83ea3a80-7d30-11eb-947b-7c407de91d03.png)

**Comment by mattgodbolt** [comment]
`#include <C++>` is not a standard C++ header. It is an Easter egg relating to https://www.includecpp.org/
