### ISSUE TITLE
[REQUEST] Prioritize libraries with titles matching the search string over those with matching descriptions only

### ISSUE THREAD

**Issue by Pokechu22** [compiler-explorer/compiler-explorer#2467]
**Is your feature request related to a problem? Please describe.**
I use an old laptop with a 1366&times;768 screen.  If I try to add the `{fmt}` library by searching `fmt`, the first thing that's listed is `mp-units` (which mentions `{fmt}` in its description), and I have to scroll down to see `{fmt}`.  This probably isn't an issue with larger screens, but is mildly annoying to me (and initially made me think that `{fmt}` was not available).

**Describe the solution you'd like**
The library search results should first show libraries with titles matching the search string (sorted alphabetically), and then after that any remaining libraries with descriptions matching the search string (sorted alphabetically as well).

**Describe alternatives you've considered**
The `{fmt}` requirement text in `mp-units` could be removed or changed in a way that it's not found in search.  Or `{fmt}` could be special-cased to sort earlier (jank!).

**Comment by partouf** [comment]
This is now live

**Comment by Pokechu22** [comment]
Works good, thanks!
