### ISSUE TITLE
[REQUEST] Ada compiler for ppc64, ppc64le and s390x

### ISSUE THREAD

**Issue by bencz** [compiler-explorer/compiler-explorer#2470]
I would like to be able to analyze the assembly generated by the Ada compiler for the ppc64, ppc64le and s390x architectures
Thanks

**Comment by partouf** [comment]
Could be possible for ppc because we have gcc compilers for those, so we can check if we have those.

Don't know what s390x is.

**Comment by bencz** [comment]
s390x is the mainframe CPU architecture ...
Major Linux distributions support s390x, Ubuntu, Debian, RedHat ....

**Comment by partouf** [comment]
Seems to not been built for any of the PPC GCC compilers.

We would need to add ADA to the configuration of our cross-compiler and recompile everything. And then hope it works.

**Comment by partouf** [comment]
these compilers are now live
