### ISSUE TITLE
[REQUEST] Allow to compile with aliased compilers

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2477]
Currently, aliases need to be resolved to their actual compiler id by the js client.

But we can probably add support for this server-side as well, so raw API calls can be resolved as well.

Maybe there are reasons why we might not want this, but not sure.

**Comment by mattgodbolt** [comment]
I can't think of a reason not to support this: or at the very least serve a redirect.

**Comment by partouf** [comment]
Cool. Redirect also sounds nice actually.
Need to find the exact error that prompted this request from me. It might just also be because this bit of code https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/handlers/compile.js#L187 only takes into account 1 possible alias eventhough in a lot of cases multiple are set.

**Comment by partouf** [comment]
`warn: Unable to find compiler with lang c++ for JSON request {"source":"<removed>","compiler":"icc202119"...`

but also

`warn: Unable to find compiler with lang undefined for request params {"compiler":"icc202119"}` - not sure what this one is.
