### ISSUE TITLE
[REQUEST] Add Binary mode support to MSVC

### ISSUE THREAD

**Issue by edmcman** [compiler-explorer/compiler-explorer#2485]
**Describe the bug**
If I compile a program using Visual Studio and `/GL`, I get: `<No output file>` as a result.

**To Reproduce**
Compile a program with MSVC x86.  Specify `/GL` as the compiler option.

**Expected behavior**
I expected to see assembly code output.

**Link**
https://www.godbolt.org/z/sK6jTe

**Additional context**
I suspect the problem is that `/GL` enables `/LTCG`, link time code generation, which may the format of the object files.  It's unclear if this is a bug report or a feature request.

**Comment by partouf** [comment]
This is related to MSVC not supporting binary mode yet, /GL only works in that mode.
There's execution on in the works on the MS side that we'll have to wait on, but I think we can enable binary mode earlier than that.

I don't think we have an issue to add binary mode to the MSVC instances yet, so I think it's good to have this on the issue list to pick up. But yes, it's more of a feature request ;)

**Comment by timmy-ms** [comment]
This is now present for compilers supported by MS. I noticed this mentions WINE, so if that is still needed please open a new request.

**Comment by edmcman** [comment]
Should this be working on godbolt.org?

**Comment by partouf** [comment]
> Should this be working on godbolt.org?

Yes -> https://www.godbolt.org/z/5cceM67MP

**Comment by edmcman** [comment]
Your link does work for me.  But if I try to compile my original file with a non-wine MSVC compiler I still get the original `<No output file>` message:

https://www.godbolt.org/z/ejheYzq4h

And if I create a new godbolt from scratch in an incognito window, I still get "No output file".  :confused:

**Comment by partouf** [comment]
> Your link does work for me. But if I try to compile my original file with a non-wine MSVC compiler I still get the original `<No output file>` message:
> 
> https://www.godbolt.org/z/ejheYzq4h
> 
> And if I create a new godbolt from scratch in an incognito window, I still get "No output file". confused

`/GL` or `/LTCG` will Not work in normal assembly mode, as it involves link-time optimization, which is only used during actually creating an executable. You Need to use Binary mode.

**Comment by edmcman** [comment]
Ah, thanks!

For future visitors, under the compiler pane, you need to select "Compile to binary" under the settings button.

![image](https://user-images.githubusercontent.com/1017189/172385280-457fc0b5-83b3-460c-a819-f50aff76de5f.png)
