### ISSUE TITLE
Add a "oneshot" donation option

### ISSUE THREAD

**Issue by iboB** [compiler-explorer/compiler-explorer#250]
I only speak for myself here, but I know there are others that feel the same way. 

I'm not a fan of Patreon, and instead of becoming a patron with a small monthly payment (and waste cents every month), I'd much rather donate, say, $50 once (and maybe other times, too if I'm really pleased by something I manage to achieve thanks to a piece of software).

Why don't you open a [Pledgie](https://pledgie.com/) campaign or even a simple paypal donation link?

**Comment by mattgodbolt** [comment]
Thanks for the suggestion, and for the offer of donation: it really is appreciated. I'll take a look at the link you gave and will follow up here.

**Comment by RabsRincon** [comment]
Github now features some sites other than Patreon on the Sponsor wiki. Maybe there is a good place to look at? Or if the current system works, we can close this too

**Comment by mattgodbolt** [comment]
Hi! We now have a paypal link on the "Other" link which goes to https://www.paypal.com/donate/?token=djgAyLY5JtIxM_zFhiKyVY7glmGOzykV1bhX29yqI-mV60rinUcet6pkhIQAO9TUkN4pVG&country.x=US&locale.x=

Hopefully that covers your use case (assuming it's still of interest). Thanks for your thoughts and again for the kind offer. I appreciate in the last 3+ years your position may have changed :)

**Comment by iboB** [comment]
Thanks. A donation was made :)

**Comment by mattgodbolt** [comment]
Many thanks!! @iboB :)
