### ISSUE TITLE
[BUG] Abseil needs linking help now

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2512]
From a few commits back, abseil stopped being a header-only library. We now need to build and link against it to have it work.

e.g. https://godbolt.org/z/5r1884qd6

ends with ...

```
/opt/compiler-explorer/gcc-10.2.0/lib/gcc/x86_64-linux-gnu/10.2.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -labsl_bad_any_cast_impl
/opt/compiler-explorer/gcc-10.2.0/lib/gcc/x86_64-linux-gnu/10.2.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -labsl_failure_signal_handler
/opt/compiler-explorer/gcc-10.2.0/lib/gcc/x86_64-linux-gnu/10.2.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -labsl_examine_stack
/opt/compiler-explorer/gcc-10.2.0/lib/gcc/x86_64-linux-gnu/10.2.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -labsl_flags_parse
/opt/compiler-explorer/gcc-10.2.0/lib/gcc/x86_64-linux-gnu/10.2.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -labsl_flags_usage
...
```

(and many more, the abseil folks seeming have gone to town with separate libraries)

Checking "compile to binary" lets us check out the link flags:
```
-g -o /tmp/compiler-explorer-compiler2021222-5411-vtwuso.80f6e/output.s --gcc-toolchain=/opt/compiler-explorer/gcc-10.2.0 -fcolor-diagnostics -fno-crash-diagnostics -isystem/opt/compiler-explorer/libs/abseil -L. -Wl,-rpath,. -Wl,-rpath,/opt/compiler-explorer/gcc-10.2.0/lib64 -Wl,-rpath,/opt/compiler-explorer/gcc-10.2.0/lib32 -O2 -std=c++17 -stdlib=libc++ -fno-exceptions /tmp/compiler-explorer-compiler2021222-5411-vtwuso.80f6e/example.cpp -labsl_bad_any_cast_impl -labsl_failure_signal_handler -labsl_examine_stack -labsl_flags_parse -labsl_flags_usage -labsl_flags_usage_internal -labsl_flags -labsl_flags_internal -labsl_flags_marshalling -labsl_flags_reflection -labsl_flags_private_handle_accessor -labsl_flags_commandlineflag -labsl_flags_commandlineflag_internal -labsl_flags_config -labsl_flags_program_name -labsl_leak_check_disable -labsl_leak_check -labsl_hash -labsl_city -labsl_periodic_sampler -labsl_random_internal_distribution_test_util -labsl_random_distributions -labsl_random_seed_sequences -labsl_random_internal_pool_urbg -labsl_random_internal_randen -labsl_random_internal_randen_hwaes -labsl_random_internal_randen_hwaes_impl -labsl_random_internal_randen_slow -labsl_random_internal_platform -labsl_random_internal_seed_material -labsl_random_seed_gen_exception -labsl_raw_hash_set -labsl_hashtablez_sampler -labsl_exponential_biased -labsl_scoped_set_env -labsl_statusor -labsl_status -labsl_cord -labsl_bad_optional_access -labsl_strerror -labsl_str_format_internal -labsl_synchronization -labsl_graphcycles_internal -labsl_stacktrace -labsl_symbolize -labsl_debugging_internal -labsl_demangle_internal -labsl_malloc_internal -labsl_time -labsl_civil_time -labsl_strings -labsl_strings_internal -lrt -labsl_base -labsl_spinlock_wait -labsl_int128 -labsl_throw_delegate -labsl_time_zone -labsl_bad_variant_access -labsl_raw_logging_internal -labsl_log_severity
```

so our systems have definitely picked up the libraries within abseil, but they don't seem to be being found.

**Comment by partouf** [comment]
hmm, this should be the package for Clang 11 + libc++ https://conan.compiler-explorer.com/v1/files/abseil/trunk/abseil/trunk/0/package/17d20f59bb889b9cbdfc3ee62682d51d2ec55d07/0/conanmanifest.txt?signature=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNvdXJjZV9wYXRoIjoiYWJzZWlsL3RydW5rL2Fic2VpbC90cnVuay8wL3BhY2thZ2UvMTdkMjBmNTliYjg4OWI5Y2JkZmMzZWU2MjY4MmQ1MWQyZWM1NWQwNy8wL2NvbmFubWFuaWZlc3QudHh0IiwidXNlcm5hbWUiOm51bGwsImZpbGVzaXplIjpudWxsLCJleHAiOjE2MTY0MjE1ODF9.WmklvtP3LyLluqeHz__W6s1fUKcDE-o1bnFB5kksXEQ

Which seems to include all these libraries..

Not sure what's going on

**Comment by mattgodbolt** [comment]
I'll take a look tonight. I'm _well_ overdue looking at this side of the codebase, always deferring to you...and I don't want you to feel pressured upon to take all the library issues!

**Comment by partouf** [comment]
CE says: info: No build found for abseil/trunk matching `{"os":"Linux","build_type":"Debug","compiler":"clang","compiler.version":"clang1100","compiler.libcxx":"libc++","arch":"","stdver":"","flagcollection":""}`

Not sure what's up with that, pretty sure it's there.. OH... arch should be x86_64 !
Seems I broke something a couple of commits ago

**Comment by partouf** [comment]
I broke something here probably https://github.com/compiler-explorer/compiler-explorer/commit/273017c431e04d81648fed240e683f11a705eb63

**Comment by partouf** [comment]
Seems to only affect Clang compilers

**Comment by partouf** [comment]
Did I even test this, ugh 
```
            let targetIdx = this.compilerOptionsArr.indexOf('-target');
            if (targetIdx !== false) {
```
indexOf returns -1 when the thing can't be found

**Comment by mattgodbolt** [comment]
I blame the reviewer for not spotting that :grinning:

**Comment by partouf** [comment]
Fixed in f227c75f5bc58a6b641b33e6203e009e78dbe703

**Comment by partouf** [comment]
Fix is now live

**Comment by denchat** [comment]
I don't know whether I should instead open a brand new issue, 
however it seems StrCat simply can't take more than 4 parameters on `clang` only.

Moreover, `clang` using `libstdc++` just throws `badalloc` even with 4 parameters.

[[LIVE](https://godbolt.org/z/M3xEbfj6c)]
```
  std::cout  // 4 parameters are okey.
             // << absl::StrCat("Hello, ", argv[0], argv[0], "\n")
             
             // 5 parameters and more:
             // undefined reference to `absl::strings_internal::CatPieces(std::initializer_list<std::__1::basic_string_view<char, std::__1::char_traits<char> > >)'
              << absl::StrCat("Hello, ", argv[0], argv[0], argv[0], "\n")
             ;
```

**Comment by yaojingguo** [comment]
It is a problem with linking. 

X86-64 clang (trunk) reports:
```
ASM generation compiler returned: 0
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/12.0.1/../../../../x86_64-linux-gnu/bin/ld: cannot find -labsl_leak_check_disable
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
Execution build compiler returned: 1
```

X86-64 GCC 11.1 reports:
```
ASM generation compiler returned: 0
/opt/compiler-explorer/gcc-11.1.0/bin/../lib/gcc/x86_64-linux-gnu/11.1.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -labsl_leak_check_disable
collect2: error: ld returned 1 exit status
Execution build compiler returned: 1
```

And I created https://godbolt.org/z/rohcd1dq7. X86-64 GCC 11.2 also reports:

```
ASM generation compiler returned: 0
/opt/compiler-explorer/gcc-11.2.0/bin/../lib/gcc/x86_64-linux-gnu/11.2.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -labsl_leak_check_disable
collect2: error: ld returned 1 exit status
Execution build compiler returned: 1
```
So it seems that `absl_leak_check_disable` is missing during linking.

**Comment by BMBurstein** [comment]
Hi @yaojingguo . Did you figure out how to get it to work? I have the same issue https://godbolt.org/z/556dh1a4G

**Comment by partouf** [comment]
@BMBurstein a binary was recently removed from abseil, this requires a change to CE
