### ISSUE TITLE
[BUG] Status output from compiler still shows linking error when no linking requested

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#2517]
**Describe the bug**
I'm simply looking at the compilation, not interested by any object.
Compile to binary is correctly not selected.

Status reports 0 error/warning, as expected.
But opening the status window shows:
```
ASM generation compiler returned: 0
/lib/x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x24): undefined reference to `main'
/tmp/ccTjbAyI.o: In function `bar':
/home/ce/<source>:9: undefined reference to `foo'
collect2: error: ld returned 1 exit status
Execution build compiler returned: 1
```
Not sure why linker is still executed but having these errors can be misleading...

**Link**

https://godbolt.org/z/osEPebPf4

**Screenshots**

![Screenshot_2021-03-25 Compiler Explorer](https://user-images.githubusercontent.com/87603/112475938-a7be0080-8d71-11eb-84bc-5a6826df83f4.png)

**Comment by partouf** [comment]
![image](https://user-images.githubusercontent.com/442630/112476557-4fd3c980-8d72-11eb-92b5-c83a334eb036.png)

Running requires linking ;)

**Comment by dkm** [comment]
Seems reasonable :), sorry for the noise !
