### ISSUE TITLE
[LIB REQUEST] **zig-args**

### ISSUE THREAD

**Issue by InfRandomness** [compiler-explorer/compiler-explorer#2525]
**Library name:**
zig-args

**Library description:**
Simple-to-use argument parser with struct-based config

**Library repository:**
https://github.com/MasterQ32/zig-args

**Motivation:**
Being able to compile and test that depends on it and having the ability to use this with "Execution Only"/"Execution Arguments" features of godbolt

**Comment by RubenRBS** [comment]
Hi! Thanks for taking the time to suggest the library.

This is actually the first one we get for Zig, so we'll have to look into how to best implement it :)

**Comment by partouf** [comment]
If there's any hint someone can give us on how to install and use the library in a regular situation, that might help us facilitate this for CE.

**Comment by InfRandomness** [comment]
Assuming you guys have a sort of build.zig in the background that you invoke Zig to build with, you would have to end up modifying that build.zig file like so : https://github.com/InfRandomness/zcoreutils/blob/master/build.zig#L38
(https://github.com/ziglang/zig/blob/master/lib/std/build.zig#L2182-L2187)
The first argument being the one that the user will be able to import, and the second being the path to the library's source file;
For zig-args, it is https://github.com/MasterQ32/zig-args/blob/master/args.zig.

**Comment by partouf** [comment]
> Assuming you guys have a sort of build.zig in the background that you invoke Zig to build with, you would have to end up modifying that build.zig file like so : https://github.com/InfRandomness/zcoreutils/blob/master/build.zig#L38
> (https://github.com/ziglang/zig/blob/master/lib/std/build.zig#L2182-L2187)
> The first argument being the one that the user will be able to import, and the second being the path to the library's source file;
> For zig-args, it is https://github.com/MasterQ32/zig-args/blob/master/args.zig.

We use the zig executable and use the `build-obj` or `build-exe` parameter.
For example `zig build-obj --cache-dir /tmp/compiler-explorer-compiler2021517-5040-4uh2ep.m78pw --name output -fno-emit-bin -femit-asm=output.s /tmp/compiler-explorer-compiler2021517-5040-4uh2ep.m78pw/example.zig`

We have no possibility to change the source code in this.

**Comment by InfRandomness** [comment]
Sorry, I have no idea how if it is possible to tell Zig to use other files while using build-exe.

**Comment by InfRandomness** [comment]
So, I have explored things a bit and thought it would probably work to build the library's zig file using zig build-lib (like : `zig build-lib file.zig`), this would give a .a file that we could then link against when building the binary itself (like : `zig build-exe -l:file.a zig/file/with/main/function.zig)

Problem with this approach : we cannot use the regular zig's @import statement, or at least, here it did not work.

**Comment by marler8997** [comment]
Adding support for libraries like this should be as simple as adding `--pkg-begin NAME SRC --pkg-end` to your compiler command-line, i.e.

```
zig build-exe ...  --pkg-begin args path-to-zig-args-repo/args.zig --pkg-end ...
```

This would make the library available through the `"args"` package, i.e.

```zig
const args = @import("args");
```

Also note that you don't have to add more source files.  Every Zig package is exposed through a single package file that can subsequently import any files from it's children directories that it needs.

**Comment by RubenRBS** [comment]
For 0.7.1, 
`zig build-obj --cache-dir /tmp/compiler-explorer-compiler2021524-16697-1tk60w0.aq33k --name output -fno-emit-bin -femit-asm=output.s --pkg-begin args /opt/compiler-explorer/libs/zig/zig-args/args.zig --pkg-end /tmp/compiler-explorer-compiler2021524-16697-1tk60w0.aq33k/example.zig`
gives `error: unrecognized parameter: '--pkg-begin args /opt/compiler-explorer/libs/zig/zig-args/args.zig --pkg-end'`,

and 0.6.0, with `build-obj --cache-dir /tmp/compiler-explorer-compiler2021524-16697-2wn2i.qbnq0q --output-dir /tmp/compiler-explorer-compiler2021524-16697-2wn2i.qbnq0q --name output --emit asm -mllvm --x86-asm-syntax=intel --pkg-begin args /opt/compiler-explorer/libs/zig/zig-args/args.zig --pkg-end /tmp/compiler-explorer-compiler2021524-16697-2wn2i.qbnq0q/example.zig`
gives ```Invalid argument: --pkg-begin args /opt/compiler-explorer/libs/zig/zig-args/args.zig --pkg-end
See /opt/compiler-explorer/zig-0.6.0/zig --help for detailed usage information```, so there must be something I'm doing wrong :(

**Comment by InfRandomness** [comment]
The pkg-begin and pkg-end might've been added in later versions, there was a good amount of changes in the CLI args for zig 0.9.0 (iirc), try to do that with Zig trunk

**Comment by RubenRBS** [comment]
Seems like that's not it either. Just tested with the latest available verison (`0.9.0-dev.256+0134cb02`) and I get the same as in 0.7.1. Maybe it has been removed? 0.6.0 seems to at least know that `--pkg-begin` exists

**Comment by marler8997** [comment]
I believe the problem is that you have put the `--pkg-begin ... --pkg-end` arguments inside some sort of quotes causing all of it to get passed as a single argument.

I don't see quote in the command you pasted but that's what I gathered from the error message.  My guess is you printed the command arguments unquoted so we can't see where spaced arguments are delimited.

**Comment by RubenRBS** [comment]
I did, indeed, break the library code when adding this. Thanks for the clue that made me realize where I broke it!

**Comment by partouf** [comment]
This has been live for a bit, but just double-checked if it's working, it is https://godbolt.org/z/sWshG1KM7
