### ISSUE TITLE
[BUG] "Adding a new library" docs point to non-existent wiki page

### ISSUE THREAD

**Issue by claremacrae** [compiler-explorer/compiler-explorer#2532]
**Describe the bug**

In the latest revision - b5d340abb80d7315495eaf710afe38bccf8f32c4  - the "[Putting it all together](https://github.com/compiler-explorer/compiler-explorer/blob/b5d340abb80d7315495eaf710afe38bccf8f32c4/docs/AddingALibrary.md#putting-it-all-together)" section of "Adding a new library" - says to "update the wiki" - linking to this URL:

https://github.com/compiler-explorer/compiler-explorer/wiki/Installed-libraries

Opening that URL gives "Create new page", suggesting that this wiki page does not exist.

**Comment by partouf** [comment]
Since the new Library widget, the wiki has gone obsolete, I think. So that reference could just be removed.

**Comment by partouf** [comment]
Absolutely! (Also no need to ask for permission!)

If you have any questions, please ask away in our discord or here.

**Comment by okkenator** [comment]
Ok, thanks and I'm glad to help out.  I guess I will just remove the sentence about the wiki and create a PR.

**Comment by okkenator** [comment]
Ok I created the PR but I am unsure if/how you would associate it to this bug.

**Comment by partouf** [comment]
Just by writing something like `Fixes #2532` in the comments of the PR just as you did here
