### ISSUE TITLE
[LIB REQUEST] **JsonCpp**

### ISSUE THREAD

**Issue by jmarrec** [compiler-explorer/compiler-explorer#2534]
**Library name:** 

JsonCpp

**Library description:**

JsonCpp is a C++ library that allows manipulating JSON values, including serialization and deserialization to and from strings. It can also preserve existing comment in unserialization/serialization steps, making it a convenient format to store user input files.

**Library repository:**

https://github.com/open-source-parsers/jsoncpp

**Library homepage:**

**Motivation:**

I have it as a dependency in a couple of projects (via `conan`, it is part of conan-center-index, cf https://github.com/conan-io/conan-center-index/tree/master/recipes/jsoncpp/all), and it's always a hassle to remember how it works internally (same as the similar nlohman json which is already supported) so I would find it useful to have it on compiler explorer

**Note**: I am already reading the wiki and trying to add it myself. I hope you do consider it for inclusion, but if not it won't be lost on me since I am genuinely curious about the inner workings of CE!

**Comment by partouf** [comment]
Hi, this library looks to require building. So it gets a little more complicated.

The long explanation is in this document https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/AddingALibrary.md

The TLDR:
1. You probably want to send us a PR @ https://github.com/compiler-explorer/infra with something that looks like https://github.com/compiler-explorer/infra/blob/main/bin/yaml/libraries.yaml#L55
2. Then we can give it a go with a test build to see if it passes and if we discover any issues
3. Then a PR to this repo, with something similar to this https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/c%2B%2B.amazon.properties#L1384
4. Then we let it build for all compilers at night
5. After that we can put it live

**Comment by jmarrec** [comment]
@partouf the PR is here: https://github.com/compiler-explorer/infra/pull/481. I'm trying to test changes locally but having trouble with `ce_install` (first time contributor here, so that's expected). I'll keep hacking at it.

**Comment by partouf** [comment]
> @partouf the PR is here: [compiler-explorer/infra#481](https://github.com/compiler-explorer/infra/pull/481). I'm trying to test changes locally but having trouble with `ce_install` (first time contributor here, so that's expected). I'll keep hacking at it.

Thanks! Will test it out

**Comment by jmarrec** [comment]
I prepared #2535 with changes on this side (assuming the infra side goes well...)

**Comment by claremacrae** [comment]
Does it matter that `libs.jsoncpp.versions.194.path=/opt/compiler-explorer/libs/jsoncpp/include` Does not have a version number in the path?

It will be something to look out for when new versions are, anyway.

**Comment by partouf** [comment]
> Does it matter that `libs.jsoncpp.versions.194.path=/opt/compiler-explorer/libs/jsoncpp/include` Does not have a version number in the path?
> 
> It will be something to look out for when new versions are, anyway.

Ha, yes, just fixed it before merging, good spot :)

**Comment by jmarrec** [comment]
Oops sorry about this, and good catch both!

**Comment by jmarrec** [comment]
@partouf did I mess this up?

https://github.com/compiler-explorer/compiler-explorer/blob/7cf9bc9dd1ffd499beb23144758714f8ff71962a/etc/config/c%2B%2B.amazon.properties#L1157

the lib built is `libjsoncpp.a` on ubuntu. Should it be `jsoncpp` instead?

**Comment by partouf** [comment]
Ah yes, it should, thanks!

**Comment by jmarrec** [comment]
Let me know if I can do something to help later today.

**Comment by partouf** [comment]
Builds have completed. If you see any issues with it live, let us know!
https://godbolt.org/z/cEWdEKeGP

**Comment by jmarrec** [comment]
Works perfectly thanks @partouf! I will try to add a relevant example too.
