### ISSUE TITLE
[REQUEST] Add documentation for debugging with VSCode on Native Windows

### ISSUE THREAD

**Issue by okkenator** [compiler-explorer/compiler-explorer#2553]
**Is your feature request related to a problem? Please describe.**

Documentation for debugging on windows does not exist.

**Describe the solution you'd like**

There is a way to run with VSCode as a debugger in order to stop on breakpoints, step over, inspect variables, view callstack.

**Comment by okkenator** [comment]
I have a few changes started.

**Comment by partouf** [comment]
Would definitely like to see this.
I know it's possible because I've used it before, but the knowledge has gone lost for me.

Wouldn't mind a `launch.json` example either.

**Comment by okkenator** [comment]
I will try to get time tonight.  At work rn.

**Comment by okkenator** [comment]
Oh boy, Windows VM is not behaving so I won't finish tonight.
