### ISSUE TITLE
[BUG] fields in /api/compilers does not work

### ISSUE THREAD

**Issue by olafurw** [compiler-explorer/compiler-explorer#2558]
**Describe the bug**
According to the API documentation, there is a fields value you can use in /api/compilers, but trying it out results in just as if you didn't use it at all

**Link**
https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/API.md
https://compiler-explorer.com/api/compilers?fields=all
https://compiler-explorer.com/api/compilers?fields=lang
https://compiler-explorer.com/api/compilers?fields=lang,semver

**Comment by partouf** [comment]
fields only work with json requests

**Comment by olafurw** [comment]
Thanks.
