### ISSUE TITLE
[BUG] // setup folding is not working

### ISSUE THREAD

**Issue by RubenRBS** [compiler-explorer/compiler-explorer#2561]
**Describe the bug**

The `// setup` magic introduced to hide some initial code is currently not working (And was dumping error messages to the console)
The offending code is:
https://github.com/compiler-explorer/compiler-explorer/blob/e7be9f59db58e1f0ddc7480316ff269873ac37f2/static/panes/editor.js#L111-L116

The problem is two-fold. 
- The `.clearSelection()` function seems not to be available anymore so we were loggin errors to the console (Commented now while we fix it)
- Folding is not performed even when commenting out that line

**To Reproduce**

Create some code with `// setup` as the first line & reload the page

**Expected behavior**

No error dump in the console (Mitigated by the linked commit) and for the folding to happen

**Link**

https://godbolt.org/z/j7x5js1ro

**Comment by mattgodbolt** [comment]
Oh blast, good spot, thanks!

**Comment by partouf** [comment]
So.. maybe there was some misunderstanding, but setup only works if you indent the lines after that https://godbolt.org/z/Kvfzv86Px - so... I think it does work, but the bugfix did probably help.
