### ISSUE TITLE
[REQUEST] `rustfmt` for Rust

### ISSUE THREAD

**Issue by ojeda** [compiler-explorer/compiler-explorer#2564]
`rustfmt` (https://github.com/rust-lang/rustfmt) is de facto tool for formatting Rust code according to style guidelines.

The Rust playground has support for it under "Tools", and similarly Compiler Explorer supports it under the "Format document" operation.

However, it is also useful to run the tool under different versions and options (typically set in a `rustfmt` file, but can also be toggled via flags with `--config`).

This would open up new use cases, such as checking out the different options and their behavior on sample code, testing the output under different versions for e.g. bug reports, etc.

In the end, it is one more tool that takes code and outputs code, and it is useful to see the behavior under flags, different inputs, diff outputs, etc.

**Comment by supergrecko** [comment]
Rustfmt may be triggered and ran over the code in the editor with the "Format document" action, is this sufficient?

**Comment by ojeda** [comment]
That covers the usual use case, yeah.

Here I was thinking about passing flags/config file so that one could test the output, report regressions on the tool, etc., like for compilers. I have added some details to OP.

**Comment by ojeda** [comment]
Actually, let me open another issue instead, so that it is more clear.

**Comment by ojeda** [comment]
Done, and that way it is an actual compiler request with the new GitHub templates: https://github.com/compiler-explorer/compiler-explorer/issues/4553 :)
