### ISSUE TITLE
[REQUEST] LLVM IR output for Rust

### ISSUE THREAD

**Issue by ojeda** [compiler-explorer/compiler-explorer#2565]
Similar to Clang's "AST output" and "IR output", it would be nice to have "LLVM IR output" for Rust via `--emit=llvm-ir`.

The Rust playground has support for it under the main button.

**Comment by ojeda** [comment]
This is what the "IR output" in CE does now, so the request here would be just to rename it to LLVM IR to distinguish it from HIR and MIR.

**Comment by supergrecko** [comment]
The pane was renamed to "LLVM IR Output" in https://github.com/compiler-explorer/compiler-explorer/pull/2795#discussion_r673398158
