### ISSUE TITLE
[REQUEST] HIR output for Rust

### ISSUE THREAD

**Issue by ojeda** [compiler-explorer/compiler-explorer#2567]
Similar to Clang's "AST output" and "IR output", it would be nice to have "HIR output" for Rust via `-Zunpretty=hir`.

The Rust playground has support for it under the main button.

**Comment by dkm** [comment]
I think I'll have a look at this !

**Comment by dkm** [comment]
As getting the HIR is only supported using nightly compiler, this will be only enabled on nightly :)

**Comment by ojeda** [comment]
You may use `RUSTC_BOOTSTRAP=1` to get it in all of them (please see https://github.com/compiler-explorer/compiler-explorer/issues/2724 as well).

**Comment by dkm** [comment]
I was strongly advised against it by `rustc` devs on Zulip...

**Comment by ojeda** [comment]
Why? CE is a tool to explore compilers; being able to explore the different outputs of a compiler (and, in general, use all its options, even unstable ones) is its core purpose.

What makes sense to request is that CE does not enable it by default. That is fine, because the compiler doesn't either -- being consistent is good here. This is why I requested the toggle in the other PR.

If you wish, feel free to @ me in their Zulip.

**Comment by supergrecko** [comment]
> You may use `RUSTC_BOOTSTRAP=1` to get it in all of them (please see #2724 as well).

Would the same apply for macro expansion? The rust macro expansion view is only available for nightly on CE right now.

**Comment by ojeda** [comment]
Definitely, it is useful to be able to perform macro expansions in all versions. I didn't notice it was only there for nightly...

**Comment by dkm** [comment]
As mentioned on rust's zulip, I'll first enable this on the nightly compiler only. If needed on other versions, I can also add the needed code to use the `RUSTC_BOOTSTRAP` trick. I would personally find it better on all versions, but as I can't see a real consensus on this, I won't take any initiative...
