### ISSUE TITLE
Improve compiler selection UI?

### ISSUE THREAD

**Issue by paulsapps** [compiler-explorer/compiler-explorer#257]
The list of compilers is ever growing, sometimes finding the right one is annoying from a huge list.

Would it be possible to change the UI to have some filters for 32/64bit/arch or something? Or just pick say GCC and then it shows all the GCC versions/arches/bitnesses?

**Comment by mattgodbolt** [comment]
It's not obvious at all but you can hit backspace and then type filters
into the drop down box. I think something better is still needed though;
hanks for the report.

**Comment by mattgodbolt** [comment]
Ideas:
* Find a hierarchical dropdown widget
* Have separate dropdowns, architecture, compiler, version (might be annoying?)
* Make it more obvious that you can type and filter by name

**Comment by roalz** [comment]
My first choice would be "make it more obvious that you can type and filter by name", but it's hard to find how, mostly because you get a pre-selected choice, and click+backspace+edit is far from being intuitive.

Failing that, my second choice would be to have separate dropdowns.
It would be great to have a "beta" site with separate dropdowns of architecture, compiler and version,
may be publicly testable and give you A/B test feedbacks.
I may prefer them separate (usually using just 1 or 2 architectures, but different compiler versions), but it would be great to take a test drive (if easy, quick and intuitive enough, it may become my first choice) :-)

**Comment by Leandros** [comment]
> Have separate dropdowns, architecture, compiler, version (might be annoying?)

I vote for this. While I often switch between compilers, I rarely chose any version except the latest on x86_64, separating the dropdowns could default to the latest version and reduce the most commonly used dropdown to just a few items without scrolling.

**Comment by mattgodbolt** [comment]
Thanks both. I'm going to sketch out something like this: either three dropdowns (arch, compiler, version) or two (arch, compiler & version) with better filtering. My own use case is to switch between compiler and versions often, so I'm leaning towards the latter.

**Comment by mattgodbolt** [comment]
And for metrics: https://docs.google.com/spreadsheets/d/1uK8jcsaF8h80-FZOoNURwGi6USHsWrdsdHKBPZGq7jQ/edit?usp=sharing  - it's very top-weighted to the default compiler and the highest. Just don't forget metrics don't capture things like me toggling between two compiler/versions :)

thanks!

**Comment by mattgodbolt** [comment]
@roalz There's already a beta site, and the dropdown will be previewed there first, don't worry (add /beta/ to the path e.g. https://gcc.godbolt.org/beta/)

**Comment by roalz** [comment]
@mattgodbolt I know about the beta site (following you on twitter ;-) ), looking forward to try the separate dropdown. And I agree, it may be enough to split architecture and keep together compiler and version.

**Comment by mattgodbolt** [comment]
Cool :) just making sure! Thanks again!

**Comment by tmccrmck** [comment]
I rarely switch between compilers as I'm only interested in one. Having a dropdown for compilers would be perfect for my use case.

**Comment by mattgodbolt** [comment]
An argument for having compiler separate from version: https://twitter.com/fourbadcats/status/844235399677526016  - typing `cl` for CL compiler filters all the clangs too...

**Comment by mattgodbolt** [comment]
I'm sketching ideas a lot on this one. I'm going to take this out of the "New UI" milestone; it's important to improve this but it's not really part of the Monaco editor/diff view release

**Comment by mattgodbolt** [comment]
More thoughts from @adishavit  :

* Rename `GCC (snapshot)` to `(trunk)`
* Sort from newest to oldest always
* Sort order changes e.g. once you start typing. EG empty dropdown puts clang trunk first; but typing `clang` puts clang trunk last

**Comment by adishavit** [comment]
Interesting [reference](https://ux.stackexchange.com/questions/tagged/dropdown):

**Comment by mattgodbolt** [comment]
Thanks. Matt_d on slack also mentioned having a modal popup. This also might dovetail into my hope to unify all the languages to one end-point (#277) where the popup can handle language selection too.

**Comment by mattgodbolt** [comment]
Also mentioned by https://twitter.com/twoscomplement/status/944054181656084480

**Comment by mattgodbolt** [comment]
Sorry for lack of progress here. I've not found anything I like so far. We don't have much metadata about each compiler, so probably need to augment the information we have.

**Comment by mattgodbolt** [comment]
Doug Swallow has mocked up this: https://bootsnipp.com/snippets/6XZrK?h=ATNfFOruR-gTaNNfzgEsxFrFKjmEJUolHAz667gCRIFK5h0IiEh4sa6_aIHsPcwhVecZ8AflMABRtiCWeinYwRgbZO6NiPgu&s=1

It doesn't have the "typeable" search that I personally like, but I wonder if I'm in the minority here. Thoughts anyone?

**Comment by Leandros** [comment]
I like it! Although, I'd like to keep the recent ones in the same level of the dropdown, since they're really common to be re-selected.

**Comment by jaredwy** [comment]
I’d miss search :(

**Comment by paulsapps** [comment]
Could some delay be added to hiding the menu? For instance you hover over clang, get to a version then accidentally move the mouse a little too far and then its gone and have you have to start over. Maybe like a 800msec delay before it hides to avoid that kind of thing could be nice.

**Comment by adishavit** [comment]
I like the mockup - especially that it supports recent compilers.

**Comment by RabsRincon** [comment]
Hi! Just dropping in here to let you know that, even if it's not as in-depth as we would like, semver ordering for most compilers will be implemented in the next release, which should happen "soon"
We're still looking into improving the experience, but while we wait, this might help mitigate the problems a little bit

**Comment by mattgodbolt** [comment]
It has been suggested over email that making the dropdown box a bit taller might help a little too. Also Wandbox was suggested as a place to look for ideas.

**Comment by valiko-ua** [comment]
I like compilers grouping mocked up by Doug Swallow back in 2018.

I didn't know that I can hit Backspace and start typing to filter compiler list until I found this ticket.
Several thoughts on this:
1. Show tooltip with this information when hovering over the compiler drop-down list (as it is done for options in the "toolbar" below it).
2. When user clicks in this field, cursor is blinking but left-right keys do not move it. So user thinks it's not editable. If it was allowed to move cursor left-right inside this field and select text (Shift+Left) then it would be a hint that it's editable, so user may try to press Backspace or Delete and discover this nice feature.
3. If user does not confirm new compiler selection by pressing Enter (e.g. presses Escape or moves focus away from this field) then restore old compiler title in this field. Currently it remains empty.

Maybe file new ticket with these "thoughts"?

**Comment by mattgodbolt** [comment]
@valiko-ua thanks for taking the time to reply here. We are a little limited by our use of a third-party widget to do most of the work for us. We use https://selectize.github.io/selectize.js/ to provide the drop-down and selection widget and that limits our ability to make too many changes (e.g. part 2). I like the idea of tooltips, but I don't think that will help that much as folks don't seem to read them for the other parts of the UI (I have to explain what the buttons do all the time even though they have tooltips).

**Comment by partouf** [comment]
A little while ago the compiler selection was massively improved by @jeremy-rifkin in https://github.com/compiler-explorer/compiler-explorer/pull/4849 by adding a new screen to select by category and instructionset/architecture

That should satisfy this ancient issue
