### ISSUE TITLE
[REQUEST] Code collapse/expand all/current scope

### ISSUE THREAD

**Issue by GuillaumeDua** [compiler-explorer/compiler-explorer#2578]
**Describe the solution you'd like**  
A shortcut or context-menu entry to collapse/expand all or current scope(s)

**Additional context**  
Such feature might makes godbolt example easier to use during trainings, talks/conferences/keynotes, etc.

**Comment by partouf** [comment]
If you press F1 in the editor and type in Fold, you can see all the related shortcuts for this.

**Comment by GuillaumeDua** [comment]
@partouf Nice one, did not notice, as I typed _"collapse"_
