### ISSUE TITLE
[REQUEST] Rainbow in the Dark (Add more colour schemes to linked code for dark theme)

### ISSUE THREAD

**Issue by Shadlock0133** [compiler-explorer/compiler-explorer#2585]
Currently, with dark theme only available colour scheme is grey shades, while light mode offers multiple colour schemes. With only greys, it can be hard to tell difference between shades.

It might be good idea to add (more) colour schemes to dark mode. Even just copying schemes from light mode would be a good start, although they might need a bit of tweaking to avoid heavy contrast with background.

**Comment by RubenRBS** [comment]
I've been trying for a bit now, and I can't come up with a scheme that looks like it would work, even with a friend's help, so I'll describe the process to create a new scheme for any brave souls out there who want to try.

Schemes live in two places. `static/colour.js` has `schemes` array that holds information about every scheme usable. Adding one is as easy as adding a new object with an id (The `name`) and a `description` that will show up in the settings pane, along with some other necessary info. My recomendation is to call it something like `{name: 'rainbow-dark', desc: 'Rainbow Dark', count: 4, themes: ['dark']}`

The `count` key specifies how many different colours the scheme has (We need a minimum of 4 different ones, but feel free to add more if you're able to!), and the `themes` one lets the scheme know for which themes it's valid. As we want a new one for the dark theme, the example has `['dark']` as the value (And you would do something like `['default', 'dark']` if you wanted to add it for both currently supported themes)

Now, in `static/colours.scss`, the classes used for each colour are defined. They are named like `.<scheme id>-<0 to count - 1>`, and affect every line that needs to have said colour (Take a look at `.rainbow-0` etc... for some examples), so new classes would need to be defined (As in `.rainbow-dark-0` thru `.rainbow-dark-3` for the example above where `count` = 4)

To test it, follow the steps in https://github.com/compiler-explorer/compiler-explorer#developing if you haven't, to be able to run the site locally. I recommend running the site with `make dev` to shorten the wait times and enable automatic recompilation of static files after they change. Then, once the site is up, go to More > Settings, set the theme to Dark, and change the colour scheme at the bottom of the pane to "Rainbow Dark" in the case of the example above (As the `description` key is the one used in the select label). As of writing this #2590 is not yet resolved you will need to reset the colour scheme on every page reload for now.

My recommenation is also that you get some sample code to test different scenarios for the different combinations of adjacency/line contents. Feel free to ask for some if you're not able to find any suitable :)

**Comment by partouf** [comment]
Someone recently implemented a rainbow-dark theme https://github.com/compiler-explorer/compiler-explorer/pull/2811
