### ISSUE TITLE
[REQUEST] Allow custom clang-format styles

### ISSUE THREAD

**Issue by AbrilRBS** [compiler-explorer/compiler-explorer#2587]
**Is your feature request related to a problem? Please describe.**

The current clang-format support for code is a bit ad-hoc, but on Discord, we got a request to allow for custom styles to be a possibility. Afaik, we used to support something like this.

They submited a sketch that looks like this:
![imagen](https://user-images.githubusercontent.com/5364255/114163300-4ded3700-992a-11eb-8cf1-3e2593d1324a.png)

**Comment by peterschussheim** [comment]
This would be a great feature, has there been any progress on this?  I would be happy to submit a patch.

**Comment by GPMueller** [comment]
Since we can now do CMake projects with multiple sources inside compiler-explorer, it would be great if clang-format could use the `.clang-format` file, like it does normally.

**Comment by vittorioromeo** [comment]
Would love to see this... any interest @mattgodbolt? :)

**Comment by robert-andrzejuk** [comment]
Would be great if I could set a url for my custom .clang-format file, and it would download and use it.

**Comment by OfekShilon** [comment]
I believe this is done, right @AbrilRBS ?
![image](https://github.com/user-attachments/assets/a59f12f3-0e0f-4359-846e-a1a8f4d96149)

**Comment by AbrilRBS** [comment]
Quite right it is, thanks a lot for the issue cleanup! :)
