### ISSUE TITLE
[BUG] Colour scheme setting not being saved

### ISSUE THREAD

**Issue by RubenRBS** [compiler-explorer/compiler-explorer#2590]
**Describe the bug**

Changing the color scheme is not currently persisted in the settings

**To Reproduce**

More > Settings. Navigate to the bottom, and change the Colour scheme to something other than the default. Reload the page. The scheme goes back to the default one.
The setting seems to be saved properly, but on page reload, a uiChange event is triggered and the setting seems to get overriden.

**Expected behavior**

Colour scheme setting is properly persisted across sessions.

**Link**

**Screenshots**

**Desktop**

 - OS:  Windows & Ubuntu
 - Browser  Firefox
 - Version  Latest

**Additional context**

This might be releated to other colour problems we have found, but I've been unable to pinpoint its origin.

**Comment by jeremy-rifkin** [comment]
Able to reproduce
