### ISSUE TITLE
[REQUEST] Is it possible to increase the maximum number of lines of LLVM IR output?

### ISSUE THREAD

**Issue by topperc** [compiler-explorer/compiler-explorer#2600]
**Is your feature request related to a problem? Please describe.**
LLVM IR output is limited to 500 lines. I believe assembly is limited to 5000.

**Describe the solution you'd like**
I'd like the limit to be larger, but I don't know what the limitations are. IR lines are typically longer than assembly.

**Comment by mattgodbolt** [comment]
Shouldn't be a problem: done! Thanks :)

**Comment by topperc** [comment]
Awesome thanks!

**Comment by mattgodbolt** [comment]
It will go live in the next day or so; I sadly missed an earlier release I did.

**Comment by partouf** [comment]
fix is live
