### ISSUE TITLE
[REQUEST] Add SDCC 4.1

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2602]
Asked over email, and sent OP some hints in case they want to try adding it themselves.

**Comment by partouf** [comment]
Should be pretty straightforward if a binary release was done and still on Sourceforge

**Comment by partouf** [comment]
They changed the tar directory layout, so needs some fiddling

**Comment by partouf** [comment]
https://github.com/compiler-explorer/compiler-explorer/commit/bee9ef75ab1c9b4e6bf9aafc5e002b480cec15dd

**Comment by partouf** [comment]
oh, this is live
