### ISSUE TITLE
[BUG] Cursor never appears in Chrome iOS

### ISSUE THREAD

**Issue by mcandre** [compiler-explorer/compiler-explorer#2609]
**Describe the bug**

The editor cursor never appears in Chrome iOS in order to code.

**To Reproduce**

1. Launch Chrome on iOS.
2. Open a Compiler Explorer source file, such as the default program.

**Expected behavior**

Tapping once on the source code editor produces a cursor for writing text.

**Mobile**

 - OS: iOS
 - Browser: Google Chrome
 - Version: Latest stable

**Additional context**

A workaround is to force the website to apply desktop mode. So I guess something in the mobile-relative HTML/CSS/JS is preventing the cursor from working in the default mobile view.

**Comment by partouf** [comment]
This is intentional as described in https://github.com/compiler-explorer/compiler-explorer/issues/2042
