### ISSUE TITLE
[BUG] Command+V hotkey for pasting text not working in Chrome iOS

### ISSUE THREAD

**Issue by mcandre** [compiler-explorer/compiler-explorer#2610]
**Describe the bug**

The usual hotkey for pasting text with Command+V is not working in Chrome iOS.

**To Reproduce**

1. Copy some code to the iOS clipboard.
2. Enter a Compiler Explorer project.
3. Press Command+V.

**Expected behavior**

The clipboard text inserts into the project.

**Actual behavior**

Nothing happens.

**Mobile**

 - OS: iOS
 - Browser: Chrome
 - Version: Latest stable

**Additional context**

The Compiler Explorer's context menu Paste option is able to finally insert the text. However, I wish this common hotkey would work here, as it does for other websites.

**Comment by mattgodbolt** [comment]
This is likely a problem with Microsoft Monaco. we don't support editing in mobile browsers and try to show a read-only view. See #2042 for more details.
