### ISSUE TITLE
[BUG] When linking with clang and libc++ under nsjail -pthread is required

### ISSUE THREAD

**Issue by apmorton** [compiler-explorer/compiler-explorer#2611]
https://godbolt.org/z/snn7GT39Y

The above code should work, but does not.
When running CE locally using firejail or no sandboxing it does work, which indicates something is going on with the environment inside nsjail that causes `-pthread` to be required.

**Comment by partouf** [comment]
Someone reported similar andat was missing -pthread -lrt -ldl . I assumed it was something that changed in latest gcc, but perhaps then not.

**Comment by partouf** [comment]
It happened for gcc when using asan something something argument

**Comment by partouf** [comment]
Tested this without nsjail on both my VM with the latest compilers and on a prod instance. This error does not appear there and works as expected.

The interesting part of this is that the LD command that gets logged in the output does not mention pthread in any situation.

The little difference I could find between the compile and LD commands could not make me reproduce the issue.

(Also I'm extremely confused as to where the eventual executable can actually find `libc++.so` without it being in the rpath, but that's a different story)

Anyway. Libc++ requires the following libraries, but these are dynamic requirements - not static. So it really shouldn't upset the linker?

```
$ ldd /opt/compiler-explorer/clang-trunk/lib/libc++.so.1.0
        linux-vdso.so.1 (0x00007ffdea77a000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6178854000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6178662000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6178647000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6178b65000)
        libc++abi.so.1 => not found
```

And pthread requires:
```
$ ldd /lib/x86_64-linux-gnu/libpthread.so.0
        linux-vdso.so.1 (0x00007ffc1196e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f94fc6f6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f94fc918000)
```

I think the nsjail configuration does mention all these paths (`/lib` and `/lib64`) - or do we explicitly have to mount `/lib/x86_64-linux-gnu` ?

So... No matter how you look at this, it's confusing in every way.

Could it be that binutils LD just contains a bug and unjustly confused the dynamic requirements of libc++ ?

**Comment by mattgodbolt** [comment]
Non-working command-line:
> "/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/11.0.0/../../../../x86_64-linux-gnu/bin/ld" --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /app/output.s /lib/x86_64-linux-gnu/crt1.o /lib/x86_64-linux-gnu/crti.o /opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/11.0.0/crtbegin.o -L. -L/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/11.0.0 -L/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/11.0.0/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/usr/lib/x86_64-linux-gnu/../../lib64 -L/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/11.0.0/../../../../x86_64-linux-gnu/lib -L/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/11.0.0/../../.. -L/opt/compiler-explorer/clang-trunk-20201112/bin/../lib -L/lib -L/usr/lib -rpath . -rpath /opt/compiler-explorer/gcc-snapshot/lib64 -rpath /opt/compiler-explorer/gcc-snapshot/lib32 /tmp/example-531c16.o -lc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/11.0.0/crtend.o /lib/x86_64-linux-gnu/crtn.o


Working
>  "/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/11.0.0/../../../../x86_64-linux-gnu/bin/ld" -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /tmp/compiler-explorer-compiler2021326-775924-uydxn1.l623j/output.s /lib/x86_64-linux-gnu/crt1.o /lib/x86_64-linux-gnu/crti.o /opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/11.0.0/crtbegin.o -L. -L/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/11.0.0 -L/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/11.0.0/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/usr/lib/x86_64-linux-gnu/../../lib64 -L/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/11.0.0/../../../../x86_64-linux-gnu/lib -L/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/11.0.0/../../.. -L/opt/compiler-explorer/clang-trunk-20201112/bin/../lib -L/lib -L/usr/lib -rpath . -rpath /opt/compiler-explorer/gcc-snapshot/lib64 -rpath /opt/compiler-explorer/gcc-snapshot/lib32 /tmp/example-c9db46.o -lc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/11.0.0/crtend.o /lib/x86_64-linux-gnu/crtn.o

**Comment by mattgodbolt** [comment]
Notably missing in the non-working: `-z relro --hash-style=gnu`

**Comment by partouf** [comment]
> Notably missing in the non-working: `-z relro --hash-style=gnu`

Right, it doesn't actually make a difference supplying those manually, but it might be a sign of ... something

**Comment by mattgodbolt** [comment]
right (yeah just tried that too -Wl,-z,relro,--hash-style=gnu )

**Comment by mattgodbolt** [comment]
my guess is it's some `ld` configuration. we had some gumph in the firejail config...I'll see

**Comment by mattgodbolt** [comment]
```private-etc passwd,ld.so.conf.d,ld.so.conf``` was what I was thinking...

**Comment by mattgodbolt** [comment]
Yup, that's it.

**Comment by mattgodbolt** [comment]
I have _no idea_ what's going on :) but ... there's magic there.

**Comment by partouf** [comment]
Crazy. Still doesn't make any sense to me. Still seems a bug from LD that no one bothered to fix because the files are usually there.

**Comment by mattgodbolt** [comment]
Looks like the files point it at `/usr/local/lib` for `libc`, and `/usr/lib/x86_64-linux-gnu` etc. Something something multiarch? I dunno :)

**Comment by mattgodbolt** [comment]
Fix is now live
