### ISSUE TITLE
[BUG] Rust: Not all public functions are dissasembled

### ISSUE THREAD

**Issue by hkratz** [compiler-explorer/compiler-explorer#2617]
**Describe the bug**
I have three public functions and only see disassembly for two of them.

**To Reproduce**
See https://godbolt.org/z/KzWx3M1YP

**Expected behavior**
Disassembly should be shown for all three public functions.

**Link**
https://godbolt.org/z/KzWx3M1YP

**Comment by partouf** [comment]
This is because function 3 results in the exact same asm as function 2 and gets aliases into 1.

There's a .set directive in the assembly for this. If you uncheck filters - directives you can see that on the bottom of the asm output.

**Comment by hkratz** [comment]
@partouf Ah yes, thank you!
