### ISSUE TITLE
[BUG] Java ASM dump fails to parse

### ISSUE THREAD

**Issue by JakeWharton** [compiler-explorer/compiler-explorer#2623]
**Describe the bug**
Java bytecode dump fails to parse with
```
Internal Compiler Explorer error: TypeError: Cannot set property 'sourceLine' of undefined
    at JavaCompiler.parseAsmForClass (/infra/.deploy/lib/compilers/java.js:257:66)
    at /infra/.deploy/lib/compilers/java.js:153:52
    at Array.map (<anonymous>)
    at JavaCompiler.processAsm (/infra/.deploy/lib/compilers/java.js:153:36)
    at JavaCompiler.afterCompilation (/infra/.deploy/lib/base-compiler.js:1231:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /infra/.deploy/lib/base-compiler.js:1207:20
    at async run (/infra/.deploy/node_modules/p-queue/dist/index.js:159:29)
Compiler returned: -1
```

**To Reproduce**
Enter the following Java into the website:
```java
class Main {
  enum Greeting {
    FORMAL, INFORMAL
  }

  static String greetingType(Greeting greeting) {
    switch (greeting) {
      case FORMAL: return "formal";
      case INFORMAL: return "informal";
      default: throw new AssertionError();
    }
  }
}
```

**Expected behavior**
Compile succeeds, bytecode dumped.

**Link**
https://godbolt.org/z/77oe5P1W9

**Additional context**
Thanks for finally adding Java in a way that (hopefully) won't cripple the site!

**Comment by mattgodbolt** [comment]
Thanks for this! The parser is definitely in need of more work! This is handy; I'm sure ther's plenty more (and I'd love to parse the `-v` verbose flag to get more)

**Comment by JakeWharton** [comment]
Yeah I saw the comment in the commit about being able to visualize constant pool. It would be super helpful for examples like [this](https://godbolt.org/z/173xbTjxK) where the `invokedyanmic` bytecode doesn't really make sense _without_ the associated constant pool entries.

That said, I'm still excited to see it even available!

**Comment by partouf** [comment]
fix is live
