### ISSUE TITLE
[REQUEST] Support for chibicc (and lcc)

### ISSUE THREAD

**Issue by camel-cdr** [compiler-explorer/compiler-explorer#2639]
To mirror the words from the tcc feature request "Compiler Explorer should obviously support the smolest and therefore without question best C compiler in the world:" [chibicc](https://github.com/rui314/chibicc/)

But jokes aside, chibicc is an even smaller compiler, that generates x86 assembly using a simple stack machine structure.
The generated assembly is thus quite suboptimal, but it might still be useful, to look at the code a very simple compiler generates.

Adding [lcc](https://github.com/drh/lcc) might also be cool for historical reasons, though I'm not certain if the licensing would work out.

**Comment by RubenRBS** [comment]
Hi hi! Sorry that we said nothing back to you for so long!

I would certainly love to have chibicc available on the site, but it seems we will need to build it ourselves, which might takes us a bit, but I'll make sure to get it done! Thank you for the request!
