### ISSUE TITLE
[REQUEST] limit number of compiler errors

### ISSUE THREAD

**Issue by milahu** [compiler-explorer/compiler-explorer#2640]
**Is your feature request related to a problem? Please describe.**

the UI becomes very slow when the compiler throws many errors

for example, this buggy code loads very slow in my browser, with 10K compiler errors
https://godbolt.org/z/5qc8b6d9f

<details>

```c++
namespace libfmt {
using namespace libfmt;
// this will throw 10K compiler errors:
#include <fmt/core.h>
}

int main()
{
    libfmt::fmt::print("hello\n");
}
```

</details>

usually i only need the first error, in this case thats a signal-to-noise ratio of 1/10K

**Describe the solution you'd like**

gcc has

`-fmax-errors=10` to stop after 10 errors
`-Wfatal-errors` to stop after one error

clang has

`-ferror-limit=10` to stop after 10 errors

i suggest adding these as "reasonable default" compiler flags
maybe with a larger default value of, lets say, 100 errors (still better than 10K errors)

**Describe alternatives you've considered**

**Additional context**

**Comment by RubenRBS** [comment]
Hi! Sorry for the radio silence, we dropped the ball hard not getting back to you sooner :/

You raise a good point on the responsiveness of the site when a compiler spits out a large output. This was somewhat tackled in #2696, but there's still much to be done. Can you check if the link still gives you slowdowns?

I don't know if we'll end up limiting the compiler errors by using those flags, but TIL about them, thanks!

**Comment by milahu** [comment]
still an issue

`-std=c++17 -O3 -flto` -> 20 seconds
`-std=c++17 -O3 -flto -fmax-errors=10` -> 4 seconds

looks like a bottleneck somewhere, or a buffer issue

**Comment by jeremy-rifkin** [comment]
The repro link seems to load ok on my browser and I don't experience slowdown. I'll close this for now since it's been a very long time but if it still affects you or anyone else please let us know.
