### ISSUE TITLE
[REQUEST] `mrustc` as alternative Rust compiler

### ISSUE THREAD

**Issue by ojeda** [compiler-explorer/compiler-explorer#2643]
[`mrustc`](https://github.com/thepowersgang/mrustc) is a Rust compiler written in C++.

While it is mainly intended as a way to reduce the long bootstrap chain of `rustc`, [it can compile some non-`rustc` code too](https://github.com/thepowersgang/mrustc#building-non-rustc-code).

**Comment by dkm** [comment]
I would like to work on this but I'm not familiar with `mrustc` yet.
What would be the better solution for using `mrustc`?
Initial guess would be:
```
$ make
$ make LIBS
```
Then I can use `bin/mrustc` with the freshly built `libstd` to compile simple examples.

How do you get the assembly output ? Also, I don't see any tag/release. Do you expect to have `mrustc` build daily from the `master` branch or is there some prebuild tarball available somewhere?

**Comment by ojeda** [comment]
> Do you expect to have mrustc build daily from the master branch or is there some prebuild tarball available somewhere?

I think having a build from time to time is enough for the moment. However, perhaps @thepowersgang would welcome nightlies nevertheless!

**Comment by dkm** [comment]
Hope to have everything correct here.
3 PR: 
- 1 for supporting mrustc in CE + updated amazon config for rust part (haven't skipped the tests this time /o\)
- builder script used to create a "packaged" mrustc for the github repository
- corresponding invocation to builder script in the infra nightly script to have it correctly build
