### ISSUE TITLE
[BUG] (?) Can't get Abseil's flatmap to work (Linker complains about the internal Wyhash...)

### ISSUE THREAD

**Issue by Falkgaard** [compiler-explorer/compiler-explorer#2658]
**Describe the bug**
```
ASM generation compiler returned: 0
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/12.0.0/../../../../x86_64-linux-gnu/bin/ld: ./libabsl_hash.a(hash.cc.o): in function `absl::hash_internal::HashState::WyhashImpl(unsigned char const*, unsigned long)':
hash.cc:(.text+0x21d): undefined reference to `absl::hash_internal::Wyhash(void const*, unsigned long, unsigned long, unsigned long const*)'
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
Execution build compiler returned: 1
```

**To Reproduce**
Use a std::string as a key in a absl::flat_hash_map and do something that requires a hash (insert, find...)

**Expected behavior**
Compile without errors.

**Link**
<https://godbolt.org/z/6Ybn94YoT>

**Screenshots**
Not necessary. See the link and linker error.

**Additional context**
I might be an idiot that missed something essential (compiler flag or whatever...)

**Comment by partouf** [comment]
Currently we link to the following 
https://github.com/compiler-explorer/compiler-explorer/blob/126204172c57848260c139046832146d6727ec4b/etc/config/c%2B%2B.amazon.properties#L1282

The binaries were built yesterday so it's pretty fresh.

Maybe the order is wrong and something was optimized away... or it's some kind of abseil issue...

Not sure...

**Comment by Falkgaard** [comment]
> It might be worth it to report this to https://github.com/abseil/abseil-cpp/issues

Will do! Cheers

**Comment by derekmauro** [comment]
https://github.com/compiler-explorer/compiler-explorer/blob/c3a171c979dd63a7f89b0ee65f9ddbd5b5bdb534/etc/config/c%2B%2B.amazon.properties#L1282

It looks like the linker inputs is missing `absl_wyhash`.

**Comment by partouf** [comment]
> https://github.com/compiler-explorer/compiler-explorer/blob/c3a171c979dd63a7f89b0ee65f9ddbd5b5bdb534/etc/config/c%2B%2B.amazon.properties#L1282
> 
> It looks like the linker inputs is missing `absl_wyhash`.

Except that there's no such binary built by the abseil project?

**Comment by derekmauro** [comment]
> Except that there's no such binary built by the abseil project?

There is: https://github.com/abseil/abseil-cpp/blob/7ba826e50dff1878e6ecc6b9af44097c040c8968/absl/hash/CMakeLists.txt#L119-L132

**Comment by partouf** [comment]
I found that it's being built, but something goes wrong within the rest of the build process.

This should be fixed with this night's build, will check in the morning.

**Comment by partouf** [comment]
I messed something up and it didn't get built yesterday, doing it right now. Meanwhile some compilers will give the error "cannot find -labsl_wyhash"

**Comment by partouf** [comment]
This is now fixed! Thanks for the heads up and the help!

**Comment by jpan127** [comment]
@partouf Hi I'm seeing this again today. https://godbolt.org/z/Ebffqvdnx

**Comment by partouf** [comment]
wyhash seems to have changed name to low_level_hash

**Comment by partouf** [comment]
this is now fixed again

**Comment by jpan127** [comment]
@partouf thank you!
