### ISSUE TITLE
Support GCC Sparc

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#266]
With hints on how:

```GCC has a GPL license so it is always open source. Most of the patches we have on GCC are not code generation related, mostly information about what libraries to generate and which defines to provide and so on. The only code generation patch we have is the B2BST errata fix, the "-mfix-b2bst" flag.
 
The easiest for Matt Godbolt would be to take the 4.9.4 release of GCC and compile it with "--target=sparc-leon-linux-gnu". If you want to include support for the "-mfix-b2bst" flag I can send you that patch.
 
Daniel Cederman
Cobham Gaisler
support@gaisler.com```

**Comment by mattgodbolt** [comment]
Also requested by twitter user @Thalionath

**Comment by thalionath** [comment]
More on how:

You could use crosstool-ng to build a cross-compiler for sparc-unknown-elf. I attached a config file [sparc-unknown-elf.zip](https://github.com/mattgodbolt/compiler-explorer/files/785192/sparc-unknown-elf.zip) to build a toolchain including:

 - gmp-6.1.2
 - mpfr-3.1.5
 - isl-0.16.1
 - mpc-1.0.3
 - binutils-2.27
 - gcc-6.3.0
 - newlib-2.5.0
 
https://github.com/crosstool-ng/crosstool-ng is great and straightforward:

    ./bootstrap
    ./configure
    make && make install

To build a toolchain, change to some temporary build an run:

    ct-ng menuconfig (kernel like config)
    ct-ng build
 
One can choose where it will install the toolchain in the config. Default is ~/x-tools

    export PATH=~/x-tools/sparc-unknown-elf/bin:$PATH
    sparc-unknown-elf-g++ -c hello.cpp -o hello.o
    sparc-unknown-elf-objdump -D hello.o

**Comment by mattgodbolt** [comment]
That's great: thanks !

**Comment by thalionath** [comment]
Ok, I was not aware how easy it is to add new compilers. So, I put together a Dockerfile to build an image running Compiler Explorer with Gaislers BCC cross compilers and gcc 7.1.0. Checkout my repo at https://github.com/thalionath/compiler-explorer-sparc

**Comment by mattgodbolt** [comment]
Was asked again about this over email. Thanks @thalionath -- we'll have to take a look at getting it on to the live site!

**Comment by dbhinz** [comment]
@thalionath I've also asked Matt about getting sparc compiler support (I asked Matt about it again via email yesterday).  Would it be possible to also bring in the GCC 4.9.4 compiler and use the compiler flags as mentioned by Matt at the start of this thread.  Let me know if I can help in some way.

**Comment by thalionath** [comment]
Luckily, ct-ng supports GCC 4.9.4 and it is a rainy weekend @dbhinz. I quickly backported and added Cobham Gaislers patch to add -mfix-b2bst, but did not test it very well. Maybe I should ask Daniel Cederman for his original 4.9.4 patch and if he is willing to provide the patches for the other errata too.

**Comment by dbhinz** [comment]
Have you made progress on getting the SPARC cross compiler working?  The latest release from Gaisler, where Daniel works, now uses the latest GCC 4.9.4 version. You might check with Daniel to get some help on this compiler.

**Comment by mattgodbolt** [comment]
Hi, I'm sorry I haven't really looked into this all that much recently. Many other things have come along and made my life busy!

I think the best way to proceed is for someone to get a docker image to build the compiler together. If you look at the [gcc-cross](https://github.com/mattgodbolt/compiler-explorer-image/tree/master/gcc-cross) docker container for example you'll see how I build other cross-compilers. Ultimately this [shell script](https://github.com/mattgodbolt/compiler-explorer-image/blob/master/gcc-cross/build/build.sh) runs, does the build and `tar`s up the result (optionally putting it in S3 where my built compilers live)

When I build the compilers I use these docker containers to ensure they're repeatable and isolated. If someone can step up to the task of making a docker container...or adapting the existing `gcc-cross` container, then that'd be great.

Once I can build the compiler it's only a few minutes' work to get it live on the site.

**Comment by dbhinz** [comment]
Matt, has the SPARC build bubbled any higher on your to-do list for compilers.  Would really like to see the GCC 4.9.4 and GCC 7.1.0 versions working.  I can attempt to do it, but not real familiar with "docker" images, etc.  Maybe Daniel at Gaisler could help.  The latest GCC 4.9.4 compiler uses -mfix-ut700 instead of the older -mfix-b2bst so that additional fixes are applied.

**Comment by mattgodbolt** [comment]
Hi @dbhinz I'm afraid not: we have so many other competing needs and requests. I'll keep this parked here in case someone else has time.

**Comment by dbhinz** [comment]
Matt, 

Thanks for keeping this in your queue to be worked.

**Comment by stefanct** [comment]
Apparently it's my turn this year ;) I would have had some use for a sparc implementation today.

From a quick glimpse over the repo and [this commit](https://github.com/mattgodbolt/compiler-explorer-image/commit/3ae1dd4b20c2837c7ed204bc8737e47454a35893) that adds a new cross compiler, I think pretty much all that is needed (in the best case where no ct-ng or other patches are required) is a working crosstool-ng configuration and an entry in `build_cross_compilers.sh`. Is that correct?

**Comment by bencz** [comment]
@stefanct Any success?

**Comment by stefanct** [comment]
I did not try but as I wrote it did not look too complicated.

**Comment by bencz** [comment]
well... maybe, it is more easy...
just for test, if you select a clang compiler ( for any arch... ), and, add this option '-target sparc64' ... tahdah, you have a Sparc64 assembly output

**Comment by bencz** [comment]
@mattgodbolt If added in the `c.amazon.properties` file ( for c++ too ) something like this:

```
....
compiler.csparc64clang.exe=/opt/compiler-explorer/clang-trunk/bin/clang
compiler.csparc64clang.demangler=/opt/compiler-explorer/gcc-snapshot/bin/c++filt
compiler.csparc64clang.objdumper=/opt/compiler-explorer/gcc-snapshot/bin/objdump
compiler.csparc64clang.name=sparc64 clang (trunk)
compiler.csparc64clang.options=-target sparc64
....

```
will it work?

**Comment by mattgodbolt** [comment]
I think so @bencz -- if it works in the usual UI to put `-target sparc64` which it seems to...then...that would work!

**Comment by partouf** [comment]
I don't mind about the diversion, but this issue was initially about Gcc and not Clang. So the question is, would that actually satisfy the original request?

**Comment by mattgodbolt** [comment]
Oh good point! I hadn't spotted we'd pivoted from gcc, sorry!

**Comment by dbhinz** [comment]
I would still like to see a gcc compiler.  Version 4.9.4 is what Gaisler.com provides for VxWorks 6.9 to use with their Leon processor.  They support a newer version of gcc and clang for VxWorks 7.x.

**Comment by partouf** [comment]
Seems they have downloads of the sources https://www.gaisler.com/index.php/downloads/compilers
It doesn't look standard, but they have a buildscript .sh thing.
We probably have to make a new builder, but it might not need anything special other than a gcc.

**Comment by dkm** [comment]
While looking at old issues, I see that I may be able to help here.
Would any these be ok?
```
sparc64-multilib-linux-gnu/  sparc-leon-linux-uclibc/     sparc-unknown-linux-gnu/   
```
I should be able to build these with our regular ct-ng setup.

**Comment by dkm** [comment]
Have successfully built a sparc-leon toolchain. Will see how far I can get it to work and will do the same for sparc64 and sparc.
Not yet sure about the diff between sparc and sparc-leon (do we need both?)

**Comment by dkm** [comment]
- [x] gcc-cross-build change https://github.com/compiler-explorer/gcc-cross-builder/pull/44
- [ ] compilers build
 - [ ]  sparc https://github.com/compiler-explorer/infra/actions/runs/3440284623
 - [ ] sparc64 https://github.com/compiler-explorer/infra/actions/runs/3440286361
 - [ ] sparc-leon https://github.com/compiler-explorer/infra/actions/runs/3440287536
- [ ] infra change
- [ ] compiler installed
- [ ] config change

**Comment by partouf** [comment]
these are now live
