### ISSUE TITLE
Consider some trickery to look nicer on less wide screens

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2664]
With reference to @KateGregory's tweet https://twitter.com/gregcons/status/1393566200618098692/photo/1

**Comment by mattgodbolt** [comment]
![image](https://user-images.githubusercontent.com/633973/118368165-42171500-b567-11eb-83b3-34236b49227c.png)

**Comment by RubenRBS** [comment]
This was fixed by #2667, but I missed that there was an associated issue, sorry about that! :)
