### ISSUE TITLE
[BUG] Rust: Broken highlighting of escape sequences in char literals

### ISSUE THREAD

**Issue by LingMan** [compiler-explorer/compiler-explorer#2665]
**Describe the bug**
Rust char literals containing an escape sequence such as `'\n'` don't get highlighted correctly and `'\"'` even breaks highlighting of the following code. Presumably the tokenization is buggy. C code does not show the same issue.

**To Reproduce**
```rust
pub fn foo() {
    let _works_in_str = "\n\"";
    let _x = '\n';
    let _y = '\"';
    // Now it thinks everything until the next
    // double quote is part of a string
}

pub fn bar() {
    let _unbreak_it = "\"\"";
    let _and_here_it_works_again = true;
}
```

**Expected behavior**
`'\n'` and `'\"'` should be colored like syntactically correct char literals and not like something invalid.

**Link**
https://godbolt.org/z/6cvhzaz1r

**Screenshots**
![godbolt](https://user-images.githubusercontent.com/18645382/118377380-31998580-b5cd-11eb-9889-ea7edc4d780c.png)

**Comment by mattgodbolt** [comment]
This is an issue in the upstream Monaco repo. I filed a bug there.
