### ISSUE TITLE
[BUG] Rust: Functions that compile to the same assembly as another function disappear from the output

### ISSUE THREAD

**Issue by LingMan** [compiler-explorer/compiler-explorer#2668]
The rust compiler deduplicates functions with identical assembly since 1.32.0. On [the rust playground](https://play.rust-lang.org/) this gets indicated by a line such as `.set example::bar, example::foo` at the end of the output. Compiler explorer filters that line  though. It can still be found hidden in a pile of other directives when filtering of directives is manually disabled, but it should be shown by default.

**To Reproduce**
Set language to Rust, choose a compiler version >= 1.32.0, and set the flags field to `-O`. Put this in the code field:
```rust
pub fn square(num: i32) -> i32 {
    num * num
}

pub fn square2(num: i32) -> i32 {
    num * num
}
```

**Expected output**
```asm
example::square:
        mov     eax, edi
        imul    eax, edi
        ret
.set example::square2, example::square
```

**Actual output**
```asm
example::square:
        mov     eax, edi
        imul    eax, edi
        ret
```

**Link**
https://rust.godbolt.org/z/6Y577MMd8

**Comment by partouf** [comment]
Hi, thanks for the example. We have so many issues regarding .set, I'm closing this issue in favor of those. https://github.com/compiler-explorer/compiler-explorer/issues/2409

**Comment by LingMan** [comment]
My search fu failed me ><
