### ISSUE TITLE
[REQUEST] Zulip external code playground integration

### ISSUE THREAD

**Issue by mvanotti** [compiler-explorer/compiler-explorer#2670]
**Is your feature request related to a problem? Please describe.**

Recently [Zulip, the chat platform](https://zulip.com/), added support for [external code playgrounds](https://zulip.com/help/code-blocks#code-playgrounds). This allows you to "export" your code to different services and run them there.

Basically it works by concatenating the url-encoded code with a predefined URL.

**Describe the solution you'd like**

I guess it would look something like:

```
https://godbolt.org?lang=cpp&compiler=XXX&compiler_flags=YYYY&code=...
```

A way to encode a godbolt playground in a URL and have the code in a parameter so that zulip can just cancatenate the URL-encoded code.

**Describe alternatives you've considered**

Maybe this don't need to be part of godbolt. It could be part of a middleware service that received the code and created a godbolt full short url, similar to this example that Matt provided over Discord:

> an example of programmatically making a URL: https://github.com/mattgodbolt/pt-three-ways-pres/blob/master/compiler-explorer.js

**Additional context**

Matt's messages from the Discord discussion:

> Hi there. Compiler Explorer doesn't currently support that, but it's an interesting idea and shouldn't be too difficult to add
> I don't have access to Zulip to play with anything, and our URL syntad is a little trickier
> If you make a "full URL" short link you can see what they look like:
> `https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(fontScale:14,fontUsePx:%270%27,j:1,lang:c%2B%2B,selection:(endColumn:17,endLineNumber:1,positionColumn:17,positionLineNumber:1,selectionStartColumn:17,selectionStartLineNumber:1,startColumn:17,startLineNumber:1),source:%27/*YOURCODEHERE*/%27),l:%275%27,n:%270%27,o:%27C%2B%2B+source+%231%27,t:%270%27)),k:50,l:%274%27,n:%270%27,o:%27%27,s:0,t:%270%27),(g:!((h:compiler,i:(compiler:g111,filters:(b:%270%27,binary:%271%27,commentOnly:%270%27,demangle:%270%27,directives:%270%27,execute:%271%27,intel:%270%27,libraryCode:%270%27,trim:%271%27),fontScale:14,fontUsePx:%270%27,j:1,lang:c%2B%2B,libs:!(),options:%27%27,selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:%275%27,n:%270%27,o:%27x86-64+gcc+11.1+(Editor+%231,+Compiler+%231)+C%2B%2B%27,t:%270%27)),k:50,l:%274%27,n:%270%27,o:%27%27,s:0,t:%270%27)),l:%272%27,n:%270%27,o:%27%27,t:%270%27)),version:4`
> A lot of those options can be dropped. And we do have some RESTful APIs
I am pretty sure encoded JSON works too (that' the RISON encoded thing)

**Comment by partouf** [comment]
Because there's too much you can't do with this method, I don't want people to make a habit out of this. So I would suggest if implemented to keep it undocumented.

On the Zulip side, the code seems to be properly encoded (https://github.com/zulip/zulip/commit/87c809c0e31246b0cb4f737d80c1629a7aeba495#diff-e0a3579cd94cdbddbf5807b5ec125f754a1c65f37a458fc7cc6d47b71c63a16fR899) so I guess it shouldn't be a problem.

**Comment by mvanotti** [comment]
@partouf could you help me understand how this api is supposed to be used? I followed your example in the discussion before, and when I try to access https://godbolt.org/fromsimplelayout?lang=c%2B%2B&compiler=gdefault&compiler_flags=-O3&code=i I get some javascript errors

**Comment by partouf** [comment]
> @partouf could you help me understand how this api is supposed to be used? I followed your example in the discussion before, and when I try to access https://godbolt.org/fromsimplelayout?lang=c%2B%2B&compiler=gdefault&compiler_flags=-O3&code=i I get some javascript errors

Hi, `gdefault` isn't a valid compiler on the website. You should use one of the compilers listed here: https://godbolt.org/api/compilers/c++

**Comment by mvanotti** [comment]
Thanks @partouf ❤️
