### ISSUE TITLE
Quick "copy to clipboard" button in share dropdown

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2671]
A number of folks, in-person and on Discord, have said they appreciate the new share dialog but it's now one more click for them in the common case.

Perhaps we can have a clipboard icon on the right of the dropdown menu item that sends the request and then puts it into the clipboard.

I hacked something like:

```pug
                button.btn.ml-auto.btn-sm.clippy(type="button" title="Copy to clipboard")
                  span.dropdown-icon.fa.fa-clipboard
```

and it looks _ok_ but I ran out of time before I got to the meat of the issue (that is, clicking the icon sends the request, and then puts the result in the clipboard).

**Comment by RubenRBS** [comment]
With .btn-group we can get something like this:
![imagen](https://user-images.githubusercontent.com/5364255/118750233-5016af80-b85f-11eb-9c5c-26e03660fd9e.png)
Any ideas?
(Note that fonts look different because I've moved the menu to use buttons instead of links)

**Comment by partouf** [comment]
Having seen some small display setups, I'm not sure we should be stuffing more things on the top bar. I would prefer it to just be on the Shortlink share menu item.
