### ISSUE TITLE
[BUG] **Run make EXTRA_ARGS='--language LANG' Throw an exception**

### ISSUE THREAD

**Issue by qufanqi** [compiler-explorer/compiler-explorer#2676]
**Describe the bug**
After git clone the repository, Run `make EXTRA_ARGS='--language LANG'` in the _compiler-explorer_ directory. The following error occurred:

```
Starting child process with '/home/qufanqi/.nvm/versions/node/v12.22.1/bin/node -r esm ./app.js --language LANG'

morgan deprecated default format: use combined format node_modules/esm/esm.js:1:278827

info: properties hierarchy: defaults, dev, dev.linux, linux, qufanqi-vmwarevirtualplatform, local

info: Reading properties from etc/config with hierarchy defaults,dev,dev.linux,linux,qufanqi-vmwarevirtualplatform,local

info: WINE not configured

error: Top-level error (shutting down): Cannot read property 'id' of undefined {"stack":"TypeError: Cannot read property 'id' of undefined\n    at /home/qufanqi/Desktop/compiler-explorer/lib/options-handler.js:62:45\n    at CompilerProps.get (/home/qufanqi/Desktop/compiler-explorer/lib/properties.js:164:20)\n    at new ClientOptionsHandler (/home/qufanqi/Desktop/compiler-explorer/lib/options-handler.js:61:48)\n    at main (/home/qufanqi/Desktop/compiler-explorer/app.js:455:34)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:66:3)\n    at /home/qufanqi/Desktop/compiler-explorer/node_modules/esm/esm.js:1:34535\n    at /home/qufanqi/Desktop/compiler-explorer/node_modules/esm/esm.js:1:34176\n    at process.<anonymous> (/home/qufanqi/Desktop/compiler-explorer/node_modules/esm/esm.js:1:34506)\n    at Function.<anonymous> (/home/qufanqi/Desktop/compiler-explorer/node_modules/esm/esm.js:1:296856)"}
Program /home/qufanqi/.nvm/versions/node/v12.22.1/bin/node -r esm ./app.js --language LANG exited with code 1
```

Then repeatedly execute `Starting child process with'/home/qufanqi/.nvm/versions/node/v12.22.1/bin/node -r esm ./app.js --language LANG'`

If I just run make, it can run normally and open http://localhost:10240/

**To Reproduce**
1. git clone https://github.com/compiler-explorer/compiler-explorer.git
2. cd compiler-explorer
3. make EXTRA_ARGS='--language LANG' 

**Expected behavior**
Automatically install all the third party libraries. For example, the language compilers listed in languages.js

**Screenshots**
![1](https://user-images.githubusercontent.com/44468530/119108254-9849f380-ba52-11eb-9952-72dfa9702cff.PNG)

**Desktop**
 - OS: Manjaro Linux 21.0.5
 - Browser 
 - Version 

**Additional context**
I use VMware® Workstation 16 Pro to run Manjaro on Windows 10
In fact, I also encountered the same problem in fedora remix for wsl. But I’m not sure if it’s a wsl problem, so I tried a few times with a virtual machine.

**Comment by RubenRBS** [comment]
You seem to be running the code following https://github.com/compiler-explorer/compiler-explorer#developing. 
> Running with make EXTRA_ARGS='--language LANG' will allow you to load LANG exclusively, where LANG is one for the language ids/aliases defined in lib/languages.js

The important bit here is _"where LANG is one for the language ids/aliases defined in lib/languages.js"_. You seem to not have subsituted LANG for any value. An example of a correct invocation would be `make EXTRA_ARGS='--language c++'` to only load the C++ compilers :)
