### ISSUE TITLE
[BUG] Go non amd64 build: no space left on device

### ISSUE THREAD

**Issue by oxzi** [compiler-explorer/compiler-explorer#2678]
**Describe the bug**

I tried to build a simple Go program on different target architectures, which results in a build error on a non amd64 compiler.

For example, building <https://godbolt.org/z/G5Kqjz6dz> works on _amd64 gc 1.16_ or _amd64 gc 1.4.1_, but not on _386 gc (tip)_, _386 gc 1.16_, _ARM64 gc 1.16_ or _MIPSLE gc 1.16_. I also tried some other targets, but it seemed like only amd64 works.
All errors are a variant of "no space left on device".

**To Reproduce**

Try to build <https://godbolt.org/z/G5Kqjz6dz> on _amd64 gc 1.16_ and again on some other architecture, as listed above.

**Expected behavior**

I expected a successfully compilation for each platform.

**Link**

https://godbolt.org/z/G5Kqjz6dz

**Screenshots**

```
go build syscall: open /tmp/go-build573388246/b029/importcfg: no space left on device
go build path: mkdir /tmp/go-build573388246/b034/: no space left on device
# strconv
can't create $WORK/b017/_pkg_.a: open $WORK/b017/_pkg_.a: no space left on device
Compiler returned: 2
```

**Comment by apmorton** [comment]
This should be fixed on the live site.

You may have to forcefully rebuild any cached compiles to clear out the error.
