### ISSUE TITLE
[BUG] Backslash Support in C and C++

### ISSUE THREAD

**Issue by JannesAlthoff** [compiler-explorer/compiler-explorer#2682]
**Describe the bug**
The Syntax Highlighter for C and C++ does not support Backslashes as a way to combine to lines as defined in the C Standard. Section 5.1.1.2 of C11 defines that each backslash char after which is a newline char shall be deleted with the newline char.

**To Reproduce**
Use A Backslash at the end of a line with a one-line comment.

**Expected behavior**
The nextline is part of the Comment.

**Link**
https://godbolt.org/z/rsn37eahz

**Comment by JannesAlthoff** [comment]
`/**\
\
/`
Results in the code being commented afterwards beacause of the same reason.

**Comment by mattgodbolt** [comment]
I've filed this as a bug in the upstream. I've submitted patches before and so we can probably make a fix and get it upstreamed.

**Comment by partouf** [comment]
Related issue -> https://github.com/compiler-explorer/compiler-explorer/issues/2288

**Comment by partouf** [comment]
this was fixed in monaco
