### ISSUE TITLE
[BUG] No content displayed in Waterfox Classic

### ISSUE THREAD

**Issue by Bu11etmagnet** [compiler-explorer/compiler-explorer#2689]
**Describe the bug**
Source editor, assembler output panes don't appear

**To Reproduce**

Open www.godbolt.org with Waterfox Classic 2021.03 (64-bit)

**Expected behavior**
Source editor, assembler output appear.

**Link**
godbolt.org

**Screenshots**
See https://github.com/MrAlex94/Waterfox/issues/2052

**Additional context**
```
SyntaxError: invalid identity escape in regular expression  vendor.v4.e355c14b4154f354d058.js:2:2630816
```
appears in the Web Console

**Comment by mattgodbolt** [comment]
Sorry, this is an upstream issue with the monaco text editor widget we use :( So far only old Safari browsers have issues with this regex, but obviously this browser also doesn't support it. We have asked Monaco for help in fixing it, but they (understandably) mostly target the major contemporary browsers. (TIL "Waterfox"!).

**Comment by mattgodbolt** [comment]
See #2529

**Comment by mattgodbolt** [comment]
Actually will close in favour of that.
