### ISSUE TITLE
[BUG] Swift nightly doesn't compile

### ISSUE THREAD

**Issue by Trzyipolkostkicukru** [compiler-explorer/compiler-explorer#2692]
**Describe the bug**
Swift nightly compiler doesn't work. When trying to compile any code, it shows the following error
```
/opt/compiler-explorer/swift-nightly/usr/bin/swift-driver: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
Compiler returned: 127
```
**To Reproduce**
- select Swift as the language for the source code
- write some valid code, for example `func hello() {}`
- select x86-64 swiftc nightly as the compiler
- look at the compiler output window

**Expected behavior**
correct code should compile

**Link**
https://godbolt.org/z/5hjjv35hh

**Screenshots**
![image](https://user-images.githubusercontent.com/5207692/120008189-00f91900-bfdb-11eb-8b05-01fb5c92e7e7.png)

**Comment by masters3d** [comment]
Asking Swift Community for help here: https://forums.swift.org/t/swift-driver-nightly-on-https-swift-godbolt-org/49802

**Comment by partouf** [comment]
This is now resolved. We're not entirely sure why, but using the Ubuntu 20 packages instead resolved the libncurses dependency. (See https://github.com/compiler-explorer/infra/commit/778c39a040e82aef4f7a0650f54c3cf15cb0154d)
