### ISSUE TITLE
IR Viewer only colourises Compiler # 1

### ISSUE THREAD

**Issue by kylefernandes** [compiler-explorer/compiler-explorer#2699]
**Describe the bug**
The IR Output doesn't have colour for any Compiler other than Compiler # 1.

**To Reproduce**
Add two compilers and open the IR Output for both.
Compiler # 2 doesn't have colour even if you close Compiler # 1 and/or its IR Output.

**Expected behavior**
The IR Output for Compiler # 2 should also have colour highlighting.

**Link**
https://godbolt.org/z/nEGbasY1c

**Screenshots**
![image](https://user-images.githubusercontent.com/20503152/120628931-29f72f00-c45d-11eb-8a10-fe934be8d30d.png)

**Comment by kylefernandes** [comment]
In case it's useful...Manually toggling colourisation via `Ctrl` + `Shift` + `F1` seems to make the IR Viewers for the other Compilers get colour highlights too :tada:. So that's a not-too-bad work-around.

**Comment by RubenRBS** [comment]
Note that the link does not even colourise the first IR view either. I'll try to take a look at it in the next few days when I have a bit of free time :)

**Comment by jeremy-rifkin** [comment]
I'll coalesce this issue with #5126
