### ISSUE TITLE
[LIB REQUEST] Boost for CUDA

### ISSUE THREAD

**Issue by bernhardmgruber** [compiler-explorer/compiler-explorer#2701]
**Library name:**
Boost as provided on https://cpp.godbolt.org/

**Motivation:**
I develop the memory-layout-performance-portability library [LLAMA](https://github.com/alpaka-group/llama) that is usable with and without CUDA. Compiler explorer gives me an incredible experience for non-CUDA scenarious. I would love to also play with CUDA on https://cuda.godbolt.org/!

Thank you for all the great work so far!

**Comment by bernhardmgruber** [comment]
Ping. This is still an issue for my team and me. We develop the [alpaka](https://github.com/alpaka-group/alpaka) performance portability layer and would like to examine the CUDA backend using CE. Please make Boost available for the CUDA language! Thank you!

**Comment by partouf** [comment]
@bernhardmgruber you can send a PR yourself to add this by having a look at https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/AddingALibrary.md and using the existing settings that we have here https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/c%2B%2B.amazon.properties#L2520

**Comment by bernhardmgruber** [comment]
Ok thx! Done: #5152
