### ISSUE TITLE
lib request for rust: fnv

### ISSUE THREAD

**Issue by c-cube** [compiler-explorer/compiler-explorer#2702]
https://crates.io/crates/fnv is a fast non cryptographic hash function that is useful for algorithms (see the download count). It'd be useful to see what the fnv hashmaps look like in godbolt.

**Comment by RubenRBS** [comment]
Hi, sorry about not getting back to you sooner, and thanks for taking the time to open the request!

I have added it to the main list of rust requests so we don't miss any of the crate requested when we end up adding support for it, so I'll close this issue in favour of the linked one :)

**Comment by c-cube** [comment]
Thank you very much! :)
