### ISSUE TITLE
[REQUEST] Add `zig c++` as a C++ compiler

### ISSUE THREAD

**Issue by kassane** [compiler-explorer/compiler-explorer#2707]
Reference: #2427 

It would be interesting to add zig compiler for C++ also.

**Comment by RubenRBS** [comment]
Hi! Sorry that we didn't get back to you sooner!

This is indeed a great suggestion, but note that until 0.8.1 comes out, this will have some problems as discussed in #2434

**Comment by kassane** [comment]
Nice. But when testing `zig c++` there is some problem during the execution of the toolchain forcing to kill the application.
