### ISSUE TITLE
[REQUEST] Support Solidity compiler (solc)

### ISSUE THREAD

**Issue by ebenali** [compiler-explorer/compiler-explorer#2723]
Support multiple versions of the solidity (`solc`) with diffing EVM assembly output (additionaly `ewasm`, possibly in a later revision)

**Comment by mattgodbolt** [comment]
I looked at this a few years back, and the solidity compiler at the time didn't output "debug info" of any sort to let us track which lines of solidity correspond to which output. I don't know if this changed, and perhaps even without this it would be useful.

**Comment by RubenRBS** [comment]
Hi! Solidity is now available on the site :)
