### ISSUE TITLE
[BUG] libunifex not linking with clang-11 or clang-12

### ISSUE THREAD

**Issue by ericniebler** [compiler-explorer/compiler-explorer#2726]
See https://godbolt.org/z/6j9cvjWPe

Results in:

```bash
/opt/compiler-explorer/gcc-10.3.0/lib/gcc/x86_64-linux-gnu/10.3.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -lunifex
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```

Also, libunifex's config.hpp is painfully out of date and needs to be regenerated. That is the subject of #2421.

**Comment by partouf** [comment]
Any PR's to change it are welcome https://github.com/compiler-explorer/infra/blob/main/bin/resources/libunifex_config.hpp

I will trigger a rebuild on the compilers where needed once that's done.

**Comment by ericniebler** [comment]
> I will trigger a rebuild on the compilers where needed once that's done.

OK, libunifex's `config.hpp` has been regenerated. Can you pls rebuild libunifex?

**Comment by partouf** [comment]
I have replaced the config.hpp, but I temporarily forgot how to build things in time before the nightlies. I will retry tomorrow afternoon.

**Comment by partouf** [comment]
this should now be resolved

**Comment by ericniebler** [comment]
Thank you!
![It's so beautiful](https://media.giphy.com/media/NiOPyn6a7tV3q/giphy.gif)
