### ISSUE TITLE
[BUG] "Execution only" pane can select targets that don't support execution

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#2730]
**Describe the bug**
User can be facing a configuration that is hard to understand ("What is wrong here???")

**To Reproduce**
Enter simple code
- Add >> Execution only (should show x86 exec result)
- change the compiler to something NOT supporting exec (eg. any KVX)
- "Could not execute the program"

**Expected behavior**
The compiler selection diag should simply not show compilers where there's no exec support

**Link**
https://godbolt.org/z/zaYaPKnMY

**Comment by dkm** [comment]
What has been misleading me was that I could not see any assembly output (clicking the "compiler output" doesn't show anything) nor see if the compiler was running or not. I was first thinking that the "could not execute the program" was referring to the compiler not being executed correctly.
If the compiler selection can't really be done at this step, maybe add something very clear, like

 'This compiler can't be used for execution, open a "compilation only" pane instead'
instead of "Could not execute the program" ?

**Comment by partouf** [comment]
That would be much clearer, indeed. Good suggestion

**Comment by partouf** [comment]
Although I think the compiler shouldn't be in the dropdown either. That might have been missed when replacing the compiler selection widget #2666

**Comment by mattgodbolt** [comment]
Ah! Nice spot @partouf ! Whoops :)
