### ISSUE TITLE
[REQUEST] Add clang 12 for RISC-V

### ISSUE THREAD

**Issue by topperc** [compiler-explorer/compiler-explorer#2739]
**Is your feature request related to a problem? Please describe.**
clang 9, 10, 11, and trunk are there for RISC-V but not 12.

**Describe the solution you'd like**
Add clang 12. Maybe sort the list so the newer versions come first. rv32gc goes trunk, 10.0.0, 10.0.1, 11.0.0, 11.0.1, 9.0.0, 9.0.1

**Describe alternatives you've considered**

**Additional context**

**Comment by RubenRBS** [comment]
Hi! Thanks for taking the time to let us know we missed this version. I've now added it and it should show up as soon as we update the site.

As for the weird version ordering, it was meant to work as you described. I've now also fixed the missconfiguration that caused it not to work, so thanks for also reporting that one :)

**Comment by topperc** [comment]
Is this still not live? I thought I remembered seeing clang 12 sometime in the last month, but it's not there now so maybe I'm crazy?

**Comment by RubenRBS** [comment]
Ah, that's embarassing. I see what's happening. You're looking at C compilers most likely, which _also_ have this version missing! Sorry about that! I'll fix it right away
