### ISSUE TITLE
[REQUEST] Does toggling language between C and C++ need to reset the compiler and source window

### ISSUE THREAD

**Issue by topperc** [compiler-explorer/compiler-explorer#2740]
**Is your feature request related to a problem? Please describe.**
Sometimes I paste code in only to realize I need to change from C to C++ or vice versa after I've picked the compiler. Changing the language resets the compiler and source window. So the code needs to be pasted again and the compiler reselected.

**Describe the solution you'd like**
Don't reset them when toggling between C and C++.

**Describe alternatives you've considered**

**Additional context**

**Comment by mattgodbolt** [comment]
There's an option to globally prevent this (go to the settings and pick "Keep editor source on language change". Right now we don't want to have complex rules about what languages are and are not source "compatible"; and the lion's share of C++ programs are not in general valid C programs. Hope that helps!
