### ISSUE TITLE
[BUG] Swift syntax highlighter doesn't recognize `fileprivate` as a keyword

### ISSUE THREAD

**Issue by RedBeard0531** [compiler-explorer/compiler-explorer#2751]
**Describe the bug**
`private` and `fileprivate` are both protection level keywords and should be highlighted similarly, but aren't:

![image](https://user-images.githubusercontent.com/118456/123937886-eb3e9100-d996-11eb-9546-e1663968b8dd.png)

Compare:

```swift
fileprivate class Foo {}
    private class Bar {}
```

**Link**

https://swift.godbolt.org/z/Tdxa8v6e7

**Comment by supergrecko** [comment]
This appears to be an upstream problem as CE's Swift syntax highlighting is powered by monaco-languages.

You may want to report this upstream. https://github.com/microsoft/monaco-languages/blob/main/src/swift/swift.ts#L110

**Comment by partouf** [comment]
fix is now live
