### ISSUE TITLE
[BUG] Binary disassembly should use native opcode encoding.

### ISSUE THREAD

**Issue by Artem-B** [compiler-explorer/compiler-explorer#2760]
**Describe the bug**

Compiler explorer currently assumes that disassembled instruction opcode is represented as a sequence of space-separated bytes. https://github.com/compiler-explorer/compiler-explorer/blob/4c5e2f756ff28460344a1f6a8cf982d63be25bf3/lib/asm-parser.js#L69

However, this is not true for many of the non-x86 architectures. E.g. many RISC architectures use 32 or 16-bit instructions. GPUs use 32 or 64 bit ones. Forcing them all to produce byte arrays makes little sense. Trying to match disassembler output and then pretend that we've got it as bytes leads to special-cased code like this: https://github.com/compiler-explorer/compiler-explorer/blob/4c5e2f756ff28460344a1f6a8cf982d63be25bf3/lib/asm-parser.js#L567
To make things worse, that special case also reverses the order of bytes which actually makes it harder to make sense of the opcode. See the current/proposed screenshots below.

**To Reproduce**

https://godbolt.org/z/5eeoxcrf6

**Expected behavior**

opcode should be displayed as shown by disassembler which, presumably, has better idea of a reasonable representation for it.

**Link**

https://godbolt.org/z/5eeoxcrf6

Proposed changes that allow displaying native opcode as matched by `asmOpcodeRe`: https://github.com/compiler-explorer/compiler-explorer/pull/2759

**Screenshots**

Current output:
![image](https://user-images.githubusercontent.com/526795/124199504-e3124e80-da87-11eb-8540-72f3f793185b.png)
Proposed output:
![image](https://user-images.githubusercontent.com/526795/124199826-b7439880-da88-11eb-8f6d-bb50e20bd68d.png)

**Additional context**

Reviewer requested to open an issue for proposed output format change:
https://github.com/compiler-explorer/compiler-explorer/pull/2759#discussion_r662628960

**Comment by partouf** [comment]
Makes sense to me. Any objections? Pinging some NVidia and Cuda people for confirmation @benbarsdell @allisonvacanti @jlebar @jrhemstad

**Comment by jlebar** [comment]
I think tra is right, as usual.  (Two ways to read that.  I endorse both.  :)

**Comment by mattgodbolt** [comment]
I think this makes sense here too. Let's change to show the natural "instruction" as the disassembler interprets it.
