### ISSUE TITLE
[BUG] Error linking with {fmt} trunk

### ISSUE THREAD

**Issue by vitaut** [compiler-explorer/compiler-explorer#2765]
**Describe the bug**
There is an error linking with {fmt} trunk in https://godbolt.org/z/bEhjTefTs:

```
/opt/compiler-explorer/gcc-trunk-20210705/bin/../lib/gcc/x86_64-linux-gnu/12.0.0/../../../../x86_64-linux-gnu/bin/ld: /tmp/ccynZi2e.o: in function `main':
example.cpp:(.text+0x61): undefined reference to `fmt::v8::vprint(fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<fmt::v8::appender, char> >)'
collect2: error: ld returned 1 exit status
```

I was not able to repro it locally with the default {fmt} build config so wondering is it something specific to the how {fmt} is built in CE.

**Expected behavior**
The example builds and runs.

**Comment by partouf** [comment]
It seems the last build was on commit 427b53405442872decb69d9735db0fa64106ebe2 but the source is from yesterday, so those are inconsistent with each other.

I don't see any logging for failed builds with fmt trunk + gcc trunk, so I'm not sure... why it hasn't built...

It might be that there's another library that's blocking all other builds. Will need to investigate

**Comment by partouf** [comment]
This specific issue is now fixed. More fmt versions will be available tomorrow after our regular nightly build. Thanks for the bugreport!

**Comment by vitaut** [comment]
Thank you!
