### ISSUE TITLE
[BUG] Tab width ignored

### ISSUE THREAD

**Issue by dgazzoni** [compiler-explorer/compiler-explorer#2770]
**Describe the bug**
"Tab width" option in Settings is ignored when formatting code using Ctrl-F9 in source view.

**To Reproduce**
1. Open a new Compiler Explorer window (tried this in regular and incognito tabs, both on godbolt.org and on a local instance.)
2. Slightly modify the default "square" code to ensure it's not formatted to a single line:

```
// Type your code here, or load an example.
int square(int num) {
  int sqr = num * num;
  return sqr;
}
```

3. Verify in More -> Settings that "Tab width" is 4.
4. Press Ctrl-F9.

**Expected behavior**
Code should be indented with 4 spaces. However, it's indented with 2 spaces.

**Link**
Not sure it's necessary, but here it is anyway: https://godbolt.org/z/e8E7bGY1o

**Comment by RubenRBS** [comment]
Thanks for reporting the issue! We really need to overhaul this bit of code, but in the meanwhile, I can totally fix this! :)

**Comment by dgazzoni** [comment]
Perhaps this is common knowledge, but an easy fix would be to use the following command-line for `clang-format`:

```
clang-format --style="{BasedOnStyle: Google, IndentWidth: 4}" input_file.c
```

Obviously, the base style, indent width value and input file name can be changed to suit, but the important part is that a simple command-line flag is all that's required.

**Comment by FederAndInk** [comment]
The formatting also differs when we do F1 "format text" vs just hitting enter, if you have "Use spaces for indentation" unchecked.
leading to a mix of spaces and tabs :/

https://godbolt.org/z/oM1sbMoTE

![2021-07-19_19-17](https://user-images.githubusercontent.com/24270152/126200524-69e9f0f9-4214-45ff-9294-611e8d3486e2.png)
