### ISSUE TITLE
[BUG] Diff view seems broken

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2782]
Some reports that diff views are broken:

1. clicking diff view from a fresh incognito view (maybe?) creates two diff views
2. some weirdness found
![image](https://user-images.githubusercontent.com/633973/125532189-d09d1f00-6515-49b9-8dae-ba1127e71720.png)

(am working with the reporter to get more info)

**Comment by steverobb** [comment]
Here's an example of opening up a diff view in a brand new godbolt.org page and getting two diff windows:

![image](https://user-images.githubusercontent.com/7372208/125532540-0c37c134-b0dc-4e0f-8200-5b73589a60f9.png)
![image](https://user-images.githubusercontent.com/7372208/125532549-5e69d0d3-3f65-4d17-be45-e3a11d34d78d.png)
![image](https://user-images.githubusercontent.com/7372208/125532566-b2bf28d8-1b41-4b4d-aef9-6bf8fb1af64c.png)

**Comment by mattgodbolt** [comment]
To confirm did you "click" the "Add DIff view" or drag it?

**Comment by steverobb** [comment]
I clicked.

**Comment by mattgodbolt** [comment]
Thanks! Super weird...we'll try and see if we can repro. Cheers!

**Comment by RubenRBS** [comment]
Can repro, but dragging:

https://user-images.githubusercontent.com/5364255/125534370-fb647351-9f91-4403-babd-97823add1fc5.mp4

**Comment by jeremy-rifkin** [comment]
I think the diff view is in need of some love in general. Some day soon. But the issues described appear resolved for now at least.
