### ISSUE TITLE
[LIB REQUEST] libsimdpp

### ISSUE THREAD

**Issue by yumeyao** [compiler-explorer/compiler-explorer#2783]
**Library name:**
libsimdpp

**Library description:**
Portable header-only C++ low level SIMD library

**Library repository:**
https://github.com/p12tic/libsimdpp

**Library homepage:**
https://github.com/p12tic/libsimdpp

**Motivation:**
handy for writing SIMD code and checking the assembly results as typing.  
* The lib targets zero-overhead low-level SIMD programming and also comes with support for mid-level vectors (vectors longer than native types).
* The lib is well documented.
* The lib itself is header-only, so it's easy for install. On the other way, it consists of a lot of files, making it difficult to copy-n-paste into the source directly.
* However, the lib lacks of intuitive simple examples. What lays inside its `example` directory is an example for an advanced feature **dynamic dispatching**.

**Comment by RubenRBS** [comment]
Hi! Thanks for taking the time to open such a detailed request :)
I'll get this done before the weekend ends
