### ISSUE TITLE
[BUG] Used branches mistakenly filtered out

### ISSUE THREAD

**Issue by PikalaxALT** [compiler-explorer/compiler-explorer#2788]
**Describe the bug**

When using an ARM gcc version and filter "Unused labels", the code example under heading "Link" below generates a switch table but the destination branches are mistakenly filtered out.

**To Reproduce**

Write C or C++ code which includes a switch statement that outputs a branch table, and compile using ARM gcc 10.2.1.

**Expected behavior**

Labels .L4, .L6, .L7, and .L8, which are assembled, should not be filtered out. Labels should appear before lines 62, 82, 95, and 108 in the filtered output.

**Link**

https://godbolt.org/z/6sdjKzGrj

**Screenshots**

Switch case begins after the unconditional `b` instruction, but label is filtered out.
![image](https://user-images.githubusercontent.com/1895773/126015461-0df4da6b-b115-4ee7-839f-3215ff19367c.png)

**Additional context**

**Comment by RubenRBS** [comment]
Hi! Thanks for the report. This seems to be more complex than it looks at first glance. I don't see a way to fix this for the general case, but maybe someone that knows better can prove me wrong :)

**Comment by mattgodbolt** [comment]
I initially thought it was a jump table thing, but interestingly you can see that the jump table is _not_ filtered. It has references to `L8` et al, but _they aren't underlined_ which means we found them but didn't think they were useful! I'll have to dig a bit deeper, @RubenRBS your instinct is right I think...

**Comment by mattgodbolt** [comment]
so! Interestingly it seems like it's the directives filter that's involved. I can't see how yet but disabling the directives filter means that even with the "unused label"  on we see `L7` et al. That leads me to think the only "root" references to L7 are believed to come from directives. but I can't see that being the case. More to investigate here for sure.

**Comment by mattgodbolt** [comment]
Minimal repor, compile with -O3 -mthumb-interwork
```cpp
char revc(char c) {
  switch (c) {
    case 'A':
      return 'T';
    case 'C':
      return 'G';
    case 'G':
      return 'C';
    case 'T':
      return 'A';
    default:
      return c;
  }
}
```

**Comment by mattgodbolt** [comment]
So; it's a bug in our handling of jump tables. We don't "know" the `.word` definitions are reachable. If you compile using `clng`, you'll see it `adr`'s `r3` to the beginning of the jump table, instead of relying on the (implied) `pc`.

**Comment by mattgodbolt** [comment]
The fix for this is now live
