### ISSUE TITLE
[BUG] Automatic closing single-quotes is bad for Rust lifetimes

### ISSUE THREAD

**Issue by kupiakos** [compiler-explorer/compiler-explorer#2799]
**Describe the bug**
When typing a single `'` in a Rust source, the Compiler Explorer editor "helpfully" adds another ending quote to make it `''`. Rust lifetimes are expressed with a single quote, such as `'a`. So, every time you type a lifetime, you need to remove the automatically created extra quote. This ends up being extremely irritating when prototyping.

**To Reproduce**
Open a Rust source, type `struct Foo<'a, T>`, and it will end up as `struct Foo<'a, T>'`

**Expected behavior**
No automatic closing quote should be created for lifetimes, so it should simply remain as `struct Foo<'a, T>`. Unless the editor is context-aware enough, I'd suggest that auto-inserting a closing single quote be completely disabled for Rust sources.

**Comment by RubenRBS** [comment]
Hi! Thanks for the report. Unfortunately, this is an issue with the Monaco Editor itself. We might be able to path things somewhat locally, but only an upstream fix would totally adress this (IF it can be done!)

Historically, we have tested possible fixes and then sent upstream patches, but I'm not confident enough in my Rust-fu to know where the lifetime quote can appear, so I can't confidentily patch it. I could try if someone points me in the right direction though.

For anyone brave enough to try for themselves, https://github.com/microsoft/monaco-languages/blob/main/src/rust/rust.ts#L22 specifies when not to autocomplete.

**Comment by partouf** [comment]
fix is now live
