### ISSUE TITLE
[BUG] Inconsistent font sizing between Output panels

### ISSUE THREAD

**Issue by lunasorcery** [compiler-explorer/compiler-explorer#2800]
**Describe the bug**
In some situations, the Output panel may use either pt-based or px-based font sizing, sometimes varying between panels on the same page. 

**To Reproduce**
- Open Compiler Explorer and Reset the code & UI layout.
- Open the Compiler's Output panel. This panel's font size will default to '14' in the UI - this is treated as 14***pt***.
- Refresh the page, or grab a shareable link and visit it - either will do. We just want to reload the UI from a serialized state.
- Observe that the font size in the Output panel is smaller than before - it's still '14' in the UI, but is now treated as 14***px***.
- Add a second Compiler, and open its Output panel. The UI will again report a font size of '14'.
- Observe that this new panel's text is larger than the first panel's text, as this new panel is using 14***pt***.

**Expected behavior**
Font sizing should be consistent across all panels, regardless of whether they've been freshly created or loaded from a serialized state.

**Additional context**
See also some tangentially-related prior discussion about whether the Output panel should be in px or pt at #2457.

**Screenshots**
First Output panel:
<img width="1277" alt="Screen Shot 2021-07-23 at 18 16 28" src="https://user-images.githubusercontent.com/2166769/126818270-2641b301-da9e-4c91-86b0-7fae7bfd6fc6.png">

First Output panel after reloading the page:
<img width="1277" alt="Screen Shot 2021-07-23 at 18 16 35" src="https://user-images.githubusercontent.com/2166769/126818283-acfe8f4e-9b3a-40de-85ab-e68bef5e8d79.png">

Post-reload Output panel (left) and new Output panel (right):
<img width="1277" alt="Screen Shot 2021-07-23 at 18 16 48" src="https://user-images.githubusercontent.com/2166769/126818288-67b1f898-1bf5-4c37-862b-c21cad31dfcd.png">

**Comment by partouf** [comment]
Thanks for filing this issue, I've seen this quite consistently before and it should probably be fixed.

**Comment by RubenRBS** [comment]
Hi! Thanks for your detailed report, it was very helpful in finding what was wrong :)
The font code did not correctly check for new panes and didn't set the px units until after a refresh, as I missed that when initially making the pt -> px change
