### ISSUE TITLE
[BUG] Compiler output is on wrong line after #if false #include "http"

### ISSUE THREAD

**Issue by Alcaro** [compiler-explorer/compiler-explorer#2803]
The frontend will replace #include "https://example.com/stdio.h" with the file's contents, surrounded with #line directives.

If the #include is in a #if false, the #lines will be ignored, and line numbers in the compiler output won't correspond to the input file, which will give not-quite-expected results.

https://godbolt.org/z/T57Trshx4

![image](https://user-images.githubusercontent.com/5085186/126848843-46f75c59-5078-4f5a-bdce-316ebf44d7b5.png)

Proposed fix: If the input contains a #include "http", add a #line after every #endif, #else, #elif, #elifdef and #elifndef in the file. (It's only necessary to add #line if any prior part of that #if contains a #include "http", but such a thing would be more complicated for little if any benefit.)

Found while researching #2802.

e: pasted wrong link, fixed

**Comment by OfekShilon** [comment]
This doesn't reproduce, can be safely closed.

**Comment by Alcaro** [comment]
Yep, it's been fixed at some point in the last two years

**Comment by partouf** [comment]
It was fixed when the http inclusion was changed to a new api with separate files instead of putting it inline https://github.com/compiler-explorer/compiler-explorer/pull/4602
