### ISSUE TITLE
[REQUEST] Add color scheme with colors for dark mode

### ISSUE THREAD

**Issue by philnik777** [compiler-explorer/compiler-explorer#2810]
I like the dark mode, but I really hate the gray shades, because it is really hard for me to distinguish them. It would be quite nice if it was possible to use some dark colors instead.

**Comment by partouf** [comment]
If you have some examples or color suggestions, they are welcome

**Comment by philnik777** [comment]
Visually I can't tell if asm lines 20-25 belong to c++ line 17 or 13 here: https://godbolt.org/z/45d6nP5PE. I'll try some colors and try to add a PR later.
