### ISSUE TITLE
[BUG] Problem with MOVBE opcode

### ISSUE THREAD

**Issue by yumeyao** [compiler-explorer/compiler-explorer#2819]
**mov** **b**ig **e**ndian

https://www.felixcloutier.com/x86/movbe

**Comment by RubenRBS** [comment]
Hi! Thanks for the report. We're aware that this instruction is missing from the tooltips (https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/scripts/docenizer.py#L89) I'll see if the issue is resolved so that we can add it :)

**Comment by yumeyao** [comment]
gcc/clang will generate it with -mmovbe, or with -march=haswell or above.
