### ISSUE TITLE
Circle intel asm is greyed out

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2826]
Darn it: I just deployed to our staging instance and it's not working. 
![Screenshot from 2021-07-29 07-58-27](https://user-images.githubusercontent.com/633973/127496343-5f4df70d-582e-4bac-8cd8-b8e32ad8f25a.png)
...I'll dig in to this a bit later...

_Originally posted by @mattgodbolt in https://github.com/compiler-explorer/compiler-explorer/issues/2824#issuecomment-889121920_

**Comment by partouf** [comment]
https://github.com/compiler-explorer/compiler-explorer/pull/2824/files#diff-73e01c5f919577be2972b1217e8c1a320c89c9bd0cbf8fda97b50ff154050bfeR7
was defined in defaults, but defaults groups are not used here
