### ISSUE TITLE
[BUG] Uncaught TypeError: t is undefined

### ISSUE THREAD

**Issue by Storyyeller** [compiler-explorer/compiler-explorer#2835]
Apart from the privacy policy popup, the editor is completely blank, rendering the site unusable. The dev console shows the following error:

Uncaught TypeError: t is undefined
    I main.js:132
    R main.js:143
    jQuery 7
    NWa+/</< main.js:316
    NWa+/< main.js:536
    jQuery 2
    n helpers.ts:87

**To Reproduce**

1. Visit https://godbolt.org/
2. Click "close" on the privacy popup
The site is completely broken

I'm using Firefox 89.0 in case that helps.

**Comment by partouf** [comment]
Thanks! Missed this one with testing

**Comment by partouf** [comment]
Fix is live
