### ISSUE TITLE
[REQUEST] Support sandbox.cfg.local and execute.cfg.local nsjail configs

### ISSUE THREAD

**Issue by mhammerly** [compiler-explorer/compiler-explorer#2845]
**Is your feature request related to a problem? Please describe.**
The nsjail configuration files included in the repo don't fully match the environment of the CE instance I maintain and it'd be a little tidier if we could keep our customization separate.

**Describe the solution you'd like**
Similar to the service and language configuration files, a .local file that is `.gitignore`d and prioritized over the stock ones would probably suit us fine.

**Additional context**
If nobody beats me to it I'll come back and do it one day. Could be a good first issue for someone new looking to contribute?

Thanks for converging on nsjail, by the way! Made my life easier :)

**Comment by RubenRBS** [comment]
Hi! Thanks for the request, it's a super good idea that I hope we can implement.

Sadly, it's not one that I think would qualify as `good first issue`, as it might not be too easy to do.
The relevant code is at https://github.com/compiler-explorer/compiler-explorer/blob/a031ef9047b16b652d1f291979450dad63c7abf1/lib/exec.js#L154 , but I'm not too sure how we would handle the hierarchy.

**Comment by apmorton** [comment]
it may be simpler to implement options in [`execution.properties`](https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/execution.defaults.properties)

```
nsjailConfigExecution=etc/nsjail/execute.cfg
nsjailConfigSandbox=etc/nsjail/sandbox.cfg
```

**Comment by RubenRBS** [comment]
This is now in the latest commit @mhammerly 
You can now create a `etc/config/execution.local.properties` file and set replace the values of
```
nsjail.config.execute=etc/nsjail/execute.cfg
nsjail.config.sandbox=etc/nsjail/sandbox.cfg
```
as needed :)
