### ISSUE TITLE
[BUG] OCaml compiler fails due to unrecognized -L flag

### ISSUE THREAD

**Issue by hyphenrf** [compiler-explorer/compiler-explorer#2848]
`4.12.0+flambda` does not understand the `-L.` library flag apparently added by default.  
I looked into the compiler configuration here in this repo but wasn't sure where to _remove_ a flag. Hence an issue, not a PR.

Compiler output:
```
/opt/compiler-explorer/ocaml-4.12.0-flambda/bin/ocamlopt: unknown option '-L.'.
Usage: ocamlopt <options> <files>
Options are:
   ...
```

**Comment by partouf** [comment]
You'll need an override for `getSharedLibraryPathsAsArguments()` - implemented in base-compiler.js
https://github.com/compiler-explorer/compiler-explorer/blob/39aac5341b1f36f3d27fbdbb5ba3b9828391e60d/lib/base-compiler.js#L432

And add it to https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/compilers/ocaml.js
It mostly likely should just `return []`
