### ISSUE TITLE
[REQUEST] LLVM-MOS Support

### ISSUE THREAD

**Issue by Serentty** [compiler-explorer/compiler-explorer#2859]
It would be neat to be able to use [LLVM-MOS](https://github.com/llvm-mos/llvm-mos) to see generated 6502 code, since that's a platform where micro-optimization matters the most. It's just an LLVM fork, so I think it should be easy to integrate.

**Comment by johnwbyrd** [comment]
Done https://github.com/llvm-mos/llvm-mos/issues/253

**Comment by RubenRBS** [comment]
This is now live
