### ISSUE TITLE
[BUG] Syntax highlighting missing for std::atomic_flag test_and_set xchg instruction

### ISSUE THREAD

**Issue by SrivastavaAnubhav** [compiler-explorer/compiler-explorer#2861]
**Describe the bug**
The test_and_set function of std::atomic_flag only highlights the `test` and `je`, not the `mov`, `xchg`, or `nop`.

**To Reproduce**
Compile the following program with x86-64 gcc 11.2.
```
#include <atomic>

int test() {
    std::atomic_flag flag;
    if (flag.test_and_set()) {
        return 1234;
    }
    return 0;
}
```
Note that the `mov`, `xchg`, and `nop` (which are all part of the test_and_set) are not highlighted.

**Expected behavior**
The `mov`, `xchg`, and `nop` (and I think the `lea` before as well, but I'm not sure) should be highlighted as coming from `test_and_add`.

**Link**
https://godbolt.org/z/jsWe1jMr6

**Screenshots**
![image](https://user-images.githubusercontent.com/17299377/129839338-d0ef4e47-a561-4304-9b64-574e3b96ecaa.png)

**Comment by partouf** [comment]
Those lines are annotated by the compiler as being part of `atomic_base.h` - so this is intended behaviour.

**Comment by SrivastavaAnubhav** [comment]
I see, thanks. Is there a workaround? A way to enable highlighting any library code my code calls as well?

**Comment by mattgodbolt** [comment]
I'm afraid not: the compiler is telling us those lines correspond to a part of the code that you didn't write. You'd see the same in the debugger if you were to step onto those instructions: the debugger woudl say those instructions correcspond to atomic_base.h. We're sorry - we can only display the information the compiler gives us. If you turn off the "Directives" filter (https://godbolt.org/z/4G6aon9vc) you can see that all we get to work with is the `.loc` things the compiler inserts in the output:

```asm
        .file 2 "/opt/compiler-explorer/gcc-11.2.0/include/c++/11.2.0/bits/atomic_base.h"
        .loc 2 205 37
        lea     rdx, [rbp-5]
        .loc 2 205 36
        mov     eax, 1
        xchg    al, BYTE PTR [rdx]
        .loc 2 205 52
        nop
```

**Comment by SrivastavaAnubhav** [comment]
Ah ok, that makes sense. Thanks for the explanation!
