### ISSUE TITLE
[LIB REQUEST] DAW JSON Link

### ISSUE THREAD

**Issue by beached** [compiler-explorer/compiler-explorer#2864]
**Library name:**
DAW JSON Link

**Library description:**
Fast JSON serialization and parsing in C++ with declarative mappings

**Library repository:**
https://github.com/beached/daw_json_link/

**Library homepage:**

**Motivation:**
It would be nice to explorer the code generated on multiple platforms/compilers

The library is header only and pulls in two other of my header libraries via FetchContent.  This can be done manually too via 3 git clones and copy/merge the include folder from each.  cmake with an install prefix handles all this.  There are examples that would test it working too, but here is a small test 

```
#include "daw/json/daw_json_link.h"

#include <cassert>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <string>

namespace daw::cookbook_class1 {
	struct MyClass1 {
		std::string member_0;
		int member_1;
		bool member_2;
	};
} // namespace daw::cookbook_class1

namespace daw::json {
	template<>
	struct json_data_contract<daw::cookbook_class1::MyClass1> {
		static constexpr char const member0[] = "member0";
		static constexpr char const member1[] = "member1";
		static constexpr char const member2[] = "member2";
		using type =
		  json_member_list<json_string<member0>, json_number<member1, int>,
		                   json_bool<member2>>;
		static inline auto
		to_json_data( daw::cookbook_class1::MyClass1 const &value ) {
			return std::forward_as_tuple( value.member_0, value.member_1,
			                              value.member_2 );
		}
	};
} // namespace daw::json

int main( ) {
	std::string_view data = R"( 
{
  "member0": "this is a test",
  "member1": 314159,
  "member2": true
}
	)";	
	auto const cls = daw::json::from_json<daw::cookbook_class1::MyClass1>(
	  std::string_view( data.data( ), data.size( ) ) );

	assert( cls.member_0 == "this is a test" );
	assert( cls.member_1 == 314159 );
	assert( cls.member_2 == true );
	std::string const str = daw::json::to_json( cls );
	puts( str.c_str( ) );

	auto const cls2 = daw::json::from_json<daw::cookbook_class1::MyClass1>(
	  std::string_view( str.data( ), str.size( ) ) );
	(void)cls2;
}
```
clang or gcc(suggest clang >= 8 or gcc >= 9)
`clang++ -std=c++17 -I /path/to/includes thisfile.cpp`
`./a.out`

**Comment by RubenRBS** [comment]
Hi! Thank you for taking the time to request the library, and sorry that it took so long to get back to you.

I've made the necessary changes to get the library (Both a trunk version updated daily and the last available release, 2.9.11) into the site, but it will take some time until it shows up as we need to push the new version to the site :)
