### ISSUE TITLE
[REQUEST] Zero-based line numbering, may be?

### ISSUE THREAD

**Issue by u07** [compiler-explorer/compiler-explorer#2867]
Hi! I believe the output line numbering should start from zero. Cause that's how commands are addressed in assembler. See the screenshot:

![image](https://user-images.githubusercontent.com/20968145/130404475-8bee51f3-0571-4603-a306-6740ef3c9aa0.png)

**Describe the solution you'd like**

Start counting from "0" in ASM output only, or in any output.

**Comment by partouf** [comment]
The numbers after the jmp's are not line-numbers, they are addresses which depend on opcodesize and alignment, etc. Labels also do not take up any address size.  So I don't think it would make much sense to try and relate them to line numbers.

**Comment by u07** [comment]
Right, you're right.. my bad, sorry)
