### ISSUE TITLE
[BUG] Conformance Viewer uses `skipAsm` incorrectly

### ISSUE THREAD

**Issue by cpplearner** [compiler-explorer/compiler-explorer#2883]
**Describe the bug**
While reading https://github.com/compiler-explorer/compiler-explorer/blob/main/static/panes/conformance-view.js, I noticed that the `skipAsm` is misplaced in https://github.com/compiler-explorer/compiler-explorer/blob/a2a73953d6a23eaaab9ac724b7947317dc6e4471/static/panes/conformance-view.js#L314-L326.

`skipAsm` is only effective as a field of `compilerOptions`, but here it's specified as a field of `options`. As is, it doesn't prevent the generation of assembly output.

This does not do any harm, other than causing a little bit more network traffic when using the conformance viewer.

**To Reproduce**
1. Open DevTools and switch to Network panel
2. Go to https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:4,positionColumn:2,positionLineNumber:4,selectionStartColumn:2,selectionStartLineNumber:4,startColumn:2,startLineNumber:4),source:'//+Type+your+code+here,+or+load+an+example.%0Aint+square(int+num)+%7B%0A++++return+num+*+num%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:37.5,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:conformance,i:(compilers:!((compilerId:arm64gtrunk,options:'')),editorid:1,langId:c%2B%2B,libs:!()),l:'5',n:'0',o:'Conformance+Viewer+(Editor+%231)+1/10',t:'0')),k:62.5,l:'4',n:'0',o:'',s:1,t:'0')),l:'2',m:100,n:'0',o:'',t:'0')),version:4
3. Notice that assembly output is included in the response

**Expected behavior**
either no assembly output, or `skipAsm` is not sent and assembly output is included

**Comment by partouf** [comment]
Excellent find. Thanks for investigating!
