### ISSUE TITLE
Library code filtered out of function (gcc11.2)

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2884]
Today stumbled on the same issue in "normal" c++ code(no manual__asm__ or .quads) that ​uses std::copy in for loop: 
https://godbolt.org/z/vGcnWM575

    ​for(int i = 0; i < arr[0]; i++)    
        ​std::copy(&arr[i-1],&arr[i],&arr[i]); 

in gcc 11.2 -O3 there is `jg .L2`, but .L2 is gone.

_Originally posted by @Maykeye in https://github.com/compiler-explorer/compiler-explorer/issues/2323#issuecomment-907619226_

**Comment by partouf** [comment]
#2891

**Comment by mattgodbolt** [comment]
Oh sorry @partouf I didn't spot this :blush: - I'm going backwards through emails. You should have closed _my_ bug as the duplicate (and then sent me a sarcastic DM :D )
