### ISSUE TITLE
Make Fortran work with CMake

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2885]
[I found this template repo](https://github.com/SethMMorton/cmake_fortran_template)

You can set the language with `PROJECT(<project-name> Fortran)`. The compiler can be set using the `FC` environment variable. Otherwise it works basically like CMake for C++. Most CMake variables with "CXX" should also have a corresponding  "Fortran" one.

I couldn't find where something like this is tested in this repo. If I can look at what you test for C++ then I can probably be more helpful.

_Originally posted by @bcornille in https://github.com/compiler-explorer/compiler-explorer/issues/2879#issuecomment-907480557_

**Comment by bcornille** [comment]
Should this be live on the site? The CMake checkbox is grayed out for me with Fortran selected. Does it take time to deploy? If so how long?

**Comment by partouf** [comment]
no, not yet. It requires manual deployment, I'll do it in a few hours probably, otherwise tomorrow

**Comment by partouf** [comment]
This is now live

Note that the example repo you linked doesn't fully work out of the box.
