### ISSUE TITLE
Incorrectly filtered label

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2891]
> Today stumbled on the same issue in "normal" c++ code(no manual__asm__ or .quads) that ​uses std::copy in for loop:
> https://godbolt.org/z/vGcnWM575
> 
> ```
> ​for(int i = 0; i < arr[0]; i++)    
>     ​std::copy(&arr[i-1],&arr[i],&arr[i]); 
> ```
> 
> in gcc 11.2 -O3 there is `jg .L2`, but .L2 is gone.

That's a bug that we can actually fix for sure. I'll make sure that we do.

_Originally posted by @partouf in https://github.com/compiler-explorer/compiler-explorer/issues/2323#issuecomment-907619556_

**Comment by partouf** [comment]
should now be fixed
