### ISSUE TITLE
[BUG] IDE mode: Unnamed excluded files disappear on refresh

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2893]
**Describe the bug**

When loading or reloading a page with an unnamed excluded pane, the excluded pane disappears until you interact with a named pane.

**To Reproduce**
* Reset UI
* Add a tree view
* Note there's a "C++ source #1" in the excluded list
* Reload the page with ctrl-R
* Note the layout is OK but the Excluded file list is now empty.
* Now "add new source editor"
* Note that both C++ source #1 *and* C++ source #2 have appeared in the output.

**Expected behavior**

The C++ source #1 should remain there on a reload.

**Comment by partouf** [comment]
Confirmed.. interesting.. most likely an Event order thing somehow. The good thing is that the information is not lost, I guess

**Comment by jeremy-rifkin** [comment]
This appears corrected now
