### ISSUE TITLE
[BUG] Missing assembly lines in C++ x86-64 clang output

### ISSUE THREAD

**Issue by Christoph-D** [compiler-explorer/compiler-explorer#2898]
**Describe the bug**
Some C++ code compiled with x86-64 clang (different clang versions) is missing some assembly lines. Unchecking "Filter > Library functions" in the output pane mitigates the issue.

**To Reproduce**
1) Enter this C++ code, compile with x86-64 clang 12.0.1 `-O3 -std=c++17`:

```
#include <string_view>
int foo(const std::string_view& s) { return s[0]; }
```

2) Observe the incomplete output:

```
        movsx   eax, byte ptr [rax]
        ret
```

3) In the compiler pane, disable "Filter > Library functions". The output now matches the expected behavior below.

**Expected behavior**
I expect three assembly lines for this function:

```
        mov     rax, qword ptr [rdi + 8]
        movsx   eax, byte ptr [rax]
        ret
```

**Link**
https://godbolt.org/z/ba5dsTvsW

**Additional context**
This bug does not happen with gcc, only with clang.

**Comment by DenisYaroshevskiy** [comment]
Another example:

This is the expected result:
cvt:
    vpmovsxwd	ymm0, xmm0
	ret
Here is what I see:
https://godbolt.org/z/T3GGbrWrM
        ret
It seems to be filtered with comments:
        vpmovsxwd       ymm0, xmm0
        #DEBUG_VALUE: cvt:x <- [DW_OP_LLVM_entry_value 1] $xmm0
        ret

**Comment by partouf** [comment]
this issue should now be fixed
