### ISSUE TITLE
[BUG] IDE mode: "main" considered a library function

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2903]
In this link: https://godbolt.org/z/sTvzqzTbP - the non-LTO version at the top right is missing the `main:` to show the main. toggling "library mode" shows it up.

**Comment by partouf** [comment]
Interesting, feels like the same problem as the one fixed in https://github.com/compiler-explorer/compiler-explorer/commit/9d382eb03e1ebddea4c51d79f0a0ee2fa12a67da - but in the objdump bits

**Comment by partouf** [comment]
the code looks ok, will have to reproduce the dump to try and fix

**Comment by partouf** [comment]
I'm confused.. I deleted the working compiler, made a full link, copied to local environment, dumped the file, made a unittest for this.. and... it works fine? but not in CE itself.. what's the difference..

**Comment by partouf** [comment]
See https://github.com/compiler-explorer/compiler-explorer/commit/222bc8765c3c88607a731ee22cee7b2ae34711f7#diff-34ed6442a447d1b7b9404337c5fe103ed802f94c43f3f2262654b441ca3b0dcd

**Comment by partouf** [comment]
ahh maybe its binaryHideFuncRe doing weird things to it? that's not set in the unittests i think

**Comment by partouf** [comment]
yes that does the trick

**Comment by partouf** [comment]
Fix is now live
