### ISSUE TITLE
[BUG] Excluded source in IDE mode lose colourization after a refresh

### ISSUE THREAD

**Issue by RubenRBS** [compiler-explorer/compiler-explorer#2909]
**Describe the bug**

If you have an excluded source file with the tree mode opened and refresh the page, no linked line colourization is visible

**To Reproduce**

On a new state (So, 1 source and its compiler), add an IDE mode. The source appears ok as an excluded file.
Refresh the page. No colourization is visible

**Expected behavior**

The colours should still be visible. The information is still there as hovering the mouse over the lines still highlight their linked counterparts.

This might be releated (If not a duplicate) of #2893

**Comment by partouf** [comment]
I'm a little confused. If it's excluded from the project, it won't be compiling with that source. Perhaps the confusion here is that excluding doesn't trigger a recompilation?

**Comment by jeremy-rifkin** [comment]
I think this might have been the same as #3059, and maybe #3245. Resolved now though.
