### ISSUE TITLE
[BUG] Format adds spaces in urls with //

### ISSUE THREAD

**Issue by Sebanisu** [compiler-explorer/compiler-explorer#2928]
**Describe the bug**

I think format thinks urls have comments in it. So if you click format it adds a space before the //
**To Reproduce**

Right click and click format.

**Expected behavior**

Spaces aren't added to urls.
**Link**

before format ::
https://godbolt.org/z/x13vxoTnj
after format:
https://godbolt.org/z/rj7czceb9

**Screenshots**

**Desktop**

 - OS: 
 windows 10
 - Browser 
 chrome
 - Version 
93.0.4577.63
**Additional context**

**Comment by supergrecko** [comment]
This behavior is due to clang-format lexing the code as a comment.

Potential workarounds include substituting any URL includes before sending it off to the formatting API and appending them after.
