### ISSUE TITLE
[BUG] Conformance button to add specific compilation sometimes adds different compiler

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2929]
https://godbolt.org/z/vhW8n1zeM

The first time you click on the MSVC compiler, the MSVC compiler is brought up.
The second time, the default gcc 11.2 compiler is shown instead of the MSVC compiler.

**Comment by RubenRBS** [comment]
I can't repro, but probably because I'm doing something wrong.

**Comment by partouf** [comment]
Can't anymore either. Maybe it was a moment where MSVC compilers were offline?

**Comment by partouf** [comment]
Ok, no it's not that.

It seems that sometimes the compiler id is empty
![image](https://user-images.githubusercontent.com/442630/132963130-8a9568f7-5994-4079-9073-c9e628c436d9.png)
