### ISSUE TITLE
[LIB REQUEST] magic_enum

### ISSUE THREAD

**Issue by andrewkcorcoran** [compiler-explorer/compiler-explorer#2933]
**Library name:** magic_enum

**Library description:** Header-only C++17 library provides static reflection for enums, work with any enum type without any macro or boilerplate code.

**Library repository:** https://github.com/Neargye/magic_enum

**Library homepage:** https://github.com/Neargye/magic_enum

**Motivation:** Easier testing of code which uses enums.

**Extra:**
```cpp
enum class Color { RED = 2, BLUE = 4, GREEN = 8 };

Color color = Color::RED;
auto color_name = magic_enum::enum_name(color);
// color_name -> "RED"

std::string color_name{"GREEN"};
auto color = magic_enum::enum_cast<Color>(color_name);
if (color.has_value()) {
  // color.value() -> Color::GREEN
}
```

**Comment by RubenRBS** [comment]
Hi! Sorry that we took so long to get back to you.
I've now made the necessary changes to add the library to the site, and it should be live "Soon":tm: :)
