### ISSUE TITLE
[BUG] Rename "CUDA" to "CUDA C++"

### ISSUE THREAD

**Issue by brycelelbach** [compiler-explorer/compiler-explorer#2934]
I'm not sure if this is the right place to report this, but right now the language mode for CUDA C++ on the compiler explorer website is listed as just "CUDA". Can this be changed to "CUDA C++", which is a bit more accurate, and makes it clear what language we're talking about? "CUDA" is a platform, not a specific language; there's "CUDA C++", "CUDA Fortran", "CUDA Python", etc.

**Comment by mattgodbolt** [comment]
Sounds like a decent rename! I'd be 100% up for this; thanks for filing!
