### ISSUE TITLE
[COMPILER REQUEST] Remove obsolete development branch of gcc static analyzer

### ISSUE THREAD

**Issue by davidmalcolm** [compiler-explorer/compiler-explorer#2937]
In https://github.com/compiler-explorer/compiler-explorer/issues/1691 I requested adding what was then the experimental GCC static analyzer branch.

I implemented this for Compiler Explorer in:
  https://github.com/compiler-explorer/compiler-explorer/pull/1712
and:
  https://github.com/compiler-explorer/infra/pull/288

I merged the code from the gcc branch into gcc trunk for gcc 10, and the branch is now obsolete.

This is confusing to users; see e.g.:
  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102328
and is wasting compilation cycles in your infrastructure (sorry).

This could be solved by removing the daily build of the obsolete branch, and either:

1. removing the option from the UI altogether
2. making the option merely add "-fanalyzer" to the regular gcc

I'm not sure which of these is the better option.

**Comment by partouf** [comment]
I will hide the compiler and disable the build first. Then we can decide if we want a different entry for analyzer.. I don't think we do.

**Comment by partouf** [comment]
the compiler is now hidden

**Comment by davidmalcolm** [comment]
Thanks; I've updated that GCC bug accordingly.
