### ISSUE TITLE
Objective-C support for GCC

### ISSUE THREAD

**Issue by apinski-cavium** [compiler-explorer/compiler-explorer#2942]
**Compiler name:**
This is not really a new compiler request but rather a request to add Objective-C support for x86_64 GCC.

**Compiler version:**
GCC trunk is enough for now.

**Compiler language:**
Objective-C (and Objective-C++)

**Compiler homepage:**
gcc.gnu.org :)

**Motivation:**
It would be useful to test Objective-C with different versions of GCC.

**Comment by MosheBerman** [comment]
+!

**Comment by dkm** [comment]
Should be easy, I'll take care of that :)

**Comment by dkm** [comment]
@MosheBerman do you know of any logo for both langs?

**Comment by MosheBerman** [comment]
Nope. Pretty sure ObjC doesn’t have one. Mayyyybe square brackets around ObjC or something. Sent from my iPhoneOn Sep 21, 2022, at 4:14 PM, Marc Poulhiès ***@***.***> wrote:﻿
@MosheBerman do you know of any logo for both langs?

**Comment by dkm** [comment]
ok, I'll leave it without any logo then :)
While doing objc, I was also planning on enabling objc++... but I'm not even sure that's a real language and not only a GCC extension. There's no syntax highlighting support in our editor and picking objective-c or c++ instead is probably not a good idea as it won't cover the interesting part (objc + c++). I'm thinking of not supporting it, unless someone asks for it. @apinski-cavium @MosheBerman what do you think ?

**Comment by mattgodbolt** [comment]
Just registering I had seen some interest in adding Objective-C via Slack

**Comment by dkm** [comment]
Fixed and this is now live :rocket:
