### ISSUE TITLE
[BUG] fmt "trunk" isn't "trunk" for MSVC

### ISSUE THREAD

**Issue by roman-orekhov** [compiler-explorer/compiler-explorer#2954]
https://godbolt.org/z/xbveGx13x

Both gcc 11.2 and MSVC v19.29 VS16.11 are set to use `fmt` trunk version, but disassembly shows `v8` namespace for gcc (suggesting the use of `fmt 8.0`) and `v7` for MSVC.

Maybe it should be possible to report actual library version (from the likes of `#define FMT_VERSION`) for any library so that such errors are caught easier? E.g. were I to use Compiler exporer just to run the code (and should it be non-erring) I wouldn't see that different versions were picked.

**Comment by partouf** [comment]
The list of libraries is actually bugged in this case.
But unfortunately for the MSVC compilers all libraries are available to include without having to select the library, so no actually noticed before this. And thus reporting library versions wouldn't help here either.

**Comment by partouf** [comment]
Was fixed a while ago (MS compilers now only have the versions that they actually have (and they dont have trunk))
