### ISSUE TITLE
[REQUEST] ctrl-d for line duplication

### ISSUE THREAD

**Issue by xTachyon** [compiler-explorer/compiler-explorer#2955]
**Is your feature request related to a problem? Please describe.**
Some IDEs, like Visual Studio, let the user duplicate a line with ctrl-d. I got quite used to it and it would be nice to be able to use it on CE too.

**Describe the solution you'd like**
Have ctrl-d do line duplication by default.

**Describe alternatives you've considered**
Have a way map ctrl-d to do line duplication.

**Comment by mattgodbolt-molty** [comment]
Heads-up: PR #8682 makes this keymap-configurable. The unconditional `Ctrl+D` → duplicate-selection binding was clobbering VS Code's multi-cursor (`editor.action.addSelectionToNextFindMatch`), which is the more widespread expectation, so the new default is **VS Code keymap** — multi-cursor stays, no more duplicate-on-Ctrl+D.

If you want the original behaviour back, switch **Settings → Keybindings → Keymap** to **JetBrains** and refresh; you'll get `Ctrl+D` → duplicate selection plus `Ctrl+Y` → delete line and `Ctrl+Shift+/` → block-comment as a bonus (with the matching `Cmd+Backspace` / `Option+Cmd+/` on macOS).
