### ISSUE TITLE
[BUG] .set directive filtered

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2959]
Via slack:

> For example I'm seeing directive usage like .set    .LC1,.LC0 from GCC where .LC1is referenced in the code being filtered out by the "Directives" filtering

https://godbolt.org/z/r1Wjx4cbY

**Comment by partouf** [comment]
xth duplicate of https://github.com/compiler-explorer/compiler-explorer/issues/2409 and something that will be fixed in new asm-parser

**Comment by mattgodbolt** [comment]
Doops!
