### ISSUE TITLE
[BUG] /EHc is forced on C++ MSVC

### ISSUE THREAD

**Issue by gcerretani** [compiler-explorer/compiler-explorer#2969]
**Describe the bug**

Compiler Explorer forces `/EHc` even if `/EHs` is explicitly set.

**To Reproduce**
```
extern "C" void foo() {
    throw 1;
}

static_assert(noexcept(foo()), "");
```

Try to compile this on any MSVC with `/EHs`.

**Expected behavior**
I would expect that `/EHs` does its job.

**Link**
https://godbolt.org/z/3nhYoezP1

**Screenshots**
n.a.

**Desktop**
n.a.

**Additional context**
The issue can be mitigated by compiling with `/EHc- /EHs`, as explained in [this answer](https://stackoverflow.com/a/69357446/3287591) on stackoverflow.

**Comment by timmy-ms** [comment]
@mattgodbolt If you have any ideas here Im all ears. My personal thought is we shouldn't pass any hidden flags ever. Anything we do by default should so up in the compiler options dialog box so everyone knows they are being set.

**Comment by OfekShilon** [comment]
See the discussion at https://github.com/compiler-explorer/compiler-explorer/pull/7164#issuecomment-2511084168.
I personally agree that this particular hidden flag wasn't a good idea, but unfortunately this can't really be solved without potentially breaking existing links. 
The `/EHc-` workaround will have to do for now.

@mattgodbolt  fyi

**Comment by mattgodbolt** [comment]
Thanks @OfekShilon - yeah I'm not really sure of a better way just now.
