### ISSUE TITLE
[REQUEST] Support LLVM IR output with ISPC compiler

### ISSUE THREAD

**Issue by dbabokin** [compiler-explorer/compiler-explorer#2970]
**Is your feature request related to a problem? Please describe.**

ISPC compiler supports LLVM IR output. It's produced if the switch `--emit-llvm-text` is passed to the compiler. Can we add "Add view..."->"LLVM IR output" similar to one that we have for clang?

**Comment by partouf** [comment]
I think we have everything in place to support this, but it needs some kind of magic to turn the option on and pass that parameter. It's not entirely clear to me how.

Looking at rust.js it's something like setting supportsIrView and irArg 
https://github.com/compiler-explorer/compiler-explorer/blob/278d28b313005effbc39519a833ddb8d92fea66d/lib/compilers/rust.js#L44

**Comment by dbabokin** [comment]
Thank you for implementing this! 🥳 🥳 🥳
