### ISSUE TITLE
[BUG] Many JVM compilers starting up at once can overwhelm startup

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2977]
On Sep 30th 2021 we had a site outage we believe is due to the large amount of JVM-based compilers. During startup we run more compilers than normally restricted by the compiler queue. This _seems_ to overwhelm the machine when it's otherwise busy and caused cascading failures.

**Comment by mattgodbolt** [comment]
Testing shows that this seems to work, but...startup now takes ~8 minutes (from a cold cache).

**Comment by mattgodbolt** [comment]
Once we have a better fix, reduce the grace period time in terraform.

**Comment by partouf** [comment]
oof, perhaps it's time to solidify our vague plans to make startup faster and make options.js more static

**Comment by mattgodbolt** [comment]
Yes, I think you're right.

**Comment by mattgodbolt** [comment]
I think we can consider this fixed now.
