### ISSUE TITLE
Update to newer npm et al

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2979]
We're far behind on npm, and node and everything. We should probably move to LTS of them all. We'd need to:

* [ ] Update the Makefile and scripts that look for and check versions. (Maybe would fix #2595)
* [ ] Update the node version used on the production site (would be a change to https://github.com/compiler-explorer/infra)

I don't know what I don't know about upgrading when we're this far behind =)

**Comment by partouf** [comment]
You mostly did this, node is updated to v16, and you changed to makefile etc, so closing
