### ISSUE TITLE
[BUG] std::system_error exception with std::packaged_task

### ISSUE THREAD

**Issue by Mazrog** [compiler-explorer/compiler-explorer#2987]
Hello,

**Describe the bug**
I have an exception thrown with a code calling a `std::packaged_task`: 
```
Program returned: 139
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
```

**To Reproduce**
This is the snippet I used reduced to the maximum: a bare call of `std::packaged_task` with a lambda and a call:
```cpp
#include <future>

int main() {
    std::packaged_task<void()>([] () {}) ();
    return 1;
}

```

**Expected behavior**
This should execute the lambda (here in the reduced example it does nothing) and return 1.

**Link**
In compiler explorer: https://godbolt.org/z/vE5Mhfzfa
In coliru: https://coliru.stacked-crooked.com/a/22915cb10847cd55

**Comment by supergrecko** [comment]
I'm not sure this is a Compiler Explorer bug, as this problem is a runtime error. Compiler Explorer seems to be working just fine.

Linking pthread into your program appears to fix the issue in your program. https://godbolt.org/z/bT8e54Ko4

**Comment by Mazrog** [comment]
Oh, I missed this :(
I thought maybe this was related to the platform compiler explorer runs on.

Anyway thank you and sorry for this...
