### ISSUE TITLE
Update MSP430 to gcc 6.2

### ISSUE THREAD

**Issue by lefticus** [compiler-explorer/compiler-explorer#299]
64 bit linux compiler is here: http://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/latest/index_FDS.html

Steps to install:

- Unpack compiler to known location (http://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/latest/exports/msp430-gcc-6.2.1.16_linux64.tar.bz2)
- Unpack support files to known location (http://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/latest/exports/msp430-gcc-support-files-1.198.zip)
- Configure CE to pass `-I <path_to_support_files>/include -L <path_to_support_files>/include`
- Make sure `needsMulti=false` otherwise we'll pick up Linux system headers and things go bad

**Comment by mattgodbolt** [comment]
Thanks as ever @lefticus

**Comment by mattgodbolt** [comment]
Oh yeah... I have the 6.2 but not the tools (oops).

**Comment by mattgodbolt** [comment]
Just tried to update compiler-explorer/infra `ce_install` to support `unzip`-ping files, but didn't manage it in one evening. Will try and rescue something, we'll get there...

**Comment by dkm** [comment]
We now have msp430 as a target for gcc 5, 6 and 12.2.0 and are planning on keeping up to date with future version.
Closing this but feel free to reopen if you think I've missed something!
