### ISSUE TITLE
[LIB REQUEST] oneTBB

### ISSUE THREAD

**Issue by anton-potapov** [compiler-explorer/compiler-explorer#3009]
**Library name:** 
oneAPI Threading Building Blocks (oneTBB) 

**Library description:**

Intel® oneAPI Threading Building Blocks (oneTBB)† is a flexible performance library that simplifies the work of adding parallelism to complex applications across accelerated architectures, even if you’re not a threading expert.

**Library repository:**

https://github.com/oneapi-src/oneTBB

**Library homepage:**

https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/onetbb.html

**Motivation:**

oneTBB is the [revamped](https://software.intel.com/content/dam/develop/external/us/en/documents/tbbrevamp.pdf) version (classical) TBB , which is _not fully_ compatible with it, so it's a pity it can not be played with using Compiler Explorer

**Comment by BenFrantzDale** [comment]
The site has TBB 2020.2 and 2020.3, but not oneTBB (2021.4.0 just came out). If I knew what's needed, I'd make a PR.

**Comment by BenFrantzDale** [comment]
I opened this PR which I think does it?: https://github.com/compiler-explorer/infra/pull/641

**Comment by anton-potapov** [comment]
@BenFrantzDale , @partouf  thank you very much ! 
https://gcc.godbolt.org/z/xaGa4P8cn
