### ISSUE TITLE
Phase out es6-promise dependency

### ISSUE THREAD

**Issue by matsjla** [compiler-explorer/compiler-explorer#3015]
Now that we have TypeScript on the frontend, we can have TypeScript automatically transpile async/await code down to ES5, which means that we shouldn't have to depend on fixes like es6-promise.

Just like the TypeScript migration, this is a gradual process, so once all files using es6-promise are ported, there shouldn't be any reason to keep the dependency.

**Comment by jeremy-rifkin** [comment]
I think this is now resolved
