### ISSUE TITLE
[BUG] Output colors ignored for Boost.Test framework

### ISSUE THREAD

**Issue by DanielLangr** [compiler-explorer/compiler-explorer#3018]
In this project: https://godbolt.org/z/b473eqvev, I see all the console output in light gray, which makes it almost unreadable (at least in the default scheme). This happens once Boost.Test starts to produce colored output. I am not sure whether this is a problem of Boost.Test or the Compiler Explorer. (Maybe, does the Boost.Test produce colors in some unsupported way?)

**Comment by supergrecko** [comment]
Apologies, this appears to be a regression from https://github.com/compiler-explorer/compiler-explorer/pull/2988/commits/533cbfae10d3e8ecfee7d97634d232fba2c2987b#diff-c0cddec368305f1e9ec4b838b14ec9550d7bbcd72c26ce930391598abd3980e0L189-R159

Will be submitting a fix shortly!

**Comment by partouf** [comment]
Fix is now live
