### ISSUE TITLE
[BUG] Clear cache and recompile does not clear cache for "Execute code"

### ISSUE THREAD

**Issue by davidstone** [compiler-explorer/compiler-explorer#3030]
**Describe the bug**
Clicking the "Clear cache and recompile" button does not clear the cache for "Execute code"

**To Reproduce**
* Write and execute some (C++) code
* Change a library so that the executed could would have a different result
* Click "Clear cache and recompile"

**Desktop**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 93

**Comment by partouf** [comment]
Is this when using the Compilation pane with the assembly or the Execution pane?

**Comment by partouf** [comment]
Also, I assume you have Automatic compilation checked off in the Settings? Otherwise it would have already attempted to recompile when changing the library

**Comment by apmorton** [comment]
I think David means on a local instance he's changed some files on disk
outside of CE that are getting #included and when forcing recompilation
it's not actually happening for the execute pane. Is this correct?

**Comment by partouf** [comment]
> I think David means on a local instance he's changed some files on disk outside of CE that are getting #included and when forcing recompilation it's not actually happening for the execute pane. Is this correct?

ahh that would make sense

**Comment by davidstone** [comment]
Yes, that is correct

**Comment by jeremy-rifkin** [comment]
I'm able to reproduce
```cpp
// ~/test.h
#include <iostream>
void foo() {
        std::cout<<"Hello World!"<<std::endl;
}
```
```cpp
// CE
#include <\
/home/rifkin/test.h>

int main() {
    foo();
}
```

![image](https://github.com/compiler-explorer/compiler-explorer/assets/51220084/9d7ba757-a62e-4b1d-a07d-a0f13142afc0)

**Comment by jeremy-rifkin** [comment]
Improved behavior is now live

**Comment by RubenRBS** [comment]
Was just coming here to comment on it after seeing it. This is great! Thanks a lot @jeremy-rifkin
