### ISSUE TITLE
[BUG] cproc version

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#3035]
At startup, this warning is given:
`/opt/compiler-explorer/cproc-master/bin/cproc cproc: unknown option '--version'`

**Comment by dkm** [comment]
I've created a quick workaround that should silence the warning by adding support for `--version` in `cproc`.
I've also asked cproc's dev if this is something they would consider. If you think this can easily wait a bit, we can leave the PR open and only merge it if this is not something upstream wants.
