### ISSUE TITLE
[BUG] Regex for checking for relative includes also checks comments

### ISSUE THREAD

**Issue by Falkgaard** [compiler-explorer/compiler-explorer#3045]
**Describe the bug**
Basically, the check for relative includes using some regex applies to the whole line, and not just the content of the angular brackets in the include. Therefore, if you have a comment on the same line containing a set of angular brackets with at least 2 periods in it, it will misinterpret it as being the actual include path and emit `<stdin>:1:1: no absolute or relative includes please`.

**To Reproduce**
MRE:
```cpp
#include <cstdio>  // <..>
int main() {}
```
The first line will result in `<stdin>:1:1: no absolute or relative includes please`

**Expected behavior**
Generally it's not really an issue (especially if you know why it happens), but it prevents code like the following:
```cpp
#include <cassert>     // for assert(...)
#include <utility>     // for std::exchange(...)
#include <stdexcept>   // for std::out_of_range
#include <ranges>      // for std::ranges::range<...> and std::ranges::range_type_v<...>
#include <type_traits> // for std::is_same_v<...>
```
where the three first lines are fine but the last two get misinterpreted as doing relative includes.

**Link**
https://godbolt.org/z/8obx7YWYT

**Desktop**
 - OS: Win 10
 - Browser Firefox
 - Version Latest

**Additional context**

**Comment by RubenRBS** [comment]
Hi! Thanks for taking the time to open the bugreport, we really appreciate it.
Also, sorry for the radio silence and that it took so long to get addressed.

I've now fixed (I think!) the issue that was causing this, but as it might break something else, I've pushed it as a PR.
Once it gets merged, it should be live "Soon":tm: :)

**Comment by Falkgaard** [comment]
Oh, no worries!

Thank you very much for fixing it! ♥

Happy Halloween!
