### ISSUE TITLE
[BUG] Scrolling on mobile

### ISSUE THREAD

**Issue by ljyanesm** [compiler-explorer/compiler-explorer#3056]
Hi, 

Thanks for such an amazing resource! I know there have been comments on improving the mobile experience, hoping this will help some folk when viewing the site on the go. 

**Describe the bug**
On an android mobile using chrome, scrolling on any editable window opens the keyboard reducing the already limited read space.

**To Reproduce**
Close the keyboard if open, scroll on an editable panel, the keyboard opens again.

**Expected behavior**
The keyboard should remain closed when scrolling and only open if the panel is tapped once.

**Comment by RubenRBS** [comment]
Hi! Thanks for taking the time to file the issue.

Note that using:
Andorid 11
Chrome 95.0.4638.74
Latest live version of the site

I've been unable to reproduce the issue. Scrolling on the editors does not open a keyboard for me.


Unfortunately, even if I were able to repro this, I don't think there's anything we can do here on our side :(

We rely on Monaco Editor by Microsoft for the Editor, and it specifically does not support Mobile phones (Even though they try no to break what little works there!). We have some code in place to make it a bit more usable, but there's so much that can be done without just using a different editor in mobile, which currently is infeasible for us :(

**Comment by ljyanesm** [comment]
Sorry I left this open for so long, I can still repro this on my side, but I understand it might not be a quick fix. Thank you for your reply.
