### ISSUE TITLE
[BUG] Assembly output pane does not have colors on load

### ISSUE THREAD

**Issue by matsjla** [compiler-explorer/compiler-explorer#3059]
**Describe the bug**
Occasionally when opening compiler-explorer, the assembly output pane doesn't have syntax coloring. It looks like this:
![image](https://user-images.githubusercontent.com/42585241/138695479-8d6512fd-cff0-485e-a375-3d8709d13fcf.png)

**To Reproduce**
I'm unsure of the actual reproduction steps, as the bug disappears as soon as you refresh the page. The developer console is also empty.

**Expected behavior**
It should have colored syntax highlighting

**Link**
Not applicable

**Screenshots**
Provided above

**Desktop**

 - OS: Ubuntu 20.04
 - Browser: Google Chrome
 - Version: 90.0.4430.72 (Official Build) (64-bit)

**Additional context**
Have seen this happen once before on staging, assumed it was something up with the staging env still starting up. This time it happened in prod.

**Comment by jeremy-rifkin** [comment]
I think this is now fixed, at least we haven't had any reports of it
