### ISSUE TITLE
[REQUEST]: Documentation on API Base64/utf8

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#3075]
### Is your feature request related to a problem? Please describe

With our `/clientstate/:base64` API call we require that json is encoded in a certain way before it is encoded to base64, otherwise, you won't be able to pass along UTF-8 characters.

This should be documented more helpfully for users.

We use similar in communication with quick-bench, probably something like this:

```
function asciiEncodeJsonText(json) {
    return json.replace(/[\u007F-\uFFFF]/g, function (chr) {
        // json unicode escapes must always be 4 characters long, so pad with leading zeros
        return '\\u' + ('0000' + chr.charCodeAt(0).toString(16)).substr(-4);
    });
};

btoa(this.asciiEncodeJsonText(JSON.stringify(state))
```

or 

```
b64UTFEncode(str) {
    return btoa(encodeURIComponent(str).replace(/%([0-9A-F]{2})/g, function (match, v) {
        return String.fromCharCode(parseInt(v, 16));
    }));
}
```

or https://stackoverflow.com/questions/31649362/json-stringify-and-unicode-characters/31652607#31652607

To be determined what the "best" way is.

### Describe the solution you'd like

Documentation

### Describe alternatives you've considered

Complain about webtechnologies.

### Additional context

Not applicable

**Comment by jinder1s** [comment]
Hi, it looks like this issue is done with merging of #4114.
