### ISSUE TITLE
[LIB REQUEST]: NSimd v3

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#3078]
### Library name

nsimd

### Library description

Nsimd v3 has been installed, but is not added to the list on the website yet
* installation: https://github.com/compiler-explorer/infra/pull/618
* todo: https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/c%2B%2B.amazon.properties#L1823

### Library repository

https://github.com/compiler-explorer/infra/pull/618

### Motivation

etc

**Comment by RubenRBS** [comment]
Closed by #3095
