### ISSUE TITLE
[BUG]: Clang Execution Only context shows no available libraries

### ISSUE THREAD

**Issue by andrewkcorcoran** [compiler-explorer/compiler-explorer#3088]
### Describe the bug

Enabling an execution only context for clang (tested with multiple versions) shows no libs available to be enabled (tested on chrome and edge). Changing the compiler to gcc or switching to a compiler context works as expected.

### Steps to reproduce

1. Visit godbolt.org
2. Add new -> Execution only
3.  Select x86-64 clang 10.0.1
4. Select libraries

### Expected behavior

Libraries should be available in all compilers

### Reproduction link

Not applicable

**Comment by RubenRBS** [comment]
Hi! Thanks for taking the time to open the bug report.
As part of our move to TS, this isssue has already been addressed in #3077, so it will get fixed once that PR lands :)
