### ISSUE TITLE
[BUG]: Clang-format base style option has no effect

### ISSUE THREAD

**Issue by evakili** [compiler-explorer/compiler-explorer#3089]
### Describe the bug

Changing clang-format style option has no effect. Always a default one is used (maybe google or llvm).

### Steps to reproduce

1. Enter this code in a new source file at godbolt.org:
```cpp
int main() {
    return 0;
}
```
2. Despite of which base style is chosen, the output of formatting document is:
```cpp
int main() { return 0; }
```

### Expected behavior

For example for GNU base style it should be formatted as:
```cpp
int
main ()
{
  return 0;
}
```

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Windows 10

### Browser version

Chrome/Edge 95, Firefox 78

**Comment by partouf** [comment]
Seems this was a result of some refactoring, but we forgot to address this problem. (https://github.com/compiler-explorer/compiler-explorer/pull/2874)

**Comment by supergrecko** [comment]
Hi, I'll look into this tonight, thanks for the bug report!

**Comment by partouf** [comment]
this has been fixed live
