### ISSUE TITLE
[BUG]: Google Benchmark cannot be used with GCC > 10.3 or Clang >= 12

### ISSUE THREAD

**Issue by amyspark** [compiler-explorer/compiler-explorer#3092]
### Describe the bug

Google Benchmark cannot be linked to with recent versions of GCC/Clang, which makes benchmarks impossible to test.

(Do notice that this is a workaround for quickbench lacking GCC 11+ and Clang 12+.)

### Steps to reproduce

1. Visit godbolt.org
2. Select a GCC version > 10.3 or Clang >= 12.
3. Select "Google Benchmark" in the Libraries section.

### Expected behavior

Link succeeds and, if a test was provided, the output panel shows the benchmark results.

### Reproduction link

https://godbolt.org/z/444orjGsf

### Screenshots

Not applicable

### Operating System

Windows_NT 10.0 19042

### Browser version

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0

**Comment by partouf** [comment]
1.5.0 failed to build (example gcc 11.1 https://conan.compiler-explorer.com/getlogging/20210428051919)

Google benchmark Trunk does build and you can link against that if you change it in your example link.

You can link against 1.5.0 with Clang >= 12 if you use libc++, stdlib does not work

**Comment by amyspark** [comment]
@mattgodbolt @partouf was this fixed? As of a few weeks benchmark was still unusable and we're already on clang 14.

**Comment by RubenRBS** [comment]
Hi! The logs show that the library (v 1.5.0) is still failing for the newer compiler versions. While not a fix, seeing that trunk seems to be doing better for those compiler versions, I've added 1.6.1 to the list so it hopefully builds in most cases, we'll see tomorrow when they get built 🤞

**Comment by amyspark** [comment]
No luck yet. Trunk is still needed: https://godbolt.org/z/nrEn97P4a

**Comment by partouf** [comment]
1.6.1 is not being built by any compiler, so I did some digging.
This is an example of what error we're getting during build: https://conan.compiler-explorer.com/getlogging/20220517040049

The error is:
```
CMake Error at CMakeLists.txt:34 (message):
  Did not find Google Test sources! Either pass correct path in
  GOOGLETEST_PATH, or enable BENCHMARK_DOWNLOAD_DEPENDENCIES, or disable
  BENCHMARK_USE_BUNDLED_GTEST, or disable BENCHMARK_ENABLE_GTEST_TESTS /
  BENCHMARK_ENABLE_TESTING.
```

We have an old version of `googletest` inside our benchmark trunk folder (I'm guessing we put it there manually?), so that's why trunk is building.

I'll have a think on how we're gonna solve this, although we might also consider just disabling the tests during build.

**Comment by partouf** [comment]
1.6.1 is now finally building
