### ISSUE TITLE
[BUG]: Java is set to US-ASCII

### ISSUE THREAD

**Issue by easyaspi314** [compiler-explorer/compiler-explorer#3093]
### Describe the bug

Java is set to use the US-ASCII encoding, but the code is saved as UTF-8.

### Steps to reproduce

1. Visit godbolt.org
2. Select Java
3. Try to do *anything* with Unicode in it
4. You get a bunch of errors

### Expected behavior

While the charset can be overridden with `-encoding UTF-8`, it should be set to UTF-8 in the first place.

### Reproduction link

https://godbolt.org/z/MrY6es7PG

### Screenshots

![image](https://user-images.githubusercontent.com/6258309/139786168-abe9f8b3-0c77-4863-9fb0-eb9619ad6199.png)

**Comment by supergrecko** [comment]
Thanks, I'll look into this.
