### ISSUE TITLE
Add 32-bit assembly compiler

### ISSUE THREAD

**Issue by 3093FengMing** [compiler-explorer/compiler-explorer#3105]
I want to add a 32-bit assembly compiler to the compiler explorer
Because some hardware does not support 64 bit assembly

**Comment by dkm** [comment]
What do you mean? There's already the possibility to use 32-bits targets. For example, by using gcc/clang and using `-m32`. The ARM compilers are also targeting 32-bits hardware. Maybe you want a particular (missing?) assembler?
