### ISSUE TITLE
Truncate error messages

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#311]
E.g. putting this code: `template<class T>class L{L<T*>operator->()};L<int>i=i->` in the view kills the browser...

**Comment by dreamzor** [comment]
Here is the more complete list :)
http://tgceec.tumblr.com/post/74534916370/results-of-the-grand-c-error-explosion

**Comment by mattgodbolt** [comment]
"Works" on the beta site. Generates a jolly large error message:

```
$ curl 'https://gcc.godbolt.org/api/compiler/g63/compile?options=-Wall' --data-binary 'template<class T>class L{L<T*>operator->()};L<int>i=i->' | wc
   6292   27269  822287
```
I think the error message needs truncating a tiny bit earlier.

**Comment by mattgodbolt** [comment]
Couldn't reproduce (via https://godbolt.org/g/ujv6gi ) though I think truncating the error output is still sensible. Renaming bug and making a feature.

**Comment by dwcraig** [comment]
I'd be happy to work on this.  Is there a preferred length to truncate the error messages to?

**Comment by dwcraig** [comment]
I am able to truncate the error message coming from the compiler response in static/compiler.js, but I am unsure how I would access the property to allow the response length to be configured.
Would it be possible for someone to point me in the right direction?

**Comment by jaredwy** [comment]
Take a look at the config files in ‘etc/‘ I would drop a new property in the default one and load it as a config option. Then use this to truncate the error string.

**Comment by dwcraig** [comment]
Thanks. The part that I am stuck on is loading it as a config option.  Sorry, my comment was unclear.  I added `truncateErrorMessages=20` to `compiler-explorer.defaults.properties`.  I am not sure where or how I should load that as a config option.

**Comment by dwcraig** [comment]
Thanks @jaredwy and @RabsRincon.  I've got it so that the number of lines can be truncated by the amount set in the `.properties` files.  What would be a good value to set the default to when there is nothing set by a user?

**Comment by partouf** [comment]
This was truncated on the serverside a long time ago, so this is actually fixed
