### ISSUE TITLE
[BUG]: Assembly output is broken when using `-flto`

### ISSUE THREAD

**Issue by Qqwy** [compiler-explorer/compiler-explorer#3111]
### Describe the bug

See [example here](https://godbolt.org/z/bnWx7v7Es)

When the flag `-flto` is given to add link-time optimization, it seems that (at least for g++ and clang++; I have not tested others), the output of the assembly changes to something which is not legible.

### Steps to reproduce

1. Visit godbolt.org
2. Create some C++ script
3. Add a compiler window. 
  - When compiling, output looks OK
4. Add the compiler flag `-flto`.
  - When recompilation finishes, output is not legible any longer.

### Expected behavior

Even when LTO is enabled, the assembly output should be legible.

### Reproduction link

https://godbolt.org/z/bnWx7v7Es

### Screenshots

Not applicable

### Operating System

Manjaro Linux x86_64 

### Browser version

Firefox 93.0 (64-bit)

**Comment by partouf** [comment]
You can only really use LTO in the "Compile to binary" mode of the website, or in IDE mode.

Example binary mode:
https://godbolt.org/z/a9djhrxj7

It's harder to figure out than usual in GCC 11 because GCC strips more from the binary than we were previously used to.
GCC 10 still emits the line locations properly.

**Comment by Qqwy** [comment]
Thank you for your response, @partouf.

It seems that even though GCC's (and Clang's) output in 'Compile to binary' mode is sort-of readable, however on larger programs a 'output truncated' message is very easily generated.
I'm not sure what could be done to make this nicer.

In any case: Is it maybe possible to add a clear error when someone uses `-flto` without 'compile to binary' active? (Maybe similar to the error being shown when trying to use `-march=native`?)

**Comment by partouf** [comment]
> In any case: Is it maybe possible to add a clear error when someone uses `-flto` without 'compile to binary' active? (Maybe similar to the error being shown when trying to use `-march=native`?)

That sounds like a reasonable solution, good one, thanks! Let's do that

**Comment by dead-tech** [comment]
I would like to work on this, if possible.

**Comment by partouf** [comment]
> I would like to work on this, if possible.

Absolutely!
