### ISSUE TITLE
[BUG]: Can't seem to be able to reach the website

### ISSUE THREAD

**Issue by wspvlv** [compiler-explorer/compiler-explorer#3122]
### Describe the bug

Whenever I try to reach the website, it is simply stuck on loading. What is weird that it seems to only happen with my IP address?

I tried pinging the address in the terminal and I was not receiving any packets:
```sh
$ ping godbolt.org
PING godbolt.org (18.66.122.100) 56(84) bytes of data.
--- godbolt.org ping statistics ---
42 packets transmitted, 0 received, 100% packet loss, time 41538ms
```

### Steps to reproduce

1. Try to visit godbolt.com

### Expected behavior

1. Access to the website.

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Arch Linux, kernel version 5.15.2

### Browser version

Google Chrome 96.0.4664.45

**Comment by mattgodbolt** [comment]
`godbolt.org` is served from Amazon Cloudfront. Can you hit other amazon sites like https://status.aws.amazon.com/ or similar?

**Comment by mattgodbolt** [comment]
> 1. Try to visit godbolt.com

you said `godbolt.com` here which isn't the right address. You did `ping godbolt.org` which is correct (and should repond; again that's not our IP though it's amazon's).

**Comment by wspvlv** [comment]
Thanks for your reply!

> `godbolt.org` is served from Amazon Cloudfront. Can you hit other amazon sites like https://status.aws.amazon.com/ or similar?

Yes, it loaded the status of AWS, and all services were operational. 

> you said godbolt.com here which isn't the right address. You did ping godbolt.org which is correct (and should repond; again that's not our IP though it's amazon's).

My bad, it was merely a typo

Eventually my browser gives up and gives me this message. 
![image](https://user-images.githubusercontent.com/66871052/142635323-fcae6fd9-4d72-4e53-840f-59585066e0bc.png)

**Comment by mattgodbolt** [comment]
It sounds like your packets aren't getting to cloudfront. I'm afraid I don't know how to diagnose this. Do you have a firewall, or an ISP that might block traffic to some places? Are you in a country that has an export embargo from the USA?

**Comment by wspvlv** [comment]
Looks like I cannot load any websites that are owned by Amazon (eg. amazon.com, twitch.tv) either, so it seems like Amazon's problem. I noticed it started happening after I have deleted my Amazon account.

**Comment by mattgodbolt** [comment]
That's really odd! But thanks for updating. I'm going to close this; there's nothing I can do here on our side to help I'm afraid.
