### ISSUE TITLE
Add TS reflection clang

### ISSUE THREAD

**Issue by hanickadot** [compiler-explorer/compiler-explorer#3123]
Hi compiler-explorer/godbolt people 🤣

can you please add this compiler:

https://github.com/matus-chochlik/llvm-project/tree/reflection

it's WIP TS reflection and we need more users to play with it

Thanks! Hana

**Comment by mattgodbolt** [comment]
* Is there a URL I can use to notify users (maybe the paper number?)
* What default flags are good to use? e.g. `-freflection-ts` - does it need `-std=?` or `-stdlib=libc++` ?

**Comment by matus-chochlik** [comment]
Hi,
`-std=c++20 -freflection-ts -freflection-ext` should be enough.

**Comment by matus-chochlik** [comment]
OK, after brief discussion with @hanickadot  we should leave out the `-freflection-ext` flag for now. So it's just:
`-std=c++20 -freflection-ts` + any libcxx-refated flags.

**Comment by mattgodbolt** [comment]
Perfect! Coming soon!

**Comment by mattgodbolt** [comment]
just building: https://github.com/compiler-explorer/compiler-workflows/actions/runs/1481427805

**Comment by mattgodbolt** [comment]
@matus-chochlik will this work with GCC's libcpp or should I force libc++ ?

**Comment by mattgodbolt** [comment]
```
compiler.clang_reflection.options=-std=c++20 -freflection-ext -stdlib=libc++
```
I'm thinking of this ^ :)

**Comment by matus-chochlik** [comment]
If it successfully compiles this:
```
#include <experimental/reflect>

auto main() -> int {
  using namespace std::experimental::reflect;
  static_assert(!Type<int>);
  using mg = reflexpr(::);
  using mi = reflexpr(int);
  using ms = reflexpr(std);
  static_assert(Object<mi>);
  static_assert(Object<ms>);
  static_assert(!ObjectSequence<mi>);
  static_assert(Type<mi>);
  static_assert(Namespace<ms>);
  static_assert(GlobalScope<mg>);
  static_assert(GlobalScope<get_scope_t<ms>>);
  get_reflected_type_t<mi> i = 0;

  return i;
}
```
then the flags are OK.

**Comment by mattgodbolt** [comment]
cool - I will pass those.

The build failed, unfortunately: https://github.com/compiler-explorer/compiler-workflows/runs/4265395609?check_suite_focus=true

```
2021-11-19T15:11:14.0970513Z In file included from /root/build/include/c++/v1/experimental/memory_resource:70:
2021-11-19T15:11:14.0971891Z In file included from /root/build/include/c++/v1/memory:671:
2021-11-19T15:11:14.0973191Z In file included from /root/build/include/c++/v1/__memory/compressed_pair.h:15:
2021-11-19T15:11:14.0974931Z /root/build/include/c++/v1/tuple:387:13: error: expected class member or base class name
2021-11-19T15:11:14.0976345Z             __tuple_leaf<_Uf, _Tf>(_VSTD::forward<_Up>(__u))...,
2021-11-19T15:11:14.0978039Z             ^
2021-11-19T15:11:14.0979099Z /root/build/include/c++/v1/tuple:399:13: error: expected class member or base class name
2021-11-19T15:11:14.0980378Z             __tuple_leaf<_Uf, _Tf>(__uses_alloc_ctor<_Tf, _Alloc, _Up>(), __a,
2021-11-19T15:11:14.0981190Z             ^
2021-11-19T15:11:14.0982238Z /root/build/include/c++/v1/tuple:413:15: error: expected class member or base class name
2021-11-19T15:11:14.0983638Z             : __tuple_leaf<_Indx, _Tp>(_VSTD::forward<typename tuple_element<_Indx,
2021-11-19T15:11:14.0984562Z               ^
2021-11-19T15:11:14.0985604Z /root/build/include/c++/v1/tuple:425:15: error: expected class member or base class name
2021-11-19T15:11:14.0987093Z             : __tuple_leaf<_Indx, _Tp>(__uses_alloc_ctor<_Tp, _Alloc, typename tuple_element<_Indx,
2021-11-19T15:11:14.0988117Z               ^
2021-11-19T15:11:14.0988816Z 4 errors generated.
2021-11-19T15:11:14.1122737Z [457/579] Building CXX object libcxx/src/CMakeFiles/cxx_static.dir/bind.cpp.o
```

Are there any special affordances I need to make in the build process? We have a driver script that builds all the various clang branches and I guessed that it should "just build" if I pointed the script at your repo

**Comment by matus-chochlik** [comment]
I'm using this to build it (with clang++12.0):
```
cmake \
        -G Ninja \
        -DLLVM_ENABLE_PROJECTS="clang;libc;libcxx;libcxxabi" \
        -DLLVM_USE_LINKER=lld \
        -DLLVM_USE_SPLIT_DWARF=ON \
        -DCMAKE_INSTALL_PREFIX=${PREFIX} \
        -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld -pthread" \
        -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld -pthread" \
        -DCMAKE_BUILD_TYPE=Debug \
        -DLLVM_PARALLEL_LINK_JOBS=${LINK_JOBS} \
        -DLLVM_PARALLEL_COMPILE_JOBS=${CMPL_JOBS} \
        ${ROOT_DIR}/llvm && \
ninja install && \
```

This is the link to the full script: https://github.com/matus-chochlik/llvm-project/blob/reflection/_reflexpr/rebuild

**Comment by mattgodbolt** [comment]
Our flags end up being:

```
cmake -G Ninja /root/llvm-project/llvm '-DLLVM_ENABLE_PROJECTS=clang;' '-DLLVM_ENABLE_RUNTIMES=libcxx;libcxxabi' -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/root/staging -DLLVM_BINUTILS_INCDIR:PATH=/opt/compiler-explorer/gcc-9.2.0/lib/gcc/x86_64-linux-gnu/9.2.0/plugin/include -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=
```

We build with gcc 7.5, with binutils from gcc 9.* (which isn't ideal, we should upgrade our GCC for sure)

Is it a requirement to build with `clang`, do you think? (this would be our first clang build to need it if so)

**Comment by matus-chochlik** [comment]
I'll try a gcc build on a different machine and let you know.

**Comment by mattgodbolt** [comment]
Thanks! If the answer is "just build with clang itself" we can take a look, but it would be our first clang-onclang build :) Let me know! I'm excited to get your branch on compiler explorer! :)

**Comment by hanickadot** [comment]
At least with clang 13 I had problems building it with gcc older than 8, maybe that's the problem?

**Comment by mattgodbolt** [comment]
clang trunk is building OK - https://github.com/compiler-explorer/compiler-workflows/actions/runs/1479082108 (that's not to say we shouldn't try and update our GCC, but I'd rather do that separately if possible)

**Comment by matus-chochlik** [comment]
The `expected class member or base class name` is probably my bad, I was messing with that part of the parser. I'll investigate and let you know.

**Comment by mattgodbolt** [comment]
Cool! Let me know and I can re-trigger a rebuild whenever you think it's good to go!

**Comment by matus-chochlik** [comment]
I think I fixed it, I don't see it here anymore. Could you please pull and try a rebuild?

**Comment by mattgodbolt** [comment]
Done: running here -> https://github.com/compiler-explorer/compiler-workflows/actions/runs/1481427805

**Comment by mattgodbolt** [comment]
Confirmed: it built! Will get on with the other things needed.

**Comment by mattgodbolt** [comment]
```
$ sudo ce_install --enable nightly  install clang reflection-trunk
...
Installing compilers/c++/nightly/clang reflection-trunk
2021-11-19 17:27:50,468 lib.installation INFO     Fetching https://s3.amazonaws.com/compiler-explorer/opt/clang-reflection-trunk-20211119.tar.xz (631212780 bytes)
2021-11-19 17:27:55,643 lib.installation INFO     30.6% of https://s3.amazonaws.com/compiler-explorer/opt/clang-reflection-trunk-20211119.tar.xz...
2021-11-19 17:28:00,685 lib.installation INFO     65.1% of https://s3.amazonaws.com/compiler-explorer/opt/clang-reflection-trunk-20211119.tar.xz...
2021-11-19 17:28:05,553 lib.installation INFO     100% of https://s3.amazonaws.com/compiler-explorer/opt/clang-reflection-trunk-20211119.tar.xz
2021-11-19 17:28:05,559 lib.installation INFO     Piping to tar Jxf -
...
$ /opt/compiler-explorer/clang-reflection-trunk/bin/clang++ --version
clang version 14.0.0 (https://github.com/matus-chochlik/llvm-project.git c3dd7f58486f0178bf0acfb63d7f491a6981b258)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/compiler-explorer/clang-reflection-trunk/bin

```

**Comment by hanickadot** [comment]
it's seems in staging there are `-freflection-ts` flag is missing

**Comment by matus-chochlik** [comment]
Yep, but when it's added manually, some parts of reflection already work.
Thank you, Matt! When you get the change please add the `-freflection-ts` to the flags.
In the meantime I'll have to go fix some bugs... :P

**Comment by mattgodbolt** [comment]
My mistake, I will update to auto-pass `-freflection-ts`

**Comment by mattgodbolt** [comment]
Manually setting it crashes with:

```
*** stack smashing detected ***: terminated
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-reflection-trunk/bin/clang++ -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S -std=c++20 -freflection-ext -stdlib=libc++ -fcolor-diagnostics -fno-crash-diagnostics -freflection-ts <source>
1.	<eof> parser at end of file
2.	<source>:3:6: LLVM IR generation of declaration 'main'
3.	<source>:3:6: Generating code for declaration 'main'
 #0 0x0000555b169572cf PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x0000555b16955190 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-reflection-trunk/bin/clang+++0x3355190)
 #2 0x0000555b1689cd78 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f9888e533c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
```

**Comment by mattgodbolt** [comment]
Will update though, and this will get rid of the `-frelfection-ext` -- maybe that's the cause of the crash?

**Comment by matus-chochlik** [comment]
There are some TODOs in the code generation, that is probably the reason. It works here though, as I said I have some debugging to do. :)

**Comment by matus-chochlik** [comment]
I hope, it doesn't cause any problems for CE when it crashes (accumulating corefiles or something), if it does, feel free to disable it and I'll let you know when I have found the source of the problems (probably tommorrow).
Thanks again for your patience.

**Comment by mattgodbolt** [comment]
It doesn't cause any issues at all!

It's now live! Thanks for your patience! :)

**Comment by matus-chochlik** [comment]
Hi,
would it be by any chance possible to trigger a manual rebuild? I messed up the last commit I did before going to sleep yesterday :P

**Comment by partouf** [comment]
> 

No problem, building now

**Comment by matus-chochlik** [comment]
Thank you! :)

**Comment by maxmitti** [comment]
Should the compiler explorer already have https://github.com/matus-chochlik/llvm-project/commit/f689b87ab76b45a28c7950d91fe61019f063470f? I can see that this commit was successfully compiled [here](https://github.com/compiler-explorer/compiler-workflows/runs/4309499072?check_suite_focus=true#step:5:10597).
The compiler explorer website still has https://github.com/matus-chochlik/llvm-project/commit/e396e72731b1ff2499d7f1dd1b7e3b4ffa435216 according to the version information.

**Comment by partouf** [comment]
If you do --version you'll get the real current version https://godbolt.org/z/sGaPczPq4
Which is f689b87ab76b45a28c7950d91fe61019f063470f

**Comment by matus-chochlik** [comment]
Hi,

On Wed, Nov 24, 2021 at 4:31 PM maxmitti ***@***.***> wrote:

> Should the compiler explorer already have matus-chochlik/llvm-project@
> f689b87
> <https://github.com/matus-chochlik/llvm-project/commit/f689b87ab76b45a28c7950d91fe61019f063470f>?
> I can see that this commit was successfully compiled here
> <https://github.com/compiler-explorer/compiler-workflows/runs/4309499072?check_suite_focus=true#step:5:10597>
> .
> The compiler explorer website still has matus-chochlik/llvm-project@
> e396e72
> <https://github.com/matus-chochlik/llvm-project/commit/e396e72731b1ff2499d7f1dd1b7e3b4ffa435216>
> according to the version information.
>
Yep, the fixup is installed, I asked for a manual rebuild after pushing it.
