### ISSUE TITLE
[BUG]: Clang reflection doesn't produce correct binaries

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#3132]
### Describe the bug

The binaries don't have correct links to their libc++ shared objects
and/or LD_LIBRARY_PATH's are not set as needed.

### Steps to reproduce

Compile something with x86-64 clang (reflection), click on compile to binary or execute the code.

### Expected behavior

Should link and run if it's correct code

### Reproduction link

https://compiler-explorer.com/z/hfa4fobEG

**Comment by partouf** [comment]
Mentioned in Discord.

Also note that `-std=stdlibc++` sometimes works, but is unlikely to work if you're actually testing reflection things.

**Comment by partouf** [comment]
Note that Clang Trunk has this line https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/c%2B%2B.amazon.properties#L303

Reflection does not

**Comment by partouf** [comment]
https://github.com/compiler-explorer/compiler-explorer/commit/029c86af0bf4bfc8c632494ac21bd4035745eceb

`libc++.so` is in `lib/x86_64-unknown-linux-gnu`

**Comment by partouf** [comment]
is fixed

**Comment by mattgodbolt** [comment]
Great spot! thanks
