### ISSUE TITLE
[QUESTION]: Is there a way to delete a shared link?

### ISSUE THREAD

**Issue by hewillk** [compiler-explorer/compiler-explorer#3134]
Hi Team,

Once I click the share button to share the code, a hyperlink with a suffix of alphanumeric characters will be generated. 
Is there any way to delete the generated hyperlink since I may just want to expose it for a while or I just accidentally clicked the share button?

Thanks
Hewill

**Comment by partouf** [comment]
Currently, there's no way to do it for users themselves. We'd have to manually delete the link from our database.

There were some user-logins in the works to facility better control of sharing code, but that's currently on hold.

**Comment by partouf** [comment]
Closing in favor of more complete issue https://github.com/compiler-explorer/compiler-explorer/issues/505 

If you have a strong need for a one-off deletion, let us know.
