### ISSUE TITLE
[BUG]: Cannot select the 1st character

### ISSUE THREAD

**Issue by pmor13** [compiler-explorer/compiler-explorer#3138]
### Describe the bug

Cannot select the 1st character.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/4587883/143610143-81c2ea50-3e26-4bf6-9281-4eb6939bdda9.png)

### Expected behavior

Can select the 1st character.

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Windows 10 64-bit

**Comment by partouf** [comment]
It's possible when the output is on the browser's edge, but not if there's a pane left to it. A 'Select all'/Copy option would definitely be useful

**Comment by jeremy-rifkin** [comment]
@pmor13 I have a question about reproducing, is it that you're unable to select the first character when starting at the top left because of the draggable separator in the site layout? I am able to select all content by selecting from the bottom right.

**Comment by RubenRBS** [comment]
I figured it's because what Partouf suggested. The sliders have some big negative margins that made the text a bit hard to select, so I've added some padding for the output in the selection PR (Sorry that this took so long to get addressed!)

**Comment by pmor13** [comment]
@jeremy-rifkin From the bottom-right to the top-left.
