### ISSUE TITLE
[BUG]: x86 -> 6502 Tool not working

### ISSUE THREAD

**Issue by RuralGeekNZ** [compiler-explorer/compiler-explorer#3140]
### Describe the bug

When using the default example the following error is generated by the x86 to 6502 tool:
error: 2: Unknown opcode: imull

Using gcc x86-64 9.3 and these options: -O3 -march=i386 -m32

### Steps to reproduce

1. Load godbolt.org with default example.
2. Set gcc x86-64 9.3 and these options: -O3 -march=i386 -m32
3. Set output to not use Intel ASM syntax
3. Add the x86 to 6502 tool

### Expected behavior

For some reason the x86 to 6502 is expecting  imul rather than imull
I presume a compiler directive is needed to generate imul instead of imull?
Similar error occurs if you change the multiply to add

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Win10

### Browser version

Firefox 94.02

**Comment by mattgodbolt** [comment]
(example short link: https://godbolt.org/z/bzjxfh6e1 )

Hi @RuralGeekNZ - I'm afraid the x86 -> 6502 tool only supports a tiny number of opcodes. It's an experiment by @lefticus only - it handles a half dozen opcodes. There's no 6502 "multiply" instruction, and x86to6502 doesn't support any way of generating multipication code. See https://github.com/lefticus/6502-cpp for details.

@lefticus has been working on a better translator to 6502 using a cross-compiler to Arduino. One day we may support that.

In the mean time you can try compiling C to 6502 with one of the C compilers -> https://godbolt.org/z/GG7zd34Pb but note this doesn't generate particularly great code.
