### ISSUE TITLE
[BUG]: Silly/annoying mouseover behaviour in Graph Viewer

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#3142]
### Describe the bug

Menu pops away when you get your mouse in the gap between the combobox and the popup menu.

### Steps to reproduce

Open graph viewer, try to select a different function.

### Expected behavior

Be a bit more user-friendly

### Reproduction link

Not applicable

### Screenshots

![graph_weird_mouseover_behaviour](https://user-images.githubusercontent.com/442630/144068552-ce8aab4f-6e1d-4f33-b646-d6a3fc5ecbf7.gif)

**Comment by nzaghen** [comment]
To add some info, as I just encountered the same behaviour, I think this happens because the Graph Viewer canvas is stealing the focus when mouseover happens
