### ISSUE TITLE
[COMPILER REQUEST]: gdc-trunk builds might be broken

### ISSUE THREAD

**Issue by ibuclaw** [compiler-explorer/compiler-explorer#3149]
### Compiler name

GDC

### Compiler version

trunk

### Compiler language

D

### Compiler homepage

gcc.gnu.org/

### Motivation

Hi,

I've recently updated the GDC sources from C++ to D, I imagine this might have broke the gdc-trunk builds (don't know how to check).  If that is the case, the please reach out to me if you need any help getting them back up again.

Thanks.
Iain.

**Comment by dkm** [comment]
Hi @ibuclaw ! What are the requirements on the base compiler ?

**Comment by ibuclaw** [comment]
You can use any gdc compiler release.  The latest version of any of the 9.x, 10.x, or 11.x releases should be fine to use (I've mostly been testing using gdc-10)

You can also use ldc2 or dmd if you point the `GDC` environmental flag at a wrapper script that translates gcc-style options to ldc2 (or dmd) style options.

**Comment by dkm** [comment]
Ok thanks ! I'll have a look later tonight if nobody else closes this in the meantime.

**Comment by dkm** [comment]
Thanks to @partouf we can confirm that build is currently failing because there's no D compiler installed. I'll update the builder image tonight and see if it's enough.

**Comment by ibuclaw** [comment]
@dkm just let us know if you pick ldc2 or dmd as the pre-installed D compiler, and I'll get a script that works with them.

**Comment by partouf** [comment]
> @dkm just let us know if you pick ldc2 or dmd as the pre-installed D compiler, and I'll get a script that works with them.

@dkm was thinking we might be able to install a ubuntu version for GDC, otherwise we'll use a version that we built ourselves and set the GDC envvar

**Comment by partouf** [comment]
We have done the ubuntu gdc install and everything built again. So we'll install that shortly

**Comment by partouf** [comment]
They are installed
