### ISSUE TITLE
[BUG]: fscanf loop fails to increment variable in parent scope

### ISSUE THREAD

**Issue by Busyvar** [compiler-explorer/compiler-explorer#3150]
### Describe the bug

Here is minimal example (input file required):
```
  #include <stdio.h>                                                                  
  int main() {
      FILE *fp = fopen("input","r");                                                  
      int entries = 0;                                                                
      char binVal[12];
      while(EOF != fscanf(fp, "%s", binVal)){                                         
          entries++;                                                                  
      }
      printf("entries:%d",entries);                                                   
      fclose(fp);                                                                     
      return 0;                                                                       
  }

```

### Steps to reproduce

1. copy code example in description
2. add a file called input in the folder with 100 lines
3. compile and run

### Expected behavior

program should print entries:100
instead, it prints entries:1
This bug doesn't occurs with gcc 11.1.0

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Archlinux x64

**Comment by mattgodbolt** [comment]
Hi: can you supply a short link that encodes a file exhibiting this behaviour please. Your code doesn't have any global variables.

**Comment by partouf** [comment]
@Busyvar can you reproduce the problem with this setup? https://godbolt.org/z/YWdPa9aTT

As far as I can see this code will work as expected. You might be hitting some undefined behaviour; for example with certain kinds of input files.

Your binVal array is also just 12 bytes, so the code will produces a SEGFAULT (the execution output will say "Program returned: 139" in this case)

Can you fill in the blanks for us here and make a link by clicking Share -> Short Link - and Paste that here?

**Comment by Busyvar** [comment]
Ok i found the case : https://godbolt.org/z/rch87EnsM
yes binval is 12 byte long which is not enought because of linebreak.
For gcc it will return 139, for tcc entries value will be always 1.

**Comment by mattgodbolt** [comment]
There's no guarantees about what happens if you use undefined behaviour: it's not really possible to reason about "what might happen". it's likely stack alignment stuff changes, or the compiler reserves more bytes for debugging....or...anything.

Whichever way this is, it's not an issue with Compiler Explorer, so I'm closing.
