### ISSUE TITLE
Enable Rust HIR and Macro Expansion for non-nightly compilers

### ISSUE THREAD

**Issue by matsjla** [compiler-explorer/compiler-explorer#3154]
You may use `RUSTC_BOOTSTRAP=1` to get it in all of them (please see https://github.com/compiler-explorer/compiler-explorer/issues/2724 as well).

_Originally posted by @ojeda in https://github.com/compiler-explorer/compiler-explorer/issues/2567#issuecomment-982461584_

**Comment by partouf** [comment]
this is now possible

![Screenshot from 2023-05-16 05-05-47](https://github.com/compiler-explorer/compiler-explorer/assets/442630/bb17b846-104c-4832-b8a2-218f37f08366)
![Screenshot from 2023-05-16 05-08-50](https://github.com/compiler-explorer/compiler-explorer/assets/442630/567a01ff-af59-4648-ab66-7c94024ced4e)
