### ISSUE TITLE
[BUG]: escape sequence bad colors

### ISSUE THREAD

**Issue by lechos22** [compiler-explorer/compiler-explorer#3156]
### Describe the bug

strings with escape sequences cause bad colouring

### Steps to reproduce

1. select python or java
2. do anything with string containing escape sequence
3. look at bytecode

### Expected behavior

dark green color should end after escape sequence

### Reproduction link

https://godbolt.org/z/rWqP6zr9E

### Screenshots

![image](https://user-images.githubusercontent.com/63498252/144745340-bd773d91-e444-47f5-953e-35ad9dcb0a68.png)

### Operating System

Windows

### Browser version

Microsoft Edge 96.0.1054.43

**Comment by lechos22** [comment]
After a check, this also occurs with java

**Comment by RubenRBS** [comment]
Hi! Thanks for the headsup.
I've tried to fix this, but the PR needs some review as I might have broken something else in the process
