### ISSUE TITLE
Where is the recommended docker image for offline networks ?

### ISSUE THREAD

**Issue by Eldadc** [compiler-explorer/compiler-explorer#3159]
### Is your feature request related to a problem? Please describe

I am working in offline network.
Where is the recommended docker image for offline networks ?
Where I can download and what is the recommended image for this great service.

Thanks

### Describe the solution you'd like

Link to downloaded image

### Describe alternatives you've considered

Link to downloaded image

### Additional context

Not applicable

**Comment by supergrecko** [comment]
CE doesn't have an official Docker image. All the Compiler Explorer images you see on DockerHub are third party. I'm also not fully sure what you mean by offline network here.
