### ISSUE TITLE
[BUG]: `std::bit_cast` is missing in armv8-a clang (trunk)

### ISSUE THREAD

**Issue by MineCake147E** [compiler-explorer/compiler-explorer#3166]
### Describe the bug

This code should be compiled correctly with `-std=c++20` option:
```c++
float ConvertALawToSingle1(uint8_t value){
    uint32_t u = (uint32_t)(int8_t)(value ^ 0b11010101);
    u <<= 19;
    u &= 0x83f80000u;
    u += 0x00040000u;
    float q = std::bit_cast<float>(u); //<= generates error: no member named 'bit_cast' in namespace 'std'
    q *= 6.64613997E+35f;
    return q;
}
```
but it doesn't.

### Steps to reproduce

1. Visit https://godbolt.org/z/93b9z8z5K
2. Select armv8-a clang (trunk) for c++
3. Set arguments to `-std=c++20 -Ofast`
4. Compile and see output panel

### Expected behavior

The assembly output should be there

### Reproduction link

https://godbolt.org/z/93b9z8z5K

### Screenshots

![image](https://user-images.githubusercontent.com/31585494/145385798-8c2e18d3-0885-4465-b792-4aaece91ce34.png)

### Operating System

Windows 10 21H2

### Browser version

Firefox 95.0 (x86-64)

**Comment by dkm** [comment]
As hinted by @partouf , looks like #4158 fixes this.
![Screenshot 2022-10-28 at 18-06-49 Compiler Explorer](https://user-images.githubusercontent.com/87603/198683055-d3c89673-d3e2-4986-a69f-864769d975ce.png)
