### ISSUE TITLE
Adjust missing AsmDocs arch message to say we don't support it

### ISSUE THREAD

**Issue by supergrecko** [compiler-explorer/compiler-explorer#3167]
> but it returns `{"error":"Unknown architecture "}` on the URL
> https://gcc.godbolt.org/api/asm/aarch64/msub
> Should it maybe return "No documentation for architecture aarch64" ?

_Originally posted by @partouf in https://github.com/compiler-explorer/compiler-explorer/issues/3117#issuecomment-990017113_

**Comment by RubenRBS** [comment]
The error handling code that appends this message can be found https://github.com/compiler-explorer/compiler-explorer/blob/d7c4eecbf7deee7ebb91be0d8d7777f4ee4cee10/lib/handlers/assembly-documentation/router.js#L53
