### ISSUE TITLE
[BUG]: Ada expanded code breaks assembly/source matching.

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#3171]
### Describe the bug

When using the GNAT Debug expanded code, the assembly/source line corresp. is broken.
 
This is caused by `-gnatDGL` that instructs GNAT to use the expanded code for debugging and this confuses CE.
Alas, removing the `D` and using `-gnatGL` dumps the expanded code in stdout.

### Steps to reproduce

1. open some Ada editor
2. open GNAT debug expanded pane
3. assembly is incorrectly mapped in source.

### Expected behavior

should work :D

### Reproduction link

https://godbolt.org/z/zdqTncEYG

### Screenshots

Not applicable
![20211210_21h23m27s_grim](https://user-images.githubusercontent.com/87603/145636928-58a64639-a2f5-46ba-a72e-3a08e7409bdf.png)

**Comment by partouf** [comment]
Doubt this is fixable, the assembly says it and we listen, that's usually the correct thing to do.
Though I guess maybe we could be like if the Debug thing is open, we don't highlight the editor's source, but the Debug editor instead?

**Comment by dkm** [comment]
I could also split in 2 processes: 1 for assembly and 1 for the .dg. Highlighting the debug would also work, but the debug info are in fact pointing to both the original source and the .dg... I guess the easiest solution is to simply split in 2 processes or find a way to have the dump not sent to stdio (doubt it is possible).
