### ISSUE TITLE
[LIB REQUEST] graphics.h

### ISSUE THREAD

**Issue by jomin2004** [compiler-explorer/compiler-explorer#3176]

**Comment by supergrecko** [comment]
Hello there,

I'm not too sure which graphics.h you are referring to here as it's not a standard library header, and appears to be "something once bundled with Borland and/or Turbo C++, in the 90's". Quoting from StackOverflow https://stackoverflow.com/a/7860668/14996499

If this is what you're referring to, could you please provide some more information about this library? Thanks!
