### ISSUE TITLE
[BUG]: MSVC compilers difference between C and C++

### ISSUE THREAD

**Issue by ojeda** [compiler-explorer/compiler-explorer#3179]
### Describe the bug

The list of MSVC compilers for C is different than the ones for C++.

In particular, it is not possible to use the latest MSVC compilers for C (as a workaround, one can use the C++ language and pass `/TC` manually).

Perhaps the potential script of https://github.com/compiler-explorer/compiler-explorer/issues/2431 could also handle this.

It would be interesting to have MSVC for C well-supported, since they committed to support the C standard about a year ago: https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/. In addition, CE is routinely used by WG14 members.

### Steps to reproduce

1. Pick C language and see the available MSVC compilers.
2. Pick C++ language and see the available MSVC compilers.
3. Compare.

### Expected behavior

The compilers that can be used for both C and C++ are available for both languages, with the same versions.

**Comment by partouf** [comment]
This doesn't really have anything to do with #2431 as the MSVC compilers are hosted in a different way at Microsoft.
We have previously worked on implementing the C side (https://github.com/compiler-explorer/infra/pull/465) but last we asked about that they were unable to merge it into their own repo.

Perhaps @timmy-ms knows more the status of adding the C compilers?

Otherwise I will close

**Comment by AaronBallman** [comment]
Please don't close this issue, it's a pretty big frustration I have as well. Switching to C++ and using /TC is a workaround, but it's still a problem when you want to compare results against other C compilers. e.g., if I want to demonstrate how MSVC compares to Tendra, I basically can't.

**Comment by partouf** [comment]
the C compilers are now live

**Comment by ojeda** [comment]
Thanks a lot!

**Comment by AaronBallman** [comment]
Thank you for this!
