### ISSUE TITLE
6502 execution things

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#3182]
I started working on trying to get 6502 execution related things.

The first thing I started on was to compile a SSD file to load into a BBC Micro emulator
* Install MMB Utils so we can create SSD files https://github.com/compiler-explorer/infra/compare/bbcmicrothings
* Add a tool to create a disk from 6502 code https://github.com/compiler-explorer/compiler-explorer/compare/bbcmicrothings

## Things that work

* Creating SSD files
* Assembling "something" - although it might be nicer to have to as part of the compiler instead of the tool

### Setting the boot option

Not sure if that's possible with MMB Utils

I read here https://archive.retro-kit.co.uk/bbc.nvg.org/faq.php3.html that you can set it up manually in the bbc by typing `*OPT 4,3` - that makes it boot on the next restart, but would be nice to set that up beforehand.

### Compiling/assembling a correct binary from the asm

I read somewhere that someone was working on more support for the BBC Micro in cc65, but progress seems to have stalled.

A solution might be this thing https://github.com/cc65/wiki/wiki/The-.ORG-directive , but there's more directives in the standard ASM output that I'm not sure of that might be in the way.

**Example of current progress** 
![image](https://user-images.githubusercontent.com/442630/146109856-ba258c5e-e553-48f0-be87-642153c6e241.png)

The SSD file is currently output as base64, and translating that back to binary is readable by jsbeeb, but obviously the file doesn't actually run.

**Comment by mattgodbolt** [comment]
If we just want an assembler, then I use my pal Rich's https://github.com/stardot/beebasm beebasm, which can build directly to a disk image.

**Comment by partouf** [comment]
> If we just want an assembler, then I use my pal Rich's https://github.com/stardot/beebasm beebasm, which can build directly to a disk image.

I saw that one yes, that might be a good one for the ASM compilers to implement.

But typing C or C++ is always nicer ;)

**Comment by mattgodbolt** [comment]
Absolutley! :) Pinging @richtw1 :)

**Comment by partouf** [comment]
Added beebasm support as ASM compiler, probably need a better AsmParser for it, but otherwise it's fine. The disk it produces is good too and can be loaded up.
We could have a thing in the result offering a download, but it would probably be nicer to autoload it in jsbeeb or virtual.bbcmic.ro - would need some hacking to support a base64 disk, probably as a hash-thing sort of like our full link.

Plenty o' things to do

**Comment by partouf** [comment]
While fiddling around with jsbeeb I realized that an ssd even if zipped but encoded in base64, is just way too many characters still to use in a URL. I think it's a no-go to go this route.

Offering a download would be the easiest, but it's not very user-friendly.

Maybe instead we could host the files somewhere. But it would be a lot better to have logins for CE so we could link services up.

**Comment by partouf** [comment]
An even crazier option would be to embed an emulator inside CE, too crazy probably

**Comment by mattgodbolt** [comment]
> An even crazier option would be to embed an emulator inside CE, too crazy probably

I hear some beeb emulators written in js are available and designed for embedding ;)

**Comment by partouf** [comment]
Now Live
