### ISSUE TITLE
Note when updating prometheus client

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#3187]
I'm using the newer prom-client version 14.0.1 in a different project, and this code I copy pasted from CE crashed.
It seems that the metrics function is now asyncronous and you need to await it before sending it to the result of the express handler.

https://github.com/compiler-explorer/compiler-explorer/blob/0e34de6d9b898d9ac1330c653668d0e1832f054e/app.js#L560

**Comment by jeremy-rifkin** [comment]
I think we can close this as we've now updated to 14.0.1
