### ISSUE TITLE
[BUG]: asm: bad inputs get stuck on 'Compiling...' forever

### ISSUE THREAD

**Issue by Alcaro** [compiler-explorer/compiler-explorer#3198]
### Describe the bug

As title says, bad asm inputs get stuck on 'Compiling...' forever.

### Steps to reproduce

1. Pick language Assembly
2. Enter something that won't compile

### Expected behavior

\<Compilation failed>

\# For more information see the output window

(or should it say "Assembling failed"?)

### Actual behavior:

\<Compiling...> (or, depending on how fast the backend responds, it may contain output corresponding to a previous input, or a blank string)

Investigation in dev tools reveal that failing C input has a `"asm": [{"text": "<Compilation failed>","source": null,"labels": []}]}` in response json. For asm, the field is absent (not even `"asm":[]` or `"asm":null`).

### Reproduction link

https://godbolt.org/z/cMKKodcKe

### Screenshots

![image](https://user-images.githubusercontent.com/5085186/146946204-d8a19168-e5d5-4960-8dda-47930a65397d.png)

### Operating System

Lubuntu 21.10

### Browser version

Firefox 95

Discovered by user Tachyon on discord.

**Comment by RubenRBS** [comment]
Hi! Thanks for taking the time to file the issue, and sorry that it took so long for us to get back to you.

I've now (hopefully) fixed the error. It should go live the next time we push an update to the site :)
