### ISSUE TITLE
[BUG]: removeFilters query param does not work with JSON body

### ISSUE THREAD

**Issue by gpanders** [compiler-explorer/compiler-explorer#3205]
### Describe the bug

The `removeFilters` query parameter does not work for API requests that with a JSON body.

### Steps to reproduce

Create the file `godbolt.json` with the contents:

```json
{
    "source": "short scale3(short x, short y, short z) {\nshort t = 10*y + z + y*x;\nreturn t;\n}",
    "options": {}
}
```

Then run `curl 'https://godbolt.org/api/compiler/g111/compile?removeFilters=intel' -H 'Content-Type: application/json' --data-binary @godbolt.json`

### Expected behavior

The returned assembly should be in ATT syntax.

Note that this works as expected when using

```console
curl 'https://godbolt.org/api/compiler/g111/compile?removeFilters=intel' --data-binary 'short scale3(short x, short y, short z) {short t = 10*y + z + y*x;return t;}'
```

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

N/A

### Browser version

N/A

**Comment by partouf** [comment]
`removeFilters` only works for the non-rest API

With the rest API you're supposed to supply the filters in the JSON (https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/API.md#post-apicompilercompiler-idcompile---perform-a-compilation)

For example:
```
"options": {
        "filters": {
             "intel": false
        }
}
```

**Comment by gpanders** [comment]
> `removeFilters` only works for the non-rest API
> 
> With the rest API you're supposed to supply the filters in the JSON (https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/API.md#post-apicompilercompiler-idcompile---perform-a-compilation)
> 
> For example:
> 
> ```
> "options": {
>         "filters": {
>              "intel": false
>         }
> }
> ```

Unfortunately this clobbers the other default filters, so it's not possible to say "use the default filters but set `intel` to false".

**Comment by partouf** [comment]
These are the defaults, they haven't changed in a while so you can use it as a template:

```
{
    binary: false,
    execute: false,
    demangle: true,
    intel: true,
    commentOnly: true,
    directives: true,
    labels: true,
    optOutput: false,
    libraryCode: false,
    trim: false,
}
```

**Comment by gpanders** [comment]
That works, even if it is fairly verbose to change just one option. A `removeFilter` equivalent for the REST API would be nice though. I'm happy to send a PR if that's something the maintainers are open to.
