### ISSUE TITLE
Something weird going on with outside user PR workflows

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#3212]
### Describe the bug

https://github.com/compiler-explorer/compiler-explorer/runs/4612245773?check_suite_focus=true#step:12:11

### Steps to reproduce

-

### Expected behavior

Shouldn't be running the deploy job

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by mbitsnbites** [comment]
Is it this change that caused this?

https://github.com/compiler-explorer/compiler-explorer/commit/0e34de6d9b898d9ac1330c653668d0e1832f054e#diff-d12cc372635ec91131d632d6f78a0785c6fa4fd4d33447e37212c7bcc083a9cb

**Comment by partouf** [comment]
> Is it this change that caused this?
> 
> [0e34de6#diff-d12cc372635ec91131d632d6f78a0785c6fa4fd4d33447e37212c7bcc083a9cb](https://github.com/compiler-explorer/compiler-explorer/commit/0e34de6d9b898d9ac1330c653668d0e1832f054e#diff-d12cc372635ec91131d632d6f78a0785c6fa4fd4d33447e37212c7bcc083a9cb)

It made it surface, but is not the root cause.
The workflow is supposed to differentiate between branches owned by compiler-explorer and those of others.

**Comment by partouf** [comment]
fixed
