### ISSUE TITLE
New privacy policy is not shown on ipad

### ISSUE THREAD

**Issue by hanickadot** [compiler-explorer/compiler-explorer#3214]
### Describe the bug

When I open compiler-explorer.com (also godbolt.org) on my ipad a floating window saying “New Privacy Policy. Please take a moment to read it” is shown, but no content there. Only button “close”

### Steps to reproduce

^^ in description

### Expected behavior

window should contain the privacy policy text

### Reproduction link

Not applicable

### Screenshots

![IMG_0332](https://user-images.githubusercontent.com/6557263/147335274-14847210-53be-4720-bd92-4efd9d275cd5.png)

### Operating System

ipad pro with ios 15.2

### Browser version

safari in ios 15.2

**Comment by partouf** [comment]
Not actually related to browser, similar empty window in chrome on desktop

**Comment by partouf** [comment]
Cookie policy window doesn't open at all (script error)

**Comment by mattgodbolt** [comment]
Wow, good find: thanks both!
