### ISSUE TITLE
[BUG]: Internal Compiler Explorer error: TypeError: Cannot read property 'localeCompare' of undefined

### ISSUE THREAD

**Issue by Fedr** [compiler-explorer/compiler-explorer#3229]
### Describe the bug

For this simple C++ program:
```
#include <iostream>

int main() 
{
  for(struct { bool OK = true; } s; s.OK; s.OK = false)
    std::cout << "Hello, world!\n";
}
```
and not the latest MSVC, e.g. 19.30 this error is shown:
```
Internal Compiler Explorer error: TypeError: Cannot read property 'localeCompare' of undefined
    at C:\compiler-explorer\lib\asm-parser-vc.js:296:36
    at Array.sort (<anonymous>)
    at AsmParser.resultObjectIntoArray (C:\compiler-explorer\lib\asm-parser-vc.js:273:23)
    at AsmParser.processAsm (C:\compiler-explorer\lib\asm-parser-vc.js:269:21)
    at AsmParser.process (C:\compiler-explorer\lib\asm-parser.js:568:21)
    at Win32VcCompiler.processAsm (C:\compiler-explorer\lib\base-compiler.js:808:25)
    at C:\compiler-explorer\lib\base-compiler.js:777:34
    at async run (C:\compiler-explorer\node_modules\p-queue\dist\index.js:255:29)
Compiler returned: -1
```

### Steps to reproduce

Open https://gcc.godbolt.org/z/fP1eTehaG

### Expected behavior

I expect too see compiler output and not any text from Compiler Explorer.

### Reproduction link

https://gcc.godbolt.org/z/fP1eTehaG

### Screenshots

![image](https://user-images.githubusercontent.com/3136125/147938488-317d94c6-5712-4266-9192-d1685b5a4143.png)

### Operating System

Windows 10

**Comment by partouf** [comment]
dupe #3125 #2386 #2093

It's already fixed in the code, but Microsoft.

**Comment by Fedr** [comment]
@partouf , I see that the related issue is open for a long time. Is there a workaround for now to compile my program using various versions of MSVC in Compiler Explorer?

**Comment by partouf** [comment]
> @partouf , I see that the related issue is open for a long time. Is there a workaround for now to compile my program using various versions of MSVC in Compiler Explorer?

Not that I'm aware of, except for running Compiler Explorer locally.
