### ISSUE TITLE
[BUG]: No color scheme applied unless "Compile to binary" is activated, which shows unrelated code

### ISSUE THREAD

**Issue by creaothceann** [compiler-explorer/compiler-explorer#3245]
### Describe the bug

Also happens with the oldest compiler version 2.6.0 (you need to remove the -Cf and -Cp parameters).

### Steps to reproduce

1. visit the reproduction link
2. check output window
3. activate "Output..." -> "Compile to binary"
4. check output window

In the second case the output window seems to show all subroutines in the translation unit, from AssignFile to Finalize, and the  Test routine with the line coloring at the very end.

### Expected behavior

Only the subroutines in the source code should be shown, with the line coloring.

### Reproduction link

https://godbolt.org/z/Trhn1h3c1

### Screenshots

Not applicable

### Operating System

Windows 10 64-bit

### Browser version

Firefox / Chrome / Opera, most recent versions

**Comment by jeremy-rifkin** [comment]
I think this is now resolved, feel free to re-open if I have missed something
