### ISSUE TITLE
[BUG]: rustc_codegen_gcc not updating?

### ISSUE THREAD

**Issue by antoyo** [compiler-explorer/compiler-explorer#3256]
### Describe the bug

It seems the compiler rustccggcc-master is not being updated.
The version shown [in here](https://godbolt.org/z/s9WTrdx8o) for example (`rustc 1.56.0-nightly (ccffcafd5 2021-08-11)`) is 5 months old.
I can also confirm that it generates code that should not be generated anymore.

**Note:** I think I might know what could cause this issue: I sometimes rewrote the history in this [git repo](https://github.com/rust-lang/rustc_codegen_gcc) and also in [this one](https://github.com/antoyo/gcc). Could that be the problem?

### Steps to reproduce

Compile any Rust code with rustccggcc-master and look at the compiler version.

### Expected behavior

The version should be the same (or close to) the one [in this file](https://github.com/rust-lang/rustc_codegen_gcc/blob/master/rust-toolchain) (nightly-2021-12-30).

### Reproduction link

https://godbolt.org/z/s9WTrdx8o

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment]
Hi! We build here https://github.com/compiler-explorer/misc-builder/blob/main/build/build-rustc-cg-gcc.sh ).  We have a daily build scripted here: https://github.com/compiler-explorer/compiler-workflows/actions/workflows/build-daily-rustc-cg-gcc_master.yml

The most recent build is: https://github.com/compiler-explorer/compiler-workflows/runs/4811496661?check_suite_focus=true

which seems to "skip" as it believed nothing had changed. I'll poke about a bit more: thanks for the clue about rewriting history.

**Comment by dkm** [comment]
Note that the git repository should have been changed from @antoyo personnal one to rust-lang (see https://github.com/compiler-explorer/misc-builder/blob/main/build/build-rustc-cg-gcc.sh ). Not sure if I've messed up something when switching it ?

**Comment by mattgodbolt** [comment]
That said, it built a few days ago: https://github.com/compiler-explorer/compiler-workflows/runs/4783622342?check_suite_focus=true

**Comment by antoyo** [comment]
Yeah, it seems to be building the correct version:
https://github.com/compiler-explorer/compiler-workflows/runs/4783622342?check_suite_focus=true#step:5:325

**Comment by mattgodbolt** [comment]
We correctly determine the "latest" version:

```
2022-01-14 15:15:42,665 lib.installation INFO     compilers/rust/newer/nightly/rustc-cg-gcc master: Most recent rustc-cg-gcc-master is 20220112                                                                                                                                         
```

Manually forcing an install:
```
2022-01-14 15:16:28,705 lib.installation INFO     Fetching https://s3.amazonaws.com/compiler-explorer/opt/rustc-cg-gcc-master-20220112.tar.xz (140050556 bytes)                                                                                                                         
2022-01-14 15:16:33,456 lib.installation INFO     100% of https://s3.amazonaws.com/compiler-explorer/opt/rustc-cg-gcc-master-20220112.tar.xz
2022-01-14 15:16:33,462 lib.installation INFO     Piping to tar Jxf -                                                                       
2022-01-14 15:16:57,047 lib.installation INFO     compilers/rust/newer/nightly/rustc-cg-gcc master failed to install: Missing source '/opt/c
ompiler-explorer/staging/rustc-cg-gcc-master-20220112'                                                                                      
Traceback (most recent call last):                                                                                                          
  File "/home/ubuntu/infra/bin/lib/ce_install.py", line 192, in main                                                                        
    if installable.install():                                                                                                               
  File "/home/ubuntu/infra/bin/lib/installation.py", line 702, in install                                                                   
    self.install_context.move_from_staging(self.local_path, self.install_path)                                                              
  File "/home/ubuntu/infra/bin/lib/installation.py", line 191, in move_from_staging                                                         
    raise RuntimeError(f"Missing source '{source}'")                                                                                        
RuntimeError: Missing source '/opt/compiler-explorer/staging/rustc-cg-gcc-master-20220112'                                                  
                                                                                                                                            
0 packages installed OK, 0 skipped, and 1 failed installation                                                                               
Failed:                                                                                                                                     
  compilers/rust/newer/nightly/rustc-cg-gcc master                                                                                          

```

....aha! it's been failing to install. Will continue to investigate.

**Comment by mattgodbolt** [comment]
(and yes, we need better monitoring of this)

**Comment by mattgodbolt** [comment]
Seems like I broke it somehow. the untarred directory has the tar name in it!
```
Jan/14 15:16 admin-node~/infra (main|✔) 32.8s $ ls /opt/compiler-explorer/staging/rustc-cg-gcc-master-20220112.tar.xz/
bin/  etc/  lib/  libexec/  share/  sysroot/                                                                          
Jan/14 15:18 admin-node~/infra (main|✔) $ ls /opt/compiler-explorer/staging/                                          
rustc-cg-gcc-master-20220112.tar.xz/                                                                                  
```

**Comment by dkm** [comment]
Should be fixed by https://github.com/compiler-explorer/misc-builder/pull/25

**Comment by dkm** [comment]
It won't build until it sees a different SHA1, so we'll have to wait for a new version to see if it works now @antoyo

**Comment by antoyo** [comment]
Ok, I pushed a commit. Let's see tomorrow if it's fixed.
Thanks!

**Comment by antoyo** [comment]
I believe it's fixed.
It's hard to confirm because caching seems to be involved, but if I change the code, I get the expected codegen.
However, the version shown is still `2021-08-11`, which might be due to caching.

**Comment by dkm** [comment]
That's possible that the version number is cached somewhere... But if you can confirm codegen is really from latest code, that's great.

One way to "see" it, is to disable filters and check the assembly file near the end https://godbolt.org/z/396nMs919

```
        .ident  "GCC: (Compiler-Explorer-Build-cggcc-e690fb12731eb5f86d4c88400a344f65607af385-gcc-13789ac0a9f3e2ee42e38927e657a910df793de5) 12.0.0 20220102 (experimental)"
```
We can see the diff between the info version in the UI `ccff.....` and the above.

**Comment by dkm** [comment]
Closing it, but don't hesitate to reopen if you think it's still incorrect :)
