### ISSUE TITLE
[BUG]: clang trunk and clang assertions trunk failing

### ISSUE THREAD

**Issue by davidstone** [compiler-explorer/compiler-explorer#3257]
### Describe the bug

[F][2022-01-15T07:19:26+0000][1] bool subproc::runChild(nsjconf_t*, int, int, int, int)():448 Launching child process failed
Compiler returned: 255

### Steps to reproduce

Select x86-64 clang, either trunk or assertions trunk, and compile anything.

### Expected behavior

The compiler launches.

### Reproduction link

https://godbolt.org/z/GchzcE4KT

### Screenshots

Not applicable

**Comment by apmorton** [comment]
```
[E][2022-01-15T08:05:21+0000][1] void subproc::subprocNewProc(nsjconf_t*, int, int, int, int, int)():205 execve('/opt/compiler-explorer/clang-trunk/bin/clang++') failed: No such file or directory
[F][2022-01-15T08:05:21+0000][1] bool subproc::runChild(nsjconf_t*, int, int, int, int)():448 Launching child process failed
[E][2022-01-15T08:05:21+0000][80707] int nsjail::standaloneMode(nsjconf_t*)():256 Couldn't launch the child process
Compiler returned: 255
```

```
# ls -al /opt/compiler-explorer/clang-trunk*/bin/clang++
lrwxrwxrwx 1 root root 5 Jan  9 01:35 /opt/compiler-explorer/clang-trunk-20220109/bin/clang++ -> clang
lrwxrwxrwx 1 root root 5 Jan 10 01:32 /opt/compiler-explorer/clang-trunk-20220110/bin/clang++ -> clang
lrwxrwxrwx 1 root root 5 Jan 11 01:35 /opt/compiler-explorer/clang-trunk-20220111/bin/clang++ -> clang
lrwxrwxrwx 1 root root 5 Jan 12 01:36 /opt/compiler-explorer/clang-trunk-20220112/bin/clang++ -> clang
lrwxrwxrwx 1 root root 5 Jan 13 01:36 /opt/compiler-explorer/clang-trunk-20220113/bin/clang++ -> clang
lrwxrwxrwx 1 root root 5 Jan 14 01:34 /opt/compiler-explorer/clang-trunk-20220114/bin/clang++ -> clang

# ls -al /opt/compiler-explorer/clang-trunk/bin/clang++
ls: cannot access '/opt/compiler-explorer/clang-trunk/bin/clang++': No such file or directory
```

looks like clang stopped shipping the clang++ symlink or it became optional and we need to ask for it in the build?
I have manually created these links for the moment, but we will need to update our configs to permanently fix this.

**Comment by partouf** [comment]
there's a commit that did something with the CMake files and got reverted today, maybe it's got something to do with that ( https://github.com/llvm/llvm-project/commit/6e52bfe09d3ab3ae6c43c079d06ebeb7bb241dec )
Though there's so much going on in llvm, it's hard to know what it could really be

**Comment by apmorton** [comment]
hmm - maybe?
comparing clang-trunk-20220114 and clang-trunk-20220115 it looks like a _lot_ of symlinks are missing - guess we will have to see if it "just works" after tonights build or if something is actually broken on our end now.

These are the commits between our build on the 14th and 15th - https://github.com/llvm/llvm-project/compare/1441ffe6a6da90e9c4800914eb0005b1087aa5d2...efeb50197091b2ade24c00b9d55814bc433a7fd1

Nothing jumped out at me besides the commit you already linked.

**Comment by partouf** [comment]
for 20220116 last night, it seems the symlinks have returned in the build of clang-trunk and assertions trunk

i think we can assume it's fixed
