### ISSUE TITLE
[BUG]: Something is going wrong when asking for Rust MIR

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#3262]
### Describe the bug

Asking the Rust MIR for the simple square example can return :
```
error: could not copy "/app/output.example.955dbcfe-cgu.0.rcgu.s" to "/app/output.s": No such file or directory (os error 2)

error: aborting due to previous error

Compiler returned: 1
```

### Steps to reproduce

1. open the Rust square example, only assembly enabled.
2. Open the LLVM-IR pane [this should work, and looks to be needed for the error to happen
3. Open the Rust MIR

### Expected behavior

Have the Rust MIR

### Reproduction link

https://godbolt.org/z/Gox17qaqb

### Screenshots

Not applicable
![Screenshot 2022-01-16 at 21-21-59 Compiler Explorer](https://user-images.githubusercontent.com/87603/149676675-43abc2d9-5f2a-4586-8baa-562a960a5313.png)

**Comment by matsjla** [comment]
Yep, I think there might be some funky things going on with the arguments and file locations we are passing to Rustc somewhere in the pipeline. I remember coming across something similar in development, but I was never able to reproduce it.

**Comment by jeremy-rifkin** [comment]
This looks like it's working correctly now
