### ISSUE TITLE
[BUG]: Short link doesn't always appear with `Ctrl-s`

### ISSUE THREAD

**Issue by ShadowMitia** [compiler-explorer/compiler-explorer#3264]
### Describe the bug

When you have `Ctrl-s` create a share link and not download to local file there is a weird issue where when you call `Ctrl-s`, then dismiss the short link panel, and then redo `Ctrl-s` you get "save page to file" instead of the short link box.

It seems that something loses focus, because it doesn't happen if you press the source area before calling `Ctrl-s`.

Note this also happens when you hit `Ctrl-s` while inside the short link box: it gives you "save page to file".

### Steps to reproduce

1. Visit compuler explorer
2. Hit `Ctrl-s`
3. Dismiss with `Esc`
4. Hit `Ctrl-s` again

### Expected behavior

The expected behaviour would be to get the short link box again.

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Pop!_OS 21.10 x86_64

### Browser version

Firefox Nightly 98.0a1 (2022-01-15) (64-bit)

**Comment by RubenRBS** [comment]
Thanks for the report! Keyboard events are always a bit tricky to get right. I'll see what I can do
