### ISSUE TITLE
[REQUEST]: Have the behaviour of `Ctrl-s` when set to creating a share link not pop up the dialog box

### ISSUE THREAD

**Issue by ShadowMitia** [compiler-explorer/compiler-explorer#3265]
### Is your feature request related to a problem? Please describe

Context: https://twitter.com/AllisonVacanti/status/1481754008662458368

If you have `Ctrl-s` set to creating a share link, it always opens a dialog box. 
`Ctrl-s` is the type of shortcut that can get called a lot (muscle memory...), having the dialog open up each time is a bit annoying.

### Describe the solution you'd like

In this case I would prefer if the link generated is done in the background with maybe a discrete notification/toast that it has been copied to clipboard.

### Describe alternatives you've considered

I have not considered alternatives.

### Additional context

Not applicable

**Comment by dead-tech** [comment]
I would like to work on this if possible.

My idea was to introduce a new setting that would let you control whether to show the dialog box when hitting `Ctrl-s`. When this checkbox is not checked it would default to copying the short link to the clipboard.

**Comment by partouf** [comment]
> I would like to work on this if possible.
> 
> My idea was to introduce a new setting that would let you control whether to show the dialog box when hitting `Ctrl-s`. When this checkbox is not checked it would default to copying the short link to the clipboard.

Do try if you want to, but there are a bunch of browser protections that might make this technically very difficult.

**Comment by mattgodbolt** [comment]
See also #3289 (originally by @RubenRBS but I had to revert and then reinstate it for a few minor issues) -- some work has been done in this direction and if you're interested in taking a look at that branch I'm sure we'd be happy for the help!

**Comment by partouf** [comment]
this is live
