### ISSUE TITLE
[BUG]: In Vim keyboard mode, Ctrl+c doesn't enter normal mode anymore

### ISSUE THREAD

**Issue by ChristianHein** [compiler-explorer/compiler-explorer#3267]
### Describe the bug

It used to be possible to exit Vim's insert and visual modes using the ```Ctrl```+```c``` keyboard shortcut, putting the user into normal mode. Roughly one or two months ago this shortcut stopped working. The shortcut now does nothing in Vim keyboard mode, as far as I can tell.
I prefer this shortcut to ```Esc``` and it's what I'm used to from other Vim implementations.

I've tested this issue on both Firefox and Chrome.

Side notes:
- The shortcut doesn't work for exiting command mode either (press ```:``` to enter). But I believe this has been true for much much longer and isn't strictly a regression.
- A possibly related issue, although it's not clear if they are also describing a regression: #3249

### Steps to reproduce

1. Visit godbolt.org
2. Open a source editor panel
3. Activate Vim keybindings
4. Press ```i``` to enter insert mode or ```v``` to enter visual mode
5. Press ```Ctrl```+```c```

### Expected behavior

You should be in Vim's normal mode. This would be indicated by "--NORMAL--" being displayed in the Vim status bar.

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Manjaro Linux 21.2.1

### Browser version

Mozilla Firefox 96.0 (64-bit), Google Chrome Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by ChristianHein** [comment]
This problem has since been fixed! I'm able to exit insert and visual mode using `Ctrl`+`c` again just fine in both Firefox 122.0.1 and Chrome 121.0.6167.160 on Linux. No idea when this change happened or what might have caused it.

**Comment by mattgodbolt** [comment]
Thanks for letting us know!
