### ISSUE TITLE
[REQUEST]: Install MSVC with support of /std:c11

### ISSUE THREAD

**Issue by pmor13** [compiler-explorer/compiler-explorer#3270]
### Is your feature request related to a problem? Please describe

Installed MSVC do not support `/std:c11`.

### Describe the solution you'd like

Install MSVC with support of `/std:c11`.

### Describe alternatives you've considered

None.

### Additional context

Not applicable

**Comment by mattgodbolt** [comment]
Hi - this is already the case, for example [here](https://godbolt.org/z/G3Wh6MrhP)

**Comment by pmor13** [comment]
The `/std:c11` is for C, not for C++. Change language to C.

**Comment by pmor13** [comment]
Here is the list of MSVC for C:
![image](https://user-images.githubusercontent.com/4587883/150526732-9871ccc0-2f0f-4a2b-a453-b241b04fe85a.png)
None of them support `/std:c11`.

**Comment by pmor13** [comment]
@mattgodbolt Consider the prev. comments.

**Comment by mattgodbolt** [comment]
Right - I missed this really should be: "Please install MSVC's C compilers". I'll ask Microsoft.

**Comment by timmy-ms** [comment]
Working on this. Couple weeks hopefully.

**Comment by pmor13** [comment]
@timmy-ms and all: FYI: the workaround is to use C++ compilers in C mode:
```
$ gcc -xc -std=c11
$ clang -xc -std=c11
$ icc -xc -std=c11
$ cl /TC /std:c11
```

**Comment by pmor13** [comment]
@timmy-ms Out of curiosity: any updates?

**Comment by timmy-ms** [comment]
I am not going to set -std=c11 in the global config, so you need to add that flag manually, but the MSVC C compilers are now in the list.

**Comment by timmy-ms** [comment]
Deployed on 6/3/2022
