### ISSUE TITLE
[BUG]: Inline ASM confuses AT&T and Intel syntax, output differs from actual GCC 7.2

### ISSUE THREAD

**Issue by JubilantJerry** [compiler-explorer/compiler-explorer#3271]
### Describe the bug

The following x86 program generates different assembly for two logically identical functions:
```
#include "immintrin.h"
#include "stdint.h"

__m256i mask_11111111(int32_t x) {
  __m128i xzzz = _mm_cvtsi32_si128(x);
  __m256i result;
  asm("vpbroadcastd %1, %0": "=x"(result): "x"(xzzz));
  return result;
}

__m256i mask_11111111_v2(int x) {
  return _mm256_broadcastd_epi32(_mm_cvtsi32_si128(x));
}
```

The `vpbroadcastd` shows up with two different operand orders in the two compiled outputs. GodBolt cannot make its mind on whether the output should be in Intel syntax or AT&T syntax. The two functions should both do the same thing, but according to GodBolt one of them has the operands in the wrong order.

### Steps to reproduce

Godbolt: Copy the program text into the C++ source, set the compiler to gcc-7.2 and use the flags `-std=gnu++17 -O3 -march=broadwell`.

gcc72: Copy the program text into the file `asm.cpp`, then execute `gcc72 -std=gnu++17 -O3 -march=broadwell asm.cpp -S -o asm.S && less asm.S` or `gcc72 -std=gnu++17 -O3 -march=broadwell asm.cpp -c -o asm.o && objdump -D asm.o | less`

### Expected behavior

The output according to GodBolt:
```
mask_11111111(int):
        vmovd   xmm0, edi
        vpbroadcastd xmm0, ymm0
        ret
mask_11111111_v2(int):
        vmovd   xmm0, edi
        vpbroadcastd    ymm0, xmm0
        ret
```
The two functions do not match in operand order.

The output according to g++-7:
```
0000000000000000 <_Z13mask_11111111i>:
   0:   c5 f9 6e c7             vmovd  %edi,%xmm0
   4:   c4 e2 7d 58 c0          vpbroadcastd %xmm0,%ymm0
   9:   c3                      ret
   a:   66 0f 1f 44 00 00       nopw   0x0(%rax,%rax,1)

0000000000000010 <_Z16mask_11111111_v2i>:
  10:   c5 f9 6e c7             vmovd  %edi,%xmm0
  14:   c4 e2 7d 58 c0          vpbroadcastd %xmm0,%ymm0
  19:   c3                      ret
```
The two functions match in operand order.

Attempting to switch the operand order in the inline ASM results in compilation failure for gcc72, but GodBolt accepts either permutation.

### Reproduction link

https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:1,endLineNumber:14,positionColumn:1,positionLineNumber:14,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:'%23include+%22immintrin.h%22%0A%23include+%22stdint.h%22%0A%0A__m256i+mask_11111111(int32_t+x)+%7B%0A++__m128i+xzzz+%3D+_mm_cvtsi32_si128(x)%3B%0A++__m256i+result%3B%0A++asm(%22vpbroadcastd+%251,+%250%22:+%22%3Dx%22(result):+%22x%22(xzzz))%3B%0A++return+result%3B%0A%7D%0A%0A__m256i+mask_11111111_v2(int+x)+%7B%0A++return+_mm256_broadcastd_epi32(_mm_cvtsi32_si128(x))%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g72,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-std%3Dgnu%2B%2B17+-O3+-march%3Dbroadwell',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,tree:'1'),l:'5',n:'0',o:'x86-64+gcc+7.2+(C%2B%2B,+Editor+%231,+Compiler+%231)',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

### Screenshots

Not applicable

**Comment by partouf** [comment]
This is a known issue with GCC and the regular assembly view (`-S` option), we cannot fix it.
To see what's actually compiled, you can use the Compile to Binary option, that will always be correct.
