### ISSUE TITLE
[BUG]: LLVM library isn't linked properly

### ISSUE THREAD

**Issue by Ayxan13** [compiler-explorer/compiler-explorer#3272]
### Describe the bug

Code using the LLVM library causes linker errors.

### Steps to reproduce

1. Visit gcc.godbolt.org
2. Language -> C++
3. Compiler -> x86-64 clang 13.0.0 (maybe others too)
4. Libraries -> LLVM 13.0.0
5. Output options -> Execute the code
5. Use the LLVM library. For instance:

```C++
#include <llvm/Support/raw_ostream.h>

int main() {
    llvm::outs() << "Hello World\n";
}
```

### Expected behavior

Linking and executing successfully 

### Reproduction link

https://gcc.godbolt.org/z/j19saMcKa

### Screenshots

![Screenshot from 2022-01-20 20-26-05](https://user-images.githubusercontent.com/45293675/150379946-89973d6c-7d23-4abe-9d05-c360fb817c6d.png)

### Operating System

Ubuntu 20.04.3 LTS

### Browser version

Version 97.0.4692.99 (Official Build) (64-bit)

**Comment by partouf** [comment]
Also mentioned in #2425 , we don't offer binaries for llvm and we're not sure how to do that yeet.

Because this is a dupe issue I'm closing this issue in favor of #2425

**Comment by Ayxan13** [comment]
@partouf  Maybe we should remove the option if it doesn't work? So people don't keep reporting this.

**Comment by partouf** [comment]
> @partouf Maybe we should remove the option if it doesn't work? So people don't keep reporting this.

I don't think this is wise, as similarly there are enough people that don't care about linking or execution and the currently solution is good enough for their use-cases.

**Comment by Ayxan13** [comment]
Okay, I can see that. Simply graying out the "execute" option would also.
