### ISSUE TITLE
[REQUEST]: Adding MIPS toolchains

### ISSUE THREAD

**Issue by FlyGoat** [compiler-explorer/compiler-explorer#3282]
### Is your feature request related to a problem? Please describe

I would like to have newer MIPS toolchains so I can mess with MIPS R6 and nanoMIPS.

### Describe the solution you'd like

Prebuilt MIPS toolchain released by MIPS can be found at:
https://codescape.mips.com/components/toolchain/2020.06-01/downloads.html

nanoMIPS toolchain can be found at:
https://github.com/MediaTek-Labs/nanomips-gnu-toolchain/releases/tag/nanoMIPS-2021.11-02

Perhaps just add them to install script?

And probably add MIPS targets to clang.

### Describe alternatives you've considered

Nope :-)

### Additional context

Not applicable

**Comment by dkm** [comment]
I'll take care of that !

**Comment by dkm** [comment]
First part ready for review. I've used the bare version for the Codescape toolchain as the linux one is ~8Gb.

**Comment by FlyGoat** [comment]
Thanks, it works :-)

**Comment by dkm** [comment]
Great ! I was leaving it open as I did not look at the clang part. If you still want this, please reopen. If you don't, then leave it closed, and maybe I'll add them another time :)

**Comment by FlyGoat** [comment]
Ah I'll leave it open then :-)

**Comment by dkm** [comment]
I'll also update the "vanilla" cross gcc as they are quite old.
