### ISSUE TITLE
[BUG]: Build system broken for production instances

### ISSUE THREAD

**Issue by jrtc27** [compiler-explorer/compiler-explorer#3287]
### Describe the bug

Previously we ran `make dist` during a docker build, then `make run` when running the image.

As of #3269 `make dist` is gone. I tried instead using `make prereqs` then `make run`, but `dist` and `run` used to imply a production node env, so that no longer works, it gets us a dev instance instead which we do not want in our production. I then tried the same with `NODE_ENV=production`, but `run` tries to run webpack, which requires dev dependencies. As a result I have to run `prereqs` with a dev env and then run `run` with a production one, which is silly. Moreover, a plain `make run` (not messing with `prereqs`) on its own won't work out of the box with `NODE_ENV=production` any more for the same reason.

I also am not a fan of webpack being run at run time. I would like to be able to do that up-front like used to happen, as that is a build step. The only reason it's done at run time is to make dev setups less likely to have stale data, but that is not applicable to us, we start from a clean tree on every build.

I would therefore like two things:
1. All dependencies needed for `NODE_ENV=production make run` to be present in packages.json, not some of them erroneously in devDependencies.
2. A way (I don't mind if I have to manually specify an extra make option or use a special target) to run webpack at build time and not at run time.

### Steps to reproduce

N/A

### Expected behavior

N/A

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by partouf** [comment]
So we moved the build code to a shell script https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/scripts/build-dist.sh - you should be able to run it as well ahead of time.

And then you should be able to start CE by passing `--static out/dist --dist` like we do here https://github.com/compiler-explorer/infra/blob/main/init/start.sh#L108

**Comment by jrtc27** [comment]
That shell script is exclusively for GitHub actions and specific to your build. It relies on GITHUB_RUN_NUMBER, generates more GitHub Actions stuff with GITHUB_REF and creates tarballs in dist-bin that I do not want when building a Docker image.

**Comment by mattgodbolt** [comment]
Hey all - thanks for this. I've dithered for a long time on the `devDependencies` vs normal dependencies, and it's a tricky one to crack. Maybe I'm naive about this but the rationale was "dependencies" are things needed to run at runtime in our production environment.

It makes 100% sense that `NODE_ENV=production make run` should Just Work™. I'll take a look at what it'd take for either that to work, or else something to let you get back to your previous setup. (I'll be looking later today)

Thanks for your patience, and sorry for breaking your use case.

**Comment by mattgodbolt** [comment]
> I also am not a fan of webpack being run at run time.
FWIW this is intended mainly to make development quicker. `make run` shouldn't need this though, only `make dev` so we can probably heal some wounds there too.

**Comment by jrtc27** [comment]
Thanks; it's non-critical now as I do have the workaround described in the bug report working, just documented with an XXX to move setting NODE_ENV back to before the `make prereqs`, pointing at this issue

**Comment by partouf** [comment]
> It makes 100% sense that `NODE_ENV=production make run` should Just Work™. I'll take a look at what it'd take for either that to work, or else something to let you get back to your previous setup. (I'll be looking later today)

Unless we move everything to devDependencies, this is not possible, as NODE_ENV influences the packages that are installed with npm install. That's one of the many issues why we were having so much trouble getting the Makefile to behave consistently.

**Comment by mattgodbolt** [comment]
> Unless we move everything to devDependencies

do you mean `dependencies` ?

**Comment by mattgodbolt** [comment]
Got it :) I may consider that...it'll mean our production instances will end up picking up all the test packages we care about but mayube that's OK if they're not huge, just to have a decent (ish) installation story. I'll have a think and a play around with ideas later.

**Comment by partouf** [comment]
> Got it :) I may consider that...it'll mean our production instances will end up picking up all the test packages we care about but mayube that's OK if they're not huge, just to have a decent (ish) installation story. I'll have a think and a play around with ideas later.

Perhaps it's an idea to have a script where locally the NODE_ENV is force to development so that it can run webpack, and then return to the original NODE_ENV and do a dist run.

**Comment by mattgodbolt** [comment]
> > Got it :) I may consider that...it'll mean our production instances will end up picking up all the test packages we care about but mayube that's OK if they're not huge, just to have a decent (ish) installation story. I'll have a think and a play around with ideas later.
> 
> Perhaps it's an idea to have a script where locally the NODE_ENV is forced to development so that it can run webpack, and then return to the original NODE_ENV and do a dist run.

It's also possible that using `NODE_ENV` to contro,l our webpack behaviour is hurting us here: there might be a better way.

**Comment by apmorton** [comment]
With some very minor changes build-dist could be made to work "just fine" outside GH actions and IMO is the most-proper way to build something that will run CE "in production".

In a single docker layer you could:
- clone CE and apply any config edits
- run the build-dist script
- untar the two resulting archives to some location they will be run from
- delete the CE git clone directory

The docker image will be left with just the npm production dependencies, CE code, and static assets required to run a functional site.

**Comment by mattgodbolt** [comment]
We'll discuss more - if it's not as urgent any more @jrtc27 and you have a workaround for now we'd rather come up with a way that we (the CE core devs) feel happy about :)

**Comment by jrtc27** [comment]
Sure

**Comment by mattgodbolt** [comment]
Thanks! I think we're going to make our dist script more amenable to "just work:tm:" for folks who want to build a distribution. Whether we wire that into `make dist` or not is up for debate, but certainly it won't be the Makefile doing the heavy lifting, it'll be a separate script.

**Comment by partouf** [comment]
I think we fixed this a few months ago, but let us know if there's anything not to your liking.

**Comment by jrtc27** [comment]
From looking at the Makefile changes it sounds like 1 is expected to have been fixed but not 2?

**Comment by mattgodbolt** [comment]
> A way (I don't mind if I have to manually specify an extra make option or use a special target) to run webpack at build time and not at run time.

This ought to now be the default with `make` - and if you're not running `make` directly then ensuring `NODE_ENV=production` is in your environment should do the trick! Please let me know if there's anything else here as I _think_ we're good now :)

**Comment by jrtc27** [comment]
> > A way (I don't mind if I have to manually specify an extra make option or use a special target) to run webpack at build time and not at run time.
> 
> This ought to now be the default with `make` - and if you're not running `make` directly then ensuring `NODE_ENV=production` is in your environment should do the trick! Please let me know if there's anything else here as I _think_ we're good now :)

From what I can tell `npm run webpack` is in the run target itself, no? I'd want to have a target that's just webpack+ts-compile without the actual running of app.js itself so I can do that once when building the docker image like build-dist.sh.

**Comment by mattgodbolt** [comment]
Ah got it, sorry! Yes!

If you look at how we package the site, it's now somewhat simplified and hopefully can inspire a way forward for you: the `etc/scripts/build-dist.sh` runs all the commands needed to make two tarballs: one containing static files to be served (webpacked), and one containing the server-side code, transpiled. You don't need to separate those two files (we have a CDN so ship them to separate locations), but essentially if you want to separate serving from webpacking etc, you can either use that script as a template, or look at how the `make run` works:

Build steps:
* `npm run webpack`
* `npm run ts-compile`

Then to run:
```sh
$ env NODE_ENV=production node -r esm ./out/dist/app.js --webpackContext ./out/webpack/static
```

or similar.

Please don't hestitate to ask further questions; and/or if it would be more useful to have an interactive discussion about how best for CE to make itself externally packageable, let me know and we can use DMs/email/Discord/whatever works :)
