### ISSUE TITLE
[LIB REQUEST] NUMPY and MATPLOTLIB

### ISSUE THREAD

**Issue by jflalle** [compiler-explorer/compiler-explorer#3292]
Hi,
Could you add those scientific libraries please ?
Regards.

**Comment by mattgodbolt** [comment]
Hi! Do you mean for python? If so, we currently don't have support for any libraries in python, but we'll keep track.  If not python, can you elaborate? Thank you!

**Comment by jflalle** [comment]
Hi !

Yes for python.

Thx for your answer.

Regards.

Le 25/01/2022 à 21:30, Matt Godbolt a écrit :

**Comment by RubenRBS** [comment]
Closing as duplicate of #3201
