### ISSUE TITLE
[REQUEST]: Ability to name panes

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#3303]
### Is your feature request related to a problem? Please describe

When creating many compilers for the same output (or indeed many editors), we give "Editor #1" or "Compiler x86-clang" names to things

### Describe the solution you'd like

It would be nice to somehow let users override - an example is https://godbolt.org/z/58sKjPvcc where the various tab names on the righthand pane could be named more usefully.

### Describe alternatives you've considered

na

### Additional context

Via slack (Denis Yaroshevskly)

**Comment by RubenRBS** [comment]
For anyone interested, this might be something worth to look into: https://golden-layout.com/tutorials/extending-tabs.html so that tabs can be renamed with a button in the tab itself

**Comment by dead-tech** [comment]
May I take this?

**Comment by partouf** [comment]
> For anyone interested, this might be something worth to look into: https://golden-layout.com/tutorials/extending-tabs.html so that tabs can be renamed with a button in the tab itself

It's not quite as complicated, really. We already do renaming in the editor for IDE Mode: https://github.com/compiler-explorer/compiler-explorer/blob/main/static/panes/editor.js#L1485

**Comment by partouf** [comment]
> May I take this?

Go right ahead!
