### ISSUE TITLE
[BUG]: New Arm and Riscv Gnat ADA compilers don't support intel format

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#3310]
### Describe the bug

Our default is "-masm=intel" https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/ada.defaults.properties#L10

(If it's not there, 'usually' it's automatically detected through https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/compilers/argument-parsers.js#L93 - but since GNAT doesn't seem to produce a normal `--help` this doesn't apply here.)

I think in order to fix this we can set `intelAsm` to empty in the arm and riscv compiler groups https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/ada.amazon.properties#L34

### Steps to reproduce

GNAT Riscv or Arm and have intel check on

### Expected behavior

don't allow selection if the compiler doesn't support it

**Comment by partouf** [comment]
cc @dkm

**Comment by dkm** [comment]
In the amazon properties, the intelAsm property has been moved to the correct group, leaving it empty for other compilers. The filter is still active but does nothing. I'll see how to have this filter correctly disabled.
