### ISSUE TITLE
[BUG]: clang trunk debug info passes filters now

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#3322]
### Describe the bug

also, I don't know if you noticed, but clang trunk now emits debug info that gets past the CE filter
https://cpplang.slack.com/archives/C28NX7947/p1643857639740079)
see the .Ldebug_list_header_start0: label at the end of https://godbolt.org/z/vvxE4E7v3

### Steps to reproduce

follow link, observe _Ldebug stuff

### Expected behavior

should be filtered

### Reproduction link

https://godbolt.org/z/vvxE4E7v3

### Screenshots

Not applicable

**Comment by partouf** [comment]
I'm guessing it gets passed the Unused filter because of this stuff in front?
Weakly referenced or something?

Some weird stuff going on, I can tell you that much.

```
.L.str.2:
        .asciz  "generic"
        .size   .L.str.2, 8

        .type   .L.str.6,@object                # @.str.6
.L.str.6:
        .asciz  "basic_string: construction from null is not valid"
        .size   .L.str.6, 50

        .section        .debug_loclists,"",@progbits
        .long   .Ldebug_list_header_end0-.Ldebug_list_header_start0 # Length
.Ldebug_list_header_start0:
```

**Comment by partouf** [comment]
tried this in the c++ asm-parser, and it works as expected there

**Comment by jeremy-rifkin** [comment]
I think this appears to be resolved
