### ISSUE TITLE
C# code is not shown as optimized

### ISSUE THREAD

**Issue by gfoidl** [compiler-explorer/compiler-explorer#3325]
https://github.com/compiler-explorer/compiler-explorer/pull/3168 added support for C#, but as it looks the output isn't optimized and looks more like a debug-output.
Different compiler-flags as listed in the PR's description and some comments don't affect the output neither.

E.g. for https://godbolt.org/z/qdqdj5ffY expected output should be similar to
```asm
Foo:Bar(System.Span`1[System.Byte],long):ubyte:
    mov rax, [rcx]
    movzx eax, byte ptr [rax+rdx]
    ret
```
as for instance [Sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAJI8YUCAAcAymIBuvMDFwBuGvSatOPfoIDCEfBN4AbMTKjzFKmmtIMAYhAg0A3jQYemAZg1IGwAE8MGAYAIWwoAAopCWwuAB5A4IA+BlxYrjQGLl4eBlyAExgEAEp3TzdqT2qGWAAzfyCQqGAGAF5amAaAWRh8aADuiNwAC2xjFgBxGAw2LrEYLkVI9LiS1Sqaj2IAdgYAVS5cbDrBAEECgsj62uAswuL18o8AXxoXoA===) shows.

**Comment by partouf** [comment]
The comparison is not very fair, sharplab works in a completely different way. I won't be expecting them to be the same or even close.

I would be interested in how the options work and if they indeed work. @hez2010 can you check if the options intended to work indeed still work as expected?

**Comment by gfoidl** [comment]
Why is the comparison not fair? .NET's JIT will output code like the expected one when optimizations are turned on.
So here something isn't working as expected, as it's more like output from debug, and this shouldn't be as per default options optimizations should be turned on -- even if explicitely turned on the output isn't shown like JIT optimizes code.

**Comment by partouf** [comment]
> Why is the comparison not fair? .NET's JIT will output code like the expected one when optimizations are turned on. So here something isn't working as expected, as it's more like output from debug, and this shouldn't be as per default options optimizations should be turned on -- even if explicitely turned on the output isn't shown like JIT optimizes code.

We use crossgen2 to output assembly, sharplab does not.

**Comment by gfoidl** [comment]
Ah, I missed https://github.com/compiler-explorer/compiler-explorer/pull/3168#issuecomment-1027389256. Thanks for the hint.

But even so, the output is not what I would expect when using compiler explorer as (superb) tool to view generated assembly code.
* Can there be a hint in the UI that puts emphasis on crossgen2 output to make this obvious?
* Are there any plans to make the output show what JIT outputs with optimized code?

Right now compiler explorer is not helpful to me to see what JIT does.
(Note: this is not a rant, should be a positive critism).

**Comment by hez2010** [comment]
@gfoidl Crossgen2 produces ReadyToRun quality of code which is less optimal than the JIT version. We want to improve the situation to produce the same JIT quality of code in future PRs.

@partouf Seems that some method signatures got removed unexpectedly in compiler explorer when both "Unused labels" and "Directives" filters enabled:

![image](https://user-images.githubusercontent.com/14960345/152671248-ed04eb55-8f20-4338-8640-7aee5c26931d.png)

![image](https://user-images.githubusercontent.com/14960345/152671268-c3922632-75eb-4cf6-ab4f-4e1240f4688d.png)

**Comment by hez2010** [comment]
I've got a fix in #3334. The R2R codegen will be closer with JIT after merging.

**Comment by hez2010** [comment]
Latest result:

```asm
Foo:Bar(System.Span`1[System.Byte],long):ubyte:
       movzx    rax, byte  ptr [rdi+rdx]
       ret      
```

**Comment by partouf** [comment]
only the parser has been adjusted

**Comment by hez2010** [comment]
> only the parser has been adjusted

`--inputbubble --compilebubblegenerics` makes the R2R codegen closer to JIT.

**Comment by partouf** [comment]
> > only the parser has been adjusted
> 
> `--inputbubble --compilebubblegenerics` makes the R2R codegen closer to JIT.

please comment in https://github.com/compiler-explorer/compiler-explorer/pull/3328 as that PR removes those parameters
