### ISSUE TITLE
Can't upgrade to Monaco 0.32 because of monaco-vim

### ISSUE THREAD

**Issue by RubenRBS** [compiler-explorer/compiler-explorer#3333]
When trying to update Monaco to the latest version, we find
```
ERROR in ./node_modules/monaco-vim/lib/cm_adapter.js 10:28-105
Module not found: Error: Can't resolve 'monaco-editor/esm/vs/editor/common/controller/cursorTypeOperations' in '/home/ruben/coding/godbolt/ce/node_modules/monaco-vim/lib'
 @ ./node_modules/monaco-vim/lib/cm/keymap_vim.js 8:41-65
```

The new path should be `monaco-editor/esm/vs/editor/common/cursor/cursorTypeOperations` which seems to fix the problem and gets the new version working nicely.

I have opened an upstream bug report https://github.com/brijeshb42/monaco-vim/issues/90

**Comment by matsjla** [comment]
Can optionally patch it ourselves using https://github.com/ds300/patch-package if there is no response from upstream.
