### ISSUE TITLE
[BUG]: fmt library compiles on msvc even if the library is disabled

### ISSUE THREAD

**Issue by vakokako** [compiler-explorer/compiler-explorer#3351]
### Describe the bug

When using msvc compiler, without enabling `fmt` library, using the library still compiles.

### Steps to reproduce

1. Visit the reproduction link

### Expected behavior

Compilation error.

### Reproduction link

https://godbolt.org/z/x8so77rMG

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment]
That _is_ odd. I agree with the sentiment @partouf - I might be persuaded we could break URL compatibility in this instance (which "version" of fmt are people getting anyway, I bet it changes without us knowing).

**Comment by jeremy-rifkin** [comment]
I think this issue is now obsolete since we're hosting msvc compilers. Now there's an error about not being able to find fmt/format.h.

**Comment by mattgodbolt** [comment]
Yay? I guess :D
