### ISSUE TITLE
[BUG]: godbolt.ms inherits tools from other compilers which it should not have

### ISSUE THREAD

**Issue by timmy-ms** [compiler-explorer/compiler-explorer#3375]
### Describe the bug

When you navigate to a MSVC compiler via godbolt.org, many tools are listed which do not work with the VC compilers. It looks like they are inherited from the main site.

### Steps to reproduce

What should be happening:
1. Visit http://godbolt.ms
2. Select tools dropdown
3. Nothing should be listed (or depending on timing, Static Analysis might be there)

1. Visit http://godbolt.org
2. Select  tools dropdown
3. Lots of tools not supported show up.

### Expected behavior

We would like only MS supported/selected tools to show up in the list.

### Reproduction link

Not applicable

### Screenshots

![image](https://user-images.githubusercontent.com/78125318/154311421-8e93d27d-df05-4dd8-a456-ad1da700b16f.png)

### Operating System

Windows 11

**Comment by RubenRBS** [comment]
If I'm not mistaken, it should be as easy as adding a
`.exclude=www.godbolt.ms@443` property key to every tool listed in https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/c%2B%2B.amazon.properties#L2390 that needs it (Such as what it is done for the clang tidy and pvs studio tools)

**Comment by partouf** [comment]
> If I'm not mistaken, it should be as easy as adding a `.exclude=www.godbolt.ms@443` property key to every tool listed in https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/c%2B%2B.amazon.properties#L2390 that needs it (Such as what it is done for the clang tidy and pvs studio tools)

That would be a tad ridiculous, remote compilers should only have the tools that they actually supply. I'm also a little bit confused at what's going on here. Perhaps compiler-discovery has broken this, because I'm pretty sure at one point in time it worked as expected.

**Comment by partouf** [comment]
Definitely most likely because of compiler-discover. It is not available for my local installation where I have tools installed for other compilers, but the msvc remote gives me none

**Comment by timmy-ms** [comment]
Libraries do the same thing, should I open a second bug for it?

**Comment by partouf** [comment]
> Libraries do the same thing, should I open a second bug for it?

No, libraries is a UI bug we introduced some time ago. The most recent issue about this was https://github.com/compiler-explorer/compiler-explorer/issues/2954

**Comment by partouf** [comment]
> Definitely most likely because of compiler-discover. It is not available for my local installation where I have tools installed for other compilers, but the msvc remote gives me none

So the problem lies in this reconstruction of tools, which I had to implement because the tool classes need to be instantiated at a later point but it didn't get saved correctly during discovery. https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/compiler-finder.js#L387

I could make an exception for remote compilers, but this obviously doesn't solve the problem if the remote actually has tools. Perhaps we can store the tools during discovery instead of doing this reconstruction from the properties.
