### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by janwilmans** [compiler-explorer/compiler-explorer#3376]
### Describe the bug

getting gcc error in clang-output window

### Steps to reproduce

1. https://godbolt.org
2. open two compiler windows
3. select gcc-11.2 on the left, clang-13 on the right.
4. add (broken) example code below
5. add compiler options for gcc-11.2: -Wall -Wextra -fcoroutines 
6. add compiler options for clang-13: -Wall -Wextra 

```
#include <type_traits>
#include <limits>
#include <fmt/core.h>
#include <coroutine>

int gen()
{
    co_yield 42;
    co_yield 44;
    co_yield 46;
}

int main()
{
    fmt::print("{}\n", gen());
    fmt::print("{}\n", gen());
    fmt::print("{}\n", gen());
}
```

### Expected behavior

error message:
"error: unable to find the promise type for this coroutine in both" or similar in both output windows

## Actual behaviour:

getting:
```
In file included from <source>:4:
/opt/compiler-explorer/gcc-11.2.0/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../include/c++/11.2.0/coroutine:334:2: error: "the coroutine header requires -fcoroutines"
#error "the coroutine header requires -fcoroutines"
```

in the CLANG-13 output window, see screenshot

### Reproduction link

https://godbolt.org/z/fqj5fv686

### Screenshots

![image](https://user-images.githubusercontent.com/5933444/154472283-f506860e-26b1-4e78-91cc-5180c78ded52.png)

### Operating System

Windows 11

### Browser version

Chrome Version 98.0.4758.102 (Official Build) (64-bit)

**Comment by janwilmans** [comment]
And maybe this should be reported as a separate issues:

* if you omit '-fcoroutines' you get a gcc-11.2 error saying you have to add `-fcoroutines`
* then when you add  `-fcoroutines`, you get a clang-13 error saying to doesn't recognize  `-fcoroutines` ;))

**Comment by partouf** [comment]
Unless there's a newer gcc version available that fixes this, i'm not sure what to do about this

**Comment by janwilmans** [comment]
I don't think so, remember, the correct behaviour is:
"error: unable to find the promise type for this coroutine" 

but its the CLANG-13 output window reporting a gcc error??? that can't right??

**Comment by partouf** [comment]
> I don't think so, remember, the correct behaviour is: "error: unable to find the promise type for this coroutine"
> 
> but its the CLANG-13 output window reporting a gcc error??? that can't right??

The error is most likely a macro in the header file, and by default clang uses gcc's stdlibc++

**Comment by janwilmans** [comment]
> The error is most likely a macro in the header file, and by default clang uses gcc's stdlibc++
ok, so then the gcc version is fine, its clang that needs to either support -fcoroutines or not-use gcc's stdlibc++. 

I think a workaround it using clang-trunk. closing.
