### ISSUE TITLE
Hello World causes ICE with ARM CL 2017 RTW

### ISSUE THREAD

**Issue by hughbe** [compiler-explorer/compiler-explorer#338]
https://godbolt.org/g/EgLvH1

```cpp
#include <iostream>

int main() {
  std::cout << "Hello, World";
}
```

```
example.cpp
/opt/compiler-explorer/windows/10.0.10240.0/ucrt/corecrt.h(205): fatal error C1189: #error:  Compiling Desktop applications for the ARM platform is not supported.
Internal Compiler Error in Z:\opt\compiler-explorer\windows\19.10.25017\lib\native\bin\amd64_arm\cl.exe.  You will be prompted to send an error report to Microsoft later.
INTERNAL COMPILER ERROR in 'Z:\opt\compiler-explorer\windows\19.10.25017\lib\native\bin\amd64_arm\cl.exe'
Please choose the Technical Support command on the Visual C++
Help menu, or open the Technical Support help file for more information
Microsoft (R) C/C++ Optimizing Compiler Version 19.10.25017 for ARM
Copyright (C) Microsoft Corporation.  All rights reserved.
Compiler exited with result code 2
```

**Comment by mattgodbolt** [comment]
I'm not sure where to pick up the ARM CRT from -- I only have the windows one available in my unusual installation. If anyone has any clues, I'd be delighted to fix this.

**Comment by AndrewPardoe** [comment]
Interesting. We don't support desktop applications on ARM32 so this could very well be intentional. It's not a great user experience to ICE, though. Let me follow up on it.

**Comment by hughbe** [comment]
Nice! Thanks for looking into it! Must say it's odd to have an ARM32 compiler than can't compile a basic Hello World ;p

**Comment by mattgodbolt** [comment]
In fairness the "installation" method on CE is unorthodox and is most likely to blame. I force /I<path to sdk> in the options so if blame that first ans foremost!

**Comment by AndrewPardoe** [comment]
@hughbe, Windows runs on two ARM32 targets: the Surface RT tablet and the Windows Phone. Neither platform officially supports desktop applications so there's no need to have the compiler produce them. (We might have an ARM IOT target but that doesn't change anything.)

**Comment by pps83** [comment]
To compile for arm you'd need `-DWINAPI_FAMILY=WINAPI_FAMILY_APP`, but then you get `'winapifamily.h': No such file or directory` which should be present.

**Comment by ggael** [comment]
I ran into the same problem. Simply including:

    #include <type_traits>

or any standard header is enough to trigger the compilation error.

After digging a bit, passing the following option does the job:

    /D _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE
