### ISSUE TITLE
[REQUEST]: Improve support for preprocessed output with MSVC

### ISSUE THREAD

**Issue by davidstone** [compiler-explorer/compiler-explorer#3382]
### Is your feature request related to a problem? Please describe

There does not appear to be an easy way to see just the preprocessed output of MSVC compiles.

### Describe the solution you'd like

Preprocessed output show appear in the normal compiled output pane, like it does with `-E` for clang and gcc, instead of in the compiler messages output pane. See https://godbolt.org/z/E6abPn3jK. This mixes in preprocessed output with things like warnings.

### Describe alternatives you've considered

None

### Additional context

https://docs.microsoft.com/en-us/cpp/build/reference/e-preprocess-to-stdout?view=msvc-170

**Comment by jeremy-rifkin** [comment]
I think this is closed by #3330

**Comment by jeremy-rifkin** [comment]
It might be nice to get /E working just for convenience though
