### ISSUE TITLE
[BUG]: GoogleTest trunk is stuck at an old commit

### ISSUE THREAD

**Issue by derekmauro** [compiler-explorer/compiler-explorer#3389]
### Describe the bug

Hi, GoogleTest maintainer here.

It appears that the GoogleTest "trunk" library on godbolt.org is stuck on commit https://github.com/google/googletest/commit/1b18723e874b256c1e39378c6774a90701d70f7a. (See https://godbolt.org/z/vYPhWMx91).

Interestingly, this appears to be a commit on the same day we changed our default branch from `master` to `main`, so it may be related to this. I took a look at the compiler-explorer code and couldn't find a reference to the branch name to change. It is possible this is a configuration issue on our end.

A colleague mentioned that the Google Benchmark library appears to have the same issue, but I haven't verified this myself.

### Steps to reproduce

1. Use https://godbolt.org/z/vYPhWMx91 to see the current GoogleTest trunk version and observe that it is 1b18723e874b256c1e39378c6774a90701d70f7a from 2021-11-12.
2. Compare to the actual trunk at https://github.com/google/googletest/commits/main.

### Expected behavior

Trunk should match a recent commit at https://github.com/google/googletest/commits/main.

### Reproduction link

https://godbolt.org/z/vYPhWMx91

### Screenshots

Not applicable

**Comment by partouf** [comment]
Sounds quite plausible. Thanks for the bugreport

**Comment by RubenRBS** [comment]
This is still stuck at the old commit and I can't figure out why. So weird

**Comment by partouf** [comment]
It was still on 'master' instead of 'main'. I have changed it, but the binaries will still need to rebuild tonight, so I'll keep this issue open for a bit.

**Comment by jeremy-rifkin** [comment]
Should be good to close now
