### ISSUE TITLE
[REQUEST]: Open VSX Registry

### ISSUE THREAD

**Issue by jalexcole** [compiler-explorer/compiler-explorer#3402]
### Is your feature request related to a problem? Please describe

This plugin is not on the open vsx registry. 

### Describe the solution you'd like

Adding this plug in to the open vsx registry for use in open source vscode options. 

https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

### Describe alternatives you've considered

N/A

### Additional context

Not applicable

**Comment by partouf** [comment]
Hi, this is not a plugin, this is a website.

**Comment by mattgodbolt** [comment]
@jalexcole if you're using Compiler Explorer as some plugin to Eclipse then please ask the maintainer of that project to register: we don't maintain nor even know of such a plugin. (and if there is, please let us know about it though and we can add links to it)

**Comment by jalexcole** [comment]
I apologize as this was where I was linked to. The plug-in in question
is MRobertEvers/vscode-compiler-explorer:
Compiler Explorer Integration With VSCode. (github.com)
<https://github.com/MRobertEvers/vscode-compiler-explorer>

This utilizes godbolt but displays everything inside of vscode for looking
at your project.

**Comment by mattgodbolt** [comment]
Oh cool. thanks for the link!
