### ISSUE TITLE
[REQUEST]: Deletion of browser-local storage files

### ISSUE THREAD

**Issue by dgazzoni** [compiler-explorer/compiler-explorer#3410]
### Is your feature request related to a problem? Please describe

I'd like to be able to delete a specific file saved to browser-local storage.

### Describe the solution you'd like

There could be a "Delete" button/link right next to each file.

### Describe alternatives you've considered

Deleting all local storage for Compiler Explorer using my web browser's settings pane, but this is the nuclear option, since it deletes every other file I have previously saved.

### Additional context

Not applicable

**Comment by RubenRBS** [comment]
Thanks for taking the time to request this feature. It's something that we should totally have implemented long ago :)
