### ISSUE TITLE
[BUG]: Changing compilers no longer updates the tab name

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#3419]
### Describe the bug

Switching between compilers doesn't update the name of the tab.

### Steps to reproduce

1. godbolt.org and reset ui
2. Note the default tab is "x86-64 gcc (C++, Editor #1, Compiler #1)"
3. Change the compiler to clang
4. Note the tab remains named "x86-64 gcc (C++, Editor #1, Compiler #1)"

### Expected behavior

Unless the tab has been manually renamed, the tab name should change to reflect the currently-selected compiler.

### Reproduction link

Not applicable

### Screenshots

![Screenshot from 2022-03-02 15-59-56](https://user-images.githubusercontent.com/633973/156456790-ca68bbf8-24a2-4f1a-b77c-58becd99e2f1.png)

Compiler changed, tab name is now wrong...

![Screenshot from 2022-03-02 16-00-12](https://user-images.githubusercontent.com/633973/156456786-e76d226b-0569-4780-b849-7e03ed8fa47b.png)

**Comment by jeremy-rifkin** [comment]
It appears this does not affect tool panes (tested ast, opt, llvm ir, graph view, preprocessor), just the compiler output pane. It does affect the diff view. Looks like this broke somewhere between 024787754e16df321e52b52e4fb62dcb7133e0f6 and 48eee26. I'll narrow this down some more.
I did notice something odd with the dropdowns in the diff view when compilers change, but the title of tab is updated appropriately.
