### ISSUE TITLE
[REQUEST]: Improve asan output from clang

### ISSUE THREAD

**Issue by jeremy-rifkin** [compiler-explorer/compiler-explorer#3422]
### Is your feature request related to a problem? Please describe

CE execution output from a program compiled with clang and `-fsanitize=address` doesn't contain line numbers in the stack trace only addresses (regardless of -g): https://godbolt.org/z/hW84n46Ms. 

### Describe the solution you'd like

From some quick googling it sounds like the solution is to put the path to llvm-symbolizer in `ASAN_SYMBOLIZER_PATH`.

### Describe alternatives you've considered

.

### Additional context

Not applicable

**Comment by partouf** [comment]
duplicate of https://github.com/compiler-explorer/compiler-explorer/issues/3023
