### ISSUE TITLE
[LIB REQUEST]: fmt make 8.x available?

### ISSUE THREAD

**Issue by lgritz** [compiler-explorer/compiler-explorer#3438]
### Library name

fmt

### Library description

The pull-down for selecting fmt library only has versions through 7.x. Can you please add 8.x flavors? Thanks.

### Library repository

https://github.com/fmtlib/fmt

### Motivation

It's the current set of releases

**Comment by m8mble** [comment]
This can be close, `fmt` 8.0.1 and 8.1.1 are live.
