### ISSUE TITLE
[BUG]: Conformance view bugged when initially selecting a compiler

### ISSUE THREAD

**Issue by jeremy-rifkin** [compiler-explorer/compiler-explorer#3445]
### Describe the bug

When initially adding compilers to the conformance view something goes wrong with the initial compile and CE shows the builds failing.
![image](https://user-images.githubusercontent.com/51220084/158215042-c00b762d-976a-412c-8d19-bb3c18de16ec.png)
Pressing any of the "Show compiler" arrows causes everything to recompile and then the output is as expected:
![image](https://user-images.githubusercontent.com/51220084/158215206-c4fb0970-3ccd-4baf-91a4-dc9a53dda147.png)

### Steps to reproduce

Open conformance view and add a compiler, it'll show the build failed even if it's perfectly fine.

### Expected behavior

Initial compile should show success here

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
@jeremy-rifkin  I believe this doesn't reproduce today. Might have been solved in the 1.5Y since.

**Comment by partouf** [comment]
I vaguely remember doing something after this was converted to typescript, but I can't pinpoint the commit that was related to fixing this.

Let's just close until someone encounters it again.
