### ISSUE TITLE
[REQUEST]: Allow to duplicate entries in conformance view

### ISSUE THREAD

**Issue by loic-joly-sonarsource** [compiler-explorer/compiler-explorer#3447]
### Is your feature request related to a problem? Please describe

Very often, with working with conformance view, I work with different versions of the same compiler, all options are the same. Or I work with different C++ standards, with the same compiler and the same options (exception for this one). Or...

Right now, to add a new compiler in the conformance view, I have to start from an empty line each time.

### Describe the solution you'd like

A button on the right hand side of each line allows to clone the line. The new identical line is put right after the cloned one.
![image](https://user-images.githubusercontent.com/37904001/158397904-3fcbcaa0-8874-49a6-ac9a-b68bde0455a0.png)

### Describe alternatives you've considered

Not applicable

### Additional context

Not applicable

**Comment by partouf** [comment]
Seems reasonable. Whenever I was using confview I experienced similar annoyances. Don't think it's difficult to add either.

**Comment by dead-tech** [comment]
I would be glad to work on this 😄

**Comment by RubenRBS** [comment]
Closes by the linked PR a few months ago, but we missed the issue! :)
