### ISSUE TITLE
[BUG]: compile to binary with clang requires disabling Filter > Library Functions

### ISSUE THREAD

**Issue by nickdesaulniers** [compiler-explorer/compiler-explorer#3449]
### Describe the bug

When we need to view the encoding of instructions, we use the Output > Compile to Binary flag. For clang, the output doesn't seem to match GCC. If I disable Filter > Library Functions, then the output looks good. I don't need to do this for GCC.

### Steps to reproduce

1. add C code
2. set Output > Compile to Binary
3. set Filter > Library Functions

compare output from clang vs gcc.

### Expected behavior

instruction encodings printed for clang

### Reproduction link

https://godbolt.org/z/W76Wf7q6d

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
I think this is now resolved
