### ISSUE TITLE
[BUG] Problem with LOOP opcode

### ISSUE THREAD

**Issue by Barabas5532** [compiler-explorer/compiler-explorer#3451]
The documentation for x86 LOOP is shown when xtensa GCC is selected. Actually it seems like any opcode that has a matching x86 opcode will show the x86 docs.

https://godbolt.org/z/MjG6o3YGT

**Comment by RubenRBS** [comment]
Hi! Thanks for the heads-up.
We will disable the asm opcode docs for xtensa until we can properly support them instead of falling back to x86
