### ISSUE TITLE
[BUG]: DWARFv5 loclist header showing up despite labels/directives being filtered out

### ISSUE THREAD

**Issue by dwblaikie** [compiler-explorer/compiler-explorer#3458]
### Describe the bug

Since Clang moved to DWARFv5 (by the looks of it) by default some DWARF directives are showing up in the default godbolt compiler window (despite label/directives filtering out most of the DWARF/all of the DWARFv4).

Maybe there's a bug in clang's output that makes it not get filtered? Nothing that I can see... 

### Steps to reproduce

1. Visit https://godbolt.org/z/6YMTPeh11
2. Check the two compiler windows
3. the -g0 window has no debug info directives visible (though removing the directives/labels filters shows lots of DWARF)
4. The other window has -g implicitly added by godbolt and shows `Ldebug_list_header_start0` and a the contents after that

### Expected behavior

Both windows should not show any debug info directives.

### Reproduction link

https://godbolt.org/z/6YMTPeh11

### Screenshots

Not applicable

**Comment by partouf** [comment]
we recently forced Clang to use dwarf 4, so this issue has disappeared for now
