### ISSUE TITLE
[REQUEST]: List compilers, which support "Execute the code" option

### ISSUE THREAD

**Issue by pmor13** [compiler-explorer/compiler-explorer#3473]
### Is your feature request related to a problem? Please describe

Here is "Select a compiler..." input:
![image](https://user-images.githubusercontent.com/4587883/160932827-15ecefbc-0e36-4fd9-8f63-9af95898e261.png)

However, how to list compilers, which support "Execute the code" option?

### Describe the solution you'd like

Add an option (filter?) to list compilers, which support "Execute the code" option.

Note: the similar option (filter?) may be useful to other options as well (e.g. "Compile to binary").

### Describe alternatives you've considered

Provide an advanced web-form to filter compilers by (combination of) parameters. Example: "show all the compilers, which support A, B, and C".

Extra: then you may consider: "compile & run the code on all such compilers/targets and show the results".

### Additional context

Not applicable

**Comment by partouf** [comment]
It's quite challenging to filter the normal compiler list in a transparant and clear way in the UI, so I'm not sure this can be done.

Perhaps a workaround for this; If you open an Executor pane, only the compilers than can execute are listed. https://godbolt.org/z/fv4ec8x3j
