### ISSUE TITLE
[BUG]: Default compilation fails for flang-trunk

### ISSUE THREAD

**Issue by operasfantom** [compiler-explorer/compiler-explorer#3476]
### Describe the bug

All Fortran's compilers but `flang-trunk` work as expected. The output of `flang-trunk` is as follows:

```
opt/compiler-explorer/clang-llvmflang-trunk/bin/flang: line 431: gfortran: command not found
flang: in /app, gfortran failed with exit status 127: gfortran -g -S -fparse-only -g -o /app/output.s -S -fparse-only /app/example.f90
ASM generation compiler returned: 127
/opt/compiler-explorer/clang-llvmflang-trunk/bin/flang: line 431: gfortran: command not found
flang: in /app, gfortran failed with exit status 127: gfortran -g -fparse-only -L. -Wl,-rpath,. -g -o /app/output.s -fparse-only -L. -Wl,-rpath,. /app/example.f90
Execution build compiler returned: 127
```

### Steps to reproduce

1. Visit godbolt.org
2. Create Fortran source
3. Choose flang-trunk as a compiler
4. Ensure that compilation fails

### Expected behavior

Compilation succeeds

### Reproduction link

https://godbolt.org/z/zYbsP176M

### Screenshots

![image](https://user-images.githubusercontent.com/31903947/161090162-5df5758d-0cc5-459c-86d1-d5a79911ce23.png)

**Comment by RubenRBS** [comment]
Hi! Sorry we took so long to get around taking a look at this bug.
As the error suggests and 
https://releases.llvm.org/11.0.0/tools/flang/docs/ReleaseNotes.html#using-flang confirms, it's not able to find `gfortran`. We can probably point it to one of our available ones so this should be an easy fix

**Comment by operasfantom** [comment]
@RubenRBS Nice to hear that an easy fix can be applied to this case👍 I look forward to playing with flang in explorer

**Comment by partouf** [comment]
This is partially fixed, but I also added flang-new.
Old flang can't emit asm anymore outside of binary, and flang-new can't properly link yet in binary mode
