### ISSUE TITLE
[REQUEST]: highlight line indefinitely

### ISSUE THREAD

**Issue by ericlagergren** [compiler-explorer/compiler-explorer#3487]
### Is your feature request related to a problem? Please describe

The "Highlight linked code lines on hover" option is great. However, it disappears after a few moments even though my mouse is still hovering.

### Describe the solution you'd like

I would like it to stay highlighted indefinitely (so long as my mouse is hovering).

### Describe alternatives you've considered

None :)

### Additional context

Not applicable

**Comment by jeremy-rifkin** [comment]
Looks like this behavior was introduced in 29adf57

**Comment by ericlagergren** [comment]
Interesting. Perhaps this could be user configurable? I find it helps me track the assembly better.

**Comment by RubenRBS** [comment]
Hi! I know it's been a while, but I've now implemented the necessary changes, it will be controlled by a setting as you suggested. Thanks for your patience :)

**Comment by ericlagergren** [comment]
Thank you :)
