### ISSUE TITLE
[BUG]: Nim compilation is broken since a few days ago

### ISSUE THREAD

**Issue by Yardanico** [compiler-explorer/compiler-explorer#3488]
### Describe the bug

Nim compilation is currently broken. I've checked locally, and the offending PR seems to be https://github.com/compiler-explorer/compiler-explorer/pull/3474. I commented there on my findings, but I'm not sure what a proper fix would look like.

### Steps to reproduce

Select "Nim" on Godbolt, and the default example will fail to compile.

### Expected behavior

Compilation successful 

### Reproduction link

https://godbolt.org/z/br1zKMEoz

### Screenshots

Not applicable

**Comment by RubenRBS** [comment]
Hi, sorry about that! Thanks for the heads-up and for taking the time to track down the issue

I've implemented a fix and if everything goes well, it should be live soon-ish :)

**Comment by mattgodbolt** [comment]
This fix is now live! Sorry for the issue!
