### ISSUE TITLE
[BUG]: Incorrect output of a clang++ compiler

### ISSUE THREAD

**Issue by ProjectMutilation** [compiler-explorer/compiler-explorer#3499]
### Describe the bug

```
#include<iostream>
#include <limits>
int main(){
   unsigned int uimax = std::numeric_limits<unsigned int>::max();
   std::cout<<uimax<<std::endl;
}
```
The output of this code was empty with using  a Clang compiler(I checked 13.0.1, 6.0.1, 10.0.1 versions but I think it's the same for any version). Similarly the behavior was observed when casting from negative int to unsigned int

### Steps to reproduce

1. Select Gcc and Clang compilers(versions doesn't matter)
2. Copy code from description in source code editor 
3. Compare stdout

### Expected behavior

Expected behavior: compiler should  outputting max_value 4294967295 in stdout

### Reproduction link

https://godbolt.org/z/raEf7Gaa3

### Screenshots

![expected behavior](https://user-images.githubusercontent.com/64891287/161931280-50e65282-b980-4863-a715-2c95030f8d2e.png)
The behavior of clang++(6.0.0) on my local machine corresponds to the expected behavior

**Comment by dkm** [comment]
Missing the "execute the code" option: https://godbolt.org/z/Ghv4jKzbv

**Comment by dkm** [comment]
![Screenshot 2022-04-06 at 11-30-18 Compiler Explorer - C](https://user-images.githubusercontent.com/87603/161944383-42e48cc1-e4bd-456c-89f4-373d647705c7.png)
