### ISSUE TITLE
std::chrono::current_zone crashes on MSVC builds

### ISSUE THREAD

**Issue by rogerorr** [compiler-explorer/compiler-explorer#3500]
The simple program in https://godbolt.org/z/Gs35jzodK that compiles:
```
#include <chrono>

int main() {
  (void)std::chrono::current_zone();
}
```
crashes on MSVC builds with error :
Program returned: 3221226505
(this is STATUS_STACK_BUFFER_OVERRUN)

**Comment by mattgodbolt** [comment]
Thanks! We've had reports but couldn't work out what the error message was.  We're trying to work out what in our sandboxing code might be causing this.

**Comment by rogerorr** [comment]
I'm not sure why it fails with that error.
But I note that calling std::chrono::current_zone() on my own Windows machine loads some DLLs:
```
Load DLL at 00007FF97AF30000 C:\WINDOWS\SYSTEM32\icu.dll
Load DLL at 00007FF99CB60000 C:\WINDOWS\System32\ucrtbase.dll
Load DLL at 00007FF99C740000 C:\WINDOWS\System32\msvcp_win.dll
Load DLL at 00007FF99B3D0000 C:\WINDOWS\SYSTEM32\kernel.appcore.dll
```

**Comment by rogerorr** [comment]
So, using https://godbolt.org/z/7j38r36sT:
```
#include <chrono>
#include <excpt.h>
#include <iostream>

int filter(unsigned int code, struct _EXCEPTION_POINTERS *ep)
{
    std::cout << "Caught " << code << std::endl;
    return EXCEPTION_CONTINUE_SEARCH;
}

int main() {
    std::cout << "Test" << std::endl;
    __try {
  (void)std::chrono::current_zone();
    } __except(filter(GetExceptionCode(), GetExceptionInformation())) {

    }
}
```

I get output:
```
Program returned: 0
   Test
   class std::system_error: The specified module could not be found.
```
Does your sandboxed env offer icu.dll?

**Comment by mattgodbolt** [comment]
Thanks @rogerorr - we've asked the MS team to look in and see if there's something missing. Super helpful, thanks :)

**Comment by StephanTLavavej** [comment]
https://github.com/microsoft/STL/wiki/VS-2019-Changelog#vs-2019-1610

> While the STL generally provides all features on all supported versions of Windows, leap seconds and time zones (which change over time) require OS support that was added to Windows 10. Specifically, updating the leap second database requires Windows 10 version 1809 or later, and time zones require `icu.dll` which is provided by Windows 10 version 1903/19H1 or later. This applies to both client and server OSes; note that Windows Server 2019 is based on Windows 10 version 1809.

If the VMs are using Windows Server 2019, that would explain this - it's too old for time zones. Windows Server 2022 will work (that's what the STL's own test VMs use).

**Comment by mattgodbolt** [comment]
Thanks all! We'll see about the OS!

**Comment by timmy-ms** [comment]
We are currently blocked by the version of Windows that Kubernetes supports. As soon as we can upgrade to Server 2022 we will. Until then there is nothing we can do here sadly. :(

**Comment by haephrati** [comment]
I had the same problems on certain Windows machines that just crashed when any timezone is set.

**Comment by jeremy-rifkin** [comment]
Now that we're hosting msvc compilers this code compiles and runs without issue
