### ISSUE TITLE
Notify the user when their link can not be properly parsed

### ISSUE THREAD

**Issue by RubenRBS** [compiler-explorer/compiler-explorer#3518]
https://github.com/compiler-explorer/compiler-explorer/pull/3515 allowed the site to load even if the long url is not deserializable, but currently the site just silently fails and displays the default config.

It would be great if a notification could be shown to the user with a helpful message when this happens.
The steps needed to implement this feature are:
1. In the catch added by the linked PR in `main.js`, initialize an instance of `Alert` which is already imported in the file
2. Choose between `Alert.alert` or `Alert.notify` to show the message to the user
3. Test that the message shows up when a exception throws inside the try (Just adding `throw new Exception();` inside the try should work)

**Comment by Vaascoo** [comment]
#3771

**Comment by Vaascoo** [comment]
Hello, I added the alert and it seems to comply with the steps mentioned in the issue. I also opened the following PR #3771
