### ISSUE TITLE
[BUG]: All share links I create point to blank page such as https://godbolt.org/resetlayout/GcTKaEq91

### ISSUE THREAD

**Issue by AllUltima** [compiler-explorer/compiler-explorer#3543]
### Describe the bug

I write some C++ code and go to the top-right and say "share link". It does not matter if I choose to create a short or full link, neither works.

short link:https://godbolt.org/z/hMTzn8bd7

Full link:
https://godbolt.org/#z:OYLghAFBqRAWIDGB7AJgUwKKoJYBdkAnAGhxAgDMcAbdAOwEMBbdEAcgEY3iLk68Ayoga0QHACw8%2BeAKoBndAAUAHuwAM3AFZji1BnVCIApACYAQqbPEFtRHhx9y9VAGFk1AK5M6IAMwBWYmcAGRw6dAA5LwAjdEIxNWIAB2Q5fAc6N09vP0CUtPs%2BUPCoplj4jkSbdDsMgTwGQjwsrx8A63RbQrp6xrxiyJi4hOsGppac9rkx/rDBsuHKgEprZA9CRFY2U18wxE8MAGojXxcHacJ0ZhPMIzUAQTv7/YY5OUOzV/QnowB2CweSQ80WoOEQICehyhhwAbsgcKhDgARZACZAsADqRAA1hAlpDoX8AfdoaTDsFkMAALLoN4MYDoPEnMyHAD0rNhOCaHhEh2E1GoBKhfyRQs53N5cIR5MpNLpDLxx18SMOamZP1%2Bot8xKeLzeyLiOBh6ERIEOQJBYI%2BXw1xItoPBYqliIp1NpcnpjKWx3%2BUOmqBASDWeCVLhOLmOJhMco9DNMJlD4cO/sDzkF2p9ooeIvV2YeeveSMNxtQCbN9qtnwUtqeFcdD1JzplbvlXp9LJTQY8IfDSfjMc9JnjidOybwAZAaeZmY1Wp1DzCIaYDDCTOz/zFRcIRpNh2UuZJ0K3O9LhwAngexVX0AAqc1KlWmABsF%2B1YqSAFobq6Bwr8W/1znJ42BWah2H8bgfDYDRiGQdgw3MSxkzWDZ0EjXwuGIPB1BA4h4CDJgkhoOJSHIFBCOI%2BIXgMCQ1ESKhqDwOI5HIaIcOIaIwkaM92Ew8iWH4AB5OhqB46DuAwZcDFEcTiFwS5amNFjZPQZQam7LZMMXTp2NBaJCG4twMHYvBtyYXjcIoPRgDkAA1HB0AAd0EpJ6AsqR%2BCEERWAkDzZAUFR2O0DhdH0QxLEsXQcGiFjIBWZAkm6ZSPw/BL7CYHAAC90G4apakcCBnAmHwQpCOZSnKHR8nSPhiqq1IaroAYKsWDoujqGY6pCvLul6JpmqGCpRj6Lrhv68rBrEFY5BQzYdFM9BNNwsC2Ag4goJguC2GUAAOJ8PyfcQ%2BT0AxDgkAA6NRLsOCAEIscxiEObB8CIdCQsONwKNoQg3qWbhsPElZ8PIojvtIiAQcokAYUQJIkgAfRhDgAE54b0Jjpnh5RDp4GgmMIFiIDY2TOMYQgxL49EBLwYTRPYySwpkmD5JqewlPY1T1KY9ztJWmC9IM8mjK2GDTJwczOEs6y7Ic5zXKgzDeE8/kfMkJX/KUVRZO0ExQoMJAIoevTYrxWDEoyFjWWQXWZvWOaQoWpbQPAyD2K23b9sOw5gEQRAzo4c6E1uw2rCe3ACB%2BnZ3s%2B0G4nQkw/qwnClhWOArgweJTexBJEhW8RXdkrbcpARIAY0FPiGNAmMhAcQgA%3D%3D

On any browser on any machine it just loads to a blank page.

Before sharing, compiling works normally. How do I recover this and share the link?

### Steps to reproduce

1. visit godbolt.org
2. Write some C++ code
3. Choose "share link" (either short or long)

### Expected behavior

I should be able to create a share link with content instead of a blank page

### Reproduction link

https://godbolt.org/resetlayout/GcTKaEq91

### Operating System

Windows 10

### Browser version

Reproduces on several browsers

**Comment by jeremy-rifkin** [comment]
This will be fixed by #3542, I think mainly MSVC compilers are affected.

**Comment by RubenRBS** [comment]
@jeremy-rifkin your bugfix fixed the issue and msvc seems to work again. Will update this issue once we push the version to prod. Thanks!

**Comment by jeremy-rifkin** [comment]
Great, thanks and sorry again for introducing this issue in the first place! 🤦‍♂️

**Comment by mattgodbolt** [comment]
> Great, thanks and sorry again for introducing this issue in the first place! man_facepalming

Gosh not at all! sorry we don't have enough testing to give us more confidence in releasing!

**Comment by RubenRBS** [comment]
Fix is now live. Again, sorry for the troubles :)
