### ISSUE TITLE
[BUG]: _Noreturn cancels printf 

### ISSUE THREAD

**Issue by pmor13** [compiler-explorer/compiler-explorer#3551]
### Describe the bug

`_Noreturn` cancels `printf`.

### Steps to reproduce

https://godbolt.org/z/efvMcnKeq

### Expected behavior

Expected output:
```
xxx
zzz
```
Actual output:
```
<nothing>
```

### Reproduction link

https://godbolt.org/z/efvMcnKeq

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
It's undefined to return from a `_Noreturn` function, I'd say the expected behavior is anything from xxx zzz to summoning the Kraken :P

The reason nothing shows up is that stdout's buffer isn't flushed before the program segfaults. If you add `setvbuf(stdout, NULL, _IONBF, 0);` to main the output is:

```
Program returned: 139
xxx
zzz
```

**Comment by pmor13** [comment]
@jeremy-rifkin Thanks! Another solution is to use `fflush(stdout)`. Hm, I thought that `\n` causes flushing. Relevant [comment](https://stackoverflow.com/q/1716296/1778275):
> `printf(..)` does not do any flushing itself, it's the buffering of `stdout` that may flush when seeing a newline (if it's line-buffered).

@mattgodbolt This issue can be resolved as "Not a problem".

**Comment by jeremy-rifkin** [comment]
@pmor13 Yeah printf is line-buffered on most systems. Not sure why it's not for CE 🤔

**Comment by jeremy-rifkin** [comment]
Ah didn't know libc only line buffers to TTYs, TIL!

**Comment by pmor13** [comment]
@mattgodbolt Can you explain why despite of 2 printf() before abort() nothing is printed? Demo: https://godbolt.org/z/bW8Ez46EM. I expect that "it eventually needs to be printed". Ok, stdout is buffered. Ok, libc does not flush on every line.
However, is libc required to flush stdout on abort()?

**Comment by pmor13** [comment]
Found: C11, 7.22.4.1 The abort function:
> Whether open streams with unwritten buffered data are flushed, open streams are closed, or temporary files are removed is **implementation-defined**.

**Comment by jeremy-rifkin** [comment]
For glibc at least no flushing is performed https://code.woboq.org/userspace/glibc/stdlib/abort.c.html#abort
