### ISSUE TITLE
[BUG]: Assembly code is filtered out on Clang 14

### ISSUE THREAD

**Issue by dungwinux** [compiler-explorer/compiler-explorer#3564]
### Describe the bug

Assembly code is filtered out when choosing Clang 14.0.0 compiler with _Compile to binary_ Output option.

### Steps to reproduce

1. Visit godbolt.org
2. Select the x86-64 clang 14.0.0 compiler for C++
3. Click on Output... and set _Compile to binary_ to On
4. View the output pane

### Expected behavior

The assembly output should be there instead of empty.

### Reproduction link

https://godbolt.org/z/Tbr5rnGdb

**Comment by dungwinux** [comment]
Turning off _Library functions_ in _Filter..._ seems to make the assembly output reappears.

**Comment by RubenRBS** [comment]
Hi! Thanks for the report
As you saw, turning off the _Library Functions_ filter makes the code show up again. That is because Clang 14.0.0 reports:
```asm
...
square(int):                             # @square(int)
.Lfunc_begin0:
        .file   0 "/app" "/app/example.cpp" md5 0x10b91831677796a5c7dc72e7bd216467
        .file   1 "example.cpp" md5 0x10b91831677796a5c7dc72e7bd216467
...
```
while Clang 13.0.0:
```asm
square(int):                             # @square(int)
.Lfunc_begin0:
        .file   1 "/app" "example.cpp"
        .loc    1 2 0                           # example.cpp:2:0
```

My guess is that either the new md5 outputs are tripping up our regex, or the new report layout is not compatible with it

**Comment by partouf** [comment]
Grmbl :(

**Comment by partouf** [comment]
(me and [RubenRBS](https://github.com/RubenRBS) refered to normal -S mode, but this issue refers to actual normal -g object/executuble generating mode)

**Comment by Trass3r** [comment]
> It seems like a new type of debug information is being used by clang

Yes, DWARFv5: https://releases.llvm.org/14.0.0/tools/clang/docs/ReleaseNotes.html#dwarf-support-in-clang

`-S` / `-fverbose-asm` hasn't changed (yet) but got mentioned recently: https://github.com/llvm/llvm-project/issues/17839#issuecomment-1077933948
