### ISSUE TITLE
[REQUEST]: detect SEGV and report

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#3567]
### Is your feature request related to a problem? Please describe

See https://github.com/compiler-explorer/compiler-explorer/pull/2936 - we tried to detect and report signals but `nsjail` loses that information. Would be cool not to!

### Describe the solution you'd like

Somehow detect the signal and report it in the API response.

### Describe alternatives you've considered

Parsing out the signal from `nsjail`'s 128+signal exit code, but then we leave ourselves open to misidentifying `int main(){ return 139; }` as a seg fault.

### Additional context

Not applicable

**Comment by partouf** [comment]
I did modified nsjail a bit and using this bit of code
```
int main() {
    char *hello;
    return hello[100];
}
```

I found that we can detect the signals at 2 points;

* Directly in the signal handler, but you get there about 3 times, so might be a bit confusing depending how we communicate it to the CE https://github.com/google/nsjail/blob/cc4245d23a74082c41c16f29e71d59e30dde0631/nsjail.cc#L56C13-L56C23
* In subproc.cc reapProc() https://github.com/google/nsjail/blob/cc4245d23a74082c41c16f29e71d59e30dde0631/subproc.cc#L354
   - Interestingly enough it's already logged, but we obviously use nsjail in quiet mode

The big question is how are we going to communicate this to CE. We could:
* put a message in stderr
* use an external file to put the info in
   - Interestingly enough https://github.com/google/nsjail/pull/201/files already does this as well

So I would opt for just using the above PR in a new nsjail fork, but the amount of code thats inlined into existing code makes maintaining the fork be much harder than it probably has to be. So perhaps it would be best to create a new fork that has all the features from that PR, but separated as much as is humanly possible. And perhaps export the data as a structured file and not just a txt file.

We could also always just go with putting in a log to stderr and be done with it. That's how it will eventually show up in the frontend one way or another anyway. And a lot less work.

**Comment by partouf** [comment]
OH, wait

Would this also help: https://github.com/google/nsjail/releases/tag/3.2 "add option to forward fatal signals to the child"

We're using 3.0

**Comment by partouf** [comment]
> OH, wait
> 
> Would this also help: https://github.com/google/nsjail/releases/tag/3.2 "add option to forward fatal signals to the child"
> 
> We're using 3.0

Just checked, no doesn't do anything in this respect, must be about when someone else sends a signal to nsjail probably

**Comment by apmorton** [comment]
https://github.com/apmorton/firejail/commit/b040316ff1ec828203c92e7d2171038d4146e7a6

You basically need to find a place to chuck that bit of code in nsjail.

**Comment by partouf** [comment]
![Screenshot from 2023-06-23 19-15-28](https://github.com/compiler-explorer/compiler-explorer/assets/442630/f2c852d5-d05d-4e54-bcb1-27a8023b7731)

**Comment by partouf** [comment]
This is now live https://godbolt.org/z/vE9ed3v1r
