### ISSUE TITLE
[REQUEST]: support core, stg and cmm output from GHC

### ISSUE THREAD

**Issue by adamse** [compiler-explorer/compiler-explorer#3571]
### Is your feature request related to a problem? Please describe

GHC can produce some intermediary outputs (like GCC and Rust). It would be nice if those could be optionally captured!

### Describe the solution you'd like

Under the tools dropdown menu there would be choice like LLVM IR, MIR output etc that pops up a new pane.

### Describe alternatives you've considered

I currently pass ex `-ddump-stg` flags to the compiler and look at the output window.

**Comment by adamse** [comment]
I started hacking on this. I see there are two styles currently: the LLVM IR or Rust MIR output (each extra output in a new pane) and the GCC RTL/Tree outputs (many things in one pane). What is the preferred way?

**Comment by RubenRBS** [comment]
Hi! Thanks for taking the time to hack at this!

As far as I can tell, we have no preferred way to handle those, so whatever works for you. I would suggest going with the LLVM IR route, as having more than one pane reduces complexity in each of them :)
