### ISSUE TITLE
[BUG]: Disabling "Highlight linked code lines on hover" prevents "Show asm description on hover" from working

### ISSUE THREAD

**Issue by acaldas1984** [compiler-explorer/compiler-explorer#3601]
### Describe the bug

If you disable "Highlight linked code lines on hover", asm description on hover doesn't show up, even when it is enabled.

### Steps to reproduce

1. Go to settings.
2. Disable "Highlight linked code lines on hover".
3. Keep "Show asm description on hover" enabled.
4. Close settings.
5. Hover on an instruction and notice that no popup is shown.

### Expected behavior

Asm instruction information should pop up on hover, even when "Highlight linked code lines on hover" is disabled.

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

MacOs Monterey 12.3.1

### Browser version

Version 100.0.4896.127 (Official Build) (x86_64)

**Comment by RubenRBS** [comment]
Hi! Nice catch, thanks for the report. We were checking the wrong setting for it! (So disabling the show asm doc on hover would do nothing too).

**Comment by RubenRBS** [comment]
This is now live
