### ISSUE TITLE
[BUG]: Select-all (Ctrl+A) in the output pane, select all site peripheral text

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#3607]
### Describe the bug

When the focus is in a source or assembly pane and you click Ctrl+A, the behavior is as expected - all pane text is selected, and nothing else.
If the focus is at an *output* pane and you click Ctrl+A, *all the page's text* is selected - source, assembly, line numbers etc.:

### Steps to reproduce

1. Visit godbolt.org and build something (even the default code)
2. At the gutter of a compiler pane click  "Output" to open an output pane
3. Click on the output pane and Ctrl+A
4. Paste somewhere outside (notepad will do fine)

### Expected behavior

I expect just the output text to be selected (can be large)

### Reproduction link

Not applicable

### Screenshots

![image](https://user-images.githubusercontent.com/73080/166057599-6d8e32ca-e403-4f43-8432-84b5987f4ae9.png)

**Comment by RubenRBS** [comment]
Hi! Thank you so much for taking the time to open the request, it's such a good idea I had to implement it right away.
If everything goes well, it should hit the live site soon-ish :)

**Comment by OfekShilon** [comment]
WOW! Never seen such response time. Thanks!
Just curious: why the difference in behavior between the output pane and, say, compiler (or 'preprocessor', or whatever) pane? Are they somehow different entities?
I mean, how come a specific manual handling of Ctral+A is even needed?

**Comment by OfekShilon** [comment]
@RubenRBS  WOW! Never seen such response times. Thanks!
Just curious: why the difference in behavior between the output pane and, say, compiler (or 'preprocessor', or whatever) pane? Are they somehow different entities?
I mean, how come a specific manual handling of Ctrl+A is even needed?

**Comment by jeremy-rifkin** [comment]
The source editor, assembly pane, preprocessor pane, etc. are all very different from the output pane. There's no real way to "focus" the output pane (at least without Ruben's changes).

You'll notice on any other web page ctrl+a selects everything on the entire page, unless you are focused in some sort of editable/text entry region like a search bar.

The source editor, assembly pane, etc. are all editors (monaco editors, specifically) and they have special logic to allow you to focus them, edit them, select all within them, use other keyboard shortcuts, etc. The output pane is just plain HTML without all the special handling from monaco.

**Comment by OfekShilon** [comment]
@jeremy-rifkin  Thank you! Makes sense.

**Comment by pmor13** [comment]
@OfekShilon Relevant: https://github.com/compiler-explorer/compiler-explorer/issues/3138. Not yet fixed.
