### ISSUE TITLE
[BUG]: Dragging a compiler pane tab loses the bottom panel

### ISSUE THREAD

**Issue by Alcaro** [compiler-explorer/compiler-explorer#3616]
### Describe the bug

See title

Probably a recent regression, feels like the kind of thing someone would notice pretty fast.

### Steps to reproduce

- Grab a compiler pane tab
- Put it back in its original location
- Observe the absense of Output (0/1) panel at compiler tab's bottom

A quick f5 makes the site repair itself.

### Expected behavior

No visual change

### Reproduction link

Not applicable

### Screenshots

Before:
![image](https://user-images.githubusercontent.com/5085186/166323327-739f56ec-2032-4571-950c-fa955b9076bf.png)
Drag it like this:
![image](https://user-images.githubusercontent.com/5085186/166323554-e430a6c2-2d0d-4b50-be79-1de2131c9ded.png)
After:
![image](https://user-images.githubusercontent.com/5085186/166323381-b1503e72-8f0b-4bfc-b1ba-1a6b7ca7ba13.png)
(Ignore the broken sponsors pane, that's just because I resized the window so the screenshot size is reasonable. The same issue reproduces on normal window sizes too.)

### Operating System

Lubuntu 21.10

### Browser version

Firefox 99

**Comment by jeremy-rifkin** [comment]
Fascinating, I can reproduce. I will try to fix when I have the chance unless someone beats me to it!
