### ISSUE TITLE
[LIB REQUEST]: boost 1.78 or newer

### ISSUE THREAD

**Issue by jmairboeck** [compiler-explorer/compiler-explorer#3622]
### Library name

Boost

### Library description

same as the existing boost library

### Library repository

https://www.boost.org/

### Motivation

I wanted to test something with boost::span which exists since Boost 1.78 in Boost Core. According to BOOST_VERSION the currently provided version is 1.77 (for x64 MSVC 19.latest). The current latest version is 1.79.

**Comment by RubenRBS** [comment]
Hi! The update frequency for MSVC libraries is longer than those of the rest of the compilers, as we delegate much of the Windows compilers to Microsoft themselves, and there's not _too_ much we can do to speed it up, sorry!

**Comment by timmy-ms** [comment]
Ruben - Feel free to assign these to me when you see them.

Joachim - We use the newest version supported inside of VCPKG. As of May 10th that is 1.79, so that will be live today!

**Comment by jmairboeck** [comment]
The thing I wanted to test was the incompatibility between boost::span and range (https://github.com/boostorg/core/issues/105) which will be fixed in boost 1.80 thankfully. I encountered that problem in our code base and wanted to test it in Compiler Explorer.

Thanks for your efforts!
