### ISSUE TITLE
[COMPILER REQUEST]: GCC 12.1

### ISSUE THREAD

**Issue by cooky922** [compiler-explorer/compiler-explorer#3624]
### Compiler name

GCC

### Compiler version

12.1

### Compiler language

any languages that GCC 12.1 supported

### Compiler homepage

http://www.gnu.org/software/gcc/gcc-12/

### Motivation

GNU has recently announced the new version of GCC which is the 12.1 that has been released recently in a couple of minutes or hours.

**Comment by dkm** [comment]
Compiler build is OK (native/x86_64), will proceed with config changes later tonight.

**Comment by dkm** [comment]
I /think/ I have everything ready:
- compiler has been correctly built (tried locally with https://github.com/compiler-explorer/infra/pull/717 and was able to install/run it)
- infra PR: https://github.com/compiler-explorer/infra/pull/717
- config update PR: https://github.com/compiler-explorer/compiler-explorer/pull/3630
