### ISSUE TITLE
[BUG]: `std::system_error` on perfectly good code

### ISSUE THREAD

**Issue by Banger** [compiler-explorer/compiler-explorer#3628]
### Describe the bug

Running a tiny program that works fine locally on my computer, fails with `std::system_error`.

### Steps to reproduce

```
#include <future>

int main() {
    std::promise<void> prom;
    auto fut = prom.get_future();
    prom.set_value();

    return 1;
}
```

x86-64 gcc 10.2 (I didn't try any other compiler) -O (didn't try other options either)

Result of run:
```
ASM generation compiler returned: 0
Execution build compiler returned: 0
Program returned: 139
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
```

### Expected behavior

Running fine with no output.
This can be added to confirm everything is working fine:
```
    auto res = fut.wait_for(std::chrono::seconds(0));
    switch (res) {
    case std::future_status::deferred:
      std::cout << "deferred\n";
      break;
    case std::future_status::ready:
      std::cout << "ready\n";
      break;
    case std::future_status::timeout:
      std::cout << "timeout\n";
      break;
    }

```
Then the output should be:
```
ready
```

### Reproduction link

https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGEs6SuADJ4DJgAcj4ARpjEEgAcpAAOqAqETgwe3r7%2ByanpAiFhkSwxcVyJdpgOGUIETMQEWT5%2BXAFVNQJ1DQRFEdGxCbb1jc05bcM9fSVlCQCUtqhexMjsHOYAzKHI3lgA1CYbbk4KBMSYrIfYJhoAgpvbu5gHR1ReBMuYVzf3d6EEexYTFCEDmBwA7FY7nsYXtTugQCAksRUCw8EpDm4AG6oPDoK57ZGow5Q26wvZMd6oPZvAGHAAihJRLAAdMBMAQAPq0z6gkk/clE1lKLlYsReTB8jakgWwylEPbnBQvRm0lkAd2BXP4xAg8MRyAQKIYqERSjQDHQCggGjmc350NhCnVhENewgSrBJkhsphoiUcIICJAPPOnNOTA%2BCkRWCosXOCN9TqDBqWdKOmIOZjMsfjmHxAFY3AxzGYHWTyXsoucmABrcvk/3PfUh96fcP1KOImvoACeICTMJbaHeLzcmdLPd7JiLJezDcr1Yu9elSabgeDocwHcjXmjIEcbDTA8d5OHabHE%2Bzh8waZnxdLC/JS7rT4h9J%2BSfOH2IDD2XHLb0PzuDgFloTgC14PwOC0UhTQ4cdLGsOElhWZ5Nh4UgCE0UCFlrEACw0fROEkKCcLgzheGjIjsJg0DSDgWAYEQFBUSSOhYnISg0BYdj6DiYAuA0AIaFoAhYmjCAonIqJQgaftuF4Hi2EEAB5BhaAU2CsCBIxxDo0h8HOGosUwaMDMwVRqneNZYP%2BTBwIM2g8GreSPCwcizjwFhOB4BYqAMYAFAANTwTB1VUpJGF83h%2BEEEQxHYKQZEERQVHUAzdC4fRDGMaxrH0Fzo1gZg2BDFgCFIUy4g4cENC0O04KSRwBHMgBaVSqIc6oWr8CBXDGVpAktaYBnKPI0l6wa9BSSaMlG0pBmyjpeu6UZPBaPQVtqEZelCfpFvGiN1uyIbjr24oxokBYFFQ1Y9DOTA1j84iOEg0hoNg%2BDVHiAA2NrfskPZgGQZB/w0FkzHdRCrEsUg9lwQgSCzDZsr2DxeI44gUa4OZeFohq8IIojHNI0gfMIj7yPgqiQBonCFkYli0ySd4uP6/AiGIPE9Di4RRHEZK%2BbStRyKy0h1WIJgkhisCILIgz4NU95WYBVAqD2H7/sB4HQfByHobYrGcbxrCGYWBALiwOJQVesmKaIz7eBp2w6bNujGvwynHI2BWvso93Cdesw/edgOCdwqqJIyEBJCAA%3D%3D

### Screenshots

Not applicable

### Operating System

Ubuntu 18.04

### Browser version

Vivaldi: 5.2.2623.41 (Stable channel) stable (64-bit)

**Comment by partouf** [comment]
I think it requires -pthread, that solves the issue https://godbolt.org/z/63cPKnc66

But I don't know why it doesn't mention that is the problem...

**Comment by jeremy-rifkin** [comment]
Ah ha! I have finally found explanations [here][1] and [here][2], glibc provides weak symbol stubs for pthread functions so that single-threaded programs don't have to be linked with pthread. I'd personally hope the compiler would detect and warn about this, it's very subtle behavior. Maybe we can find a way to do so?

[1]: https://stackoverflow.com/questions/60381333/reason-for-unknown-exception-in-promise-without-lpthread
[2]: https://stackoverflow.com/questions/21092601/is-pthread-in-glibc-so-implemented-by-weak-symbol-to-provide-pthread-stub-functi

**Comment by partouf** [comment]
> Ah ha! I have finally found explanations [here](https://stackoverflow.com/questions/60381333/reason-for-unknown-exception-in-promise-without-lpthread) and [here](https://stackoverflow.com/questions/21092601/is-pthread-in-glibc-so-implemented-by-weak-symbol-to-provide-pthread-stub-functi), glibc provides weak symbol stubs for pthread functions so that single-threaded programs don't have to be linked with pthread. I'd personally hope the compiler would detect and warn about this, it's very subtle behavior. Maybe we can find a way to do so?

This doesn't really explain why local installations would somehow not need -pthread.

To be completely honest, to me, it's very clear why some of these new threaded things need -lpthread and or -lrt, but I've dealt with c++ crossplatform differences with threading and the likes.

What I find disappointing about gcc is that the requirements aren't explained through header file macros. Which leads to people blaming us.

**Comment by jeremy-rifkin** [comment]
Definitely in agreement there.

I can't reproduce locally, on any system / compiler I have access to, being able to build and run this without -pthread.

**Comment by jeremy-rifkin** [comment]
@Banger What compiler / version / options did you use to run that locally without having to explicitly link with pthread?
