### ISSUE TITLE
Diff link in policies are not correctly generated

### ISSUE THREAD

**Issue by JohelEGP** [compiler-explorer/compiler-explorer#3629]
That is, the Cookie policy and Privacy policy under Policies at the top-right of CE. The diff link links to https://github.com/compiler-explorer/compiler-explorer/commit/#{lastCommit}. Presumably, `#{lastCommit}` should be the commit the respective policy changed.

**Comment by mattgodbolt** [comment]
Thanks: I _think_ we may have fixed this and not yet deployed the fix. We'll check though. Thank you!

**Comment by mattgodbolt** [comment]
It turns out we hadn't. Fixing now. Thanks!

**Comment by mattgodbolt** [comment]
I had to revert my fix, so...I need to unrevert once I fix it!

**Comment by RubenRBS** [comment]
This is now live (for real this time)
