### ISSUE TITLE
[REQUEST]: Display all run commands with full arguments

### ISSUE THREAD

**Issue by piegamesde** [compiler-explorer/compiler-explorer#3639]
### Is your feature request related to a problem? Please describe

I used Godbolt to reproduce and minimize a bug. Now, I'd like to run that part locally (outside of my usual project environment) in order to bisect the compile version. However, I don't know which command line arguments to pass in order to get the desired result.

### Describe the solution you'd like

Have some console where all commands that are run, with all arguments, are displayed.

### Describe alternatives you've considered

-

**Comment by mattgodbolt** [comment]
(We do run other commands whose output is not logged, e.g. `c++filt` etc but if it's a compiler bug I suspect you just need the compiler flags. If this is an issue with linking and execution, that might not be enough)

**Comment by mattgodbolt** [comment]
So! We don't run the linker separately in binary mode, we "just" compile straight to an executable using the compiler as both the compiler and linker driver. So I think you should be set.

And the UI is hardly obvious so don't worry about that! How would you know, honestly!? :) Our UX leads a little to be desired...

Feel free to reopen if there's still stuff missing, but I'm going to close for now.
