### ISSUE TITLE
[REQUEST]: support AST view for ISPC compiler

### ISSUE THREAD

**Issue by dbabokin** [compiler-explorer/compiler-explorer#3648]
### Is your feature request related to a problem? Please describe

ISPC starting from v1.18.0 supports dumping AST with `--ast-dump` switch, so we should support it natively in compiler explorer interface.

### Describe the solution you'd like

"Add new..." button should have "AST output" option for ISPC, like it has for clang.

Note that AST format looks similar to clang, but it's not quite clang AST. So clang highlighting will not work out of the box, but  we can tweak the format to match clang parse in the future.

Also, if it's not possible to make it compiler version sensitive (`--ast-dump` is supported only by 1.18.0), that should be ok to fail for earlier compilers.

### Describe alternatives you've considered

Passing `--ast-dump` directly in the command line will also work.

### Additional context

Not applicable

**Comment by RubenRBS** [comment]
Hi! Thanks for the request. I've now added the necessary checks to have AST produced. It should be live soon if no major issues are found :)
