### ISSUE TITLE
[BUG]: Unable to build CMake based IDE tree project

### ISSUE THREAD

**Issue by ew98** [compiler-explorer/compiler-explorer#3649]
### Describe the bug

Here is a simple example of a C++/CMake project that fails to build and run.

https://godbolt.org/z/v48drr7cc

Similar code runs locally in my VM with 

cmake version 3.16.5 
and
g++ (Gentoo 9.3.0-r1 p3) 9.3.0

If this is a project configuration option, it is not intuitively apparent on what is misconfigured. I've seen this explained in one other SO post:
https://stackoverflow.com/questions/71114607/error-in-setting-up-goldbolt-with-childprocess-launch-failure

however there are no responses to resolve or workaround.

I got the same response using different browsers (Brave/Chrome)

### Steps to reproduce

1. Go to godbolt.org and take the sample routine, add a std::cout statement with includes from <iostream> and <string>
2. Create vanila CMakeLists.txt to build project
3. Select CMake checkbox on IDE tree view
4. Compiler stage appears to have succeeded but there is an error code following the build

### Expected behavior

Should not see compiler output:

<No output file /tmp/compiler-explorer-compiler2022410-7520-1u0ot4x.8ci2g/build/output.s>

Should not see executor output:

Compiler stdout
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/compiler-explorer/gcc-9.3.0/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/compiler-explorer/gcc-9.3.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /app/build
Scanning dependencies of target main
[ 50%] Building CXX object CMakeFiles/main.dir/main.cpp.o
[100%] Linking CXX executable main
[100%] Built target main
Program returned: 255
Program stderr
[F][2022-05-10T23:24:55+0000][1] bool subproc::runChild(nsjconf_t*, int, int, int, int)():448 Launching child process failed

### Reproduction link

https://godbolt.org/z/v48drr7cc

### Screenshots

Not applicable

### Operating System

Windows 10

### Browser version

Brave Browser Version 1.38.111 Chromium: 101.0.4951.54 (Official Build) (64-bit)

**Comment by partouf** [comment]
It's not magic, you'll need to supply your actual executable name (main, not the default output.s)

https://godbolt.org/z/h43rdcW3P

**Comment by ew98** [comment]
Thanks for that. It may not have been on this simple demo project, but the first multi file IDE tree project I tried to do exactly that and the output.s could not be edited.
