### ISSUE TITLE
[BUG]: unable to run java files with public class

### ISSUE THREAD

**Issue by yaojingguo** [compiler-explorer/compiler-explorer#3653]
### Describe the bug

Unable to run Java code.

### Steps to reproduce

1. Visit godbolt.org
2. Select JDK 18.0.0
3. Paste the following code:
```
public class Hi {
  public static void main(String[] args) {
    System.out.println("hello, world");
  }
}
```

### Expected behavior

`Execute the code` output should be `hello, world`.

### Reproduction link

https://godbolt.org/z/xxWWY5aT6

### Screenshots

<img width="1383" alt="截屏2022-05-12 下午12 13 41" src="https://user-images.githubusercontent.com/516386/167990764-79cb797b-b9eb-4476-b8b8-a9bc3db3e8d2.png">

### Operating System

macOS 10.15.7

### Browser version

Google Chrome Version 101.0.4951.54 (Official Build) (x86_64)

**Comment by Headline** [comment]
Hello - Using your link I'm getting the expected output of 

```
<source>:1: error: class Hi is public, should be declared in a file named Hi.java
public class Hi {
       ^
1 error
Compiler returned: 1
```

Was it stuck compiling for you? This error is expected and you should not declare your main class `public`

**Comment by matsjla** [comment]
Compiler Explorer's file name is hard coded as `example.java`, meaning there is a limitation meaning we can't have public classes like this.

One way to achieve this is using the Tree view, but public classes are unfortunately not available for single-file CE snippets.

The solution is to make your class non-public. https://godbolt.org/z/9zq7MnrTo

**Comment by yaojingguo** [comment]
> The solution is to make your class non-public.
This workaround works. Thanks a lot.

@matsjla
