### ISSUE TITLE
[BUG]: Bug with ansi color processing

### ISSUE THREAD

**Issue by jeremy-rifkin** [compiler-explorer/compiler-explorer#3659]
### Describe the bug

The first time this code https://godbolt.org/z/evGE6f7Ga is run it's colored properly as 
![image](https://user-images.githubusercontent.com/51220084/168406237-5ca29a75-9582-42cc-b17e-51b81474ff6c.png)
When the code is rerun the pink color is still applied at the beginning
![image](https://user-images.githubusercontent.com/51220084/168406256-dc5d53d6-8fde-40fc-9785-9b12e8022f8e.png)

### Steps to reproduce

-

### Expected behavior

-

### Reproduction link

-

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment]
After a reload:
```
<div class="program-exec-output" style="color: red;">foo<span style="color:#ff00d7">bar</span></div>
```

if you then cause a recompilation:

```
<div class="program-exec-output" style="color: red;"><span style="color:#ff00d7">foo<span style="color:#ff00d7">bar</span></span></div>
```

**Comment by partouf** [comment]
We call toHtml() here https://github.com/compiler-explorer/compiler-explorer/blob/main/static/panes/output.ts#L224

But we don't clear the "stickyStack" that's used here https://github.com/compiler-explorer/compiler-explorer/blob/main/static/ansi-to-html.ts#L472

So the last state (the pink) was remembered and used for `foo`

We should reset or reconstruct errorAnsiToHtml and normalAnsiToHtml before we use them again after a recompile.

**Comment by jeremy-rifkin** [comment]
I'll go ahead and add a reset method for the filter

**Comment by mattgodbolt** [comment]
Oh neat!!! Nice find and fix :) :tada:
