### ISSUE TITLE
[LIB REQUEST]: toml11

### ISSUE THREAD

**Issue by hwhsu1231** [compiler-explorer/compiler-explorer#3663]
### Library name

toml11

### Library description

toml11 is a C++11 (or later) header-only toml parser/encoder depending only on C++ standard library.

### Library repository

https://github.com/ToruNiina/toml11

### Motivation

I saw that Compiler Explorer supports [`toml++`](https://github.com/marzer/tomlplusplus), but didn't support [`toml11`](https://github.com/ToruNiina/toml11). Because `toml++` is required to use C++17 (or later), it means that we cannot use `toml++` with C++11 or C++14. However, `toml11` can do it.

**Comment by RubenRBS** [comment]
Hi! Thanks for the requests. As it was a pretty easy one, I've gone ahead and added the library myself, and once merged, the changes should be live soon-ish
