### ISSUE TITLE
[BUG]: raw string literals breaks semantic colorization

### ISSUE THREAD

**Issue by nebularnoise** [compiler-explorer/compiler-explorer#3684]
### Describe the bug

Colorization is broken in the code window, after using a raw string literal.

### Steps to reproduce

Paste the following code:
```cpp
#include <string>
#include <iostream>


int main(){
    
    auto s = R""""(
    Hello World
    )"""";

    std::cout << "hello";
    
}
```

### Expected behavior

The following line
```cpp
std::cout << "hello";
```
Should not be colorized fully in 'string colour'.

### Reproduction link

https://godbolt.org/z/3q71v411j

### Screenshots

![Screenshot_20220518_124917](https://user-images.githubusercontent.com/33561374/169022196-cddb0016-8e50-4abe-bafb-ce8db904d2a7.png)

**Comment by matsjla** [comment]
This is an issue with the upstream monaco-editor theme https://github.com/microsoft/monaco-editor/blob/main/src/basic-languages/cpp/cpp.ts but we could possibly overwrite it in our cppp mode https://github.com/compiler-explorer/compiler-explorer/blob/main/static/modes/cppp-mode.ts

**Comment by RubenRBS** [comment]
Similar to #513, I thought it was supposed to be fixed

**Comment by jeremy-rifkin** [comment]
It's fine for more typical raw string literals like https://godbolt.org/z/6Kvxc564G, the quotes in the delimiter sequence are throwing things off.
@nebularnoise Have you submitted an issue upstream yet?

**Comment by jeremy-rifkin** [comment]
Thanks :)

**Comment by jeremy-rifkin** [comment]
https://github.com/microsoft/monaco-editor/pull/4436 Ostensibly will fix things. Once the change from https://github.com/microsoft/vscode/pull/183463 is in monaco we can also fix on the CE side of things.

**Comment by jeremy-rifkin** [comment]
This is now fixed upstream 🎉
