### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by anterpin** [compiler-explorer/compiler-explorer#3688]
### Describe the bug

# Vim Mode
In the text editor vim mode Ctrl+[ should have the same behaviour as Esc.
Right now it does nothing.

### Steps to reproduce

1. Visit godbolt.org
2. Set to Vim Mode
3. Press Ctrl+[

### Expected behavior

It should have the same behaviour as Esc

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
We use https://github.com/brijeshb42/monaco-vim for vim keybinds, I think this issue would be better directed there
