### ISSUE TITLE
[BUG]: Variable-width fonts wrap at wrong location

### ISSUE THREAD

**Issue by davidstone** [compiler-explorer/compiler-explorer#3698]
### Describe the bug

If you set the font to a variable-width / proportional font instead of a fixed-width / monospace font, word wrapping occurs as though the font were a fixed-width font.

Note that VS Code had the same bug:
* https://github.com/microsoft/vscode/issues/2654
* https://github.com/microsoft/vscode/issues/89573

The conclusion was that they added a setting to make word wrapping work properly with variable-width fonts -- `"editor.wrappingStrategy": "advanced"`.

### Steps to reproduce

1. Visit godbolt.org
2. Go to Settings -> Editor -> Desired Font Family in editors
3. Change font to Verdana
4. Check Enable Word Wrapping
5. Write a long line in the source editor (all 'l' will wrap too early, all 'W' will wrap too late and add horizontal scroll)

### Expected behavior

Word wrapping should be based on actual character length, not number of characters

### Reproduction link

Not applicable

### Screenshots

![image](https://user-images.githubusercontent.com/1459008/169587931-76af646b-e6b6-43fc-ae6b-5f91b65182d6.png)

**Comment by jeremy-rifkin** [comment]
Thank you for the detailed bug report!
