### ISSUE TITLE
Ada compile to binary and execution broken

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#3709]
I teach computer science and I am using godbolt to share codes in different languages. In the last semester all ADA code was running fine. I was checking the material for this semester and I noticed that ADA code is not running. It shows the following message:
_try "gnatmake --help" for more information.
Compiler did not produce an executable_

Link: https://godbolt.org/z/dY49hPeWf

I am trying the Tree version, but still not working.

Any help?
Thanks.

_Originally posted by @jhkhouri62 in https://github.com/compiler-explorer/compiler-explorer/issues/3459#issuecomment-1136144989_

**Comment by dkm** [comment]
I saw these changes. After the initial merge, GNAT was completely broken if any option was added in the interface, and then it was working again after the following changes... I'll apply your suggestion, thanks!

**Comment by dkm** [comment]
The issue here is that the assumption that the inputFileName is last in the `options` list given to `runCompiler` does not hold anymore. Not sure since when, but it was not the best solution.

**Comment by dkm** [comment]
I've a patch, but I think it would be better if I could test it a bit more, so won't merge it as quickly as expected.
It changes how options are handled so I really need to test all scenario where options are inserted by Compiler Explorer... Are you in a hurry @jhkhouri62 or can this wait a few more days?

**Comment by jhkhouri62** [comment]
It is fine, I can wait... in two weeks I shall introduce Abstract Data Type and ADA is suitable for that. Most of the examples I use is based on godbolt online compiler. Thanks for prompt reply.

**Comment by partouf** [comment]
changes for this are now live

**Comment by jhkhouri62** [comment]
It is working!! I am putting the godbolt links back in my class presentation. I have a comment on ADA multi file with Tree resource. It works fine, but only if name the main file as _example.adb_.

link: https://godbolt.org/z/WaYxoesKK 

If I use another name as here https://godbolt.org/z/qq9erqhPb compiler issues this message:

<File example.adb has no content or file is missing>

It is not a big issue. You did a great job.

Thank you all.
