### ISSUE TITLE
[BUG]: Mysterious behavior with # in command line arguments

### ISSUE THREAD

**Issue by AaronBallman** [compiler-explorer/compiler-explorer#3719]
### Describe the bug

Consider the following code:
```
#warning "what?"
#pragma message("whattt??")
```
In Clang, you can silence the first diagnostic with `-Wno-#warnings` and the second with `-Wno-#pragma-messages`. Additionally, you can upgrade them into errors via `-Werror=#warnings` and `-Werror=#pragma-messages`.

However, in CE, you... can't? Can? A bit of both? I honestly am not certain what's going on.

### Steps to reproduce

On the site, select Clang as the compiler, enter the code above.

1) Add `-Wno-#warnings -Wno-#pragma-messages` as the command line arguments for the compiler. Notice that the diagnostics are not suppressed. Try it again on a native client and they will be.
2) Delete the old command line arguments and add `-Werror=#warnings -Werror=#pragma-messages` instead. Notice that the `#warning` was upgraded into an error, but the `#pragma message` was not.
3) Scratch your head and wonder how that happens. :-)

### Expected behavior

For the first step, I'd expect both diagnostics to be suppressed same as on the command line. For the second step, I'd expect both diagnostics to be upgraded to an error. This is the behavior you get from the command line.

### Reproduction link

https://godbolt.org/z/68Kej8Pf7

### Screenshots

Not applicable

**Comment by partouf** [comment]
Seems everything after the # is getting filtered out by clientside javascript, unknown where

**Comment by AaronBallman** [comment]
Oh interesting, could that explain this behavior with `-###` as well? (This would normally print out the cc1 invocation from the driver.)

https://godbolt.org/z/TxKna4Yrj

**Comment by partouf** [comment]
utils isn't used client-side though

**Comment by partouf** [comment]
wait it does work clientside now, im confused

**Comment by partouf** [comment]
so maybe it is a serverside issue

**Comment by partouf** [comment]
confirmed with a unittest its indeed the splitArguments function
