### ISSUE TITLE
[BUG]: please switch to a different cppcoro fork

### ISSUE THREAD

**Issue by dangelog** [compiler-explorer/compiler-explorer#3739]
### Describe the bug

CE allows users to select `cppcoro` as a 3rd party library. However it uses https://github.com/lewissbaker/cppcoro which is unmaintained and does not even work on any recent compiler (as it has `#include <experimental/stuff>`). 

https://github.com/andreasbuhr/cppcoro seems to be a much more maintained fork.

### Steps to reproduce

1. Add cppcoro as a 3rd party library
2. Try to build anything that uses it, e.g. https://gcc.godbolt.org/z/vxrz79nr5

### Expected behavior

It should build :)

### Reproduction link

https://gcc.godbolt.org/z/vxrz79nr5

### Screenshots

Not applicable

**Comment by partouf** [comment]
this is now switched over
