### ISSUE TITLE
[BUG] Output assembly is assumed to be x86-64 for Rust

### ISSUE THREAD

**Issue by ghost** [compiler-explorer/compiler-explorer#3759]
I've been using Godbolt.org with Rust for Arm32/Arm64, but all instruction documentation seems to only refer to x86 documentation, which is erroneous, as this can be specified via compiler flags

![0](https://user-images.githubusercontent.com/90156453/172988827-ff08e6b8-0e04-46c6-91df-0b72616b0bf3.png)
.

**Comment by dkm** [comment]
Yes, CE don't check the compiler option to guess what ISA you are targetting. We would need something in between what we have for C/C++ and that. I tried applying the same hack as in C/C++ for clang, but it adds dozens and dozens of compilers in the list (but all are pointing to the same compiler...). A better approach would be to have a dropdown menu or parsing options for getting the target....

**Comment by jeremy-rifkin** [comment]
Repro https://godbolt.org/z/db446odsj

There is now a compiler overrides menu which has a target architecture dropdown menu. It isn't yet used to update the instruction set used for documentation and whatnot but it should be possible to do this.
