### ISSUE TITLE
[COMPILER REQUEST]: Swift 5.7 nightly

### ISSUE THREAD

**Issue by igor-makarov** [compiler-explorer/compiler-explorer#3762]
### Compiler name

Swift

### Compiler version

5.7 - nightly

### Compiler language

Swift

### Compiler homepage

https://www.swift.org/download/

### Motivation

Hi! 

I'm a very big fan of Compiler Explorer!

Swift 5.7 is now in pre-release phase. This means that it's got its own release branch with actively built snapshots.

It's probably going to be up for the coming months. I believe it should be added in the same way as `nightly` is - with periodic pulls from `swift.org`.

PRs:
* https://github.com/compiler-explorer/compiler-explorer/pull/3764
* https://github.com/compiler-explorer/infra/pull/748

Thanks!

**Comment by igor-makarov** [comment]
I'm gonna add it as another 'nightly' compiler. 
FYI @Lukasa

Where do I choose the display name in the website drop-down?

**Comment by igor-makarov** [comment]
Edited the issue description to be more useful.

**Comment by igor-makarov** [comment]
@mattgodbolt quick question - does 'nightly' actually mean something other than 'each night'? 
I opened the Swift `5.7-nightly` compiler and it shows a version that is 11 days old and not the latest, from 3 days ago. The same seems to be the case for the `main` nightly as well.

**Comment by partouf** [comment]
`--version` says it's from a commit from 4 days ago now, so that seems to check out https://godbolt.org/z/sMPE1o4fq
The i info icon is cached version information that only refreshes when we deploy a new CE version.

**Comment by igor-makarov** [comment]
@partouf you're right - I see the latest version when I run it with `-v`.

I'll open a separate issue about the web UI being out of sync. Thanks for clearing it up!

**Comment by igor-makarov** [comment]
Opened https://github.com/compiler-explorer/compiler-explorer/issues/3858 on the popover bug.
