### ISSUE TITLE
[REQUEST]: Pre-fill `--edition=2021` for Rust

### ISSUE THREAD

**Issue by ojeda** [compiler-explorer/compiler-explorer#3765]
### Is your feature request related to a problem? Please describe

Arguably, users may prefer to compile with the latest Rust edition by default (`--edition=2021`), instead of the first one (`--edition=2015`, compiler default).

With the new Rust library support (https://github.com/compiler-explorer/compiler-explorer/issues/3763), this is even more prominent because one needs to compile with the newer edition or manually add `extern crate` declarations.

### Describe the solution you'd like

Pre-fill the compiler flags box with `--edition=2021` when a new compilation or execution window is added for the Rust language.

This also allows users to more quickly switch the edition if needed.

### Describe alternatives you've considered

Do it by default in the compiler flags.
  - The compiler does not allow more than one `--edition` flag, thus users would not be able to switch.

Do it by default in the compiler flags, but parse users' flags and, if `--edition` is detected, do not add the `--edition` to the base flags.
  - Potentially surprising behavior for users.

Add a combobox to select the edition.
  - Requires extra UI elements.

### Additional context

The Rust Playground does select 2021 as the default edition. Cargo also creates projects with the latest edition by default.

**Comment by narpfel** [comment]
I’ve also been annoyed by the 2015 default in the past.

For reference, the 2018 edition was stabilised in [v1.36](https://doc.rust-lang.org/edition-guide/rust-2018/index.html), the 2021 edition was stabilised in [v1.56](https://doc.rust-lang.org/edition-guide/rust-2021/index.html), so always setting `--edition=2021` would not work for old versions.

> Do it by default in the compiler flags, but parse users' flags and, if --edition is detected, do not add the --edition to the base flags.

I personally would not find this surprising. Also, there’s already precedent for this with the `--emit` flag:
https://github.com/compiler-explorer/compiler-explorer/blob/1123f0f58f91e68f7b94c012863a25fc05fe9b5b/lib/compilers/rust.ts#L127-L136

**Comment by partouf** [comment]
I don't really understand why rust doesn't do this by default itself when a certain "edition" is stable enough. With C++ the compiler vendors update the default Standard C++ version every few major versions, we assume and rely on that.

**Comment by narpfel** [comment]
I believe the idea is that changing the default edition is considered a breaking change, which violates Rust’s stability guarantee.

Relevant comment in the original editions RFC: https://github.com/rust-lang/rfcs/pull/2052#issuecomment-312747178

**Comment by partouf** [comment]
> I believe the idea is that changing the default edition is considered a breaking change, which violates Rust’s stability guarantee.
> 
> Relevant comment in the original editions RFC: [rust-lang/rfcs#2052 (comment)](https://github.com/rust-lang/rfcs/pull/2052#issuecomment-312747178)

I guess that refers to breaking changes in code, as binary compatibility is already out of the window with every version anyway.

I can understand the reasoning, but then it also follows that we do not make an edition change without making it fully clear to the user.

**Comment by RubenRBS** [comment]
Just a comment for anyone who tries to implement the suggested solution:
> Pre-fill the compiler flags box with --edition=2021 when a new compilation or execution window is added for the Rust language.
I don't think there currently is (If there is then just ignore me, but please point to it!) a way to prefill the options for a compiler in the UI. We should first try to add this feature. Note that it's definetely harder to get right than it sounds

**Comment by partouf** [comment]
I was thinking maybe we could solve it in a similar way as https://github.com/compiler-explorer/compiler-explorer/issues/3682 and https://github.com/compiler-explorer/compiler-explorer/issues/1966 even though they're not really equivalent (like stdlib version versus c++ version)

**Comment by ojeda** [comment]
HLSL when using DXC would also benefit from one of the solutions here.

**Comment by mattgodbolt** [comment]
Right: there's definitely some UI/UX concerns but a general solution to the "add a default argument, and make it clear to the user it's there, while letting them change it" would be great.

**Comment by kornelski** [comment]
This is another case of Rust not fitting the C model: #1524

> I don't really understand why rust doesn't do this by default itself 

Rust users generally don't invoke `rustc` directly, but instead run builds via Cargo. Cargo *does* change the default edition over time for newly-created projects, and automatically sets the appropriate `--edition` flags.

But because compiler explorer is built around the lower-level `rustc`, it lacks the conveniences that Cargo does for Rust users.

This problem came up in discussion about raising `rustc`'s default edition. Rust won't do it due to backwards compatibility, at least not without a long transition period. However, it could warn about the gotcha of the missing edition flag. However, the warning would be annoying particularly in the compiler explorer. So lack of default `--edition` flag on rust.godbolt.org is ironically a blocker for Rust raising the default edition.

https://users.rust-lang.org/t/why-crates-for-rust-2015-are-still-around/92361/13

**Comment by partouf** [comment]
We have added a new screen where if you create a new Rust compiler, or reset your view (and you're on rust.godbolt.org or have rust as a default), Edition 2021 now gets selected by default.

(Note that when you switch from for example c++ to rust, it works differently, you'll have to select it manually from the new screen)

![Screenshot from 2023-05-16 05-05-47](https://github.com/compiler-explorer/compiler-explorer/assets/442630/506bb141-339c-4ea1-a27f-95ef5eac2ea2)
![Screenshot from 2023-05-16 05-06-14](https://github.com/compiler-explorer/compiler-explorer/assets/442630/d2566b27-0072-47d8-9332-e6862d9b2509)

Hope that helps!

**Comment by RalfJung** [comment]
This change made it quite hard to run Rust code against old compilers, see https://github.com/compiler-explorer/compiler-explorer/issues/5349. The edition selection is hidden way too much, people are unlikely to find this out. I was ready t just give up and conclude that godbolt no longer works with old compilers, until I decided to report an issue, then found this old issue, and then found the work-around.

**Comment by partouf** [comment]
Feel free to send a PR with improvements, but this is what multiple people wanted

**Comment by Kobzol** [comment]
I hit the same problem as Ralf, and also found it unintuitive to find the correct edition switch setting. Maybe godbolt could detect if `--edition` is passed and in such case it would not pass the default `2021` value?

**Comment by partouf** [comment]
> I hit the same problem as Ralf, and also found it unintuitive to find the correct edition switch setting. Maybe godbolt could detect if `--edition` is passed and in such case it would not pass the default `2021` value?

It should, if not its a bug

**Comment by partouf** [comment]
> > I hit the same problem as Ralf, and also found it unintuitive to find the correct edition switch setting. Maybe godbolt could detect if `--edition` is passed and in such case it would not pass the default `2021` value?
> 
> It should, if not its a bug

Oh im wrong no, overrides always have preference, which makes sense outside of rust world

**Comment by narpfel** [comment]
> Maybe godbolt could detect if `--edition` is passed and in such case it would not pass the default `2021` value?

That’s what I proposed in https://github.com/compiler-explorer/compiler-explorer/issues/3765#issuecomment-1152994111. It seems this is still possible?

Side note: `--edition` is only passed by default when creating a new compiler, but not when switching to Rust from another language (also switching languages unsets/removes all overrides?). I never noticed that it could be passed by default until re-reading https://github.com/compiler-explorer/compiler-explorer/issues/3765#issuecomment-1548909937 just now, so I still always manually pass `--edition=2021` if I need it.

**Comment by ojeda** [comment]
I would still prefer that we go with pre-filling, thus making it explicit for the user as well as making the edition easy to change.

**Comment by mattgodbolt** [comment]
Pre-filling is something we've not done before. I don't have a good idea how to do the UI:
- user visits godbolt.org
- we pre-fill with `--edition=2023` as default Rust has that (or whatever)
- user picks an older rust
- older rust complains about bad edition? flag not compatible
- user has to edit pre-filled box?

is that the flow? Then there's exactly one pre-fill which must be `--edition=LATEST` as that's what the user will see whenever they pick Rust, even if they immediately then choose another rust version?

**Comment by mattgodbolt** [comment]
> I hit the same problem as Ralf, and also found it unintuitive to find the correct edition switch setting. Maybe godbolt could detect if `--edition` is passed and in such case it would not pass the default `2021` value?

This is an idea too, though it means parsing the command-line (`--edition=X` or `--edition X` or `-e X` or whatever cmdline params Rust supports). We can do a cheesey way of `if the string `--edition` is anywhere, then don't pass edition) maybe?

**Comment by Kobzol** [comment]
I think that even grepping the cmdline would be enough, as a heuristic.

**Comment by ojeda** [comment]
@mattgodbolt Yeah, that is exactly the flow I was thinking.

> Then there's exactly one pre-fill which must be --edition=LATEST as that's what the user will see whenever they pick Rust, even if they immediately then choose another rust version?

Yeah. Personally, I don't mind the compiler complaining that the edition is wrong if I change the version of the compiler. In fact, I appreciate getting the error. Changing it would be faster anyway than going into "Overrides" like today or, before that, writing the full flag name manually.

One could be smarter here (e.g. changing the pre-filled flag to the right edition if the window is pristine and the version changed), but I don't think the magic is really needed. Instead, what could be very useful is letting the user customize their pre-fill flags for languages/compilers (e.g. `-std=c11 -Wall -Wextra -Wpedantic -O2`), but that is an orthogonal suggestion (assuming it is not possible already, CE has many features! :).

In addition, I would imagine new users use mostly the latest stable version or nightly in CE, where the pre-filled edition will work, so many of them will not need to change it. And for those that switch to an older compiler, it should be fairly obvious how to fix the edition since the UI widget for changing the version is adjacent to the `--edition` flag. In other words, it is hard to miss.

**Comment by mattgodbolt** [comment]
Thanks @ojeda - we'll chat on the team and see what comes up. The edition being an override was (we thought) a nice way of supplying the param in a unified way, but obviously it's not working quite as everyone would like.

**Comment by ojeda** [comment]
I have added the user-editable suggestion to https://github.com/compiler-explorer/compiler-explorer/issues/3100 (from https://github.com/compiler-explorer/compiler-explorer/issues/3765#issuecomment-1668478130), simplified the wording and updated it with some of the recent developments (it was fairly old).

Thus the proposal now proposes prefilling by compiler/language (so e.g. `--edition 2021` for Rust here could be such a user) and making these defaults user-configurable.
