### ISSUE TITLE
[REQUEST]: recompile only after setting all parameters (execution args, compiler, src code) and not after each parameter setting  

### ISSUE THREAD

**Issue by lfero** [compiler-explorer/compiler-explorer#3783]
### Is your feature request related to a problem? Please describe

Every time a change is made to the src code/ adding arguments/changing compiler Godbolt executes re-compilation. can we recompile only after setting all parameters (execution args, compiler, src code)?

### Describe the solution you'd like

Maybe to add a button to the executor pane (like the Clear cache & recompile button) that enables manual re-compilation

### Describe alternatives you've considered

Adding a button to do manual compilation

### Additional context

Not applicable

**Comment by RubenRBS** [comment]
Hi. Sorry that this took so long to address, we're slower to catch up this time of the year. The request makes a lot of sense, so I've gone ahead and implemented a solution for it in #3862. 

Once the PR is merged, under `Settings > Compilation` you'll find `Compile executor automatically when arguments change`. Disabling it will disable the automatic recompilation. With the also newly added recompilation button (identical to the compiler one, as you suggested), this will hopefully be what you were looking for :). Again, sorry for the radio silence for almost a month!
