### ISSUE TITLE
[REQUEST]: Add descriptions of PTX assembly instructions for CUDA C++

### ISSUE THREAD

**Issue by jrhemstad** [compiler-explorer/compiler-explorer#3785]
### Is your feature request related to a problem? Please describe

Today, for Standard C++, in the assembly pane you can hover over instructions to get a tool tip that describes each instruction. 

This does not currently work for PTX assembly instructions in CUDA C++.

### Describe the solution you'd like

When compiling CUDA C++ code, I would like to be able to hover over the generated PTX assembly and get a description of each instruction.

### Describe alternatives you've considered

N/A

### Additional context

After talking with @mattgodbolt, here's the rough breakdown of how this works in other languages:

There's a `BaseAssemblyDocumentationProvider` that defines a `getInstructionInformation` function to perform a lookup of the description of the instruction, e.g., for [`amd64`](https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/asm-docs/amd64.ts) 

This queries a corresponding ["database" of instruction <-> description mappings](https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/asm-docs/generated/asm-docs-amd64.js). 

This database is generated by one of these [docenizer scripts](https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/scripts/docenizers/docenizer.py) that parses the html docs for the ISA.

For CUDA PTX I think the steps here are:
1. Create a `docenizer` script to generate the instruction description database from the [PTX ISA docs](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#instructions).
2. Put the instruction database in `generated/asm-docs-ptx.js`
3. Create a `ptx.ts` documentation provider that connects to the `asm-docs-ptx.js` database
4. Profit!

**Comment by matsjla** [comment]
Yes, there is also a more thorough document on adding these here! https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/AddingAssemblyDocumentation.md

**Comment by jeremy-rifkin** [comment]
Should be implemented by #5129
