### ISSUE TITLE
[BUG]: linking against date library doesn't bring in required curl

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#3791]
### Describe the bug

The date library has been built with the remote api enabled (which lets it go grab tz info from the internet using libcurl). However, linking against it will give missing symbols from libcurl, as that's not about.

### Steps to reproduce

Click the link below. Also tried adding `-lcurl` but there's no curl lib around in the iamge.

### Expected behavior

Linking against curl, or else not having the ability to fetch things from the internet. If we disable the download (and of course the executable doesn't have internet access) maybe we'll need to make the `INSTALL` point at a timezone file that we add to the sandbox ( https://howardhinnant.github.io/date/tz.html#Installation )

### Reproduction link

https://godbolt.org/z/ox5jcb7T6

### Screenshots

Not applicable

**Comment by partouf** [comment]
Weird.. I remember it used to work and it didnt need curl.. either way, we can ofcourse add curl and add it as a dependency. Dont think we have curl-dev currently added to our image, but then we could just add it as an extra liblink

**Comment by mattgodbolt** [comment]
I wonder if the base image gained libcurl-dev or something and that leaked into the scripts autodetect (or something)

**Comment by partouf** [comment]
Xersesc seems to require libcurl as well https://github.com/compiler-explorer/compiler-explorer/discussions/2763#discussioncomment-3023120

I hope to continue my efforts later today
