### ISSUE TITLE
[BUG]:  Godbolt link stopped working and automatically change to resetlayout

### ISSUE THREAD

**Issue by ranaanoop** [compiler-explorer/compiler-explorer#3811]
### Describe the bug

I used to share godbolt links but recently noticed that the shared links has stopped working. For example, you can see [here](https://stackoverflow.com/questions/72664029/msvc-vs-clang-gcc-bug-during-overload-resolution-of-function-templates-one-of-wh) that i've shared a godbolt link but when we click on that [link](https://godbolt.org/z/8KsrcnMez) nothing is displayed on the screen and the link automatically changes from `https://godbolt.org/z/8KsrcnMez` to `https://godbolt.org/resetlayout/8KsrcnMez`  . 

You can confirm this by visiting: https://godbolt.org/resetlayout/8KsrcnMez 

This happens for other gotdbolt links also that i shared. What is the problem here and is it(the problem) from my side or it is a compiler explorer bug.

### Steps to reproduce

1. Visit https://godbolt.org/resetlayout/8KsrcnMez
On visiting the above site you'll notice that the given link automatically changes to https://godbolt.org/resetlayout/8KsrcnMez

### Expected behavior

The link should open normally and the content should be displayed. Currently we get a blank screen which should not happen.

### Reproduction link

https://godbolt.org/z/8KsrcnMez

### Screenshots

![Screenshot from 2022-06-27 20-49-53](https://user-images.githubusercontent.com/93918384/175975880-95e80f90-6d91-4579-a5ac-8f0aaac9ba16.png)

### Operating System

Ubuntu Linux 18.04

### Browser version

Firefox 101.0.1(64 bit)

**Comment by partouf** [comment]
Oops.. Thanks for the repro
We recently converted some code to typescript, but we obviously missed some codepaths

**Comment by partouf** [comment]
Fix is now live
