### ISSUE TITLE
[BUG]: MSVC compiler incorrectly rejects trivial code while other compiler accept it

### ISSUE THREAD

**Issue by ranaanoop** [compiler-explorer/compiler-explorer#3813]
### Describe the bug

I noticed that a very simple/trivial C++ example given [here](https://godbolt.org/z/do5Kvcz1f) is not working with msvc. By not working i mean there is a red cross shown instead of a green tick mark. As you'll see by clicking on the link given above, the code is trivial and other compilers have no problem in processing it. But msvc rejects it for some reason. 

I also noticed that for if we try out the same example by opening a separate godbolt window/tab it works in msvc. For example [here](https://godbolt.org/z/PMx4K6v78) it works without any problem but [here](https://godbolt.org/z/do5Kvcz1f) it doesn't.

### Steps to reproduce

1. Visit https://godbolt.org/z/do5Kvcz1f

### Expected behavior

There should be green tick marks for msvc also instead of the currently shown red cross marks. 

### Reproduction link

https://godbolt.org/z/do5Kvcz1f

### Screenshots

![Screenshot from 2022-06-28 15-13-04](https://user-images.githubusercontent.com/93918384/176149362-a099a195-31ec-45c0-a23c-92a87c00f373.png)

### Operating System

Ubuntu Linux 18.04

### Browser version

Firefox 101.0.1(64 bit)

**Comment by partouf** [comment]
Seems to be an UI bug, the compilation on the request/response side appears to be working correctly

**Comment by ranaanoop** [comment]
Yes, moreover i also noticed that there used to be a icon shown at the right corner which is not shown anymore after the update. For reference, i have attached a screenshot below which highlight the icon i am talking about. This icon was very useful as in case of error, when the user hovered over this icon, it used to open up a tooltip showing the errors.

But this icon is not anymore shown. Is this a regression or was this intended. I was thinking of opening a feature request issue or a bug report but i am not sure which of the two. Can you tell whether it is possible to bring back this icon and whether a new issue is required for this. 
![ui-change](https://user-images.githubusercontent.com/93918384/176165540-0ec9db26-b777-4687-b892-bc8014952def.png)

**Comment by RubenRBS** [comment]
It's totally a regression, nice catch

**Comment by ranaanoop** [comment]
@RubenRBS I've opened a separate issue for the missing icon [here](https://github.com/compiler-explorer/compiler-explorer/issues/3814) and delete my comment as it is no longer needed. And thanks for the confirmation.

**Comment by ranaanoop** [comment]
@partouf Looks like the bug has been solved. [Demo](https://godbolt.org/z/do5Kvcz1f).

**Comment by partouf** [comment]
yes, someone fixed it, thanks for reminding me
