### ISSUE TITLE
[BUG]: Notebook icon not showing anymore

### ISSUE THREAD

**Issue by ranaanoop** [compiler-explorer/compiler-explorer#3814]
### Describe the bug

I noticed that there used to be an icon shown at the right corner which is not shown anymore after the update. For reference, i have attached a screenshot below which highlight the icon i am talking about. This icon was very useful in case of error, when the user hovered over this icon, it used to open up a tooltip showing the errors.

But this icon is not shown anymore. This seems to be regression or was this intended i am not sure. **Is there a way to bring back this icon** so that when i hover over this notebook icon(shown by an arrow in the attached screenshot) i get a tooltip containing the error as it used to do before. 
The screenshot shown below is from earlier time(like 3 or 4 weeks) but now there is no such icon shown anymore as can be verified [here](https://godbolt.org/z/jxKxv43fa).

### Steps to reproduce

1. Visit https://godbolt.org/z/jxKxv43fa 

On visiting the above mentioned link you'll find that the icon is not anymore shown there. 

### Expected behavior

I expect the notebook icon to be shown so that when i hover over it and if there are any errors then a tooltip should open which should contain all the errors. 

### Reproduction link

Not applicable

### Screenshots

![ui-change](https://user-images.githubusercontent.com/93918384/176165540-0ec9db26-b777-4687-b892-bc8014952def.png)

### Operating System

Ubuntu Linux 18.04

### Browser version

Firefox 101.0.1(64 bit)

**Comment by mattgodbolt** [comment]
Thanks for the great bug filing with screenshots! I'm certain this was not removed on purpose: we'll take a look - thanks!

**Comment by ranaanoop** [comment]
@mattgodbolt @RubenRBS I noticed just now that the notebook icon is back!. I have attached the screenshot below which shows 2 things: 

1) In the first screenshot we can see that in case there is any error in the program, the notebook icon is shown for all compilers.

2) In the second screenshot we can see that in case there is no error in the program, the notebook icon is shown only for msvc and not for gcc and clang. **I am curious to know if this was intentional**. That is, in case there is no error, only the msvc tabs have the notebook icon. 

**Overall I'm satisfied with the result which is that i wanted the notebook icon in case of an error.** 

Thanks to the developers!

![screenshot1](https://user-images.githubusercontent.com/93918384/185451119-e97b4511-e39e-4858-bdc5-ae749ebf4eab.png)

![screenshot2](https://user-images.githubusercontent.com/93918384/185451162-4a907e20-7b68-4793-ae7b-01ca55393dc3.png)

**Comment by RubenRBS** [comment]
Thanks for noticing! Sorry it took so long to bring them back.

The icon is not meant to be shown for msvc either, I just forgot to implement the proper checks. Nice catch!

(MSVC always prints the input filename so we have to check for that)

**Comment by ranaanoop** [comment]
@RubenRBS I see, thanks.
