### ISSUE TITLE
[LIB REQUEST]: YOMM2 - open multi-methods for C++17

### ISSUE THREAD

**Issue by jll63** [compiler-explorer/compiler-explorer#3818]
### Library name

YOMM2

### Library description

YOMM2 implements fast, open multi-methods that closely follow the proposal by Peter Pirkelbauer, Yuriy Solodkyy and Bjarne Stroustrup [in this paper](https://www.stroustrup.com/multimethods.pdf)

### Library repository

https://github.com/jll63/yomm2

### Motivation

To be honest, I am the author of this library, and I feel that having it in compiler explorer could help popularize it. Beyond that, I want to promote the inclusion of this feature in the language.

The library produces code that is compact and fast. Compiler explorer would neatly showcase that. 

Example of a call to a method with one virtual argument (the open method equivalent of a virtual function call):
```asm
	movq	%rax, %r12
	movq	vtable for Dog+16, (%rax)
	movq	yorel::yomm2::detail::dispatch_data::instance<yorel::yomm2::default_registry>::_+24(%rip), %rax
	movb	yorel::yomm2::detail::dispatch_data::instance<yorel::yomm2::default_registry>::_+40(%rip), %cl
	movslq	yorel::yomm2::detail::method<_yomm2_method_kick, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (yorel::yomm2::virtual_<Animal&>), yorel::yomm2::default_policy>::slots_strides(%rip), %rdx
	movl	typeinfo for Dog, %esi
	imulq	yorel::yomm2::detail::dispatch_data::instance<yorel::yomm2::default_registry>::_+32(%rip), %rsi
	shrq	%cl, %rsi
	movq	(%rax,%rsi,8), %rax
	leaq	40(%rsp), %rdi
	movq	%r12, %rsi
	callq	*(%rax,%rdx,8)
```

Example of a call to a multi-method with two virtual arguments:
```asm
	movq	%rax, %r12
	movq	vtable for Dog+16, (%rax)
	movq	yorel::yomm2::detail::dispatch_data::instance<yorel::yomm2::default_registry>::_+24(%rip), %rax
	movq	yorel::yomm2::detail::dispatch_data::instance<yorel::yomm2::default_registry>::_+32(%rip), %rdx
	movb	yorel::yomm2::detail::dispatch_data::instance<yorel::yomm2::default_registry>::_+40(%rip), %cl
	movq	yorel::yomm2::detail::method<_yomm2_method_meet, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (yorel::yomm2::virtual_<Animal&>, yorel::yomm2::virtual_<Animal&>), yorel::yomm2::default_policy>::slots_strides(%rip), %rsi
	movl	typeinfo for Bulldog, %edi
	imulq	%rdx, %rdi
	shrq	%cl, %rdi
	movq	(%rax,%rdi,8), %rdi
	movslq	(%rsi), %rbx
	movq	(%rdi,%rbx,8), %rbx
	movl	typeinfo for Dog, %edi
	imulq	%rdx, %rdi
	shrq	%cl, %rdi
	movq	(%rax,%rdi,8), %rax
	movslq	8(%rsi), %rcx
	movslq	16(%rsi), %rdx
	movslq	(%rax,%rcx,8), %rax
	imulq	%rdx, %rax
	leaq	8(%rsp), %rdi
	movq	%r14, %rsi
	movq	%r12, %rdx
	callq	*(%rbx,%rax,8)
```
As for a snippet of code, you can run the test suite, or compile any of the examples in the `examples` directory. E.g.:

```
$ cd examples
$ clang++-12 -std=c++17 adventure.cpp -lyomm2 -oadventure
$ ./adventure
bob fights elliot with axe:
not agile enough to wield
rambo fights paddington with axe:
and cuts it into pieces
rambo fights paddington with banana:
are you insane?
rambo fights elliott with axe:
and dies a honorable death
bob fights elliot with hands:
you just killed a dragon with your bare hands. Incredible isn't it?
rambo fights elliot with hands:
you just killed a dragon with your bare hands. Incredible isn't it?
```

**Comment by RubenRBS** [comment]
Hi! Thanks for taking the time to open the library request. As you might have seen, some work has already been done in order to add the lib to the site, but as with all the libraries that need building, the process is a bit slower than header-only libs. We hope to be able to finish soon :tm:

**Comment by partouf** [comment]
Libraries have been built, all thats needed is to add the library to the c++ properties file

**Comment by jll63** [comment]
> [...] as with all the libraries that need building, the process is a bit slower than header-only libs

Thanks! Once it has been built and installed for the first time, will it be easier to install new versions?

**Comment by RubenRBS** [comment]
Yes! Both compiler-explorer/infra and this repo will need PRs in case of new versions.

The first one will need a line here, https://github.com/compiler-explorer/infra/blob/main/bin/yaml/libraries.yaml#L1620

As for this repo, I'll show once I get around pushing the changes

**Comment by jll63** [comment]
Any idea when this will go through?

**Comment by jll63** [comment]
This seems to have stalled. No biggie, in the meantime the library has become header only. Also today I installed a local instance, tested my changes, and made the two PRs. As I should have done in the first place, sorry for being lazy.
