### ISSUE TITLE
[BUG] "6502-c++ 11.1.0" compiler doesn't work

### ISSUE THREAD

**Issue by shentino** [compiler-explorer/compiler-explorer#3833]
Triggering source code (I don't think this is relevant)

```C++
#include <iostream>

using namespace std;

class bad
{
    int x;
public:
    virtual ~bad();
};

class worse: public bad
{
    int y;
public:
    virtual ~worse();
};

bad::~bad()
{
    cout << "I am bad::~bad" << endl;
}

worse::~worse()
{
    cout << "I am worse::~worse" << endl;
}

int main(int argc, char *argv[], char *envp[])
{
    bad *thing = new worse;

    delete thing;
}
```

Error message:

```
--target is required
Run with --help for more information.
Compiler returned: 106
```

Evidence that this is a compiler-explorer issue:

The code compiles perfectly on the default compiler.  And the error message itself strongly suggests a glitch with compiler invocation.

**Comment by partouf** [comment]
This is a custom compiler (see https://github.com/lefticus/6502-cpp), not a normal one so you can't really compare.

If you follow the instructions you can see that you have to pass --target in order to set the target to C64 or to X16
```
 -t,--target ENUM:value in {C64->0,X16->1} OR {0,1} REQUIRED
                              6502 - based system to target
```

**Comment by shentino** [comment]
Should I forward the issue to lefticus or is this entirely user error on my part?

**Comment by partouf** [comment]
It is no error, it is expected behaviour for this compiler
