### ISSUE TITLE
[BUG]: LLVM opt pipeline view fails with Assertion error in llvm-print-after-all-parser

### ISSUE THREAD

**Issue by jrmuizel** [compiler-explorer/compiler-explorer#3839]
### Describe the bug

I get a `Assertion error in llvm-print-after-all-parser` when trying to use the LLVM opt pipeline view

### Steps to reproduce

Given
```c
int f(int n) {
    for (int i = 0; i < 8; i++) {
        n += i;
    }
    return n;
}
```
I get:
```
Assertion error in llvm-print-after-all-parser: IR Dump Before LoopDeletionPass on Parallel Loop at depth 1 containing: %4<header><latch><exiting>
```

### Expected behavior

It should compile.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
Thanks for the report! Can reproduce here https://godbolt.org/z/9Gs58YzT3, looks like it only happens with clang 13+.
