### ISSUE TITLE
[BUG]: Conformance view shows a error for MSVC when infact it is a success

### ISSUE THREAD

**Issue by MarekR22** [compiler-explorer/compiler-explorer#3841]
### Describe the bug

Conformance view displays red dot when in fact compilation is successful.

### Steps to reproduce

See this godbolt: https://godbolt.org/z/7zG98so7z

Note code is valid and simple.
gcc and clang shows green dot.
MSVC shows red dot.
Checking details of MSVC shows a success, no errors or warnings.

### Expected behavior

Conformance view for MSVC should reflect actual state of success or failure.

### Reproduction link

https://godbolt.org/z/7zG98so7z

### Screenshots

Not applicable

### Operating System

Windows 10

### Browser version

Firefox 102.

**Comment by partouf** [comment]
Thanks for the report, we already have an issue for it https://github.com/compiler-explorer/compiler-explorer/issues/3813
