### ISSUE TITLE
[BUG]: ast viewer truncates the output in some cases 

### ISSUE THREAD

**Issue by shafik** [compiler-explorer/compiler-explorer#3849]
### Describe the bug

Given the following example: https://godbolt.org/z/GKza5dvrh

The Ast Viewer truncates the output but if I use `-Xclang -ast-dump` directly I do see the whole AST dump. I show both cases in the link above

### Steps to reproduce

Plugging the following C++ code into compiler explorer:

```cpp
void f();

 char Bar(auto ) {
    return {};
}

int main() {
    char c = Bar([]{});
    return c;
}
```

The AST Viewer does not show the whole AST for this code.

### Expected behavior

Showing the AST similar to what I see when using `-Xclang -ast-dump` 

### Reproduction link

https://godbolt.org/z/GKza5dvrh

### Screenshots

Not applicable

**Comment by partouf** [comment]
Thanks for the example, this looks like something we should fix. Luckily we appear to have some unit testing for this so we can use this example to run on.
Maybe the user-code filtering makes some wrong assumptions about the output, but I'm not very familiar with the code behind the AST viewer.
