### ISSUE TITLE
[BUG]: Rust code does not compile even though it should

### ISSUE THREAD

**Issue by Pardoxa** [compiler-explorer/compiler-explorer#3853]
### Describe the bug

So, maybe I am missing something obvious, but this example code runs fine on the playground: https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=215479cf99c580603bb27282e871dfad
However it fails to compile in Compiler Explorer

### Steps to reproduce

1) Visit https://godbolt.org/
2) Change Language to Rust
3) Copy the code from the playground https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=215479cf99c580603bb27282e871dfad 
4) See Compiling error

### Expected behavior

Code should compile

### Reproduction link

https://godbolt.org/z/95Ecvce9T

### Screenshots

Not applicable

**Comment by partouf** [comment]
If you look at the advanced options in the playground you can see that it’s using edition 2021. So, if you pass ‘—edition=2021’ to the compiler arguments in Compiler Explorer it will also work

**Comment by Pardoxa** [comment]
Ah, I forgot about
