### ISSUE TITLE
[REQUEST]: Make "optimization-output" messages link to source

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#3856]
### Is your feature request related to a problem? Please describe

When using opt-viewer offline, the generated lines for optimization remarks contain clickable links to source lines (check eg [here](https://ofekshilon.github.io/optview2-cpython/._Include_internal_pycore_call.h.html#L43). This source location is a vital part of the optimization remark, essential to being able to interpret it.
Currently these links are dropped entirely in compiler explorer.  

### Describe the solution you'd like

-

### Describe alternatives you've considered

I suggest to either:
(1) Add the source line num to the message (probably easiest)
(2) Make the 'call'/'store'/'invoke' etc message word clickable, and have a click focus the line in the source editor
(3) To be in harmony with the rest of compiler explorer, perhaps the right thing to do is have a _hover_ above an optimization message with link, paint the linked source line with some colour?

I can probably submit a PR for (1) myself. (2) and (3) require more familiarity with the code.

### Additional context

Not applicable

**Comment by partouf** [comment]
It would probably be good to have an example to unittest (there are currently 0 unittests for opt!) and enrich the returning opt json.
And then we can figure out how to proceed further on what makes sense the most.

**Comment by OfekShilon** [comment]
> It would probably be good to have an example to unittest (there are currently 0 unittests for opt!) and enrich the returning opt json. And then we can figure out how to proceed further on what makes sense the most.

The opt code used to be an npm dependency on compiler-opt-info which was seemingly abandoned, and so the code was [brought inside](https://github.com/compiler-explorer/compiler-explorer/commit/29b6e4a462bf276c5352631338203c16aa5c8744).  The original compiler-opt-info did have [some tests](https://github.com/jaredwy/compiler-opt-info/tree/master/test), I can at least migrate them as-are into compiler-explorer and make sure that the json contains the debug info from the yamls. Hopefully next week.

**Comment by jaredwy** [comment]
Not abandoned. Just hasn't needed to be touched until now :)

I have been meaning to get to improving opt but unfortunately my health took a turn, so happy to lend a hand where needed :)

**Comment by RubenRBS** [comment]
All my best wishes to you @jaredwy, hoping you get better :)

**Comment by jaredwy** [comment]
I use it in another project, so thats why it's a seperate repo so I can consume it in npm. It also has utility outside of CE so Would be good if we make changes that we also update that project.

**Comment by OfekShilon** [comment]
Jared, glad to see you're online and feel well always!
 There's an open issue and PR at your repo for a previous fix, for ~6mon
now (currently at an airport line, navigation is cumbersome). Please
consider accepting.

Also, please consider granting at least one other person push permissions
to your repo, to not have it depend on the responsivity of a single person.

בתאריך יום א׳, 10 ביולי 2022, 23:39, מאת Jared Wyles ‏<
***@***.***>:

**Comment by OfekShilon** [comment]
@jaredwy  this is the bug that was left hanging: https://github.com/jaredwy/compiler-opt-info/issues/1

Initially I formed an npm package 'compiler-opt-info2' with the fix and made a CE PR to move to it, but following the discussion on the CE bug changed it to internal CE code:

**Comment by OfekShilon** [comment]
@partouf Seems the json data already contains the line/column in the `DebugLoc` subelement of `Args`.  Snippet from raw yaml file:
```
--- !Missed
Pass:            gvn
Name:            LoadClobbered
DebugLoc:        { File: 'src/timer.c', Line: 59, Column: 3 }
Function:        uv_timer_init
Args:
  - String:          'load of type '
  - Type:            '[2 x i8*]*'
  - String:          ' not eliminated'
  - String:          ' because it is clobbered by '
  - ClobberedBy:     store
    DebugLoc:        { File: 'src/timer.c', Line: 59, Column: 3 }     <==========
```
This reflects in the CE source as:
```js
interface LLVMOptInfo extends OptInfo {
    Pass: string;
    Name: string;
    DebugLoc: DebugLoc;
    Function: string;
    Args: Array<object>;
}
```
The current code for generating the tooltip [explicitly filters out DebugLoc](https://github.com/OfekShilon/compiler-explorer/blob/6227760907b071d210f27a233d09e59a96eda777/lib/llvm-opt-transformer.ts#L28):

```js
function DisplayOptInfo(optInfo: LLVMOptInfo) {
    return optInfo.Args.reduce((acc, x) => {
        return (
            acc + R.pipe(R.partial(R.pickBy, [(v: any, k: string) => k !== 'DebugLoc']), R.toPairs, R.head, R.last)(x)
        );
    }, '');
}
```
So `LLVMOptInfo.Args` already has `DebugLoc` elements (0, 1 or more)  that are a `{ File, Line, Column} ` object. I can submit a PR that adds line/col text to the tooltip, but nothing more ambitious like linking to other panes. Do you think that's doable?

**Comment by partouf** [comment]
Thanks for figuring this out, I had no idea. Should be doable then I think. I can add source/editor linking at a later time, we have some code for that but it's all over the place and needs some refactoring.

**Comment by OfekShilon** [comment]
@partouf  I just submitted #3908. It's not the full fix, but hey - it's a step forward..

**Comment by OfekShilon** [comment]
@partouf  thanks for pulling!  Do you know when will it be deployed?

**Comment by partouf** [comment]
deploying now, will be finished in about >30 minutes

**Comment by OfekShilon** [comment]
Closing the issue as it didn't receive any attention in 0.5Y and the existing solution seems good enough.

**Comment by RubenRBS** [comment]
Oh I didn't know 2 and 3 were suggested, they definetely look like good ideas but we're short on bandwith to tackle it atm :/
