### ISSUE TITLE
[BUG]: "gword ptr" 

### ISSUE THREAD

**Issue by bookh22** [compiler-explorer/compiler-explorer#3859]
### Describe the bug

Assembly output is partially wrong. The "gword ptr" is likely a spelling mistake.

As seen from line 12 and line 14:
```
       mov      gword ptr [rbp-10H], rax
       mov      edi, dword ptr [rbp-04H]
       mov      rsi, gword ptr [rbp-10H]
```

### Steps to reproduce

1. Visit https://godbolt.org/
2. Choose Visual Basic
3. Type the following code:

```
Module Program
    Function Square(num As Integer) As Integer
        Return num * num
    End Function

    sub Main()
        Print (Square(8))
    end sub
End Module
```

### Expected behavior

The "gword ptr" should be "qword ptr" instead.

### Reproduction link

https://godbolt.org/z/hcvsPsrKK

### Screenshots

![screenshot](https://pictr.com/images/2022/07/09/BqBXk2.png)

### Operating System

Windows 11 21H2

### Browser version

Google Chrome Version 103.0.5060.114 (Official Build) (64-bit)

**Comment by dkm** [comment]
If you're correct, then it's a bug in the compiler, not compiler explorer. There's nothing we can do about that...

**Comment by partouf** [comment]
It's not a bug, they have several references to gword in their code and they have a couple of other weird ones https://github.com/dotnet/runtime/blob/11f24dd3b68da68dbbbd222dac98768f6893f30c/src/coreclr/jit/instr.cpp#L199
It seems to be a EA_GCREF, whatever that means

**Comment by bookh22** [comment]
Oh, I didn't know that. Thanks for the informative reply!
