### ISSUE TITLE
Pony Lang LLVM IR Output

### ISSUE THREAD

**Issue by RossSmyth** [compiler-explorer/compiler-explorer#3864]
While putting together #3855 I tried to get LLVM IR to output, but this method fails
https://github.com/compiler-explorer/compiler-explorer/blob/a5c45b6f0b7d8c0f85198f1142c480a477e09420/lib/base-compiler.ts#L961-L972
With the alternate internal error. 

I left all the logic for getting IR to output though. Ponyc will output LLVM IR if you give it the flag `--pass ir` which is commented out here:
https://github.com/compiler-explorer/compiler-explorer/blob/a5c45b6f0b7d8c0f85198f1142c480a477e09420/lib/compilers/pony.ts#L37-L42

But ponyc can only output a single artifact for any run of the compiler, and which is output depends on the order of the arguments. So if you have `-pass asm` after the `--pass ir` flag, then asm will be output, so I made sure to remove that flag to be safe.
https://github.com/compiler-explorer/compiler-explorer/blob/a5c45b6f0b7d8c0f85198f1142c480a477e09420/lib/compilers/pony.ts#L64

**Comment by OfekShilon** [comment]
@RossSmyth while I'm here: is the `-d` option here intentional?  https://github.com/compiler-explorer/compiler-explorer/blob/a5c45b6f0b7d8c0f85198f1142c480a477e09420/lib/compilers/pony.ts#L45

I'd think you'd want to have optimization options specified on the command line for each compilation. No?

**Comment by OfekShilon** [comment]
@RossSmyth  Actually, I'd appreciate if you could take a look at PR #5977 and verify it makes sense. (I've never heard of pony before this..)

**Comment by RossSmyth** [comment]
@RossSmyth while I'm here: is the `-d` option here intentional?
> 
> https://github.com/compiler-explorer/compiler-explorer/blob/a5c45b6f0b7d8c0f85198f1142c480a477e09420/lib/compilers/pony.ts#L45
> 
> I'd think you'd want to have optimization options specified on the command line for each compilation. No?

hmmm good question. I can't remember. It'd probably be a good idea to remove it.

Maybe I thought that outputting optimized code by default would be confusing? Especially because ponyc is setup opposite of most compilers where it outputs optimized by default.

**Comment by RossSmyth** [comment]
If you do I would put it in a separate PR because there may have been a reason like something with mangling or debug info that would make it hard to use.

**Comment by OfekShilon** [comment]
@RossSmyth do pony compilations default to non-optimized, like C/C++?  If so, not forcing `-d` is definitely the right thing to do.  It is a very typical usage of CE to diff optimized vs non-optimized build results, we wouldn't want to ban either.

**Comment by RossSmyth** [comment]
Yes I do that often. Pony defaults to optimized. You pass `-d` to get a debug build.

**Comment by OfekShilon** [comment]
Is there some counter-switch to disable `-d`? I'm guessing not, so we better remote the forced `-d` to enable comparisons.

**Comment by RossSmyth** [comment]
No there is not a flag for optimized builds. So currently there is no way for CE to view them.
