### ISSUE TITLE
[BUG]: java: command not found kotlin-jvm-1.7.0

### ISSUE THREAD

**Issue by yeikel** [compiler-explorer/compiler-explorer#3869]
### Describe the bug

Running 

/opt/compiler-explorer/kotlin-jvm-1.7.0/bin/kotlinc: line 98: java: command not found
Compiler returned: 127

### Steps to reproduce

1. Visit https://godbolt.org/
2. Select kotlin 1.7.0
3. Try to compile

### Expected behavior

It compiles

### Reproduction link

https://godbolt.org/z/cPx1j4TMW

### Screenshots

![image](https://user-images.githubusercontent.com/8935151/178596738-06b77da3-422e-4130-b0b8-429c9080cc7e.png)

**Comment by partouf** [comment]
Thanks for the bugreport, we had accidentally linked it to a non-existing java version. I have made a temporary solution, until fully fixed it will be a bit more slower than usual.
