### ISSUE TITLE
[REQUEST]: Persist current page state on a per browser window/tab basis

### ISSUE THREAD

**Issue by tahonermann** [compiler-explorer/compiler-explorer#3870]
### Is your feature request related to a problem? Please describe

It is common for me to have multiple Compiler Explorer (godbolt.org) browser (Firefox) windows/tabs open for an extended period of time (days, weeks) while working on various problems. When a browser restart is required (e.g., due to a need to reboot the laptop or restart the browser for updates), open windows/tabs are restored but since only one page state is preserved (as a persistent cookie), all restored windows/tabs end up with matching restored state; they each get the state corresponding to whichever window/tab last persisted its current page state. This results in the loss of code, selected compilers, pane layout, etc... for all windows/tabs except one.

### Describe the solution you'd like

I'd like for Compiler Explorer (godbolt.org) to, somehow, persist the current page state separately for each window/tab; at least across browser restarts. I know next to nothing about cookies, sessions, or browser internals, so I have no idea what kinds of technical challenges this request poses, what technical solutions are available, or what the consequences might be.

### Describe alternatives you've considered

Never ever having to restart my computer or browser, but various evil forces keep interfering.

It seems that per-session state might be preserved if one first copies a short/full link corresponding to current page state? That is hard to remember to do after every change though (and any change seems to effectively redirect to the "common" session).

### Additional context

Not applicable

**Comment by RubenRBS** [comment]
Hi! Thanks for taking the time to explain this feature. While there might be better ways to do it, I've implemented one in the linked PR. It will take a bit until we can get around to merge it though, as I'm a bit short on time this next few weeks

**Comment by tahonermann** [comment]
Wow! That was fast! Thanks for taking a look already!

**Comment by tahonermann** [comment]
Thank you for doing this! Looking at the change made, it appears this is an opt-in feature for now. To enable, (after reloading), Select More -> Settings, select the "Site behaviour" tab, check the "Keep page status per tab" option, and then click Close.
