### ISSUE TITLE
[REQUEST]: documentation tooltips in LLVM IR displays

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#3872]
### Is your feature request related to a problem? Please describe

LLVM Optimization Pass Viewer is unbelievable!! Major, major kudos to @jeremy-rifkin. Now I have the audacity to ask for even more:

I don't know how you guys do the magic of assembly tooltips, but maybe you can wave your wand and have it apply to LLVM-IR and LLVM-Optimization-Pass-Viewer panes? I mean, upon hover in IR panes display the relevant snippet from the [LangRef](https://llvm.org/docs/LangRef.html)?

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Additional context

Not applicable

**Comment by jeremy-rifkin** [comment]
Thanks @OfekShilon :)
This is definitely doable, I think @matsjla already did a lot of the hard work for this in #3737, I'll take a look at what all would be required to implement the tooltips in the panes later!

**Comment by OfekShilon** [comment]
> Thanks @OfekShilon :) This is definitely doable, I think @matsjla already did a lot of the hard work for this in #3737, I'll take a look at what all would be required to implement the tooltips in the panes later!

The only way I'm able to enjoy @matsjla great work is if I explicitly add the switch `-emit-llvm` so IR appears in the assembly pane. Am I missing something?

Also, not sure how the LangRef crawler was implemented - but it seems to have collected only instructions. Attributes are (arguably) even more important and less self-evident. Would it be possible to extend the data?

**Comment by OfekShilon** [comment]
Indeed I see [only IR instructions are collected](https://github.com/compiler-explorer/compiler-explorer/pull/3737/commits/88210197dc5a79087fcf150d34947193f1609151#diff-aaf2994290c9d28d78d80382881deb2af287a97cf13169f806fe748599abc3a4R14).  This is great - but hopefully it can be made incredible :)

**Comment by jeremy-rifkin** [comment]
There's a lot I'd like to improve with our LLVM tooling, including better filtering, better metadata handling, and control flow graphs just to name a few (I'm also working on improving our CFG tool itself). If you have other ideas for improving our LLVM tooling I'd be all ears!

**Comment by OfekShilon** [comment]
> There's a lot I'd like to improve with our LLVM tooling, including better filtering, better metadata handling, and control flow graphs just to name a few (I'm also working on improving our CFG tool itself). If you have other ideas for improving our LLVM tooling I'd be all ears!

As you can see I'm not shy about requests :)   But now that you mention it, I would very much appreciate enhancements at the Opt Viewer pane:

1. Filtering of remarks. The easiest such filter is 'missed only' which could be a checkbox.

2. Display index of remarks. Code snippets can be large, and I'm often forced to scroll extensively to know if there were any remarks and where.

**Comment by matsjla** [comment]
> maybe you can wave your wand and have it apply to LLVM-IR and LLVM-Optimization-Pass-Viewer panes? I mean, upon hover in IR panes display the relevant snippet from the [LangRef](https://llvm.org/docs/LangRef.html)?

This is a bit tricky...

Assembly documentation tooltips are added to the output panes based on the Monaco Editor language type of the editor the output code is in.

It's therefore not really realistic to have it be enabled with -emit-llvm flag detection :( - I hope to maybe make it possible for individual compilations to specify their output language type, but until then there's only questionable bandaid fixes that could work.

If you really wanted to, you could open a new LLVM IR editor with the code and see the assembly docs in there https://godbolt.org/z/7sb9bMnMv

**Comment by OfekShilon** [comment]
> If you really wanted to, you could open a new LLVM IR editor with the code and see the assembly docs in there https://godbolt.org/z/7sb9bMnMv

As mentioned, `-emit-llvm` dumps IR to the assembly window which _does_ display IR tooltips.  The LLVM IR source editor at your link doesn't display instruction tooltips for me...  Did you mean to paste IR in LLVM-IR-source, add an `opt` compiler and watch the tooltips there?  That's doable, but carries a few extra manual steps w.r.t `-emit-llvm`. 

Anyway - hopefully this can be improved, but isn't urgent. Do you think it's possible to extend your (great!) LangRef crawler to collect attribute reference too? The attributes vocabulary is vast, and unlike instructions - not so self-explanatory.

**Comment by OfekShilon** [comment]
Partially addressed in #6937
