### ISSUE TITLE
Unable to remove LLVM IR from dropdown

### ISSUE THREAD

**Issue by vinoski** [compiler-explorer/compiler-explorer#3873]
For a compiler that doesn't support or doesn't want to support LLVM IR, it would be nice to be able to remove it from the "Add new element for this compiler" dropdown menu. But it's currently not possible, because this line of code:

    this.irButton.toggle(!!this.compiler.supportsIrView);

is missing from after [this line of compiler.js code](https://github.com/compiler-explorer/compiler-explorer/blob/c934dede0a735d038314a4602b0fdb1022e7c89b/static/panes/compiler.js#L2193).

**Comment by partouf** [comment]
the llvm things are based on supported compiler arguments, so are you saying you have a compiler that has those specific arguments, but can't actually produce it?

**Comment by jeremy-rifkin** [comment]
Oops it used to be there! I'll fix it shortly.

**Comment by vinoski** [comment]
Thanks! I tried setting `this.compiler.supportsIrView = false` in my compiler constructor, but that didn't work, and only by adding the suggested line was I able to get it working.

**Comment by jeremy-rifkin** [comment]
Was my mistake here https://github.com/compiler-explorer/compiler-explorer/commit/ed1a4e6b2794e096ecf049a64ed4944733f81b94#diff-e6ef2b234b8da2cad706ea8b722d6d625bfe61e7fa00d3bcea305c2ce3e1889fL2145

**Comment by jeremy-rifkin** [comment]
4295077, will be fixed next time we deploy
