### ISSUE TITLE
[BUG]: Out of Bounds Read

### ISSUE THREAD

**Issue by thewb** [compiler-explorer/compiler-explorer#3879]
### Describe the bug

I wrote some wonky c++ in compiler explorer and the program output has environment variables and possibly arbitrary memory.

<img width="719" alt="Screen Shot 2022-07-16 at 3 10 03 PM" src="https://user-images.githubusercontent.com/10623888/179373438-7871dfb6-d1ee-4ea8-8b3b-79d9af86112a.png">
 

### Steps to reproduce

1. select the x86-64 clang 3.6 compiler
2. enter the following c++

~~~c++ 
#include <iostream>
int main(void){
    char * first;
    char * last;
    for (; first != last; ++first) {
        std::cout << *first;
    }
}
~~~

3. keep pressing enter, the size of the source file seems to relate to how many bytes are read. You will eventually get things like:

~~~
Mobx86_64./output.sLD_LIBRARY_PATH=/opt/compiler-explorer/clang+llvm-3.6.2-x86_64-linux-gnu-ubuntu-14.04/lib:/opt/compiler-explorer/clang+llvm-3.6.2-x86_64-linux-gnu-ubuntu-14.04/lib32:/opt/compiler-explorer/clang+llvm-3.6.2-x86_64-linux-gnu-ubuntu-14.04/lib64ASAN_OPTIONS=color=alwaysUBSAN_OPTIONS=color=alwaysMSAN_OPTIONS=color=alwaysLSAN_OPTIONS=color=alwaysASAN_SYMBOLIZER_PATH=/opt/compiler-explorer/clang+llvm-3.6.2-x86_64-linux-gnu-ubuntu-14.04/bin/llvm-symbolizerHOME=/app./output.s
~~~

### Expected behavior

I don't think that I expected to read environment variables and random memory.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment]
Compiler Explorer runs in a sandbox - you'll see whatever memory is around in the process, which includes the environment and anything else fired up inside the sandbox. It's easier to see the environment variables with the `char **envp` third parameter to `main(int argv const char *argv[], char **envp) {...}`.

I don't believe anything is being leaked here that you didn't upload yourself, or isn't already visible in the environment your program runs in.

Do you think there's anything specifically worryingly leaked here?

(For what it's worth the sandbox is `nsjail`, and the env it runs in is very carefully controlled and limited)

**Comment by thewb** [comment]
I get it's sandboxed and all, just thought you might want to know about the behaviour. Cheers.

**Comment by mattgodbolt** [comment]
Thanks! It's expected behaviour :+1: :)
