### ISSUE TITLE
[BUG]: <Compilation failed: (intermediate value).bind is not a function> with GCC Tree/RTL pane

### ISSUE THREAD

**Issue by amonakov** [compiler-explorer/compiler-explorer#3886]
### Describe the bug

Attempt to open GCC Tree/RTL dump pane results in
```
<Compilation failed: (intermediate value).bind is not a function>
```
message in the compiler output (assembly) pane. This appears to be a very recent regression.

### Steps to reproduce

1. Visit godbolt.org
2. Select "More > Reset code and UI layout"
3. In output pane, select "Add more > GCC Tree/RTL"

### Expected behavior

Compilation should succeed and Tree/RTL dumps be available for inspection.

### Reproduction link

https://godbolt.org/z/b194hfv1q

### Screenshots

Not applicable

**Comment by dkm** [comment]
yikes, something is broken, thanks for the report!

**Comment by partouf** [comment]
fix is now live
