### ISSUE TITLE
[LIB REQUEST] Eigen in Carbon

### ISSUE THREAD

**Issue by jjcasmar** [compiler-explorer/compiler-explorer#3892]
I wanted to test some of this new Carbon stuff and well it behaves using a complex templated C++ library like Eigen. There are no support for it though in [carbon.compiler](https://carbon.compiler-explorer.com/). 

Since Carbon supports C++, would it be possible to enable the C++ libraries that compiler-explorer supports?

**Comment by matsjla** [comment]
The current Carbon explorer (not CE) doesn't implement all proposals yet, and the actual compiler is probably not going to be here for a few years.

I'm not sure if the amount of work to support libraries for Carbon is worth it considering it will probably break as explorer and the new Crbon compilers evolve

If you want to give implementing it a shot I'm sure we could point you in the general direction though

**Comment by jjcasmar** [comment]
Make sense. 

Sorry, I dont think I can find time to implement libraries support for Carbon Explorer. 
I just wanted to play with a new toy!
