### ISSUE TITLE
[COMPILER REQUEST]: TemplateSpecialization Resugaring Clang

### ISSUE THREAD

**Issue by mizvekov** [compiler-explorer/compiler-explorer#3903]
### Compiler name

LLVM Clang TemplateSpecialization Resugaring (D127695)

### Compiler version

15.0.0-git

### Compiler language

C, C++

### Compiler homepage

https://github.com/mizvekov/llvm-project/tree/D127695

### Motivation

Hello.

I have been working on a LLVM project to improve Clang's preservation of type sugar.

This is a work in progress deal which I intend to demo in the near future.

I have a branch on my personal LLVM fork, which is also available on [D127695](https://reviews.llvm.org/D127695)

Is it possible to add this as one of the Clang flavors available in CE?

Thanks!

**Comment by matsjla** [comment]
Hey there, this sounds very cool. If you have time to do some of the work that'd be great. The steps for adding a clang fork are:

1. Add a build script in clang-builder https://github.com/compiler-explorer/clang-builder/blob/main/build/build.sh#L55
2. Get it added to the infra https://github.com/compiler-explorer/infra/blob/main/bin/yaml/cpp.yaml#L652
3. Add a configuration in the CE properties https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/c%2B%2B.amazon.properties

You can look at the old PRs for Widberg Clang (or any of the other nightly experimental clangs) for more details on how to get through the different steps

**Comment by mizvekov** [comment]
Thanks!

Added:
https://github.com/compiler-explorer/clang-builder/pull/38
https://github.com/compiler-explorer/infra/pull/770
https://github.com/compiler-explorer/compiler-explorer/pull/3905

**Comment by partouf** [comment]
now live
