### ISSUE TITLE
[BUG]: Abseil fails to link, unable to find -labsl_leak_check_disable

### ISSUE THREAD

**Issue by asoffer** [compiler-explorer/compiler-explorer#3909]
### Describe the bug

Including absl/strings/str_cat.h with "execution only" will not run due to this linker error with clang trunk or gcc trunk

### Steps to reproduce

https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:13,endLineNumber:3,positionColumn:13,positionLineNumber:3,selectionStartColumn:13,selectionStartLineNumber:3,startColumn:13,startLineNumber:3),source:'%23include+%22absl/strings/str_cat.h%22%0A%0Aint+main()+%7B%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:executor,i:(argsPanelShown:'1',compilationPanelShown:'0',compiler:clang_trunk,compilerOutShown:'0',execArgs:'',execStdin:'',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!((name:abseil,ver:trunk)),options:'',source:1,stdinPanelShown:'1',tree:'1',wrap:'1'),l:'5',n:'0',o:'Executor+x86-64+clang+(trunk)+(C%2B%2B,+Editor+%231)',t:'0')),header:(),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

### Expected behavior

Correct program execution (no output, returns 0).

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by partouf** [comment]
fix is now live
