### ISSUE TITLE
[LIB REQUEST]: Rayon (Rust)

### ISSUE THREAD

**Issue by mrauhu** [compiler-explorer/compiler-explorer#3927]
### Library name

Rayon

### Library description

Rayon: A data parallelism library for Rust

### Library repository

https://github.com/rayon-rs/rayon

### Motivation

It's like the OpenMP for Rust.

```rs
use rayon::prelude::*;

fn sum_of_squares(input: &[i32]) -> i32 {
    input.par_iter()
         .map(|&i| i * i)
         .sum()
}
```

**Comment by RubenRBS** [comment]
Hi! Sorry that this took so long to get adressed. We're now looking into adding the missing libraries to Rust :)

**Comment by partouf** [comment]
This is now live https://godbolt.org/z/hh1nW7zW4
