### ISSUE TITLE
[REQUEST]: Add llvm-dwarfdump as a tool.

### ISSUE THREAD

**Issue by ZequanWu** [compiler-explorer/compiler-explorer#3940]
### Is your feature request related to a problem? Please describe

I would like be able to look at dwarf debug info.

### Describe the solution you'd like

Add llvm-dwarfdump as a tool under tool tab.

### Describe alternatives you've considered

dwarfdump.

### Additional context

Not applicable

**Comment by dwblaikie** [comment]
+1

**Comment by DavidSpickett** [comment]
This was done by https://github.com/compiler-explorer/compiler-explorer/pull/5726.

**Comment by dwblaikie** [comment]
Hmm - I'm not exactly sure how to /use/ this, sorry - bit of a naive question. But when I greate a "compilation only" it says "llvm-dwarfdump (trunk) requires an executable or binary object" - but when I choose "execution" I can't find the "tools" menu to apply llvm-dwarfdump to it?

**Comment by partouf** [comment]
The "requires an executable or binary object" warning is always about the "Link to binary" option

**Comment by dwblaikie** [comment]
Ah, thanks!
