### ISSUE TITLE
ARM assembly annotations

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#395]
When/if we get to doing this: https://twitter.com/maver/status/854995391753965568 will be handy.

**Comment by mattgodbolt** [comment]
https://developer.arm.com/products/architecture/a-profile/exploration-tools

**Comment by partouf** [comment]
I'm guessing this can be closed (tweet is unavailable, but I see that the ASM documentation changes mentioned this issue)
