### ISSUE TITLE
[BUG]: User defined literals can not be compiled

### ISSUE THREAD

**Issue by PhamLeHai** [compiler-explorer/compiler-explorer#3963]
### Describe the bug

Code using user-defined literals can not be parsed and compiled normally.

### Steps to reproduce

Example code:
```C++
#include <iostream>

struct KM {
    int value;
};

KM operator "" _km(const char * p) {
    return KM {std::atoi(p)};
};

KM operator "" _km(long double v) {
    return KM {(int)v};
};

int main() {
    auto t = 12_km;
    std::cout << t.value << std::endl;
}

```

### Expected behavior

It should print out `12` to the console.

### Reproduction link

https://godbolt.org/z/96ExnTn69

### Screenshots

Not applicable

**Comment by partouf** [comment]
Suspect this is a bug in https://github.com/compiler-explorer/asm-parser/blob/main/src/utils/jsonwriter.cpp , possibly a json keyname that is not escaped where it should have been. Should be testable.

**Comment by partouf** [comment]
fix is now live
