### ISSUE TITLE
[COMPILER REQUEST]: GCC 12.2 native & cross

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#3973]
### Compiler name

gcc

### Compiler version

12.2

### Compiler language

all of them

### Compiler homepage

https://sourceware.org/pub/gcc/releases/gcc-12.2.0/

### Motivation

:)

**Comment by dkm** [comment]
Native build: https://github.com/compiler-explorer/infra/actions/runs/2888347105

**Comment by dkm** [comment]
Cross compiler must wait for https://github.com/crosstool-ng/crosstool-ng/pull/1806 .

**Comment by dkm** [comment]
Will list errors causing some lang/target being disabled.

Can't enable Ada on mips64el:
```
[ERROR]    i-cexten.ads:277:28: error: modulus exceeds limit (2 ** 64)                                    
[ERROR]    i-cexten.ads:280:28: error: modulus exceeds limit (2 ** 64)            
[ERROR]    i-cexten.ads:283:28: error: modulus exceeds limit (2 ** 64)                                                                                                                                              
[ERROR]    i-cexten.ads:286:28: error: modulus exceeds limit (2 ** 64)                                    
[ERROR]    i-cexten.ads:289:28: error: modulus exceeds limit (2 ** 64)     
```
Same for D:
```
crosstool-ng/.build/src/gcc-12.2.0/libphobos/src/std/stdio.d:247:28: error: undefined identifier 'fputc_unlocked'       
....
```

**Comment by dkm** [comment]
> ### mips64el
> ### D:
> 
> ```
> crosstool-ng/.build/src/gcc-12.2.0/libphobos/src/std/stdio.d:247:28: error: undefined identifier 'fputc_unlocked'       
> …
> ```

@ibuclaw here's the error for mips64el.

The build confg/scripts:
 - [build.sh](https://github.com/compiler-explorer/gcc-cross-builder/blob/main/build/build.sh)
 - the corresponding [ct-ng conf](https://github.com/compiler-explorer/gcc-cross-builder/blob/main/build/latest/mips64el-12.2.0.config)
 
To reproduce, you need to use ct-ng, copy the config in `.config` and then enable D in the config (`ct-ng menuconfig` ...).
You can also use our docker image: https://github.com/compiler-explorer/gcc-cross-builder (let me know if you need help with that, if you want to go that way) if you don't want to deal with ct-ng build/deps.

**Comment by ibuclaw** [comment]
> > ### mips64el
> > ### D:
> > ```
> > crosstool-ng/.build/src/gcc-12.2.0/libphobos/src/std/stdio.d:247:28: error: undefined identifier 'fputc_unlocked'       
> > …
> > ```
> 
> @ibuclaw here's the error for mips64el.
> 

@dkm thanks! Looks like not a mip64el problem, rather a blind spot in the uClibc bindings.

Raised upstream issue for this particular error: https://issues.dlang.org/show_bug.cgi?id=23344

There still are, however, a number of uClibc bindings that are mips32-only.  Will need to add what's missing in upstream too before compilation will succeed.

**Comment by ibuclaw** [comment]
> > ### mips64el
> > ### D:
> > ```
> > crosstool-ng/.build/src/gcc-12.2.0/libphobos/src/std/stdio.d:247:28: error: undefined identifier 'fputc_unlocked'       
> > …
> > ```
> 
> @ibuclaw here's the error for mips64el.
> 

@dkm thanks! Looks like not a mip64el problem, rather a blind spot in the uClibc bindings.

Raised upstream issue for this particular error: https://issues.dlang.org/show_bug.cgi?id=23344

There still are, however, a number of uClibc bindings that are mips32-only.  Will need to add what's missing in upstream too before compilation will succeed.

**Comment by dkm** [comment]
Thanks @ibuclaw for looking into that! I wonder if my previous issues with ARM target were related/similar. It was also at link time but for others symbols. I don't have exact error, but can surely reproduce when I'm back, if you think it's worth investigating (missing symbol for some tls function when enabling "static toolchain" in ct-ng).

**Comment by ibuclaw** [comment]
Could be if it uses uClibc as well.  Looks like bindings are rather incomplete for that runtime.
