### ISSUE TITLE
[BUG]: clang for powerpc64le misidentified as gcc in compiler list

### ISSUE THREAD

**Issue by programmerjake** [compiler-explorer/compiler-explorer#3983]
### Describe the bug

clang for powerpc64le is misidentified as gcc in the compiler list

the `https://gcc.godbolt.org/client-options.js?hash=...` API returns (trimmed & formatted):
```json
{
    "id": "ppc64leclang",
    "name": "power64le gcc (snapshot)",
}
```

### Steps to reproduce

open the reproduction link.

observe compiler id in output assembly is clang despite being labeled in list as gcc:
```
.ident  "clang version 16.0.0 (https://github.com/llvm/llvm-project.git 7d273fde110d7735512c3b71a83eb88e89d189cc)"
```

### Expected behavior

clang should be named clang in the list of compilers.

### Reproduction link

https://gcc.godbolt.org/z/soMY9PMdd

### Screenshots

Not applicable

**Comment by RubenRBS** [comment]
Oh, probably my fault. Will fix this as soon as I can

**Comment by mattgodbolt** [comment]
This fix is now live: thanks!
