### ISSUE TITLE
[COMPILER REQUEST]: Google  clspv

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#3992]
### Compiler name

 clspv

### Compiler version

main branch

### Compiler language

OpenCL-C to Vulkan

### Compiler homepage

https://github.com/Google/clspv

### Motivation

Mentioned as something that would be helpful.
@rjodinchr please add anything that you thing would be helpful here.
We can build the compiler with our nightly jobs if you don't provide any binary release. Then, we need to know how to call it (input, output), what's expected (assembly ? binary ?).

**Comment by rjodinchr** [comment]
Thanks for the issue @dkm,

To be more accurate, the compiler language is: OpenCL-C to Vulkan SPIR-V

To build `clspv` you just need to fetch the dependencies (llvm, and some SPIR-V repositories), using `python3 <clspv>/utils/fetch_sources.py`.
Then it is just a typical cmake.
The default target will build `clspv`.
You will also need to run the target `spirv-dis`, which is the disassembler that will be used to generate a readable output.

To use it, let's start simple with: `clspv <input> -o <output>`. And then: `spirv-dis <output> -o <readable_output>`.
`clspv` should be located here: `<build>/bin`, and `spirv-dis` here: `<build>/third_party/SPIRV-Tools/tools/`

Thanks again

**Comment by partouf** [comment]
Currently building (original buildscript didn't work anymore) https://github.com/compiler-explorer/infra/runs/8254617898?check_suite_focus=true

**Comment by rjodinchr** [comment]
https://github.com/compiler-explorer/misc-builder/pull/45
the default branch is now main

**Comment by partouf** [comment]
> Currently building (original buildscript didn't work anymore) https://github.com/compiler-explorer/infra/runs/8254617898?check_suite_focus=true

seems to be compiling, but it needs some extra changes to upload the tar to our S3

**Comment by partouf** [comment]
this is the tar we produce, can someone check if its built correctly? https://compiler-explorer.s3.amazonaws.com/opt/clspv-main-20220908.tar.xz

**Comment by rjodinchr** [comment]
I have tested it, it looks good, thanks

**Comment by rjodinchr** [comment]
I am not sure what are the next steps now.
Once clspv is installed in the amazon instance, we should be able to merge #4014, right?

@dkm mentioned the nightly builder to make sure that clspv is always up-to-date, but I guess with `build-clspv.sh` there is not many things left to do here either?

**Comment by partouf** [comment]
We need some install things, and then test it all together. I'm a bit busy this weekend, but maybe next week I'll have time, unless someone else picks it up.

**Comment by rjodinchr** [comment]
Thank you everyone for the support!
This issue can now be closed, `clspv` is available and works as expected 🙂
Thanks again
