### ISSUE TITLE
[BUG]: LLVM Opt Pipeline Viewer fails with -stdlib=libc++

### ISSUE THREAD

**Issue by gonzalobg** [compiler-explorer/compiler-explorer#4007]
### Describe the bug

When using LLVM Opt Pipeline Viewer with `x86_64 clang (trunk)`, the passes are correctly shown without passing the `-stdlib=libc++` option to clang, but when this option is passed, then it return: `<Error>` and no output is shown.

When using x86_64 clang 14.0 then it works. And when not using the -stdlib=libc++ option with clang trunk, then it also works.

@jeremy-rifkin 

### Steps to reproduce

https://godbolt.org/z/nsdbqaYEf

### Expected behavior

The Opt passes should be shown.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
How odd, thank you for the report

**Comment by jeremy-rifkin** [comment]
Locally the issue is that the invocation of clang with `-mllvm --print-before-all -mllvm --print-after-all` is actually timing out. I will try to get some better diagnostics to the front end about this.

**Comment by jeremy-rifkin** [comment]
It does not take much to get things to time out (especially when dumping the full module, though that isn't the case here).

Running `clang++ test.cpp -g -o output.s ... -O3 -std=c++20 -stdlib=libc++ -mllvm --print-before-all -mllvm --print-after-all > /dev/null 2>&1` alone on this input takes 18 seconds. The generated pass dump output is 1.6 million lines and 180 MB. It is possible it could make sense to port https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/parsers/llvm-pass-dump-parser.ts to C++ but even with that the time taken to execute clang alone is quite large.

If any llvm wizards happen to read this and have insight into better ways to do this, I'd be very interested

**Comment by gonzalobg** [comment]
> Locally the issue is that the invocation of clang with -mllvm --print-before-all -mllvm --print-after-all is actually timing out (85 seconds). I will try to get some better diagnostics to the front end about this.

Oh! Thank you for tracking this down! I did not realize this.

Just getting some better diagnostics sounds good to me!
