### ISSUE TITLE
[REQUEST]: Add ZX emulation

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#4008]
I'm investigating on how to add https://github.com/gasman/jsspeccy3 to CE to run binaries built with z88dk

(As mentioned here https://github.com/compiler-explorer/compiler-explorer/pull/3812)

**Comment by partouf** [comment]
The current problem that I'm facing is that it uses workers, so I can't put the release as suggested here https://github.com/gasman/jsspeccy3#embedding on our CDN and test it.

Which means I'll have to either
* add it to our codebase
* or fork it and create a npm package out of it and use that
* or fork it and create a website out of it to put in an iframe

Either way, I think we'll have to add some functions to it to allow direct binary loading instead of getting it from an URL.

**Comment by partouf** [comment]
It seems that there's already an official package https://www.npmjs.com/package/jsspeccy

**Comment by partouf** [comment]
> It seems that there's already an official package https://www.npmjs.com/package/jsspeccy

I actually don't know how to use it...

**Comment by mattgodbolt** [comment]
Silly aside: jsspeccy formed the OG basis for https://github.com/mattgodbolt/miracle 's z80 emulator :)

**Comment by partouf** [comment]
this is now live (with PR https://github.com/compiler-explorer/compiler-explorer/pull/4065)

Examples:

* https://godbolt.org/z/4zh5jaov6
* https://godbolt.org/z/h8d3dzWsr
* https://godbolt.org/z/qnE7jhnvc
