### ISSUE TITLE
[BUG]: __m512 isn't highlighted

### ISSUE THREAD

**Issue by phuclv90** [compiler-explorer/compiler-explorer#4012]
### Describe the bug

`__m128` and `__m256` are highlighted normally but `__m512` isn't

### Steps to reproduce

Type `__m512` to any source editors

### Expected behavior

`__m512` should be highlighted

### Reproduction link

https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:1,endLineNumber:10,positionColumn:1,positionLineNumber:10,selectionStartColumn:1,selectionStartLineNumber:10,startColumn:1,startLineNumber:10),source:'%23include+%3Cintrin.h%3E%0A%23include+%3Cxmmintrin.h%3E%0A%0Aextern+__m128+__vectorcall+test(__m128+a,+__m128+b,+__m256+c,+__m512+d,+__m256+e,+__m512+f)%3B%0A%0A__m128+__vectorcall+test2(__m128+a,+__m128+b,+__m256+c,+__m512+d,+__m256+e,+__m512+f)%0A%7B%0A++++return+test(b,+a,+e,+f,+c,+d)%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:38.16892327530626,l:'4',m:100,n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:vcpp_v19_32_x64,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'/O2+/arch:AVX512+/W3',selection:(endColumn:14,endLineNumber:12,positionColumn:14,positionLineNumber:12,selectionStartColumn:14,selectionStartLineNumber:12,startColumn:14,startLineNumber:12),source:1,tree:'1'),l:'5',n:'0',o:'x64+msvc+v19.32+(C%2B%2B,+Editor+%231,+Compiler+%231)',t:'0')),header:(),k:48.25760326798374,l:'4',m:50,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86+msvc+v19.32',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x64+msvc+v19.32+(Compiler+%231)',t:'0')),header:(),l:'4',m:50,n:'0',o:'',s:0,t:'0')),k:61.83107672469375,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

### Screenshots

<img width="873" alt="Screen Shot 2022-09-02 at 9 19 36 AM" src="https://user-images.githubusercontent.com/9285512/188044782-235ca844-9aec-42f6-bacb-dd40929d5661.png">

**Comment by jeremy-rifkin** [comment]
Hi @phuclv90 thank you for the report, we use the monaco editor and our C++ syntax highlighting is from them (I don't think we do any custom C++ highlighting on top of what they have). It would be great to file this issue upstream with them.
(relevant code: https://github.com/microsoft/monaco-editor/blob/main/src/basic-languages/cpp/cpp.ts#L194)

**Comment by jeremy-rifkin** [comment]
I have been corrected by Ruben on discord, we do actually add on our own keywords https://github.com/compiler-explorer/compiler-explorer/blob/main/static/modes/cppp-mode.ts#L87. We're happy to do a quick fix on our end but it'd be better to address this upstream :)
