### ISSUE TITLE
[BUG]: Ada/GNAT broken when binary and/or exec mode used

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#4027]
### Describe the bug

When compiling to binary, the assembler view is invalid.

### Steps to reproduce

Try to compile the default code with binary enabled.

### Expected behavior

binary and/or executable

### Reproduction link

https://ada.godbolt.org/z/M4dbvo93a

### Screenshots

Not applicable

**Comment by partouf** [comment]
It claims it did not produce an executable. When I try the example that we provide it works fine https://ada.godbolt.org/z/3aTdaaPbY

I suspect it's the Example taking a parameter while that's the main program (because the file is called that way)

https://ada.godbolt.org/z/GqKcbMWh1 does work

**Comment by dkm** [comment]
You're right, sorry was too quick at opening the issue!
