### ISSUE TITLE
[REQUEST]: Support cv_loc/cv_file format

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#4028]
### Is your feature request related to a problem? Please describe

Odin uses llvm to output llvm-as output, which uses `cv_loc` and `cv_file` directives for file and location. Can we support this too in our default parser?

### Describe the solution you'd like

Support `cv_loc` in `asm-parser`

### Describe alternatives you've considered

Hacking the odin compiler

### Additional context

Example code:

```asm
main.main:
.Lfunc_begin54:
        .cv_func_id 52
        .cv_file        10 "C:\\Users\\Jesse\\AppData\\Local\\Temp\\compiler-explorer-compiler202285-9656-uudy13.4g1h\\example.odin"
        .cv_loc 52 10 3 0
.seh_proc main.main
        subq    $24, %rsp
        .seh_stackalloc 24
        .seh_endprologue
.Ltmp423:
        .cv_loc 52 10 4 5
        movq    $1, 16(%rsp)
        .cv_loc 52 10 5 5
        movq    $2, 8(%rsp)
        .cv_loc 52 10 6 5
        movq    16(%rsp), %rax
        addq    8(%rsp), %rax
        movq    %rax, (%rsp)
.Ltmp424:
        .cv_loc 52 10 7 1
        addq    $24, %rsp
        retq
```

**Comment by JesseRMeyer** [comment]
The associated Odin code for that asm snippet is:
```go
package main

main :: proc () {
    bob := 1
    sally := 2
    bob_sally := bob + sally
}
```

If helpful.

**Comment by RubenRBS** [comment]
Reminder that we'll need to edit [compiler-explorer/asm-parser](https://github.com/compiler-explorer/asm-parser) for any changes to show in the live site

**Comment by partouf** [comment]
> Reminder that we'll need to edit [compiler-explorer/asm-parser](https://github.com/compiler-explorer/asm-parser) for any changes to show in the live site

Currently that still only applies to objdump parsing, but I would appreciate keeping asm-parser synced if we change that in case we do want to switch
