### ISSUE TITLE
[BUG]: CMake Execution pane broken

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#4030]
### Describe the bug

Program is actually executing (if you look at the response in the Network tab in Chrome), but the UI is showing it wasn't able to execute.

### Steps to reproduce

Open the CMake C++ Template, you can also recreate the pane etc. and see the same

### Expected behavior

Should show execution output and not an error

### Reproduction link

https://godbolt.org/z/abEE7czr3

### Screenshots

Not applicable

**Comment by RubenRBS** [comment]
Ohh this seems to be a repo of COMPILER-EXPLORER-9J9 ! Finally

**Comment by mattgodbolt** [comment]
Also reported to me via a Twitter DM

**Comment by RubenRBS** [comment]
The executor is expecting `result.buildResult` to always be present but this does not seem to be the case. I've added an extra if while we investigate the issue
