### ISSUE TITLE
How to use libc++-15 with clang-15?

### ISSUE THREAD

**Issue by Reedbeta** [compiler-explorer/compiler-explorer#4045]
I know that libc++ can be selected by using `-stdlib=libc++` with clang. However, I'm wondering if there is a way in Compiler Explorer to select particular versions of libc++?

LLVM 15 was recently released and libc++-15 now fully supports the C++20 ranges library, in particular range views, which weren't implemented before. However, when selecting clang-15 in Compiler Explorer, I still get an error message `no member named 'views' in namespace 'std::ranges'`: https://godbolt.org/z/q47W1ToTb (which is the same error received in earlier versions of clang).

It works if I select clang-trunk. Also, I downloaded the LLVM 15 release myself and verified that the same code compiles properly with it using the in-box version of libc++. So I'm guessing Compiler Explorer is using an older libc++ even when you select clang-15. Is there a way to point it at the newer version?

**Comment by partouf** [comment]
Thanks for the hint. Considering our buildsystem I’m assuming this isn’t in actual trunk yet, but we can investigate

**Comment by partouf** [comment]
So Clang 15 still has the views under a guard that you can disable using `-fexperimental-library`, they only removed it 24 days ago but did not include it in the Clang 15 release https://github.com/llvm/llvm-project/commit/b8cb1dc9ea87faa8e8e9ab7a31710a8c0bb8b084

**Comment by Reedbeta** [comment]
OK, thanks. I'm still confused how it worked when I tried the manually downloaded release, but this gets me going for now.
