### ISSUE TITLE
Use both the optimization level and the specific optimization option, the optimization option does not work.[BUG]: 

### ISSUE THREAD

**Issue by xiaoleiren** [compiler-explorer/compiler-explorer#4049]
### Describe the bug

Use both the optimization level and the specific optimization option, the optimization option does not work.
e.g.
-O1/2/3  -fno-inline
The optimization level takes effect, but the optimization flag does not work.

### Steps to reproduce

inline int Add(int a, int b)
{
   return a + b;
}
int main()
{
   int num1 = 1;
   int num2 = 2;
   int myNum = Add(num1, num2);
}

### Expected behavior

-O1/2/3  -fno-inline

Thanks to all the developers for their contributions, I really appreciate it, and if I'm using it incorrectly, please feel free to let me know. Thanks again!

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by dkm** [comment]
Please provide an example link so that we know which compiler you are using and how to detect the issue. I suspect this has nothing to do with CE and simply shows that the compiler can do counter-intuitive things wrt inlining.

**Comment by jeremy-rifkin** [comment]
I can see the behavior testing with gcc. I don't think this is a CE issue, rather an issue of gcc not being able to turn off its inlining.
