### ISSUE TITLE
Have a "Auto" setting for dark mode

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#4057]
Maybe make that the default, then "auto" can select light/dark with https://www.hanselman.com/blog/how-to-detect-if-the-users-os-prefers-dark-mode-and-change-your-site-with-css-and-js

Twitter thread: https://twitter.com/smurthys/status/1569782727624327171?s=20&t=CnmVxZacMIlXUPziwptCOg

**Comment by RubenRBS** [comment]
Fun fact: We try to do this already in [static/settings.ts#L302](https://github.com/compiler-explorer/compiler-explorer/blob/05d0fa6e856a3593808884b79ce31c2a735048a8/static/settings.ts#L302) - If it's being suggested it means it's not working anymore :/

**Comment by mattgodbolt** [comment]
or the OP already had the setting "guessed' at. The code you linekd sets the default; presumably if the setting had been saved it would override that.
