### ISSUE TITLE
[COMPILER REQUEST]: clang15 and clang-trunk as an HLSL compiler option

### ISSUE THREAD

**Issue by thewilsonator** [compiler-explorer/compiler-explorer#4060]
### Compiler name

LLVM Clang

### Compiler version

trunk and LLVM15

### Compiler language

HLSL

### Compiler homepage

https://releases.llvm.org/15.0.0/tools/clang/docs/ReleaseNotes.html

### Motivation

CE already has clang-15 and clang-trunk, and clang can compile HLSL using the in development DirectX backend.
But clang is not available as an HLSL compiler option. Adding this would allow easily tracking the progress of the backend development and explore the form the IR takes for other LLVM frontends that want to use the backend

**Comment by RubenRBS** [comment]
Closed by #4061
