### ISSUE TITLE
[COMPILER REQUEST]: Kalray KVX 4.8 and 4.9 (both gcc 9 based IIUC)

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#4066]
### Compiler name

gcc

### Compiler version

4.8 4.9

### Compiler language

*

### Compiler homepage

https://github.com/kalray/build-scripts/releases

### Motivation

:)
ping @fallen @xavierraynaud so you can see when I'm done :)

**Comment by XavierRaynaud** [comment]
thanks a lot !
