### ISSUE TITLE
[LIB REQUEST]: `tl::expected` (C++)

### ISSUE THREAD

**Issue by qqii** [compiler-explorer/compiler-explorer#4081]
### Library name

`tl::expected`

### Library description

`tl::expected` is a single header implementation of `std::expected` *with functional-style extensions.*

### Library repository

https://github.com/TartanLlama/expected

### Motivation

I'd like to compare the decompiled output to [`expected-lite`](https://github.com/martinmoene/expected-lite), another single header implementation of `std::expected`. I'm especially interested in how the functional-style extensions stack up.

**Comment by RubenRBS** [comment]
Hi! Thanks for the request, I've now added the necessary changes and it should be live soon :)
