### ISSUE TITLE
[BUG]: Default Cpp2 source code generates ill-formed code

### ISSUE THREAD

**Issue by JohelEGP** [compiler-explorer/compiler-explorer#4087]
### Describe the bug

The current default: https://compiler-explorer.com/z/99PxKjGMz.
The part of it in question:
```Cpp2
main: () -> int =
    std::cout << "Hello " << name() << "\n";
```
Generates
```C++
[[nodiscard]] auto main() -> int { 
    return std::cout << "Hello " << name() << "\n"; }
```
Which results in:
```
[ 66%] Building CXX object CMakeFiles/test.dir/test.cpp.o
test.cpp2: In function 'int main()':
test.cpp2:12:44: error: cannot convert 'std::basic_ostream<char>' to 'int' in return
   12 |     std::cout << "Hello " << name() << "\n";
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^      
      |                                            |
      |                                            std::basic_ostream<char>
```
Found when adding a CMake module to support Cpp2: https://godbolt.org/z/f8Eeo489o.

### Steps to reproduce

1. https://compiler-explorer.com
2. Choose Cpp2-cppfront as language

### Expected behavior

Adding braces around the statement works:
```Cpp2
main: () -> int = {
    std::cout << "Hello " << name() << "\n";
}
```
Generates:
```C++
[[nodiscard]] auto main() -> int{
    std::cout << "Hello " << name() << "\n";
}
```
See https://compiler-explorer.com/z/nbq7hhfP9, https://godbolt.org/z/cYf1MrPM4.

### Reproduction link

https://compiler-explorer.com/z/99PxKjGMz

### Screenshots

Not applicable

**Comment by partouf** [comment]
Doesn't look like a bug to me, but either way that would be something for https://github.com/hsutter/cppfront - but I see Issues is disabled in that repo.

Cool idea using Cmake for this, though

**Comment by partouf** [comment]
The example is here https://github.com/compiler-explorer/compiler-explorer/blob/main/examples/cpp2_cppfront/default.cpp2 you can just edit that and create a PR

**Comment by JohelEGP** [comment]
Sorry, but this was my mistake. The default code has the braces. I must have removed them.
