### ISSUE TITLE
[BUG]: Undefined symbols when linking to Libc++ with CMake project

### ISSUE THREAD

**Issue by JohelEGP** [compiler-explorer/compiler-explorer#4088]
### Describe the bug

Linking "hello world" with a CMake project (https://godbolt.org/z/G4qabKxcM), with effective compile and link flags `-stdlib=libc++` and `-lc++abi`, respectively, results in undefined symbol errors. Without a CMake project, it works: https://godbolt.org/z/6d5zsTzoj.

### Steps to reproduce

1. Visit https://godbolt.org/z/G4qabKxcM.
2. Confirm the presence of `-stdlib=libc++` under the output of `[ 50%] Building CXX object CMakeFiles/test.dir/test.cpp.o`.
3. Confirm the presence of `-lc++abi` under the output of `[100%] Linking CXX executable test`.
4. Confirm the linker errors further below.

### Expected behavior

The program links and executes correctly, just like without the CMake project: https://godbolt.org/z/6d5zsTzoj.

### Reproduction link

https://godbolt.org/z/G4qabKxcM

### Screenshots

Not applicable

**Comment by partouf** [comment]
`-stdlib=libc++` is passed to the compiler for the program, but not for the tests. Not sure why, they must be overwritten somewhere.

```
[ 50%] Building CXX object CMakeFiles/test.dir/test.cpp.o
/opt/compiler-explorer/clang-trunk/bin/clang++ --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot   -std=c++2b -stdlib=libc++ -MD -MT CMakeFiles/test.dir/test.cpp.o -MF CMakeFiles/test.dir/test.cpp.o.d -o CMakeFiles/test.dir/test.cpp.o -c /app/test.cpp
```

```
[100%] Linking CXX executable test
/opt/compiler-explorer/cmake-v3.23.1/bin/cmake -E cmake_link_script CMakeFiles/test.dir/link.txt --verbose=1
/opt/compiler-explorer/clang-trunk/bin/clang++ --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -std=c++2b -L/app -Wl,-rpath,/app -Wl,-rpath,/opt/compiler-explorer/gcc-snapshot/lib64 -Wl,-rpath,/opt/compiler-explorer/gcc-snapshot/lib32 -lc++abi CMakeFiles/test.dir/test.cpp.o -o test 
```

**Comment by JohelEGP** [comment]
Thank you. That fixes it.
