### ISSUE TITLE
[BUG]: Clang 15 uses libstdc++12, but its corresponding Clang Tidy only uses libstdc++9.

### ISSUE THREAD

**Issue by cjdb** [compiler-explorer/compiler-explorer#4092]
### Describe the bug

As discovered in https://github.com/llvm/llvm-project/issues/57973, Clang 15 uses libstdc++12, but its corresponding Clang Tidy only uses libstdc++9.

This can cause issues since Clang can compile C++20 code, but it can't be linted.

### Steps to reproduce

1. Select Clang 15 as the compiler.
2. Add `-v` to the options.
3. Enable Clang Tidy.

### Expected behavior

Clang and Clang Tidy should always use the same version of the standard library.

### Reproduction link

https://godbolt.org/z/d59j5dnTj

### Screenshots

Not applicable

**Comment by apmorton** [comment]
The catch here is that there is exactly one version of clang tidy on the site (the current clang trunk build) - its completely oblivious to whether or not you are even using clang.

The best we can do without pretty major reworking is bump the version of gcc that its using.

See: https://github.com/compiler-explorer/compiler-explorer/blob/4185afad920ea7cd7efbe7f90cc085aa03b4f0a7/etc/config/c%2B%2B.amazon.properties#L2918

We could either bump this to the latest versioned gcc, or switch to using gcc trunk.

Not sure which is more defensible.

**Comment by apmorton** [comment]
You can work around this issue for now by adding `--extra-arg=--gcc-toolchain=/opt/compiler-explorer/gcc-12.2.0` to the clang-tidy arguments
https://godbolt.org/z/Es5xdrr6v

**Comment by partouf** [comment]
fix is now live
