### ISSUE TITLE
[BUG]: Dropdown options under conformance view does not have msvc x64 option anymore

### ISSUE THREAD

**Issue by ranaanoop** [compiler-explorer/compiler-explorer#4103]
### Describe the bug

I noticed that when clicking on the dropdown button under the conformance view, there is no option for choosing "x64 msvc v19.latest" anymore. For example, in one of my stackoverflow posts i gave [this link](https://godbolt.org/z/oorG7ajKd) on which if you'll click you'll also notice that the msvc compilers are not there. I've attached the screenshot below highlighting the same.

![MSVC FRONTEND BUG](https://user-images.githubusercontent.com/93918384/193404581-7091c98e-ae99-4b53-be29-dc7baef36b44.png)

### Steps to reproduce

1. Visit the link https://godbolt.org/z/oorG7ajKd
2.  You'll notice that in two of the options there is no msvc compiler.

### Expected behavior

I expect that when i get those 2 blank options(which used to have msvc compiler) back and same when i click on the dropdown button shown in the screenshot.

### Reproduction link

https://godbolt.org/z/oorG7ajKd

### Screenshots

![MSVC FRONTEND BUG](https://user-images.githubusercontent.com/93918384/193404637-f8c24e10-7bb5-4e03-935f-084463718998.png)

### Operating System

Ubuntu Linux 18.04

### Browser version

Firefox 101.0.1(64 bit)

**Comment by partouf** [comment]
msvc is temporarily disabled due to problems on the MS side of things, they'll probably be back after the weekend

**Comment by ranaanoop** [comment]
@partouf Ok, I see.

**Comment by ranaanoop** [comment]
@partouf Looks like msvc is back. [Demo](https://godbolt.org/z/6doWdnzcr). So, closing this issue.
