### ISSUE TITLE
[REQUEST]: Multiple LLVM Opt Pipelines

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#4112]
### Is your feature request related to a problem? Please describe

I wish to inspect the optimization pipeline for two ever-so-slightly different functions, to be able to pinpoint the source of difference in optimization decisions. Selecting a function in a single opt-pipeline pane is already great - I wish I could add two such viewers, to select a different function in each.

### Describe the solution you'd like

Currently after opening one llvm-opt-pipeline pane, the option becomes disabled in the "Add" dropdown:
![image](https://user-images.githubusercontent.com/73080/193888256-7d69413c-c525-43bb-b46c-e63df03fd5ca.png)

Hopefully it's feasible to allow a few of these to open.

### Describe alternatives you've considered

Curl up into a ball and cry

### Additional context

llvm-opt-pipeline is a *seriously* great feature. Thanks.

**Comment by RubenRBS** [comment]
Sounds like a good idea, I've now opened a PR for it :)

**Comment by OfekShilon** [comment]
@RubenRBS that took an entire 16 minutes. You're getting slow ..
