### ISSUE TITLE
[BUG]: Compilation of default erlang example fails

### ISSUE THREAD

**Issue by goelzma** [compiler-explorer/compiler-explorer#4121]
### Describe the bug

Selecting erlang from the language dropdown results in a failed compilation on the default example.

### Steps to reproduce

As above, or use the link below.

### Expected behavior

The result of compiling the example code is shown.

### Reproduction link

https://godbolt.org/z/Mdrad75G6

### Screenshots

Not applicable

**Comment by RubenRBS** [comment]
Hi! Thanks for the heads-up. It seems to have broken in a recent refactor. I've now pushed a fix that should go live soon :)
