### ISSUE TITLE
[COMPILER REQUEST]: i686 gcc / i686 clang

### ISSUE THREAD

**Issue by cheyao** [compiler-explorer/compiler-explorer#4123]
### Compiler name

i686 gcc/i686 clang

### Compiler version

12.2.0 i686 Linux

### Compiler language

C, C++, asm

### Compiler homepage

https://gcc.gnu.org/

### Motivation

I would really like to test out 32 bit code on godbolt

**Comment by partouf** [comment]
this is already possible by passing `-m32` to the compilers

**Comment by mattgodbolt** [comment]
@cheyao https://godbolt.org/z/z63cP7nG4 is an example of building and running C++ code in 32-bit mode. Feel free to reopen if that's not what you're asking about! Thanks.

**Comment by cheyao** [comment]
Oh yea that was what I wanted! thx
