### ISSUE TITLE
[BUG]: "Filter Debug Info" in llvm-opt-pipeline-viewer removes important (non-debugg) attributes

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#4126]
### Describe the bug

In the LLVM Opt Pipeline viewer, under the 'Filters' dropdown there's a checkbox for 'Filter Debug Info' which is (I think) checked by default. 
![image](https://user-images.githubusercontent.com/73080/194541726-75da6dd7-5dfc-43d5-955a-6ef24fd84d7f.png)

It removes from the display the postfix attributes `!dbg !XX` which is good, but it also removes attributes with important semantic meaning, like `!tbaa !XX`.

### Steps to reproduce

1. Visit https://godbolt.org/z/bvT6dzc9M
2. Check and uncheck the 'Filter Debug Output' checkbox. 
3. Observe the changes in displayed IR

### Expected behavior

Hide only `!dbg !XX` attributes

### Reproduction link

https://godbolt.org/z/bvT6dzc9M

### Screenshots

Without filtering:
![image](https://user-images.githubusercontent.com/73080/194541881-71a0c99d-c262-41c8-89f9-6ae98b5c0416.png)

With filtering:
![image](https://user-images.githubusercontent.com/73080/194542010-8d0dc7c8-5555-404f-91cc-7870e830aab0.png)

**Comment by OfekShilon** [comment]
These regexes probably need another look:
https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/parsers/llvm-pass-dump-parser.ts#L113

**Comment by jeremy-rifkin** [comment]
Thank you for the report!
