### ISSUE TITLE
[BUG]: C++ shows an Error which is non - but only if another C-Executor is activated

### ISSUE THREAD

**Issue by bjoekeldude** [compiler-explorer/compiler-explorer#4137]
### Describe the bug

I was presenting something to my students and showed one C-Implementation that actually IS an error and on the other side a C++ Implementation that isn't an error. 
Anyway, the C++ Editor shows a red underline.

### Steps to reproduce

1. This shows an error in line 18 of the right Cpp Editor: https://godbolt.org/z/esdv447Y9
2. Same implementation when C-Executor is deactivated doesn't show the Error: https://godbolt.org/z/MWY5fGeav

### Expected behavior

No Error in the first place in the Cpp Implementation

### Reproduction link

Not applicable

### Screenshots

<img width="957" alt="image" src="https://user-images.githubusercontent.com/10761141/194916371-bde5f269-62e9-46ff-a860-e4cb43b88303.png">

### Operating System

Windows 10

### Browser version

Chrome 105.0.5195.127 (64-Bit)

**Comment by mattgodbolt** [comment]
Thanks for the links: confirmed - it looks like the error messages for the C editor are being applied to the C++ editor (both on line 11 in the first example you gave)
