### ISSUE TITLE
[LIB REQUEST]: fmt make 9.x available?

### ISSUE THREAD

**Issue by reddwarf69** [compiler-explorer/compiler-explorer#4141]
### Library name

fmt

### Library description

The pull-down for selecting fmt library only has versions through 8.x. Can you please add 9.x flavors? Thanks.

### Library repository

https://github.com/fmtlib/fmt

### Motivation

It's the current set of releases.

By the way, there was https://github.com/compiler-explorer/compiler-explorer/issues/3438 for 8.x. Do you have anything informing you of new releases? It may be broken for fmt.

**Comment by RubenRBS** [comment]
Thnaks for the heads-up! I'll try to get this updated this weekend



> Do you have anything informing you of new releases? It may be broken for fmt.

That would be issues such as this one, mostly :)
