### ISSUE TITLE
[REQUEST]: Sort newest versions of libraries on top

### ISSUE THREAD

**Issue by kiwixz** [compiler-explorer/compiler-explorer#4142]
### Is your feature request related to a problem? Please describe

I'm used to see the most recent on top, especially for versions (see github releases and tags for example).  So it takes me one extra second when adding a library in compiler explorer because I most often than not just want to click the first line to get the most recent version.

### Describe the solution you'd like

Reverse the libraries versions combo box sort order.

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by mattgodbolt** [comment]
For what it's worth I've thought the same too!

**Comment by RubenRBS** [comment]
I think the fact that they appear somewhat sorted is a fluke. As far as I can tell, we don't try to sort them at any point!

But we can probably try to do so :)

**Comment by partouf** [comment]
they are probably in order of how they were added to the properties file, which is usually from low version to high
