### ISSUE TITLE
[BUG]: Failure to compile should prevent execution of code 

### ISSUE THREAD

**Issue by JohelEGP** [compiler-explorer/compiler-explorer#4147]
### Describe the bug

With code execution enabled, an ill-formed program will fail to compile. This does not prevent the execution step from running, which attempts to recompile the code, most likely resulting in another failure to compile.

### Steps to reproduce

1. Visit https://compiler-explorer.com/z/TsWEnf8Pq, with source:
```C++
int;
```
2. Notice that the errors are doubled, once for each step, as indicated by `ASM generation compiler returned:` and `Execution build compiler returned:`:
```
<source>:1:1: error: declaration does not declare anything [-fpermissive]
    1 | int;
      | ^~~
ASM generation compiler returned: 1
<source>:1:1: error: declaration does not declare anything [-fpermissive]
    1 | int;
      | ^~~
Execution build compiler returned: 1
```

### Expected behavior

Failure to compile prevents the execution step from running.

### Reproduction link

https://compiler-explorer.com/z/TsWEnf8Pq

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
Great idea, this seems like such a no-brainer I can't believe we didn't do it sooner
