### ISSUE TITLE
[REQUEST]: Environment variable support

### ISSUE THREAD

**Issue by SoniEx2** [compiler-explorer/compiler-explorer#4151]
### Is your feature request related to a problem? Please describe

We'd like to use `RUSTC_BOOTSTRAP` with older rustc versions, to make it easier to explore them.

### Describe the solution you'd like

Being able to set env vars would allow setting `RUSTC_BOOTSTRAP`.

### Describe alternatives you've considered

N/A

### Additional context

Not applicable

**Comment by partouf** [comment]
Duplicate of https://github.com/compiler-explorer/compiler-explorer/issues/3154 following discussion in https://github.com/compiler-explorer/compiler-explorer/issues/2567#issuecomment-982461584

**Comment by SoniEx2** [comment]
none of those show up searching for "environment"

**Comment by jryans** [comment]
Environment variables controlling output also comes up with Racket (various diagnostic outputs I'd like to visualise are controlled by environment variables there).

For the Racket case, I've been thinking of potentially looking for certain known env vars in the optimisation flags input and supporting only those if found (to avoid exposing all env vars which might do bad things to e.g. `PATH`).

Perhaps though something more general is warranted if this exists across several toolchains. It would also be okay to treat each variant as its own special case. I just thought it would be good to mention it's not just e.g. this one flag from Rust that's of interest.

**Comment by Jorropo** [comment]
This also come up when trying to configure the go compiler.
For example enabling amd64 sub architectures require setting the `GOAMD64` environment variable to either `v1`, `v2`, `v3` or `v4`.

**Comment by landaire** [comment]
I'd also like to voice support for this. It'd be useful for scenarios where you wish to compile with `-fsanitize=address -fsanitize-recover=address` and run with `ASAN_OPTIONS=halt_on_error=0`.

**Comment by VictorEijkhout** [comment]
OpenMP programs are far-going controlled through environment variables. And right now I think one compiler is broken in how it deals with a variable so I'd like to try different compilers.

```
OMP_SCHEDULE=static ./myprogram
```

**Comment by partouf** [comment]
You can now add the variable to a new screen.

![Screenshot from 2023-05-16 05-05-47](https://github.com/compiler-explorer/compiler-explorer/assets/442630/e46c3a66-d632-4974-b759-9a4e9388838d)
![Screenshot from 2023-05-16 05-08-50](https://github.com/compiler-explorer/compiler-explorer/assets/442630/6814fd25-6fda-44ee-98e9-bf16c6115a6b)

This is available for the compiler only for now.
We might add a similar feature in the future for user code execution.
