### ISSUE TITLE
[REQUEST]: Increase the size of the compiler selection drop down menu

### ISSUE THREAD

**Issue by akbyrd** [compiler-explorer/compiler-explorer#4157]
### Is your feature request related to a problem? Please describe

I have a hard time finding the compiler I want to select in the drop down menu.

![image](https://user-images.githubusercontent.com/484784/195761081-eb1dc086-d097-44d9-89be-cae593b64dc9.png)

### Describe the solution you'd like

A much, much bigger drop down. Or a larger selection window with logical groupings of compilers. Or a hierarchical menu. There are probably quite a few ways to skin this UX cat.

### Describe alternatives you've considered

Not applicable

### Additional context

Not applicable

**Comment by RubenRBS** [comment]
Hi! Thanks for taking the time to request this change. You're right, we can always do better in the UI/UX department.
The main roadblock here comes from us not actually knowing what we're doing when it comes to it hahaha. We can certainly try some experiments and see if anything looks good. I'll give it some thoughts :)

**Comment by jeremy-rifkin** [comment]
Thank you for opening the issue. Making that dropdown taller should be straightforward and a good improvement for now.

Hierarchical is a good idea, I think architecture as the first layer of the hierarchy could be very helpful but I'm not immediately sure what the best interface would be.
It could also be helpful to hide compiler forks by default
![image](https://user-images.githubusercontent.com/51220084/195948686-5f347bd4-73af-47ae-b664-287e2cebdb0e.png)
(I suspect other than trunk these are used very rarely and by more experienced users)

**Comment by RubenRBS** [comment]
There has been some talk is Discord about how to best improve this - namely, grouping by vendor/arch could be a viable way to reduce clutter

**Comment by jeremy-rifkin** [comment]
This was fixed by #4849 🎉
