### ISSUE TITLE
[COMPILER REQUEST]: New architecture LoongArch GCC support

### ISSUE THREAD

**Issue by specialpointcentral** [compiler-explorer/compiler-explorer#4162]
### Compiler name

GCC

### Compiler version

gcc-12.2.0

### Compiler language

C++, Assembly, C

### Compiler homepage

https://gcc.gnu.org/

### Motivation

LoongArch is a new RISC ISA, which is a bit like MIPS or RISC-V, and today Linux/GCC/LLVM etc. support LoongArch. So I want to support this new architecture.
I have opened an PR at [gcc-cross-builder](https://github.com/compiler-explorer/gcc-cross-builder/pull/40), and what do I need to do next?

Thanks.

**Comment by dkm** [comment]
Hey, thanks for the initial PR for gcc-cross-builder. I'll bump the ct-ng revision to have your latest change in the dockerimage.
You also need a change in the infra repository (to be able to install the compiler after it has been built from gcc-cross-builder) and the config changes in compiler-explorer.

I see you only have C/C++ enabled. Usually I try to enable as much lang as possible: Ada, D, Go, Fortran... I'll try that locally and see how it works :)

**Comment by dkm** [comment]
Running a build now to check it works and if we can enable more languages.

**Comment by dkm** [comment]
"[ERROR]    configure: error: "libffi has not been ported to loongarch64-unknown-linux-gnu.""
Not sure what is causing this yet (what depends on libffi)

**Comment by dkm** [comment]
Hmmm, probably Go

**Comment by dkm** [comment]
c/c++/objc/d/fortran OK
Ada/Go KO 

:)

**Comment by specialpointcentral** [comment]
Thanks a lot for testing other types of compilers.
I think c/c++/fortran are fine because I have used them before, but I am not sure if objc/d are supported. Also, I know that Ada/Go are not supported yet. :-)

**Comment by dkm** [comment]
I'll build the compiler later today and proceed with the testing and needed changes in infra and config. Thanks @specialpointcentral !

**Comment by specialpointcentral** [comment]
Great! Thanks. 👍

**Comment by dkm** [comment]
TODO:
- [ ] build the compiler: https://github.com/compiler-explorer/infra/actions/runs/3310674182
- [ ] changes in infra
- [ ] changes in config
- [ ] compiler installed

**Comment by dkm** [comment]
After testing, seems that D is not OK, same issue as with sh. Hopefully will be fixed in GCC 13.
I'll need to fix config, rebuild and rework the config changes
