### ISSUE TITLE
[BUG]: GCC trunk doesn't link libraries to use with <stacktrace>

### ISSUE THREAD

**Issue by cuzdav** [compiler-explorer/compiler-explorer#4167]
### Describe the bug

The C++23 <stacktrace> code requires extra linking which is not set up in the  x86_64 gcc trunk.

While there is a facility to add some libraries to the link line, for the standard library we shouldn't have to do this, and the needed library does not seem to be an option anyway.

### Steps to reproduce

This program doesn't link.  GccTrunk, x86_64, option `-std=c++23`

#include <stacktrace>
int main() { std::stacktrace::current(); }

output:
ASM generation compiler returned: 0
/opt/compiler-explorer/gcc-trunk-20221018/bin/../lib/gcc/x86_64-linux-gnu/13.0.0/../../../../x86_64-linux-gnu/bin/ld: /tmp/ccQGvUbg.o: in function `std::stacktrace_entry::_S_init()':
/opt/compiler-explorer/gcc-trunk-20221018/include/c++/13.0.0/stacktrace:162: undefined reference to `__glibcxx_backtrace_create_state'
/opt/compiler-explorer/gcc-trunk-20221018/bin/../lib/gcc/x86_64-linux-gnu/13.0.0/../../../../x86_64-linux-gnu/bin/ld: /tmp/ccQGvUbg.o: in function `std::basic_stacktrace<std::allocator<std::stacktrace_entry> >::current(std::allocator<std::stacktrace_entry> const&)':
/opt/compiler-explorer/gcc-trunk-20221018/include/c++/13.0.0/stacktrace:255: undefined reference to `__glibcxx_backtrace_simple'
collect2: error: ld returned 1 exit status
Execution build compiler returned: 1

### Expected behavior

ASM generation compiler returned: 0
Execution build compiler returned: 0
Program returned: 0

### Reproduction link

https://godbolt.org/z/Pc87c3Y39

### Screenshots

Not applicable

**Comment by partouf** [comment]
https://gcc.gnu.org/onlinedocs/libstdc++/manual/debug_mode_using.html mentions you have to use `-lstdc++_libbacktrace`

Then it works https://godbolt.org/z/aTTMr7vc4

I don't think this should be linked by default

**Comment by mattgodbolt** [comment]
This is similar to having to link against filesystem to get `<filesystem>` etc I think. The documentation is not clear, but others have posted similar things. I agree we shouldn't link against it by default: our policy is to expose the compiler's default behaviour in almost all cases.

**Comment by cuzdav** [comment]
Thanks.  Makes sense.
