### ISSUE TITLE
[BUG]: opt pipeline viewer missing most passes

### ISSUE THREAD

**Issue by davidtgoldblatt** [compiler-explorer/compiler-explorer#4169]
### Describe the bug

The LLVM opt pipeline viewer seems to no longer show all relevant passes; it now only shows one (seemingly somewhere in target codegen, but the specific pass shown can change depending on compiler version).

### Steps to reproduce

1. Visit godbolt.org
2. Change the compiler to any clang compiler.
3. In the compiler tab, click "Add New" -> "LLVM Opt Pipeline"
4. Examine the "LLVM Opt Pipeline Viewer" tab

### Expected behavior

All LLVM opt passes are shown, with before/after.

### Reproduction link

https://godbolt.org/z/c1oP5b5Ke

### Screenshots

<img width="1534" alt="Screen Shot 2022-10-18 at 3 29 23 PM" src="https://user-images.githubusercontent.com/1660204/196557259-9a905522-89af-47b6-b5b9-1f2e6b45f83a.png">

**Comment by jeremy-rifkin** [comment]
Good find, thanks for the bug report
