### ISSUE TITLE
[BUG]: Scroll to Source does not work for dotnet

### ISSUE THREAD

**Issue by Therzok** [compiler-explorer/compiler-explorer#4171]
### Describe the bug

Example URL: https://godbolt.org/z/Mr44zq78j

When clicking Scroll to Source on any of the disassembled methods, nothing happens in the source pane.

### Steps to reproduce

See this godbolt sample: https://godbolt.org/z/Mr44zq78j

Alternatively: Use dotnet compiler, put in any code, try to navigate to source of any disassembled method.

### Expected behavior

The source pane should scroll to the method.

### Reproduction link

https://godbolt.org/z/Mr44zq78j

### Screenshots

<img width="487" alt="image" src="https://user-images.githubusercontent.com/109974/196713952-148fe4ee-6b8c-4aaa-a4ca-3f466419a694.png">

### Operating System

macOS

### Browser version

Version 106.0.5249.103 (Official Build) (x86_64)

**Comment by RubenRBS** [comment]
We can probably hide that action when that's the case then
