### ISSUE TITLE
[BUG]: Version Tree button does not work

### ISSUE THREAD

**Issue by RubenRBS** [compiler-explorer/compiler-explorer#4172]
### Describe the bug

The Version tree button does not open the last commit version in GitHub (In fact, it's not even clickable)

### Steps to reproduce

https://godbolt.org
Other > Version Tree is not clickable

### Expected behavior

The buttons be clickable

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by partouf** [comment]
On my mobile I could open it, it points to the SH compiler commit from 7 days ago

**Comment by RubenRBS** [comment]
Found the issue: I got my dev page and the live site mixed up. As you said, it works perfectly
