### ISSUE TITLE
[BUG]: Spurious red highlighting

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#4179]
### Describe the bug

https://godbolt.org/z/fWjMc7hff See that lines 5 and 10 are highlighted red

### Steps to reproduce

follow the link

### Expected behavior

no errors  maybe duplicate of #4084 

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by RubenRBS** [comment]
Found something similar in #4043, seems to be releated to the filenameRe in util's parseOutput

**Comment by jeremy-rifkin** [comment]
#4635 is another example https://godbolt.org/z/Mq5MMbWs9
![image](https://user-images.githubusercontent.com/51220084/218629860-9878abb8-2131-43f7-979d-80b631ea071e.png)

**Comment by jeremy-rifkin** [comment]
I think one thing we can do is separate compilation / execution stdout/stderr. Maybe also only parse the stderr, though I'm sure there is some compiler somewhere on the site that will output errors to stdout :)

**Comment by RubenRBS** [comment]
Sounds like a good idea!

**Comment by OfekShilon** [comment]
This is fixed now with @partouf's https://github.com/compiler-explorer/compiler-explorer/commit/25b5eccabfef1588d5ac4721c3ca152b9b620627
