### ISSUE TITLE
[BUG]: Loading button keeps on revolving 

### ISSUE THREAD

**Issue by ranaanoop** [compiler-explorer/compiler-explorer#4187]
### Describe the bug

If we visit [this link](https://godbolt.org/z/871Wf88x4), we will notice that the loading button in the rightmost window keeps on revolving. Below is the attached screenshot. 

### Steps to reproduce

1. Visit https://godbolt.org/z/871Wf88x4
2. After visiting note that the loading button(highlighted by red arrow) keep on revolving as the code is not being able to compile for some reason.

### Expected behavior

The loading button should stop revolving once the program is compiled.

### Reproduction link

https://godbolt.org/z/871Wf88x4

### Screenshots

![Frame 2(3)](https://user-images.githubusercontent.com/93918384/197382403-7c30a762-e41f-406b-b1af-e821cfa4606c.png)

### Operating System

Ubuntu Linux 18.04

### Browser version

Firefox 101.0.1(64 bit)

**Comment by partouf** [comment]
Probably related to #4188

**Comment by partouf** [comment]
should be fixed, let us know

**Comment by ranaanoop** [comment]
@partouf Yes, it works now.
