### ISSUE TITLE
LLVM/Clang should support the new target loongarch64

### ISSUE THREAD

**Issue by vfdff** [compiler-explorer/compiler-explorer#4191]
### Describe the bug

loongarch64 target has been in the llvm upstream for a long time, but now it is still now supportted.
see detail  https://godbolt.org/z/facPsvEaY

The above case come from https://reviews.llvm.org/D136222.

### Steps to reproduce

https://godbolt.org/z/facPsvEaY

### Expected behavior

works fine as local build

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment]
If I understand correctly, this is a new architecture supported by newer clangs? Is it something that needs to be configured at clang build time? We'd welcome a PR to https://github.com/compiler-explorer/clang-builder/blob/main/build/build.sh if you know how to do it!

Thanks, Matt

**Comment by specialpointcentral** [comment]
link to #4162

**Comment by specialpointcentral** [comment]
Now let's deal with this issue.

link to #6794.
