### ISSUE TITLE
[BUG]: Unable to add a new source editor

### ISSUE THREAD

**Issue by reconndev** [compiler-explorer/compiler-explorer#4194]
### Describe the bug

- A couple of days ago it worked but now trying to use IDE mode I am able to add a new source editor. There is no response

### Steps to reproduce

1. Visit godbolt.org
2. Close all window panes
3. Select Add -> Tree (IDE Mode)
4. In the Tree pane, click (+) "plus sign", select Source editor

### Expected behavior

The new window pane should pop up after selecting a new Source editor.

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Browser version

Version 106.0.5249.119 (Official Build) (arm64)

**Comment by partouf** [comment]
This slipped through the cracks because it's caused by the MOTD which we generally don't test locally. Thanks for letting us know. I'll try to produce a fix today

**Comment by partouf** [comment]
fix is live
