### ISSUE TITLE
[BUG]: Clone Compiler leaves the compiler flags field blank

### ISSUE THREAD

**Issue by Alcaro** [compiler-explorer/compiler-explorer#4207]
### Describe the bug

see title

### Steps to reproduce

- Type anything that affects output in compiler options field (-O2, --help, -xc, --not-an-option, whatever)
- Add new -> Clone Compiler
- The new compiler has the same output (or lack thereof) as the original, but the compiler options field is empty

### Expected behavior

Slightly less empty compiler options field

### Reproduction link

Not applicable

### Screenshots

![image](https://user-images.githubusercontent.com/5085186/198568560-40b4a002-7b39-445d-8295-4cb6ed6b3f4c.png)

### Operating System

Lubuntu 22.04

### Browser version

Firefox 106

**Comment by RubenRBS** [comment]
Ooops, probably releated to the recent TS conversion. Will try to fix asap

**Comment by partouf** [comment]
fix is now live
