### ISSUE TITLE
[BUG]: Reset UI layout stopped working

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#4213]
### Describe the bug

More->Reset UI doesn't do anything

### Steps to reproduce

1. https://godbolt.org/z/W47M8a6da
2. hit reset
3. nothing

### Expected behavior

a fresh new UI

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by RubenRBS** [comment]
I can't seem to repro this. Pressing the reset button properly resets the ui in my Firefox browser

**Comment by partouf** [comment]
Can confirm nothing happens in Chrome, no error either

**Comment by RubenRBS** [comment]
How did this work at all?
https://github.com/compiler-explorer/compiler-explorer/blob/b7dcb664f25cdfbc77017d720c94e8f8620dafaf/views/index.pug#L29 it's a button that we add an href to, but that's not supposed to work

**Comment by partouf** [comment]
ohhhh - but it used to be an 'a' https://github.com/compiler-explorer/compiler-explorer/commit/6c053b8a627bf576703306b15a71742a3aec2c99#diff-91a32afc54a61d377040500037bedf45210bd74d620a04ba1eb93faa1d4cdb0aR29

**Comment by RubenRBS** [comment]
I'm a dummy sometimes, sorry! Will fix it asap
