### ISSUE TITLE
[BUG]: `make run` misses to deploy the "etc/scripts" folder

### ISSUE THREAD

**Issue by aw32** [compiler-explorer/compiler-explorer#4225]
### Describe the bug

`make run` uses as root directory a new folder "out/dist/" which misses the "etc" folder from the repository.
Therefore, the scripts in "etc/scripts" are not available.
For example Python misses the "dis_all.py" script and fails with the following message:
```
/opt/homebrew/bin/python3.10: can't open file '/path/to/compiler-explorer/out/dist/etc/scripts/disasms/dis_all.py': [Errno 2] No such file or directory
Compiler returned: 2
```
This does not happen with the `make dev` command as it runs with the repository folder as root directory.

### Steps to reproduce

1. Clone the repository.
2. Configure "etc/config/python.defaults.properties" to define the installed Python versions.
3. Run `make run EXTRA_ARGS='--language python'`
4. Visit "http://localhost:10240/" for the local site.
5. The compilation of the example fails.

### Expected behavior

The `make run` rule should consider the necessary dependencies and/or the readme should explain how the "etc/scripts" folder is deployed to the root directory in this case.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by RubenRBS** [comment]
Hi! Sorry that this feel thru the cracks and we didn't get back to you in time. You're totally right, this is something that should work

**Comment by RubenRBS** [comment]
Closed by #4450 right?

**Comment by aw32** [comment]
> Closed by #4450 right?

No.

**Comment by lcarlier** [comment]
I'm also having the same issue.

Is there any fix available?

**Comment by lcarlier** [comment]
Thanks, running `make dev` works indeed. 

The only drawback is that the compiler explorer logo has the "DEV watermark"
![image](https://user-images.githubusercontent.com/5570374/232744345-0424c8c4-105a-4a5a-be62-e31af0cd35fd.png)

I suppose there is also some performance hit but as long that we don't see issue we can live with it.

**Comment by ezyang** [comment]
This affected me!

**Comment by OfekShilon** [comment]
A fix was merged, should be publicly visible at the next deploy
