### ISSUE TITLE
[BUG]: dotnet compiler option bug

### ISSUE THREAD

**Issue by RubenRBS** [compiler-explorer/compiler-explorer#4226]
While investigating #4218, I've found that the compiler code probably has a bug with the way it handles its options. See how the variable in the linked line is only written to, never read

https://github.com/compiler-explorer/compiler-explorer/blob/16d7af446c3e270adaf6377b6cedcc2262308b07/lib/compilers/dotnet.ts#L139

**Comment by kasperk81** [comment]
line 139 caches the options object. next line loops over the cached object and pushes to crossgen2Options hash. that crossgen2Options object is then passed to the compiler.

i don't see any issue here, what am i missing?

**Comment by partouf** [comment]
The options get filtered and divided up between compiler and crossgen.

There should probably be some feedback when something doesn't pass the filter, and we should probably allow --help (to both in this case and return both helps) and perhaps also return from our side what options we allow.

**Comment by kasperk81** [comment]
of course, user experience issue is https://github.com/compiler-explorer/compiler-explorer/issues/4218. but this bug  report isn't correct afaict. we _are_ reading the options in the loop on next line.

**Comment by RubenRBS** [comment]
Nice catch. For some reason I misread the code
