### ISSUE TITLE
[REQUEST]: Indirect inclusion of network files

### ISSUE THREAD

**Issue by steve02081504** [compiler-explorer/compiler-explorer#4232]
### Is your feature request related to a problem? Please describe

I have a repo to provide some header files with a lot of indirect includes ([example](https://github.com/ELC-lang/ELC/blob/master/parts/header_file/files/elc/base))
And I want to use these headers in godbolt for my testing or whatever
Since godbolt doesn't support the inclusion of relative paths in files that are included in the network, this has been difficult for me for a while
So far I've merged all my files into one file in a [separate repo](https://github.com/ELC-lang/online_cpp_header_files) using github action and a small tool, but I think that's a bit silly: interdependent files need to include a full copy of each other

### Describe the solution you'd like

I'd like files that have already been included via url to continue to indirectly include files in the network!

### Describe alternatives you've considered

perhaps this needs to be limited in size and depth, and perhaps a cache of preprocessed network files to avoid excessive network throughput

### Additional context

Not applicable

**Comment by RubenRBS** [comment]
Hi! Thanks for taking the time to open the request. This has been discussed a few more times before (Notably, some good suggestions from @YarikTH in #3929), but no work has been done on it as it's trickier than one would expect. We have some ideas, but until we can implement any of them, I'm sorry to say you'll still need to use your workaround for a bit :(

Closing in favour of the linked issue, but again, thanks for taking the time to open the request :)
