### ISSUE TITLE
[BUG]: Cannot add switches to python interpreter

### ISSUE THREAD

**Issue by TheCoder49** [compiler-explorer/compiler-explorer#4236]
### Describe the bug

Adding "-O" does not work when trying to run python in optimized mode

### Steps to reproduce

add "-O" to the "Compiler options"

### Expected behavior

Godbolt runs python in optimized mode

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by RubenRBS** [comment]
Hi! Thanks for your patience.

It seems we broke it in #3496 while trying to fix another issue.
I've now pushed a fix and it should be live Soon ™️ :)

**Comment by RubenRBS** [comment]
This is now live
