### ISSUE TITLE
[BUG]: Link error when linking against google benchmark

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#4242]
### Describe the bug

```
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/13.0.0/../../../../x86_64-linux-gnu/bin/ld: ./libbenchmark.a(benchmark.cc.o): relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIE
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/13.0.0/../../../../x86_64-linux-gnu/bin/ld: failed to set dynamic section sizes: bad value

```
when compiling the attached link

### Steps to reproduce

Follow the link

### Expected behavior

Should link

### Reproduction link

https://godbolt.org/z/vMnb51zfa

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment]
Adding `-Wl,-no-pie` helps a bit:

```
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/13.0.0/../../../../x86_64-linux-gnu/bin/ld: <source>:81: undefined reference to `benchmark::Initialize(int*, char**, void (*)())'
```

**Comment by partouf** [comment]
It's probably all going to be a bit of mess with gcc and clang switching to PIE, but benchmark has been recompiled against gcc trunk 4/5 days ago. I think gcc switched to PIE a couple weeks ago?

So I'm a little confused..

**Comment by partouf** [comment]
OH Clang!

gcc trunk does work and has not switched to default pie yet.

Benchmark seems to have stopped building for clang trunk; e991355 was the last commit that was built.. That's Jun 9, 2021

https://conan.compiler-explorer.com/getlogging/20221005042023 was the last build try that failed last month, seems related to missing requirements to build.

**Comment by dkm** [comment]
That's strange, i believe GCC is pie by default for several month now. There's --no-default-pie to disable this IIRC

**Comment by partouf** [comment]
> That's strange, i believe GCC is pie by default for several month now. There's --no-default-pie to disable this IIRC

hm, maybe im wrong, but no explicit default pie here in gcc trunk: https://godbolt.org/z/6b9E3Kbn3

Clang switched in v15/trunk to `-pic-is-pie` https://godbolt.org/z/bd5v558Yo
(before Clang v15, they compiled with `-mrelocation-model static` vs now pic + pic-is-pie)

**Comment by partouf** [comment]
But commits in gcc log are hinting that they're going to switch to default pie

**Comment by dkm** [comment]
Sorry, You're correct and I was wrong, it's not enabled by default in GCC, only most distros are using --enable-default-pie but default, configure option is false

**Comment by partouf** [comment]
If I had a penny for every time that I was right, I would have at least... 1 penny
