### ISSUE TITLE
[BUG]: "Output..." is missing on the output window

### ISSUE THREAD

**Issue by yongzhangopks** [compiler-explorer/compiler-explorer#4249]
### Describe the bug

On the header of output window it only shows A, Wrap lines and Select all. "Output..." is missing.

### Steps to reproduce

1. Enter any C++ code.
2. View output window

### Expected behavior

It should show "Output..." on the header of the output window

### Reproduction link

Not applicable

### Operating System

Windows 10

**Comment by yongzhangopks** [comment]
"Reset GUI layout" resolved it.

**Comment by RubenRBS** [comment]
Do you happen to have an stored link to this? We might be able to see if we broke something on our end
