### ISSUE TITLE
[BUG]: Compiler Explorer doesn't work if the web browser doesn't have an internet connection

### ISSUE THREAD

**Issue by RichardBelzer** [compiler-explorer/compiler-explorer#4252]
### Describe the bug

Compiler Explorer is unusable in situations where you are on a network that doesn't have a connection to the internet.

### Steps to reproduce

1. Set up Compiler Explorer with the instructions here https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/WindowsNative.md
2. Confirm that everything works great
3. Cut the internet connection
4. Clear the browser cache
5. Go to Compiler Explorer
6. Nothing works anymore

(The first step is what I use. I expect this issue to happen with any kind of install of CE)

### Expected behavior

The page fully loads, I can use CE.

### Reproduction link

Not applicable

### Screenshots

As you can see here, the page doesn't fully load. CE seems to be trying to get my web browser to pull some kind of 3rd party dependencies from the internet that I cannot access. This is problematic in an "offline" environment where you can access the CE server but cannot access the internet.

![image](https://user-images.githubusercontent.com/69686380/200196504-8f4700bf-9cdc-42b2-870a-1133806e0ebd.png)

### Operating System

Windows 11

### Browser version

Microsoft Edge 107.0.1418.35

**Comment by RichardBelzer** [comment]
FYI: I was able to fix this issue by commenting out one line:

static\tests\motd.ts:
`const stub = global.sinon.stub;`

Why this one line is messing everything up makes no sense to me, also why it's relating to testing is also perplexing. I'm just trying to access the server and not run any tests.

Not sure if things are supposed to behave this way, so I'll leave this ticket open until someone says otherwise and closes it.

**Comment by RubenRBS** [comment]
This is super wierd, thanks for the report. I'll see if I can dig into why this is happening

**Comment by partouf** [comment]
Noticed this as well during one of my debugging sessions locally, but that was because this `if` is not working right sometimes (no idea why yet) https://github.com/compiler-explorer/compiler-explorer/blob/main/views/_layout.pug#L9
But that would still mean you would need internet. Perhaps we can download `sinon.js` and use a local version instead?
