### ISSUE TITLE
[BUG]: GCC static analysis branch is outdated/obsolete

### ISSUE THREAD

**Issue by superjamie** [compiler-explorer/compiler-explorer#4256]
### Describe the bug

GCC static analysis branch is very outdated, `gcc -v` reports:

~~~
gcc version 10.0.0 20200115 (experimental)
~~~

Upstream GCC stopped using their [devel/analyzer](https://gcc.gnu.org/git/?p=gcc.git;a=shortlog;h=refs/heads/devel/analyzer) branch as defined in [gcc-builder/build/build.sh](https://github.com/compiler-explorer/gcc-builder/blob/0eb7b81e754ea0ffb1e7eb0f1d833300f66b2151/build/build.sh#L47). The last commit was Jan 2020, matching the above datestamp. Current GCC static analyzer commits are made directly into trunk.

I can think of two possible solutions:

* Remove CE's **gcc (static analysis)** and add the `analyzer` plugin to [gcc trunk in build.sh](https://github.com/compiler-explorer/gcc-builder/blob/0eb7b81e754ea0ffb1e7eb0f1d833300f66b2151/build/build.sh#L62), reflecting the upstream status that the static analysis is not so experimental anymore
* Update CE's **gcc (static analysis)** to track trunk (keeping the **analyzer** plugin enabled)

### Steps to reproduce

Compile C or C++ with **x86-64 gcc (static analysis)** branch.

### Expected behavior

Compiler is latest nightly code, like the **x86-64 gcc (trunk)** build.

Instead, very old build from Jan 2020 is used.

### Reproduction link

https://godbolt.org/z/q3ovchq1a

### Screenshots

Not applicable

**Comment by dkm** [comment]
True that the branch is not live anymore, but I'm not sure there's anything to do on `master` to use `-fanalyzer`. I believe it's now part of gcc and development is done in `master` branch.

See https://godbolt.org/z/eETcbffc6
which is part of a fresh (beg november) test case added by @davidmalcolm .

Maybe we should simply hide the old compiler (old links will still work, but we won't show the compiler in the drop down menu).

What do you think? Or is there an `analyzer` plugin we need to enable that I'm not aware of?

**Comment by superjamie** [comment]
Thanks for the quick response!

Very strange. I've got a test case which doesn't trip the analyzer on Compiler Explorer no matter what I try, but apparently it does work for the upstream developers:

* [GCC Bug 107566 - array out of bounds not detected](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107566)
* <https://godbolt.org/z/dx96qbcqs>

You are right though, if I put one of upstream's test cases into CE's **gcc (trunk)**, it does correctly trip the analyzer:

* [gcc/testsuite/gcc.dg/analyzer/out-of-bounds-1.c](https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=gcc/testsuite/gcc.dg/analyzer/out-of-bounds-1.c;h=9f3cda6e02b9dc3a0af17b7ae315aa2394347fef;hb=7e3b45befdbbf1a1f9ff728fa2bac31b4756907c)
* <https://godbolt.org/z/1xWxjedM7>

I am not sure why my minimal reproducer doesn't work 🤔

Anyway, I think your suggestion is best:

> Maybe we should simply hide the old compiler (old links will still work, but we won't show the compiler in the drop down menu).

That way CE users won't accidentally use an old outdated version of GCC when trying to use `-fanalyzer`.

**Comment by davidmalcolm** [comment]
As it's turned out, all of my development work on the gcc analyzer has been in trunk aka master.

I haven't touched that old branch in years, so at this point its presence in the menu is confusing to Compiler Explorer users.  Sorry about that.

My preference would be for that old compiler option to be either deleted altogether, or for it to be hidden.

**Comment by dkm** [comment]
Thanks, I'll proceed with the hiding (we never delete any compiler as we want all existing links to continue working as long as compiler explorer exists :)
