### ISSUE TITLE
[BUG]: Directives-Filter removes .half and .dword directives

### ISSUE THREAD

**Issue by Bueddl** [compiler-explorer/compiler-explorer#4275]
### Describe the bug

Usually directives such as .byte, .word, etc. are not filtered, even if the directives-filter is set. This seems not to work for .half and .dword directives as created by rv64gc for example.

See this example: https://godbolt.org/z/dr8Pdc3s7

For the input:
```
extern const char test_char = 42;
extern const short test_short = 42;
extern const int test_int = 42;
extern const long test_long = 42;
extern const long long test_longlong = 42;
```

the generated output with the directives filter enabled on rv64gc gcc12.2.0 is:
```
test_char:
        .byte   42
test_short:
test_int:
        .word   42
test_long:
test_longlong:
```

### Steps to reproduce

1. Visit godbolt.org
2. Select C++
3. Select RISC-V rv64 gcc 12.2.0 or loongarch64 gcc 12.2.0 for example (or any other compiler that generated those directives)
4. Paste into the source window: `extern const int test_int = 42;`
5. Make sure the directives filter is enabled
6. View the generated and filtered assembly output

### Expected behavior

Directives such as .dword and .half are not filtered in alignment with similar directives such as .word, .byte, etc.

### Reproduction link

https://godbolt.org/z/dr8Pdc3s7

### Screenshots

Not applicable

**Comment by Bueddl** [comment]
I suspect that there are just a few values missing in the `dataDefn` array: https://github.com/compiler-explorer/compiler-explorer/blob/17a56af6961bb72895459a47c7b176f929887d3d/lib/parsers/asm-parser.ts#L86

**Comment by partouf** [comment]
fix is now live
