### ISSUE TITLE
[COMPILER REQUEST]: KVX 4.10

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#4280]
### Compiler name

KVX 4.10

### Compiler version

4.10

### Compiler language

*

### Compiler homepage

https://github.com/kalray/build-scripts/releases/tag/v4.10.0

### Motivation

https://github.com/kalray/build-scripts/releases/tag/v4.10.0

**Comment by dkm** [comment]
cc @XavierRaynaud @fallen

**Comment by dkm** [comment]
- [ ] infra change
- [ ] compiler installed
- [ ] config change

**Comment by XavierRaynaud** [comment]
Many thanks @dkm

**Comment by fallen** [comment]
Awesome, thanks :)
