### ISSUE TITLE
Add ninja support to IDE CMake

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#4285]
Even though you can use custom commands and the likes to get modules to work, there are a lot of bugs still in modules in both gcc and clang. And the compilers are not consistent in their way of compiling modules, std headers and calling code.

        The official CMake integration is not there yet, but it's hinting that you might have to use ninja as a build system.
        We currently use Make, so we might have to change that to ninja once Cmake is upgraded.

_Originally posted by @partouf in https://github.com/compiler-explorer/compiler-explorer/issues/1892#issuecomment-927326464_

**Comment by mpusz** [comment]
CMake is upgraded now :-)
Do you know how to use Ninja in CE? I compile the code with -GNinja but always get:

```
Step make returned: 2
make: *** No targets specified and no makefile found.  Stop.
```

> We currently use Make, so we might have to change that to ninja once Cmake is upgraded.

Actually, why do you use make directly? I would recommend calling build via CMake for CMake projects. With that, no matter which CMake generator will be used by the user, you can always easily call a build step for it.

Here is a generic workflow to use CMake for all steps of the build:
```
cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/.local
cmake --build . --config Release
ctest -VV -C Release
cmake --install . --config Release --strip
```

**Comment by mpusz** [comment]
Here is my test project for modules: https://godbolt.org/z/ex5b51PYY.

**Comment by partouf** [comment]
I did prepare it to work with ninja (and also use --build), but still have to merge and test it (https://github.com/compiler-explorer/compiler-explorer/pull/4287/files)
Probably will happen soon

**Comment by partouf** [comment]
> Here is my test project for modules: https://godbolt.org/z/ex5b51PYY.

Works on staging at the moment, but lots of errors;
https://godbolt.org/staging/z/ex5b51PYY

**Comment by partouf** [comment]
Ninja is now supported, changes are live. Needs passing -GNinja, make is still the default

**Comment by partouf** [comment]
Nope, sorry. We need to do some research and microsoft communication for that

**Comment by mpusz** [comment]
> Nope, sorry. We need to do some research and microsoft communication for that

It seems that MSVC is the only compiler that correctly supports modules for now. I hoped that the patches for modules mentioned below are already on the GCC mainline but it seems they are not.

![image](https://user-images.githubusercontent.com/506260/211921738-367f7a00-d83e-48c5-8e14-5540c2055864.png)

It seems that we either have to provide this patched gcc somehow or wait for the changes on the GCC trunk to happen.

**Comment by mpusz** [comment]
Anyway, the CE environment is now ready to play with modules. Thanks!!!
We just have to wait for compilers to catch up... 😉

**Comment by partouf** [comment]
we might be able to build the patched gcc, but im all out of steam at the moment, maybe @mattgodbolt can arrange the magic
