### ISSUE TITLE
[BUG]: `opt-decoration` css class not visible in dark/dark+ theme

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#4300]
### Describe the bug

In clang optimization pane, the opt-decorations on the left sidebar are visible only in light theme - see screenshots below.
I _suspect_ this came with #4203 by @RubenRBS , but might be completely off.

### Steps to reproduce

1. In any clang compiler pane add 'Optimization'
2. Under 'More'/'Settings' toggle dark/light themes.

### Expected behavior

opt-decorations should be visible, doesn't matter too much with what colors

### Reproduction link

https://godbolt.org/z/zEc54behz

### Screenshots

![image](https://user-images.githubusercontent.com/73080/202552315-7cc7d5e3-3488-4fce-a085-fd6a339f0aea.png)

![image](https://user-images.githubusercontent.com/73080/202552339-51408d0e-506b-462e-886e-36803879e2fc.png)

**Comment by jeremy-rifkin** [comment]
Good spot!

**Comment by jeremy-rifkin** [comment]
I can't actually reproduce this (tested all color schemes on both firefox and chrome)
![image](https://user-images.githubusercontent.com/51220084/202586462-fd314daa-d4fd-499b-b852-6ac44bab0697.png)

**Comment by OfekShilon** [comment]
> I can't actually reproduce this (tested all color schemes on both firefox and chrome) ![image](https://user-images.githubusercontent.com/51220084/202586462-fd314daa-d4fd-499b-b852-6ac44bab0697.png)

That's weird. I now checked on win11-chrome, win11-edge, ubuntu-firefox, and macos-safari. All missing opt-decoration display in dark mode.

**Comment by OfekShilon** [comment]
I now tested a few browsers on https://www.browserstack.com/ (just VMs with browsers, short free trial available). opt-decoration indeed missing in dark mode:
![image](https://user-images.githubusercontent.com/73080/202674138-30101d44-3381-49a5-8a36-c6d98566acb6.png)
![image](https://user-images.githubusercontent.com/73080/202674170-801bd142-7f59-4fc6-9b33-b3aa923aa595.png)

**Comment by OfekShilon** [comment]
> What browsers do you see them not showing up in?

The screenshots are from chrome and safari

**Comment by jeremy-rifkin** [comment]
Thank you

**Comment by partouf** [comment]
doesn't work for me neither in chrome
