### ISSUE TITLE
[BUG]: zig lang crypto execution crash

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#4316]
### Describe the bug

Attached crypto usage sometimes crashes with SIGILL

### Steps to reproduce

1. visit link
2. run a few times
3. observe crash

### Expected behavior

No crashes. Maybe a zig thing (-mcpu baseline "fixes") but maybe our sandbox upsets CPU feature detection?

### Reproduction link

https://godbolt.org/z/aKfE9ncna

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment]
Logged into a box where it happened:

```
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonst
                                 op_tsc cpuid extd_apicid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm 
                                 sse4a misalignsse 3dnowprefetch topoext ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr
                                  rdpru wbnoinvd arat npt nrip_save rdpid
```

though I am pretty sure I've seen it happen on other ones too (this was a c5a.large)

**Comment by partouf** [comment]
Maybe similar thing that happened with https://github.com/compiler-explorer/compiler-explorer/issues/3936

Zig always targets "native" unless you specify it. And execution might happen on a different node.

Perhaps requires mentioning in a warning/alert of some kind?

**Comment by mattgodbolt** [comment]
> Zig always targets "native" unless you specify it. And execution might happen on a different node.

Of courseee!!!

You're a genius @partouf !

**Comment by mattgodbolt** [comment]
It's exactly that: good spot @partouf

**Comment by mattgodbolt** [comment]
A warning might be the way to go. The executable was cached on one node and then run on another (which explains some things about how it was intermittant I think?)
