### ISSUE TITLE
[BUG]: `Result: [Object object]` in log for wine

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#4330]
### Describe the bug

exec.ts outputs a `Result [Object object]` at startup

### Steps to reproduce

run with wine
look at log output

### Expected behavior

something useful :)

Comes from:
https://github.com/compiler-explorer/compiler-explorer/blob/c363d1a07d0cffb05601ad914c3b557fd2be5257/lib/exec.ts#L356
```ts
        logger.info(`Killing any pre-existing wine-server`);
        let result = await child_process.exec(`${server} -k || true`, {env: env});
        logger.info(`Result: ${result}`);
        logger.info(`Waiting for any pre-existing server to stop...`);
        result = await child_process.exec(`${server} -w`, {env: env});
        logger.info(`Result: ${result}`);
```

the two log lines here...either json stringify...or remove...

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by guoci** [comment]
The 2 log lines seem irrelevant, `child_process.exec` calls are async but do not return a promise, so the `await` keyword does not block. The `await` keywords are removed in https://github.com/compiler-explorer/compiler-explorer/commit/910d69f233414ebfb0b680e012f44ced14505016.
