### ISSUE TITLE
[BUG]: Ordering of operands in SIMD instructions

### ISSUE THREAD

**Issue by btzy** [compiler-explorer/compiler-explorer#4339]
### Describe the bug

SIMD inline assembly in gcc x86-64 have arguments in the wrong order, even though using the intrinsic (e.g. `_mm256_cmpgt_epi32`) does the correct thing.

For example, try the following code the compiler explorer ([link](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:1,endLineNumber:9,positionColumn:1,positionLineNumber:9,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:'%23include+%3Cx86intrin.h%3E%0A__m256i+f(__m256i+a,+__m256i+b)+%7B%0A++++__m256i+res%3B%0A++++//+asm(%22vpcmpgtd+%251,+%252,+%250%22+:+%22%3Dx%22(res)+:+%22x%22(a),+%22x%22(b))%3B%0A++++asm(%22vpcmpgtd+%252,+%251,+%250%22+:+%22%3Dx%22(res)+:+%22x%22(a),+%22x%22(b))%3B%0A++++//+res+%3D+_mm256_cmpgt_epi32(a,+b)%3B%0A++++return+res%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g122,deviceViewOpen:'1',filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-std%3Dc%2B%2B20+-march%3Dhaswell+-O3',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+12.2+(Editor+%231)',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)):
```
#include <x86intrin.h>
__m256i f(__m256i a, __m256i b) {
    __m256i res;
    // asm("vpcmpgtd %1, %2, %0" : "=x"(res) : "x"(a), "x"(b));
    asm("vpcmpgtd %2, %1, %0" : "=x"(res) : "x"(a), "x"(b));
    // res = _mm256_cmpgt_epi32(a, b);
    return res;
}
```

Look at the assembler output.  Then toggle the assembler syntax between Intel and AT&T.  Observe that the arguments remain in the same positions.  Try the other commented out asm line, and the arguments still remain whichever syntax is selected.  However, if we try the `_mm256_cmpgt_epi32` line, we will notice that the argument order changes depending on the chosen assembler syntax.

Note that the correct equivalent inline assembly for the intrinsic is the second option, i.e. `asm("vpcmpgtd %2, %1, %0" : "=x"(res) : "x"(a), "x"(b));`.

### Steps to reproduce

1. Click the link in the bug description above.
2. Toggle the "Intel asm syntax" option, and observe that the argument order doesn't change.
3. Change the uncommented line to the one with the intrinsic (i.e. `_mm256_cmpgt_epi32`), and observe that the argument order changes when we toggle the "Intel asm syntax" option.

### Expected behavior

The argument order should change for inline assembly as well.

### Reproduction link

https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:1,endLineNumber:9,positionColumn:1,positionLineNumber:9,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:'%23include+%3Cx86intrin.h%3E%0A__m256i+f(__m256i+a,+__m256i+b)+%7B%0A++++__m256i+res%3B%0A++++//+asm(%22vpcmpgtd+%251,+%252,+%250%22+:+%22%3Dx%22(res)+:+%22x%22(a),+%22x%22(b))%3B%0A++++asm(%22vpcmpgtd+%252,+%251,+%250%22+:+%22%3Dx%22(res)+:+%22x%22(a),+%22x%22(b))%3B%0A++++//+res+%3D+_mm256_cmpgt_epi32(a,+b)%3B%0A++++return+res%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g122,deviceViewOpen:'1',filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-std%3Dc%2B%2B20+-march%3Dhaswell+-O3',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+12.2+(Editor+%231)',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment]
This is a "feature" of GCC - GCC itself does not interpret the code you put in the `asm` block other than to do text substitution. (e.g. look at https://godbolt.org/z/93jhGzczr ) - GCC will put whatever text you put in the `asm` block directly in the output. It doesn't use which assembly you've chosen to output for its own generated code.

Clang is different and actually parses the asm you write in its `asm` blocks, but sadly this is just how GCC works.

**Comment by mattgodbolt** [comment]
For what it's worth the debate rages on in the GCC community itself, with posts as recent as earlier today: https://gcc.gnu.org/pipermail/gcc/2022-November/240103.html

**Comment by btzy** [comment]
Thanks for the quick reply.  I only just realised (after you have me that link) that `-masm=intel` actually changes the behaviour of the resultant binary, so the output of your compiler explorer is absolutely correct.
