### ISSUE TITLE
[BUG]: Rust Nightly Compiler has not updated since 2022-10-01

### ISSUE THREAD

**Issue by scottmcm** [compiler-explorer/compiler-explorer#4345]
### Describe the bug

Somehow CE has stable Rust 1.65 (dated 2022-11-02), but the nightly is *much* older, still 
```
rustc 1.66.0-nightly (57f097ea2 2022-10-01)
```

The current nightly on [Rust's playground](https://play.rust-lang.org/) is
```
1.67.0-nightly (2022-11-25 8681d4cffcd23bbe6199)
```

So it appears that the version in CE as failing to update for some reason.

### Steps to reproduce

1. Visit https://rust.godbolt.org/
2. Change the compiler to "rustc nightly"
3. Click the ℹ for details about the compiler

Actual: nightly is from 2022-10-01

### Expected behavior

Nightly is from some point in the past week.

### Reproduction link

https://rust.godbolt.org/z/e67vrnoqh

### Screenshots

![image](https://user-images.githubusercontent.com/18526288/204077930-0dec1720-d4fa-485a-929b-a73755287def.png)

**Comment by partouf** [comment]
The rust nightly installer currently errors out with

```
install: installing component '-json-preview'
install: error: manifest for -json-preview does not exist at /opt/compiler-explorer/staging/37e00ea8-1915-4b3f-bad3-1344ddacef55/__temp_install__/-json-preview/manifest.in. see logs at '/opt/compiler-explorer/staging/37e00ea8-1915-4b3f-bad3-1344ddacef55/rust-nightly/lib/rustlib/install.log'
2022-11-26 12:39:35,036 lib.ce_install  INFO     compilers/rust/newer/nightly nightly failed to install: Command '['./install.sh', '--prefix=/opt/compiler-explorer/staging/37e00ea8-1915-4b3f-bad3-1344ddacef55/rust-nightly', '--verbose', '--without=rust-docs']' returned non-zero exit status 1.
```

Will check the logging

**Comment by partouf** [comment]
It appears there's a bug in the installer when passing `--without=rust-docs`
I removed it for now

The nightly should be up-to-date tomorrow

**Comment by partouf** [comment]
seems up to date
