### ISSUE TITLE
[BUG]: pragma once warning if include happens through URL

### ISSUE THREAD

**Issue by Viatorus** [compiler-explorer/compiler-explorer#4349]
### Describe the bug

Using a URL as include path, like

`#include "https://viatorus.github.io/cpp-github-project/cpprj.hpp"`

Raises ` #pragma once in main file` for most compilers.

### Steps to reproduce

https://gcc.godbolt.org/z/v5zh8jMMv

### Expected behavior

Since it is a "include", the file should be included as an header and not copy-paste into the source.

**Comment by mattgodbolt** [comment]
Compilers don't really support `#include <url-here>`, so we have to do what we can to support it. We have a number of issues relating to this hack I put in once for a friend...I'm not sure how best to fix it.

**Comment by steve02081504** [comment]
> Compilers don't really support `#include <url-here>`, so we have to do what we can to support it. We have a number of issues relating to this hack I put in once for a friend...I'm not sure how best to fix it.

Can we handle this hack on the server side (downloading the file pointed to by the url and caching it until the content expires and replacing the url with the server-side cache path) rather than on the client side (pulling the file content and replacing it in the code submitted to the server)?

**Comment by mattgodbolt** [comment]
We _can_. But it's a lot of work to do, and it potentially turns the site into a DoS attack vector. See:

- #3929 
- #2142

**Comment by partouf** [comment]
This shouldn't happen anymore because url includes are sent as separate files now. (This while keeping the downloading on the client's side and not exposing ourselves to various issues.)
