### ISSUE TITLE
[BUG]: ASM highlighting doesn't recognize ` as valid method signature in callsites

### ISSUE THREAD

**Issue by hez2010** [compiler-explorer/compiler-explorer#4350]
### Describe the bug

The editor doesn't recognize \` as valid method signature in callsites, so a character \` will mess up the rest ASM highlighting.

### Steps to reproduce

See https://godbolt.org/z/Ev8Eno819

### Expected behavior

The highlighting should not be messed up with ` at the method callsites.

### Reproduction link

https://godbolt.org/z/Ev8Eno819

### Screenshots

![image](https://user-images.githubusercontent.com/14960345/204120478-a0183f07-8f58-4c06-a129-a1047bc71298.png)

**Comment by jeremy-rifkin** [comment]
Thanks for the report, we'll have to update the asm syntax grammar here https://github.com/compiler-explorer/compiler-explorer/blob/main/static/modes/asm-mode.ts to accommodate this new use of `

**Comment by mattgodbolt** [comment]
Made tricky by the fact that (according to my notes...) ` is sometimes used by MSVC to quote things. ( https://microsoft.github.io/monaco-editor/monarch.html can be used to test stuff out: paste the `return {...}` bit from asm-mode.ts in to it and then you can play about with it. Having a look now...

**Comment by mattgodbolt** [comment]
I got it

**Comment by mattgodbolt** [comment]
will roll out shortly as part of the .NET execution push
