### ISSUE TITLE
[BUG]: Syntax highlighting of (multi)character literals is broken

### ISSUE THREAD

**Issue by Levev** [compiler-explorer/compiler-explorer#4355]
### Describe the bug

I was fooling around in godbolt when I noticed that `'\0'` and `'\n'` are being highlighted differently. That gave me the idea to look into multicharacter literals as well, and turns out that the syntax highlighting for them is broken.
I *think* the contents of multicharacter literals are treated similarly as normal code, because if a keyword is present in one, then they get highlighted as keywords. This applies to float/integer literals as well; they are highlighted as numbers. E.G. `'int'` gets highlighted as blue and `'123'` gets highlighted as green (except for the apostrophes)

keywords I tested:
- int
- long
- char

if we care about multicharacter literals longer than four characters (should work on compilers supporting 8 byte-long ints):
- short
- static
- const
- sizeof
- signed
- unsigned

### Steps to reproduce

1. visit godbolt.org
2. select C or C++ mode(these are the ones I tested) with any compiler
3. paste the following code snippet: 
```c
int multichar[] = {
    'int',
    'long',
    'char',
    '123',
    '\0'
};
```

### Expected behavior

Ideally `'\0'` should be highlighted just like `'\n'` or `'\r'` is. 
In case of multicharacter literals, they could either be highlighted as normal character literals, or perhaps they could be highlighted with a different color to account for the difference between strings / multicharacter literals

### Reproduction link

https://godbolt.org/z/8bjz91esq

### Screenshots

![image](https://user-images.githubusercontent.com/72160179/204194342-f3625779-20d9-4457-9973-bf1ae48c1ca7.png)

### Operating System

Manjaro Linux 5.15.76-1-MANJARO

### Browser version

Firefox 106.0.4 64-bit

**Comment by jeremy-rifkin** [comment]
Thank you for the bug report! We use monaco and it looks like this issue is present in upstream monaco too 
![image](https://user-images.githubusercontent.com/51220084/204201254-b49f3518-f7de-44ec-97cb-dec7950bff7d.png)

It'd be worthwhile to report the issue at https://github.com/microsoft/monaco-editor as well.

We're happy to patch over upstream monaco if needed, our patches live at https://github.com/compiler-explorer/compiler-explorer/blob/main/static/modes/cppp-mode.ts.

 Interestingly the highlighting looks fine in vscode, I'm not sure what vscode is doing different.

**Comment by RubenRBS** [comment]
Submited the issue for `\0` upstream as that seems the easiest for them to fix, but feel free to open another one requesting multicharacter literal support too!

**Comment by Levev** [comment]
Sure, going to look into it soon!

**Comment by RubenRBS** [comment]
Hi! The PR fixing this was just merged upstream yesterday (Sorry about the delay!) so it should be there next time we bump our dependencies
