### ISSUE TITLE
[BUG]: Pahole corrupted output

### ISSUE THREAD

**Issue by madhur4127** [compiler-explorer/compiler-explorer#4405]
### Describe the bug

Pahole output is full of lines like:
```
	/* Force padding: */
	int                        :32;
	int                        :32;
	int                        :32;
```
which feels like a wrong output because that much padding would require a super computer to run.

### Steps to reproduce

[Use this link](https://compiler-explorer.com/z/seo9TWfnY)

### Expected behavior

The millions of `/* Force padding */` lines shouldn't exist.

### Reproduction link

https://compiler-explorer.com/z/seo9TWfnY

**Comment by partouf** [comment]
ah yes https://compiler-explorer.com/z/8x53o13Kc

**Comment by madhur4127** [comment]
I tried to fix it here: https://github.com/compiler-explorer/infra/pull/899
