### ISSUE TITLE
[COMPILER REQUEST]: LLVM and GCC BPF

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#4408]
### Compiler name

GCC and LLVM

### Compiler version

latest 

### Compiler language

all of them :)

### Compiler homepage

-

### Motivation

As discussed with , BPF support in CE would be nice.
- [x] first step is having BPF supported in crosstool-ng https://github.com/crosstool-ng/crosstool-ng/pull/1870
- [x] then setup our builders to build an x-gcc for bpf
- [x] update compilers accordingly (what languages?) -> C/C++
- [x] see if monaco has any support for syntax highlighting BPF (-> there's none)

**Comment by dkm** [comment]
(side note: bpf already enabled in our llvm builds, so one must use `--target bpf` to use it. We won't do anything more on that front.

**Comment by dkm** [comment]
Will build it in nightly as BPF is still under dev and previous GCC releases are not representative.

**Comment by borkmann** [comment]
@dkm thanks so much for adding this, this is awesome!

I see it can be used already online https://godbolt.org/z/hWEW5jePs .

Is there a way you could also add a dedicated section for `BPF clang trunk`?

That would be amazing!

Thanks so much,
Daniel

**Comment by dkm** [comment]
Hello @borkmann 
Happy to see this is useful :)
I'm looking at adding them now

**Comment by borkmann** [comment]
> Hello @borkmann Happy to see this is useful :) I'm looking at adding them now

Super awesome, thanks so much!

**Comment by dkm** [comment]
So, we are currently using gcc to link (what we call "compile to binary") and we fail to have clang pick the gcc bpf toolchain. See https://github.com/compiler-explorer/compiler-explorer/pull/4556/commits/cc848d366c9c555f3dd7d6a2e2e1b8f42a0f16e1 where we use:
`--gcc-toolchain=/opt/compiler-explorer/bpf/gcc-trunk/bpf-unknown-none/` . The compiler warns that it's unused during compilation (expected) but still uses `/usr/bin/gcc` to link (and fails).

So I've disabled binary support until we have a fix, sorry.

**Comment by dkm** [comment]
Clang compiler are now live :rocket: (with "compile to binary" disabled)

**Comment by dkm** [comment]
I'll open another issue for having binary support for clang compilers

**Comment by borkmann** [comment]
> Clang compiler are now live rocket (with "compile to binary" disabled)

Awesome! Thanks so much for all your work on this! I'll link this to ebpf.io as well.

**Comment by dkm** [comment]
You're welcome, don't hesitate to ask if you think of something that could be useful, we are here to help :)

**Comment by borkmann** [comment]
> You're welcome, don't hesitate to ask if you think of something that could be useful, we are here to help :)

Thanks a lot! My current wish list if anyone has cycles to work on this would be (Cc @yonghong-song / @dafaust for additional input):

1) Pick a choice (LLVM BPF asm syntax vs gcc BPF asm syntax) to compare llvm/gcc compilation result with same disassembler

2) BTF viewer (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/bpf/btf.rst)

Perhaps this could be added to "+ Add new" menu as an output option.

Both gcc and clang support generating BTF, this can be dumped and introspected, for example:
```
$ cat t.c
struct t {
  int a:2;
  int b:3;
  int c:2;
} g;
$ gcc -c -O2 -g t.c
$ pahole -JV t.o
File t.o:
[1] STRUCT t kind_flag=1 size=4 vlen=3
        a type_id=2 bitfield_size=2 bits_offset=0
        b type_id=2 bitfield_size=3 bits_offset=2
        c type_id=2 bitfield_size=2 bits_offset=5
[2] INT int size=4 bit_offset=0 nr_bits=32 encoding=SIGNED
```
(For pahole, also latest trunk would be recommended.)

This would help to compare generated BTF from both compilers.

**Comment by dkm** [comment]
Small headsup, linking is still disabled, but you can use our new "compile to binary object" to have clang's output `objdump`ed by `llvm-objdump`: https://godbolt.org/z/xWxMKd4T3
