### ISSUE TITLE
Super long C++ symbols in the CFG viewer

### ISSUE THREAD

**Issue by jeremy-rifkin** [compiler-explorer/compiler-explorer#4411]
https://godbolt.org/z/G1zx49h7v

![image](https://user-images.githubusercontent.com/51220084/206606891-2a53ceda-f641-4f87-84a3-8060e9933137.png)

Simplifying `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >` to `std::string` and similar simplifications help a lot. But we probably need to truncate or wrap. It could be cool to truncate but allow the user to expand a long symbol if they need to see what it is.

**Comment by Saldivarcher** [comment]
How difficult would it be to also allow a user to export the graph?

**Comment by jeremy-rifkin** [comment]
That's a good question! At the moment it's a mix of svg and html nodes, it might be relatively easy to export everything as an svg. Iirc text can be a bit janky in svg. html2canvas might be an option too and that'd theoretically make it easy for us to save as a png.

**Comment by Saldivarcher** [comment]
I mean personally, I wouldn't mind janky text, if exporting an svg would be easier. Just having the option would be great. 😄

**Comment by jeremy-rifkin** [comment]
Tracking the export graph idea at  #4419
