### ISSUE TITLE
[LIB REQUEST]: stdexec

### ISSUE THREAD

**Issue by BenFrantzDale** [compiler-explorer/compiler-explorer#4418]
### Library name

stdexec from Nvidia

### Library description

Prototype of P2300 and then some: https://github.com/NVIDIA/stdexec

### Library repository

https://github.com/NVIDIA/stdexec

### Motivation

It’s the prototype of C++26 execution. It’d be great to have.

**Comment by partouf** [comment]
we already support this, you can find it under the name std::execution
