### ISSUE TITLE
Export CFG button

### ISSUE THREAD

**Issue by jeremy-rifkin** [compiler-explorer/compiler-explorer#4419]
It'd be awesome to be able to export CFGs as either svgs or pngs

Thanks @Saldivarcher for the suggestion!

**Comment by jeremy-rifkin** [comment]
(Cross posting stuff from the other issue just to keep things consolidated)

> At the moment it's a mix of svg and html nodes, it might be relatively easy to export everything as an svg. Iirc text can be a bit janky in svg. html2canvas might be an option too and that'd theoretically make it easy for us to save as a png.

**Comment by jeremy-rifkin** [comment]
@Saldivarcher Both SVG and PNG exports are live, thanks again for the suggestion!

**Comment by Saldivarcher** [comment]
@jeremy-rifkin just tried it out, it works great! Thanks for your work 😄
