### ISSUE TITLE
[BUG]: Some console outputs not working properly

### ISSUE THREAD

**Issue by steve02081504** [compiler-explorer/compiler-explorer#4420]
### Describe the bug

demo code: https://godbolt.org/z/fKTfK7469
This code works fine when compiled on my computer with Visual Studio Community 17.5.0 Preview 1.0
![图片](https://user-images.githubusercontent.com/31927825/206882897-fad90bb6-de36-4f7a-b050-9c168a62f67e.png)
But when you run it online on godbolt you will not see the output
![图片](https://user-images.githubusercontent.com/31927825/206882908-17ae33bd-2f03-42db-a69d-7320545af206.png)

My initial thought is that this may be because my output lib uses `WriteConsoleW` and `ReadConsoleW` to read and write console handles, and godbolt may disable these api's for security reasons, although I'm not sure.
https://github.com/ELC-lang/ELC/blob/43f1f792f79be401c8a90449c18953424ac16d2a/parts/_share/APIs/streams.hpp

### Steps to reproduce

https://godbolt.org/z/fKTfK7469

### Expected behavior

Output the text normally or tell me how to work around it

### Reproduction link

https://godbolt.org/z/fKTfK7469

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
Hey thanks for the bug report, I think this is expected behavior. `WriteConsole` writes at the current cursor location and in this case there is no console so the call fails: https://godbolt.org/z/YW4ET7fdP (zero means the call failed).

**Comment by steve02081504** [comment]
> Hey thanks for the bug report, I think this is expected behavior. `WriteConsole` writes at the current cursor location and in this case there is no console so the call fails: [godbolt.org/z/YW4ET7fdP](https://godbolt.org/z/YW4ET7fdP) (zero means the call failed).

Thanks for the explanation!
I now know how to fix this...
