### ISSUE TITLE
[BUG]: Multi library include file not found with CUDA compiler

### ISSUE THREAD

**Issue by correaa** [compiler-explorer/compiler-explorer#4425]
### Describe the bug

https://github.com/compiler-explorer/compiler-explorer/pull/4367.
Similar changes worked with C++ and Circle languages.

### Steps to reproduce

1. Visit Godbolt
2. Go to CUDA language
3. Add "B-Multi" library
4. `#include<multi/array.hpp>`

### Expected behavior

The same library works with C++ and Circle compiler.

### Reproduction link

https://godbolt.org/z/zensesY57

### Screenshots

Not applicable

**Comment by RubenRBS** [comment]
Hi! This seems to be an oversight from our side. As GPU support is pretty new, we're still trying to figure out how to handle it, so for now manual version bumping of gpu nodes is needed, and we seem to have forgotten to do so this time around, sorry! Will fix asap

**Comment by correaa** [comment]
The problem now is a different one. Perhaps and incompatibility betweeen CUDA 11.3 and gcc 13 in the installed system.
https://godbolt.org/z/Pqq7T9x4f

**Comment by partouf** [comment]
Clang trunk + gcc trunk is not super stable, but you might be able to use -stdlib=libc++

**Comment by correaa** [comment]
well, i was trying to use nvcc (+ gcc). is it possible at all?

**Comment by partouf** [comment]
> well, i was trying to use nvcc (+ gcc). is it possible at all?

yes, we had a slight issue with nvcc, it should be up again if you refresh your page

**Comment by correaa** [comment]
works now (with nvcc) https://godbolt.org/z/TxrrPW6de

![image](https://user-images.githubusercontent.com/3047763/207431225-4227ce5d-fbe8-4f1f-af42-dbc93cf0277c.png)
