### ISSUE TITLE
Support for "plain" text editor for mobile?

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#443]
https://twitter.com/zygoloid/status/870381517662429184

**Comment by RabsRincon** [comment]
Switching to a textarea on mobile detection is somewhat trivial, but is a simple textarea enough? How "simple" should the mobile version be? Indeed, I don't know if the current default layout would work for phones

**Comment by RabsRincon** [comment]
As mentioned by @Zingan in #469 , this should be toggleable by the user

**Comment by jckarter** [comment]
At least on iOS, a plain text view integrates pretty well with the platform's gestures for text navigation and hardware keyboard support, and IME most attempts to customize behavior with Javascript tend to break or interfere with the OS behavior. I'd appreciate an option to get a totally plain text area.

**Comment by partouf** [comment]
Think we're good on this now
