### ISSUE TITLE
[COMPILER REQUEST]: Add experimental ISPC template branch to list of ISPC compiler versions

### ISSUE THREAD

**Issue by pbrubaker** [compiler-explorer/compiler-explorer#4433]
### Compiler name

ISPC

### Compiler version

Experimental Template Support

### Compiler language

ISPC

### Compiler homepage

http://ispc.github.io

### Motivation

Add a WIP feature branch to the ISPC compiler list based off this PR - https://github.com/ispc/ispc/pull/2393

This PR contains experimental template support for ISPC and would be nice to have it on CE as it matures so people can bang on it!  :)

**Comment by mattgodbolt** [comment]
So in general it's not possible to base off a PR, but off a branch instead (wihch should be equivalent). Will take a look now

**Comment by mattgodbolt** [comment]
So...it seems we don't build our own `ispc`s currently, instead snagging the nightly build from:
```
      url: "https://ci.appveyor.com/api/projects/ispc/ispc/artifacts/build/ispc-trunk-linux.tar.gz?job=Environment: APPVEYOR_BUILD_WORKER_IMAGE=Ubuntu1804, LLVM_VERSION=latest"

```

is there an appveyor for PR builds? if not, this is a little more work as we'll need to set up our own build for this PR.

**Comment by pbrubaker** [comment]
Thanks Matt, I'm looking into it.  Thought you built all the compilers, which would have made this easy!

**Comment by mattgodbolt** [comment]
100% : we can definitely build if you give us instructions,. We have quite a setup for it.

**Comment by mattgodbolt** [comment]
Working on it in compiler-explorer/ispc-builder

**Comment by pbrubaker** [comment]
It's working great!
