### ISSUE TITLE
[REQUEST]: Please disable Ctrl+S to download files in chrome/edge

### ISSUE THREAD

**Issue by reasoning** [compiler-explorer/compiler-explorer#4445]
### Is your feature request related to a problem? Please describe

When using Godbolt i find i have constantly a large set of downloaded files/html source since i habitually press Ctrl+S to save changes (like i do in almost every other programming editor).

Since im sure that i am not alone, and many programmers get used to "saving" before compililng.

Perhaps this would be a simple usability improvement ?

### Describe the solution you'd like

I would like Ctrl+S to simply save changes and re-compile code, as it would in VScode or Visual Studio.

I do not want Ctrl+S to download a copy of the current html source when using Godbolt as a programming editor.

### Describe alternatives you've considered

Not applicable

### Additional context

Not applicable

**Comment by mattgodbolt** [comment]
Please go to "More" and then "Settings", then pick "Keybindings" and change the behaviour there.
![image](https://user-images.githubusercontent.com/633973/208138878-b460afc4-17ef-403b-99fe-4e2ba3de1949.png)

**Comment by mattgodbolt** [comment]
We don't have an option to compile the code as (by default) that happens within 200ms of you stopping typing. If you've disabled that, then alt-enter will compile.

I wasn't aware vscode and visual studio compiled on save.
