### ISSUE TITLE
[LIB REQUEST]: subtle

### ISSUE THREAD

**Issue by jcape** [compiler-explorer/compiler-explorer#4449]
### Library name

subtle

### Library description

Subtle provides pure-rust traits and utilities for constant-time cryptographic implementations (conditional assignment, constant-time comparison, etc.), which would be very nice to have when using the compiler-explorer to evaluate whether a particular code snippet is actually constant-time or is getting branches added to it.

### Library repository

https://crates.io/crates/subtle

### Motivation

Untested, but something like this should work:

```rust
use subtle::{Choice, CtEq};

pub fn main() {
    let foo = b"A string";
    let bar = b"A different string";

    println!("{foo} == {bar}? {}", foo.ct_eq(bar));
}
```

**Comment by RubenRBS** [comment]
Thanks for the request. I'll try to get this done as it should be quick and easy, but installing new Rust libraries is not our most exercised task, so we might run into unexpected complications. We'll keep you updated

**Comment by partouf** [comment]
It should be easy to send in a PR if you have a linux box, the instructions are here https://github.com/compiler-explorer/infra/blob/main/docs/adding_rust_crates.md

**Comment by partouf** [comment]
This is now live.
The example didn't work for me, but this one does: https://godbolt.org/z/MWe9soh7c
