### ISSUE TITLE
[BUG]: API compile request claims it can't find external header file

### ISSUE THREAD

**Issue by skramm** [compiler-explorer/compiler-explorer#4465]
### Describe the bug

On this location:
https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/API.md#post-apicompilercompiler-idcompile---perform-a-compilation-1
it is described how one can use the API to trigger a build.

Indeed, this:
```
curl 'https://godbolt.org/api/compiler/g63/compile?options=-Wall' --data-binary $'#include <iostream> \n int main() {}'
```
works fine (please note the usage of the `$'text\ntext'` to get the required EOL)

However, when attempting to do the same using an external header file, it fails, claiming it can't access the file (although the path is perfectly fine).
For example, this fails:
```
curl 'https://godbolt.org/api/compiler/g63/compile?options=-Wall' --data-binary $'#include "https://raw.githubusercontent.com/skramm/homog2d/master/homog2d.hpp"\nint main() {}'
```
Output:
```
# Compilation provided by Compiler Explorer at https://godbolt.org/
<Compilation failed>
# Compiler exited with result code 1
Standard error:
<source>:1:79: fatal error: https://raw.githubusercontent.com/skramm/homog2d/master/homog2d.hpp: No such file or directory
 #include "https://raw.githubusercontent.com/skramm/homog2d/master/homog2d.hpp"
                                                                               ^
compilation terminated.
```

### Steps to reproduce

Steps to reproduce:
1: run this in a (Linux) shell:
```
curl 'https://godbolt.org/api/compiler/g63/compile?options=-Wall' --data-binary $'#include "https://raw.githubusercontent.com/skramm/homog2d/master/homog2d.hpp"\nint main() {}'
```

Direct link to the file, for conveniency:
https://raw.githubusercontent.com/skramm/homog2d/master/homog2d.hpp

### Expected behavior

* expected result: build starts and curl returns some data
* observed result: curl return a message from CE, claiming it can not access the file.

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Ubuntu 20.04.5

**Comment by skramm** [comment]
Maybe this is inability is done on purpose (which I would understand, as it opens the door for potential abusive usage?).
But if that is the case, then the "API" doc page should clarify this.

**Comment by partouf** [comment]
Inclusion of URL's is a frontend feature, the contents of the url are retrieved by your browser and inlined in the sourcecode. That's why this won't work.

**Comment by RubenRBS** [comment]
But you're right in that we should clarify this in the api, yeah good idea :)

**Comment by skramm** [comment]
Ok, I get it. So not a real bug, more of an undocumented feature ;-)
I'll let you guys close the issue, unless you want to keep it open as a reminder to fix the doc?

**Comment by skramm** [comment]
BTW, any chance the API evolves so it gets possible to trigger a build using a shortlink?
Say, something like GET `/api/shortlinkinfo/<linkid>/build` ?
That would be a great feature!

**Comment by partouf** [comment]
> BTW, any chance the API evolves so it gets possible to trigger a build using a shortlink? Say, something like `GET /api/shortlinkinfo/<linkid>/build` ? That would be a great feature!

It's not likely as that will need to be maintained separately without us actually using it. It would involve simulating what the frontend does on a compile ("compile this as this human intended" - which is not obvious in the encoding of shortlinks - plus needing to implement the download for url includes and all other things we do) and then having to return an array of compilations instead of just 1.

**Comment by skramm** [comment]
Ok, thanks for your answer, makes sense.

**Comment by RubenRBS** [comment]
(Leaving this open until we fix the docs yes)

Thanks for taking the time to file the original report with such detail btw, really appreciated :)
