### ISSUE TITLE
[BUG]: external asm parser doesn't check return code

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#4469]
### Describe the bug

If the external parser fails (e.g. not found) then the error code goes unchecked and the JSON parser tries to parse the error output as JSON, leading to odd issues.

### Steps to reproduce

1. run local with `externalparser=CEAsmParser` and a `externalparser.exe=/not/a/file`
2. compile binary
3. note the error stacktrace is:

```
Internal Compiler Explorer error: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at CEAsmParser.parseAsmExecResult (/home/matthew/dev/ce/compiler-explorer/lib/external-parsers/base.ts:76:59)
    at CEAsmParser.objdumpAndParseAssembly (/home/matthew/dev/ce/compiler-explorer/lib/external-parsers/base.ts:98:21)
```

### Expected behavior

Error message like "external asm parser failed: ...OUTPUT HERE" (e.g. `./dump-and-parse.sh: line 4: /usr/local/bin/asm-parser: No such file or directory` in my case)

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by partouf** [comment]
Should probably crash on startup. I don't think we should fiddle around with runtime error detection or something.

So add a file check here https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/external-parsers/base.ts#L24 I think

**Comment by mattgodbolt** [comment]
I think it's still worth checking. If the process quits for other reasons (SEGV) etc, it's useful to know rather than getting a cryptic JSON parse message.

**Comment by mattgodbolt** [comment]
I'll add the check too for earlier failing.
