### ISSUE TITLE
[BUG] Problem with MOVABS opcode: error fetching documentation

### ISSUE THREAD

**Issue by BossOfTheGym** [compiler-explorer/compiler-explorer#4481]
Greetings!

Here is an issue:
![image](https://user-images.githubusercontent.com/35870598/209079736-eceecd82-5341-474e-969f-08a8b60e679f.png)

It persists even if I reload the page.

**Comment by mattgodbolt** [comment]
Can you explain what you were doing when you saw this error.  I can only guess that you said "show assembly documentation".  We don't have any documentation for the `MOVABS` instruction, and we should probably show a better error. Can you confirm that's what you were doing? Thanks

**Comment by gautam1168** [comment]
I'm able to reproduce it by doing what you mentioned above @mattgodbolt 

Just typed out the code, then opened this menu
![image](https://user-images.githubusercontent.com/9499740/218303623-ec07270b-5726-4191-b0de-c7645d1bfeb5.png)

It gives this error
![image](https://user-images.githubusercontent.com/9499740/218303687-0371b854-c420-4cfc-b5e2-ab8e9f1e51be.png)

The api call is giving 404
![image](https://user-images.githubusercontent.com/9499740/218303711-e2a971f0-8d31-4380-8c69-b0bd88d37472.png)

**Comment by RubenRBS** [comment]
Thanks for taking the time to reproduce the issue! For the x86 asm documentation, we parse https://www.felixcloutier.com/x86/, and it seems like MOVABS is also missing from there, so no wonder we can't find it! In case that you want to try and fix this, my solution would be to either see why it's not there? (Is it maybe there inside another MOV variant and our scripts are not picking it up?) or just hardcode adding it in the scripts at [etc/scripts/disasams](https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/scripts/docenizers/docenizer-amd64.py), which might be faster and easier. (Or don't! No rush to do anything else than what you have already done, either way it's much appreciated!)

**Comment by gautam1168** [comment]
I am not advanced enough with assembly programming to understand exactly why this mnemonic is missing in the intel manual where the felixcoutier website gets the data from. However, this instruction seems to have been an issue for other people as well. And in those places they are saying its just the `MOV` instruction but with AT&T syntax for 64bit values (I don't know what that means). Here are a couple threads saying that. 

https://github.com/cirosantilli/x86-assembly-cheat/blob/master/x86-64/movabs.asm
https://github.com/capstone-engine/capstone/issues/461

I can make a PR to add a hardcoded line but I don't know if these are reliable sources.

**Comment by partouf** [comment]
You can find the intel documentation (that felix uses) here https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html

The relevant part of the documentation is Volume 2 "Intel® 64 and IA-32 Architectures Software Developer's Manual Combined Volumes 2A, 2B, 2C, and  2D: Instruction Set Reference, A- Z"

But you won't find MOVABS in there, it's just a made up instruction that gcc uses. (Though I think it's a "bug" that they also use it during Intel syntax)

I don't really think there's anything we can do about this.

Maybe it can be made to just send it to the MOV documentation. (if not found and instruction.includes('MOV') then etc)

**Comment by matsjla** [comment]
If this happens to be a gcc but then I don't think we should go out of our way to support it

**Comment by gautam1168** [comment]
I found this in llvm:
![image](https://user-images.githubusercontent.com/9499740/220988468-f6197a1a-0cd4-4e44-bf69-a9a162d1bdbf.png)

https://github.com/llvm-mirror/llvm/blob/master/lib/Target/X86/X86InstrInfo.td

This file also says things like: 
```
// Match 'movq <largeimm>, <reg>' as an alias for movabsq.
def : InstAlias<"mov{q}\t{$imm, $reg|$reg, $imm}", (MOV64ri GR64:$reg, i64imm:$imm), 0>;
```

I do not really understand what this means. Im guessing that it is saying that `movq` is the actual instruction and `movabs` is an alias defined by the compiler/disassembler?

**Comment by jeremy-rifkin** [comment]
> LLVM is also emitting `movabs` with intel syntax: https://c.godbolt.org/z/q3W4osE5M
> 
> So not really sure about the "GCC bug" here...

objdump also seems to be emitting `movabs`

Because this is such a common issue / question and evidently the alias is widespread I think it would be reasonable for us to special-case it

**Comment by jeremy-rifkin** [comment]
For anyone looking to implement this:
The x86 assembly doc data is at https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/asm-docs/generated/asm-docs-amd64.ts
Which is generated by a python script located at https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/scripts/docenizers/docenizer-amd64.py
