### ISSUE TITLE
[BUG]: Closing brace not unindented

### ISSUE THREAD

**Issue by davidstone** [compiler-explorer/compiler-explorer#4485]
### Describe the bug

In older versions of compiler explorer, with the "Automatically indent code" setting turned on, the closing brace would be automatically unindented. This behavior seems to have changed at some point probably this month?

### Steps to reproduce

1. Visit godbolt.org
2. Type `void f() {`
3. Enter a newline
4. Type `}`

### Expected behavior

The closing `}` has leading whitespace removed

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Arch Linux

### Browser version

Firefox 108.0.1

**Comment by OfekShilon** [comment]
The behavior today seems to match the expected, with or without 'insert matching brackets' checked.
