### ISSUE TITLE
[BUG]: Text rendered one character per line until editor window is resized when word wrapping is enabled

### ISSUE THREAD

**Issue by davidstone** [compiler-explorer/compiler-explorer#4486]
### Describe the bug

When first visiting godbolt.org, the "saved" text and any next text I type is rendered as a single character per line, rather than wrapping properly. Changing any of the display-related settings (for instance, font or color scheme) or resizing either the window or the editor pane causes text to be displayed properly. Refreshing the page causes the issue to reappear.

The issue appears for me under both Firefox and Chromium. It began occurring approximately 2-3 months ago, but possibly longer.

### Steps to reproduce

1. Visit godbolt.org
2. Turn on word wrap in settings
3. Refresh page

### Expected behavior

Text appears wrapped properly

### Reproduction link

Not applicable

### Screenshots

![image](https://user-images.githubusercontent.com/1459008/209248774-7704f271-5be0-4c34-9ba9-5b49d6045a87.png)

### Operating System

Arch Linux

**Comment by mattgodbolt** [comment]
Fantastic! Able to repro here too. We've seen this crop up from time to time. Thanks for the screenshot and the clear instructions

**Comment by partouf** [comment]
mentioned in discord, but actual serious suggestion; this feature should be deprecated, it cannot possibly be maintained due to the volatility of both user input and the monaco editor

**Comment by davidstone** [comment]
> mentioned in discord, but actual serious suggestion; this feature should be deprecated, it cannot possibly be maintained due to the volatility of both user input and the monaco editor

I hope we don't take that route. I can live without word wrap in the input box because most of my lines are short enough to where it doesn't matter. It would be a serious degradation of my experience if the compiler output windows couldn't have word wrap turned on. I suspect the work involved in solving it for compiler output is the same as solving it for user input, though.

**Comment by partouf** [comment]
> > mentioned in discord, but actual serious suggestion; this feature should be deprecated, it cannot possibly be maintained due to the volatility of both user input and the monaco editor
> 
> I hope we don't take that route. I can live without word wrap in the input box because most of my lines are short enough to where it doesn't matter. It would be a serious degradation of my experience if the compiler output windows couldn't have word wrap turned on. I suspect the work involved in solving it for compiler output is the same as solving it for user input, though.

No compiler output should be fine, that works totally differently. But that setting should never be applied to the source editor.
