### ISSUE TITLE
[BUG]: Site theme "Dark+" flashes white screen before turning dark

### ISSUE THREAD

**Issue by davidstone** [compiler-explorer/compiler-explorer#4487]
### Describe the bug

When first visiting / refreshing godbolt.org, if I have the site theme set to "Dark+", I'm treated to a brief (0.5 seconds or so? However long it takes to fully load) blinding white page before the theme seems to kick in and turn the page dark. Setting the site theme to "Dark" does not have this problem.

This occurs under both Firefox and Chromium.

### Steps to reproduce

1. Visit godbolt.org
2. Set site theme to "Dark+"
3. Refresh

### Expected behavior

The page initially loads dark, like the "Dark" theme does

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Arch Linux

**Comment by mattgodbolt** [comment]
CC @RubenRBS or @apmorton  I think who might know what this is (I think one of them did the workaround to get it "dark enough" until the site loads up proper)
