### ISSUE TITLE
[REQUEST]: pipeline starting from LLVM IR to LLC as compiler and with an intermediate LLVM Opt step

### ISSUE THREAD

**Issue by SixthDot** [compiler-explorer/compiler-explorer#4492]
From the LLVM IR output I occasionally would like to have the output for LLVM Opt as LLVM IR then this intermediate output passed to LLC, which does not seem to be possible at the moment.

**Comment by jeremy-rifkin** [comment]
Thank you for the request! Does the LLVM Opt Pipeline fit the bill? <https://godbolt.org/z/4Txn8YWTP> clang here should essentially be doing the IR -> opt -> llc pipeline.

**Comment by SixthDot** [comment]
Yes.

**Comment by jeremy-rifkin** [comment]
Excellent, merry christmas and happy holidays!
