### ISSUE TITLE
[BUG]: `fmt` library doesn't work with C++ x64 msvc compiler

### ISSUE THREAD

**Issue by codereport** [compiler-explorer/compiler-explorer#4494]
### Describe the bug

`fmt` library does not seem to work with MSVC?

### Steps to reproduce

1. Go to godbolt
2. Select x64 msvc v19.latest
3. Compiler options /std:c++latest
4. Type the following code:
```cpp
#include <fmt/core.h>

auto main() -> int {
    fmt::print("Merry Christmas!");
    return 0;
}
```

### Expected behavior

I expect the below godbolt link to print Merry Christmas. Instead I see:
```
example.cpp
ASM generation compiler returned: 0
example.cpp
output.s.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) void __cdecl fmt::v9::detail::vprint_mojibake(struct _iobuf *,class fmt::v9::basic_string_view<char>,class fmt::v9::basic_format_args<class fmt::v9::basic_format_context<class fmt::v9::appender,char> >)" (__imp_?vprint_mojibake@detail@v9@fmt@@YAXPEAU_iobuf@@V?$basic_string_view@D@23@V?$basic_format_args@V?$basic_format_context@Vappender@v9@fmt@@D@v9@fmt@@@23@@Z) referenced in function "void __cdecl fmt::v9::print<>(class fmt::v9::basic_format_string<char>)" (??$print@$$V@v9@fmt@@YAXV?$basic_format_string@D$$V@01@@Z)
output.s.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) void __cdecl fmt::v9::vprint(class fmt::v9::basic_string_view<char>,class fmt::v9::basic_format_args<class fmt::v9::basic_format_context<class fmt::v9::appender,char> >)" (__imp_?vprint@v9@fmt@@YAXV?$basic_string_view@D@12@V?$basic_format_args@V?$basic_format_context@Vappender@v9@fmt@@D@v9@fmt@@@12@@Z) referenced in function "void __cdecl fmt::v9::print<>(class fmt::v9::basic_format_string<char>)" (??$print@$$V@v9@fmt@@YAXV?$basic_format_string@D$$V@01@@Z)
C:\Users\ContainerAdministrator\AppData\Local\Temp\compiler-explorer-compiler20221125-34032-1wa2wcu.3evr\output.s.exe : fatal error LNK1120: 2 unresolved externals
Execution build compiler returned: 2
```

### Reproduction link

https://godbolt.org/z/n8EMocac6

### Screenshots

Not applicable

### Operating System

Ubuntu 20.04

### Browser version

Chrome

**Comment by RubenRBS** [comment]
Hi, thanks for the report. MSVC compilers are provided by Microsoft, so we have less control over them than for the rest of the available compilers. We'll check what the possible solutions are, as I'm not now sure that they ever supported libbraries in x64 (But I could be totally wrong)

**Comment by cdacamar** [comment]
I don't believe there's any MSVC bug here.  Since fmtlib has a separately-compiled component, you would need to define the macro `FMT_HEADER_ONLY` as per the 'Features' list: https://github.com/fmtlib/fmt#features.  Once I set that macro the program will work: https://godbolt.org/z/h1cWhE9rs

**Comment by codereport** [comment]
Awesome! This works great for me! Thanks @cdacamar
