### ISSUE TITLE
[LIB REQUEST]: simdjson

### ISSUE THREAD

**Issue by jzwinck** [compiler-explorer/compiler-explorer#4508]
### Library name

simdjson

### Library description

The simdjson library uses commonly available SIMD instructions and microparallel algorithms to parse JSON 4x faster than RapidJSON and 25x faster than JSON for Modern C++.

### Library repository

https://github.com/simdjson/simdjson

### Motivation

This library is widely used and a good example of some SIMD techniques.

**Comment by lemire** [comment]
We are available to help make this happen.

**Comment by lemire** [comment]
@jzwinck Is this something you are willing to look at ?

**Comment by jzwinck** [comment]
@lemire I don't know when I might have time for it, so if you or your team do, please go ahead.  If not, perhaps you can answer a quick question: does it seem reasonable to use the "singleheader"/amalgamated version of simdjson for this, since the instructions Matt linked above explain that header-only libraries are simpler to integrate?

**Comment by lemire** [comment]
@jzwinck Yes. I would definitively recommend the single header version (simdjson.h and simdjson.cpp) as it would almost surely be an order of magnitude simpler !!!

**Comment by partouf** [comment]
this is now live

**Comment by jzwinck** [comment]
Works for me, thank you @partouf.

**Comment by lemire** [comment]
@partouf Thanks Patrick.
