### ISSUE TITLE
[BUG]: Embedded mode is broken

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#4541]
### Describe the bug

If you make an embedded link and try and iframe embed it, it breaks with JS errors.

### Steps to reproduce

1. Get an iframe embedded link
2. paste it into a local html doc
3. Open it
4. Observe the errors

Visiting the URL directly works though which is odd, so it seems embed iframe specific.

Example HTML:
```html
<html>
    <body>
        <iframe width='800px' height='200px' src='https://godbolt.org/e#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:17,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:6,positionColumn:2,positionLineNumber:6,selectionStartColumn:2,selectionStartLineNumber:6,startColumn:2,startLineNumber:6),source:'%23include+%3Cstring.h%3E%0A%0Aint+main(int+c,+char*+argv%5B%5D)+%7B%0A++char+buf%5B10%5D%3B%0A++strcpy(buf,+argv%5B0%5D)%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:23.529370801505742,l:'4',m:17.92452830188679,n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:armg1220,deviceViewOpen:'1',filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:16,fontUsePx:'0',j:5,lang:c%2B%2B,libs:!(),options:'-O2',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+ARM+gcc+12.2+(linux)+(Editor+%231)',t:'0')),header:(),l:'4',m:37.641125419216095,n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:armg1220,deviceViewOpen:'1',filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:16,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-D_FORTIFY_SOURCE%3D2+-O2',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+ARM+gcc+12.2+(linux)+(Editor+%231)',t:'0')),header:(),l:'4',m:44.43434627889711,n:'0',o:'',s:0,t:'0')),k:100,l:'3',n:'0',o:'',t:'0')),version:4'></iframe>
    </body>
</html>
```

Going directly to the iframe's destination seems to [work](https://godbolt.org/e#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:17,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:6,positionColumn:2,positionLineNumber:6,selectionStartColumn:2,selectionStartLineNumber:6,startColumn:2,startLineNumber:6),source:'%23include+%3Cstring.h%3E%0A%0Aint+main(int+c,+char*+argv%5B%5D)+%7B%0A++char+buf%5B10%5D%3B%0A++strcpy(buf,+argv%5B0%5D)%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:23.529370801505742,l:'4',m:17.92452830188679,n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:armg1220,deviceViewOpen:'1',filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:16,fontUsePx:'0',j:5,lang:c%2B%2B,libs:!(),options:'-O2',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+ARM+gcc+12.2+(linux)+(Editor+%231)',t:'0')),header:(),l:'4',m:37.641125419216095,n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:armg1220,deviceViewOpen:'1',filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:16,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-D_FORTIFY_SOURCE%3D2+-O2',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+ARM+gcc+12.2+(linux)+(Editor+%231)',t:'0')),header:(),l:'4',m:44.43434627889711,n:'0',o:'',s:0,t:'0')),k:100,l:'3',n:'0',o:'',t:'0')),version:4)

The errors are:
```
helpers.ts:120 Uncaught Error: Unwrap failed, at https://static.ce-cdn.net/main.v16.5a7b7121b3a368c1170f.js:1
    at n (assert.ts:63:15)
    at t.unwrap (assert.ts:77:9)
    at e.readValue (rison.ts:414:19)
    at ( (rison.ts:318:36)
    at e.readValue (rison.ts:404:27)
    at ( (rison.ts:318:36)
    at e.readValue (rison.ts:404:27)
    at e.parse_array (rison.ts:450:30)
    at ! (rison.ts:299:30)
    at e.readValue (rison.ts:404:27)
    at ( (rison.ts:318:36)
    at e.readValue (rison.ts:404:27)
    at e.parse_array (rison.ts:450:30)
    at ! (rison.ts:299:30)
    at e.readValue (rison.ts:404:27)
    at ( (rison.ts:318:36)
    at e.readValue (rison.ts:404:27)
    at e.parse_array (rison.ts:450:30)
    at ! (rison.ts:299:30)
    at e.readValue (rison.ts:404:27)
    at ( (rison.ts:318:36)
    at e.readValue (rison.ts:404:27)
    at e.parse (rison.ts:390:28)
    at M (rison.ts:238:14)
    at t.decode_object (rison.ts:247:12)
    at p (url.ts:83:18)
    at t.deserialiseState (url.ts:90:17)
    at main.js:272:20
    at z (main.js:348:13)
    at HTMLDocument.<anonymous> (main.js:566:18)
    at c (jquery.js:3830:29)
    at h (jquery.js:3898:12)
```

which implicates the new rison stuff, maybe?

### Expected behavior

It should work :)

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
With the single quotes I think the HTML gets messed up:
![image](https://user-images.githubusercontent.com/51220084/210858724-3bdac0f0-5ea6-4df2-a6bb-cbbd5c57dc1a.png)

But I am able to reproduce with double quotes too
```html
<html>
    <body>
        <iframe width='800px' height='200px' src="https://godbolt.org/e#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:17,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:6,positionColumn:2,positionLineNumber:6,selectionStartColumn:2,selectionStartLineNumber:6,startColumn:2,startLineNumber:6),source:'%23include+%3Cstring.h%3E%0A%0Aint+main(int+c,+char*+argv%5B%5D)+%7B%0A++char+buf%5B10%5D%3B%0A++strcpy(buf,+argv%5B0%5D)%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:23.529370801505742,l:'4',m:17.92452830188679,n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:armg1220,deviceViewOpen:'1',filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:16,fontUsePx:'0',j:5,lang:c%2B%2B,libs:!(),options:'-O2',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+ARM+gcc+12.2+(linux)+(Editor+%231)',t:'0')),header:(),l:'4',m:37.641125419216095,n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:armg1220,deviceViewOpen:'1',filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:16,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-D_FORTIFY_SOURCE%3D2+-O2',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+ARM+gcc+12.2+(linux)+(Editor+%231)',t:'0')),header:(),l:'4',m:44.43434627889711,n:'0',o:'',s:0,t:'0')),k:100,l:'3',n:'0',o:'',t:'0')),version:4"></iframe>
    </body>
</html>
```

**Comment by mattgodbolt** [comment]
I wondered about that: I couldn't think why it used singles but I thought it was ok... fun stuff :)

**Comment by jeremy-rifkin** [comment]
I can't reproduce with double quotes anymore, I think my original reproduction was incorrect. We got a report about embeds just showing the last state the site was loaded in rather than the url's state, might have been that.

I am able to reproduce only with the single-quoted attribute. I'll look at adding better error handling.
