### ISSUE TITLE
[BUG]: `range-v3` missing for gcc and clang

### ISSUE THREAD

**Issue by poconn** [compiler-explorer/compiler-explorer#4559]
### Describe the bug

The `range-v3` library, which is in the listed supported libraries and works on MSVC, is not found for gcc and clang (from a quick check, seems to be all versions).

### Steps to reproduce

```cpp
#include <range/v3/range.hpp>  // or any other header
```
Use e.g. `x86-64 gcc 12.2`

### Expected behavior

The code should compile.

### Reproduction link

https://godbolt.org/z/7G8oa5bTT

### Screenshots

Not applicable

**Comment by partouf** [comment]
You will actually have to tell us to use the range library by clicking Libraries and select a Range version. The way MSVC handles it is incorrect.

**Comment by poconn** [comment]
Whoops, sorry about that, thanks for the quick response!
