### ISSUE TITLE
[COMPILER REQUEST]: Update to SDCC 4.2.2

### ISSUE THREAD

**Issue by pinobatch** [compiler-explorer/compiler-explorer#4561]
### Compiler name

SDCC

### Compiler version

4.2.2

### Compiler language

C

### Compiler homepage

https://sdcc.sourceforge.net/

### Motivation

SDCC 4.1 was added in #2602. SDCC 4.2 has a much improved calling convention.

**Comment by partouf** [comment]
Requires adding 4.2.2 to https://github.com/compiler-explorer/infra/blob/main/bin/yaml/c.yaml#L57
and adding to https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/c.amazon.properties#L1865

**Comment by deepu-bansal** [comment]
Can you assign me this issue?

**Comment by pinobatch** [comment]
As of June 7, 2023, SDCC 4.3.0 is available
