### ISSUE TITLE
[BUG]: Aarch64 compilers do not seem to support float128.

### ISSUE THREAD

**Issue by Sholde** [compiler-explorer/compiler-explorer#4570]
### Describe the bug

Compilation failed

### Steps to reproduce

1. Visit godbold
2. Use the gcc or clang compiler for aarch64 and try to compile a C file with types __float128 or _Float128.

### Expected behavior

The compilation works and generates the assembly.

### Reproduction link

https://godbolt.org/z/T8E1evEsj

**Comment by Sholde** [comment]
Hi @dkm ,

Thanks for your quick reply.

In local, my gcc seems to use libquadmath calls like `__multf3`.

Link: https://github.com/gcc-mirror/gcc/blob/master/libgcc/soft-fp/multf3.c

Regards,

**Comment by mattgodbolt** [comment]
We must be missing some options in our GCC build. I'll see if we can enable it: on my laptop's system GCC I can compile `__float128`

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.3.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04) 
```

something hiding in those options may enable it (at build time).

**Comment by mattgodbolt** [comment]
(for what it's worth even if we support this, you'll probably only see:

```asm
        call    __multf3@PLT
```
 in the output)

**Comment by mattgodbolt** [comment]
https://godbolt.org/z/bfb6Ecr4E works though... hmm

**Comment by mattgodbolt** [comment]
Ah! Aarch64: https://gcc.gnu.org/onlinedocs/gcc/Floating-Types.html says "__float128 is available on i386, x86_64, IA-64, and hppa HP-UX, as well as on PowerPC GNU/Linux targets that enable the vector scalar (VSX) instruction set. __float128 supports the 128-bit floating type. On i386, x86_64, PowerPC, and IA-64 other than HP-UX, __float128 is an alias for _Float128. On hppa and IA-64 HP-UX, __float128 is an alias for long double."

not available on Aarch64

**Comment by mattgodbolt** [comment]
@Sholde can you confirm how you built your local gcc and what flags you're using?

**Comment by Sholde** [comment]
I'm just using the gcc provided by my package manager. It may be that the `_Float128` type is considered `long double` internally, because I also tested it with a new installation of llvm/clang 14.0 that I just compiled, and the `_Float128` type is not recognized. With this compiler, llvm/clang, my example works with the `long double` type.

**Comment by dkm** [comment]
our cross gcc is configured with : 
```
Configured with: /opt/.build/aarch64-unknown-linux-gnu/src/gcc/configure --build=x86_64-build_pc-linux-gnu --host=x86_64-build_pc-linux-gnu --target=aarch64-unknown-linux-gnu --prefix=/opt/compiler-explorer/arm64/gcc-trunk-20230110/aarch64-unknown-linux-gnu --exec_prefix=/opt/compiler-explorer/arm64/gcc-trunk-20230110/aarch64-unknown-linux-gnu --with-sysroot=/opt/compiler-explorer/arm64/gcc-trunk-20230110/aarch64-unknown-linux-gnu/aarch64-unknown-linux-gnu/sysroot --enable-languages=c,c++,fortran --enable-__cxa_atexit --disable-libmudflap --enable-libgomp --enable-libssp --enable-libquadmath --enable-libquadmath-support --disable-libsanitizer --disable-libmpx --with-gmp=/opt/.build/aarch64-unknown-linux-gnu/buildtools --with-mpfr=/opt/.build/aarch64-unknown-linux-gnu/buildtools --with-mpc=/opt/.build/aarch64-unknown-linux-gnu/buildtools --with-isl=/opt/.build/aarch64-unknown-linux-gnu/buildtools --disable-lto --without-zstd --enable-threads=posix --enable-target-optspace --disable-plugin --disable-nls --disable-multilib --with-local-prefix=/opt/compiler-explorer/arm64/gcc-trunk-20230110/aarch64-unknown-linux-gnu/aarch64-unknown-linux-gnu/sysroot --enable-long-long
```

**Comment by dkm** [comment]
> I'm just using the gcc provided by my package manager. It may be that the `_Float128` type is considered `long double` internally, because I also tested it with a new installation of llvm/clang 14.0 that I just compiled, and the `_Float128` type is not recognized. With this compiler, llvm/clang, my example works with the `long double` type.

Could you give the GCC version and maybe your distribution?

**Comment by Sholde** [comment]
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/11/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.2.0-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.2.0 (Ubuntu 11.2.0-19ubuntu1) 
```

**Comment by dkm** [comment]
[didn't know ubuntu had backported the modula2 frontend in their GCC 11 !]

**Comment by Sholde** [comment]
Btw my issue is closed.

**Comment by dkm** [comment]
What do you mean by that? You don't need _Float128 anymore? Or you're fine with our compilers not supporting it?
If you've found more info on the matter I'm still interested to understand why your compiler has support and ours don't :)

**Comment by Sholde** [comment]
Hi @dkm,

I may have misspoken but I meant that in **compiler explorer**, as with my llvm/clang installation, you can use float128 using the `long double` type instead of `_Float128`.

It seemed to me that armclang accepts `_Float128`, so that's why I tested it in the first place, even though armclang is not available in **compiler explorer**.

Regards,

**Comment by dkm** [comment]
Hmm, of course using a macro to replace the missing type by some other type can work... but is it really what you want?
I mean, you could substitute it with int : https://godbolt.org/z/c1ad145dW and the code would still show `_Float128`.

And while I was trying to play with your example, discovered that `_Float128` is defined somewhere (maybe gcc, maybe libc... haven't checked):

https://godbolt.org/z/3Kd7j78j6

**Comment by dkm** [comment]
So I think we can indeed close this issue :) Thanks @Sholde
