### ISSUE TITLE
[BUG]: Unable to request library from conan: 404

### ISSUE THREAD

**Issue by YarikTH** [compiler-explorer/compiler-explorer#4572]
### Describe the bug

Around 10.01.2023 at about 07:30 UTC I worked on C++ code with 2 active libraries: Boost 1.81.0 and {fmt} 9.1.0, then suddenly code stops compiling with error message `<Unable to request library from conan: 404>`.

Using trial and error I found out that problem was with {fmt} 9.1.0, because removing it or changing to {fmt} 9.0.0 stops the error.

Then after half an hour {fmt} 9.1.0 worked well again.

Temporary shut downs are fine, but error message could be more precise. `<Unable to request library from conan: 404>` indirectly points to some requested library, but without specific and I'm as a user even have no idea that conan is used for one of them (or for each) under the hood. It would be better to provide more details to debug. At least library name and maybe its conan package name. 

I thought that conan package maintainers are done something in this moment, but it seems that CE has some conan package caching that could misbehave for a while.

From discord `#general`

> YarikTH
<Unable to request library from conan: 404>
🥲
Problem info can be little more verbosely. I have no idea which library is requested from conan
It is {fmt} via trial and error 
It seems that 9.1.0 was removed several minutes ago. Bad move from package maintainer I think
Restored 🤔

> partouf
Its slightly more complicated than that, we use a separate conan server where everything is automated, but our caching screws up the communication sometimes.
though im not sure  why that would happen with fixed version libraries, nothing should be happening with that

> YarikTH
{fmt} 9.1.0 was missing for a while, while 9.0.0 was available
it is not a problem, but error message could be more precise. At least pointing at the specific library instead of 404

> Rubén
There might be a reason we haven't been giving more context from the begining (Maybe that's all we know of the error ourselves? Who knows!) but you're right, we can do better in reporting the error to the user
If only so it's easier for us to debug too!
:)

### Steps to reproduce

Error is sporadic. I haven't seen such errors before.

So it is easier to emulate it via misconfiguring one of the packages to reproduce `conan: 404` error.

### Expected behavior

At least error message has more precise info about the problem.

Ideally conan package should always behave well. As I understood local conan caching was done for it at least but something went wrong.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by partouf** [comment]
This should be happening less and less, as we removed the caching from in-between CE and the Conan instance.
