### ISSUE TITLE
[REQUEST]: Upgrade cmake to 3.25 (for module support)

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#4576]
### Is your feature request related to a problem? Please describe

Requested by @mpusz on Slack

### Describe the solution you'd like

Can we update cmake

### Describe alternatives you've considered

na

### Additional context

Not applicable

**Comment by partouf** [comment]
Can be updated here https://github.com/compiler-explorer/infra/blob/main/bin/yaml/tools.yaml#L12

**Comment by partouf** [comment]
is now live
