### ISSUE TITLE
Intel syntax for Haskell

### ISSUE THREAD

**Issue by RubenRBS** [compiler-explorer/compiler-explorer#458]

**Comment by colejohnson66** [comment]
Currently, it looks like GHC [doesn't support outputting in Intel syntax](https://stackoverflow.com/questions/15529785/how-to-generate-intel-assembler-syntax-from-ghc-of-haskell)

**Comment by mattgodbolt** [comment]
Looks like intel syntax is working out of the box on newer Haskells.
