### ISSUE TITLE
[BUG]: #include url inhibits optimization remarks 

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#4585]
### Describe the bug

I'm compiling with clang and with the optimization pane open.
For this code I see optimization remarks as expected:

```c
void f(int* a, const int& b) {
    for(int i=0; i<10; ++i)
        a[i] += b;
}
```

But when adding any include url, even when not using it, such as
```c
#include <https://raw.githubusercontent.com/nemequ/hedley/master/hedley.h>
```
The optimization remarks disappear.

### Steps to reproduce

1. Visit godbolt.org
2. Select clang15 (or any clang), in the clang editor toolbar click 'Add new'/'Optimization'
3. Type any code in the C++ editor, such as
```c
void f(int* a, const int& b) {
    for(int i=0; i<10; ++i)
        a[i] += b;
}
```
and optimization remarks apper.
4. Add this line above or below the function, and optimization remarks disappear:
```c
#include <https://raw.githubusercontent.com/microsoft/snmalloc/main/src/snmalloc/aal/aal_arm.h>
```

### Expected behavior

Optimization remarks should still be available.

### Reproduction link

https://godbolt.org/z/xYa4efP5f

### Screenshots

![image](https://user-images.githubusercontent.com/73080/212300980-0808d594-440a-4101-a8c2-b08f7a0ab116.png)

![image](https://user-images.githubusercontent.com/73080/212301147-b3833b22-1ad8-4f96-ab64-8c7ad13c7096.png)

**Comment by OfekShilon** [comment]
The direct problem is at [this line](https://github.com/compiler-explorer/compiler-explorer/blob/3e606d32828aee7ec1ef4f1f764bc7cec7ef58b9/lib/base-compiler.ts#L2396):
```js
            if (opt.DebugLoc && opt.DebugLoc.File && opt.DebugLoc.File.includes(this.compileFilename)) {
                output.push(opt);
```
`this.compileFilename` is example.cpp, but when #including a file from url - opt.DebugLic.File is always `'<stdin>'`. 
I assume this condition is there to exclude opt remarks from headers. Not sure if that's currently possible when including from urls.

**Comment by jeremy-rifkin** [comment]
Repro'd, thank you for finding and fixing!
