### ISSUE TITLE
[BUG]: Designated initializers compile with -std=c++11 and 17

### ISSUE THREAD

**Issue by Naahun** [compiler-explorer/compiler-explorer#4603]
### Describe the bug

Designated initializers seems to work with the above mentioned compile flags (c++11, c++17), but it should only work in c++20 and above, but seems to work. 

### Steps to reproduce

1. Visit godbolt.org
2. Select compiler e.g.: x86-64 clang 15.0.0
3. Set compiler flag '-std=c++11' or '-std=c++17'
4. Copy this code in the source editor:
`#include <iostream>

class A{
public:
    int a;
    int b;
};

int main()
{
    A var{.a=1, .b=2};
    std::cout << var.a << std::endl;
}`

### Expected behavior

Compiler should throw an error, and ideally tell you this is a c++20 feature

### Reproduction link

https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIM6SuADJ4DJgAcj4ARpjEEgDMpAAOqAqETgwe3r7%2ByanpAiFhkSwxcVyJdpgOGUIETMQEWT5%2BAVU1AnUNBEUR0bEJtvWNzTltwz2hfaUDFQCUtqhexMjsHObxocjeWADUJvFuTgoExJisB9gmGgCC1zfbTAoKu3cA7Fa3SV5RtHjIIHuu2Bu1CBF2TAOnxuINBgl2USh9xMbwAIkjbvcwbsWExQhA5siPkCQTCAG4NFEWAB0kPiqK4pF21MR9LMKPR8WhsJO6BAKCW4IObmFuwpxFp%2B0Oot5/NctAx71RHAWtE4AFZeH4OFpSKhOCLLNZdgolitMPszPEeKQCJoVQsANYgeLxamuj2er0ANn0nEkWvtes4vAUIA0tvtCzgsCQaBYSTosXIlHjifocUeRi46o0EawZP%2BmAAanhMAB3ADySUYnBtNFoBFiYYgUSDUVCDQAnnXeB3mMQu5WotpqnbuLx42xBJWGLQezreFhcUZxIvSPgzjUyZgw%2BvMKpql4m73yIJMGr138osRux4sEHTngWL2FlQDMAFKWK9XaxOZIIIhiOwUgAfIShqEGuiMgYRgoNY1j6HgURhpACyoEkjgCHuAC0vIHKiphGpYXA2u0WF%2BBArijH4jLBFMJRlHoKRpBRNHMfkFG9Ixsy2BeY61BM7GMuRgndNx/TlEM3TCdJjQSTM5QLKayyrBIqoaoG676hwuyqAAHN6OHepIuxZsAuw5tSGjWbsEC4IQJCWtacy8OOWhzE6Lpul6vker6l4BqQ2q6jpobhpGi7RjAiAgAeR5EGQFAQA0n7KIYF5CAgqDltqNppnQTAUelYS0FlOUhZOqAJkmmawcAOZ5qQBUZpWx7lblQbxcgNzEJ%2BIaBIeyB1Pg2q8PwgGiOIoETeBKjqOu0H6IYxgIZYSEofA6GYRkuH4fSRFWCRZFmmpIkEKNJWZdlnX/qcmBrDa5a3kkr5%2BhwmrBUGOnYENx5OQZRkmWZ9WWeq1m2RAhpHTYuwOYlzlcK5kUeV5rrun5vnvUFlXBhw4URu5DrvWYWmhQNROeaQO7EGkziSEAA%3D%3D

### Screenshots

![image](https://user-images.githubusercontent.com/10808961/212661031-00dc74da-3306-4a00-a5a6-4dc2cf4366dd.png)

### Operating System

windows 10

### Browser version

google chrome Version 108.0.5359.126 (Official Build) (64-bit)

**Comment by partouf** [comment]
This seems to be a long standing feature/bug https://github.com/llvm/llvm-project/issues/47039 because the feature has overlap with the C standard.
Using `-Werror=c99-designator` in the example that you gave does work. https://godbolt.org/z/bxTYEeaGe
