### ISSUE TITLE
[BUG] Problem with MOVL opcode

### ISSUE THREAD

**Issue by barnabyrobson** [compiler-explorer/compiler-explorer#4606]
The MOVL documentation states "Copies the second operand (source operand) to the first operand (destination operand)." But that order is only true for Intel asm. For AT&T asm we copy from the first to the second.

**Comment by barnabyrobson** [comment]
The same issue is true for MOVQ .. I wonder if this is a more general issue.

**Comment by partouf** [comment]
Duplicate of https://github.com/compiler-explorer/compiler-explorer/issues/695
We use the official Intel documentation, so obviously this might give some issues on AT&T syntax
