### ISSUE TITLE
[BUG]: Control flow graph is ugly if recompiled while hidden

### ISSUE THREAD

**Issue by Alcaro** [compiler-explorer/compiler-explorer#4611]
### Describe the bug

See title/steps

### Steps to reproduce

1. Visit godbolt.org
2. Reset code/UI
3. Swap the code for anything containing branches or conditionals
4. Add new -> Control flow graph
5. Grab the CFG panel's tab and drop it into the compiler panel, so they become tabs on the same panel
6. Switch to compiler
7. Recompile
8. Switch back

### Expected behavior

![image](https://user-images.githubusercontent.com/5085186/212958943-4a47047a-ddb9-49eb-84df-bd2cf6d6b52e.png)
Actual behavior:
![image](https://user-images.githubusercontent.com/5085186/212959000-45f4bfdc-f382-4964-849f-ea652cb07133.png)

### Reproduction link

https://godbolt.org/z/dW8qE998o

### Screenshots

See above

**Comment by jeremy-rifkin** [comment]
The issue is the computing of the basic block dimensions when the pane is `display:none`

**Comment by Alcaro** [comment]
Solution 1: Write your own computation function. The font is monospace, it should™ be easy.
Solution 2: Make it not display:none. Instead, use opacity:0;pointer-events:none;.
Solution 3: Tag it for redraw, then check for that tag when the tab is focused.

I have no opinion on which option is better, but I'm sure your UI framework does.

**Comment by jeremy-rifkin** [comment]
Solution 3 is definitely viable, it would add some complexity with monitoring events. Solution 2 is not as the display:none is controlled by golden layout.

I think the easiest solution here is to create a hidden `.graph-container .graph .block-container` outside of golden layout and use that for computing block dimensions (that way we get the styles), I'll probably do this

**Comment by dkm** [comment]
This is now live :rocket:
