### ISSUE TITLE
[BUG]: Cannot change colour scheme/themes, going to settings bugs the visuals too

### ISSUE THREAD

**Issue by AgainPsychoX** [compiler-explorer/compiler-explorer#4618]
### Describe the bug

There are no colour schemes/themes listed. By solely opening and closing the settings dialog it changes visual making them look buggy.

### Steps to reproduce

1. Visit godbolt.org
2. Open More dropdown
3. Open Settings
4. Try change "Line highlighting colour scheme"

### Expected behavior

There should be things to chose from

### Reproduction link

Not applicable

### Screenshots

![image](https://user-images.githubusercontent.com/23557839/213382142-ce7cbc8e-6ff9-4aef-9e92-1c929853f879.png)

Looks like the HTML isn't properly populated...
![image](https://user-images.githubusercontent.com/23557839/213382196-e83be3fa-3a91-4a6c-992a-3162cfc54ea4.png)

And sadly it makes code hard to read:
![image](https://user-images.githubusercontent.com/23557839/213382648-3ec3ab8f-2b19-4767-8a87-b092ad99358c.png)

### Operating System

Windows 10

### Browser version

109.0.5414.75 (official) (64-bit) (cohort: Stable)

**Comment by jeremy-rifkin** [comment]
Thank you for the report! I’ll try to repro and patch tomorrow (or someone else may beat me to it)

**Comment by jeremy-rifkin** [comment]
I'm able to reproduce locally, the issue was introduced with #4490

**Comment by jeremy-rifkin** [comment]
Ok, the offending lines are https://github.com/compiler-explorer/compiler-explorer/blob/c6a548c765110ea977dee829bef6419b9a194a50/static/settings.ts#L462-L466
