### ISSUE TITLE
API fairness

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#462]
Today when discussing with colleagues it occurred to me it would be good to have some level of API "fairness". From the logs someone is currently doing a bunch of compiles that consistently time out:

```
Jun 12 09:28:06 340bbe71260e gcc: warn: Timeout for ./c-preload/compiler-wrapper [ '/opt/compiler-explorer/gcc-6.3.0/bin/g++', 
Jun 12 09:28:06 340bbe71260e gcc:   '-g', 
Jun 12 09:28:06 340bbe71260e gcc:   '-o', 
Jun 12 09:28:06 340bbe71260e gcc:   '/tmp/compiler-explorer-compiler117512-54-oairyt.54l3ex9a4i/output.s', 
Jun 12 09:28:06 340bbe71260e gcc:   '-masm=intel', 
Jun 12 09:28:06 340bbe71260e gcc:   '-S', 
Jun 12 09:28:06 340bbe71260e gcc:   '/tmp/compiler-explorer-compiler117512-54-oairyt.54l3ex9a4i/example.cpp' ] after 7500 ms 
```

And that's making the site appear slow to other users. Consider some level of queueing/throttling at the API end point (maybe using Amazon's API gateway?)

**Comment by partouf** [comment]
Issue feels out of date, lets close until we have more concrete reason to do this
