### ISSUE TITLE
[BUG]: Colour scheme setting is broken

### ISSUE THREAD

**Issue by hanickadot** [compiler-explorer/compiler-explorer#4626]
### Describe the bug

In Compiler Explorer Settings drop down menu for "Line highlighting colour scheme" is empty.

### Steps to reproduce

1. visit compiler-explorer.com
2. go to settings
3. look at the "Line highlighting colour scheme" dropdown box

### Expected behavior

there should be some color schemes to select from

### Reproduction link

Not applicable

### Screenshots

Not applicable
<img width="1249" alt="Screenshot 2023-01-20 at 20 32 47" src="https://user-images.githubusercontent.com/6557263/213790312-e4e26c29-eea9-4f33-82e5-40be3ae64703.png">

### Operating System

Mac OS 13.1

### Browser version

Safari 16.2

**Comment by jeremy-rifkin** [comment]
Thank you for the report! Fixed in  #4622 and will be live next time we deploy!
