### ISSUE TITLE
[BUG]: Compile to binary object gives error for LDC

### ISSUE THREAD

**Issue by JohanEngelen** [compiler-explorer/compiler-explorer#4649]
### Describe the bug

Enabling "Compile to binary object" fails for LDC (D language).
The error reported is `<No output: objdump returned 1>`

LDC does support `-c`, with same behavior as GCC.

### Steps to reproduce

1. Visit godbolt.org
2. Select D language, LDC compiler (e.g. LDC 1.30.0)
3. Enable "Compile to binary object"

### Expected behavior

Normal assembly output.

It does work for GDC.

### Reproduction link

https://d.godbolt.org/z/55886Moaa

### Screenshots

Not applicable

**Comment by dkm** [comment]
Oh, that's weird. I'll look into it

**Comment by dkm** [comment]
The reason it's not working is mainly because I didn't plan on enabling it for anything more than all `gcc` compilers and `rustc` and `ldc` got promoted here by mistake. It's mainly a matter of giving the correct options

**Comment by dkm** [comment]
Confirmed, `objdump` is given the assembly file. Will fix that :) Thanks for reporting

**Comment by dkm** [comment]
Nearly fixed, the filter decides to remove everything, so there is some tuning to do

**Comment by dkm** [comment]
Ok, so the faulty error comes from the `d.defaults.properties`, the fix is correct. I'll check if `dmd` needs the same fix before pushing a fix.
