### ISSUE TITLE
[BUG]: Java/Kotlin support broken

### ISSUE THREAD

**Issue by pradt2** [compiler-explorer/compiler-explorer#4677]
### Describe the bug

Java and Kotlin support is broken. No inputs work, including the default `Square` class.

### Steps to reproduce

Select `Java` or `Kotlin` , observe the Output panel.

### Expected behavior

The disassembled bytecode should be shown.

### Reproduction link

Not applicable

### Screenshots

![image](https://user-images.githubusercontent.com/12902844/216053357-d435ecf4-6693-43be-b0cc-534bb1c4ea81.png)

**Comment by mattgodbolt** [comment]
Thanks: Probably broken in #4609 but we have a fix for at least java in #4668 - will update the site with the fixes and hope that fixes kotlin too.

**Comment by jeremy-rifkin** [comment]
https://godbolt.org/z/cjo9nMzTe Java and Kotlin are good to go, Scala is broken

**Comment by mattgodbolt** [comment]
Awesome: thanks @jeremy-rifkin !

**Comment by mattgodbolt** [comment]
Closing in favour of #4681 for scala
