### ISSUE TITLE
[BUG]: Compiler API - inconsistency in documentation about libraries usage

### ISSUE THREAD

**Issue by DatabaseDropper** [compiler-explorer/compiler-explorer#4699]
Hi!

### Describe the bug

Documentation states that `include paths` in `userArguments` are deprecated and that I should use lib id / version, but when I do that then I do receive compilation errors and I need to use use arg.

Documentation Screenshoot:
![obraz](https://user-images.githubusercontent.com/47637776/216829070-19e8b43d-a4f7-43fd-9f3c-5284060d600f.png)

### Steps to reproduce

Send this payload to compiler api

```
{
  "source": "#include <boost/hana.hpp>\r\n#include <string>\r\n#include <iostream>\r\n\r\nusing namespace boost::hana;\r\n\r\nstruct animal\r\n{\r\n\tBOOST_HANA_DEFINE_STRUCT(animal,\r\n\t\t(std::string, name),\r\n\t\t(int, legs),\r\n\t\t(bool, has_tail)\r\n\t);\r\n};\r\n\r\nint main()\r\n{\r\n\ttuple<std::string, int, bool> t{ \"c4at\", 4, true };\r\n\tfor_each(t, [](auto value) { std::cout << value << '\\n'; });\r\n\r\n\tanimal cat{ \"cat\", 4, true };\r\n\tfor_each(cat, [](auto pair) { std::cout << boost::hana::second(pair) << '\\n'; });\r\n}\r\n",
  "options": {
    "userArguments": "",
    "compilerOptions": {
      "skipAsm": false,
      "executorRequest": false
    },
    "filters": {
      "binary": false,
      "commentOnly": false,
      "demangle": false,
      "directives": false,
      "execute": true,
      "intel": false,
      "labels": false,
      "libraryCode": false,
      "trim": false
    },
    "tools": [],
    "libraries": [
      {
        "id": "boost",
        "version": "1.81.0"
      }
    ]
  },
  "lang": "c++",
  "allowStoreCodeDebug": true
}
```

and you will receive an error that

```
 "stderr": [
    {
      "text": "\u001b[1m<source>:1:10: \u001b[0m\u001b[0;1;31mfatal error: \u001b[0m\u001b[1m'boost/hana.hpp' file not found\u001b[0m",
      "tag": {
        "line": 1,
        "column": 10,
        "text": "fatal error: 'boost/hana.hpp' file not found",
        "severity": 3,
        "file": "example.cpp"
      }
    },
    {
      "text": "#include <boost/hana.hpp>"
    },
    {
      "text": "\u001b[0;1;32m         ^~~~~~~~~~~~~~~~"
    },
    {
      "text": "\u001b[0m1 error generated."
    }
  ],
```

but when I add this lib to userArguments

```
  "source": "#include <boost/hana.hpp>\r\n#include <string>\r\n#include <iostream>\r\n\r\nusing namespace boost::hana;\r\n\r\nstruct animal\r\n{\r\n\tBOOST_HANA_DEFINE_STRUCT(animal,\r\n\t\t(std::string, name),\r\n\t\t(int, legs),\r\n\t\t(bool, has_tail)\r\n\t);\r\n};\r\n\r\nint main()\r\n{\r\n\ttuple<std::string, int, bool> t{ \"c4at\", 4, true };\r\n\tfor_each(t, [](auto value) { std::cout << value << '\\n'; });\r\n\r\n\tanimal cat{ \"cat\", 4, true };\r\n\tfor_each(cat, [](auto pair) { std::cout << boost::hana::second(pair) << '\\n'; });\r\n}\r\n",
  "options": {
    "userArguments": " -I/opt/compiler-explorer/libs/boost_1_81_0 ",
    "compilerOptions": {
      "skipAsm": false,
      "executorRequest": false
    },
    "filters": {
      "binary": false,
      "commentOnly": false,
      "demangle": false,
      "directives": false,
      "execute": true,
      "intel": false,
      "labels": false,
      "libraryCode": false,
      "trim": false
    },
    "tools": [],
    "libraries": [
      {
        "id": "boost",
        "version": "1.81.0"
      }
    ]
  },
  "lang": "c++",
  "allowStoreCodeDebug": true
}
```

then it works fine

### Expected behavior

I think that 

```
  "libraries": [
      {
        "id": "boost",
        "version": "1.81.0"
      }]
```

section should be enough for libraries to be included. 

Now I'm converting it like that, but it'll work only for C++, so it's not very robust :(

```csharp
var sb = new StringBuilder();
foreach (var path in foundVersion.Pathes)
{
	sb.Append($" -I{path} ");
}
requestData.options.userArguments += sb.ToString();
```

I'd also want to ask two questions:

What are API limits? how should I queue compilations on my side to not pressure your servers? 1 per min? 5min? 15?

What's the timeout/execution halt for the program? like runtime above 1min and 512MB of RAM?

Thanks in advance

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

API

### Browser version

API

**Comment by partouf** [comment]
The "version" that you used is not correct. The version should refer to the "id" that's used and not the actual version number. For Boost 1.81.0 that will be "181", you can find those here https://godbolt.org/api/libraries/c++

**Comment by DatabaseDropper** [comment]
@partouf 

oh shit

thank you for quick response!

I guess we can close this unless somebody can comment on those issues too

>What are API limits? how should I queue compilations on my side to not pressure your servers? 1 per min? 5min? 15?

>What's the timeout/execution halt for the program? like runtime above 1min and 512MB of RAM?

**Comment by RubenRBS** [comment]
> API limits

Right now we don't impose any API limitations (Other than anti DDoS measures), but we might do so at some later point in time if the need arises, so feel free to send as many as desired (We handle upwards of 3M per week, so a few thousands more per day should not hurt us too much!)
We do ask you to set a proper User Agent just so we can identify and contact you in case something goes wary.

> Timeout

This can be found in our config.
https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/nsjail/compilers-and-tools.cfg says around 1GB for compilers, and https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/nsjail/user-execution.cfg specifies 200MB for user code execution.

As for the timeouts, https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/compiler-explorer.amazon.properties#L6 specifies a compilation timeout of 20s, and right now I can't find the execution timeout, but it should be a similar number afaik

**Comment by partouf** [comment]
execution timeout is this one I think https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/compiler-explorer.defaults.properties#L3
