### ISSUE TITLE
Turn optimisations on by default for Julia

### ISSUE THREAD

**Issue by giordano** [compiler-explorer/compiler-explorer#4712]
The Julia frontend in Compiler Explorer has optimisations turned off by default: https://github.com/compiler-explorer/compiler-explorer/blob/fb47642ff74f450d0592678498317f699b899470/etc/scripts/julia_wrapper.jl#L35 But this is odd, because

1. julia itself has optimisations on by default.  [`code_llvm`](https://docs.julialang.org/en/v1/stdlib/InteractiveUtils/#InteractiveUtils.code_llvm) has `optimize=true` by default
2. native code is always optimised, in fact `optimize` isn't passed to [`code_native`](https://docs.julialang.org/en/v1/stdlib/InteractiveUtils/#InteractiveUtils.code_native) (which doesn't even accept this keyword): https://github.com/compiler-explorer/compiler-explorer/blob/fb47642ff74f450d0592678498317f699b899470/etc/scripts/julia_wrapper.jl#L95
3. compiler passes are defined as optimisations, for example demotion of `half` to `float`.  For example, in https://godbolt.org/z/GcdKq7WjP it looks like the LLVM IR is doing a native `fadd half`, even though the assembly has the demotion to `float` with `vcvtph2ps`/`vcvtps2ph` instructions.  This creates a weird mismatch between default LLVM IR and assembly

I think `optimize` should be `true` by default, but this also means that the option `--optimize` wouldn't make much sense anymore and would need to be renamed.  I'm happy to take a stab at this, if there is some agreement on turning optimisations on and renaming `--optimize` (to what?).

CC: @gbaraldi @vchuravy

**Comment by vchuravy** [comment]
Agreed. I should also go back to #4674 so that folks have a chance to discover the arguments to the compiler wrapper.

**Comment by mattgodbolt** [comment]
See also #1524, just for some context on the arguments for and against optimization on defaults.

**Comment by mattgodbolt** [comment]
As per the other PR, I'm going to merge and we can see how it goes from there.
