### ISSUE TITLE
[BUG]: small UI glitch

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#4714]
### Describe the bug

The tab is displayed over compiler name.

### Steps to reproduce

Open shared link: https://gcc.godbolt.org/z/6Wcrnzqfb.

### Expected behavior

Tab above compiler name.

### Reproduction link

https://gcc.godbolt.org/z/6Wcrnzqfb

### Screenshots

![Screenshot 2023-02-10 at 14-39-43 Compiler Explorer - C](https://user-images.githubusercontent.com/87603/218106346-3eb2c921-4adc-4d53-829e-276087aa4fd8.png)

**Comment by jeremy-rifkin** [comment]
I can't reproduce this with a browser window 1627px wide. Presumably this is a golden layout bug that we'd need to upgrade to solve.

**Comment by dkm** [comment]
Can't reproduce on my other machine. I'll retry with the one where this happened and see the exact setup.

**Comment by jeremy-rifkin** [comment]
Oh shoot I messed up the wording of my comment last evening, I meant to say I _can only reproduce_ it on a browser window 1627px wide (presumably +/- a few pixels). Tested with chrome.

**Comment by dkm** [comment]
Oh nice. I was using firefox, not sure about version/resolution yet

**Comment by jeremy-rifkin** [comment]
I can no longer seem to reproduce

**Comment by jeremy-rifkin** [comment]
Ah there we go, shrinking then reloading the page does it. triggering the resize event properly hides the tab. 1627 didn't work for me but 1672px does now.
![image](https://github.com/compiler-explorer/compiler-explorer/assets/51220084/7e4e391f-bb6f-46af-82fb-6205980aa77a)
![image](https://github.com/compiler-explorer/compiler-explorer/assets/51220084/098e948f-5e78-4801-b70b-4b0f7d4c2f68)

**Comment by jeremy-rifkin** [comment]
For a little while during the page load everything is ok
![image](https://github.com/compiler-explorer/compiler-explorer/assets/51220084/14db6ba1-1eb9-473b-ae39-d7599e841cb6)

Not exactly sure what causes it to change
