### ISSUE TITLE
rustc_cg_gcc doesn't build anymore

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#4715]
```
31861   │ 2023-02-10T00:23:03.3235847Z    Compiling proc_macro v0.0.0 (/root/build-rustc-cg-gcc/rustc_codegen_gcc/build_sysroot/sysroot_src/library/proc_macro)
31862   │ 2023-02-10T00:23:03.3874643Z    Compiling unicode-width v0.1.10
31863   │ 2023-02-10T00:23:03.4654707Z    Compiling getopts v0.2.21
31864   │ 2023-02-10T00:23:09.4851662Z    Compiling test v0.0.0 (/root/build-rustc-cg-gcc/rustc_codegen_gcc/build_sysroot/sysroot_src/library/test)
31865   │ 2023-02-10T00:23:18.2760525Z    Compiling sysroot v0.0.0 (/root/build-rustc-cg-gcc/rustc_codegen_gcc/build_sysroot)
31866   │ 2023-02-10T00:23:18.3476639Z     Finished dev [unoptimized + debuginfo] target(s) in 49.75s
31867   │ 2023-02-10T00:23:18.5530069Z 
31868   │ 2023-02-10T00:23:18.5530424Z real   0m50.043s
31869   │ 2023-02-10T00:23:18.5530683Z user   1m11.765s
31870   │ 2023-02-10T00:23:18.5531507Z ~/build-rustc-cg-gcc ~
31871   │ 2023-02-10T00:23:18.5531794Z sys    0m8.160s
31872   │ 2023-02-10T00:23:18.6296282Z info: removing component 'rust-src'
31873   │ 2023-02-10T00:23:18.8507205Z info: removing component 'rustc-dev'
31874   │ 2023-02-10T00:23:19.1976224Z info: removing component 'llvm-tools-preview'
31875   │ 2023-02-10T00:23:19.2661377Z error: the crate `panic_abort` does not have the panic strategy `abort`
31876   │ 2023-02-10T00:23:19.2661647Z 
31877   │ 2023-02-10T00:23:19.2681325Z error: aborting due to previous error
31878   │ 2023-02-10T00:23:19.2681526Z 
31879   │ 2023-02-10T00:23:26.7161811Z ##[error]Process completed with exit code 1.
31880   │ 2023-02-10T00:23:26.7217917Z ##[group]Run ./post-run.sh "rustc-cg-gcc_master" "" "" "1675987395"
```
https://github.com/compiler-explorer/compiler-workflows/actions/workflows/build-daily-rustc-cg-gcc_master.yml?page=2

Failing since Jan 12

**Comment by dkm** [comment]
So the build works, but the error comes from the sanity check:
```
 216   │ echo "fn main() -> Result<(), &'static str> { Ok(()) }" > /tmp/test.rs
 217   │ ./toolroot/bin/rustc -Cpanic=abort -Zcodegen-backend=librustc_codegen_gcc.so 
       │  --sysroot toolroot/sysroot --emit asm -o test.s  /tmp/test.rs
 218   │ test test.s
 219   │ 
 220   │ ./toolroot/bin/rustc -Cpanic=abort -Zcodegen-backend=librustc_codegen_gcc.so 
       │ --sysroot toolroot/sysroot /tmp/test.rs
 221   │ ./test
```

This is still more or less following instructions in https://github.com/rust-lang/rust/tree/master/compiler/rustc_codegen_gcc with the `-Cpanic=abort`.

**Comment by antoyo** [comment]
One way to fix the `error: the crate panic_abort does not have the panic strategy abort` is to build the sysroot with this variable set:
```
CG_RUSTFLAGS=-Cpanic=abort
```
I'm not sure how rust allows both `panic=abort` and `panic=unwind` in the same installation.

Perhaps @bjorn3 would know.

**Comment by bjorn3** [comment]
Rust's build system has a wrapper around rustc which adds extra flags depending on various factors. This wrapper checks if the crate name is `panic_abort` and in that case adds `-Cpanic=abort`. See https://github.com/rust-lang/rust/blob/73f40197ecabf77ed59028af61739404eb60dd2e/src/bootstrap/bin/rustc.rs#L92-L102

**Comment by dkm** [comment]
Nice, it fixes the problem, thanks both. I'm not sure I understand what is happening, but will try to read a bit :)

**Comment by dkm** [comment]
@bjorn3 do you mean that using `-Cpanic=abort` when building the sysroot is not correct as it forces the panic for everything instead of only the `panic_abort`?

**Comment by bjorn3** [comment]
Using `-Cpanic=abort` for the whole sysroot forces everything to use `-Cpanic=abort`. While it technically works, this would make it impossible to test cg_gcc's new unwinding support.

**Comment by dkm** [comment]
Ok, that's what I feared :(
I've looked at https://github.com/rust-lang/rustc_codegen_gcc/blob/master/build_sysroot/build_sysroot.sh and don't see an easy way to have it only for `panic_abort`...

@antoyo : I can resume the build by having it global and do apply a later fix when you have something more focused on the `panic_abort` crate.

**Comment by dkm** [comment]
The compiler builds again, but with panic=abort forced on the whole build. Better than it being stuck...

https://github.com/compiler-explorer/compiler-workflows/actions/runs/4218786495

**Comment by dkm** [comment]
Ok, so it builds correctly now... I'll close this, and will probably forget about this until something else breaks :facepalm:
