### ISSUE TITLE
[BUG]: Go compiler groups are a mess

### ISSUE THREAD

**Issue by Alcaro** [compiler-explorer/compiler-explorer#4733]
### Describe the bug

Our Go compilers are sorted under these groups:

x86 GC
GC ARM
GC ARM
GC MIPS
GC MIPS
GC MIPS
GC MIPS
GC PPC
GC PPC
GC RISC-V
GC S390X
GC WASM
x86 GC
GCCGO arm
GCCGO arm64
GCCGO mips
GCCGO mips64
GCCGO mips64el
GCCGO mips64
GCCGO POWER64
GCCGO POWER
GCCGO POWER64LE
GCCGO riscv64
GCCGO s390x
GCCGO sparc
GCCGO sparc64
gccgo

Some of those names are suboptimal at best. Those duplicates are just weird, and that bottom category not having an architecture isn't necessarily correct behavior either.

There are better category names in https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/go.amazon.properties, so I think it's some kind of bug in our category handlers. No clue about the x86 gccgo, it doesn't seem to exist in that file at all.

And we don't have an amd64 gccgo. That's probably a third bug.

### Steps to reproduce

Yes

### Expected behavior

More walruses

### Reproduction link

https://go.godbolt.org/

### Screenshots

Not applicable

**Comment by dkm** [comment]
proposal:
`<Compiler Name> <arch>`
with
- `<Compiler Name>` in `GCCGO`, `GO`
- and `<arch>` in the list used above for the `GCCGO` compilers.
