### ISSUE TITLE
[BUG]: SASS-PTX selection not preserved when creating a link for sharing

### ISSUE THREAD

**Issue by u235axe** [compiler-explorer/compiler-explorer#4749]
### Describe the bug

The state of the Device Viewer panel, that in case of CUDA C++ is either PTX (default) or SASS, is not preserved, when a link is created for sharing (does not matter if short, or full link was created).

### Steps to reproduce

1. Visit godbolt.org
2. Select CUDA C++
3. Go to the Device Viewer panel
4. Select SASS from the dropdown menu
5. Create a link for sharing on the top right of the webpage
6. Open the newly created link in another browser or tab
7. Note the state of the selection as PTX instead of SASS

### Expected behavior

I would expect the state of the selection to stay as it was set up at the time of sharing, such that I don't need to explain people how to switch to the other output each time I try to show them something that is only visible in the SASS.

### Screenshots

Not applicable

**Comment by partouf** [comment]
:( this did used to work
