### ISSUE TITLE
[LANGUAGE REQUEST]: LLVM Machine IR

### ISSUE THREAD

**Issue by yashssh** [compiler-explorer/compiler-explorer#4762]
### Language name

LLVM Machine IR

### Language homepage

https://llvm.org/docs/MIRLangRef.html

### Compiler homepage

https://releases.llvm.org/

### Compiler version

LLVM 15.0.0

### Motivation

As a backend compiler engineer, I repeatedly run into the need for a compiler explorer for LLVM machine-level IR similar to what we have for LLVM IR. 
Since this MIR will need the same compiler that LLVM IR needs (opt & llc) it's straightforward to integrate. I have a working version for MIR support on a local instance and would like to submit a patch here.

**Comment by matsjla** [comment]
Hey, this sounds excellent! Feel free to open a pull request with your local changes and we can work out how to integrate it with prod together

**Comment by singh-yashwant** [comment]
Great I'll open a pull request as soon as I can.
