### ISSUE TITLE
MSVC Output Option greyed out and unchecked

### ISSUE THREAD

**Issue by NBlad** [compiler-explorer/compiler-explorer#4769]
Pretty sure this used to work and there is a Microsoft announcement back in 2022 that executing MSVC code was available.  When I try it now the execute output option is unchecked and disabled (so that you cannot enable).

**Comment by jeremy-rifkin** [comment]
Hello, MSVC execution is currently disabled due to a recent security concern. We're working on a workaround.

**Comment by tocic** [comment]
@jeremy-rifkin Seems like the `msvc v19.latest` (`vcpp_v19_latest_x64`) compiler have completely disappeared. Is it down for maintenance?

![image](https://user-images.githubusercontent.com/22129543/224728220-8e5ef3de-9544-4a9b-b284-98759505f1d1.png)

**Comment by mattgodbolt** [comment]
We had an outage. Our friends at MS have fixed the issue on their side just now. We're in the process of bouncing to pick up their return.

**Comment by mattgodbolt** [comment]
It should be back again...

**Comment by PeterSommerlad** [comment]
any chance that execution with recent msvc will be enabled again?

**Comment by jeremy-rifkin** [comment]
Hi @pmolodo, yes. MSVC execution is still a priority :)

**Comment by mattgodbolt** [comment]
It's in the hands of lawyers, unfortunately. We are as ready as we can be on our side to make the changes, but hands are tied over some legal things. We're working with Microsoft on this still.

**Comment by pmolodo** [comment]
Gotcha - appreciate the update!

**Comment by tocic** [comment]
Any news on this :pray:?

**Comment by jeremy-rifkin** [comment]
We are now hosting msvc compilers and execution is restored 🎉
