### ISSUE TITLE
[BUG]: ldd tool executes readelf instead?

### ISSUE THREAD

**Issue by disconnect3d** [compiler-explorer/compiler-explorer#4772]
### Describe the bug

It seems there is a bug with the ldd tool where it executes the readelf tool instead.

### Steps to reproduce

1. Visit godbolt.org
2. Choose C example/compiler
3. Click "Add tool..." -> "ldd"

### Expected behavior

I expected an error from the ldd tool, not from readelf

### Reproduction link

https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1AB9U8lJL6yAngGVG6AMKpaAVxYM9DgDJ4GmADl3ACNMYhAAVlIAB1QFQlsGZzcPPVj4mwFffyCWUPCoy0xrRKECJmICZPdPLgtMK0yGMoqCbMCQsMiLcsrq1LqFXra/DryuiIBKC1RXYmR2DgB6ACoAagAVAE9ozDWt2eI1tCw1hDDMUjWSNdpUJnQ1wzXMVVZo%2BgA6NZWlgFINABBPwENYKACOrgqmAgILWDHckzWfwA7AAhAGAtbYtbETAEOYMeHuH7Elh/ADMGKBqIAIpiONNaJwIrxPBwtKRUJxHGDDgtkQAmCk8UgETSM6YAaxAkgAbJ8AJwADgiyq4ETlGkFyopcuVyv0nEkbIlXM4vAUIA0Yol0zgsBgiBQqBY0ToYXIlDQbo94WQwC4gsFpCwADc8AsAGp4TAAdwA8rt2aKaLQCGErRBgmbgn4KltOKK88xiFsE8FtMVxdxeD62IIEwxaIWObwsCxDMBxG3Q3g8SUw5grb3XsVXBmzSCGmbaHhgsQC84sGaCMQ8Cwi4y%2BAZgAoY/Gk4wtzJBCIxOwpKf5Eo1GbdHUDEYQKZjOY58ErZBpqhok0R5aDTVok9gME4Lg1F4YHtLk%2BRpHECQCP0tQxAhTQwZ04SDEBJQCC0fQQQM9SNKUwwYeMWE9K0yF6EMrTkXBXDTAo/KXkyLKmr23IcGsqjKnKAC0cqSGswDIMgaxBp8gprBAuCEDcfzCkxvA1lokzSiAOqfBoUhcMqkgUoqKJcHKIqCtIzIcCapCboKUTspy3GWtatptvaToQEgswENEE5ehAPruvQxABKwix8YJwmieJkmCtJvCYPgRDrugej8GeojiFeGU3io6i9g%2BpBxou0RbuxHCsqQjm8NxCYTn5oKoFQvH8UJIliRJUkyRAzi%2BiFQoipMql2tM5wPF0EAVTZdkOWazkWK5anbg6zpEC4AUVHuFqkFtCjKIYDRCAgqBximdausFYRhWwnCRe1MVdfFgqJclJB4GldS5ee2XSLlij5feegsAITBoPJKUABJMAoaKYIwgITqgR7%2BGlta2aD4NvcQKMniDzBoGU%2BDnT0xM7UMxMHf4tDHadJPrbQACSaVDOuRgKMVpXlUalWcU5nCs34e6tVFHWxd1skQ4pylXH1V1HEpQ0je5028HZkhKoqWvazr2tytV83k0tdqkKtXkgAzm3ENtHC8HtVNHSdZ0nkFfo3RFbXRZ1cUJaQSUKal6WyD9l5/bIAN3oVwOY6gUvENDsPwwwiNECjSV4zHce4%2Bj%2BNg6gRN%2BCeFOF7bpN%2BA7NNO/TqAuMzIC0Og6Cc0wZW1hVVU1eaHAN4891e%2BLz2S9jg11Gsct%2BiPw1uepqu2Vpc1cUbNrLRppAyhEFI6XpBlGSZZlBjzFJ87VO0rxVL0G4vpdn6QQ7EPEdiSEAA

### Screenshots

<img width="332" alt="image" src="https://user-images.githubusercontent.com/10009354/221177494-740c16e8-caa6-49de-8e59-b70c4711215e.png">

**Comment by partouf** [comment]
This is a logging issue, ldd is actually used here

**Comment by partouf** [comment]
> I'm facing the same issue, I tried to open the link in the first comment but with readelf. I opened the link to make sure that I was not doing something wrong and I face the same **_requires an executable or binary object_** error with `ldd`, `readelf`, `nm` and other tolls. could you please recheck the fix? ![image](https://private-user-images.githubusercontent.com/20566477/287332870-1a3f4254-d38f-42f1-9228-6e8dab6977d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NTA0MDgsIm5iZiI6MTcwMTQ1MDEwOCwicGF0aCI6Ii8yMDU2NjQ3Ny8yODczMzI4NzAtMWEzZjQyNTQtZDM4Zi00MmYxLTkyMjgtNmU4ZGFiNjk3N2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE3MDE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwOWViYmQ0YmY5Y2IzZThlMjRmODBkNjcwYmJiNGQzYzE0MTJhMjU3ZDIyMDkwNjFiZWUwNjcyNzFjMGNjZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UEnJcF_grmWwGxcH2sByH0577L1iY1oGZaFk24OjRbc)

I am confused, the errors in this screenshot looks fine... What do you mean, exactly?

**Comment by AnasKhedr** [comment]
yes, you're absolutely correct
enabling those option makes readelf work just fine.
my bad, just a usage issue :/

**Comment by jeremy-rifkin** [comment]
All good, our interface sometimes isn't the most intuitive 😄
