### ISSUE TITLE
[COMPILER REQUEST]: GCC for vax-netbsdelf?

### ISSUE THREAD

**Issue by jbglaw** [compiler-explorer/compiler-explorer#4783]
### Compiler name

GNU GCC

### Compiler version

trunk

### Compiler language

C, C++, Assembly (possibly Go, Rust, Modula-2, D, ...)

### Compiler homepage

https://gcc.gnu.org

### Motivation

Right now, there's not a single compiler targeted at VAX. The VAX backend got is far from dead, but got a major overhault recently. It'd be nice to see the effect of compiler options with this. (A gcc-8 would be a good reference for something "old" I think.)

**Comment by dkm** [comment]
I'll have a look :)
First step will probably be to add support for VAX to crosstool-ng, that would be the easier way to have it handled like all of our cross gcc. Quick look shows there's no support yet.
I guess there's no linux support either, but can we use the common binutils/newlib/gcc combination?

**Comment by jbglaw** [comment]
I don't yet know what's actually needed for CE, but there's (right now) no longer a vax-linux port. Once there was one, but it died due to rotting away, as the compiler wasn't really fit and glibc parts (esp. newer components like NPTL threads and TLS support) were missing at that point.

So... If you need to get a compiler that's able to *link* userland programs (as a cross-compiler), that might not be that easy. It is however, quite easy to compile C -> ASM and ASM with GAS to object files, with an usual `gcc -c` call.

Looking at NetBSD, I think it should be fairly simple to use NetBSD's `build.sh` with the `tools` target, which builds a full cross compiler including libc. Let me know, what the actual requirements are. I guess we'd be able to cook up something.

**Comment by dkm** [comment]
We can always use a custom build script to build the toolchain, so no hard requirement: we can always special case the build or how the compiler can be used. Currently, all gcc-cross that we build are built using ct-ng and we simply have a config file for each compiler: makes it very easy to maintain.

I don't think we currently have an instance of a gcc that's not able to link anything, but that's very easy to handle as we do have settings for "Link to binary" and "Compile to binary". I know nothing about VAX, so will need to read a bit and see if it can simply be added in ct-ng. If not, then we'll go the custom script way :)

**Comment by jbglaw** [comment]
I don't really know the infrastructure, but can I help somehow with building the toolchain or integrating it (ie. to supply a merge request in the end?) If so, I'd be grateful for a few pointers. (-:

**Comment by dkm** [comment]
I've been looking at this. Is there an easy way to pick a specific version of GCC?

**Comment by dkm** [comment]
Oh, but this is cross building the full system, not only the compiler. Haven't checked how much it is doing. That may be a bit overkill and a waste of compute. I'll adapt the script in its current form to work with our infra, but being able to stop earlier would be great. Having the complete system may also make the packaging harder if everything is installed in the same directory...

**Comment by dkm** [comment]
First exp: 
- the build script seems highly coupled with a given gcc version (10.4.0 currently).
- bumping/changing gcc version doesn't look easy at all. Source tree is imported (https://github.com/NetBSD/src/tree/trunk/external/gpl3/gcc), changes that bump the version are non trivial merge (https://github.com/NetBSD/src/commit/357230f7cdd6ce47d4193f0a92fb3ebaf072b377)
- resulting size is 100% ok (160M extracted, 36M compressed)

So, this would only be used to build "current" NetBSD (10.4.0 currently, which sounds already a bit old).

@jbglaw does that sound correct and acceptable?

**Comment by jbglaw** [comment]
The GIT tree (which is a conversion of NetBSD's official CVS tree, which they still keep, because CVS has a way smaller memory footprint at runtime compared to GIT) contains the whole NetBSD system (kernel and basic userland, but no "fancy" 3rd party programs, which are built from `pkgsrc`.) GCC (and Binutils) are imported, they contain a number of patches. (Most notably to support NetBSD's goal of reproducible builds.)

My small shell script above used NetBSD's `build.sh` to build a part of NetBSD: The `tools` (compiler plus a number of useful tools to be running on the BUILD system) and `libs` (which are the most usual libs, for the TARGET system.) If you'd build the `release` target, you'd get a full NetBSD build.

So what you found out is mostly correct (though not the initial guesstimate that it's already a complete NetBSD system.)

I'd be happy to see that currently imported compiler (right now: 10.4.0) to show up on the Compiler Explorer!

(I've yet to look into what's actually needed for Compiler Explorer. If a bare-metal compiler without target libs is enough, that can compile pure C/C++ code without any libc/libstdc++, then I'd suggest another approach:
```
[binutils]
.../configure --prefix=... --target=vax-netbsdelf
make DESTDIR=... install-strip-{binutils,gas,ld}

[gcc]
.../configure --prefix=... --enable-languages=all --disable-gcov --disable-shared --disable-threads --target=vax-netbsdelf --without-headers --disable-multilib
make DESTDIR=... install-strip-gcc
```

But as I said: That 10.4.0 compiler is a good starting point. That's what's being used right now. Newer versions will show up in NetBSD land later on. (Ie. for VAX for the GCC 12 versions to show up as that gained a _lot_ of VAX patches.)

**Comment by dkm** [comment]
Ok, thanks for all this information. I can definitely add this compiler !

**Comment by jbglaw** [comment]
With the above `configure` + `make` combination, it should be pretty straight forward to build any recent GCC version, though without userland libraries. But for `-S` infocations to get some assembly, that would be working as expected.

**Comment by dkm** [comment]
True. I'll finish adding the one using netbsd, I have a local setup working correctly, so it's now a matter of having all paths correctly aligned. We can add more recent compiler as a later step :) Thanks for your help @jbglaw

**Comment by jbglaw** [comment]
I just documented what I'd easily reproduce here (for my work wrt. http://toolchain.lug-owl.de/). The final, detailed work was done by you, thanks a lot for that!

**Comment by jbglaw** [comment]
I suggest this patch:

```
$ git diff
diff --git a/build/build-vax-netbsd.sh b/build/build-vax-netbsd.sh
index bad9cf5..3c967d2 100755
--- a/build/build-vax-netbsd.sh
+++ b/build/build-vax-netbsd.sh
@@ -4,13 +4,13 @@ set -exuo pipefail
 
 ## This script uses NetBSD script to build the cross gcc, and will only use what
 ## they are using, which is fixed and not configurable. Currently, it's 10.4.0
-VERSION=10.4.0
+VERSION=$(curl -q https://raw.githubusercontent.com/NetBSD/src/trunk/external/gpl3/gcc/dist/gcc/BASE-VER)
+[ -z "${VERSION}" ] && exit 1
 
-TARGET=vax-netbsd-elf
+TARGET=vax-netbsdelf
 
 OUTPUT=/home/gcc-user/${TARGET}-gcc-${VERSION}.tar.xz
 STAGING_DIR=/opt/compiler-explorer/${TARGET}/gcc-${VERSION}
-export CT_PREFIX=${STAGING_DIR}
 
 ARG1=${1:-}
 FULLNAME=${TARGET}-gcc-${VERSION}
```
* Pull current GCC version from Github (as the repo isn't yet fetched)
* The `elf` suffix is added to the OS name for NetBSD, as pure `*-netbsd` would be in `a.out` format. It's not `-elf` as that would suggest freestanding binary code.

**Comment by dkm** [comment]
Compiler is currently building: https://github.com/compiler-explorer/infra/actions/runs/4462449687/jobs/7836997371

**Comment by dkm** [comment]
Something is not working, I probably have the output file wrong. I'll have a look in the coming days...

**Comment by jbglaw** [comment]
I did add another comment to the latest commit: IMHO it should be `TARGET=vax-netbsdelf`, not `TARGET=vax-netbsd`. If it's purely cosmetic, it doesn't matter. But `vax-netbsd` would strictly describe an ancient version of NetBSD using the old (abandoned) a.out format instead of ELF.

**Comment by dkm** [comment]
Yes, I saw that and fixed it. I've started a new compiler build. Better to get everything correctly named from the beginning. Thanks for spotting all these :)

**Comment by dkm** [comment]
Found a stupid typo in build script, so compiler is rebuilding. Last piece of config ready to go... Should be done in a few days now :)

**Comment by jbglaw** [comment]
Amazing typo. Even with looking at the `git show` output, it took a bit to recognize it.

I looked around in the `cross-builder` repo. Most GCCs are built with `ct-ng` as it seems. However, there's also `./build/msp430-gcc453/build.sh`, which does a very basic job of building just Binutils + GCC. That would work out of the box for a `--target=vax-linux` as well, with all-HEAD sources (or any reasonable older release.)

So maybe it's as easy as adding "vax" support and possibly disable a libc in `ct-ng` and call it a day? The `vax-netbsdelf-gcc` would be a lot more useable (as it would allow for "real" code to build), but adding `vax` to `ct-ng` would probably open a simple path to add a number of specific GCC versions? I'm already working with `ct-ng` at http://toolchain.lug-owl.de/ ,  will have a look at that.

**Comment by dkm** [comment]
> Amazing typo. Even with looking at the `git show` output, it took a bit to recognize it.

Only found it when setting up a test env and using shell completion to check the paths :D

> I looked around in the `cross-builder` repo. Most GCCs are built with `ct-ng` as it seems. However, there's also `./build/msp430-gcc453/build.sh`, which does a very basic job of building just Binutils + GCC. That would work out of the box for a `--target=vax-linux` as well, with all-HEAD sources (or any reasonable older release.)

Completely forgot about this script. I'll try to build a vax cross to test this. I don't think I've ever used it personally as I've used ct-ng since 12.2 for msp430.

> So maybe it's as easy as adding "vax" support and possibly disable a libc in `ct-ng` and call it a day? The `vax-netbsdelf-gcc` would be a lot more useable (as it would allow for "real" code to build), but adding `vax` to `ct-ng` would probably open a simple path to add a number of specific GCC versions? I'm already working with `ct-ng` at http://toolchain.lug-owl.de/ , will have a look at that.

This would be the easiest for us as that's indeed how we build most of the cross gcc and I have some script to help with the build and test when a new gcc version is released. It's already quite time consuming with only ct-ng builds...

**Comment by jbglaw** [comment]
Don't spend time on the msp430 script. While it's very much appreciated to get this first (vax-netbsdelf) compiler up'n'running, I'll have a look at `ct-ng` to get that running. That'll match your workflows much better and I can take workload away from you.

Actually, I already have a first small patch to ct-ng, but that's not enough though, as libgcc does not (yet) build. But we'll get there and I'd be happy if, at some day, I can just supply a ct-ng `.config` file for two or three other relevant GCC versions and we'd be done with it.

**Comment by jbglaw** [comment]
(If you give the msp430 script a try nonetheless, I saw that libgcc wouldn't build. But for just compiling without a libc and without final linking, libgcc wouldn't be needed. So that would still result in a proper compiler, building just `make all-gcc install-gcc`.)

**Comment by dkm** [comment]
Haven't found much time playing with the msp430. I think I'll wait for your possible ct-ng patch if you ever have one. If you never find time for pushing it or it's not possible, then don't hesitate to ping me :)
I'll focus on finishing this smaller change (should be 1 review away, hopefully).

**Comment by dkm** [comment]
The gcc 10.4 NetBSDelf is now live! :rocket:

**Comment by jbglaw** [comment]
Thanks  A LOT!  I'm working on the ct-ng stuff (fixing libgcc), will come back to you once that's done. Then, we'd be able to build other compiler versions (though only bare-metal) as well.

**Comment by dkm** [comment]
Probably yes, I haven't really followed this new feature, but it's probably a matter of setting the isa field in the conf. I'll take care of this! Thanks for telling us :)

**Comment by dkm** [comment]
(started a fix for the popup filter : https://github.com/compiler-explorer/compiler-explorer/pull/4924)
