### ISSUE TITLE
[BUG]: Output Link to binary change assembly code

### ISSUE THREAD

**Issue by Et7f3** [compiler-explorer/compiler-explorer#4785]
### Describe the bug

Output Link to binary change assembly code

### Steps to reproduce

1. Visit provided link
2. In Compiler for editor #2 add Link to binary
3. See the mov instruction changed.

### Expected behavior

We must find common code before and after

### Reproduction link

https://godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyagA%2BudTkVjVEQJDqzTAGF09AK5smIAKzknADIETNgAcp4ARtikIAAc5AAO6ErE9kyuHl6%2BicmpQkEh4WxRMfHW2LZpIkQspEQZnt48Vtg2dkLVtUQFYZHRcVY1dQ1ZzUpD3cG9xf2xAJRW6O6kqJxcAPTrAKQATADMwageOADUW3vOAO7BRNFM9AB0SOe4W1oAgrsHTEfup%2BfOG6kYJPF5vT4fIgATwS2BwNBO41I7lsJ1MqlwACEzgB2THgk6Ek43E4scgnCLkywnTDk7Dkmjk4DkpDkggnci6DkAa3O%2BI%2BWxxABEThjMeSAFSqMV88Hg6VYk4AcWwRFU2AiEAAbugCJg5rj%2Be8iSdSKrlkwThAFZi5uYzSxMMAlABHS5kTAQLTqABsWgUAQCc1lAuFXAW9G4Pn43i4OnI6G4zkRSxW2DO%2Bz45CI2nDC25IGkAE4HkWy%2BWKxXDNxpPw2L4tORY/HE1x%2BEoQI2c3Hw%2BQ4LAUBg2AkGNFKNQhyPGDEtahTFqeEXTEZbuNTL7ZDgtQRVgA1AjYS4AeVhsazdHot1IHYgEVz5AiwVqUO4WcfrFIUKPEV0FW7WaHDhhCPe4Xx7cgcDYYxgEkcDCDNSotWwDtwOwdQKncW5X34G5WnvegCAiUhn1cHB7yIYF614XsaCMZ190PE9mGwuRhDECROBkVjFBUDR730ZojBMEBzFMSwCIiDtIAWdAEnaJgUPbVo/zSRwmBcNxGikeJAimIoShAHEchSeSRiaeIkhMtIen0/ojPKSoOgmMztJaNoqgmGy%2BhieznM00Yyk8vTvMMhYlFTVYpAjKMY3vVsTg3E42CUWcTgXEsV2QogrXwYgyAzPYeDmfhux0OYFiQbBHX6CBoq4WtyHrHxG2bfhW3bTts1zcryALZrqy4PZYvA9qup7BZ%2BwQeAIEHLA8EIEgKCoWhR1YDgWMENjxEkLjNp4tRNHA/QdkMaCRIsNyVIcCAnBcv1/HUryZhiLjLLydJ/O8e63vkp6DK4hz5M6YZPpAe7AY8ro/v6AG/MyL7G3GKHgueqRpDCiK1mhWF4URCiUWy9FFUFI0TRJMkKSpclaROekTkZE5mROVliQ5LlepDT5hVFLFJRtTm5X2eEpjRUxYWwbkIBEXAlQAWVwUIABVyXeIUhQAJVwEQRANE09f1g3DaJLYfGcAkrRJo2retm3bYNk2zY%2BE1sewdAaAgCUIFVjWtZ1g1VF5PZsTtkOrYd83CRYJQ2AgXYdjYdAtQdohdh8VO45OaW5YVxWMx2EBU%2BaVOtAzkA8/OIVSDj61uQNMu47YavPe9zXtfK4Mg7OU2I9FQPg9DgfB/18OndxIVgwFAUhewOgQkZpQIHl2WDXMcXJbj504/JJeJ4hT5p9n9NQiIFU1Q1WrredKAkQJk5j/VCITglCU5i9X1/UDcq5Q%2BG1lVVB/tS6n1IaHuZoiAWitDaOYx9T4AI7kaQUQpeyRi4NGJscUkwpmWKsAqOwSrdXzA2AaDUmotQwW2KwnVSq9kmjNNA6BhyjiWhOBhU5%2BioGADwHgewILYG3HuA8x5TwbQYFeG8d5wLvmfCxKRn5vy/lsCxQCzAiAgXoGBeMkFoKwU0QQBCdgkIoXjGhDCWFqKUGEHhcCEliKflImseMFECBUT4AsWiLB6KCKYmefge12I7VkHtZQB1%2BIgBOkJMwF0JJSVqgmOSaQUIAFojxZghtdW6oMeAnV0oUEKPCfppBclk4y71oYxB4WkpgwN6iZJOpU6pZSQAVLhlpYpSM6iNL2BjbBnAdh1TQa1BM3AEqxB9Ikn00hGaoFQCcLhDw9g5QWvlL4fT8HjQqlVHAMRYkoJIUQwZo0OxdgIb1IhKChroJGtwNZZU6p4MuS2a5Y1bnkCQteVS0ggA%3D

### Screenshots

Before
<img width="388" alt="image" src="https://user-images.githubusercontent.com/29592775/221417569-2b30ac31-0cba-4f4d-8844-224787e4d10a.png">
After
<img width="345" alt="image" src="https://user-images.githubusercontent.com/29592775/221417591-474435d0-f8cc-4df0-beb6-1ffc69153456.png">

The move operand are inverted in the second example (and correct)

**Comment by partouf** [comment]
When using inline-assembly, the gcc compiler always just prints whatever you passed as inline assembly. Only when linking it will actually build the code and show how it will actually look like.
We can't change anything about that, it's just how it is when using inline assembly.

**Comment by partouf** [comment]
https://github.com/compiler-explorer/compiler-explorer/issues/1037
