### ISSUE TITLE
[BUG]: `llvm-cov` can't find `ld`

### ISSUE THREAD

**Issue by RubenRBS** [compiler-explorer/compiler-explorer#4796]
### Describe the bug

When running the `llvm-cov` tool, it seems like it can't find `ld` so it's unable to show useful results

### Steps to reproduce

1. Select C++ and a clang compiler
2. Open the llvm-cov tool

### Expected behavior

Coverage data should be displayed

### Reproduction link

https://godbolt.org/z/n44To6E37

### Screenshots

Not applicable

**Comment by partouf** [comment]
This is actually not an easy problem. The order of the compiler arguments have probably changed and the tool relied on a certain arrangement. That wasn't a good solution to begin with, so it needs a rewrite either way. Not sure how to solve yet, probably need to add some parameters or info to reconstruct a solid command line for llvm-cov.
