### ISSUE TITLE
[BUG]: URL #include doesn't work in IDE mode

### ISSUE THREAD

**Issue by dvirtz** [compiler-explorer/compiler-explorer#4801]
### Describe the bug

for files other than `example.cpp`:

```
/app/to.hpp:6:10: fatal error: raw.githubusercontent.com/cor3ntin/rangesnext/master/include/cor3ntin/rangesnext/to.hpp: No such file or directory
    6 | #include "raw.githubusercontent.com/cor3ntin/rangesnext/master/include/cor3ntin/rangesnext/to.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Steps to reproduce

https://godbolt.org/z/hhfWfh9nq

### Expected behavior

Compilation succeeds

### Reproduction link

see above

### Screenshots

Not applicable

**Comment by partouf** [comment]
this has been fixed a couple weeks back, sorry for not addressing this earlier

**Comment by partouf** [comment]
> executors still has this bug: https://godbolt.org/z/4a816T5z5

Thanks for the heads up, I'll make sure we fix this
