### ISSUE TITLE
[BUG]: Unable to get version for compiler

### ISSUE THREAD

**Issue by PlasmaHH** [compiler-explorer/compiler-explorer#4805]
### Describe the bug

Not totally sure if this is really a bug, a cry for help or a suggestion for improving documentation...

I am trying to add to our local instance a proprietary compiler (iar) and added to the `c++.local.properties`

```
group.iar.compilers=iar932
group.iar.isSemVer=true
group.iar.versionFlag=--version
compiler.iar932.name=IAR 9.32
compiler.iar932.exe=/mnt/c/Programme/IAR Systems/Embedded Workbench 9.1/arm/bin/iccarm.exe
compiler.iar932.semver=9.32
```

As you might have spotted, the setup is a bit unusual as I am within a WSL2 environment, trying to call a windows executable. Calling said executable with --version on the command line at least works fine, I am not so sure however if there might be an issue from within the compiler explorer.

It finds all other gcc/clang compilers just fine, but for the iar I get the error:

`Unable to get version for compiler '/mnt/c/Programme/IAR Systems/Embedded Workbench 9.1/arm/bin/iccarm.exe' - TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received ''`

Am I missing some configuration? Do I need to already at that step write me a lib/compilers/ file for the compiler and set like group.iar.compilerType=iar and implement something (whatever that is, this is where the "add a new compiler" documentation is lacking) ....

### Steps to reproduce

See above, though without an IAR license its probably going to be hard...

### Expected behavior

At least the version getting step should succeed and counted in "Compilers created:" ...

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

openSUSE TW on Windows 10 WSL2

**Comment by PlasmaHH** [comment]
I have been digging through the code a  little and what I think is going on is...

in exec.ts function executeNone the needsWine(command) returns true, which causes the executeWineDirect to be called which puts command+args together in an array and tries to run wine as the command, but its not there, so the empty file it is complaining is the filename where wine would have been...

however I am running this from within wsl2 so it doesn't need any wine...

looking at the needsWine function it checks if the file ends with .exe and for !proces.env.wsl .. Exporting wsl=1 before starting makes this run through, so the way wsl is detected should probably be updated?

In app.js there is a check for if uname -a contains Microsoft, but in my case it contains microsoft... so maybe check for the substring icrosoft instead? or do it case insensitive?

**Comment by partouf** [comment]
> In app.js there is a check for if uname -a contains Microsoft, but in my case it contains microsoft... so maybe check for the substring icrosoft instead? or do it case insensitive?

Case insensitive check is the way to go, I think

Thanks for looking into this, haven't been able to test wsl for a while myself

**Comment by OfekShilon** [comment]
@PlasmaHH  the real test for WSL is [here](https://github.com/compiler-explorer/compiler-explorer/blob/13eabd6d048c5caf75627a7cb0fe2d7ecad1dde6/app.ts#L160):
```
execSync('uname -a').toString().toLowerCase().includes('microsoft')
```
Perhaps this needs to change. What do you get in your distro over WSL when you run either -
1. `uname -a`
2. `cat /proc/version`

?

**Comment by PlasmaHH** [comment]
> @PlasmaHH the real test for WSL is [here](https://github.com/compiler-explorer/compiler-explorer/blob/13eabd6d048c5caf75627a7cb0fe2d7ecad1dde6/app.ts#L160):
> 
> ```
> execSync('uname -a').toString().toLowerCase().includes('microsoft')
> ```
> 
> Perhaps this needs to change. What do you get in your distro over WSL when you run either -
> 
> 1. `uname -a`
> 2. `cat /proc/version`
> 
> ?

Have a look at when that change was introduced: https://github.com/compiler-explorer/compiler-explorer/commit/2a3c1738d88f07d4f11c18fb0959733e3bb95d41

it seems that in the meantime the issues was detected and fixed elsewhere... 
(due to changes I had to made to my local copy and the effort needed to keep things up to date I haven't pulled for a very long time and not tested any newer version yet )

**Comment by OfekShilon** [comment]
@PlasmaHH  thank you. I'm closing for now, feel free to re-open if needed.
