### ISSUE TITLE
[BUG]: MSVC non-wine compilers missing

### ISSUE THREAD

**Issue by RA-Kooi** [compiler-explorer/compiler-explorer#4810]
### Describe the bug

The non-wine MSVC compilers are missing and https://godbolt.ms/ is down/inaccessible because their certificate expired yesterday (March 1st). I assume all that needs to happen is for MS to update their certificate and things should be working normally again?

### Steps to reproduce

1. Visit godbolt.org
2. Select the compiler dropdown and type in `msvc`
3. Notice that the non-wine versions are missing

### Expected behavior

The latest MSVC compilers are available.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
Not a bug, unfortunately we had to disable microsoft compilers temporarily. I’ll leave this issue open until it’s resolved in case it helps anyone else.

**Comment by jeremy-rifkin** [comment]
Cert issue resolved and we’ve re-enabled msvc compilers

**Comment by RA-Kooi** [comment]
Thanks!

On an unrelated note, I can swear code execution with MSVC compilers was available at one point, did it get disabled? Or did I just dream that?

**Comment by jeremy-rifkin** [comment]
MSVC execution has been disabled since January 17th unfortunately due to a security concern (see also #4769). It will not be disabled forever but unfortunately at the moment we don't have an estimate for when we'll be able to get a workaround up and running.

**Comment by adah1972** [comment]
This issue seems to indicate that MSVC compilers should still be active but result execution is disabled. However, today I cannot find MSVC 2019, and previously working link now has the wrong result....

**Comment by jeremy-rifkin** [comment]
They are unfortunately down again due to some issue causing https://www.godbolt.ms/ to give 502 errors
