### ISSUE TITLE
Link the stats page from the main page

### ISSUE THREAD

**Issue by jeremy-rifkin** [compiler-explorer/compiler-explorer#4812]
We have public stats at https://stats.compiler-explorer.com/ and we should link to it from the main site

![image](https://user-images.githubusercontent.com/51220084/222635297-489f5adf-fd25-4a0a-a958-5beafcdb93ce.png)

**Comment by jeremy-rifkin** [comment]
For anyone looking to implement this, the options in this menu are created in https://github.com/compiler-explorer/compiler-explorer/blob/main/views/menu-other.pug

**Comment by Aakarshan-369** [comment]
Hi! @jeremy-rifkin. I've added the link in #4819.
Thanks! :)
