### ISSUE TITLE
[BUG]: newer versions of a library not pulled

### ISSUE THREAD

**Issue by correaa** [compiler-explorer/compiler-explorer#4813]
### Describe the bug

I have installed a (my) library in godbolt infrastructure. (called "B-Multi trunk" in the list).
I have been suspicious that the library was not being updated.
When using the trick of including a .git file as a header I can see that it corresponds to a version from January.

In godbolt
```
#include <multi/../../.git/ORIG_HEAD>
```
In godbolt output
```
In file included from <source>:1:
/opt/compiler-explorer/libs/bmulti/trunk/.git/ORIG_HEAD:1:1: error: 'b4ea4e9658e8c4e57901d42949a82886e76e9ef1' does not name a type
    1 | b4ea4e9658e8c4e57901d42949a82886e76e9ef1
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compiler returned: 1
```

In my git log:
```
$ git log | grep b4ea4e9658e8c4e57901d42949a82886e76e9ef1 -A 5
commit b4ea4e9658e8c4e57901d42949a82886e76e9ef1
Author: Alfredo Correa <alfredo.correa+work@gmail.com>
Date:   Wed Jan 18 07:21:31 2023 +0000

    fix formatting
```

What is going on? Do I have the wrong impression that the library has not been updated since January?
Is it a problem with the cache?

I opened this feature request to know for sure what is the version being loaded, https://github.com/compiler-explorer/compiler-explorer/issues/4446#issuecomment-1445562037

### Steps to reproduce

1. go to https://godbolt.org/z/Kzd18KPEK

2. Look for hash `b4ea4e9658e8c4e57901d42949a82886e76e9ef1` in  https://gitlab.com/correaa/boost-multi/-/commits/master?search=fix+formatting

### Expected behavior

Libraries should be updated every few days.

### Reproduction link

 https://godbolt.org/z/Kzd18KPEK

### Screenshots

![image](https://user-images.githubusercontent.com/3047763/222827040-a06075cb-6263-4f80-b68a-2524b593a5e8.png)

![image](https://user-images.githubusercontent.com/3047763/222827133-b62df988-15a6-4bf9-8c09-2c36d729c9fb.png)

**Comment by mattgodbolt** [comment]
Hi @correaa ! Sorry for the trouble here: for what it's worth you can use `-E` to get more info: https://godbolt.org/z/Ge3fbxMMs if that's helpful next time. I'm taking a look at the library now

**Comment by mattgodbolt** [comment]
`git log` says:
```
commit 5a8ba54a18c14253f9e9925486548cb2d0119415 (HEAD -> master, origin/master, origin/HEAD)
Merge: b4ea4e965 c94a3e9c2
Author: Alfredo Correa <alfredo.correa+work@gmail.com>
Date:   Sun Jan 22 10:37:13 2023 +0000

    Merge branch 'add_1D_delayed_assign' into 'master'
    
    Add 1 d delayed assign
    
    See merge request correaa/boost-multi!517
```

**Comment by mattgodbolt** [comment]
The installer says:
```
2023-03-03 21:03:56,760 libraries/c++/nightly/bmulti trunk INFO     remote hash: 1d74307e11b8729e6936b5382335472b4d5fad25, current hash 5a8ba54a18c14253f9e9925486548cb2d0119415, needs installation
```

and then it fails in our code. I'll investigate and fix. Thanks for drawing this to my attention!

**Comment by mattgodbolt** [comment]
```88427deea6e
Mar/03 21:22 admin-node/o/c/l/b/trunk 3.4s $ less /opt/compiler-explorer/libs/bmulti/trunk/.git/ORIG_HEAD
Mar/03 21:24 admin-node/o/c/l/b/trunk 1.2s $ pwd
/opt/compiler-explorer/libs/bmulti/trunk
Mar/03 21:24 admin-node/o/c/l/b/trunk $ sudo git describe HEAD
v0.79-792-g1d74307e
Mar/03 21:24 admin-node/o/c/l/b/trunk $ sudo git log | head
commit 1d74307e11b8729e6936b5382335472b4d5fad25
Merge: 14b6d16a d515ab4e
Author: Alfredo Correa <alfredo.correa+work@gmail.com>
Date:   Fri Mar 3 20:12:43 2023 +0000

    Merge branch 'fix_gemm_cuda' into 'master'
    
    Fix gemm cuda
    
    See merge request correaa/boost-multi!547
```
now up to date. Sorry about that: underlying issue fixed too.

**Comment by correaa** [comment]
Should I be seeing the change immediately, or it will take a few hours.
This is what I see now:

![image](https://user-images.githubusercontent.com/3047763/222850571-b43f3ec4-dfa0-45e4-8db9-0fbe1cfe1605.png)

**Comment by correaa** [comment]
I see a current version now. It was a matter of waiting. Thanks!
