### ISSUE TITLE
MSVC Version info is going off screen if you press "Toggle full version output" after pressing the "i" button in the "output" pane

### ISSUE THREAD

**Issue by henrik-jensen** [compiler-explorer/compiler-explorer#4816]
### Discussed in https://github.com/compiler-explorer/compiler-explorer/discussions/4815

This seems to be a problem with the output of msvc "cl.exe". Gcc does not have this problem.

Actual version info disappears if you press "Toggle full version output" after pressing the "i" button in the "output" pane
and the "Toggle full version output" is now unreachable, as @jeremy-rifkin mentions in the [comments](https://github.com/compiler-explorer/compiler-explorer/issues/4816#issuecomment-1454467869),- "the tooltip is going off the screen".

**Workaround:** You have to refresh the page to get the simple info back.

## Example: With the "x64 msvc v19.latest" compiler: 
![image](https://user-images.githubusercontent.com/9413242/222877029-a1d5c9cb-5322-44fd-a5ad-3c52fd08529d.png)
 
Pressing "Toggle full version output":
![image](https://user-images.githubusercontent.com/9413242/222877081-61ee727a-e9a6-4bad-ab81-912bfb1b53a2.png)

This text is not scrollable and pressing the "i" button again gives you the "full version info" and you can't get back to "Simple version info" without doing a browser refresh.
Notice the "Toggle full version output" show an incomplete, non-scrollable command line option output, missing version info.

## gcc compiler does not have this problem:

Simple info:
![image](https://user-images.githubusercontent.com/9413242/222878049-c8bc03c5-5bd8-47d7-85d0-46a7ebd8c47c.png)

Full info:
![image](https://user-images.githubusercontent.com/9413242/222878037-a5eef40c-e10b-494d-8332-f50c697d37e6.png)

Notice you can come back to "Simple info" by pressing "Toggle full version output"

**Comment by jeremy-rifkin** [comment]
Confirmed, the tooltip is  going off the screen
