### ISSUE TITLE
[BUG]: Manually constructed URL produces different compilers depending on the local data

### ISSUE THREAD

**Issue by tocic** [compiler-explorer/compiler-explorer#4817]
### Describe the bug

Consider [this link][1] generated using the following python script some time ago (maybe the format has changed since then).

<details>
<summary>
Click to see the python script.
</summary>

```python
import json
import urllib.parse

editor = {
    "type": "component",
    "componentName": "codeEditor",
    "componentState": {
        "id": 1,
        "source": "int main(){}",
    },
}

compiler = {
    "type": "component",
    "componentName": "compiler",
    "componentState": {
        "source": 1,
        "compiler": "g92",
    },
}

obj = {
    "version": 4,
    "content": [
        {
            "type": "row",
            "content": [editor, {"type": "column", "content": [compiler]}],
        }
    ],
}

payload = json.dumps(obj)
ceFragment = urllib.parse.quote(payload)
print("https://godbolt.org/#" + ceFragment)
```

</details>

When you follow the link without the site's local data you will get the `Jakt` compiler, otherwise `x86-64 gcc 9.2`.

[1]:
https://godbolt.org/#%7B%22version%22%3A%204%2C%20%22content%22%3A%20%5B%7B%22type%22%3A%20%22row%22%2C%20%22content%22%3A%20%5B%7B%22type%22%3A%20%22component%22%2C%20%22componentName%22%3A%20%22codeEditor%22%2C%20%22componentState%22%3A%20%7B%22id%22%3A%201%2C%20%22source%22%3A%20%22int%20main%28%29%7B%7D%22%7D%7D%2C%20%7B%22type%22%3A%20%22column%22%2C%20%22content%22%3A%20%5B%7B%22type%22%3A%20%22component%22%2C%20%22componentName%22%3A%20%22compiler%22%2C%20%22componentState%22%3A%20%7B%22source%22%3A%201%2C%20%22compiler%22%3A%20%22g92%22%7D%7D%5D%7D%5D%7D%5D%7D

### Steps to reproduce

1. accept cookies from the site
2. visit the link
3. reload the page, you'll see `x86-64 gcc 9.2`
4. clear the local data
5. reload the page, you'll see `Jakt`

### Expected behavior

If the link is ill-formatted I expect an error as in #4555.
If the link is fine I expect only one correct compiler.

**Comment by partouf** [comment]
This seems to happen when someone's default language is Jakt and not C++ (default language is not stored in cookies, but in local storage) - I guess it has some kind of change behavior over the current state of the page.

This might also just one of the tradeoffs for trying to keep default language working in situations where the user does want it to change, but I imagine we can at least check if the user didn't come to the site using a link.

**Comment by tocic** [comment]
@partouf I found and minimizied [the code that generated the link](https://github.com/knatten/cppquiz/blob/8b45f29068db559cdf29c2c867b2efd5719d114a/quiz/templatetags/quiz_extras.py#L55).

**Comment by jeremy-rifkin** [comment]
I'm able to reproduce on the live site by setting my default language to jakt, also able to reproduce locally. I also opened a cppquiz CE url and hit the same issue:

https://godbolt.org/#%7B%22version%22%3A%204%2C%20%22content%22%3A%20%5B%7B%22type%22%3A%20%22row%22%2C%20%22content%22%3A%20%5B%7B%22type%22%3A%20%22component%22%2C%20%22componentName%22%3A%20%22codeEditor%22%2C%20%22componentState%22%3A%20%7B%22id%22%3A%201%2C%20%22source%22%3A%20%22%23include%20%3Ciostream%3E%5Cr%5Cn%5Cr%5Cnstruct%20S%20%7B%5Cr%5Cn%20%20operator%20void%28%29%20%7B%5Cr%5Cn%20%20%20%20std%3A%3Acout%20%3C%3C%20%5C%22F%5C%22%3B%5Cr%5Cn%20%20%7D%5Cr%5Cn%7D%3B%5Cr%5Cn%5Cr%5Cnint%20main%28%29%20%7B%5Cr%5Cn%20%20S%20s%3B%5Cr%5Cn%20%20%28void%29s%3B%5Cr%5Cn%20%20static_cast%3Cvoid%3E%28s%29%3B%5Cr%5Cn%20%20s.operator%20void%28%29%3B%5Cr%5Cn%7D%22%2C%20%22options%22%3A%20%7B%22compileOnChange%22%3A%20true%2C%20%22colouriseAsm%22%3A%20true%7D%7D%7D%2C%20%7B%22type%22%3A%20%22column%22%2C%20%22content%22%3A%20%5B%7B%22type%22%3A%20%22component%22%2C%20%22componentName%22%3A%20%22compiler%22%2C%20%22componentState%22%3A%20%7B%22id%22%3A%201%2C%20%22source%22%3A%201%2C%20%22compiler%22%3A%20%22g92%22%2C%20%22filters%22%3A%20%7B%22b%22%3A%201%2C%20%22execute%22%3A%201%2C%20%22intel%22%3A%201%2C%20%22commentOnly%22%3A%201%2C%20%22directives%22%3A%201%7D%2C%20%22options%22%3A%20%22-std%3Dc%2B%2B17%22%7D%7D%2C%20%7B%22type%22%3A%20%22component%22%2C%20%22componentName%22%3A%20%22output%22%2C%20%22componentState%22%3A%20%7B%22compiler%22%3A%201%2C%20%22source%22%3A%201%7D%7D%5D%7D%5D%7D%5D%7D

![image](https://user-images.githubusercontent.com/51220084/224574251-fafad4e3-8fd4-4216-b8d0-262c75e3f046.png)

**Comment by jeremy-rifkin** [comment]
I think what's needed is to set the editor's language in the state

```diff
editor = {
    "type": "component",
    "componentName": "codeEditor",
    "componentState": {
        "id": 1,
+       "lang": "c++",
        "source": "int main(){}",
    },
}
```

I'm not sure this is something we can handle better on our end.

**Comment by mattgodbolt** [comment]
We may have to "guess" the language from the compiler id: in theory they're all unique but as time has ticked on we namespace them differently. But the ones in these older URLs might be easy to guess (and/or just "guess" c++)

**Comment by jeremy-rifkin** [comment]
I think three behaviors on our end come to mind:
- notice that there's no `lang` in the state and error (but I'm not sure if that would break any existing stuff)
- notice that there's no `lang` in the state and try to guess
- keep the behavior of defaulting to the default language and then give an error about `g92` not existing as a jakt compiler

No idea which is best

**Comment by partouf** [comment]
I do not agree with guessing, editor language is different from compiler, when you're using IDE mode you can have different languages for each file/editor.

I think some kind of error instead of defaulting to something is the best option here. But I'm not sure how to manifest such an error.

**Comment by tocic** [comment]
@jeremy-rifkin IIUC, your and mine links must produce the error "No language specified for editor" now. But I still experience the same behaviour for them.

Also, shouldn't we update the docs?

https://github.com/compiler-explorer/compiler-explorer/blob/850cee9e089ae68b152fbfc1b26a42db8975f3b3/docs/API.md?plain=1#L86

**Comment by jeremy-rifkin** [comment]
Hi, can you clarify what you mean when you say you still experience the same behavior for them?

As for the API docs, the part of the docs linked is specifically for `POST /api/compiler/<compiler-id>/compile`. I don’t think we have docs for the internals of our UI states.

**Comment by tocic** [comment]
Well, when I follow the links without the local data I'm getting `Jakt`, otherwise `x86-64 gcc 9.2`, i.e. the same behaviour described above. But now I expect the error instead.

![jakt](https://user-images.githubusercontent.com/22129543/225518003-c3696ae6-662a-4b9d-bea5-7d3f63ea6b2f.gif)

> the part of the docs linked is specifically for `POST /api/compiler/<compiler-id>/compile`. I don’t think we have docs for the internals of our UI states.

Does that mean that the API call has different requirements than manually constructed link? That is you can omit the language in the request, but cannot in manually constructed link.

**Comment by jeremy-rifkin** [comment]
Ah ok. Without local data it looks like the compiler explorer privacy policy popup clobbers the error popup. Fixing that will probably be tricky.


> Does that mean that the API call has different requirements than a manually constructed link? That is you can omit the language in the request, but cannot in the manually constructed link.

The API and our frontend's internal state are completely different yes. The compiler/compiler-id/compile endpoint wouldn't tell you anything about an editor pane's state. Some day I hope we can get the UI state stuff documented properly.
