### ISSUE TITLE
[BUG]: C++: External data symbols aren't demangled

### ISSUE THREAD

**Issue by Alcaro** [compiler-explorer/compiler-explorer#4822]
### Describe the bug

External data symbols, like _ZStL8__ioinit, aren't demangled. (Certain other cases remain mangled too, I haven't been able to determine the exact conditions.)

### Steps to reproduce

Pretty much anything involving std::cout will reproduce. Or just click any or all of these:

Realistic example: https://godbolt.org/z/4Wra1bWTe
Simplified example: https://godbolt.org/z/51cebeGfY
Incorrect, not just missing, demangling (similar to #1732): https://godbolt.org/z/PbKhWWh1f

### Expected behavior

Demangle everything that can be demangled

### Reproduction link

See above

### Screenshots

Not applicable

**Comment by partouf** [comment]
The solution might be to support `mov     \w*, OFFSET FLAT:(\w*)` as an official label-carrying line.

Would need to be added in this file https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/demangler/base.ts and added as a regex that this function loops over https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/demangler/base.ts#L114 to collect.

**Comment by Alcaro** [comment]
Yes, that would fix the issue as stated, but it still feels like a fairly hacky solution. It won't fix things like
- `cmp QWORD PTR x[rip], OFFSET FLAT:_Z1aii` https://godbolt.org/z/jrKxdx76j
- at&t asm https://godbolt.org/z/rrzjqT14z
- Mangled symbols in string literals https://godbolt.org/z/3TErsv35q
- Unmangled symbols that contain mangled symbols https://godbolt.org/z/5hYrTKPhM

But several of those will only be found by troublemakers like me, so it may be better to simply wontfix them.

**Comment by OfekShilon** [comment]
Outside of wacky cases like 'mangled symbols in string literals' and 'unmangled symbols that contain mangled symbols', the ongoing improvements in demangling seems to have solved it. Closing.
