### ISSUE TITLE
[REQUEST]: CMake mode to specify -DCMAKE_BUILD_TYPE=Debug

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#4825]
### Is your feature request related to a problem? Please describe

People get confused when their cmake output doesn't have the line colouring/cross-referencing by default.

Maybe we should pre-populate the cmake box with CMAKE_BUILD_TYPE ? Or find a way to force CMake to pass `-g` to the linker?

### Describe the solution you'd like

Not sure

### Describe alternatives you've considered

We could:
- prepopulate the box
- pass `-g` in the linker flags somehow

### Additional context

Not applicable

**Comment by partouf** [comment]
You can also use `-g` in the compiler arguments.

I would be Ok with prepopulating the cmake argument box with build type when you first open it from the dropdown, that's sufficiently isolated that this shouldn't cause any issues.

**Comment by mattgodbolt** [comment]
Hmm - if `-g` in the compiler args work, can we get our "normal" process to auto-inject `-g` like it does for regular compiles?

**Comment by partouf** [comment]
> Hmm - if `-g` in the compiler args work, can we get our "normal" process to auto-inject `-g` like it does for regular compiles?

I'd rather not, because then you can't disable it

**Comment by mattgodbolt** [comment]
> I'd rather not, because then you can't disable it

That's already the case on the main site, though. I understand; but it's surprising to our users (apparently, I get an email every other month about it)
