### ISSUE TITLE
Issues with riscv in cmake

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#4827]
From email:

Here's a link which shows the build failing in cmake config on r64gc clang 12, but working with x86-64 clang.

   https://godbolt.org/z/ex5rv8E5G

and a screen shot of it appears below.

If I change the tool chain in the drop down to any of the risc-v toolchains I tried, or even the aarch64 ones I tried, I get the same result.  (I remember that the aarch64 one was working on a non-cmake simpler project the other day though.  Maybe it is all cmake specific?   I hope I'm not doing anything dumb with cmake or otherwise.)

The cmakefile is a pretty simple one--I use it in a simple way.  FYI, it works on every toolchain I have tried on every platform I have locally, including MacOS and aarch64 for the Jetson Nano.

![image](https://user-images.githubusercontent.com/633973/223499379-fcf9ddf0-d1bc-4125-8eb8-55a6b16816ad.png)

**Comment by partouf** [comment]
hmm, it's passing clang instead of clang++ because https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/c%2B%2B.amazon.properties#L635 is set to clang

**Comment by partouf** [comment]
how have we not seen this before...

**Comment by partouf** [comment]
will take a look at this locally and attempt fixes to make it work

**Comment by partouf** [comment]
hmm, there also seems to be wrong with not all options being passed or something
