### ISSUE TITLE
[REQUEST]: support parsing/display of `-fstack-usage` `su` files

### ISSUE THREAD

**Issue by lefticus** [compiler-explorer/compiler-explorer#4834]
### Is your feature request related to a problem? Please describe

When using GCC's `-fstack-usage`, a file is generated with the extension `.su` which is a list of 

`<functionname> <stack usage> <type of stack>`

See docs here: https://gcc.gnu.org/onlinedocs/gcc/Developer-Options.html#index-fstack-usage

I'd like to be able to see the output from that file

### Describe the solution you'd like

Inline reporting of function stack usage where possible in the source code.

### Describe alternatives you've considered

It's not possible to get this output in any other way that I know of. (except perhaps with `#embed`?)

### Additional context

Not applicable

**Comment by OfekShilon** [comment]
Optimization remarks also show stack usage:
![image](https://user-images.githubusercontent.com/73080/223956621-5ee51b1f-0606-48f2-92db-9355c995891a.png)

Maybe that's good enough? Is the static/dynamic/bounded stack type really useful?

**Comment by lefticus** [comment]
Yeah, my main comment is that is clang's feature, not gcc.

**Comment by jeremy-rifkin** [comment]
This would be great to integrate into CE. It looks like clang and icx support `-fstack-usage` too.

**Comment by dkm** [comment]
(closed by #5160 )
