### ISSUE TITLE
[REQUEST]: Add diff view for sass and ptx assembly for cuda c++

### ISSUE THREAD

**Issue by Saitama10000** [compiler-explorer/compiler-explorer#4838]
### Is your feature request related to a problem? Please describe

Add diff view for sass and ptx assembly for cuda c++. Currently it only works for nvcc x86-64 assembly.

### Describe the solution you'd like

Add diff view for sass and ptx assembly for cuda c++. 

### Describe alternatives you've considered

It should be relatively simple to implement? Though I'm not entirely sure...

### Additional context

Not applicable

**Comment by partouf** [comment]
This was added a while ago with https://github.com/compiler-explorer/compiler-explorer/pull/4973
