### ISSUE TITLE
[BUG]: Debugging-on-WSL documentation out of date

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#4840]
### Describe the bug

Things might have changed since this [doc](https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/WindowsSubsystemForLinux.md#debugging) was formed 6Y ago by @AndrewPardoe. 

Today's vscode uses a WSL-native server and I'm using it to debug CE over WSL identically to over linux. In particular, I'm not limited to attaching to a running CE instance and I'm not limited to printf-debugging for startup code.

I'm personally using the launch.json published by Paul Taylor [here](https://discord.com/channels/763778740345765900/764131393332314123/1045049049394458684) and am launching an instance by just `make` - not `make NODE_ARGS="--inspect"` as the existing doc says and neither `make debug` as Paul's discord post says (for some reason breakpoints fail to bind for me after `make debug`. Didn't investigate further).

### Steps to reproduce

-

### Expected behavior

-

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
I'm unable to add 'documentation' label (perhaps admin permissions are required?)

**Comment by partouf** [comment]
I don't think this is related to WSL, it's more about that we changed our way of launching CE in development mode. For dev we now use `ts-node-esm` which does not support `--inspect`.

I'm sure there's a way to do it, but I haven't dug into it fully yet to find out how to debug properly.

**Comment by partouf** [comment]
https://typestrong.org/ts-node/docs/usage/#node-flags-and-other-tools
I suspect maybe we can do `NODE_OPTIONS="--inspect"`

**Comment by partouf** [comment]
ah but `make` uses node again https://github.com/compiler-explorer/compiler-explorer/blob/main/Makefile#L80
so there NODE_ARGS would be a must

`make debug` should do it... but it's incredibly intense because it also does a lot of console logging which slows down everything

It doesn't entirely work for me yet. It thinks it's attached (both IDE and node are saying so), but nothing is debuggable it seems...

**Comment by OfekShilon** [comment]
Here's a capture of my debugging experience, using vscode, on WSL, with running just `make` (vscode auto-attaches at launch), using Paul Taylor's `launch.json`. The debugging experience is excellent. Is this somehow different from your setup?

https://user-images.githubusercontent.com/73080/224304559-833ffcc0-599b-49c4-8d31-c7ee9eb96674.mp4
