### ISSUE TITLE
[BUG]: Parsing ClientState from base64 via `/clientstate/` may be failing on very long requests.

### ISSUE THREAD

**Issue by Headline** [compiler-explorer/compiler-explorer#4844]
### Describe the bug

The following url [here](https://godbolt.org/clientstate/eyJzZXNzaW9ucyI6W3siaWQiOjAsImxhbmd1YWdlIjoiYysrIiwic291cmNlIjoiI2luY2x1ZGUgPHN0ZGlvLmg+XG4jaW5jbHVkZSA8c3RyaW5nPlxuI2luY2x1ZGUgPHN5cy91aW8uaD5cbiNpbmNsdWRlIDxlcnJuby5oPlxuXG5pbnQgbWFpbigpXG57XG4gICAgc3RkOjpzdHJpbmcgczsgLy8gc2VnZmF1bHQgaWYgdGhpcyBsaW5lIGlzbid0IGNvbW1lbnRlZCBvdXRcbiAgICBcbiAgICBzdHJ1Y3QgaW92ZWMgbG9jYWxbMV07XG4gICAgc3RydWN0IGlvdmVjIHJlbW90ZVsxXTtcbiAgICBjaGFyIHJlbTFbMjA0OF07XG4gICAgY2hhciByZW0yWzIwNDhdO1xuICAgIGNoYXIgbG9jWzQwOTZdO1xuICAgIHNzaXplX3QgbnJlYWQgPSAwO1xuICAgIHBpZF90IHBpZCA9IDQxMzE1OyAvLyBoYXJkIGNvZGVkIGJlY2F1c2UgSSdtIGp1c3QgdGVzdGluZyB0aGlzIHJpZ2h0IG5vd1xuICAgIFxuICAgIHNpemVfdCBvZmZzZXQgPSAweDQwMDAwMDtcbiAgICBzaXplX3QgYnl0ZXNfbGVmdCA9IDB4MTM0OTAwMCAtIDB4NDAwMDAwOyAvLyB0aGlzIGlzIGFsd2F5cyB0aGUgY29kZSBtZW1vcnkgcmFuZ2Ugb24gdGhlIHRhcmdldCBwcm9ncmFtXG4gICAgbG9jYWxbMF0uaW92X2Jhc2UgPSBsb2M7XG4gICAgbG9jYWxbMF0uaW92X2xlbiA9IDQwOTY7XG4gICAgcmVtb3RlWzBdLmlvdl9iYXNlID0gKHZvaWQqKTB4NDAwMDAwO1xuICAgIHJlbW90ZVswXS5pb3ZfbGVuID0gMjA0ODtcbiAgICByZW1vdGVbMV0uaW92X2Jhc2UgPSAodm9pZCopMHg0MDIwNDg7XG4gICAgcmVtb3RlWzFdLmlvdl9sZW4gPSAyMDQ4O1xuICAgIHNpemVfdCB0b3RhbCA9IDA7XG4gICAgXG4gICAgcHJpbnRmKFwiRUlOVkFMOiAlZFxcbkVGQVVMVDogJWRcXG5FTk9NRU06ICVkXFxuRVBFUk06ICVkXFxuRVNSQ0g6ICVkXFxuXFxuXCIsIEVJTlZBTCwgRUZBVUxULCBFTk9NRU0sIEVQRVJNLCBFU1JDSCk7XG4gICAgXG4gICAgZG9cbiAgICB7XG4gICAgICAgIGxvY2FsWzBdLmlvdl9sZW4gPSBieXRlc19sZWZ0ID49IDQwOTYgPyA0MDk2IDogYnl0ZXNfbGVmdDtcbiAgICAgICAgcmVtb3RlWzBdLmlvdl9iYXNlID0gKHZvaWQqKW9mZnNldDtcbiAgICAgICAgcmVtb3RlWzBdLmlvdl9sZW4gPSBieXRlc19sZWZ0ID49IDIwNDggPyAyMDQ4IDogYnl0ZXNfbGVmdDtcbiAgICAgICAgb2Zmc2V0ICs9IDIwNDg7XG4gICAgICAgIHJlbW90ZVsxXS5pb3ZfYmFzZSA9ICh2b2lkKilvZmZzZXQ7XG4gICAgICAgIHJlbW90ZVsxXS5pb3ZfbGVuID0gYnl0ZXNfbGVmdCAtIDIwNDggPj0gMjA0OCA/IDIwNDggOiAoYnl0ZXNfbGVmdCAtIDIwNDggPj0gMCA/IGJ5dGVzX2xlZnQgLSAyMDQ4IDogMCk7XG4gICAgICAgIG9mZnNldCArPSAyMDQ4O1xuICAgICAgICBucmVhZCA9IHByb2Nlc3Nfdm1fcmVhZHYocGlkLCBsb2NhbCwgMSwgcmVtb3RlLCAyLCAwKTtcbiAgICAgICAgYnl0ZXNfbGVmdCAtPSBucmVhZDtcbiAgICAgICAgdG90YWwgKz0gbnJlYWQ7XG4gICAgICAgIGlmIChucmVhZCAhPSBsb2NhbFswXS5pb3ZfbGVuKVxuICAgICAgICB7XG4gICAgICAgICAgICBwcmludGYoXCJlcnJubyAlZFxcblwiLCBlcnJubyk7XG4gICAgICAgICAgICBwcmludGYoXCIlenUgcmVhZCBiZWZvcmUgZXJybm9cXG5cIiwgdG90YWwpO1xuICAgICAgICAgICAgcmV0dXJuIDE7XG4gICAgICAgIH1cbiAgICB9XG4gICAgd2hpbGUgKGJ5dGVzX2xlZnQpO1xuICAgIFxuICAgIHByaW50ZihcImJ5ZVxcblwiKTtcbiAgICByZXR1cm4gMDtcbn1cbiIsImNvbXBpbGVycyI6W3siaWQiOiJnMTIyIiwib3B0aW9ucyI6Ii1mc2FuaXRpemU9YWRkcmVzcyJ9XSwiZXhlY3V0b3JzIjpbeyJhcmd1bWVudHMiOiIiLCJjb21waWxlciI6eyJpZCI6ImcxMjIiLCJsaWJzIjpbXSwib3B0aW9ucyI6Ii1mc2FuaXRpemU9YWRkcmVzcyJ9LCJzdGRpbiI6IiJ9XX1dfQ==) (embedded as it's quite large, copy link and paste somewhere to see full contents) leads to a page not found error message.

The base64 encoded json is the following:
```json
{
  "sessions": [
    {
      "id": 0,
      "language": "c++",
      "source": "#include <stdio.h>\n#include <string>\n#include <sys/uio.h>\n#include <errno.h>\n\nint main()\n{\n    std::string s; // segfault if this line isn't commented out\n    \n    struct iovec local[1];\n    struct iovec remote[1];\n    char rem1[2048];\n    char rem2[2048];\n    char loc[4096];\n    ssize_t nread = 0;\n    pid_t pid = 41315; // hard coded because I'm just testing this right now\n    \n    size_t offset = 0x400000;\n    size_t bytes_left = 0x1349000 - 0x400000; // this is always the code memory range on the target program\n    local[0].iov_base = loc;\n    local[0].iov_len = 4096;\n    remote[0].iov_base = (void*)0x400000;\n    remote[0].iov_len = 2048;\n    remote[1].iov_base = (void*)0x402048;\n    remote[1].iov_len = 2048;\n    size_t total = 0;\n    \n    printf(\"EINVAL: %d\\nEFAULT: %d\\nENOMEM: %d\\nEPERM: %d\\nESRCH: %d\\n\\n\", EINVAL, EFAULT, ENOMEM, EPERM, ESRCH);\n    \n    do\n    {\n        local[0].iov_len = bytes_left >= 4096 ? 4096 : bytes_left;\n        remote[0].iov_base = (void*)offset;\n        remote[0].iov_len = bytes_left >= 2048 ? 2048 : bytes_left;\n        offset += 2048;\n        remote[1].iov_base = (void*)offset;\n        remote[1].iov_len = bytes_left - 2048 >= 2048 ? 2048 : (bytes_left - 2048 >= 0 ? bytes_left - 2048 : 0);\n        offset += 2048;\n        nread = process_vm_readv(pid, local, 1, remote, 2, 0);\n        bytes_left -= nread;\n        total += nread;\n        if (nread != local[0].iov_len)\n        {\n            printf(\"errno %d\\n\", errno);\n            printf(\"%zu read before errno\\n\", total);\n            return 1;\n        }\n    }\n    while (bytes_left);\n    \n    printf(\"bye\\n\");\n    return 0;\n}\n",
      "compilers": [
        {
          "id": "g122",
          "options": "-fsanitize=address"
        }
      ],
      "executors": [
        {
          "arguments": "",
          "compiler": {
            "id": "g122",
            "libs": [],
            "options": "-fsanitize=address"
          },
          "stdin": ""
        }
      ]
    }
  ]
}
```

### Steps to reproduce

1. Visit [here](https://godbolt.org/clientstate/eyJzZXNzaW9ucyI6W3siaWQiOjAsImxhbmd1YWdlIjoiYysrIiwic291cmNlIjoiI2luY2x1ZGUgPHN0ZGlvLmg+XG4jaW5jbHVkZSA8c3RyaW5nPlxuI2luY2x1ZGUgPHN5cy91aW8uaD5cbiNpbmNsdWRlIDxlcnJuby5oPlxuXG5pbnQgbWFpbigpXG57XG4gICAgc3RkOjpzdHJpbmcgczsgLy8gc2VnZmF1bHQgaWYgdGhpcyBsaW5lIGlzbid0IGNvbW1lbnRlZCBvdXRcbiAgICBcbiAgICBzdHJ1Y3QgaW92ZWMgbG9jYWxbMV07XG4gICAgc3RydWN0IGlvdmVjIHJlbW90ZVsxXTtcbiAgICBjaGFyIHJlbTFbMjA0OF07XG4gICAgY2hhciByZW0yWzIwNDhdO1xuICAgIGNoYXIgbG9jWzQwOTZdO1xuICAgIHNzaXplX3QgbnJlYWQgPSAwO1xuICAgIHBpZF90IHBpZCA9IDQxMzE1OyAvLyBoYXJkIGNvZGVkIGJlY2F1c2UgSSdtIGp1c3QgdGVzdGluZyB0aGlzIHJpZ2h0IG5vd1xuICAgIFxuICAgIHNpemVfdCBvZmZzZXQgPSAweDQwMDAwMDtcbiAgICBzaXplX3QgYnl0ZXNfbGVmdCA9IDB4MTM0OTAwMCAtIDB4NDAwMDAwOyAvLyB0aGlzIGlzIGFsd2F5cyB0aGUgY29kZSBtZW1vcnkgcmFuZ2Ugb24gdGhlIHRhcmdldCBwcm9ncmFtXG4gICAgbG9jYWxbMF0uaW92X2Jhc2UgPSBsb2M7XG4gICAgbG9jYWxbMF0uaW92X2xlbiA9IDQwOTY7XG4gICAgcmVtb3RlWzBdLmlvdl9iYXNlID0gKHZvaWQqKTB4NDAwMDAwO1xuICAgIHJlbW90ZVswXS5pb3ZfbGVuID0gMjA0ODtcbiAgICByZW1vdGVbMV0uaW92X2Jhc2UgPSAodm9pZCopMHg0MDIwNDg7XG4gICAgcmVtb3RlWzFdLmlvdl9sZW4gPSAyMDQ4O1xuICAgIHNpemVfdCB0b3RhbCA9IDA7XG4gICAgXG4gICAgcHJpbnRmKFwiRUlOVkFMOiAlZFxcbkVGQVVMVDogJWRcXG5FTk9NRU06ICVkXFxuRVBFUk06ICVkXFxuRVNSQ0g6ICVkXFxuXFxuXCIsIEVJTlZBTCwgRUZBVUxULCBFTk9NRU0sIEVQRVJNLCBFU1JDSCk7XG4gICAgXG4gICAgZG9cbiAgICB7XG4gICAgICAgIGxvY2FsWzBdLmlvdl9sZW4gPSBieXRlc19sZWZ0ID49IDQwOTYgPyA0MDk2IDogYnl0ZXNfbGVmdDtcbiAgICAgICAgcmVtb3RlWzBdLmlvdl9iYXNlID0gKHZvaWQqKW9mZnNldDtcbiAgICAgICAgcmVtb3RlWzBdLmlvdl9sZW4gPSBieXRlc19sZWZ0ID49IDIwNDggPyAyMDQ4IDogYnl0ZXNfbGVmdDtcbiAgICAgICAgb2Zmc2V0ICs9IDIwNDg7XG4gICAgICAgIHJlbW90ZVsxXS5pb3ZfYmFzZSA9ICh2b2lkKilvZmZzZXQ7XG4gICAgICAgIHJlbW90ZVsxXS5pb3ZfbGVuID0gYnl0ZXNfbGVmdCAtIDIwNDggPj0gMjA0OCA/IDIwNDggOiAoYnl0ZXNfbGVmdCAtIDIwNDggPj0gMCA/IGJ5dGVzX2xlZnQgLSAyMDQ4IDogMCk7XG4gICAgICAgIG9mZnNldCArPSAyMDQ4O1xuICAgICAgICBucmVhZCA9IHByb2Nlc3Nfdm1fcmVhZHYocGlkLCBsb2NhbCwgMSwgcmVtb3RlLCAyLCAwKTtcbiAgICAgICAgYnl0ZXNfbGVmdCAtPSBucmVhZDtcbiAgICAgICAgdG90YWwgKz0gbnJlYWQ7XG4gICAgICAgIGlmIChucmVhZCAhPSBsb2NhbFswXS5pb3ZfbGVuKVxuICAgICAgICB7XG4gICAgICAgICAgICBwcmludGYoXCJlcnJubyAlZFxcblwiLCBlcnJubyk7XG4gICAgICAgICAgICBwcmludGYoXCIlenUgcmVhZCBiZWZvcmUgZXJybm9cXG5cIiwgdG90YWwpO1xuICAgICAgICAgICAgcmV0dXJuIDE7XG4gICAgICAgIH1cbiAgICB9XG4gICAgd2hpbGUgKGJ5dGVzX2xlZnQpO1xuICAgIFxuICAgIHByaW50ZihcImJ5ZVxcblwiKTtcbiAgICByZXR1cm4gMDtcbn1cbiIsImNvbXBpbGVycyI6W3siaWQiOiJnMTIyIiwib3B0aW9ucyI6Ii1mc2FuaXRpemU9YWRkcmVzcyJ9XSwiZXhlY3V0b3JzIjpbeyJhcmd1bWVudHMiOiIiLCJjb21waWxlciI6eyJpZCI6ImcxMjIiLCJsaWJzIjpbXSwib3B0aW9ucyI6Ii1mc2FuaXRpemU9YWRkcmVzcyJ9LCJzdGRpbiI6IiJ9XX1dfQ==)

### Expected behavior

The base64 encoded json input should be parsed.

**Comment by jeremy-rifkin** [comment]
Thank you for the report @Headline, looks like the issue is that the base64 slug contains forward slashes in it. Looking into a fix on our end.

**Comment by Headline** [comment]
> Thank you for the report @Headline, looks like the issue is that the base64 slug contains forward slashes in it. Looking into a fix on our end.

Oh, I see! Should I be encoding this differently on my end?

**Comment by jeremy-rifkin** [comment]
I think you should be good, `/` is a valid base64 character

**Comment by jeremy-rifkin** [comment]
Fix is live
