### ISSUE TITLE
[BUG]:  COBOL: options "compile/link to binary" not working

### ISSUE THREAD

**Issue by GitMensch** [compiler-explorer/compiler-explorer#4857]
### Describe the bug

Filter "compile to binary" not working

### Steps to reproduce

1. Visit gotbold.org
2. choose COBOL
3. see assembler
4. change filter to enable "compile to binary"
5. see "<No output: objdump returned 255>"

### Expected behavior

Assembly output shown.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by GitMensch** [comment]
Is there any option to tell the bot to add the lang-cobol tag?

**Comment by dkm** [comment]
Confirmed, see https://c.godbolt.org/z/Wjaef1oqr
