### ISSUE TITLE
[LANGUAGE REQUEST]: BatchScript

### ISSUE THREAD

**Issue by pandasoli** [compiler-explorer/compiler-explorer#4873]
### Language name

BatchScript

### Language version

10.0.19043.1288

### Compiler homepage

...

### Compiler version

Microsoft Windows CMD.exe version 10.0.19043.1288

### Motivation

The tool already have **Bash Script**, and I miss **Bach Script**.  
This is the language that windows runs on the `cmd.exe`.

I don't know what you use to run the languages this tool supports, but as it supports **Bash Script** I would say your machine is **Linux**, if it is, I didn't find any good **Batch** interpreters, but I hope you know how to do it.

**Comment by matsjla** [comment]
Hi, thanks for the request!

We currently don't support Bash scripts, and I'm not quite sure how we'd display anything for bash/batch scripts (they are just interpreted). Do you have any more context you can give?

**Comment by pandasoli** [comment]
So I'm sorry, I talked to the guys how made a Discord bot that compile/interprete languages, and they have Bash.  
But the replied to my issue saying they use this tool and another one.

Thank you!
