### ISSUE TITLE
[BUG]: `/**/` style comments after code/directives in asssemly mode do not syntax highlight correctly

### ISSUE THREAD

**Issue by dragonmux** [compiler-explorer/compiler-explorer#4876]
### Describe the bug

While [poking this bit of curséd](https://godbolt.org/z/d4nhnqrec) we found that if putting `/**/` style comments after assembler directives of code, syntax highlighting will not work on them.

### Steps to reproduce

1. Visit godbolt.org
2. Switch into assembly mode w/ binutils (gas) as the assembler
3. Write an assembler directive such as `.att_syntax` or assembly such as `xor rax, rax` then follow it by a comment on the same line such as `/* Switch to AT&T syntax */` or `/* zero rax */`

### Expected behavior

The `/**/` style comment gets syntax highlighted green

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
I think this would be a good first issue for anyone looking to contribute

Our asm syntax highlighting rules are defined in https://github.com/compiler-explorer/compiler-explorer/blob/main/static/modes/asm-mode.ts

Documentation on monaco syntax highlighting rules can be found at https://microsoft.github.io/monaco-editor/monarch.html

A helpful tip for debugging monaco syntax highlighting is to hit F1 -> "Developer: Inspect Tokens" in the editor in CE.

**Comment by SiyaoIsHiding** [comment]
Woah thank you very much you always give super useful guidance for good first issues. Gonna work on it right now.

**Comment by jeremy-rifkin** [comment]
Thanks @SiyaoIsHiding, let us know if you run into any issues!

**Comment by dragonmux** [comment]
Looks to be working, thank you for fixing this!
