### ISSUE TITLE
[BUG]: "Settings > Editor > Tab width" ignored

### ISSUE THREAD

**Issue by cherusker** [compiler-explorer/compiler-explorer#4877]
### Describe the bug

Tab width is being ignored (and set to `4` spaces) in the source editor.

### Steps to reproduce

- open https://godbolt.org in an incognito window (tested with Firefox + Chrome)
- leave all settings on default, set the tab width to `2`
- clear the default text in the source editor
- type `int main() {` and press the enter key
- observe how the indentation is **4** spaces

### Expected behavior

- observe how the indentation is **2** spaces

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
This is strange. https://github.com/compiler-explorer/compiler-explorer/blob/26395eb53a02379415d6b71813f37ab481461d4c/static/panes/editor.ts#L1256-L1259 is running properly with the correct value but the editor isn't respecting the tab size.

**Comment by jeremy-rifkin** [comment]
Ah, we have to set indentSize too
