### ISSUE TITLE
Add new Kalray compiler

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#4880]
@dkm : this pull request is now merged. It can be used in godbolt.

_Originally posted by @XavierRaynaud in https://github.com/kalray/build-scripts/issues/61#issuecomment-1471553030_

**Comment by hominhquan** [comment]
It seems to be managed automatically in https://github.com/compiler-explorer/infra/blob/9905b1a3234703ff2d4cdcf9e5e9f6b63c266037/bin/yaml/cpp.yaml#L421 ?

There are so two PRs to be created each time we are bumping a version ?

**Comment by hominhquan** [comment]
okay, understood. I'll try to do this exercise (for the first time). I'll ping you when PRs are submitted.

**Comment by dkm** [comment]
Sure!

**Comment by hominhquan** [comment]
@dkm The two PRs have been submitted. Please feel free to feedback :)

**Comment by dkm** [comment]
And before you ask @hominhquan: everything is merged and you only have to wait for someone to do a release of the site (take the master branch and use it for the website). Should be a small wait, and a comment will be added when it's live. Thanks for doing this, I'll let you do the following updates on your own :)

**Comment by dkm** [comment]
This is now live! :rocket:

**Comment by XavierRaynaud** [comment]
thanks a lot.
