### ISSUE TITLE
[BUG]: <Compilation failed: Bad Gateway>on all MSVC Compilers

### ISSUE THREAD

**Issue by r-christie** [compiler-explorer/compiler-explorer#4881]
### Describe the bug

Selecting any MSVC compiler from the list of compilers, on basic valid helloworld code shows the error:

<Compilation failed: Bad Gateway> instead of compiling the code. Other compilers seem fine.

### Steps to reproduce

Visit godbolt
Select any MSVC compiler from the list of compilers
Use any basic valid helloworld code in the code window

Compiler output panel shows:
`<Compilation failed: Bad Gateway> `

instead of compiling the code. Other compilers seem fine.

### Expected behavior

MSVC compiler should compile the code

### Reproduction link

https://godbolt.org/z/b7s6fcMnW

### Screenshots

Not applicable

### Operating System

Windows 10 Enterprise

### Browser version

Firefox 110.0.1

**Comment by jeremy-rifkin** [comment]
Unfortunately the microsoft compilers have been having some trouble lately. If you go to https://www.godbolt.ms/ you’ll see a 502 gateway error. They should be back soon.
