### ISSUE TITLE
[BUG]: Popup with error when adding Editor

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#4889]
### Describe the bug

When clicking Add... ->  Source Editor

This error pops up:
![Screenshot from 2023-03-20 11-57-47](https://user-images.githubusercontent.com/442630/226320249-93c61924-3c1c-4a55-8d6b-7a32131da0e5.png)

### Steps to reproduce

-

### Expected behavior

Error should not be happening.
Editor does get added without issues aside from the popup, but c++ is always selected no matter what my Default language is.

Should actually select the default language by default. (obviously)

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by dkm** [comment]
This is now live! :rocket:
