### ISSUE TITLE
[BUG]: **vscode compiler-explorer extension** `clang` bug

### ISSUE THREAD

**Issue by NEX-S** [compiler-explorer/compiler-explorer#4895]
### Describe the bug

clang1600                             | x86-64 clang 16.0.0
llvmas1600                            | x86-64 clang 16.0.0
cclang1600                            | x86-64 clang 16.0.0

sometimes don't have highlight to ASM with the cursor and sometimes compile failed

### Steps to reproduce

vscode settings:
```json
"compiler-explorer.url": "https://godbolt.org",
    "compiler-explorer.compiler": "clang1600",
    "compiler-explorer.debug": false,
    "compiler-explorer.options": "",
```

test.c
```c
#include <stdio.h>

void func (void) {
	printf("Hello");
}
```

### Expected behavior

seems everything's fine in compiler "g122"

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Arch Linux

**Comment by partouf** [comment]
Can't really reproduce this on the website itself, so it's probably better to report this issue here https://github.com/MRobertEvers/vscode-compiler-explorer
