### ISSUE TITLE
[BUG]: Non-WINE MSVC compilers have category `other` instead of category `msvc`

### ISSUE THREAD

**Issue by PhilipBAdams** [compiler-explorer/compiler-explorer#4899]
### Describe the bug

WINE MSVC compilers are under category 'msvc', but non-wine MSVC compilers are under category 'other'

### Steps to reproduce

1. Visit godbolt.org
2. Select the 'pop-out view' for compiler selection
3. Apply category 'msvc' 

### Expected behavior

MSVC x86, x64, and arm64 versions should be visible

### Reproduction link

Not applicable

### Screenshots

![image](https://user-images.githubusercontent.com/35666630/227074268-dbb7d865-d6d9-4486-9939-ea159634557f.png)

**Comment by jeremy-rifkin** [comment]
Indeed, we're waiting on MS to update their config to take advantage of the new `compilerCategories` property

**Comment by jeremy-rifkin** [comment]
We're now hosting MSVC compilers and the compilers show up in the correct category
