### ISSUE TITLE
[COMPILER REQUEST]: MSVC version 17.5

### ISSUE THREAD

**Issue by rboxman** [compiler-explorer/compiler-explorer#4902]
### Compiler name

x64 MSVC v19.35

### Compiler version

17.5 (or 19.35)

### Compiler language

C++

### Compiler homepage

https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#visual-studio-2022-version-175-releases

### Motivation

In order to properly file bugs and explore platform differences, it's necessary to test against the latest version to see if things have been fixed, made worse, or otherwise changed.

I tried filing an issue on Microsoft first since I thought they maintained those compilers:
https://developercommunity.visualstudio.com/t/Update-compilers-on-Compiler-Explorer--/10318410

But I guess not according to their response?

**Comment by rboxman** [comment]
This seems fixed...

**Comment by mattgodbolt** [comment]
Thanks for checking!
