### ISSUE TITLE
[COMPILER REQUEST]: m68k cross gcc

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#4904]
### Compiler name

gcc

### Compiler version

*

### Compiler language

*

### Compiler homepage

*

### Motivation

m68k is still used, in particular in retro projects :)

ct-ng has some sample conf, so should not be very hard to add.

**Comment by glaubitz** [comment]
Can we get LLVM M68k added as well? The M68k backend can be enabled in recent versions of LLVM as an experimental feature.

**Comment by dkm** [comment]
> Can we get LLVM M68k added as well? The M68k backend can be enabled in recent versions of LLVM as an experimental feature.

We probably can if it's only a matter of adding it to the list of enable backends

**Comment by glaubitz** [comment]
> > Can we get LLVM M68k added as well? The M68k backend can be enabled in recent versions of LLVM as an experimental feature.
> 
> We probably can if it's only a matter of adding it to the list of enable backends

Yes, it's enough to pass `-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=M68k` to cmake when configuring LLVM.

**Comment by dkm** [comment]
I should be able to add m68k along with the GCC 13.1.0 update (see https://github.com/compiler-explorer/gcc-cross-builder/pull/54), local build looks fine.

**Comment by glaubitz** [comment]
Awesome, thanks a lot!

**Comment by dkm** [comment]
clang build: https://github.com/compiler-explorer/infra/actions/runs/4839134081

**Comment by dkm** [comment]
FYI, current clang trunk has m68k (so you can already use it by providing `-target`).
I'm really close to merging my cross gcc 13.1 config changes that also add the cross-gcc for m68k + the config to have clang m68k listed in the compilers.

**Comment by dkm** [comment]
This is live :rocket:

**Comment by glaubitz** [comment]
Thanks. I did a quick run but currently it still seems to be missing the necessary development headers.

**Comment by dkm** [comment]
Can you be more specific?

**Comment by glaubitz** [comment]
I cannot compile a simple "Hello World" program such as:

```c++
#include <iostream>

int main () {
      cout << "Hello World!" << endl;
      return 0;
}
```

**Comment by dkm** [comment]
Ah, correct. The ct-ng sample config only builds a `m68k-unknown-elf` without any libc.
Can I expect to have newlib build for this target? Maybe I can try...
