### ISSUE TITLE
[BUG]: Can't dismiss pink banner

### ISSUE THREAD

**Issue by cjdb** [compiler-explorer/compiler-explorer#4918]
### Describe the bug

I can't dismiss the "Now in Pink" banner without turning my editor pink. This is very distracting and affects my ability to concentrate.

### Steps to reproduce

Go to Compiler Explorer and not be in pink mode.

### Expected behavior

Should be able to dismiss the notification.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment]
Thanks! An oversight on our part: we should have had a little close icon/no thanks type thing. This was a plan just for today anyway: one way or another you'll not see the banner soon.

**Comment by jeremy-rifkin** [comment]
A close button is now live
