### ISSUE TITLE
[BUG]: The UI looks strange on Edge, with characters separated by line breaks

### ISSUE THREAD

**Issue by LukaMod** [compiler-explorer/compiler-explorer#4923]
### Describe the bug

but it looks fine on Chrome

When I modify any setting, such as 'Add New => compiler', the UI returns to normal

### Steps to reproduce

1. Visit https://godbolt.org/ on Edge

### Expected behavior

the code displays normally

### Reproduction link

Not applicable

### Screenshots

![image](https://user-images.githubusercontent.com/13666451/229333662-33210bcf-beb1-495b-8b52-4e8e075a463f.png)

after click “**Add New => compiler**"

![image](https://user-images.githubusercontent.com/13666451/229334340-24408cf9-bc1e-4ff2-8a3a-ed58807b3a3b.png)

### Operating System

win11

### Browser version

Microsoft Edge 111.0.1661.62（Official Build）（64-bit）

**Comment by jeremy-rifkin** [comment]
Thanks for the report. I can't reproduce this but I have ran into this locally a while back. I think something was briefly messed up during some refactoring that was being done and it corrupted states or settings. When I ran into it I was able to get it to go away by resizing the editor too.

Can you try clearing your cache and local storage for CE and see if the issue persists?

**Comment by LukaMod** [comment]
Clearing local storage solved the problem, but I have encountered this issue on both of my PCs
