### ISSUE TITLE
[BUG]: objdump fails for all assemblers 

### ISSUE THREAD

**Issue by sdkrystian** [compiler-explorer/compiler-explorer#4925]
### Describe the bug

No disassembly is produced with any assembler (GNU as, llvmas, NASM, etc.); instead, objdump exits with code 1. The object file itself is being produced (readelf -a shows expected output). I suspect this relates to the recent commits which affect how arguments are passed to objdump. 

### Steps to reproduce

See attached link

### Expected behavior

Not applicable 

### Reproduction link

https://godbolt.org/z/h791qh3s5

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
Thanks for the report, confirmed

**Comment by mattgodbolt** [comment]
This might be fixed in the latest deploy: unable to confirm right now but I made some fixes

**Comment by partouf** [comment]
I think this is fixed?

**Comment by sdkrystian** [comment]
Yup, it's fixed.
