### ISSUE TITLE
[BUG]: stdout not visible in Pink theme

### ISSUE THREAD

**Issue by andrew-kay-oxb** [compiler-explorer/compiler-explorer#4926]
### Describe the bug

Pink theme is pretty, but stdout appears as white on white on my monitor.

### Steps to reproduce

1. Select pink theme
2. execute in main: std::cout << "anything\n";
4. in execution pane, output is white on white

### Expected behavior

Expected black on pale pink, or dark pink on white, or something visible.

### Reproduction link

Not applicable

### Screenshots

![image](https://user-images.githubusercontent.com/103109002/229360251-7012a17f-8273-435b-b9ef-80b3883c3438.png)

### Operating System

Ubuntu 20.04.6 LTS \n \l, 64 bit

### Browser version

Firefox 111.0 (6 bit)

**Comment by jeremy-rifkin** [comment]
Thanks for the report!

**Comment by partouf** [comment]
fix is live
