### ISSUE TITLE
[BUG]: Demangling seems to be broken

### ISSUE THREAD

**Issue by philnik777** [compiler-explorer/compiler-explorer#4928]
### Describe the bug

Demangling is enabled, but identifiers are still mangled.

### Steps to reproduce

Visit godbolt.org and look at the assembly output

### Expected behavior

The identifiers should be demangled

### Reproduction link

https://godbolt.org/z/EcxGfc6M4

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
Thanks for the report, confirmed

**Comment by mattgodbolt** [comment]
Fix is now deployed! Sorry for that!
