### ISSUE TITLE
[REQUEST]: Use `llvm-cxxfilt` for clang

### ISSUE THREAD

**Issue by philnik777** [compiler-explorer/compiler-explorer#4929]
### Is your feature request related to a problem? Please describe

There are some clang-specific extension (e.g. `__attribute__((enable_if))`) that GCC's `c++filt` can't demangle.

### Describe the solution you'd like

Change the demangler for clang configurations to `llvm-cxxfilt`.

### Describe alternatives you've considered

It would also be possible to teach GCC's `c++filt` clang extensions, but that seems a lot harder to get through and would most likely always lag behind `llvm-cxxfilt` w.r.t. clang extensions.

### Additional context

Not applicable

**Comment by cjdb** [comment]
**Example program**

```cpp
#include <tuple>

int main()
{
    std::tuple<int> x;
}
```

**Expected output**

```asm
main:                                   # @main
        push    rbp
        mov     rbp, rsp
        sub     rsp, 16
        lea     rdi, [rbp - 4]
        call    std::__1::tuple<int>::tuple[abi:ne180000]<std::__1::__is_implicitly_default_constructible, std::__1::is_default_constructible, 0>()
        xor     eax, eax
        add     rsp, 16
        pop     rbp
        ret
```

**Actual output**

```asm
main:                                   # @main
        push    rbp
        mov     rbp, rsp
        sub     rsp, 16
        lea     rdi, [rbp - 4]
        call    _ZNSt3__15tupleIJiEEC2B8ne180000ITtTpTyENS_37__is_implicitly_default_constructibleETtTpTyENS_24is_default_constructibleETnNS_9enable_ifIXsr4_AndIT0_IJiEEEE5valueEiE4typeELi0EEEv
        xor     eax, eax
        add     rsp, 16
        pop     rbp
        ret
```

**Comment by OfekShilon** [comment]
@cjdb can you please share a link with the output you pasted? For me `c++filt` seems to be demangling as expected: https://godbolt.org/z/M17Mab5Pd

**Comment by philnik777** [comment]
@OfekShilon something like
```
void func() __attribute__((enable_if(true, ""))) {}
```
should demonstrate it

**Comment by jeremy-rifkin** [comment]
> @cjdb can you please share a link with the output you pasted? For me `c++filt` seems to be demangling as expected: https://godbolt.org/z/M17Mab5Pd

It looks like -stdlib=libc++ is needed to repro <https://godbolt.org/z/dPrfs7MTb>

**Comment by OfekShilon** [comment]
Thanks @jeremy-rifkin!! Do you know how changing stdlib can impact name mangling by the compiler?
Anyway, I'm now able to reproduce and test, and PR #6080 hopefully addresses this.

**Comment by cjdb** [comment]
> Thanks @jeremy-rifkin!! Do you know how changing stdlib can impact name mangling by the compiler? Anyway, I'm now able to reproduce and test, and PR #6080 hopefully addresses this.

Different standard library implementations use different conventions for things. For example, although you type `std::tuple<int>` as a user, libc++ defines it as `std::__1::tuple`, which will be mangled differently. I don't think libstdc++ uses this convention.

**Comment by partouf** [comment]
llvm-cxxfilt is now used for all our trunk clangs, we're looking at the other versions, but might take a while

**Comment by OfekShilon** [comment]
llvm-cxxfilt is now used for all clang flavours. Will be live at next deployment.
