### ISSUE TITLE
[COMPILER REQUEST]: Add support for the Intel 2023.1 compiler on x86-64 Linux

### ISSUE THREAD

**Issue by tahonermann** [compiler-explorer/compiler-explorer#4939]
### Compiler name

icx

### Compiler version

2023.1 x86-64 Linux

### Compiler language

C, C++, SYCL

### Compiler homepage

https://www.intel.com/content/www/us/en/developer/tools/oneapi/dpc-compiler.html

### Motivation

The 2023.1 release was made available on 2023-03-29.

**Comment by rscohn2** [comment]
Completed in #5173. You can tag me in  oneapi related issues because I do not monitor issues here.

**Comment by tahonermann** [comment]
This was completed back in July; closing.
