### ISSUE TITLE
[COMPILER REQUEST]: GCC SuperH cross compiler with GDB simulator

### ISSUE THREAD

**Issue by jscott0** [compiler-explorer/compiler-explorer#4956]
### Compiler name

gcc-sh-elf

### Compiler version

latest stable

### Compiler language

C

### Compiler homepage

https://tracker.debian.org/pkg/gcc-sh-elf

### Motivation

Hi,
I'm extremely biased: I'm the package maintainer, but I would like to inform you of my package for Debian (and descendants like Ubuntu) gcc-sh-elf. It's in the standard Debian repositories; you don't need to compile it. Several things make this compiler and setup special:

- The target is bare-metal, no OS, but the toolchain does use Newlib to provide the functions of an ISO C standard library.
- SuperH is a mostly open ISA; the majority of the patents have expired if not all.
- Even though this is bare-metal, there is a simulator provided by the package, sh-elf-run, that allows you to actually run the binaries! This includes being able to use standard I/O; a "hello world" runs fine under the simulator.

GCC 12 is in Debian unstable and will be in Debian Bookworm, GCC 13 is in experimental. In general, I will always keep the stable GCC release packaged, and you can parse the version number of the Debian package at any time to figure out the precise version. I concede that Newlib is a little out-of-date, but that's a goal that's being worked on.

Edit: It also supports advanced GCC features, like the stack protector.

**Comment by mattgodbolt** [comment]
Thanks for the suggestion! Unfortunately we don't use traditional package management solutions for our compilers for a variety of reasons. We'd be happy to support this compiler if it can fit in with our existing requirements - a tarball or similar that's relocatable and free of external dependencies.

**Comment by dkm** [comment]
Also, we already have sh cross-gcc build using ct-ng. How does your package compare to this feature-wise? We could tune our current config if needed (see https://github.com/compiler-explorer/gcc-cross-builder/blob/main/build/latest/sh-12.2.0.config for example).

**Comment by jscott0** [comment]
Oh, okay, I see that there probably isn't much interest for this compiler then. If a bare-metal target with simulator is sought, an ARM target would probably be more appropriate.
