### ISSUE TITLE
api not working

### ISSUE THREAD

**Issue by Zizar-Bog** [compiler-explorer/compiler-explorer#4960]
I read the API documentation I take from there json I put the request in Python, and it does not work, please help, below is the code:
``
import requests
import json

url = "https://godbolt.org/api/compiler/g82/compile"

data = {
    "source": "int main () { return 1; }",
    "compiler": "g82",
    "options": {
        "userArguments": "-O3",
        "executeParameters": {
            "args": ["arg1", "arg2"],
            "stdin": "hello, world!"
        },
        "compilerOptions": {
            "executorRequest": True
        },
        "filters": {
            "execute": True
        },
        "tools": [],
        "libraries": [
            {"id": "openssl", "version": "111c"}
        ]
    },
    "lang": "c++",
    "allowStoreCodeDebug": True
}

headers = {'Content-type': 'application/json'}

response = requests.post(url, data=json.dumps(data), headers=headers)

print(response.json()) 
``

**Comment by mattgodbolt** [comment]
You are missing the "Accept" header so Compiler Explorer is replying in text form:
```py
>>> print(response.text)
# Compilation provided by Compiler Explorer at https://godbolt.org/

# Compiler exited with result code 1
```

so, doing this, fixes it:
```py
>>> headers = {'Content-type': 'application/json', 'Accept': 'application/json'}
>>> response = requests.post(url, data=json.dumps(data), headers=headers)
>>> print(response.json())
{'code': 1, 'okToCache': True, 'timedOut': False, 'stdout': [], 'stderr': [], 'execTime': '150', 'processExecutionResultTime': 0.002931000664830208, 'didExecute': True, 'buildResult': {'inputFilename': '/tmp/compiler-explorer-compiler2023311-9273-1qq78mw.5qxc/example.cpp', 'code': 0, 'okToCache': True, 'timedOut': False, 'stdout': [], 'stderr': [], 'execTime': '637', 'processExecutionResultTime': 0.001459999941289425, 'downloads': [], 'executableFilename': '/tmp/compiler-explorer-compiler2023311-9273-1qq78mw.5qxc/output.s', 'compilationOptions': ['-g', '-o', '/tmp/compiler-explorer-compiler2023311-9128-1xyheld.2eco/output.s', '-fdiagnostics-color=always', '-O3', '/tmp/compiler-explorer-compiler2023311-9128-1xyheld.2eco/example.cpp', '-isystem/opt/compiler-explorer/libs/openssl/openssl_1_1_1c/x86_64/opt/include', '-L.', '-Wl,-rpath,.', '-Wl,-rpath,/opt/compiler-explorer/gcc-8.2.0/lib64', '-Wl,-rpath,/opt/compiler-explorer/gcc-8.2.0/lib32', '-Wl,-rpath,/opt/compiler-explorer/libs/openssl/openssl_1_1_1c/x86_64/opt/lib', '-Wl,-rpath,/opt/compiler-explorer/libs/openssl/openssl_1_1_1c/x86/opt/lib', '-L/opt/compiler-explorer/libs/openssl/openssl_1_1_1c/x86_64/opt/lib', '-L/opt/compiler-explorer/libs/openssl/openssl_1_1_1c/x86/opt/lib', '-lssl', '-lcrypto'], 'packageDownloadAndUnzipTime': '32'}}
```
