### ISSUE TITLE
[BUG]: Standard output parsed as compiler errors

### ISSUE THREAD

**Issue by HappyCerberus** [compiler-explorer/compiler-explorer#4963]
### Describe the bug

When using CE with an executor, some output seems to be parsed as compiler errors.

This leads to very confusing squiggly lines.

### Steps to reproduce

Demo: https://compiler-explorer.com/z/Gfx4K4x46

### Expected behavior

Probably should distinguish between stdout and stderr?

### Reproduction link

https://compiler-explorer.com/z/Gfx4K4x46

### Screenshots

https://imgur.com/KBwnedk

**Comment by jeremy-rifkin** [comment]
Hey, thanks for the report! We're currently tracking this at #4179 so I'll close in favor of that.
