### ISSUE TITLE
[BUG]: Can't hide hex output

### ISSUE THREAD

**Issue by Timmmm** [compiler-explorer/compiler-explorer#4965]
### Describe the bug

Ok this is really weird but the assembly output has the hex code for all the instructions between every line. I've tried every option but I can't turn it off. I even used Firefox's "clear cookies and other site data" option but it had no effect.

![image](https://user-images.githubusercontent.com/376842/232309376-77fa0a0f-6430-4c6c-b53f-3c3ed30dcf78.png)

### Steps to reproduce

I am not sure how this got turned on in the first place tbh.

### Expected behavior

There should be an option to turn this off. Probably in the `Output...` drop-down.

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Browser version

Firefox 102.9.0esr

**Comment by partouf** [comment]
This is the Output -> `Compile to binary object` or `Link to binary` option, when that's on there's no separate way to switch off the inline hex

**Comment by Timmmm** [comment]
That is greyed out and unchecked for me:

![image](https://user-images.githubusercontent.com/376842/232321835-576f3290-a0f6-49f5-baae-57fa1c579e7d.png)

**Comment by partouf** [comment]
I did mention "Link to binary", that's the one checked on

**Comment by Timmmm** [comment]
Ah right, that did the trick thanks! Probably could be clearer (I could have sworn I tried that) but never mind.

**Comment by jeremy-rifkin** [comment]
Agreed, we can probably do a better job on the ui here
