### ISSUE TITLE
Screenshot generation

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#498]
Would be great to support screenshots for snippets in tweets etc.

https://github.com/GoogleChrome/puppeteer might be a way to achieve this on the server?

**Comment by RabsRincon** [comment]
Yes yes! Once I get back I'll get into this. :)

Would all the page need to be rendered? Or should the top menu be excluded?

**Comment by mattgodbolt** [comment]
I think the embedded view should render nicely. Cool :)

**Comment by RabsRincon** [comment]
Note that this feature + unfurling = Awesome

**Comment by mattgodbolt** [comment]
Agreed... @RabsRincon I suspect this isn't in-progress at the moment?

**Comment by partouf** [comment]
Just closing this, I think we're good on the linking front and this would be fancy but not so useful.
