### ISSUE TITLE
[BUG]: Clicking "add new editor" gives "Unknown language specified for editor"

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#5006]
### Describe the bug

Clicking add editor on an editor gives an error. The error resolves ok, it's just an annoying popup.

### Steps to reproduce

On an editor pane, click add new and choose "Source Editor". Observe:

### Expected behavior

no error popup.

### Reproduction link

Not applicable

### Screenshots

Not applicable![image](https://user-images.githubusercontent.com/633973/235144391-fa8aa503-eb0d-4874-9ba1-088cadd2533d.png)

**Comment by partouf** [comment]
this is when your default language is somehow empty

**Comment by mattgodbolt** [comment]
So it is!
![image](https://user-images.githubusercontent.com/633973/235148516-4875ad91-00f7-47e3-956b-4dc0bb59c499.png)
