### ISSUE TITLE
Filtering bug for code involving std::function

### ISSUE THREAD

**Issue by jeremy-rifkin** [compiler-explorer/compiler-explorer#5020]
In https://godbolt.org/z/efxaKh311 the `std::_Function_handler<void (), main::{lambda()#1}>::_M_invoke(std::_Any_data const&):` label is filtered out as a directive, leaving some code at the top of the compiler output that's not attached to any function.

```x86asm
        mov     rdi, QWORD PTR [rdi]
        jmp     fclose
```

**Comment by partouf** [comment]
We have parsing code that backtracks and deletes the label if it's not your own code, but it does not read all the attributions, just the first one https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/parsers/asm-parser.ts#L509

(so unchecking Library filter will work too)

Not sure how to fix

**Comment by partouf** [comment]
Maybe the quick and dirty solution would be to remember the deleted label and reintroduce it when we suddenly see user code and it doesn't have a label, but that probably wouldn't work in every case or differently ordered situations

**Comment by dwblaikie** [comment]
copying over my comment from https://reviews.llvm.org/D147506#4362969 :

 what's godbolt doing - scanning the .debug_line table only? & checking the first entry related to the function symbol/label? If it could scan through the whole function's line table and check if any of the code came from the user's code, that might be an option? (though it could still end up detecting library functions - like templates that are instantiated with user defined types that then get inlined)

If you wanted to reliably detect functions defined in the user's source code, you'd have to use more than just the .debug_line section, you'd have to use the .debug_info section - Symbolizing just the starting address, then iterating up any stack frames you get (in case you get more than one, which would happen if the first instruction were inlined, for instance) and checking the function name/the file it's declared in is the file you're interested in.

**Comment by partouf** [comment]
> copying over my comment from https://reviews.llvm.org/D147506#4362969 :
> 
> what's godbolt doing - scanning the .debug_line table only? & checking the first entry related to the function symbol/label? If it could scan through the whole function's line table and check if any of the code came from the user's code, that might be an option? (though it could still end up detecting library functions - like templates that are instantiated with user defined types that then get inlined)
> 
> If you wanted to reliably detect functions defined in the user's source code, you'd have to use more than just the .debug_line section, you'd have to use the .debug_info section - Symbolizing just the starting address, then iterating up any stack frames you get (in case you get more than one, which would happen if the first instruction were inlined, for instance) and checking the function name/the file it's declared in is the file you're interested in.

We don't parse any debug tables, we parse the assembly generated by the compiler sequentially line by line (and then specifically `.file` and `.loc` directives here for drawing the relation with the sourcecode lines and being able to filter between user code and library code).

We do this because every compiler emits their assembly differently. And javascript restricts the amount of computing we can do on this for backtracking, though it might be possible. I also did just try to first collect the proc lines and filter afterwards, but that screws up filtering for compilers that do not emit any usable debug info. Still might be possible if we just apply it to Clang assembly.

This is different from objdumps from generated binary, then we always know what's what and there's a clear separation between everything.

**Comment by dwblaikie** [comment]
hmm - so you're looking at the assembly from the user's code - but trying to skip over things like template instantiations or inline functions from included headers that aren't part of the user's code.

Yeah, if you could backtrack a bit, in some sense - keep track of the last public label (without the "." at the start) and if you see any .line directive from a user's source file then render everything from that last label to the next label.

(this will still catch template instantiations that have some user code in them - I don't think you can avoid that without looking at the .debug_info contents)
