### ISSUE TITLE
[BUG]: all go gc (tip) backends are old

### ISSUE THREAD

**Issue by egonelbre** [compiler-explorer/compiler-explorer#5034]
### Describe the bug

It seems that `x86-64 gc (tip)` and `arm64 gc (tip)` and other `(tip)` backends are very old.

The info button indicates that the compiler was compiled in the year 2021.

### Steps to reproduce

1. Go to godbolt
2. Select `x86-64 gc go.tip` backend
3. Press "Info" button in the compiler pane
4. Notice the date and commit hash.

### Expected behavior

I would expect the `go (tip)` to be relatively up to date, something like at most a week old. I definitely wouldn't expect `go (tip)` to be older than the latest stable release.

If keeping those backends up to date is problematic, maybe it would be possible to either rename or hide them altogether, because otherwise they can cause confusion.

### Reproduction link

Not applicable

### Screenshots

<img width="632" alt="Screenshot 2023-05-10 at 08 07 10" src="https://github.com/compiler-explorer/compiler-explorer/assets/192964/22acd55b-abcd-4576-a89a-813bbb837791">

**Comment by dkm** [comment]
I'll have a look if the builder is still in a working state (I only discover it today), and if it is, I'll see to add it to our daily builds

**Comment by dkm** [comment]
https://github.com/compiler-explorer/infra/actions/runs/5297836460 <- this is a manual build of `master` branch. It should work and update the current `go (tip)` compiler. If result is OK, I'll add the nightly build of go master.

**Comment by dkm** [comment]
Oh, `go` was supposed to be built nightly, but a small piece was missing. Current compiler should be up to date (don't rely on the tooltip, it's not refreshed, so it will show whatever version was installed when the node was started), and nightly magic should happen starting tonight.

**Comment by dkm** [comment]
After looking a bit more, the builder is already triggered everyday. Will fix the shell error and clean the script a bit, hopefully this will fix the build.
