### ISSUE TITLE
m68k is missing libc/libstdc++

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#5037]
Thanks. I did a quick run but currently it still seems to be missing the necessary development headers.

_Originally posted by @glaubitz in https://github.com/compiler-explorer/compiler-explorer/issues/4904#issuecomment-1541822094_

**Comment by dkm** [comment]
local compiler with newlib works correctly. Now rebuilding it before installing it: https://github.com/compiler-explorer/infra/actions/runs/4936703628

**Comment by dkm** [comment]
https://c.godbolt.org/z/qxsP39Mco
a bit better

**Comment by partouf** [comment]
Toolchain should get you half the way, you sometimes also have to supply sysroot. See #5001

**Comment by glaubitz** [comment]
> Toolchain should get you half the way, you sometimes also have to supply sysroot. See #5001

On a system with `debootstrap` and `qemu-m68k-static` installed, this is fairly simple:

```
# debootstrap --no-check-gpg --arch=m68k --variant=buildd \
              --include=debian-ports-archive-keyring \
                unstable sysroot-m68k \
                http://ftp.ports.debian.org/debian-ports
```

**Comment by dkm** [comment]
Tried quickly `sysroot` but that is still not ok. Maybe I'm not using it correctly? https://c.godbolt.org/z/64sYdcEMK
 
@glaubitz we don't really use this kind of installation...

**Comment by partouf** [comment]
the m86 gcc directory doesn't seem to contain a sysroot dir

**Comment by dkm** [comment]
Ok... And ct-ng doesn't allow me to build a sysroot, probably because it's a bare toolchain...

**Comment by dkm** [comment]
I'll close this one, as I don't see a quick fix... Or is it really an issue for you @glaubitz ? I really don't know what people are expecting from an m68k toolchain

**Comment by glaubitz** [comment]
On May 10, 2023, at 7:15 PM, Marc Poulhiès ***@***.***> wrote:﻿
I'll close this one, as I don't see a quick fix... Or is it really an issue for you @glaubitz ? I really don't know what people are expecting from an m68k toolchain
I’m curious how it works for the other architectures?

**Comment by dkm** [comment]
Comparing with rv32 12.1.0, both look very similar... Don't understand why clang++ complains about gcc-toolchain for m68k but not for rv32. https://c.godbolt.org/z/5M163PT5G I'll see if I can find some time later tonight.

**Comment by dkm** [comment]
Have compared rv32 and m68k but can't really see the difference. I've tried to dig the `strace` of clang to see what files are missing/checked... For `riscv32` I get a lot of `stat` call in the dir provided by `gcc-toolchain`:

```
stat("/opt/compiler-explorer/riscv32/gcc-10.2.0/riscv32-unknown-elf", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/opt/compiler-explorer/riscv32/gcc-10.2.0/riscv32-unknown-elf/lib32", 0x7ffed659cd90) = -1 ENOENT (No such file or directory)
stat("/opt/compiler-explorer/riscv32/gcc-10.2.0/riscv32-unknown-elf/lib", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/opt/compiler-explorer/riscv32/gcc-10.2.0/riscv32-unknown-elf/lib/gcc", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
...
```

But none with the m68k :

```
$  strace  /opt/compiler-explorer/clang-trunk/bin/clang++ -target m68k-unknown-elf  --gcc-toolchain=/opt/compiler-explorer/m68k/gcc-13.1.0/m68k-unknown-el
f /tmp/test.cc  -print-search-dirs |& grep gcc-13 
$
```

So I guess I'm out of quick ideas to try tonight and should probably read some more...

**Comment by dkm** [comment]
I'll close this one as it's been fixed on the gcc side. Not really sure what's missing on clang's side, but even with the latest `override` feature, this doesn't work. I guess there's something missing in the llvm config for m68k...
