### ISSUE TITLE
[BUG]: MSVC using broken STL?

### ISSUE THREAD

**Issue by alwaysmpe** [compiler-explorer/compiler-explorer#5039]
### Describe the bug

Using some parts of the STL on MSVC (definitely `x86 msvc v19.35`, other versions also affected) cause a compilation error. EG it's possible to include the `unordered_set` header, and declare an instance of, eg `unordered_set<int>`, however calling the merge function results in the error `<source>(7): error C2039: 'merge': is not a member of 'std::unordered_set<int,std::hash<int>,std::equal_to<int>,std::allocator<int>>'
`

Also when trying to use `std::reduce` (after including the `numeric` header) I get the error `<source>(8): error C2039: 'reduce': is not a member of 'std'`.

The same code compiles with clang/gcc fine. Unless I've missed something blindingly obvious, this seems like a bug.

### Steps to reproduce

Compiling the snippet:

    #include <iostream>
    #include <numeric>
    #include <unordered_set>

    int main() {
        std::cout << "hello world!" << std::endl;
        std::unordered_set<int> a;
        std::unordered_set<int> b;
        a.merge(b);
        std::reduce(a.begin(), a.end());
    }

Using `x86 msvc v19.35` (several other versions that I picked at random also seem broken).

Gives the error:

    example.cpp
    <source>(9): error C2039: 'merge': is not a member of 
    'std::unordered_set<int,std::hash<int>,std::equal_to<int>,std::allocator<int>>'
    <source>(7): note: see declaration of 'std::unordered_set<int,std::hash<int>,std::equal_to<int>,std::allocator<int>>'
    <source>(10): error C2039: 'reduce': is not a member of 'std'
    C:/data/msvc/14.29.30149/include\unordered_set(24): note: see declaration of 'std'
    <source>(10): error C3861: 'reduce': identifier not found
    Compiler returned: 2

### Expected behavior

Should compile successfully, as per gcc/clang/local msvc.

### Reproduction link

https://godbolt.org/z/xMvnvcbvr

### Screenshots

Not applicable

**Comment by partouf** [comment]
If you look at `/help`, you can see that the default c++ std version for MSVC 19.35 is c++14
So you'll need to pass `/std:c++17` to make it work
