### ISSUE TITLE
[REQUEST]: Add MSVC execution

### ISSUE THREAD

**Issue by jonnygrant** [compiler-explorer/compiler-explorer#5043]
### Is your feature request related to a problem? Please describe

Would be great if we could execute code compiled by MSVC

### Describe the solution you'd like

Maybe possible under a VM, or WINE?

### Describe alternatives you've considered

Microsoft do offer Visual Studio online

### Additional context

Not applicable

**Comment by jeremy-rifkin** [comment]
Hi @jonnygrant, we have had MSVC execution in the past but it has been disabled since earlier this year due to a security issue. Unfortunately the MSVC compilers are on infrastructure we don't run - Microsoft hosts them. We are working to re-enable execution but we don't have an ETA at the moment.

**Comment by omergoktas** [comment]
Still unfixed 😑
@TartanLlama any [hope](https://devblogs.microsoft.com/cppblog/execution-and-static-analysis-support-for-msvc-on-compiler-explorer/)?

**Comment by jeremy-rifkin** [comment]
We are now hosting msvc compilers and execution is restored 🎉
