### ISSUE TITLE
[REQUEST]: Add option to filter `llvm.dbg.value` and friends from `-emit-llvm` output

### ISSUE THREAD

**Issue by fodinabor** [compiler-explorer/compiler-explorer#5044]
### Is your feature request related to a problem? Please describe

When showcasing LLVM IR in compiler-explorer there's a conflict between wanting the source/IR correspondence to be visualized with colors but on the other hand not wanting the IR output to be polluted with `llvm.dbg.value` calls right now.

So either, we have colors, or we add `-g0` to remove the `llvm.dbg.value` calls, but then we lose the colors.

### Describe the solution you'd like

It'd be great if we could add a filter to remove those debug calls in the output and still enjoy the colors.

### Describe alternatives you've considered

Add `-g0`.. but as mentioned, that removes the colors..

### Additional context

https://godbolt.org/z/qKzbvorYn

**Comment by jeremy-rifkin** [comment]
See also #1314
