### ISSUE TITLE
[BUG]: Short link generation fails when behind a reverse proxy

### ISSUE THREAD

**Issue by coretechsec** [compiler-explorer/compiler-explorer#5048]
### Describe the bug

When running behind a reverse proxy the short link generation fails as an unhandled DOMException is raised. 

Caveat to the following: I'm not a web dev and this is just based on what I think is happening.

I believe this is because when `window.history.pushState` is called with the generated short link the host part of the URL does not match that of the current address and so the browser throws a DOMException. Due to the population of the short link window being done after the call to `window.history.pushState` this means that the short link appears to not have generated.

## Potential solutions 

For my local setup I have worked around this by changing the call to `pushState` to use a relative url rather than an absolute one by doing `new URL(extra).pathname` but I'm not sure if this is a viable solution more generally. 

The other option that I considered was not doing the `window.history.pushState` call at all after generating the shortlink, I think that this would be the preferable option for if using an external link shortening service such as TinyURL.

### Steps to reproduce

1. Run the compiler explorer locally, behind a reverse proxy that exposes a different port than the compiler explorer app. In my case I'm using Nginx and a dockerised build.
2. Visit the exposed address on nginx.
3. Click Share > Shortlink
4. The shortlink box will be empty and when looking in the browser console it shows an unhandled DOMException.

### Expected behavior

The shortlink should be populated the same as it would if not running behind a reverse proxy.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by partouf** [comment]
We run behind a proxy and other have too, it should usually be fine.

Here's some tips I think https://github.com/compiler-explorer/compiler-explorer/issues/634

It's important to set these in your nginx configuration:
```
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

To make CE match your public url instead of what the proxy calls it with.
