### ISSUE TITLE
[BUG]: Directive stripping is removing code

### ISSUE THREAD

**Issue by smeenai** [compiler-explorer/compiler-explorer#5050]
### Describe the bug

See https://godbolt.org/z/qnYTjzTo9 for an example. If I look at the assembly output right now, all I see is `ret`. Turning off the filtering for Directives gets me the whole assembly output. This seems to be a recent regression.

### Steps to reproduce

1. Visit https://godbolt.org/z/qnYTjzTo9
2. The output should only display `ret` instead of the full assembly for the function
3. Click Filter and deselect Directives, and the full assembly should be displayed.

### Expected behavior

See above

### Reproduction link

https://godbolt.org/z/qnYTjzTo9

### Screenshots

<img width="2053" alt="image" src="https://github.com/compiler-explorer/compiler-explorer/assets/1123966/253e3c4b-b34a-4cdb-a56d-0cee1e634eba">

### Browser version

Firefox 112.0.2

**Comment by jeremy-rifkin** [comment]
Thanks for the report, confirmed. It looks like turning off filtering library functions also works, and interestingly turning off filtering comments too.

**Comment by jeremy-rifkin** [comment]
Might be related to #5020

**Comment by partouf** [comment]
not really a regression on our part, we haven't changed asm parsing for quite a while. The clang directive strategy has just changed (for the worse for us, but im sure they have their reasons)

**Comment by smeenai** [comment]
Hmm, #5020 was for gcc, whereas this is for Clang. My example does display as expected with Clang 16 though, so there's definitely some Clang element here as well. I can't repro the multiple `.loc` directives locally, unfortunately, otherwise it's straightforward to bisect Clang to determine the responsible change. Maybe it's a combination of new Clang and the particular libstdc++ version used by Compiler Explorer?

**Comment by smeenai** [comment]
I bisected the Clang debug info change to https://reviews.llvm.org/D147506, and commented on that diff asking for recommendations.

**Comment by partouf** [comment]
> I bisected the Clang debug info change to https://reviews.llvm.org/D147506, and commented on that diff asking for recommendations.

Thanks for the link, interesting stuff. Can understand why they did it, definitely sensible change really. Considering a similar but also different issue pops up in gcc, it might be best for us to just adapt and go with it. Although I'm not sure how yet, it makes things very complicated.
