### ISSUE TITLE
[BUG]: Ghost compilers to be removed from the properties files

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#5052]
### Describe the bug

* gnatppc641120
* nvcxx_arm_cxx22_7
* nvcxx_arm_cxx22_9
* nvrtc102
* nvrtc101u2
* nvrtc101u1
* nvrtc101
* nvrtc100
* nvrtc92
* nvrtc91
* solc036
* /usr/bin/toit

### Steps to reproduce

https://github.com/compiler-explorer/infra/actions/runs/4968591553/jobs/8891278478

### Expected behavior

-

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by dkm** [comment]
Hmmm, GNAT for ppc64 11.2.0 should be working, not sure what's happening here. Not sure removing the config is the expected fix. I should have a look into why it's not there. At some point I saw this and fixed the build: https://github.com/compiler-explorer/gcc-cross-builder/pull/29/files
Maybe I forgot to resquash?

**Comment by OfekShilon** [comment]
@dkm thanks. Do you want me to revert gnatppc641120 so you can check at your leisure?
@partouf  we no longer have access to the original infra run. What indicates a 'ghost' compiler for you?

**Comment by partouf** [comment]
`mos-atari8-clang` can be replaced by `mos-atari8-common-clang`

they also added:
* `mos-atari8-cart-megacart-clang`
* `mos-atari8-cart-std-clang`
* `mos-atari8-cart-xegs-clang`
* `mos-atari8-dos-clang`

But will require maintenance, testing etc. It's hard to keep up with truth be told and hardly anyone uses it, so doesn't have any prio in adding.
