### ISSUE TITLE
[BUG]: Strings with leading '/app/' get truncated in output

### ISSUE THREAD

**Issue by sven-hoek** [compiler-explorer/compiler-explorer#5060]
### Describe the bug

When writing a string to stdout (that's where I have tested it) that has a leading `/app/`, that part of the string is omitted in the output.

For example:
`cout << "/app/aaa\n";` will output  only `aaa`, same thing happens when using `printf`.

It seems that `$HOME` is set to `/app` for the environment the app runs in, so possibly at some point all lines beginning with that string have it removed.

### Steps to reproduce

1. Visit godbolt.org
2. Run the following code with (almost) any common compiler (I tested with the latest gcc and clang), or just visit [this link](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:enum.hpp,fontScale:10,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:55,endLineNumber:8,positionColumn:55,positionLineNumber:8,selectionStartColumn:55,selectionStartLineNumber:8,startColumn:55,startLineNumber:8),source:'%23include+%3Ciostream%3E%0A%23include+%3Cstring%3E%0A%0Ausing+std::cout%3B%0Ausing+namespace+std::string_literals%3B%0A%0Aauto+expand_home_folder(std::string+path)+-%3E+std::string+%7B%0A++++static+const+std::string+homedir+%3D+getenv(%22HOME%22)%3B%0A++++if+(path.substr(0,+2)+%3D%3D+%22~/%22s)+%7B%0A++++++++cout+%3C%3C+%22Replacing+!'%22+%3C%3C+path.substr(0,+1)+%3C%3C+%22!'+of+!'%22+%3C%3C+path%0A+++++++++++++%3C%3C+%22!'+with+!'%22+%3C%3C+homedir+%3C%3C+%22!'%5Cn%22%3B%0A++++++++path.replace(0,+1,+homedir)%3B%0A++++%7D%0A++++cout+%3C%3C+%22%5Ct%22+%3C%3C+path+%3C%3C+!'%5Cn!'%3B%0A++++return+path%3B%0A%7D%0A%0Aint+main(int+argc,+char**+argv)+%7B%0A++++const+auto+expanded_path+%3D+expand_home_folder(%22~/some/folder%22)%3B%0A++++cout+%3C%3C+expanded_path+%3C%3C+!'%5Cn!'%3B%0A%7D%0A'),l:'5',n:'0',o:enum.hpp,t:'0')),k:48.241949521322894,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g131,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:10,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+13.1+(Editor+%231)',t:'0'),(h:executor,i:(argsPanelShown:'0',compilationPanelShown:'0',compiler:g122,compilerName:'',compilerOutShown:'0',execArgs:'',execStdin:no%0Ano%0Ano%0Ano%0Aasdf%0Ayes%0Aasdf%0Aasdf%0Aasdf%0Aasdf%0Aasd%0Afasd%0Ayes%0Afa%0Asdf%0Aasdf%0Aasd%0Af,fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'',overrides:!(),source:1,stdinPanelShown:'0',tree:'1',wrap:'1'),l:'5',n:'0',o:'Executor+x86-64+gcc+12.2+(C%2B%2B,+Editor+%231)',t:'0')),k:51.758050478677106,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4):
```cpp
#include <iostream>
#include <string>

using std::cout;
using namespace std::string_literals;

auto expand_home_folder(std::string path) -> std::string {
    static const std::string homedir = getenv("HOME");
    if (path.substr(0, 2) == "~/"s) {
        cout << "Replacing '" << path.substr(0, 1) << "' of '" << path
             << "' with '" << homedir << "'\n";
        path.replace(0, 1, homedir);
    }
    cout << "\t" << path << '\n';
    return path;
}

int main(int argc, char** argv) {
    const auto expanded_path = expand_home_folder("~/some/folder");
    cout << expanded_path << '\n';
}
```
3. View output pane

### Expected behavior

The last line of the output should be
```
/app/some/folder
```

but it is only shown as
```
some/folder
```

Note that the line above it (printing inside the function) works because of a prepended `\t` character. This was especially confusing as I first thought that some weird optimization might be happening when returning the string.

### Reproduction link

[godbolt.org](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:enum.hpp,fontScale:10,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:55,endLineNumber:8,positionColumn:55,positionLineNumber:8,selectionStartColumn:55,selectionStartLineNumber:8,startColumn:55,startLineNumber:8),source:'%23include+%3Ciostream%3E%0A%23include+%3Cstring%3E%0A%0Ausing+std::cout%3B%0Ausing+namespace+std::string_literals%3B%0A%0Aauto+expand_home_folder(std::string+path)+-%3E+std::string+%7B%0A++++static+const+std::string+homedir+%3D+getenv(%22HOME%22)%3B%0A++++if+(path.substr(0,+2)+%3D%3D+%22~/%22s)+%7B%0A++++++++cout+%3C%3C+%22Replacing+!'%22+%3C%3C+path.substr(0,+1)+%3C%3C+%22!'+of+!'%22+%3C%3C+path%0A+++++++++++++%3C%3C+%22!'+with+!'%22+%3C%3C+homedir+%3C%3C+%22!'%5Cn%22%3B%0A++++++++path.replace(0,+1,+homedir)%3B%0A++++%7D%0A++++cout+%3C%3C+%22%5Ct%22+%3C%3C+path+%3C%3C+!'%5Cn!'%3B%0A++++return+path%3B%0A%7D%0A%0Aint+main(int+argc,+char**+argv)+%7B%0A++++const+auto+expanded_path+%3D+expand_home_folder(%22~/some/folder%22)%3B%0A++++cout+%3C%3C+expanded_path+%3C%3C+!'%5Cn!'%3B%0A%7D%0A'),l:'5',n:'0',o:enum.hpp,t:'0')),k:48.241949521322894,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g131,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:10,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+13.1+(Editor+%231)',t:'0'),(h:executor,i:(argsPanelShown:'0',compilationPanelShown:'0',compiler:g122,compilerName:'',compilerOutShown:'0',execArgs:'',execStdin:no%0Ano%0Ano%0Ano%0Aasdf%0Ayes%0Aasdf%0Aasdf%0Aasdf%0Aasdf%0Aasd%0Afasd%0Ayes%0Afa%0Asdf%0Aasdf%0Aasd%0Af,fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'',overrides:!(),source:1,stdinPanelShown:'0',tree:'1',wrap:'1'),l:'5',n:'0',o:'Executor+x86-64+gcc+12.2+(C%2B%2B,+Editor+%231)',t:'0')),k:51.758050478677106,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

### Screenshots

![image](https://github.com/compiler-explorer/compiler-explorer/assets/15048669/3f8e80bb-a391-405e-a3b2-21d6e5af0e15)

**Comment by mattgodbolt** [comment]
Thanks for this: our rather naïve way of trying to make output/error messages show up the filename and not the implementation details of the site is obviously causing an issue here. Sorry for the confusion: we'll have a think about a better solution!

**Comment by sven-hoek** [comment]
Thanks for the feedback. Seems to be a rather minor issue in this otherwise excellent and very appreciated tool.

**Comment by partouf** [comment]
> Related to #4179, maybe some day a fix for one will be a fix for both

Right, we have generalized parsing because for compiler errors and ide mode asm for example we need to easily match user code. But it’s not needed to have for user execution stdout/stderr. Still requires some splitting up some code and calls, and not f up maintainability

**Comment by OfekShilon** [comment]
This is fixed now, probably by @partouf's https://github.com/compiler-explorer/compiler-explorer/commit/25b5eccabfef1588d5ac4721c3ca152b9b620627

**Comment by partouf** [comment]
Ah, right. Yes. Thank you
