### ISSUE TITLE
[REQUEST]: LLVM-IR suggested enhancements

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#5062]
### Is your feature request related to a problem? Please describe

The LLVM-IR contents somewhat lag behind the shiny and new llvm-opt-pipeline view.

### Describe the solution you'd like

(1) When LLVM-IR view is active, it would be helpful to build with `-fno-discard-value-names`. This (most of the time) preserves var names in the IR.

(2) It would be helpful to add the filter checkboxes from llvm-opt-pipeline pane, to optionally declutter the view. At least the removal of debug info is very useful.

Thanks for all your great work!

### Describe alternatives you've considered

Curl up into fetal posture and cry

### Additional context

Not applicable

**Comment by OfekShilon** [comment]
Sorry I see now that the -fno-discard-filter is a default-on option in the opt-pipeline:
<img width="304" alt="image" src="https://github.com/compiler-explorer/compiler-explorer/assets/73080/c6864aea-d30d-4911-b937-c00fee4c65a1">

It would be just great just to have the same options and filters (besides 'hide inconsequential passes') on the llvm-ir display.

**Comment by OfekShilon** [comment]
@jeremy-rifkin that would be awesome. Perhaps it would be feasible to add data-dependency-graphs too?

**Comment by jeremy-rifkin** [comment]
Data dependency graphs are a good idea, we could definitely do something like that. And for assembly too.

**Comment by jeremy-rifkin** [comment]
Will divert to #1158 for data-flow / data-dependency stuff
