### ISSUE TITLE
[BUG]: flang trunk has wrong version

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#5069]
### Describe the bug

```info: /opt/compiler-explorer/clang-llvmflang-trunk/bin/flang flang version @FLANG_VERSION@ is ready```
seen in log file

### Steps to reproduce

look at compiler discovery logfile

### Expected behavior

should show a version

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by partouf** [comment]
that's the actual version it seems
```
$ /opt/compiler-explorer/clang-llvmflang-trunk/bin/flang --version
flang version @FLANG_VERSION@
```

**Comment by mattgodbolt** [comment]
Well! Then...no bug here. nothing to see here, move along...
