### ISSUE TITLE
Tooltips on ARM assembly instructions show x86 description

### ISSUE THREAD

**Issue by 10110111** [compiler-explorer/compiler-explorer#507]
E.g. for `push` instruction, which has the same mnemonic in both x86 and ARM, the tooltip describes the operation of x86 variant, and also refers to the context menu item, which, in its turn, leads to a page about x86.
Instructions with ARM-unique mnemonics, like `bl`, don't have any tooltips, which is of course better than wrong ones for shared mnemonics.

**Comment by mattgodbolt** [comment]
Thanks for the report. Currently Compiler Explorer doesn't "know" what assembly code is being generated, and so has no way to tell which architecture to use. Compilers like clang allow you to use compiler settings to target different architectures. I guess some kind of heuristic guesser would be needed to work out what's going on in that case.

**Comment by 10110111** [comment]
What about `-dumpmachine` options for gcc and clang, and something similar for other compilers?

**Comment by mattgodbolt** [comment]
Great idea! Thanks!

**Comment by Trass3r** [comment]
I don't see any tooltips for arm code.

**Comment by RabsRincon** [comment]
Good catch @Trass3r. If the compiler does not support Intel asm syntax, we disable the tooltip to avoid most of the confussion generated by the missmatch. Unfortunately, this is not 100% accurrate, and having a better solution would be nice

**Comment by mattgodbolt** [comment]
CC @WillLovett who has been thinking about this a little.

**Comment by RubenRBS** [comment]
Hi! Thanks for your patience and sorry about a general lack of updates on this regard!
Starting with #2070, some great progress was made by @jovere with #2463 - We now show ARM documentation where possible, but there's always room for improvement in how we detect it. I'll close this issue in favour of the linked one
