### ISSUE TITLE
[BUG]: There is result truncation in the Output panel for Program returned: part.

### ISSUE THREAD

**Issue by mrDzamba** [compiler-explorer/compiler-explorer#5077]
### Describe the bug

There is result truncation in the  `Output` panel for `Program returned:` part. 
For `return l(51);`:   it is stated `Program returned: 255` - Correct
For `return l(52);`:  Instead of statement `Program returned: 260` it is stated `Program returned: 4` - Bug
For `return l(53);`:  Instead of statement `Program returned: 265` it is stated `Program returned: 9` - Bug

Assembly window shows correct results in all 3 mentioned examples.

I run same code on my PC `Ubuntu 22.04.2 LTS` with `gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0` and result is `265`, as expected.

### Steps to reproduce

Just run the following lambda function example with -O1 optimization flag:
```
int main(void)
{
    auto l = [](int a){return 5*a;};

    return l(53);
}
```

### Expected behavior

Assembly code:
```
main:
        mov     eax, 265
        ret
```
Output window should look like
```
ASM generation compiler returned: 0
Execution build compiler returned: 0
Program returned: 265
```

### Reproduction link

https://godbolt.org/z/Mh8e7WaPj

### Screenshots

Not applicable

### Operating System

Ubuntu 22.04.2

### Browser version

Firefox 113.0.2 (64-bit)

**Comment by jeremy-rifkin** [comment]
Hi @mrDzamba, this is intended behavior. A program's exit code on POSIX is 8 bits and 260 overflows that.

**Comment by mrDzamba** [comment]
@jeremy-rifkin sure, totally forgot that, sorry for misunderstanding. :) sorry for disturbance, will close this issue now.

**Comment by jeremy-rifkin** [comment]
No worries at all, take care
