### ISSUE TITLE
[BUG]: Sorting libraries based on semver doesn't actually work

### ISSUE THREAD

**Issue by brevzin** [compiler-explorer/compiler-explorer#5085]
### Describe the bug

#4153 claimed to sort libraries based on semver (fixing #4142), but it doesn't seem to be completely right.

For instance, `mp-units` is ordered oldest-to-newest with trunk last:
* 0.3.1
* 0.4.0
* ...
* 0.7.0
* trunk

`fmt` is ordered newest-to-oldest with trunk first:
* trunk
* 9.1.0
* 9.0.0
* ...
* 4.1.0
* 4.0.0

`GLM` is ordered newest-to-oldest, except with trunk last:
* 0.9.9.8
* 0.9.9.7
* ...
* 0.9.8.5
* trunk

Also that PR updated `options-handler.js` but not `options-handler.ts`, which also has this comment which seems relevant: https://github.com/compiler-explorer/compiler-explorer/blob/0364ef87ad28e5176b62d2b25f13fb42579baf6c/lib/options-handler.ts#L365-L369

So something isn't quite right here. 

### Steps to reproduce

Look at the version ordering for `mp-units` vs `fmt` vs `GLM` in C++.

### Expected behavior

The expected behavior is that `trunk` should go first (if present) and then all the semver versions in decreasing order. 

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by RubenRBS** [comment]
Thanks for the heads up and the detailed investigation, it helps a lot! will give it a look as soon as I can :)
