### ISSUE TITLE
[BUG]: [MLIR] Output in CE get's trimmed.

### ISSUE THREAD

**Issue by Sameeranjoshi** [compiler-explorer/compiler-explorer#5092]
### Describe the bug

same test case, same flags - using commandline - output correct
same test case, same flags - Using CE - output trimmed
What is trimmed ? 
Highlighted part in image - 
![Screenshot from 2023-05-30 14-39-10](https://github.com/compiler-explorer/compiler-explorer/assets/24942282/393709ae-0dd3-472a-8016-7289018cbf35)

Input file 
https://gist.github.com/Sameeranjoshi/f9bc5dac276ee158841d94fc661e12c1

Commandline - 
llvm-project/build/bin/mlir-opt test.mlir --test-transform-dialect-interpreter -allow-unregistered-dialect --split-input-file --verify-diagnostics

NOTE: To reproduce with CE the mlir should be trunk version as some of the upstream API breaking changes will not work for the MLIR16.0 version which is supported in CE.

### Steps to reproduce

1. Try command line - expected output
2. Try CE based output- current output
3. compare both

### Expected behavior

![Screenshot from 2023-05-30 14-39-10](https://github.com/compiler-explorer/compiler-explorer/assets/24942282/393709ae-0dd3-472a-8016-7289018cbf35)

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by Sameeranjoshi** [comment]
@mattgodbolt this has an update that now it can be reproducible after the commits for mlir-trunk.
I checked now and it still fails.
Can you please check if this could be fixed as the output is incomplete for such edge cases ?
I don't have/know the location of the built binaries on AWS, I would run them as mentioned both with command line and CE and see why would there be difference.

Thanks

**Comment by mattgodbolt** [comment]
I don't follow, sorry. Can you share a short link that demonstrates the problem? I'm finding it hard to know what's relevant here

**Comment by Sameeranjoshi** [comment]
https://godbolt.org/z/vbM4PdTGr
THis trims the output as highlighted in image.

**Comment by mattgodbolt** [comment]
Thanks for your patience. By hacking a POST I can see that we get the `#map` lines back if we turn _off_ the `commentOnly` filter that's being defaulted to true in this case. The mlir compiler will either need to remove that filter or somehow disasble this behaviour. In DMs with @Sameeranjoshi the suggestion was to do no filtering at all

**Comment by jeremy-rifkin** [comment]
Should be closed by #5902
