### ISSUE TITLE
[BUG]: can't link c++ when 'date' library is included

### ISSUE THREAD

**Issue by Spongman** [compiler-explorer/compiler-explorer#5099]
### Describe the bug

`cannot find -lcurl-d: No such file or directory`

### Steps to reproduce

- c++ source `int main() {}`
- output: "link to binary"
- add "date" library (either version)

recent gcc & clang both:
```
ld: cannot find -lcurl-d
```

### Expected behavior

no error

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment]
Short link: https://godbolt.org/z/6P6WGW5Pe

**Comment by partouf** [comment]
Date just requires curl, can't really change that, it has to be added by the user manually https://godbolt.org/z/M11qWrzja

see also https://github.com/compiler-explorer/compiler-explorer/issues/3791

**Comment by partouf** [comment]
(we could also consider disabling the requirement during build https://howardhinnant.github.io/date/tz.html#Installation but it's not trivial to rebuild all the date binaries)

**Comment by partouf** [comment]
Addressed it in the library description https://github.com/compiler-explorer/compiler-explorer/commit/e4a955f64800b7cc63bdcff43edbcd42811b1c79
