### ISSUE TITLE
[BUG]: Overrides for gcc Std version only list C versions on gcc 13

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#5101]
### Describe the bug

With the default GCC 13 selected, only C standards are listed

### Steps to reproduce

1. reset code layout
2. click overrides
3. open std version overrides
4. note it lists only C standards

### Expected behavior

Should have c++.  seems to be all GCC versions. Clang seems ok

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by partouf** [comment]
I am such an idiot...

`        } else if (exe.includes('gcc')) {`

`compiler.g131.exe=/opt/compiler-explorer/gcc-13.1.0/bin/g++`
