### ISSUE TITLE
Code returns 3628800 but output shows 0

### ISSUE THREAD

**Issue by AntLinea** [compiler-explorer/compiler-explorer#5118]
https://godbolt.org/z/7o9YY8q6q
simple demo code finds factorial of 10 and returns it from main.
Assembly shows code returning 3628800 but output shows 
 Program returned: 0

**Comment by partouf** [comment]
there's are internal (linux) limits to return codes, in this case you'll have to use some other output mechanisms like `std::cout` https://godbolt.org/z/MTed7oEq8
