### ISSUE TITLE
[QUESTION] Trouble getting "Execute the code" working for a new language

### ISSUE THREAD

**Issue by SixthDot** [compiler-explorer/compiler-explorer#5125]
I've locally added a new language. I can get output of ".s" files displayed, disasm of ".o" files too and finally the disasm of compiled binary. However the option "Execute the code" does not work, which is strange as the binary can be disasm.

Here is the content of the "Output of ..." window

```
ASM generation compiler returned: 0
nothing to compile !
Compiler did not produce an executable
Execution build compiler returned: 0
```

> nothing to compile !

is generated by the compiler when no files are passed, meaning that the compiler is invoked a second time while the executable is already produced.

How does "Execute the code" works exactly

**Comment by jeremy-rifkin** [comment]
You'll want to look at the code paths leading to https://github.com/compiler-explorer/compiler-explorer/blob/71ae48c8e7e2f3a59f052cefcb19b91523f30948/lib/base-compiler.ts#L1849-L1862

**Comment by jeremy-rifkin** [comment]
I’ll close for now. If there is more we can help with let us know 😄

**Comment by SixthDot** [comment]
Actually that still does not work but I have given up as essentially I'm just interested to have the asm, the LLVM IR, and finally highlightning basqed on DWARF info. 

Custom language support [is here](https://gitlab.com/styx-lang/styx-explorer/-/commit/c1e681e0600b65fd703be40f8dccb09576f92f94), in case there would be an obvious mistake explaining why that did not work.

**Comment by partouf** [comment]
> Actually that still does not work but I have given up as essentially I'm only interested to have the asm, the LLVM IR, and finally highlightning based on DWARF info.
> 
> Custom language support [is here](https://gitlab.com/styx-lang/styx-explorer/-/commit/c1e681e0600b65fd703be40f8dccb09576f92f94), in case there would be an obvious mistake explaining why that did not work.

your .filter function in https://gitlab.com/styx-lang/styx-explorer/-/commit/c1e681e0600b65fd703be40f8dccb09576f92f94#a29e1b11f817ba22c074789b9b3bc261ff55354a_0_50
filters out Everything

**Comment by SixthDot** [comment]
thanks @partouf, gonna look at that.
