### ISSUE TITLE
IR pane linking partially breaks after the first compile

### ISSUE THREAD

**Issue by jeremy-rifkin** [compiler-explorer/compiler-explorer#5126]
When first opening the IR pane lines are visually linked
![image](https://github.com/compiler-explorer/compiler-explorer/assets/51220084/1ec7625c-a999-44cb-b94b-045399c769fa)
As soon as a recompilation happens the links go away
![image](https://github.com/compiler-explorer/compiler-explorer/assets/51220084/69b0d72e-d36c-4162-9123-9758d28a6e4b)

Mousing over still works
![image](https://github.com/compiler-explorer/compiler-explorer/assets/51220084/2fc46311-ebbe-4e30-a93d-b0b6ccf9ef84)

#5078 is going to make the ir pane do a recompilation immediately so it won't look right the first time either

**Comment by OfekShilon** [comment]
Unable to reproduce. Could it be this is resolved?
