### ISSUE TITLE
[BUG]: ELF and binary displayed on output window when executing

### ISSUE THREAD

**Issue by jonnygrant** [compiler-explorer/compiler-explorer#5138]
### Describe the bug

https://godbolt.org/z/P79W5doqz

ELF and binary displayed on output window when executing

### Steps to reproduce

1. https://godbolt.org/z/P79W5doqz

### Expected behavior

Try to run

Note I have a screenshot if anyone needs.

### Reproduction link

https://godbolt.org/z/P79W5doqz

### Screenshots

Not applicable

**Comment by partouf** [comment]
what's wrong with this exactly? it makes perfect sense to me...

**Comment by dkm** [comment]
You're accessing the optional without checking it actually has something, and turns out it doesn't have a value, so you're displaying garbage from memory.

See this modified example that checks before taking the value and displaying it:
https://godbolt.org/z/P5nYjaYxW

As @partouf said, I don't see anything wrong here, except your code.

**Comment by jonnygrant** [comment]
Sorry I should have said, I expected a crash, or garbage, just seemed odd it was exactly the ELF address that gets displayed.
I added address sanitizer, but that didn't report anything.  I'm experimenting to find build options that will catch std::optional being dereferenced without checking.

**Comment by dkm** [comment]
You're in the undefined behavior territory, so anything can happen... And seeing some ELF somewhere in the memory is really not very surprising. I guess you could try to see which object you are hitting by inspecting the output of `ldd` and `readelf`

**Comment by jonnygrant** [comment]
Thank you. That clang-tidy tip is great.

We should use .value() as you say, great to have an exception like vector.at() to catch any mistakes that go unnoticed.  https://godbolt.org/z/5orhsMoc8
