### ISSUE TITLE
[REQUEST]: dont colorize log message when not started in a console

### ISSUE THREAD

**Issue by SixthDot** [compiler-explorer/compiler-explorer#5139]
### Is your feature request related to a problem? Please describe

I launch compiler-explorer from a GUI, that GUI then read the output, and it seems that the escapes added to colourize the log messages are still emitted.

example:

![log_colors](https://github.com/compiler-explorer/compiler-explorer/assets/102113538/6b02d837-eb7c-4aec-9a2e-3d746399d797)

Usually developmenet tools have a system allowing to deactivate colouring when not launched from a terminal.

### Describe the solution you'd like

There should be a system to deactivate coloring, either a manual one using extra args or an automatic one based on `isatty()`. 

Other option is to support [No_COLOR](https://no-color.org/)

### Describe alternatives you've considered

none, this is a minor problem

**Comment by jeremy-rifkin** [comment]
Good idea
