### ISSUE TITLE
[BUG]: Firefox clipboard workaround is bugged

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#5142]
### Describe the bug

A report from someone at mozilla:

> Hi there, we just received a report that the compiler explorer's context menu doesn't work on Firefox, and I took a quick peek to see what we can do to fix it.

> I see that the problem is that Firefox doesn't yet support the Async Clipboard web API, but we're working on it right now, and there's a small bug in your code that will prevent it from working even once Firefox supports it. It appears to be a small copy-paste from VSCode's Monaco editor, and altering one condition in an if-statement should fix it:

```
          void 0 !== navigator.clipboard &&
          !navigator.userAgent.includes('Firefox') ||
          document.queryCommandSupported('paste') ||
          this.editor.addAction({
            id: 'firefoxDoesntSupportPaste',
```

>Changing that third line with queryCommandSupport to the following should do the trick, and will hopefully future-proof the compiler editor for when Firefox supports Async Clipboard:

```
          'readText' in navigator.clipboard ||
```

(If you're curious, some more context is available at https://github.com/webcompat/web-bugs/issues/123378 at the related Bugzilla bug as well)

### Steps to reproduce

Visit godbolt.org in FF and look at the edit menu

### Expected behavior

it should work (once FF supports it) - current workaround will preclude it if starts working.

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Browser version

Firefox

**Comment by jeremy-rifkin** [comment]
I was a little confused because that code does not appear in our codebase but it must be what tsc/webpack translates our code to

https://github.com/compiler-explorer/compiler-explorer/blob/f8d95a33ec987aba3fb69759c2bade3ce90fbdf4/static/panes/editor.ts#L935-L948

**Comment by wisniewskit** [comment]
Yes, that looks like it should be the code. All I could see was the minified/transpiled version, as I didn't realize you had it on GitHub until a few minutes ago. Funny enough the variant on the [VSCode GitHub is also different](https://github.com/microsoft/vscode/blob/b8fe761e224d85fe5c80dc3dfb9976b38d3c36cc/src/vs/editor/contrib/clipboard/browser/clipboard.ts#L27-L30):
```
// Firefox only supports navigator.clipboard.readText() in browser extensions.
// See https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText#Browser_compatibility
// When loading over http, navigator.clipboard can be undefined. See https://github.com/microsoft/monaco-editor/issues/2313
const supportsPaste = (typeof navigator.clipboard === 'undefined' || browser.isFirefox) ? document.queryCommandSupported('paste') : true;
```
