### ISSUE TITLE
[BUG]: Linker error GCC 11.x+ googletest

### ISSUE THREAD

**Issue by bklarson** [compiler-explorer/compiler-explorer#5186]
### Describe the bug

I can link fine against Google Test when using GCC 10.4 or older.

Starting at 11.1, I get linker errors:

/opt/compiler-explorer/gcc-11.1.0/bin/../lib/gcc/x86_64-linux-gnu/11.1.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -lgtest_maind
/opt/compiler-explorer/gcc-11.1.0/bin/../lib/gcc/x86_64-linux-gnu/11.1.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -lgtestd
/opt/compiler-explorer/gcc-11.1.0/bin/../lib/gcc/x86_64-linux-gnu/11.1.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -lgmockd
collect2: error: ld returned 1 exit status

### Steps to reproduce

1. Visit https://godbolt.org/z/qzeavdr7n
2. Notice everything working
3. Update the compiler for the execution window (far right) to GCC 11.1 or newer

### Expected behavior

The program should link and run

### Reproduction link

https://godbolt.org/z/qzeavdr7n

### Screenshots

Not applicable

**Comment by partouf** [comment]
Google test 1.10.0 does not compile against the newer GCC's because they have "Treat warnings as errors" on. https://conan.compiler-explorer.com/getlogging/20230430013323

You can use the Google test trunk version
