### ISSUE TITLE
[BUG]: LLVM IR output (e.g. from `opt`) should be highlighted as IR

### ISSUE THREAD

**Issue by jryans** [compiler-explorer/compiler-explorer#5187]
### Describe the bug

At the moment, most compiler output is assumed to be assembly, and the syntax highlighting and filtering options assume an assembly file. 

For some compilers / toolchains such as LLVM's `opt` tool, the output is not assembly (LLVM IR in this case). For the case of `opt`, it would be great to at least have LLVM IR syntax highlighting in the output window. Ideally the filtering menus would also be changed (removing assembly specific ones), but that may be better handled as future work.

I do notice that the `monacoDisassembly` property is currently set at the language level, but different tools for the same input language can output different things. Perhaps a fix for this issue might change the output's Monaco language to set by the compiler logic instead of assumed to be fixed for a language.

### Steps to reproduce

1. Go to CE
2. Choose LLVM IR as language
3. Choose some version of opt
4. Look at the output

### Expected behavior

Syntax highlighting should be set to LLVM IR

### Reproduction link

https://godbolt.org/z/Y3ro5P7q5

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
Thanks @jryans for opening this issue. I was looking recently at making `-emit-llvm` also turn on llvm highlighting for the editor pane.
While I'm here, the IR and control flow graph panes should also be available for opt.

**Comment by partouf** [comment]
I believe this was fixed a little while ago
`lang: "llvm"` is now returned in the API, and that syntax model should be used now

**Comment by jeremy-rifkin** [comment]
thanks partouf, can confirm it's now resolved
