### ISSUE TITLE
[BUG]: ispc (trunk) is not updating

### ISSUE THREAD

**Issue by dbabokin** [compiler-explorer/compiler-explorer#5195]
### Describe the bug

ispc (trunk) is not updating. The version that is used is the following: Intel(r) Implicit SPMD Program Compiler (Intel(r) ISPC), 1.20.0dev (build commit e601785c8e353aa2 @ 20230419, LLVM 15.0.7)

Note the build date: 20230419.

### Steps to reproduce

1. Visit godbolt.org
2. Select "ispc" language
3. Select "ispc (trunk)" compiler
4. Check the compiler version in the status bar.

### Expected behavior

Daily updates of "ispc (trunk)"

### Reproduction link

https://godbolt.org/z/re1rna8v7

### Screenshots

Not applicable

**Comment by dbabokin** [comment]
Where the "ispc" image comes from in this workflow?

**Comment by partouf** [comment]
https://github.com/compiler-explorer/ispc-builder

**Comment by dbabokin** [comment]
I've submitted https://github.com/compiler-explorer/ispc-builder/pull/1 to fix the issue.

**Comment by partouf** [comment]
It's now up to date, thanks @dbabokin !
