### ISSUE TITLE
[COMPILER REQUEST]: MSVC version 17.6

### ISSUE THREAD

**Issue by codereport** [compiler-explorer/compiler-explorer#5213]
### Compiler name

x64 MSVC v19.36

### Compiler version

17.6 (or 19.36)

### Compiler language

C++

### Compiler homepage

https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes

### Motivation

Copying from  https://github.com/compiler-explorer/compiler-explorer/issues/4902: 

> In order to properly file bugs and explore platform differences, it's necessary to test against the latest version to see if things have been fixed, made worse, or otherwise changed.

Personally though, I am giving a talk tomorrow at C++ on Sea and most of the MSVC ranges views have been merged back in March 2023 but the latest aren't available on Godbolt. Here is the current status: https://github.com/codereport/ranges-examples/blob/master/cpp23_ranges_status.md

**Comment by SGSSGene** [comment]
If I am not mistaken v19.36 is availabe. But the newst compiler v19.39 and v19.40 havn't been added yet. Any chance to see v19.40 beeing added?

**Comment by jeremy-rifkin** [comment]
We have 19.38 so I will go ahead and close. We've been working on hosting msvc compilers ourselves and I imagine we can get 19.39 and 19.40 in the near future.
