### ISSUE TITLE
[REQUEST]: show timestamp when shortlink was created

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#5220]
### Is your feature request related to a problem? Please describe

Suggested during cpponsea

To show when a shortlink was created (after havent clicked one somewhere and CE showing the contents)

Should probably make an API call or include it in `/api/shortlinkinfo` as well

### Describe the solution you'd like

Not sure where to place it in the UI yet

### Describe alternatives you've considered

-

### Additional context

Not applicable

**Comment by RubenRBS** [comment]
> Not sure where to place it in the UI yet

Just my 2 cents :) but when you first commented this in dc, my first thought was something like 
![image](https://github.com/compiler-explorer/compiler-explorer/assets/5364255/777117a9-4e1d-49e8-a524-88be012b5fa0)

**Comment by partouf** [comment]
That does look nice

Would it work with small screens though..

**Comment by partouf** [comment]
What about a little i icon that on-click and/or mouse-over shows a tiny tooltip? Maybe possible to also collapse into the burger menu when on mobile

**Comment by jeremy-rifkin** [comment]
Collapsing on smaller screens is a good idea

**Comment by partouf** [comment]
now live
