### ISSUE TITLE
[BUG]: Inline asm operands in gcc is displayed in wrong order 

### ISSUE THREAD

**Issue by CGQAQ** [compiler-explorer/compiler-explorer#5231]
### Describe the bug

Inline asm operands in GCC is displayed in the wrong order.
![屏幕截图 2023-07-04 144653](https://github.com/compiler-explorer/compiler-explorer/assets/15936231/2416d00f-322f-47e8-b377-23d033399340)

### Steps to reproduce

1. Visit godbolt.org
2. Select x86-64 gcc trunk
3. Select C language
4. input 
```C
#include <stdio.h>

int main() {
    int a = 5, b = 7, c;

    asm("mov %1, %0\n\t"
        "add %2, %0\n\t"
        : "=r"(c)
        : "r"(a), "r"(b)
        :);

    printf("%d + %d = %d", a, b, c);

    return 0;
}
```
5. See the output panel

### Expected behavior

Just like the output of clang
![屏幕截图 2023-07-04 144619](https://github.com/compiler-explorer/compiler-explorer/assets/15936231/f76e8155-b22d-46cd-baad-5a2438a8d08f)

### Reproduction link

https://godbolt.org/z/Peve5bbTM

### Screenshots

Not applicable

**Comment by TangJinJian** [comment]
6

**Comment by partouf** [comment]
This is normal behaviour for gcc, it shows inline assembly in whatever manner the user wrote it. It will compile to the right thing if you use the Compile to binary object or Link to binary options.

We have an outstanding issue to maybe show a warning in our UI https://github.com/compiler-explorer/compiler-explorer/issues/1037
