### ISSUE TITLE
[BUG]: inline methods always filtered now?

### ISSUE THREAD

**Issue by jgarvin** [compiler-explorer/compiler-explorer#5235]
### Describe the bug

I'm pretty sure it didn't always work this way but I'm not sure. If you put this into godbolt.org you will get no assembly output:

```
inline int bar(int a)
{
    return a + 1;
}
```

But if you remove the `inline` keyword it works fine. This is annoying for member functions because if you define them inside the class/struct declaration then they are implicitly inline and don't show up.

### Steps to reproduce

1. Copy and paste snippet above into godbolt.org
2. Pick GCC 13.1. Doesn't appear to matter whether you use any flags, happens with and without -O2.

### Expected behavior

Assembly should appear

### Reproduction link

https://godbolt.org/z/11f55YdKv

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
I think this has always been the case in C++. If an inline function isn’t used in a TU the compiler doesn’t even have to generate code for it. (Unless I’m confusing myself, I’m away from my computer to double check)

One way to check if it is a filtering issue is to turn off all filters. Does that make it appear?

**Comment by jgarvin** [comment]
Ah I didn't realize the filtering was customizable, indeed it doesn't appear. I was assuming it had to since there needs to a be a non-inlined version compiled for things like taking the address or calls that can't be inlined, but duh that just ends up happening in the translation unit that does those things instead.
