### ISSUE TITLE
[BUG]: The new LLVM-IR options/filters are not preserved in generated full/short links

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#5247]
### Describe the bug

If you send someone a link to a CE page with "LLVM Opt Pipeline" pane, your choices of its options/filters checkboxes are preserved.
If you send someone a link to a CE page with "LLVM IR" pane, with the (very nice!) new addition of options/filters - your checkboxes are *NOT* preserved.

### Steps to reproduce

(1) You can use any CE with LLVM-IR, eg https://godbolt.org/z/6noEvb41E
(2) Change some options/filters selection, eg uncheck 'Hide Instruction Metadata' and 'Filter Attribute Groups':
![image](https://github.com/compiler-explorer/compiler-explorer/assets/73080/e39d4166-cf03-483c-af3e-2cdf5d4bacb6)
(3) 'Share' and copy a short link to the page:
![image](https://github.com/compiler-explorer/compiler-explorer/assets/73080/fb09a254-9d2a-4a5d-a9e1-54bce97b1e85)
(4) Paste in a new tab, and your selections would vanish:
![image](https://github.com/compiler-explorer/compiler-explorer/assets/73080/35d24c3a-7619-45e1-a653-81a649dbdd00)

### Expected behavior

Links should encode LLVM-IR filters/options selections, as they do for LLVM-Opt-Pipeline.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
Thank you for noticing, I’ll take a look

**Comment by OfekShilon** [comment]
@jeremy-rifkin I also think the `fno-discard-value-names` option checkbox has no effect, on either LLVM-IR or LLVM-Opt-Pipeline.  Could that be?

Disabling it could actually be useful - I'm trying to match an IR CFG with assembly CFG, and it would be easier if labels were the same: https://www.compiler-explorer.com/z/9aKzjfn3x

**Comment by jeremy-rifkin** [comment]
The `-fno-discard-value-names` option works, however not if `-fno-discard-value-names` is being manually passed to the compiler pane. I think it could be good to filter out `-fno-discard-value-names` if it's manually passed, I'll give some thought to whether that could interfere with anyone's workflow though.

**Comment by OfekShilon** [comment]
> The `-fno-discard-value-names` option works, however if `-fno-discard-value-names` is being manually passed to the compiler pane then it will indeed appear to have no effect. I think it could be good to filter out `-fno-discard-value-names` if it's manually passed, I'll give some thought to whether that could interfere with anyone's workflow though.

Oh sorry, my bad. I forgot I had an explicit -fno-discard there, no action needed.

**Comment by jeremy-rifkin** [comment]
All good!
