### ISSUE TITLE
[BUG]: LLVM IR viewer sometimes says "Internal error; unable to open output path"

### ISSUE THREAD

**Issue by jryans** [compiler-explorer/compiler-explorer#5255]
### Describe the bug

Sometimes when I have the LLVM IR viewer open, it will report "Internal error; unable to open output path". When this happens, I can usually workaround it by "tweaking" the input (adding a space somewhere) to force things to re-run and it usually works as expected.

This suggests there is a race condition (perhaps missing `await`...?) somewhere in the process.

### Steps to reproduce

1. Try to use the LLVM IR viewer
2. Edit the input code various times
3. Occasionally you encounter "Internal error; unable to open output path" in the IR viewer pane

### Expected behavior

The LLVM IR viewer should always show the IR (assuming compilation completed of course).

### Reproduction link

https://godbolt.org/z/cx4x9s37f

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
I've never seen this and am currently unable to reproduce. Does this still happen for you?

**Comment by jryans** [comment]
I used to see it quite often, as I was regularly using this workflow (viewing the LLVM IR) at the time I reported this. I haven't been using that workflow much recently, but I'll try it a bit over the next few days and update this issue after that.

**Comment by jryans** [comment]
I haven't seen it the last few days, so let's assume it's been fixed. 🙂 I'll reopen if it comes back.

**Comment by jryans** [comment]
Ah never mind, I've just seen it happen again:

https://godbolt.org/z/qW9dbz3vj

**Comment by jryans** [comment]
Here's my typical workflow, in case these details might matter to reproduce:
 
1. Switch C language input, some Clang compiler, and open the LLVM IR viewer
2. Close the tab, reopen the tab (as if it's a new day, but with step 1's context already in place)
3. Paste in some C file into the input (perhaps larger files are more likely to trigger it)
4. _Sometimes_ you will end up hitting this internal error, but so far I don't understand the trigger conditions

**Comment by partouf** [comment]
Happens extremely randomly, had to hit refresh tens of times to reproduce, and even when cached its not guaranteed to popup again. It must be some kind of write-read race condition.

**Comment by jeremy-rifkin** [comment]
Thanks so much, this is helpful

**Comment by OfekShilon** [comment]
The problem is in:
```ts
    getIrOutputFilename(inputFilename: string, filters?: ParseFiltersAndOutputOptions): string {
        return inputFilename.replace(path.extname(inputFilename), '.ll');
    }
```

`inputFilename` includes the result of `temp.mkdir` and once in a while includes `.c` *not just at the suffix*. Replacing *all* of the occurences of `.c` with `.ll` results in a non-existent file. 

I'll prepare some small fix soon.

**Comment by partouf** [comment]
fix is now live

**Comment by jryans** [comment]
Thanks all, glad to have this fixed! 

I never would have guessed it was rogue file extension replacement... Great work @OfekShilon! 😄
