### ISSUE TITLE
[REQUEST]: Run compiler-explorer as https service

### ISSUE THREAD

**Issue by fish2bird** [compiler-explorer/compiler-explorer#5257]
### Is your feature request related to a problem? Please describe

We need https in our company,  can compiler-explorer run in SSL mode without the help of nginx?

### Describe the solution you'd like

support deploy in https mode

### Describe alternatives you've considered

maybe we need config certificates and etc.

### Additional context

Not applicable

**Comment by mattgodbolt** [comment]
compiler explorer has no native support for https. We run it with a localhost-only mode and then use nginx. I'll happily accept a patch for https but it's not on our roadmap. Security is very hard: we leave that kind of thing to nginx or similar proxies that can handle it much better.

**Comment by fish2bird** [comment]
> compiler explorer has no native support for https. We run it with a localhost-only mode and then use nginx. I'll happily accept a patch for https but it's not on our roadmap. Security is very hard: we leave that kind of thing to nginx or similar proxies that can handle it much better.

Thanks.
