### ISSUE TITLE
[BUG]: CUDA/C++ sometimes fails to execute

### ISSUE THREAD

**Issue by robertmaxton42** [compiler-explorer/compiler-explorer#5260]
### Describe the bug

There is some setting or error preventing certain instances of Godbolt compiling CUDA/C++ from properly executing. Assuming a well-formed program, compilation succeeds but execution fails with

```
<Cannot read properties of null (reading 'extractAllToRoot')>
Execution build compiler returned: -1
```

Telling the compiler to "Link to binary" gives a more useful error:

```
Internal Compiler Explorer error: TypeError: Cannot read properties of null (reading 'extractAllToRoot')
    at file:///infra/.deploy/lib/base-compiler.js:711:37
    at Function.map (/infra/.deploy/node_modules/underscore/underscore-node-f.cjs:1342:22)
    at NvccCompiler.getSharedLibraryPaths (file:///infra/.deploy/lib/base-compiler.js:706:28)
    at NvccCompiler.getSharedLibraryPathsAsArguments (file:///infra/.deploy/lib/base-compiler.js:727:196)
    at NvccCompiler.prepareArguments (file:///infra/.deploy/lib/base-compiler.js:861:29)
    at NvccCompiler.doCompilation (file:///infra/.deploy/lib/base-compiler.js:1621:34)
    at file:///infra/.deploy/lib/base-compiler.js:2069:74
    at async file:///infra/.deploy/lib/base-compiler.js:2051:25
    at async file:///infra/.deploy/node_modules/p-timeout/index.js:90:13
Compiler returned: -1
```

It is possible, by using example programs from elsewhere (e.g. the tweet that announced that CUDA/C++ execution support was now supported), to work around this problem and create an instance that makes the same program execute correctly. As such, it is likely that there is an incorrect setting hidden somewhere in the interface. However, I'm still going to label this a "bug", as I've looked thoroughly enough that a setting with an application-breaking effect this major shouldn't also be this well hidden; assuming it exists and is decided needs to continue to exist, it needs to be easily found and/or better labeled.

### Steps to reproduce

The link under "Reproduction link" goes to a UI setup that doesn't work.
The link under "Expected behavior" goes to one that does, despite compiling the same program in the same language with the same compiler version and options. 

### Expected behavior

https://tinyurl.com/workingcuda

### Reproduction link

https://tinyurl.com/brokencuda

### Screenshots

Not applicable

### Operating System

Windows 11

### Browser version

Microsoft Edge

**Comment by bdice** [comment]
I can reproduce this issue. https://godbolt.org/z/ebf5ePe6h

**Comment by partouf** [comment]
sorry, already fixed this in https://github.com/compiler-explorer/compiler-explorer/pull/5325 but we have not updated our GPU instance yet

**Comment by bdice** [comment]
Thank you very much!
