### ISSUE TITLE
[BUG]: Incorrect constant in disassembly of C# code

### ISSUE THREAD

**Issue by svick** [compiler-explorer/compiler-explorer#5270]
### Describe the bug

The disassembly for C# code displays large constants incorrectly. This seems to be a consequence of the `JitDiffableDasm`/`JitDisasmDiffable` option. Is that option necessary? If it is, fixing this may require changes on the .Net side. (See also https://github.com/dotnet/runtime/issues/64981.)

### Steps to reproduce

1. Compile the following C# code:

    ```c#
    class Test
    {
        static long M1(long a) => a & 0x80000000;
        static long M2(long a) => a & 0x80000;
        static long M3(long a) => a * 0x84210;
    };
   ```

2. Observe that the produced disassembly is:

    ```asm
    // crossgen2 8.0.0-preview.7.23354.99+2fbb7eb1ba014de7200e39f048d1ea74a39f0b61

    Test:M1(long):long (FullOpts):
           mov      eax, 0xD1FFAB1E
           and      rax, rdi
           ret      

    Test:M2(long):long (FullOpts):
           mov      rax, rdi
           and      rax, 0xD1FFAB1E
           ret      

    Test:M3(long):long (FullOpts):
           imul     rax, rdi, 0xD1FFAB1E
           ret      

    Test:.ctor():this (FullOpts):
           ret      
    ```

### Expected behavior

The constants are displayed correctly, not as `0xD1FFAB1E` ("diffable").

### Reproduction link

https://godbolt.org/z/93a8hf1v3

cc: @EgorBo

**Comment by EgorBo** [comment]
cc @hez2010 I think we no longer need JitDisasmDiffable, JitDisasm doesn't print instructions' raw bytes anymore in Main

**Comment by hez2010** [comment]
Agree. If you would like to, feel free to open a PR that removes `JitDisasmDiffable` from crossgen2 arguments.

**Comment by hez2010** [comment]
@partouf This issue has been fixed and can be closed.
