### ISSUE TITLE
[BUG]: mrustc: function returning enum doesn't put anything into the return value struct

### ISSUE THREAD

**Issue by SperkLabs** [compiler-explorer/compiler-explorer#5279]
### Describe the bug

I reported this to mrustc, and the developer responded that their build of it generated correct code.

https://github.com/thepowersgang/mrustc/issues/313

I made a simple function that uses an enum as a return value to indicate if the result is valid or not. The generated C code returns a struct, but doesn't assign anything to the members of that struct.

https://godbolt.org/z/T1ssdafnz

### Steps to reproduce

code here:

https://godbolt.org/z/T1ssdafnz

### Expected behavior

the generated C code function should assign results to member(s) of the rv struct.

### Reproduction link

https://godbolt.org/z/T1ssdafnz

### Screenshots

Not applicable

**Comment by partouf** [comment]
Because the code is interleaved with valid asm label, our filtering automatically hides things

If you disable all the filters, I think it should be as expected?
https://godbolt.org/z/59vno3hh8

We might have to consider disabling all filters by default...

**Comment by SperkLabs** [comment]
You're right! Thanks for the fast response.
