### ISSUE TITLE
[BUG]:  `TypeError [ERR_UNKNOWN_FILE_EXTENSION]` on node latest

### ISSUE THREAD

**Issue by edhebi** [compiler-explorer/compiler-explorer#5285]
### Describe the bug

For some reason using node 20.4.0 there are errors around webpack, typescript and ts-node-esm.

This issue is mainly here to provide results for anyone with the same issue, the fix is to downgrade to node LTS or whatever compiler explorer currently expects (16.x at the time of writing this). After a discord interaction it was recommended I post it here, it's now done

### Steps to reproduce

1. Use node latest
2. run `make`

### Expected behavior

I should build. To be clear, node latest isn't really supported by compiler explorer and this is not really something that needs fixing until 20.x becomes compiler explorer's LTS.

### Reproduction link

Not applicable

### Screenshots

```
make 
make prebuild
make[1]: Entering directory '/.../compiler-explorer'
/usr/bin/npm run webpack

> compiler-explorer@0.0.3 webpack
> ts-node-esm ./node_modules/webpack-cli/bin/cli.js --node-env=production --config webpack.config.esm.ts

[webpack-cli] Failed to load '/.../compiler-explorer/webpack.config.esm.ts' config
[webpack-cli] TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /.../compiler-explorer/webpack.config.esm.ts
    at new NodeError (node:internal/errors:405:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:99:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:142:36)
    at defaultLoad (node:internal/modules/esm/load:91:20)
    at nextLoad (node:internal/modules/esm/hooks:733:28)
    at load (/.../compiler-explorer/node_modules/ts-node/dist/child/child-loader.js:19:122)
    at nextLoad (node:internal/modules/esm/hooks:733:28)
    at Hooks.load (node:internal/modules/esm/hooks:377:26)
    at handleMessage (node:internal/modules/esm/worker:168:24)
    at checkForMessages (node:internal/modules/esm/worker:117:28) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
make[1]: *** [Makefile:75: prebuild] Error 2
make[1]: Leaving directory '/.../compiler-explorer'
make: *** [Makefile:84: run] Error 2
```

**Comment by PlasmaHH** [comment]
After upgrading my opensuse TW system I came here to report this as a bug. It would be nice if this was fixed or at least a proper message being displayed.

As a workaround, things seem to work when doing `make NODE_OPTIONS="--loader ts-node/esm"` even though it spits out lots of warnings about loader being experimental.

**Comment by mattgodbolt** [comment]
We don't currently support this version of node: we will obviously have to upgrade at some point but right now it seems our uneasy alliance of ts node loaders and command line switches has failed.

If you need to get CE running, using an older node is required. But I agree we should probably make it an explicit error until this is fixed.

**Comment by PlasmaHH** [comment]
@OfekShilon can you elaborate exactly on what "not planned" as a close reason here means? That compiler explorer is not planned to support node.js 20.4 or anything newer for the time being?

**Comment by OfekShilon** [comment]
@PlasmaHH  sorry for not clearing it up. We currently run on node 20, expected to upgrade to 22 soon-ish. I'm unable to reproduce this error - do you still have it? If so I'll re-open
