### ISSUE TITLE
[BUG]: LLVM cross compilers fail with -stdlib=libc++

### ISSUE THREAD

**Issue by Mistuke** [compiler-explorer/compiler-explorer#5293]
### Describe the bug

When using armv8-a clang and using LLVM's own libc++ compilation fails, see https://godbolt.org/z/rYEG39j96

This seems to be another manifestation of a clang bug https://github.com/llvm/llvm-project/issues/57104 in that the LLVM build system doesn't correctly normalize targets.  from https://github.com/llvm/llvm-project/issues/57104#issuecomment-1336442726 it seems like setting LLVM_RUNTIME_TARGETS during build should maybe fix it So I think here? https://github.com/compiler-explorer/clang-builder/blob/main/build/build.sh#L167

### Steps to reproduce

on a C++ compiler, use `-O3 -stdlib=libc++` and use a standard header.

compilation should succeed.

### Expected behavior

expected compilation to work

### Reproduction link

https://godbolt.org/z/rYEG39j96

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
As a workaround at least for this case you can add this to the compile options line:
```
-I/opt/compiler-explorer/clang-18.1.0/include/x86_64-unknown-linux-gnu/c++/v1/
```
(You can change the clang-version to match the one you're using).

@partouf maybe we can add it ourselves for cross-compilation + libc++ combination? WDYT?

**Comment by partouf** [comment]
> As a workaround at least for this case you can add this to the compile options line:
> 
> ```
> -I/opt/compiler-explorer/clang-18.1.0/include/x86_64-unknown-linux-gnu/c++/v1/
> ```
> 
> (You can change the clang-version to match the one you're using).
> 
> @partouf maybe we can add it ourselves for cross-compilation + libc++ combination? WDYT?

Oh that's super weird that clang doesn't include that dir automatically, but yes I'm sure we can figure something out.

Also thank you, this is the first time that someone has suggested a fix (this 2023 issue was not the first)

**Comment by OfekShilon** [comment]
> Oh that's super weird that clang doesn't include that dir automatically, but yes I'm sure we can figure something out.
> 
> Also thank you, this is the first time that someone has suggested a fix (this 2023 issue was not the first)

I learnt of this today in the CE slack: https://cpplang.slack.com/archives/C7ETT0ZRP/p1710970039539679 .
I'll push this workaround in the near days and hope that (1) it's enough, (2) we'd remember to remove it in the future for llvm versions that include a proper fix  :(

**Comment by Quuxplusone** [comment]
Note that on Slack I was really trying to get _this_ to work: https://godbolt.org/z/c3v3xKozs i.e. using "x86-64 clang (trunk)" with a cross-compiling `--target=` option, rather than using "armv8-a clang (trunk)" directly. (Because this lets me compare trunk against "x86-64 clang (P1144 experimental)" without having to add a new P1144 compiler per target to the dropdown.) This seems harder to make work, although I don't understand quite what the difference is.

**Comment by partouf** [comment]
Ah but that would technically not be correct, you would need an include dir of the same target, not x86_64-unknown-linux-gnu
but we don't have any others, which is also 1 of many remaining issues with clang armv8
