### ISSUE TITLE
Rebuild and reinstall clang assertions 10.0.0

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#5295]
we have a problem with libc version for clang 10 https://godbolt.org/z/cEGK7qvhz -- clang 10 needs to be (maybe) rebuilt, reinstalled and re-squashed. I built it with the wrong OS initially (oops) but the docker is now fixed.

**Comment by Endilll** [comment]
This issue can be closed as completed .Clang 10 has been working fine for a while.

**Comment by mattgodbolt** [comment]
Thanks @Endilll !
