### ISSUE TITLE
[BUG]: Comments appearing in template parameters are not shown in green

### ISSUE THREAD

**Issue by hewillk** [compiler-explorer/compiler-explorer#5299]
### Describe the bug

<img width="333" alt="截圖 2023-07-29 下午7 49 52" src="https://github.com/compiler-explorer/compiler-explorer/assets/67143766/f6e5a7d3-ce90-4255-b12b-2dc2b40e9271">

The commented `const` in the template parameter is still rendered in keyword blue.

### Steps to reproduce

https://godbolt.org/z/hqEd49PxG

### Expected behavior

The commented `const` in the template parameter should be green as in the first example.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by partouf** [comment]
You could file this bug @ https://github.com/microsoft/monaco-editor

But I do not believe it can be fixed there. I think this requires the contextual information that `std::vector` is a template and not an identifier (so the difference between the comparison `a<b` and template `a<b>`), and we can't make that differentiation with just the regexy parser that monaco provides.

We've been thinking about ways to support an LSP to hookup to the editor to get contextual information, but it's not going to happen any time soon.

**Comment by OfekShilon** [comment]
Tracking a suggested upstream fix here too: https://github.com/microsoft/monaco-editor/pull/4256.

**Comment by RubenRBS** [comment]
Thanks a lot @OfekShilon !! All your work is greately appreciated :)

**Comment by OfekShilon** [comment]
Upstream fix merged today, didn't make it into monaco 0.45 :(
Hopefully I'll remember to close this when monaco 0.46 comes out.
