### ISSUE TITLE
rustc_cg_gcc broken

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#5342]
Build is failing since last week: https://github.com/compiler-explorer/compiler-workflows/actions/workflows/build-daily-rustc-cg-gcc_master.yml
@Antoyo, has anything changed that would make our build script fail like that?
```
7   │ 2023-08-04T00:37:51.0923384Z   Downloaded rustc-demangle v0.1.23
31778   │ 2023-08-04T00:37:51.0936383Z   Downloaded addr2line v0.19.0
31779   │ 2023-08-04T00:37:51.0953704Z   Downloaded miniz_oxide v0.6.2
31780   │ 2023-08-04T00:37:51.0973074Z   Downloaded cc v1.0.81
31781   │ 2023-08-04T00:37:51.0997022Z   Downloaded hashbrown v0.14.0
31782   │ 2023-08-04T00:37:51.1038376Z   Downloaded getopts v0.2.21
31783   │ 2023-08-04T00:37:51.1049193Z   Downloaded unicode-width v0.1.10
31784   │ 2023-08-04T00:37:51.1337514Z    Compiling libc v0.2.147
31785   │ 2023-08-04T00:37:51.1338213Z    Compiling core v0.0.0 (/root/build-rustc-cg-gcc/rustc_codegen_gcc/build_sysroot/sysroot_src/library/core)
31786   │ 2023-08-04T00:37:51.1338511Z    Compiling memchr v2.5.0
31787   │ 2023-08-04T00:37:51.1338849Z    Compiling std v0.0.0 (/root/build-rustc-cg-gcc/rustc_codegen_gcc/build_sysroot/sysroot_src/library/std)
31788   │ 2023-08-04T00:37:58.8126432Z    Compiling rustc-std-workspace-core v1.99.0 (/root/build-rustc-cg-gcc/rustc_codegen_gcc/build_sysroot/sysroot_src/library/rustc-std-w
        │ orkspace-core)
31789   │ 2023-08-04T00:37:58.8973274Z libgccjit.so: error: 'alias' attribute ignored because function is defined [-Wattributes]
31790   │ 2023-08-04T00:37:58.8974039Z libgccjit.so: error: 'alias' attribute ignored because function is defined [-Wattributes]
31791   │ 2023-08-04T00:37:58.8974713Z libgccjit.so: error: 'alias' attribute ignored because function is defined [-Wattributes]
31792   │ 2023-08-04T00:37:58.8975378Z libgccjit.so: error: 'alias' attribute ignored because function is defined [-Wattributes]
31793   │ 2023-08-04T00:37:58.8976048Z libgccjit.so: error: 'alias' attribute ignored because function is defined [-Wattributes]
31794   │ 2023-08-04T00:37:58.8976718Z libgccjit.so: error: 'alias' attribute ignored because function is defined [-Wattributes]
31795   │ 2023-08-04T00:37:58.8977364Z libgccjit.so: error: 'alias' attribute ignored because function is defined [-Wattributes]
31796   │ 2023-08-04T00:37:58.8978007Z libgccjit.so: error: 'alias' attribute ignored because function is defined [-Wattributes]
31797   │ 2023-08-04T00:37:58.8978563Z libgccjit.so: error: 'alias' attribute ignored because function is defined [-Wattributes]
31798   │ 2023-08-04T00:37:58.8979134Z libgccjit.so: error: 'alias' attribute ignored because function is defined [-Wattributes]
```

**Comment by dkm** [comment]
Thanks! So our build should be automatically fixed when you merge this :+1:

**Comment by antoyo** [comment]
Btw, so changes are being done to the build system of `rustc_codegen_gcc`: https://github.com/rust-lang/rustc_codegen_gcc/pull/319 is the first PR do to that.

This is probably going to affect you.

**Comment by dkm** [comment]
Thanks for the head's up, our builds are currently KO indeed, I'll have a look in the coming days.

**Comment by antoyo** [comment]
Also, the sysroot is not compiled in release mode (with `--release-sysroot`).
It would be nice to enable this flag by default.

**Comment by antoyo** [comment]
@dkm: All the build system is now rewritten in Rust, so there should not have many changes to it anytime soon.

**Comment by dkm** [comment]
Nice, thanks for the ping @antoyo . I've been doing some Docker things lately and this motivated me to fix this build. I'll give it a stab and let you know if I need any help!

**Comment by dkm** [comment]
Have resumed work on this one... Not sure how long I will take to fix it though.

**Comment by dkm** [comment]
@antoyo it looks like it's already working again. I'm a bit surprised as I haven't adjusted the way we invoke the compiler (still has `-Cpanic=abort` for example). I'll still test the invocation adjustment... but maybe it's fixed? I don't really know how to verify it's really using `cg_gcc` (would need to trigger some verbose asm for example, with version info etc).

**Comment by antoyo** [comment]
It doesn't seem to work for me (perhaps your example is cached?).

If I update the example, I get this error:
```
error: couldn't load codegen backend /app/librustc_codegen_gcc.so: cannot open shared object file: No such file or directory

Compiler returned: 1
```

Also, you would know it uses gc_gcc by looking at the `.comment` section.

**Comment by dkm** [comment]
Woooowoooo, less than a year after this issue was created, it's fixed :tada: 
Let me know if anything is not working as expected @antoyo . Compiler nightly has been OK for the last few days, and today's fix for the frontend makes it working again.
