### ISSUE TITLE
[BUG]: ARM links appear to ignore `-Wl,...` flags

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#5372]
### Describe the bug

Passing `-Wl,opt` should get to the linker

### Steps to reproduce

1. visit https://godbolt.org/z/bYxbvTcjM and note the `-Wl,not-valid` doesn't cause an error with the linker on ARM
2. switch to x86 and see it correctly errors out

### Expected behavior

Passing ARM linker options (e.g. `-Wl,--print-memory-usage` should work

### Reproduction link

https://godbolt.org/z/bYxbvTcjM

### Screenshots

Not applicable

**Comment by partouf** [comment]
The point of the "Compile to binary object" is that it doesn't actually Link, you can see the commands with -v https://godbolt.org/z/1xEexh9nr and the last command is just to assemble. The linking only happens when using the "Link to binary" option

**Comment by mattgodbolt** [comment]
Ah! I hadn't spotted that! Nice find: thanks @partouf
