### ISSUE TITLE
[BUG]: `abort()` calls get reported as seg faults in executed code

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#5376]
### Describe the bug

When an executed program calls `abort()` the actual error reported is SEGFAULT.

### Steps to reproduce

1. Call `abort()` in a program
2. Observe the output says
```
Program returned: 139
Program terminated with signal: SIGSEGV
```

### Expected behavior

Something like:
```
Program returned: 138
Program terminated with signal: SIGABRT
```

### Reproduction link

https://godbolt.org/z/6s9Y3YPqe

### Screenshots

Not applicable

**Comment by partouf** [comment]
duplicate of https://github.com/compiler-explorer/compiler-explorer/issues/5224

**Comment by mattgodbolt** [comment]
Oh shucks. Thanks partouf
