### ISSUE TITLE
[BUG]: COBOL (gcobol) shows linking errors

### ISSUE THREAD

**Issue by GitMensch** [compiler-explorer/compiler-explorer#5382]
### Describe the bug

execution is not possible for gcobol

### Steps to reproduce

1. Visit godbolt.org
2. Switch to COBOL which will open a sample program
3. Click on "add new->execution only"
4. the default opens with gnucobol, you see the execution
5. change the execution to gcobol
6. See

> Could not execute the program
Compiler returned: 1
Compiler stderr
>
>/opt/compiler-explorer/cobol/gcc-cobol-master-20230809/bin/../lib/gcc/x86_64-linux-gnu/13.1.1/../../../../x86_64-linux-gnu/bin/ld: cannot find -lgcobol: No such file or directory
collect2: error: ld returned 1 exit status

### Expected behavior

working linking (and execution)

### Reproduction link

https://godbolt.org/z/8775E8Wde

### Screenshots

Not applicable

**Comment by dkm** [comment]
Thanks, I'll have a look!

**Comment by dkm** [comment]
I should probably fix the build first, see #5499

**Comment by dkm** [comment]
Looks like the compiler is broken. I've tried to contact the author but the mail is not delivered correctly. I'll probably need to contact them using their gitlab. The gcc drivers adds the libgcobol in the link command, but it is not built anymore.

**Comment by GitMensch** [comment]
Thank you for the update. Other than the gitlab instance you should be able to contact them as noted in https://cobolworx.com/pages/cobforgcc.html (I possibly would just send an email to all of those three developers listed).

**Comment by dkm** [comment]
Good find, I've used these mails instead.

**Comment by dkm** [comment]
Problem found: we are using the `install-strip` target when installing... and currently, this target is broken in `libgcobol` and does nothing... so the lib is not installed and the compiler complains because it can't find it.
I've notified the gcobol devs (thanks for them being so helpful). I'll see if they fix this on their end or if I need to fix this on our end.

**Comment by dkm** [comment]
https://gitlab.cobolworx.com/COBOLworx/gcc-cobol/-/commit/89f96f795b954ecca57f87a6e5d6b65fc6769b64
local build is ok, starting a new build for the site now, hopefully this will go away after it is installed.

**Comment by dkm** [comment]
```
/opt/compiler-explorer/cobol/gcc-cobol-master-20230927/bin/../lib/gcc/x86_64-linux-gnu/13.1.1/../../../../x86_64-linux-gnu/bin/ld: cannot find -lstdc++: No such file or directory
```
:rofl:

**Comment by dkm** [comment]
And it's finally fixed
![image](https://github.com/compiler-explorer/compiler-explorer/assets/87603/9b58d6c9-138e-4152-beab-0833c7c74e03)

Thanks for the upstream dev for fixing and helping me :)
