### ISSUE TITLE
[BUG]: ICX >= 2023.0.0 cannot find device with SYCL code

### ISSUE THREAD

**Issue by Luigi-Crisci** [compiler-explorer/compiler-explorer#5408]
### Describe the bug

Any ICX >= 2023.0.0  cannot find any devices on which run a simple SYCL code.

### Steps to reproduce

See the reproduction link.

### Expected behavior

Execute the code on the host device

### Reproduction link

https://godbolt.org/z/qfesvWPq6

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment]
I'm afraid I don't know enough about SYCL or ICX or anything to know what might be going on here. https://www.intel.com/content/www/us/en/developer/articles/system-requirements/intel-oneapi-dpcpp-system-requirements.html doesn't have any obvious answers to me.

Do you have any experience with this kind of thing? What might we be missing?

**Comment by partouf** [comment]
I wonder if perhaps the CPU requirements are increased up to a point where our AWS instances aren't good enough? We don't run ICX on instances with GPU's, so it has to choose the CPU, but the CPU in this case is either AMD EPYC 7571 or Intel Xeon 8375C - but I just checked and even on the Intel Xeon it doesn't work.

Perhaps we have missed something from the installation or environment settings?

In the "Known issue" section it mentions this:
"If you installed Intel compilers as part of the oneAPI 2023.2 release of the Intel® oneAPI Base Toolkit, the Intel® oneAPI HPC Toolkit, the Intel® oneAPI IoT Toolkit, or from the oneAPI Standalone Component page, please install the appropriate patch for your environment."

**Comment by partouf** [comment]
I ran sycl-ls for 2023 and 2022 on one of the Intel Xeon instances.

2023 returned Nothing

2022 returned
```
[host:host:0] SYCL host platform, SYCL host device 1.2 [1.2]
```

**Comment by Luigi-Crisci** [comment]
How is ICX installed on the amaozn machines? I can try to reproduce on my Xeon machine.
Usually this error arises when Intel OpenCL runtimes are not properly configured.

**Comment by partouf** [comment]
> How is ICX installed on the amaozn machines? I can try to reproduce on my Xeon machine. Usually this error arises when Intel OpenCL runtimes are not properly configured.

It's installed through the offline install script with these paramers https://github.com/compiler-explorer/infra/blob/main/bin/yaml/cpp.yaml#L900

This happens on a different machine, and only the directories are used on the CE instances. (Env variables like LD_LIBRARY_PATH and OCL_ICD_FILENAMES are set inside of our CE backend, should be equivalent to what `setvars.sh` does)

**Comment by partouf** [comment]
I just ran sycl-ls with trace -1

```
$ SYCL_PI_TRACE=-1 sycl-ls
SYCL_PI_TRACE[basic]: Plugin found and successfully loaded: libpi_opencl.so [ PluginVersion: 12.21.1 ]
SYCL_PI_TRACE[-1]: dlopen(/opt/compiler-explorer/intel-cpp-2023.1.0.46347/compiler/2023.1.0/linux/lib/libpi_level_zero.so) failed with <libze_loader.so.1: cannot open shared object file: No such file or directory>
SYCL_PI_TRACE[all]: Check if plugin is present. Failed to load plugin: libpi_level_zero.so
SYCL_PI_TRACE[-1]: dlopen(/opt/compiler-explorer/intel-cpp-2023.1.0.46347/compiler/2023.1.0/linux/lib/libpi_cuda.so) failed with </opt/compiler-explorer/intel-cpp-2023.1.0.46347/compiler/2023.1.0/linux/lib/libpi_cuda.so: cannot open shared object file: No such file or directory>
SYCL_PI_TRACE[all]: Check if plugin is present. Failed to load plugin: libpi_cuda.so
SYCL_PI_TRACE[-1]: dlopen(/opt/compiler-explorer/intel-cpp-2023.1.0.46347/compiler/2023.1.0/linux/lib/libpi_hip.so) failed with </opt/compiler-explorer/intel-cpp-2023.1.0.46347/compiler/2023.1.0/linux/lib/libpi_hip.so: cannot open shared object file: No such file or directory>
SYCL_PI_TRACE[all]: Check if plugin is present. Failed to load plugin: libpi_hip.so
---> piPlatformsGet(
        <unknown> : 0
        <nullptr>
        <unknown> : 0x7fff080f7efc
) --->  pi_result : PI_SUCCESS

---> piTearDown(
        <unknown> : 0
) --->  pi_result : PI_SUCCESS
        [out]void * : 0
```

The fails on level0, cuda and hip are I think expected, we do not have them installed (we do have cuda but I have not set the library path).

`libpi_opencl.so` gives no errors, so I kind of was expecting an opencl:cpu entry to show up in sycl-ls 2022 as well, not just host:host

Like mentioned here in the example `[opencl:cpu:2]` is mentioned https://www.intel.com/content/www/us/en/docs/oneapi/programming-guide/2023-1/device-selection.html

**Comment by partouf** [comment]
Oh... there might be some extra installs needed for OpenCL https://support.zivid.com/en/latest/getting-started/software-installation/gpu/install-opencl-drivers-ubuntu.html

So I think in this case it fails because Host might be deprecated/removed in 2023? It mentions it is at least deprecated for the filtering; https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md#sycl_device_filter so perhaps the backend itself is not supported anymore either?

**Comment by Luigi-Crisci** [comment]
Fresh installed on an Xeon Gold 5218
```bash
sycl-ls
[opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2023.16.6.0.22_223734]
[opencl:cpu:1] Intel(R) OpenCL, Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz 3.0 [2023.16.6.0.22_223734]
[opencl:cpu:2] Intel(R) OpenCL, Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz 3.0 [2023.15.3.0.20_160000]
[opencl:acc:3] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2023.15.3.0.20_160000]
```
I also don't see the host device, while I can see both the OpenCL CPU and FPGA emulator. However on my machine I manually installed the OpenCL some time ago, so I'm not sure if it's for this reason that DPC++ manage to find the devices.
However I don't know if the DPC++ host device actually requires OpenCL, as even on a proper configured machine I can't see it

**Comment by partouf** [comment]
The host backend should not require OpenCL or any other 3rd party drivers, it's described in the sycl specs https://github.com/KhronosGroup/SYCL-Docs/blob/SYCL-2020/master/adoc/chapters/host_backend.adoc but I wouldn't be surprised if Intel decided to not support it out of the box anymore...

**Comment by partouf** [comment]
Do you have any insider info on this @rscohn2 ?

**Comment by rscohn2** [comment]
I will look into it. It probably is a missing environment variable.

**Comment by rscohn2** [comment]
This should be enough to execute. 
```
LD_LIBRARY_PATH=/opt/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/opt/intel/oneapi/compiler/latest/linux/lib:/opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin/ OCL_ICD_FILENAMES=/opt/intel/oneapi/compiler/latest/linux/lib/x64/libintelocl.so ./sycl-test
```
We already have this: https://github.com/compiler-explorer/compiler-explorer/blob/5c51cecd9cad7e7e95d01bb78c485323b48e80e9/lib/compilers/clang.ts#L328
and this: https://github.com/compiler-explorer/compiler-explorer/blob/5c51cecd9cad7e7e95d01bb78c485323b48e80e9/etc/config/c%2B%2B.amazon.properties#L1036

I will check tomorrow if no one looks at it before then.

**Comment by partouf** [comment]
I can confirm that adding TBB to libpath automatically adds more devices to sycl-ls

```
$ source /opt/compiler-explorer/intel-cpp-2023.1.0.46347/compiler/latest/env/vars.sh
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/compiler-explorer/intel-cpp-2023.1.0.46347/tbb/latest/lib/intel64/gcc4.8
$ sycl-ls
[opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2023.15.3.0.20_160000]
[opencl:cpu:1] Intel(R) OpenCL, Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz 3.0 [2023.15.3.0.20_160000]
```

**Comment by rscohn2** [comment]
> Reproduction link
> https://godbolt.org/z/qfesvWPq6

It works now.

**Comment by Luigi-Crisci** [comment]
Just checked it. Thank you for solving the issue so quickly!
