### ISSUE TITLE
[REQUEST]: [LLC] Dump module IR before/after each pass even if compilation crashes

### ISSUE THREAD

**Issue by TBodyAltra** [compiler-explorer/compiler-explorer#5411]
### Is your feature request related to a problem? Please describe

If the compilation of llc crashed, it would be nice to be able to view the dumped module IR before/after each pass (for passes that are success).

So the programmer would be able know what the input IR for the crashed pass.

### Describe the solution you'd like

Maybe the module IR could be dumped immediately after pass, regardless of the result of the compilation result.

### Describe alternatives you've considered

Compiler Explorer has an option to “Dump Full Module” in the “LLVM Opt Pipeline Viewer”. If the compilation was success, full modules before/after each opt pass would be dumped. 
 
However, if the compilation crashed, nothing is dumped out. I was wondering if the modules before/after each success opt pass could be dumped out even if the compilation failed eventually? So that the programmer could examine the modules and try to locate the pass which resulted in an error-prone IR.
 
I mean “modules” as the llvm IR.
 
On my local server, I would hack the llvm source code and dump the modules to files before/after each pass.

**Comment by jeremy-rifkin** [comment]
Hi @TBodyAltra, do you by chance have an example of llc crashing on the live site I could play with? This seems like something we can support.

**Comment by TBodyAltra** [comment]
> Hi @TBodyAltra, do you by chance have an example of llc crashing on the live site I could play with? This seems like something we can support.

Hi jeremy, here's a live crash site of llc (https://godbolt.org/z/3WKPd4Pdj). The input IR is a bit huge though..

**Comment by OfekShilon** [comment]
I was about to suggest the same thing.. I'll look into it this too.
