### ISSUE TITLE
[REQUEST]: Add Profile-Guided Optimization (PGO) support

### ISSUE THREAD

**Issue by zamazan4ik** [compiler-explorer/compiler-explorer#5414]
### Is your feature request related to a problem? Please describe

I am doing a [research / promoting](https://github.com/zamazan4ik/awesome-pgo) Profile-Guided Optimization (PGO) usage across different projects (mostly open-source). As you can see in the repository above, there are multiple benchmarks across different kinds of software where I compare "PGO vs non-PGO" performance.

But from time to time, people ask me about smaller examples where PGO shines. And I think showing these kinds of examples with Godbolt is a neat feature to have. Also, this idea was suggested in a local C++ chat.

### Describe the solution you'd like

There are at least two kinds of PGO: Instrumentation and Sampling (also known as [AutoFDO](https://github.com/google/autofdo)). I suggest starting with adding Instrumentation PGO support to Godbolt.

Instrumentation works in the following way:
- At first, we need to build a program in Instrumentation mode
- Then we run the program on a sample workload. After the run, a profile file with some runtime information will be created
- Then we compile the program once again with the runtime information

As you see, we need to somehow create the profile information and store it before the next compilation. I think it would be the biggest challenge here (or maybe not since I have no clue how Godbolt works under the hood).

From the UX point of view, it could be an additional checkbox or dropdown menu mode. Or maybe something better :)

Regarding compilers, all major C++ compilers (Clang, GCC, MSVC) support PGO. More information about language/compiler support can be found here](https://github.com/zamazan4ik/awesome-pgo#pgo-support-in-programming-languages-and-compilers).

### Describe alternatives you've considered

I see no viable alternatives here.

### Additional context

Here I want to leave some related materials that possibly could help:
- [Here](https://github.com/zamazan4ik/awesome-pgo) I collect various materials regarding PGO: benchmarks, various languages and compilers support, etc.
- Clang [docs](https://clang.llvm.org/docs/UsersManual.html#profile-guided-optimization) about PGO. GCC and MSVC support PGO too.

**Comment by zamazan4ik** [comment]
By the way, applying PGO to the used by the godbolt platform binaries could help with optimizing the performance of the platform. According to the tests, PGO helps a lot with optimizing performance for [compilers](https://github.com/zamazan4ik/awesome-pgo#compilers-and-interpreters) and different [tooling](https://github.com/zamazan4ik/awesome-pgo#developer-tooling). E.g. you can see the results for LLVM-based tooling [here](https://github.com/llvm/llvm-project/issues/63486).

**Comment by OfekShilon** [comment]
This would be quite challenging to support, and not sure about the added value.
We'd need to form a way to upload training workload data. Need to think about storage limitation and retention policy, and careful sandboxed execution. Also there's a 30-sec build job timeout that we'd want to keep, which would limit PGO to very, very small training runs - if any.
All in all, I tend to think compiler-explorer is just not the right tool for this.

**Comment by zamazan4ik** [comment]
Excuse me for the late reply - didn't see a notification before :(

> We'd need to form a way to upload training workload data. Need to think about storage limitation and retention policy, and careful sandboxed execution. Also there's a 30-sec build job timeout that we'd want to keep, which would limit PGO to very, very small training runs - if any.

Yes, you are right. Also, I want to add another way - allow to execute training workload (of course with proper sandboxing, etc.) directly at Compiler Explorer. However, this way also requires careful design.

> CE builds from sources only the 'nightly' versions, the rest are from binary distributions. These are still a lot of compilers, and a typical nightly build is ~3h+. Investing more time and computing resources into optimizing these builds makes sense only where they are used for more than a single day...

For Nightly versions - I agree. What about compilers from the binary distribution? There is a chance that compilers from binary distributions are not PGO optimized in the upstream (from where you download precompiled compilers). Since the released versions are not changed anymore, it will be valuable to recompile them with PGO: these versions are executed frequently. And if these binary distributions are not already PGO-optimized - you can get a 15-20% compilation speed boost for them by applying PGO. Is it worth spending time on it or not for the project - it's up to you.

**Comment by OfekShilon** [comment]
@zamazan4ik Regarding upstream compiler builds: maybe they build with PGO - or at least some do - I don't know. Anyway it's best to raise this at the compiler repos directly, CompilerExplorer has no say in this.
