### ISSUE TITLE
[BUG]: Qt library should not need include prefix

### ISSUE THREAD

**Issue by Maddimax** [compiler-explorer/compiler-explorer#5443]
### Describe the bug

When working with Qt, a User expects all headers to be available as e.g. `#include <QString>`.
When working in compiler explorer though only  `#include <QtCore/QString>` works. It would be great if both worked.

### Steps to reproduce

1. Visit godbolt.org
2. Select the Qt Library (e.g. version 6.5.2)
3. Change the source to `#include <QString>`

### Expected behavior

The code compiles without errors

### Reproduction link

https://godbolt.org/z/GT7cPGMxE

### Screenshots

Not applicable

**Comment by Maddimax** [comment]
I'd love to help investigating this myself, but I'm not sure how I could try to reproduce the issue locally / suggest a fix for it :(

**Comment by partouf** [comment]
there's no easy way to test it, but I'll accept a PR with the paths added to 
https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/c%2B%2B.amazon.properties#L3844

You can do `libs.qt.paths=/app/qt/include/QtCore:/app/qt/include/QtEtc`

I think that should work

**Comment by Maddimax** [comment]
Thanks! Done.
