### ISSUE TITLE
[LIB REQUEST] Add Qt support to the Include libs menu

### ISSUE THREAD

**Issue by tomisaacson** [compiler-explorer/compiler-explorer#546]
Add support for Qt on the Include libs menu. Qt binaries can be downloaded for various compilers under the open source license:
https://www1.qt.io/download-open-source/#section-2

**Comment by mattgodbolt** [comment]
There's some documentation here: https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/AddingALibrary.md -- we'd welcome help in getting more libraries installed. Usually the trouble here is getting a clean download URL to allow easy installation, but maybe you can find one!

**Comment by BugZappr** [comment]
Here's an article by a Qt guy who had to clone it, modify it, and wrote a blog article about it:

https://blog.qt.io/blog/2017/06/22/using-compiler-explorer-qt/

Not much to it, actually.

**Comment by mattgodbolt** [comment]
Happy to accept PRs to add this library. The documentation is linked above; it's not on my priority list right now but if someone wants to pick it up we can help!

**Comment by Trass3r** [comment]
> #probably-wont-happen

Did it simply not get picked up by anyone or is there a major blocker?

**Comment by partouf** [comment]
> > #probably-wont-happen
> 
> Did it simply not get picked up by anyone or is there a major blocker?

I invite you to prove me wrong and send us a PR

**Comment by Trass3r** [comment]
I guess that's a no on the blocker.
Never used it with anything but CMake myself.
Somehow you need to get the correct include paths.

**Comment by Maddimax** [comment]
I think this issue can be closed as "Done" ( see PR #4593 )

**Comment by BugZappr** [comment]
Thanks guys!  Qt really is fairly big in the C++ world, being the most popular, and one of several at most cross-platform C++ widget frameworks.  Of course, yours will be only one of several platforms it runs on; but I take it it will be running on either a *nix or Windows platform, which will make a fine reference implementation.
