### ISSUE TITLE
[BUG]: taocpp json library cannot compile

### ISSUE THREAD

**Issue by michael-brade** [compiler-explorer/compiler-explorer#5462]
### Describe the bug

When including taocpp-json (trunk), you also need to manually add taocpp-pegtl. However, even then a simple include of the json library doesn't work:

```
In file included from /opt/compiler-explorer/libs/taojson/trunk/include/tao/json/events/from_file.hpp:9,
                 from /opt/compiler-explorer/libs/taojson/trunk/include/tao/json/from_file.hpp:9,
                 from /opt/compiler-explorer/libs/taojson/trunk/include/tao/json.hpp:11,
                 from <source>:3:
/opt/compiler-explorer/libs/taojson/trunk/include/tao/json/internal/filesystem.hpp:7:10: fatal error: tao/pegtl/internal/filesystem.hpp: No such file or directory
    7 | #include <tao/pegtl/internal/filesystem.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Compiler returned: 1
```

### Steps to reproduce

On godbolt.org, select gcc 13.2, under Libraries, add "PEGTL trunk" and "taoJSON trunk", include `tao/json.hpp` -> crash

### Expected behavior

I would expect it to compile successfully.

### Reproduction link

https://godbolt.org/z/KM7qzbfMq

### Screenshots

Not applicable

**Comment by partouf** [comment]
I suggest you file this @ https://github.com/taocpp/json

They seem to have removed the internal file from the PEGTL repo, 
 https://github.com/taocpp/PEGTL/commit/788f223ee7c8377f78966c87d60b91188e3df33a
but they did not remove the reference to the internal header here https://github.com/taocpp/json/blob/main/include/tao/json/internal/filesystem.hpp#L7

**Comment by michael-brade** [comment]
I see, good point. Will do. However, the reason I had to choose trunk is because PEGTL 3.x is not available, only PEGTL 2.8, but json doesn't work with PEGTL 2.x.

Is it possible to add PEGTL 3.x to the list of supported libraries then?

**Comment by OfekShilon** [comment]
@michael-brade  I believe this is fixed upstream now. If you can verify, please close this.

**Comment by michael-brade** [comment]
Yes it's true.
