### ISSUE TITLE
Handle remaining llvm ir terminators for llvm ir CFGs

### ISSUE THREAD

**Issue by jeremy-rifkin** [compiler-explorer/compiler-explorer#5464]
The following IR breaks compilations when the CFG is open because `invoke` isn't handled currently

```llvm
define dso_local noundef i32 @f(int)(i32 noundef returned %n) local_unnamed_addr personality ptr @__gxx_personality_v0 {
entry:
  %exception = tail call ptr @__cxa_allocate_exception(i64 4) #2
  store i32 %n, ptr %exception, align 16
  invoke void @__cxa_throw(ptr nonnull %exception, ptr nonnull @typeinfo for int, ptr null) #3
          to label %unreachable unwind label %lpad

lpad:
  %0 = landingpad { ptr, i32 }
          catch ptr null
  %1 = extractvalue { ptr, i32 } %0, 0
  %2 = tail call ptr @__cxa_begin_catch(ptr %1) #2
  tail call void @__cxa_end_catch()
  ret i32 %n

unreachable:
  unreachable
}
```

https://godbolt.org/z/bvPaa6fj3

**Comment by OfekShilon** [comment]
Only after suggesting a fix did I notice this was assigned to @jeremy-rifkin. Not sure what are the ethics of this now, anyway - sorry.

**Comment by jeremy-rifkin** [comment]
No worries at all! I self-assigned because I wanted to take care of it but I've unfortunately been busy with other things so it's fair game for others. And thanks so much for taking the time to fix it 😄
