### ISSUE TITLE
[REQUEST]: colour LLVM IR lines to match source lines

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#5475]
### Is your feature request related to a problem? Please describe

It is *very* helpful to be able to visually match IR/assembly lines to source lines by colours. In assembly this already happens, in LLVM-IR not yet.

The info must be already there since hovering over a source line does highlight the corresponding IR range, it's just a matter of using it for colouring as done for assembly.

### Describe the solution you'd like

I wish the background coloring of lines in the LLVM-IR view would match the corresponding source line.

### Describe alternatives you've considered

-

**Comment by OfekShilon** [comment]
<img width="638" alt="image" src="https://github.com/compiler-explorer/compiler-explorer/assets/73080/29907034-53a8-44d6-a89f-2a3ba0778bfc">

**Comment by jeremy-rifkin** [comment]
Thanks for opening this. There are a handful of places where we're missing line matching - I think the system is in some need of some work overall.

**Comment by RubenRBS** [comment]
Yeah, some parts of the system would need to be re-thought for this to work as suggested, but it's a great one! Thanks :)

**Comment by OfekShilon** [comment]
Closing as a duplicate of #5126
