### ISSUE TITLE
Report of CE not working in WSL2

### ISSUE THREAD

**Issue by jeremy-rifkin** [compiler-explorer/compiler-explorer#5476]
@evakili reported that 2a3c1738d88f07d4f11c18fb0959733e3bb95d41 broke things locally for them:

> @jeremy-rifkin This change causes my local instance of CE on WSL2 to fail to run. The error is `cmd.exe: not found` on line 159 of this file.

https://github.com/compiler-explorer/compiler-explorer/blob/2a3c1738d88f07d4f11c18fb0959733e3bb95d41/app.ts#L159

As far as I can tell, cmd.exe and other windows programs are supposed to work from WSL.

> `cmd.exe` is not working in any of my WSL2 distros. In one of them, it says `cmd.exe not found` and in others, it says `bad executable format`.

**Comment by jeremy-rifkin** [comment]
We'll likely need more info or be able to reproduce ourselves. @evakili what distros are you using? What windows version are you on?

**Comment by evakili** [comment]
I have Debian, Ubuntu and CentOS distros:

```
➜ wsl --list -v
  NAME                   STATE           VERSION
* Debian                 Running         2
  docker-desktop-data    Running         2
  Ubuntu                 Stopped         2
  docker-desktop         Running         2
  CentOS9-stream         Stopped         2
```

**Comment by evakili** [comment]
I fixed the problem with the help of comments in microsoft/WSL#8843. But is this is right way to find if a Linux installation is a WSL one?

**Comment by partouf** [comment]
Ah, so you can't run cmd.exe in general.

"command not found" for debian is documented here https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#command-not-found-when-executing-windows-exe-in-linux

edit: The other error you've found already it seems. I'm not sure, WSL is alien to me.

**Comment by Fabian-programmer** [comment]
I have the same error.
In wsl2 you have to option to set within `/etc/wsl.conf`
`appendWindowsPath = false`

This will exclude all widnows path from the PATH variable, thus not finding cmd.exe anymore.
