### ISSUE TITLE
[BUG]: Filter Directives removes `.space` directives too aggressively

### ISSUE THREAD

**Issue by fghzxm** [compiler-explorer/compiler-explorer#5489]
### Describe the bug

Version tree: e43ed54afa
Link: [/z/7rGnfd7Gh](https://godbolt.org/z/7rGnfd7Gh)

![Wrong result](https://github.com/compiler-explorer/compiler-explorer/assets/32954258/f09162b6-fac1-4f35-97cd-42e58d279a50)

In the screenshot above I export 2 symbols `i` and `j` from a C++ file, `i` is the constant 0 and `j` is 1.  However, the assembly seems to show that both `i` and `j` reside in the same memory location containing 1.

Turning off Filter Directives reveals that the `.space` directive, which actually allocates the memory for `i`, was filtered:

![Unfiltered result](https://github.com/compiler-explorer/compiler-explorer/assets/32954258/6a70e5bb-5449-42b6-887f-3f3d3b46bd87)

### Steps to reproduce

See the link above. Alternatively:
1. Add the compiler "ARM gcc 11.2.1 (none)";
2. Change code to just `extern const int i = 0;`;
3. See that the output is just
   ```asm
   i:
   ```
4. Uncheck "Filter..." -> "Directives" and see that the `.space` directive was filtered:
   ```asm
   @ ...
   i:
           .space  4
   @ ...
   ```

### Expected behavior

The assembly output should be something like
```asm
i:
  .space 4
j:
  .word 1
```

### Reproduction link

https://godbolt.org/z/7rGnfd7Gh

### Screenshots

See above

**Comment by partouf** [comment]
no idea this directive existed

it probably could be enough to add to https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/parsers/asm-parser.ts#L101 to make it appear
