### ISSUE TITLE
[REQUEST]: please add support for boost libraries

### ISSUE THREAD

**Issue by agrasagar** [compiler-explorer/compiler-explorer#5493]
please add boost libraries for supporting
#include <boost/asio.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <boost/signals2/signal.hpp>
#include <boost/thread/thread.hpp>

**Comment by partouf** [comment]
Can you elaborate? You can use these header files fine https://godbolt.org/z/1jWWz9933

**Comment by agrasagar** [comment]
ok. thanks.
