### ISSUE TITLE
[REQUEST]: add support for llvm-dwarfdump

### ISSUE THREAD

**Issue by cjdb** [compiler-explorer/compiler-explorer#5501]
### Is your feature request related to a problem? Please describe

It'd be nice to diff the debug info generated by two implementations directly.

### Describe the solution you'd like

Add support for llvm-dwarfdump to the list of tools.

### Describe alternatives you've considered

It's possible to look at the debug info by revealing comments, but this also diffs the assembly.

### Additional context

Not applicable

**Comment by jeremy-rifkin** [comment]
This was on my mind recently. It looks like we are building llvm-dwarfdump so it should be easy to add support.

**Comment by DavidSpickett** [comment]
Diffing tool output is not supported yet unfortunately (https://github.com/compiler-explorer/compiler-explorer/issues/1211).

I also wanted to use llvm-dwarfdump recently, so I've got it working locally and will send a PR shortly to add it as a tool.

**Comment by DavidSpickett** [comment]
The tool is now live, here's an example comparing Arm64/x86 for a thread local variable: https://godbolt.org/z/W5W4e8Eob

**Comment by jeremy-rifkin** [comment]
Nice! I'll go ahead and close this

**Comment by cjdb** [comment]
Thank you! This is much appreciated.
