### ISSUE TITLE
[REQUEST]: CMake v3.27

### ISSUE THREAD

**Issue by vicentebolea** [compiler-explorer/compiler-explorer#5502]
### Language name

CMAKE

### Language version

CMAKE 3.27

### Language homepage

https://cmake.org/

### Compiler homepage

https://cmake.org/

### Compiler version

3.27

### Motivation

CMake language is heavily used in C/C++ projects by the cmake interpreter. Adding support in godbolt to cmake can be trully useful for the community.

To process a cmake language script in cmake use `cmake -P script_path`

**Comment by vicentebolea** [comment]
Note that I would be happy to assist/make this change if needed

**Comment by partouf** [comment]
just involves changes this number https://github.com/compiler-explorer/infra/blob/main/bin/yaml/tools.yaml#L12

**Comment by vicentebolea** [comment]
> just involves changes this number https://github.com/compiler-explorer/infra/blob/main/bin/yaml/tools.yaml#L12

Thanks for the prompt response, to make it clear, What I am requesting is being able to interpret cmake scripts in GodBolt. Thanks

**Comment by partouf** [comment]
> > just involves changes this number https://github.com/compiler-explorer/infra/blob/main/bin/yaml/tools.yaml#L12
> 
> Thanks for the prompt response, to make it clear, What I am requesting is being able to interpret cmake scripts in GodBolt. Thanks

right, sorry, missed that, that's a different story, I'm not really sure that's possible

**Comment by vicentebolea** [comment]
In principle it is simply calling `cmake -P ./scriptfilehere`, I am happy to assist with this

**Comment by vicentebolea** [comment]
> In principle it is simply calling `cmake -P ./scriptfilehere`, I am happy to assist with this

@partouf

**Comment by partouf** [comment]
> > In principle it is simply calling `cmake -P ./scriptfilehere`, I am happy to assist with this
> 
> @partouf

I understand, but CMake is already added as a special language and will probably mess some things up, so it will require some extra effort if it's possible to do.

**Comment by vicentebolea** [comment]
> > > In principle it is simply calling `cmake -P ./scriptfilehere`, I am happy to assist with this
> > 
> > 
> > @partouf
> 
> I understand, but CMake is already added as a special language and will probably mess some things up, so it will require some extra effort if it's possible to do.

Perhaps we can call this `CMakeScript`
