### ISSUE TITLE
ForCompile: A Fortran library to access the API

### ISSUE THREAD

**Issue by gha3mi** [compiler-explorer/compiler-explorer#5516]
Hello,

I have developed a Fortran library to access the API, which can be found here: https://github.com/gha3mi/forcompile

I would appreciate it if it could be made available on the API page: https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/API.md#implementations

Thanks,
Ali

**Comment by dkm** [comment]
Simply create a pull request that adds your library to the list and we'll review/apply :)

**Comment by partouf** [comment]
hi, this is now actually live
