### ISSUE TITLE
[COMPILER REQUEST]: gcc 7.5 missing from C config (is present in C++)

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#5523]
### Compiler name

gcc

### Compiler version

/

### Compiler language

/

### Compiler homepage

/

### Motivation

It's strangely missing and this has been confusing me this morning as something was supposed to be fixed in latest 7, and we only have 7.4 online :)

**Comment by mattgodbolt** [comment]
I kicked off the build: https://github.com/compiler-explorer/infra/actions/runs/6312358938 anyway :) (I see you self-assigned this: thanks Marc)

**Comment by dkm** [comment]
Oh, I was planning on doing it later today, after work. Thanks! You can leave the boring config to me :)

**Comment by dkm** [comment]
Oh, wait, looks like we have it, but not defined in C config. There's g++ 7.5.

**Comment by mattgodbolt** [comment]
lol thanks Marc -- I wonder what happened :D Not to worry at all I should have checked. But hey! freshly compiled gcc 7.5 :)
