### ISSUE TITLE
[COMPILER REQUEST]: Update arm-none-eabi-gcc

### ISSUE THREAD

**Issue by LunarLambda** [compiler-explorer/compiler-explorer#5545]
### Compiler name

arm-none-eabi GCC

### Compiler version

13.2.0

### Compiler language

C++, C

### Compiler homepage

https://gcc.gnu.org/gcc-13/

### Motivation

The GBA homebrew development community makes extensive use of compiler explorer for testing code and bisecting problems. Of particular interest is the arm-none-eabi target, which is lagging behind the arm-linux-[gnu]eabi[hf] targets by several versions.

It would be nice if it could be updated, as testing code against a slightly different ARM target leads to issues with compiler flags and optimisation passes being different.

**Comment by dkm** [comment]
It's true we usually only provide on GCC version for each tarrget arch. In particular, we don't provide systematically every target OS possible.

But we can change that of course. Out of interest, could you provide an example of such difference?

**Comment by LunarLambda** [comment]
the linux target compilers require `-mfloat-abi=soft` otherwise refuses to compile code for the CPU we target (arm7tdmi). While they can be used, the generated code is usually slightly different, probably due to some tuning options being different(?) (or due to version differences)

Don't have a concrete example right now, sadly. It's just something that comes up every now and then in our community. But the compiler is already there, it just needs updating.

**Comment by dkm** [comment]
Ok, thanks for the details. I'll have a look later then and let you know. Adding another compiler is the simplest approach but I would like to investigate other alternative first before that.

**Comment by partouf** [comment]
We have gotten these compilers from arm.com before, but their website has become even more of a maze since then. We'll need to do some digging.

**Comment by partouf** [comment]
It's probably one of these https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads
But they go up to 12.3

**Comment by LunarLambda** [comment]
Yeah, arm.com lags behind by a version usually. The download link is the right one.

**Comment by partouf** [comment]
The last our installs has been 11.2 it seems https://github.com/compiler-explorer/infra/blob/main/bin/yaml/cpp.yaml#L180

So we could at least install the v12 ones

**Comment by dkm** [comment]
> the linux target compilers require `-mfloat-abi=soft` otherwise refuses to compile code for the CPU we target (arm7tdmi). While they can be used, the generated code is usually slightly different, probably due to some tuning options being different(?) (or due to version differences)
> 
> Don't have a concrete example right now, sadly. It's just something that comes up every now and then in our community. But the compiler is already there, it just needs updating.

Is this the kind of error you get?
https://c.godbolt.org/z/bGT8TW5M3
```
<source>:2:1: sorry, unimplemented: Thumb-1 'hard-float' VFP ABI
```

**Comment by LunarLambda** [comment]
yeah. I know the flag fixed it but it causes some confusion for people "why do I need this flag here but not in my project, why does it give slightly different code"

**Comment by LunarLambda** [comment]
yes. I'm not really sure why. The main difference I've seen is in stack usage/register allocations, and sometimes loop structure. Again I think the linux-eabi compilers might have different defaults for tuning options. I couldn't entirely figure out the reason.

**Comment by dkm** [comment]
I can also add arm-none-eabi to the list of cross compiler we build, unless you need a specific version from ARM.

**Comment by LunarLambda** [comment]
If possible that would be ideal I think

**Comment by dkm** [comment]
Tried a local build and it builds directly. I'll add this. Is it ok if I simply build 13.2.0 now and only update for later releases? Or do you need an older version?

**Comment by LunarLambda** [comment]
nope that would be perfect for us. Maybe the 12.3 from arm.com could still be included since some people in our community use it as an alternative but it's not super pressing. thank you very much for this

**Comment by dkm** [comment]
the compiler should be install tonight, I'll merge the corresponding config tomorrow.
@partouf is adding the ARM compilers in https://github.com/compiler-explorer/compiler-explorer/pull/5551

I'll keep this new target in the list of cross-compiler we build on each new gcc release.

**Comment by LunarLambda** [comment]
sweet! thank you

**Comment by dkm** [comment]
Everything is ready, but I'll wait until cppcon is over to merge anything that touches the live site, so most probably early next week :)
