### ISSUE TITLE
[BUG]: F# results in .NET Restore error 

### ISSUE THREAD

**Issue by gimbles** [compiler-explorer/compiler-explorer#5553]
### Describe the bug

Trying to use F# (on the official instance) leads to a .NET restore error

### Steps to reproduce

1. Visit godbolt.org
2. Try to run F# code
3. Reflect on life

### Expected behavior

It should build normally

### Reproduction link

https://godbolt.org/z/99dn51d9n

**Comment by gimbles** [comment]
`/opt/compiler-explorer/dotnet-trunk-20230907/.dotnet/sdk/8.0.100-rc.1.23415.11/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1064: Package FSharp.Core, version 8.0.100-beta.23409.1 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions. [/app/CompilerExplorer.fsproj]`

This is the consistently hit error

**Comment by partouf** [comment]
duplicated of https://github.com/compiler-explorer/compiler-explorer/issues/4675
