### ISSUE TITLE
[BUG]: All mips (el) gcc compilers erorr out on -mips32r6

### ISSUE THREAD

**Issue by jackodirks** [compiler-explorer/compiler-explorer#5567]
### Describe the bug

Trying to compile any C code with any mips (el) gcc target results in the following error:

```
In file included from /opt/compiler-explorer/mipsel/gcc-13.2.0/mipsel-multilib-linux-gnu/mipsel-multilib-linux-gnu/sysroot/usr/include/features.h:515,
                 from /opt/compiler-explorer/mipsel/gcc-13.2.0/mipsel-multilib-linux-gnu/mipsel-multilib-linux-gnu/sysroot/usr/include/bits/libc-header-start.h:33,
                 from /opt/compiler-explorer/mipsel/gcc-13.2.0/mipsel-multilib-linux-gnu/mipsel-multilib-linux-gnu/sysroot/usr/include/stdint.h:26,
                 from /opt/compiler-explorer/mipsel/gcc-13.2.0/mipsel-multilib-linux-gnu/lib/gcc/mipsel-multilib-linux-gnu/13.2.0/include/stdint.h:9,
                 from <source>:1:
/opt/compiler-explorer/mipsel/gcc-13.2.0/mipsel-multilib-linux-gnu/mipsel-multilib-linux-gnu/sysroot/usr/include/gnu/stubs.h:14:11: fatal error: gnu/stubs-o32_soft_2008.h: No such file or directory
   14 | # include <gnu/stubs-o32_soft_2008.h>
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Compiler returned: 1
```

### Steps to reproduce

1. Go to godbolt.org
2. Select the language C.
3. Put a valid C program in the left pane, for example:
```
#include <stdio.h>

int main(void) {
    printf("Hello, world!\n");
    return 0;
}
```

4. Select a Mips (el) gcc, for example Mips (el) gcc 13.2.0
5. Set the compiler flags to -mips32r6
6. Observe the output screen

### Expected behavior

I expect the program to compile and show me assembly, just like it would when setting the compilation flag to -mips32r5

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
Unable to reproduce:  https://godbolt.org/z/Ehbbbzf4d
Perhaps the repro steps are missing something? Or is it solved?

**Comment by jackodirks** [comment]
It is indeed solved, somehow. Closing.
