### ISSUE TITLE
[Request]Download the output.

### ISSUE THREAD

**Issue by steve02081504** [compiler-explorer/compiler-explorer#5570]
### Is your feature request related to a problem? Please describe

I sometimes want to run some c++ programmes I've written on my office computer (godbolt's online runtime is very short, and sometimes I want to do some brute force calculations), but my office computer is running windows 7 which isn't enough to run the newer c++ compilers.
So I was wondering, if godbolt can allow you to run a programme online, why can't it provide a button to download the compiled executable?

### Describe the solution you'd like

Provide a button to download the compiled output.

### Describe alternatives you've considered

Idk.

### Additional context

Not applicable

**Comment by jeremy-rifkin** [comment]
I think this has been considered before in #203. There are some concerns about abuse of the service.

**Comment by mattgodbolt** [comment]
This is not on the roadmap currently. As @jeremy-rifkin says, it has a number of issues, one of wihch is that CE could become a "compiler farm" pretty easily. We also have some proprietary tools and compilers and would need to ensure we don't allow CE to become a way of subverting their licenses. In particular, if you're using Windows, then the proprietary Windows compilers do not allow for us to send you the binary results. You need to download and install and agree to the MS EULA to do so, sorry.
