### ISSUE TITLE
[BUG]: LLVM optimization pipeline of trunk broken

### ISSUE THREAD

**Issue by dzaima** [compiler-explorer/compiler-explorer#5587]
### Describe the bug

LLVM Opt Pipeline Viewer of a trunk clang/LLVM compiler displays incorrect pass contents for IR passes (machine IR passes display fine).

This is presumably due to https://github.com/llvm/llvm-project/pull/66412/files#diff-9bcb7cbad2f3a6a1516397a3d059d03c91dcfdbd9edda564baddf1bb2652d928L745-R850, which added a leading semicolon to IR dump separation lines.

### Steps to reproduce

1. select a trunk clang compiler, e.g. "x86-64 clang (trunk)"
2. add new → LLVM Opt Pipeline

### Expected behavior

IR passes have correct contents.

### Reproduction link

https://godbolt.org/z/Y7a4KzGo5

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
Thanks for the heads up!

**Comment by partouf** [comment]
Guessing this bit of code https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/parsers/llvm-pass-dump-parser.ts#L120 `^\*{3}`
To remain compatible with older versions I guess it will have to become `^;?\s?\*{3}` maybe?
