### ISSUE TITLE
[REQUEST]: Option to edit compiler parameters

### ISSUE THREAD

**Issue by nnatu** [compiler-explorer/compiler-explorer#5595]
### Is your feature request related to a problem? Please describe

Currently I see -o -S and -g as default parameters passed for each compiler. But all compilers are unable to handle these parameters and end up getting errors

### Describe the solution you'd like

Is it possible to customize the parameters used for a specific compiler? I can also handle it on the backend on my local instance if you can tell me which scripts to update

### Describe alternatives you've considered

As I said this problem might be specific to me so if you can help me understand which scripts to update that would be helpful

### Additional context

Not applicable

**Comment by jeremy-rifkin** [comment]
Hi @nnatu, do you have an example handy? If that's the case it's a bug in the lib/compilers/\<compiler>.ts for that compiler and it's something that should be fixed there.

**Comment by nnatu** [comment]
@jeremy-rifkin The error is not for compiler on public website. I am adding a new compiler on my local instance. How can I edit the parameters passed for that?

**Comment by jeremy-rifkin** [comment]
Thanks for confirming this doesn't affect the live site. Take a look at how optionsForFilter is implemented for any compiler in lib/compilers, e.g. https://github.com/compiler-explorer/compiler-explorer/blob/10796b3696cf1eef928de8c750b4d3350ee0c2db/lib/compilers/java.ts#L124C3-L129
