### ISSUE TITLE
[REQUEST]: Be able to write a script to preprocess source code

### ISSUE THREAD

**Issue by hadrielk** [compiler-explorer/compiler-explorer#5597]
### Is your feature request related to a problem? Please describe

I'd like to prototype an idea for some new C++ language syntax, and before having to implement the idea in a fork of a compiler, I just want to see what it looks like for users; and give people a link to godbolt to see and try the idea out.

So long as the syntax doesn't change C++ semantics, and could be syntactically transformed into valid C++ code, I could just write a script as a shim to do that transformation. You can think of it as a script-based preprocessor.

### Describe the solution you'd like

I'd only need the script to be given either the raw input content from the C++ source window-pane/file, or the ability to open+read the file - whichever is easier and safe for CE to offer.

The script would be responsible for parsing that C++ and doing whatever with it, and then either write out the transformed C++ into a new file, or via an API call - again, whatever's easier and safe for CE to support.

And after that the gcc/clang/whatever compiler is given the new file/output to use for the actual compilation stage.

Or CE could have that output as a separate file and window-pane, which the "normal" compiler stage is always driven from.

I.e., this whole idea can just be: can we have a way to take a C++ source page/file "X" and feed it to a script as the "compiler" or tool, and have its output be another C++ source page/file "Y"? Since that way the usual C++ compilers can just be used for file-Y as they already do today.

I don't care what language the script needs to be in - python, typescript/javascript, bash, whatever. Well... preferably _not_ bash, or perl, or... actually on second thought, let's just say it should only be either python or javascript. 😄 

### Describe alternatives you've considered

I don't know of any alternatives. The normal C/C++ Preprocessor is not sufficient to transform the type of syntax I'm thinking of. For my current idea, I need the preprocessing to parse string literals and generate code from within it.

The same thing would apply for some other proposed new-syntax use cases: pattern matching, reflection, etc. They're not merely library changes; they're language changes. But they can often be simulated by (potentially complicated) textual transformation into some valid existing C++.

### Additional context

Not applicable

**Comment by Endilll** [comment]
Looking and C++ lexer, preprocessor, and parser, I'd say this is unlikely to take off without libclang supporting such script.

**Comment by hadrielk** [comment]
> Looking and C++ lexer, preprocessor, and parser, I'd say this is unlikely to take off without libclang supporting such script.

At first I was going to try to explain that I don't need a lexer/preprocessor/etc. - what I was asking for was a stage in CE's pipeline be added for _before_ the compiler is invoked at all.

But now I realize you mean: so that the code can be correctly highlighted for errors, assembly lines, etc., _afterwards_.

And you're right. Which makes this totally not worth it. So I'll just close this request.

Thanks for taking the time to respond!

**Comment by partouf** [comment]
I do think there's something in this idea, but it does require a lot of bits and bobs to connect everything together. There's been a handful of people requesting being able to produce X with their code and then feed that into compiler Y. Or a tool where the output is re-fed into a compiler.

Currently most of the compilers that produce something like C or C++ feed that into a pre-defined compiler, but there has been an instance with for example Carbon where someone has figured out to write a CMake script to feed it into a compiler instead.

That does of course require the Carbon to C++ transpiler to already be in place and installed, so it's not exactly the same scenario.

So.. yeah.. it's complicated...

**Comment by hadrielk** [comment]
Maybe a GSoC project?

But there're probably a ton of more-useful things that could be done for CE, instead.
