### ISSUE TITLE
[BUG]: In LLVM-Opt-Pipeline, the diff view occasionally fails to highlight the diffs

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#5618]
### Describe the bug

When navigating between passes, either via clicks or arrow keys, occasionally passes that *do* modify the IR fail to show diffs in the before/after view.  I think I have a consistent repro, but if this doesn't work for you - just click up and down the list of consequential (green) passes and you're sure to hit this behavior.

### Steps to reproduce

1. I use the default source
```cpp
int square(int num) {
    return num * num;
}
```
and the compiler "armv8-a clang 16.0.0" with the single switch `-O3`
2. From the compiler pane "Add new... / LLVM Opt Pipeline"
3. Under "Filters" check "Hide Inconsequential Passes"
4. Click on the passes from the first onwards (either with mouse or down key). 

When you get to "Two-address instruction pass" (pass #8) you'd see empty diff.  Afterwards click one pass down and then back up to "Two-address instruction pass", and you'd see the diffs properly.

### Expected behavior

The diffs should always be highlighted.

### Reproduction link

https://godbolt.org/z/sW34or49G

### Screenshots

Coming from above, no diff:
<img width="757" alt="image" src="https://github.com/compiler-explorer/compiler-explorer/assets/73080/8deebb5d-e0de-4340-95e2-4fce09d506f8">

Coming from below, diff shown:
<img width="758" alt="image" src="https://github.com/compiler-explorer/compiler-explorer/assets/73080/da4d12e4-6251-4ef7-80cb-3d0a85ad9735">

**Comment by jeremy-rifkin** [comment]
Thanks for opening this, I'm suspecting a monaco bug

**Comment by OfekShilon** [comment]
> Thanks for opening this, I'm suspecting a monaco bug

They have a 'playground' for creating snippets suitable for reporting bugs: https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0#example-creating-the-editor-hello-world

Perhaps it is possible to trim this down to something reportable?

**Comment by nikic** [comment]
In Firefox, I'm no longer seeing diff highlighting at all. In Chrome, the highlighted diffs don't change when selecting a different pass (that is, the surrounding IR changes, and then in the middle there is a random diff from a completely different pass).

**Comment by alexshirley** [comment]
I also saw this with regular assembly diffs. A temporary solution is to simply copy the short-link to a new browser window.

**Comment by jryans** [comment]
This issue appears to go away if you revert back to Monaco 0.43, so that may be a good temporary fix until the next Monaco release.

**Comment by mattgodbolt** [comment]
Closing for now, can reopen if we accidentally reintroduce. But hopefully we can move to monaco 0.45 or whatever later and be safe.

**Comment by mattgodbolt** [comment]
Monaco 0.45 is out. @OfekShilon do you know how to see if the fix was in it?

**Comment by OfekShilon** [comment]
> Monaco 0.45 is out. @OfekShilon do you know how to see if the fix was in it?

It seems so!
