### ISSUE TITLE
[BUG]: Rust "Compiler did not produce an executable" when requesting both execution and LLVM IR / MIR

### ISSUE THREAD

**Issue by RalfJung** [compiler-explorer/compiler-explorer#5630]
### Describe the bug

When I ask godbolt to both execute the code and show MIR, then MIR works but the execution window shows "Compiler did not produce an executable".

### Steps to reproduce

1. Starting with the default Rust setup, change the code to
```rust
pub fn main() {
    println!("Hello world!");
}
```
2. In the compiler pane, click the cogwheel and then "Execute the code". A new pane appears where it says "Hello world!", as expected.
3. In the compiler pane, click the "+" and then "Rust MIR".

Now the "Output" pane shows "Compiler did not produce an executable".

### Expected behavior

A new pane with the MIR  should appear, and nothing else should change.

### Reproduction link

https://rust.godbolt.org/z/qab18q4eK

### Screenshots

Not applicable

**Comment by dkm** [comment]
That's probably because we end up passing the `-Zunpretty=mir` for the executable

**Comment by RalfJung** [comment]
There's no `-Zunpretty` in this example? Or do you mean it is added by godbolt to produce the MIR?

**Comment by OfekShilon** [comment]
Seems adding `--emit mir=...` causes rustc to stop emitting an executable :(
A fix is now merged, will be live at the next deployment.

**Comment by RalfJung** [comment]
Yeah, `--emit` takes an exhaustive list of what to emit.

**Comment by OfekShilon** [comment]
This is now live.
