### ISSUE TITLE
[REQUEST]: Support LLVM-MCA for armv8-a clang

### ISSUE THREAD

**Issue by sjoerdmeijer** [compiler-explorer/compiler-explorer#5649]
### Is your feature request related to a problem? Please describe

LLVM-MCA is supported for X86-64 clang compilers, but not for armv8-a clang:

"The current language or compiler does not support this tool"

### Describe the solution you'd like

LLVM-MCA is supported for armv8-a. Could support be added for armv8-a?

### Describe alternatives you've considered

n/a

### Additional context

Not applicable

**Comment by partouf** [comment]
Involves removing the mention of `arm` here https://github.com/compiler-explorer/compiler-explorer/blob/be5a9802470986942c572dd14f2a47ab14002699/etc/config/c%2B%2B.amazon.properties#L4512
(5 years ago it did not support arm and we intentionally disabled it for that reason)

**Comment by sjoerdmeijer** [comment]
Makes sense. Not sure about `arm` though, that might not be very well supported, but agree that we want to remove `aarch` from that list.

**Comment by sjoerdmeijer** [comment]
@partouf: are you happy if I create a merge request for this? The fix looks very simple. Testing would be more challenging for me, but install compiler explorer locally and giving it a try looks very doable.

**Comment by partouf** [comment]
> @partouf: are you happy if I create a merge request for this? The fix looks very simple. Testing would be more challenging for me, but installing compiler explorer locally and giving it a try looks very doable.

please do, no need for testing really, we can do that more quickly

**Comment by FabianSchuetze** [comment]
Is this now supported on compiler explorer? I might misunderstood the initial request, but when I look at the example here: https://godbolt.org/z/f6d9h1Gvz I do think I can use llvm-mca.

**Comment by partouf** [comment]
Doesn't look like it, not sure what's going on. Thanks for the ping, will investigate later

**Comment by FabianSchuetze** [comment]
Thanks a lot, @partouf , very much appreciated.

**Comment by FabianSchuetze** [comment]
Congratulations to being on c++cast and thanks for all the nice discussions, @partouf .  Do you have an idea what the issue with mca for arm is?

**Comment by partouf** [comment]
this should be fixed now and it is live, be aware that you do need to pass `--march` and `--mcpu` to llvm-mca before it understands what's going on

**Comment by FabianSchuetze** [comment]
Fantastic - many thanks!
