### ISSUE TITLE
[BUG]: Page not loading properly on Safari

### ISSUE THREAD

**Issue by aDifferentJT** [compiler-explorer/compiler-explorer#5650]
### Describe the bug

The page isn't loading

### Steps to reproduce

Visit godbolt.org in Safari

### Expected behavior

The page should fully load

### Reproduction link

Not applicable

### Screenshots

<img width="1680" alt="Screenshot 2023-10-25 at 11 12 53" src="https://github.com/compiler-explorer/compiler-explorer/assets/10051116/86cd4aed-0be5-4ae2-a379-9844aefabcde">

### Operating System

macOS 12.5

### Browser version

Safari 16.0

**Comment by mattgodbolt** [comment]
Thanks; this is unexpected but I bet comes from Monaco. My work machine is on Safari 17 and seems ok.

**Comment by mattgodbolt** [comment]
Can you do me a favour and see if https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0#example-creating-the-editor-hello-world works OK?

**Comment by QuentinUK** [comment]
SyntaxError: Invalid regular expression: invalid group specifier name
/*! For license information please see vendor.v35.691f80bb96fb141a4105.js.LICENSE.txt */

**Comment by mattgodbolt** [comment]
@QuentinUK that's great -- I will try and file a bug with them

**Comment by QuentinUK** [comment]
This is the version introduced the bug:-
https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0-dev-20230919#example-creating-the-editor-hello-world

**Comment by mattgodbolt** [comment]
Filed above; if there's any context you can add, please do!

**Comment by jeremy-rifkin** [comment]
It seems to work locally for me on safari 16.6. Some specific state might be needed?

**Comment by OfekShilon** [comment]
I was able to reproduce it online (with SauceLabs), for the reported monaco+safari versions:
![image](https://github.com/compiler-explorer/compiler-explorer/assets/73080/aa9be83d-c558-4870-ae41-24bf3839a09f)

And on the same testing platform+browser it seems fixed for the latest monaco.   So closing this for now, will re-open if someone can still reproduce it.
