### ISSUE TITLE
Missing demangler on...something

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#5655]
```
Error executing demangler  
{
  "code": 255,
  "execTime": "15",
  "okToCache": true,
  "stderr": " Usage: nsjail [options] -- path_to_command [args]\n Options:\n --help|-h \n \tHelp plz..\n --mode|-M VALUE\n \tExecution mode (default: 'o' [MODE_STANDALONE_ONCE]):\n\tl: Wait for connections on a TCP port (specified with --port) [MODE_LISTEN_TCP]\n\to: Launch a single process on the console using clone/execve [MODE_STANDALONE_ONCE]\n\te: Launch a single process on the console using execve [MODE_STANDALONE_EXECVE]\n\tr: Launch a single process on the console with clone/execve, keep doing it forever ....cut...",
  "stdout": "",
  "timedOut": false,
  "truncated": false
}
```

seen in the logs; not sure where it comes from. some more handy log output would be useful

**Comment by mattgodbolt** [comment]
Mayybe this: `POST /api/compiler/dxc_1_7_2207/compile`

**Comment by partouf** [comment]
I do not like how this is showing the nsjail help, we should block execution if the executable path is empty

**Comment by partouf** [comment]
DXC indeed (eventhough the demangler check is disabled?!)

`Execution {"args":["--config","etc/nsjail/compilers-and-tools.cfg","--env=HOME=/app","--",""],"command":"/opt/compiler-explorer/nsjail/nsjail"`

**Comment by partouf** [comment]
The code around `supportsDemangle`/`demangler` is a bit of a mess

**Comment by partouf** [comment]
this is now live
