### ISSUE TITLE
[COMPILER REQUEST]: Nim 2

### ISSUE THREAD

**Issue by inv2004** [compiler-explorer/compiler-explorer#5664]
### Compiler name

Nim

### Compiler version

2.0.0 [Linux: amd64]

### Compiler language

Nim

### Compiler homepage

https://nim-lang.org/install_unix.html

### Motivation

Nim is already supported on your platform, but Nim 2 is major update for the language

**Comment by adokitkat** [comment]
Upvote

**Comment by jeremy-rifkin** [comment]
We'll happily accept a PR 😄 

https://github.com/compiler-explorer/infra/pull/617 and https://github.com/compiler-explorer/compiler-explorer/pull/3043 can be used as templates, unless something has changed significantly with how the nim 2 compiler compiler works

**Comment by adokitkat** [comment]
> We'll happily accept a PR 😄
> 
> [compiler-explorer/infra#617](https://github.com/compiler-explorer/infra/pull/617) and #3043 can be used as templates, unless something has changed significantly with how the nim 2 compiler works

@jeremy-rifkin  Thanks, I'll do it.

**Comment by adokitkat** [comment]
https://github.com/compiler-explorer/compiler-explorer/pull/5702 here :)

**Comment by jeremy-rifkin** [comment]
PRs merged, thanks for the contribution!
