### ISSUE TITLE
[BUG]: Rust compiler with "--emit llvm-ir" produces incomplete output

### ISSUE THREAD

**Issue by RalfJung** [compiler-explorer/compiler-explorer#5667]
### Describe the bug

When using godbolt to generate LLVM IR for Rust programs, the output is sometimes incomplete.

### Steps to reproduce

1. Open [this](https://rust.godbolt.org/#g:!((g:!((g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:rust,selection:(endColumn:1,endLineNumber:8,positionColumn:1,positionLineNumber:8,selectionStartColumn:1,selectionStartLineNumber:8,startColumn:1,startLineNumber:8),source:'extern+%22C%22+%7B%0A++++static+mut+OUT:+u32%3B%0A%7D%0A%0Apub+fn+set(x:+u32)+%7B%0A++++unsafe+%7B+OUT+%3D+x%3B+%7D%0A%7D%0A'),l:'5',n:'0',o:'Rust+source+%231',t:'0')),k:56.06310860346977,l:'4',m:100,n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:nightly,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:rust,libs:!(),options:'--emit+llvm-ir',overrides:!((name:edition,value:'2021')),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+rustc+nightly+(Editor+%231)',t:'0')),header:(),k:43.93689139653023,l:'4',m:100,n:'0',o:'',s:0,t:'0')),l:'2',m:100,n:'0',o:'',t:'0')),k:100,l:'3',m:100,n:'0',o:'',t:'0')),l:'3',n:'0',o:'',t:'0')),version:4).
2. Observe that `@OUT` is undeclared in the output

### Expected behavior

The output should contain `@OUT = external global i32` somewhere -- and when running `rustc --emit llvm-ir --crate-type lib` locally, that line is there, so this seems to be a godbolt issue, not a rustc issue.

As another example, open [this](https://rust.godbolt.org/z/jnzdj5Kdd) and compare it with the LLVM IR generated [here](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a42cb01ce7bc22f12289fd7d4690ec51). In godbolt, a bunch of stuff is missing, for instance the large block at the end that says
```
!0 = !{i32 8, !"PIC Level", i32 2}
!1 = !{i32 2, !"RtLibUseGOT", i32 1}
!2 = !{i32 2, !"Dwarf Version", i32 4}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = !{!"rustc version 1.75.0-nightly (2f1bd0729 2023-10-27)"}
!5 = distinct !DICompileUnit(language: DW_LANG_Rust, file: !6, producer: "clang LLVM (rustc version 1.75.0-nightly (2f1bd0729 2023-10-27))", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !7, splitDebugInlining: false)
!6 = !DIFile(filename: "src/lib.rs/@/playground.ed3c2e4d39ff508d-cgu.0", directory: "/playground")
!7 = !{!8, !68, !77}
!8 = !DICompositeType(tag: DW_TAG_enumeration_type, name: "Feature", scope: !10, file: !9, baseType: !14, size: 8, align: 8, flags: DIFlagEnumClass, elements: !15)
!9 = !DIFile(filename: "<unknown>", directory: "")
!10 = !DINamespace(name: "x86", scope: !11)
```
This means copy-pasting the LLVM IR to serve as input for further exploration doesn't work.

Interestingly, in other cases (such as in the first example) godbolt does show the block of `!` declarations at the end.

### Reproduction link

https://rust.godbolt.org/z/bec1Ys7ov

### Screenshots

Not applicable

**Comment by dkm** [comment]
:wave: @RalfJung 

It's our filters that are not doing the correct job, see  https://rust.godbolt.org/z/5vxaxqhKK
You need to click "filter" and then disable all filters. They are probably not suited for LLVM-IR, we should fix that.

Thanks for the report!

**Comment by RalfJung** [comment]
Ah, good to know they can be configured. :)

**Comment by OfekShilon** [comment]
@RalfJung the preferred way to get LLVM-IR in compiler-explorer is not an explicit `--emit llvm-ir` switch, but rather the menu item 'Add new.../LLVM IR':
![image](https://github.com/compiler-explorer/compiler-explorer/assets/73080/a93af5e8-dc0c-4e73-ac3d-94f3d75b1e0c)

The output pane has text filters configured for assembly. In theory it could detect a `--emit llvm-ir` build switch and adjust but currently it doesn't.

This IR pane has a 'filters' dropdown too, and it is preferrable to play with the checkboxes there to get to your desired level of detail.

**Comment by RalfJung** [comment]
Ah I see, thanks for pointing that out!

The reason I ended up with that configuration is that I am looking to use godbolt as a way to quickly explore things with the Rust compiler, but assembly is the one thing I do *not* care about. I can't even read assembly. So generally I want to see any compiler errors that show up, and I want to see MIR or LLVM IR, and sometimes I want to see the output obtained when running the program. [This](https://rust.godbolt.org/z/M14Geza5s) is the configuration I arrived at to achieve that, and I was happy that I'm not wasting precious screen space with a useless (to me) assembly window. I was unhappy that I have to edit the command line twice (once for the executor and once for the window that dumps MIR / LLVM IR), but that still seemed okay.

Is there some other way to have MIR / LLVM IR be the main output, instead of assembly?

There are also a lot of other things that can be dumped with `-Zunpretty`, most of which are not offered by godbolt as a dedicated menu entry (nor would I expect godbolt to offer that, these are highly experimental and keep changing). What is the intended way to get e.g. the output of `-Zunpretty=thir-tree`? And is there a way to get the LLVM IR or MIR into the space where the assembly usually shows up?

**Comment by OfekShilon** [comment]
@RalfJung  an assembly pane doesn't have to take up screen real estate: 
![image](https://github.com/compiler-explorer/compiler-explorer/assets/73080/32c1253d-8475-4bff-b3da-04b6a150127f)

check https://rust.godbolt.org/z/qo9GMGbEj

If you drag a pane alongside an existing pane header they form a 'stack' - occupying the same screen area.

However I had to re-compile a few times to get both panes without error...  If you need to, use this button on the bottom left corner of the assembly pane:
![image](https://github.com/compiler-explorer/compiler-explorer/assets/73080/48a5327a-808d-452d-a85f-a9c1988b4a2f)

If this isn't a fluke, it's worth a separate bug report.

**Comment by RalfJung** [comment]
>  check https://rust.godbolt.org/z/qo9GMGbEj

Unfortunately now I can't just edit (or even see) the compiler flags any more, they are hidden together with the assembly. Being able to try different flags is a main reason to use godbolt over the native [Rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021).

> However I had to re-compile a few times to get both panes without error... If you need to, use this button on the bottom left corner of the assembly pane:

Yeah I'm also getting that behavior. The reload button is also not visible when the assembly pane is hidden.

**Comment by dkm** [comment]
> Ah I see, thanks for pointing that out!

Completely forgot about this, sorry, and thanks @OfekShilon !

> There are also a lot of other things that can be dumped with `-Zunpretty`, most of which are not offered by godbolt as a dedicated menu entry (nor would I expect godbolt to offer that, these are highly experimental and keep changing). What is the intended way to get e.g. the output of `-Zunpretty=thir-tree`?

There was some effort at some point (see HIR and MIR in https://github.com/compiler-explorer/compiler-explorer/issues/2567 for example). For the other not listed in the menu, you need to hijack the asm pane as you did.

> > check https://rust.godbolt.org/z/qo9GMGbEj
> 
> Unfortunately now I can't just edit (or even see) the compiler flags any more, they are hidden together with the assembly. Being able to try different flags is a main reason to use godbolt over the native [Rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021).

You can resize the asm pane to only display the first line with arguments:
![image](https://github.com/compiler-explorer/compiler-explorer/assets/87603/40ad6a88-55fb-4d0c-a351-8f53fb209f46)

https://rust.godbolt.org/z/P49aEaY3e

> > However I had to re-compile a few times to get both panes without error... If you need to, use this button on the bottom left corner of the assembly pane:
> 
> Yeah I'm also getting that behavior. The reload button is also not visible when the assembly pane is hidden.

This is a bug /o\

**Comment by OfekShilon** [comment]
> This is a bug /o\

@RalfJung: I see you already reported it separately at #5630. Suggest to close this and track 5630 - this really shouldn't happen.

**Comment by RalfJung** [comment]
I think that is a different bug, since the one we have here is unstable - reloading the page can fix or break things.

**Comment by RalfJung** [comment]
> You can resize the asm pane to only display the first line with arguments:

Yeah that's the best I got so far: https://rust.godbolt.org/z/3EnGde6c9

However, it's a bit awkward in that when my screen size changes (which happens multiple times a day as my laptop travels between different screens), the height of the assembly bar changes, and some of the buttons disappear or a bit of assembly text leaks through.

It's still probably better than my previous solution, given the assumptions godbolt filtering makes. Still I wish the main compiler window was not so hard-coded on providing assembly, and instead treated assembly as just one of many representations of the program that one can explore. But I guess that's a feature request.

For this bug... would it be worth a warning when `--emit`/`-Zunpretty` is recognized, saying that assembly filtering is still applied? FWIW I've been doing [similar things with clang](https://llvm.godbolt.org/z/3G5Poh1PM) and that probably has the same issues.

**Comment by dkm** [comment]
> However, it's a bit awkward in that when my screen size changes (which happens multiple times a day as my laptop travels between different screens), the height of the assembly bar changes, and some of the buttons disappear or a bit of assembly text leaks through.

true...

> It's still probably better than my previous solution, given the assumptions godbolt filtering makes. Still I wish the main compiler window was not so hard-coded on providing assembly, and instead treated assembly as just one of many representations of the program that one can explore. But I guess that's a feature request.

Yes. But you're right saying the ASM is "special", but maybe that's something we could relax a bit... Not sure.

> For this bug... would it be worth a warning when `--emit`/`-Zunpretty` is recognized, saying that assembly filtering is still applied? FWIW I've been doing [similar things with clang](https://llvm.godbolt.org/z/3G5Poh1PM) and that probably has the same issues.

Yes, it has. But anything that changes the output has the "problem": `-E` with `gcc/clang` and probably others. But we could do something about that. Maybe a small popup as we are doing for other features (like using `-march=native`).

**Comment by OfekShilon** [comment]
The original issue here seems solved, closing this in favor of a more focused discussion in #5987
