### ISSUE TITLE
[BUG]: The block in the CFG where the ret statement is located has a back edge

### ISSUE THREAD

**Issue by ZY546** [compiler-explorer/compiler-explorer#5672]
### Describe the bug

Perhaps the block in the CFG where the ret statement is located should not have a back edge.
But this is not the case in the link below.
https://godbolt.org/z/5f6YKra4h

### Steps to reproduce

Not applicable

### Expected behavior

Not applicable

### Reproduction link

https://godbolt.org/z/5f6YKra4h

### Screenshots

<img width="476" alt="image" src="https://github.com/compiler-explorer/compiler-explorer/assets/77828578/24e31952-0cac-4578-9c54-988c4d27097e">

**Comment by OfekShilon** [comment]
Fix submitted at #5691
