### ISSUE TITLE
[BUG]:  a form of an ARM return statement mis-handled by CFG

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#5684]
### Describe the bug

ARM has some exotic ways to return from functions. 

One is `bx lr` which is [indeed sort of a branch](https://stackoverflow.com/questions/27084857/what-does-bx-lr-do-in-arm-assembly-language) but seems to be [handled correctly by CE](https://godbolt.org/z/b6zsdTMM5). 

Another is [`pop {***, pc}`](https://stackoverflow.com/questions/24777842/poppc-in-assembly) which (surprisingly) is [visualized in the CFG as a jmp](https://godbolt.org/z/6x5daz9Y7).

### Steps to reproduce

https://godbolt.org/z/6x5daz9Y7

### Expected behavior

No edge should come out of a block terminating with `pop {<something containing pc>}`

### Reproduction link

https://godbolt.org/z/6x5daz9Y7

### Screenshots

![image](https://github.com/compiler-explorer/compiler-explorer/assets/73080/b4551a97-d1a2-48d2-9003-6c7a5ddb5fa1)

**Comment by jeremy-rifkin** [comment]
I feel like this is a case I tried to handle, but maybe incorrectly or decided to wait until later

**Comment by jeremy-rifkin** [comment]
Yeah
https://github.com/compiler-explorer/compiler-explorer/blob/2f0b8028c7636d5dcf421644f831f4e9fb3f8fea/lib/cfg/instruction-sets/arm.ts#L81

**Comment by OfekShilon** [comment]
I closed this because it's probably the same as #5672, maybe not related to the actual block terminal. Won't know without checking.
