### ISSUE TITLE
[BUG]: no llvm libraries, no llvm-config

### ISSUE THREAD

**Issue by mgood7123** [compiler-explorer/compiler-explorer#5728]
### Describe the bug

llvm includes are found but llvm-config and llvm libs are not found

https://godbolt.org/z/vPqj496x9

### Steps to reproduce

attempt to link library LLVM

### Expected behavior

should link

### Reproduction link

https://godbolt.org/z/vPqj496x9

### Screenshots

Not applicable

**Comment by florianhumblot** [comment]
Seems related to #4814  which has been open for a while

**Comment by partouf** [comment]
We have never built binaries for LLVM, this is a longstanding issue that we have no solution for yet.

**Comment by partouf** [comment]
llvm library binaries are now available for llvm 19.1.0 and trunk
