### ISSUE TITLE
MSVC ARM #error on #include <type_traits>

### ISSUE THREAD

**Issue by adr26** [compiler-explorer/compiler-explorer#573]
If you #include <type_traits>, the MSVC ARM compiler hits an #error in ucorecrt.h and then ICEs:

https://godbolt.org/g/LNN5tB

Does more need to be done to set up the MSVC ARM compiler correctly (c.f. http://pete.akeo.ie/2017/05/compiling-desktop-arm-applications-with.html)?

Thanks, Andrew R

**Comment by mattgodbolt** [comment]
CE currently runs on Linux under WINE, and so we're very limited in the support for Windows™ compilers we can provide. @AndrewPardoe of Microsoft is helping us work through a better solution.

**Comment by danilaml** [comment]
Same with `#include <limits>`, but works fine with ARM64.

**Comment by mattgodbolt** [comment]
I wonder if we can get Microsoft to add the ARM compilers to the officially supported set. CC @ubsan and @Rastaban if they can help (is there a better MS username to "at" to draw attention?)

**Comment by Rastaban** [comment]
I can't promise anything in the near future because we are all busy with Dev16 deadlines and the holidays.  I am interested in seeing this happen though.

**Comment by mattgodbolt** [comment]
Ping @Rastaban on this (thanks!)

**Comment by Rastaban** [comment]
FYI @dan-shaw

**Comment by partouf** [comment]
Since this does work on the Microsoft instanced MSVC versions, I'm going to close this one.
