### ISSUE TITLE
[BUG]: clang-trunk error when including <functional> from libstdc++

### ISSUE THREAD

**Issue by GuillaumeDua** [compiler-explorer/compiler-explorer#5731]
### Describe the bug

[disclaimer]: Don't know if this issue lies to llvm-clang or compiler-explorer. 

With clang-trunk and libstdc++ (gcc-14), including `<functional>` results in the following error:

```
Could not execute the program
Compiler returned: 1
Compiler stderr
In file included from <source>:4:
In file included from /opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/14.0.0/../../../../include/c++/14.0.0/functional:72:
In file included from /opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/14.0.0/../../../../include/c++/14.0.0/vector:67:
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/14.0.0/../../../../include/c++/14.0.0/bits/stl_bvector.h:189:35: error: expected string literal as argument of '__assume__' attribute
  189 |       __attribute__ ((__assume__ (__ofst < unsigned(_S_word_bit))));
      |                                   ^
1 error generated.
```

### Steps to reproduce

Link to reproduce: https://godbolt.org/z/nhGYrh1Wr

Code to reproduce:

```cpp
#include <functional>
auto main() -> int {}
```

### Expected behavior

It compiles, links, and produce the expected output.

### Reproduction link

https://godbolt.org/z/nhGYrh1Wr

### Screenshots

Not applicable

**Comment by partouf** [comment]
This tends to happen occasionally with bleeding edge compilers racing one another

This is probably because of this https://github.com/llvm/llvm-project/issues/71858

You can work around the issue by using `-stdlib=libc++`, using an older clang version, or selecting a different gcc toolchain from the Overrides options

**Comment by GuillaumeDua** [comment]
Thanks @partouf for pin-pointing the llvm issue, it seems to be the good one.
As mentioned in the disclaimer, if this is related to compilers vendors, then we can close it.

**Comment by partouf** [comment]
We can keep it open for a bit, so that other people running into this problem know what's up

**Comment by OfekShilon** [comment]
Fixed in trunk now, closing.
