### ISSUE TITLE
[BUG]: "TypeError: asm.replace is not a function" when "Compile to binary object" and LLVM MCA are both enabled

### ISSUE THREAD

**Issue by TiborGY** [compiler-explorer/compiler-explorer#5735]
### Describe the bug

Having the "Compile to binary object" option and the LLVM MCA tool enabled simultaneously results in the following error
```
Internal Compiler Explorer error: TypeError: asm.replace is not a function
    at LLVMMcaTool.rewriteAsm (file:///infra/.deploy/lib/tooling/llvm-mca-tool.js:32:14)
    at LLVMMcaTool.writeAsmFile (file:///infra/.deploy/lib/tooling/llvm-mca-tool.js:38:47)
    at LLVMMcaTool.runTool (file:///infra/.deploy/lib/tooling/llvm-mca-tool.js:45:20)
    at ClangCompiler.runToolsOfType (file:///infra/.deploy/lib/base-compiler.js:1343:49)
    at ClangCompiler.afterCompilation (file:///infra/.deploy/lib/base-compiler.js:2188:69)
    at ClangCompiler.afterCompilation (file:///infra/.deploy/lib/compilers/clang.js:100:22)
    at async file:///infra/.deploy/lib/base-compiler.js:2170:24
    at async env.enqueue.abandonIfStale (file:///infra/.deploy/lib/base-compiler.js:2151:25)
    at async file:///infra/.deploy/node_modules/p-timeout/index.js:90:13
Compiler returned: -1
```

### Steps to reproduce

1. Visit godbolt.org
2. Enable the LLVM MCA tool
3. Enable the "Compile to binary object" option
4. Observe that no LLVM MCA output is displayed
5. Wait a couple of minutes
6. Observe that an LLVM MCA output is now displayed, despite the ASM window still displaying `<Compilation failed>`

### Expected behavior

No Internal Compiler Explorer error is encountered.
LLVM MCA works correctly even if "Compile to binary object" is enabled. If that is not reasonable to support, make it fail gracefully with an error message stating they are mutually exclusive.

### Reproduction link

https://godbolt.org/z/PzcMvbrz5

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
Locally I don't get the live-site error, instead llvm-mca does try to run on the machine-code + asm output and emits errors like -
```
<source>:11:7: error: unexpected token at start of statement
   1:   48 89 e5                                                mov    rbp,rsp
        ^
<source>:12:7: error: unexpected token at start of statement
   4:   89 7d fc                                                mov    DWORD PTR [rbp-0x4],edi
        ^
```
So we should probably disable llvm-mca on 'binary object', same as we do for 'link to binary'. Fix already implemented, to be merged soon.
