### ISSUE TITLE
Rust beta/nightly optimises everything away

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#5782]
Not sure why but:
https://godbolt.org/z/71erEzGT6 optimizes to nothing, but removing the `-O` generates code as expected.

Not sure if this is a new thing where unused code is deleted that we don't understand?

**Comment by mattgodbolt** [comment]
Our flags are:
```
-C debuginfo=1 -o /tmp/compiler-explorer-compiler20231021-7139-1r6ir3a.t9ox/output.s --emit asm -Cllvm-args=--x86-asm-syntax=intel --crate-type rlib --color=always --edition 2021 -O /tmp/compiler-explorer-compiler20231021-7139-1r6ir3a.t9ox/example.rs
```

and with the filters off we only see:

```
        .text
        .intel_syntax noprefix
        .file   "example.e701e141d12e9087-cgu.0"
        .section        .debug_aranges,"",@progbits
        .ident  "rustc version 1.75.0-beta.1 (782883f60 2023-11-12)"
        .section        ".note.GNU-stack","",@progbits
```

so...not sure what's going on here!

**Comment by ohsix** [comment]
if i add -C link-dead-code=yes it stays

setting inline-threshold=0 didn't do it (it's not an inlining thing)

**Comment by Nilstrieb** [comment]
As of recently, rustc started to automatically add `#[inline]` to small functions. The attribute makes it so that functions are only codegened in codegen units that actually need them. rust-lang/rust#116505
I'm not sure what the best solution is here (there is an unstable flag to turn it off, and adding `#[no_mangle]` to functions is also a simple fix (not really something CE can do though)) @saethlin I forgot what you recommended to the playground and can't find it right now, so asking you :)

**Comment by mattgodbolt** [comment]
Thanks everyone!

**Comment by mattgodbolt** [comment]
I _think_ i'm going to close this as "working as intended" ... it's unfortunate but we can't go putting _too many_ byzantine surprising compiler options into the compiler to work around things the compiler's trying hard to do for us...

**Comment by saethlin** [comment]
FWIW, this property has been surprising to a lot of people at this point; it wouldn't hurt to have a note (in the UI? I swear I saw the guidance to add `pub` on the site long ago) that in addition to making functions you want to see `pub` that you may need to add `#[inline(never)]` to them.

**Comment by partouf** [comment]
Could change the default example https://github.com/compiler-explorer/compiler-explorer/blob/main/examples/rust/default.rs
but it will only show up for new users/new domain/new browser/etc

**Comment by Kimundi** [comment]
I wonder if it would make sense for CE to provide a small helper macro for Rust code, eg 
```rust
#[codegen]
fn foo() {}
```
that expands to just
```rust
#[inline(never)]
pub foo() {}
```

Probably not worth the effort though, as it hard to predict what else might break in the future, and if fixing those case can be done with a attribute
