### ISSUE TITLE
[BUG]: In IR CFG the entry block's label isn't shown

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#5784]
### Describe the bug

In this example simple case: https://www.compiler-explorer.com/z/Gj5KT9861
The topmost block in the CFG has the label `loop1(long, long*, long*):`  instead of `for.body.preheader:`.

### Steps to reproduce

Visit the link.

### Expected behavior

I personally think the block's label can replace the function name - no need to display both. The function name is visible at the function selection dropdown

### Reproduction link

https://www.compiler-explorer.com/z/Gj5KT9861

### Screenshots

![image](https://github.com/compiler-explorer/compiler-explorer/assets/73080/a510e507-96bf-4232-a1a4-642cf7f5cbfb)

**Comment by jeremy-rifkin** [comment]
Oh, I think this rings a bell. It may be good to not completely discard that label :)

**Comment by OfekShilon** [comment]
@jeremy-rifkin you did put this comment in `splitToLlvmBlocks`: 
https://github.com/compiler-explorer/compiler-explorer/blob/5bcfd84bac6df87c7c53c3d67b27bca7f03e6577/lib/cfg/cfg-parsers/llvm-ir.ts#L87

I *think* this is true for assembly, but not to IR. At least for the cases I came across so far. Anyway is this view acceptable? (function name + label)
<img width="426" alt="image" src="https://github.com/compiler-explorer/compiler-explorer/assets/73080/075e64f3-aceb-453d-b96d-b34370d90b6a">

If so I'll submit a PR with the fix.

**Comment by jeremy-rifkin** [comment]
Looks good to me!
