### ISSUE TITLE
[BUG]: Unittest under Windows issue

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#5786]
### Describe the bug

Don't know how long it's been that this issue has been in here, because it's not treated as an error, but:
```
  1 failing

  1) CompilerDropInTool
       Should be able to swap toolchain:

      AssertionError: expected [ '-gdwarf-4', '-g', '-o', …(8) ] to deeply equal [ '-gdwarf-4', '-g', '-o', …(8) ]
      + expected - actual

         "output.s"
         "-mllvm"
         "--x86-asm-syntax=intel"
         "-S"
      -  "--gcc-toolchain=\\opt\\compiler-explorer\\gcc-11.1.0"
      +  "--gcc-toolchain=/opt/compiler-explorer/gcc-11.1.0"
         "-fcolor-diagnostics"
         "-fno-crash-diagnostics"
         "/app/example.cpp"
       ]
      
      at Context.<anonymous> (file:///D:/a/compiler-explorer/compiler-explorer/test/tool-tests.ts:189:37)
      at process.processImmediate (node:internal/timers:478:21)
```

### Steps to reproduce

-

### Expected behavior

Should probably include a *if win32 then use the other slash*

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
It's probably better to use `path.join` than some explicit 'if win32' construct, but slash direction isn't the only issue here: there is no `\opt` folder in windows, good chance gcc was installed to somewhere beginning with `C:\`. 

I'm surprised to see that running CE on windows is even supported. Are there actual instances running on windows?  If so, do they use the 'infra' scripts? If so, where do these scripts install compilers on windows?

**Comment by partouf** [comment]
> It's probably better to use `path.join` than some explicit 'if win32' construct, but slash direction isn't the only issue here: there is no `\opt` folder in windows, good chance gcc was installed to somewhere beginning with `C:\`.
> 
> I'm surprised to see that running CE on windows is even supported. Are there actual instances running on windows? If so, do they use the 'infra' scripts? If so, where do these scripts install compilers on windows?

Yes, we do! We refer to the server godbolt.ms which is hosted with an old version of CE by Microsoft, and we run godbolt.org/winprod ourselves for the mingw compilers.

The mingw compilers are installed from our linux admin node https://github.com/compiler-explorer/infra/blob/main/bin/yaml/windows.yaml and then get transfered to a network share that windows instances can access.

To install: https://github.com/compiler-explorer/infra/blob/main/docs/installing_compilers.md#on-ce-infrastructure

Some more documentation https://github.com/compiler-explorer/infra/blob/main/docs/windows_architecture.md

This is the packer script we use to make an image https://github.com/compiler-explorer/infra/blob/main/packer-win.json

And this is our sandbox application that we use, that we recently made public https://github.com/compiler-explorer/cewrapper which makes it possible for us to run compilers and user code in a sandbox.

The unittests however just run on Github's environment https://github.com/compiler-explorer/compiler-explorer/blob/main/.github/workflows/test-win.yml and https://github.com/compiler-explorer/compiler-explorer/blob/main/.github/workflows/deploy-win.yml

**Comment by OfekShilon** [comment]
Thanks for all the info! The relevant bit seems this: https://github.com/compiler-explorer/infra/blob/main/docs/installing_compilers.md#on-windows

The command line specified is 
```ps
./ce_install.ps1 --staging-dir "D:/tmp/staging" --dest "D:/efs/compilers" --enable windows install windows
``` 
While I got a bunch of errors trying to run it myself, it seems to indicate the default compilers root folder is "D:/efs/compilers". That's probably what the win tests expect, no?

**Comment by OfekShilon** [comment]
@partouf so I tried to follow the docs, made some [small fixes](https://github.com/compiler-explorer/infra/issues/1168) along the way but still can't get anything to run on windows. Can you say whether `ce_install.ps1` actually runs on windows today?

**Comment by partouf** [comment]
So, tar -xf should definitely work https://superuser.com/a/1473255

But I never tested the extract_into_folder option, which was only meant for linux's unzip

Fixing that now

**Comment by partouf** [comment]
lots of unittests failing or at least showing up in the github file changes page (but not showing up as actual test failures)

**Comment by partouf** [comment]
mostly fixed now
