### ISSUE TITLE
[BUG]: GCC trunk is stuck on intel mode

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#5797]
### Describe the bug

The option to change intel/at&t is greyed out for gcc trunk

### Steps to reproduce

go to the site and pick x86 trunk: https://godbolt.org/z/xzo7GEGfx
try and change to AT&T syntadx

### Expected behavior

should be supported

### Reproduction link

https://godbolt.org/z/xzo7GEGfx

### Screenshots

Not applicable

**Comment by GabrielRavier** [comment]
I have the opposite problem - GCC trunk is stuck on AT&T mode for me

**Comment by mattgodbolt** [comment]
Well that's far worse!! @GabrielRavier that makes this a high priority. Will try and find a fix asap

**Comment by jeremy-rifkin** [comment]
Now resolved
