### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by zBeeble42** [compiler-explorer/compiler-explorer#5798]
### Describe the bug

Various clang > 14 don't have asprintf(3) available (at least with #include <stdio.h>).  clang <= 14 work.  As do any gcc versions (including trunk).

### Steps to reproduce

1. visit godbolt.org
2. select C and clang >= 15.  I used X85/64 and risc-v to test.
3. load in a short bit of C that includes "#include <stdio.h>" and a call to asprintf()
4. fail.

### Expected behavior

not fail.

### Reproduction link

https://godbolt.org/z/vzfq7MTfv

### Browser version

Firefox 120.0 64bit windows 10.

**Comment by mattgodbolt** [comment]
Per the [man page](https://man7.org/linux/man-pages/man3/asprintf.3.html) this is a GNU extension that requires `#define _GNU_SOURCE` -> https://godbolt.org/z/7dY1xvz4K
