### ISSUE TITLE
[BUG]: Case of messed up IR CFG

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#5799]
### Describe the bug

Somehow no edges are formed here:
https://www.compiler-explorer.com/z/3j4bEaWG1

### Steps to reproduce

Visit the link

### Expected behavior

Valid control flow graph.

### Reproduction link

Not applicable

### Screenshots

<img width="508" alt="image" src="https://github.com/compiler-explorer/compiler-explorer/assets/73080/f36e12e3-e6fd-489b-a957-9ee03282e503">

**Comment by jeremy-rifkin** [comment]
Nice find
