### ISSUE TITLE
[BUG]: Clang trunk compiler for C/C++ doesn't allow LLVM IR output

### ISSUE THREAD

**Issue by Benjins** [compiler-explorer/compiler-explorer#5802]
### Describe the bug

Selecting a trunk version of clang for C/C++, it's not possible to add an LLVM-IR output panel. If one is added and then the compiler is changed back to Clang trunk, it does not show the IR. It instead says "<LLVM IR output is not supported for this compiler>". I tried for X86, ARM, and RISC-V, and none of them showed LLVM IR output or allowed the panel to be added

Selecting a 16.x or 17.x clang compiler for C++ does not repro this, and allows LLVM-IR output as expected

### Steps to reproduce

1. Visit godbolt.org
2. Select C or C++ language
3. Add Clang trunk compiler (X86, ARM/ RISC-V)
4. Select "Add New..." menu
5. There is no option to add LLVM-IR. If one is added, it does not show the output, instead giving an error that it isn't supported

### Expected behavior

The compiler should offer LLVM IR as an output for clang trunk versions, and if it's selected it should show the produced IR

### Reproduction link

https://godbolt.org/z/a4EPej5a9

### Screenshots

![2023_11_26_godbolt_clang_trunk_llvm_ir_output_bug_01](https://github.com/compiler-explorer/compiler-explorer/assets/6193112/c81f2d71-dca9-4be4-be8d-af22d70b4134)

### Operating System

Windows

### Browser version

Google Chrome 119.0.6045.124 (Official Build) (64-bit)

**Comment by jeremy-rifkin** [comment]
Thanks for the report!

**Comment by jeremy-rifkin** [comment]
Now resolved
