### ISSUE TITLE
[BUG]: Rust 1.55.0 and lower gives unfriendly errors about Edition 2021

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [compiler-explorer/compiler-explorer#5803]
### Describe the bug

See title

### Steps to reproduce

1. Visit https://rust.godbolt.org/
2. Select `rust 1.55.0`

```
error: the crate requires edition 2021, but the latest edition supported by this Rust version is 2018

Compiler returned: 1
```

### Expected behavior

The `--edition` flag can be configured, but is not hard-coded.

### Reproduction link

https://rust.godbolt.org/z/Yr75j8cK6

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment]
As a workaround the "Overrides" can be used to supply an older version.

**Comment by mattgodbolt** [comment]
In fact, I'm not sure why the overrides get pre-popluated with 2021 and then picking an older version "keeps" it

**Comment by partouf** [comment]
> In fact, I'm not sure why the overrides get pre-popluated with 2021 and then picking an older version "keeps" it

Because it supports it as a command line argument. I don't really feel like making exceptions upon exceptions for Rust.

Feel free to send a PR if anyone has a good idea on making it more user friendly.

**Comment by partouf** [comment]
Forgot this was a duplicated of https://github.com/compiler-explorer/compiler-explorer/issues/5349 so closing this issue
