### ISSUE TITLE
Toast notification z-index issue

### ISSUE THREAD

**Issue by jeremy-rifkin** [compiler-explorer/compiler-explorer#5822]
![image](https://github.com/compiler-explorer/compiler-explorer/assets/51220084/707fef3e-b814-4418-9b29-0590e2d941db)

**Comment by partouf** [comment]
An attempt to fix this was done here https://github.com/compiler-explorer/compiler-explorer/pull/5719 but the solution doesn't work and it might not be fixable from the toast's perspective. We might have to do something about the editors map instead.

**Comment by RubenRBS** [comment]
Weird! In my testing it worked locally. Wonder what the difference is?

**Comment by partouf** [comment]
should be fixed by https://github.com/compiler-explorer/compiler-explorer/commit/88e94c9e903b32285ca2dcb0c470906bc93901d4

**Comment by jeremy-rifkin** [comment]
Awesome!

**Comment by mattgodbolt** [comment]
Oh you star: thank you partouf!
