### ISSUE TITLE
[BUG]: LLVM IR viewer is no longer working for LDC (D language)

### ISSUE THREAD

**Issue by JohanEngelen** [compiler-explorer/compiler-explorer#5826]
### Describe the bug

For the D language, LLVM IR view is no longer working. Instead it displays: `Internal error; unable to open output path`.

### Steps to reproduce

Select LDC compiler for D, for example LDC 1.34.0, and open the LLVM IR viewer (Add new ... -> LLVM IR)

### Expected behavior

LLVM IR output should be there

### Reproduction link

https://cpp.godbolt.org/z/Po4fjd5Pn

### Screenshots

Not applicable

**Comment by partouf** [comment]
Ah, something went wrong here https://github.com/compiler-explorer/compiler-explorer/pull/5749/files#diff-8db8be3ba7abc816d6dfa1e8dff8edf9bb38d8e269bc58f608ec8b7fa4f669abL133

I did not pay enough attention. The .ll file should be based on the outputfilename (output.s) and not on the inputfile (example.d)

**Comment by partouf** [comment]
Fix is now live
