### ISSUE TITLE
[BUG]: cannot set environment variables whose values contains equal signs

### ISSUE THREAD

**Issue by dangelog** [compiler-explorer/compiler-explorer#5847]
### Describe the bug

In an "Executor" pane one can click the "Runtime tools" button and use it to set environment variables, as a list of KEY=VALUE pairs.

If a VALUE contains an equal sign however this doesn't seem to work. For instance, setting `ASAN_OPTIONS=detect_invalid_pointer_pairs=2` truncates the input and sets only `ASAN_OPTIONS=detect_invalid_pointer_pairs`, resulting in an error.

I'm not sure if there's a workaround (double quotes?).

### Steps to reproduce

Add an executor to a compiler.
Click "Runtime Tools" and paste `ASAN_OPTIONS=detect_invalid_pointer_pairs=2` to its environment variables.
Close the dialog to validate the changes.
Open "Runtime Tools" again: the `=2` has been lost.

### Expected behavior

Environment variables are kept as-is.

### Reproduction link

https://gcc.godbolt.org/z/jr1nresad

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
Thanks for reporting this! A fix is underway: https://github.com/compiler-explorer/compiler-explorer/pull/5882
