### ISSUE TITLE
[COMPILER REQUEST]: GCC trunk on powerpc64 and powerpc64le

### ISSUE THREAD

**Issue by jedilyn** [compiler-explorer/compiler-explorer#5881]
### Compiler name

GCC

### Compiler version

trunk GCC

### Compiler language

the same as what the current GCC 13.2.0 provides

### Compiler homepage

https://gcc.gnu.org/

### Motivation

Currently the compiler explorer provides GCC 11, 12, 13 on powerpc64/powerpc64le but not GCC trunk. But for clang, it provides the clang trunk, it would be helpful to have GCC trunk on ppc64{,le} as well.

**Comment by dkm** [comment]
This can be done yes!

**Comment by dkm** [comment]
refs https://github.com/compiler-explorer/compiler-explorer/issues/2041

Both compilers are correctly built along other nightlies. Now I only need to update the gazillions config files :sweat_smile:

**Comment by dkm** [comment]
This is live :rocket:

**Comment by jedilyn** [comment]
Perfect, thanks a lot!
