### ISSUE TITLE
[BUG]: IDE Mode doesn't allow selection of languages beyond Pascal (selection limit?)

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#5883]
### Describe the bug

From ADA to Pascal is visible, but nothing beyond that

### Steps to reproduce

Add IDE mode, try to select Scala for example, not there

### Expected behavior

Rust, Scala, Python, and more should be visible to select from

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
I did some tomselect-related changes there, maybe I broke something?  Will check today.
