### ISSUE TITLE
[BUG]: clang AST not filtering out std code

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#5889]
### Describe the bug

Non-user code isn't filtered out:
https://godbolt.org/z/3dx8xhd9b

There's an attempt to do it in:
 https://github.com/compiler-explorer/compiler-explorer/blob/cc1e0ea283af0fb559a070e24212c999349028b0/lib/llvm-ast.ts#L144-L146

Needs to be re-examined.

### Steps to reproduce

https://godbolt.org/z/3dx8xhd9b

### Expected behavior

display AST for just user code.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by partouf** [comment]
this is now live
