### ISSUE TITLE
[BUG]: issue involving Duplicate compiler id d8-8156 

### ISSUE THREAD

**Issue by miles0201** [compiler-explorer/compiler-explorer#5897]
### Describe the bug

Duplicate compiler id d8-8156 when trying to build a newly updated local windows installtion. I believe it is related to the very recent addition of android-java.amazon.properties and android-kotlin.amazon.properties

### Steps to reproduce

Update to the very latest GIT version (last couple of days). Follow directions to build a c++.local.properties file from WindowsLocal.properties. Attempt to build and get:

Duplicate compiler id d8-8156

WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.89.0 compiled with 3 warnings in 1868 ms
info: properties hierarchy: defaults, dev, dev.win32, win32, VM-Windows11Dev, local
info: Reading properties from etc\config with hierarchy defaults,dev,dev.win32,win32,vm-windows11dev,local
info: Not configuring sentry
info: WINE not configured
warn: Unable to stat tools.clangquerydefault tool binary
warn: Unable to stat tools.clangtidydefault tool binary
warn: Unable to stat tools.clangquery7 tool binary
warn: Unable to stat tools.clangquery8 tool binary
warn: Unable to stat tools.clangquery9 tool binary
warn: Unable to stat tools.clangquery10 tool binary
warn: Unable to stat tools.clangquery11 tool binary
warn: Unable to stat tools.clangquery12 tool binary
warn: Unable to stat tools.strings tool binary
warn: Unable to stat tools.ldd tool binary
warn: Unable to stat tools.readelf tool binary
warn: Unable to stat tools.nm tool binary
warn: Unable to stat tools.llvmdwarfdumpdefault tool binary
warn: Unable to stat tools.clangquerydefault tool binary
warn: Unable to stat tools.clangtidydefault tool binary
warn: Unable to stat tools.readelf tool binary
warn: Unable to stat tools.nm tool binary
warn: Unable to stat tools.llvmdwarfdumpdefault tool binary
warn: Unable to stat tools.strings tool binary
warn: Unable to stat tools.ldd tool binary
warn: Unable to stat tools.llvmdwarfdumpdefault tool binary
warn: Unable to stat tools.strings tool binary
warn: Unable to stat tools.ldd tool binary
warn: Unable to stat tools.llvmdwarfdumpdefault tool binary
warn: Unable to stat tools.readelf tool binary
warn: Unable to stat tools.nm tool binary
warn: Unable to stat tools.llvmdwarfdumpdefault tool binary
info: OPTIONS HASH: eee361cc42ae6807c0c941a958275650b33d4c86689c796a1a23bdb5dd6563a9
info: Created cache default of type InMemoryCache(50Mb)
info: Created cache executable of type InMemoryCache(50Mb)
info: Created cache compiler of type OnDiskCache(out/compiler-cache, 1024mb)
'gcc' is not recognized as an internal or external command,
operable program or batch file.
warn: Unable to get multiarch: Error: Command failed: gcc -print-multiarch
'gcc' is not recognized as an internal or external command,
operable program or batch file.

info: Cleaning temp dirs every 600 secs
info: Using local storage solution on lib\storage\data\
info: =======================================
info:   git release f8dd324af3cde9204f98fca739b5640eec943fad
error: Duplicate compiler id android-d8-default in domain defaults,local
error: Group vc2017_32 is orphaned from the language compilers list for c++ in domain defaults,local
error: Group vc2017_64 is orphaned from the language compilers list for c++ in domain defaults,local
error: Top-level error (shutting down): Assertion failed {"stack":"Error: Assertion failed\n    at fail (file:///C:/LocalTransfer/Programming/Tools/CompilerExplorer/compiler-explorer/lib/assert.ts:91:15)\n    at assert (./compiler-explorer/lib/assert.ts:96:9)\n    at CompilerFinder.checkOrphanedProperties (./compiler-explorer/lib/compiler-finder.ts:485:13)\n    at CompilerFinder.find (./compiler-explorer/lib/compiler-finder.ts:489:14)\n    at main (./compiler-explorer/app.ts:443:57)"}

### Expected behavior

Used to build OK. Restore local vs2017 (or VS2022) build and operational behavior

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Windows 11

### Browser version

Firefox

**Comment by mattgodbolt** [comment]
Oh! Thank you for spotting that -- I haven't had this happen locally but it seems likely that's an issue!
if you can pass a command line argument of `--language c++` then that might get you running temporarily

**Comment by jrmwng** [comment]
I encounter very similar error messages. CE had worked fine in my environment (Windows 11 + VS2022 community edition with clang) some months ago.

```
C:\GitHub\compiler-explorer>npm start --language c++

> compiler-explorer@0.0.3 start
> npm run webpack && cross-env NODE_ENV=LOCAL node --no-warnings=ExperimentalWarning --loader ts-node/esm app.ts c++


> compiler-explorer@0.0.3 webpack
> node --no-warnings=ExperimentalWarning --loader ts-node/esm ./node_modules/webpack-cli/bin/cli.js --node-env=production --config webpack.config.esm.ts

webpack: compiling for production.
webpack: Limiting parallelism to 8
assets by status 10.9 MiB [cached] 64 assets
assets by status 4.9 MiB [compared for emit]
  assets by path ../../dist/ 60.9 KiB
    asset ../../dist/static/favicons/favicon-suspend.ico 11.5 KiB [compared for emit] [from: static/favicons/favicon-suspend.ico] [copied]
    asset ../../dist/static/favicons/favicon-dev.ico 11.5 KiB [compared for emit] [from: static/favicons/favicon-dev.ico] [copied]
    asset ../../dist/static/favicons/favicon-staging.ico 11.5 KiB [compared for emit] [from: static/favicons/favicon-staging.ico] [copied]
    asset ../../dist/static/favicons/favicon-beta.ico 11.4 KiB [compared for emit] [from: static/favicons/favicon-beta.ico] [copied]
    asset ../../dist/static/favicons/favicon.ico 10.8 KiB [compared for emit] [from: static/favicons/favicon.ico] [copied]
    asset ..\..\dist\manifest.json 4.28 KiB [compared for emit]
  assets by path *.js 4.84 MiB
    asset ts.v38.worker.fe8c176051b0598f2fb9bdd3459c965f.js 4.61 MiB [compared for emit] [minimized] [big] 2 related assets
    asset editor.v38.worker.afbd84bf87ff32f64c63d43e1a5dde9a.js 237 KiB [compared for emit] [minimized] 1 related asset
Entrypoint main [big] 5.43 MiB (25 MiB) = runtime.v38.d03233f132271a824b3b.js 2.1 KiB vendor.v38.7c5805b94835eb42d2e9.css 391 KiB vendor.v38.731a9954d4c11dc39cac.js 4.16 MiB main.v38.b30d6f9f63aba6c65c4d.css 71.7 KiB main.v38.6ff1f38e9586e1d600b6.js 832 KiB 61 auxiliary assets
Entrypoint noscript [big] 4.55 MiB (18.4 MiB) = runtime.v38.d03233f132271a824b3b.js 2.1 KiB vendor.v38.7c5805b94835eb42d2e9.css 391 KiB vendor.v38.731a9954d4c11dc39cac.js 4.16 MiB noscript.v38.25c83b732e82c1f0c668.css 444 bytes noscript.v38.91c71bc0583e11ef1ade.js 2.98 KiB 12 auxiliary assets
cached modules 20.5 MiB (javascript) 4.44 MiB (asset) 472 KiB (css/mini-extract) 4.86 KiB (runtime) [cached] 1511 modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  ts.v38.worker.fe8c176051b0598f2fb9bdd3459c965f.js (4.61 MiB)
  45a265d0f07b31cde85f.ttf (410 KiB)
  573d754b19d4042030ff.svg (320 KiB)
  6ecce7fcf653602d83fc.png (253 KiB)
  baf2659a761351ec4924.png (253 KiB)
  082d1652adebc1c3d815.png (260 KiB)
  fee4405468d39f59ab0e.png (245 KiB)
  main.v38.6ff1f38e9586e1d600b6.js (832 KiB)
  vendor.v38.7c5805b94835eb42d2e9.css (391 KiB)
  vendor.v38.731a9954d4c11dc39cac.js (4.16 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (5.43 MiB)
      runtime.v38.d03233f132271a824b3b.js
      vendor.v38.7c5805b94835eb42d2e9.css
      vendor.v38.731a9954d4c11dc39cac.js
      main.v38.b30d6f9f63aba6c65c4d.css
      main.v38.6ff1f38e9586e1d600b6.js
  noscript (4.55 MiB)
      runtime.v38.d03233f132271a824b3b.js
      vendor.v38.7c5805b94835eb42d2e9.css
      vendor.v38.731a9954d4c11dc39cac.js
      noscript.v38.25c83b732e82c1f0c668.css
      noscript.v38.91c71bc0583e11ef1ade.js


WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.89.0 compiled with 3 warnings in 1384 ms
info: properties hierarchy: defaults, dev, dev.win32, win32, DESKTOP-G2MH1GV, local
info: Reading properties from etc\config with hierarchy defaults,dev,dev.win32,win32,desktop-g2mh1gv,local
info: Not configuring sentry
info: WINE not configured
warn: Unable to stat tools.clangquerydefault tool binary
warn: Unable to stat tools.clangtidydefault tool binary
warn: Unable to stat tools.clangquery7 tool binary
warn: Unable to stat tools.clangquery8 tool binary
warn: Unable to stat tools.clangquery9 tool binary
warn: Unable to stat tools.clangquery10 tool binary
warn: Unable to stat tools.clangquery11 tool binary
warn: Unable to stat tools.clangquery12 tool binary
warn: Unable to stat tools.strings tool binary
warn: Unable to stat tools.ldd tool binary
warn: Unable to stat tools.readelf tool binary
warn: Unable to stat tools.nm tool binary
warn: Unable to stat tools.llvmdwarfdumpdefault tool binary
warn: Unable to stat tools.clangquerydefault tool binary
warn: Unable to stat tools.clangtidydefault tool binary
warn: Unable to stat tools.readelf tool binary
warn: Unable to stat tools.nm tool binary
warn: Unable to stat tools.llvmdwarfdumpdefault tool binary
warn: Unable to stat tools.strings tool binary
warn: Unable to stat tools.ldd tool binary
warn: Unable to stat tools.llvmdwarfdumpdefault tool binary
warn: Unable to stat tools.strings tool binary
warn: Unable to stat tools.ldd tool binary
warn: Unable to stat tools.llvmdwarfdumpdefault tool binary
warn: Unable to stat tools.readelf tool binary
warn: Unable to stat tools.nm tool binary
warn: Unable to stat tools.llvmdwarfdumpdefault tool binary
info: OPTIONS HASH: a44f3fbe159e5202177c5659c2cca9365c72a396f6ced1c688c025d9bf44aea5
info: Created cache default of type InMemoryCache(50Mb)
info: Created cache executable of type InMemoryCache(50Mb)
info: Created cache compiler of type OnDiskCache(out/compiler-cache, 1024mb)
'gcc' is not recognized as an internal or external command,
operable program or batch file.
warn: Unable to get multiarch: Error: Command failed: gcc -print-multiarch
'gcc' is not recognized as an internal or external command,
operable program or batch file.

info: Cleaning temp dirs every 600 secs
info: Using local storage solution on lib\storage\data\
info: =======================================
info:   git release a0f14383a6c4e40d73ba707e02575dd972197afe
error: Duplicate compiler id d8-8156 in domain amazon,amazonwin,gpu
error: Duplicate compiler id android-d8-default in domain defaults,local
error: Group clang_32 is orphaned from the language compilers list for c++ in domain defaults,local
error: Group clang_64 is orphaned from the language compilers list for c++ in domain defaults,local
error: Group vc2019_32 is orphaned from the language compilers list for c++ in domain defaults,local
error: Group vc2019_64 is orphaned from the language compilers list for c++ in domain defaults,local
error: Top-level error (shutting down): Assertion failed {"stack":"Error: Assertion failed\n    at fail (file:///F:/GitHub/compiler-explorer/lib/assert.ts:91:15)\n    at assert (file:///F:/GitHub/compiler-explorer/lib/assert.ts:96:9)\n    at CompilerFinder.checkOrphanedProperties (file:///F:/GitHub/compiler-explorer/lib/compiler-finder.ts:485:13)\n    at CompilerFinder.find (file:///F:/GitHub/compiler-explorer/lib/compiler-finder.ts:489:14)\n    at main (file:///F:/GitHub/compiler-explorer/app.ts:443:57)"}
```

**Comment by miles0201** [comment]
Like you, I tried Matt Godbolt's suggestion.; like you, I obtained the same results as you documented above.

**Comment by partouf** [comment]
This is also a major issue with the live site, except we don't get those warnings it seems. The same ID just gets used for both the kotlin and java compilation. This is extremely bad.

**Comment by partouf** [comment]
fix is live
