### ISSUE TITLE
[LIB REQUEST] Boost

### ISSUE THREAD

**Issue by wongmunchoy** [compiler-explorer/compiler-explorer#5922]
Website: https://www.boost.org/

**Comment by partouf** [comment]
Can you expand on your request? as we do have Boost added as a Library currently

**Comment by wongmunchoy** [comment]
I was using a local instance of Compiler Explorer and there is no Boost Library there.
It looks like the link to suggest a library from there has redirected this to GitHub Compiler Explorer and I was not aware of this.
Please consider closing the request. Thank you for the reply.
