### ISSUE TITLE
[BUG]: The LLVM IR comment filter should ignore `;` in some cases

### ISSUE THREAD

**Issue by ojeda** [compiler-explorer/compiler-explorer#5923]
### Describe the bug

The LLVM IR comment filter (or Clang with `-emit-llvm`) considers `;` as a comment inside a string literal, thus removes the rest of the line.

This can come up when inspecting the LLVM IR output of inline assembly (which may be using `;` to separate instructions in some cases) or string literals.

The filter can be easily disabled by the user though, so there is a simple workaround.

### Steps to reproduce

Compile:

```c
asm("nop; nop");
const char* s = "nop; nop";
```

with Clang and use `-emit-llvm` or use the LLVM IR Viewer. Notice how lines are cut in the output. Disable the comment filter to see them properly.

### Expected behavior

The comment filter could be improved to avoid filtering in some cases.

### Reproduction link

https://godbolt.org/z/Yh5dqTd9T

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
Thanks, good find

**Comment by OfekShilon** [comment]
I created a PR with a fix for this particular example (#5929). The fixed code might still be confused by escaped quotes `\"`, but I can't think of a way to create this in real IR so ignoring it for now..
@ojeda your phrasing was general - did you have other examples in mind? I can't think of others in real IR, would love to tackle it while I'm around this code.

**Comment by ojeda** [comment]
Thanks! No, I didn't notice other examples but I didn't know if there could be other cases.

**Comment by partouf** [comment]
fix is now live
