### ISSUE TITLE
[COMPILER REQUEST]: UPMEM DPU Compiler

### ISSUE THREAD

**Issue by JulianvDoorn** [compiler-explorer/compiler-explorer#5936]
### Compiler name

dpu-upmem-dpurte-clang

### Compiler version

version 2023.2.0

### Compiler language

C

### Compiler homepage

https://sdk.upmem.com/

### Motivation

Compiler explorer does not host UPMEM's compiler for their processing-in-memory architecture. It would be nice if their platform specific compiler can be made available on compiler explorer. (See https://www.upmem.com/ for more info)

It seems like UPMEM themselves have made an attempt at adding it (https://github.com/upmem/compiler-explorer), however their repository is already 5070 commits behind. Which, I think, is the reason that running make no longer works out of the box.

**Comment by partouf** [comment]
It looks like it's pretty straight forward from their changes https://github.com/compiler-explorer/compiler-explorer/compare/main...upmem:compiler-explorer:master

And the LLVM based compiler + libraries can be downloaded at sdk.upmem.com

Will need similar changes to our c.amazon.properties
And compilers will also need to be added here https://github.com/compiler-explorer/infra/blob/main/bin/yaml/c.yaml to download

**Comment by JulianvDoorn** [comment]
@partouf Thank you for your pointers, I've made an attempt to make the changes you mentioned (see https://github.com/compiler-explorer/compiler-explorer/compare/main...JulianvDoorn:compiler-explorer:main and https://github.com/compiler-explorer/infra/compare/main...JulianvDoorn:infra:main).

I think it should work, since using ce_install installs the compiler just fine on Ubuntu 22.04. When
The only thing left is that only the latest compiler supports Ubuntu 22.04, prior versions only support 20 or earlier. I don't know how I could put the OS/platform as a wildcard into the URL (similarly to how {name} is replaced with target versions). If you happen to know how this can be done the best way then please let me know, so that I can make the edit and possibly open a PR.

**Comment by dkm** [comment]
Nice. Please create a PR, makes discussion easier! (Nice to see upmem is still alive !)

**Comment by dkm** [comment]
I believe this is now done.
