### ISSUE TITLE
[BUG]: If ..  else goto has wrong code highlighting

### ISSUE THREAD

**Issue by evilpie** [compiler-explorer/compiler-explorer#5941]
### Describe the bug

C code produced by mrustc is is wrongly highlighted.

The following is `if` and `else`, it should not be shown as a comment.
```c
if(var0) goto bb1; else goto bb2;
```

### Steps to reproduce

1. Visit Godbolt
2. Paste the code
3. Select Rust and the compiler "mrustc"

```rust
pub fn square(num: i32) -> i32 {
    return if (num > 5) { num * num } else { 0 }
}
````

### Expected behavior

`else goto bb2;` is shown as normal code, so colors following `if(var0) goto bb1;`.

### Reproduction link

https://godbolt.org/z/86oEv7G9v (Line 139)

### Screenshots

![image](https://github.com/compiler-explorer/compiler-explorer/assets/296445/ab14f5de-8b58-473c-a54a-5dc4045bff33)

### Browser version

Firefox

**Comment by OfekShilon** [comment]
Could you please share a link which includes the offending code example?
On the tab that contains the example, Click 'share' / 'short link'.
![image](https://github.com/compiler-explorer/compiler-explorer/assets/73080/0708faca-7417-46bc-a7c2-43d9e57c0041)

**Comment by evilpie** [comment]
The link works correctly for me.

![image](https://github.com/compiler-explorer/compiler-explorer/assets/296445/0d0f9d07-4582-4c12-a6fb-20d7daa784d1)

**Comment by OfekShilon** [comment]
Sorry I see now. The output of compilation is parsed _as assembly_, which has many artifacts when it is in fact C code. It's not just the `goto` you pointed to, note even the coloring of `static` much earlier in the output:
![image](https://github.com/compiler-explorer/compiler-explorer/assets/73080/5abd3c67-5249-46b1-8805-5f7aca73013d)

Not sure there's a reasonable fix, but I'll look into it. As a workaround you can paste the output into a C-source pane (even in another CE tab).
