### ISSUE TITLE
[BUG]: newer Intel icc compilers use incompatible libstdc++ headers

### ISSUE THREAD

**Issue by jwakely** [compiler-explorer/compiler-explorer#5943]
### Describe the bug

Any non-trivial use of C++17 (or later) results in errors with icc 2021.8.0 and newer icc versions. The errors come from the libstdc++ headers, because GCC 13 uses a new `__is_convertible` built-in unconditionally in C++17 mode. That is [a libstdc++ bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113241), but until it's fixed CE should probably not use GCC 13 headers with Intel icc compilers. Using headers from GCC 12 should work.

### Steps to reproduce

Compile any C++ program that includes `<type_traits>` using "x86_64 icc 2021.8.0", or 2021.9.0, or 2021.10.0

### Expected behavior

No unfixable error coming from the standard library headers.

### Reproduction link

https://gcc.godbolt.org/z/esEG8jeqa

### Screenshots

Not applicable

### Operating System

N/A

### Browser version

N/A

**Comment by jwakely** [comment]
A workaround is to add this before including any headers:

```c++
#define __is_convertible(F, T) is_convertible<F, T>::value
```

but it's undefined to use a reserved name like that, so this is not something users should be encouraged to do.

**Comment by dkm** [comment]
Strange, the config has:
```
compiler.icc202171.exe=/opt/compiler-explorer/intel-cpp-2022.2.1.16991/compiler/latest/linux/bin/intel64/icc
compiler.icc202171.ldPath=/opt/compiler-explorer/intel-cpp-2022.2.1.16991/compiler/latest/linux/compiler/lib/intel64_lin
compiler.icc202171.libPath=/opt/compiler-explorer/intel-cpp-2022.2.1.16991/compiler/latest/linux/compiler/lib/intel64_lin:/opt/compiler-explorer/intel-cpp-2022.2.1.16991/compiler/latest/linux/compiler/lib/ia32_lin
compiler.icc202171.semver=2021.7.1
compiler.icc202171.options=-gxx-name=/opt/compiler-explorer/gcc-12.2.0/bin/g++
```

**Comment by jwakely** [comment]
I've fixed the libstdc++ bug, so gcc 13.3 headers should be ok again.

**Comment by dkm** [comment]
Oh, nice to hear, thanks for the notification @jwakely . The 13.3 will probably be released in a few months (~~april/may). We could use gcc-12 headers until 13.3 is released. That's several changes in a short time, but I guess if we break old links with gcc-12, switching to gcc-13.3 would probably fix them back. Does that sound reasonable?

**Comment by dkm** [comment]
Looks like I need to fiddle more intel config, 2021.{8,9,10}

**Comment by mattgodbolt** [comment]
> I guess we may break some existing "shared" link by switching from 13 to 12... @mattgodbolt what should we do in this case? :)

I think I'm ok in this case actually. thanks for the ping!

**Comment by dkm** [comment]
I've reverted the workaround and adjusted the config to use gcc 13.3.
