### ISSUE TITLE
[BUG]: Improper column highlighting on warnings in printf

### ISSUE THREAD

**Issue by Alcaro** [compiler-explorer/compiler-explorer#5948]
### Describe the bug

Improper column highlighting on warnings in printf

### Steps to reproduce

Click repro link

### Expected behavior

![image](https://github.com/compiler-explorer/compiler-explorer/assets/5085186/e1463fd1-c5d0-428d-ae7f-362e5060c8c9)
or
![image](https://github.com/compiler-explorer/compiler-explorer/assets/5085186/130fa36b-3e16-416e-a345-9a0601701725)

Actual behavior:
![image](https://github.com/compiler-explorer/compiler-explorer/assets/5085186/7d13c6d5-4b30-4ed5-a036-7ea458f79c14)

### Reproduction link

https://godbolt.org/z/11d8YsW1n

### Screenshots

Not applicable

**Comment by partouf** [comment]
Unfortunately it's "correct", the compiler says the issue is at column 14, that's the f in %f

**Comment by Alcaro** [comment]
Underlining that single character is another possible correct answer.

Highlighting until the end of the string just looks weird.

**Comment by partouf** [comment]
Highlighting just 1 character is terrible for other error messages. We highlight the "word" if there's no information about the length of the thing, which is the case here.

For it to somewhat resemble the error, we would need to parse the extra information that compilers might give with the squiggles (which obviously not every compiler and in every situation will give and it's really hard to do taking into account various situations), and then we would need to store and use that in our API.

But other than that, sure.

**Comment by Alcaro** [comment]
~~oh don't worry, just tell everyone to use single letter variable names~~

I think a reasonably safe heuristic would be "if the error does not point to the start of a token, highlight only that single character". If that turns out too restrictive, you could highlight the entire string.

The current rule seems to be highlight to the end of the token, no matter where it starts.

**Comment by partouf** [comment]
> The current rule seems to be highlight to the end of the token, no matter where it starts.

Correct, this line is responsible for that https://github.com/compiler-explorer/compiler-explorer/blob/main/static/panes/editor.ts#L1526

**Comment by Alcaro** [comment]
That looks easy enough to edit.
```js
                        const span = this.getTokenSpan(obj.tag.line ?? 0, obj.tag.column);
                        colBegin = obj.tag.column;
                        if (span.colEnd === obj.tag.column) colEnd = -1;
                        else if (span.colBegin === obj.tag.colBegin) colEnd = span.colEnd;
                        else colEnd = obj.tag.column;
```
But I can't test it, so I'll leave the PRing to someone else.
