### ISSUE TITLE
Add the CompCert C compiler

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#595]
http://compcert.inria.fr/compcert-C.html

(Requested over email)

**Comment by Reilithion** [comment]
CompCert's current license might pose a challenge. But since the public release "can be used for evaluation, research and education purposes", I think it can be used on the site.

**Comment by andrew-appel** [comment]
Based on an e-mail I received today from the CEO of AbsInt, I am confident that if you request a no-cost CompCert license for the purpose of including it in the C Compiler Explorer, they will be willing to provide.  You can find his e-mail at https://www.absint.com/staff/cf.htm

**Comment by dkm** [comment]
@valoran-m how am I supposed to build and link with cc?
```
$ /opt/compiler-explorer/compcert/CompCert-x86_64-3.12/bin/ccomp -o /tmp/test /tmp/test.c                                                  
/usr/bin/ld: cannot find -lcompcert: No such file or directory
collect2: error: ld returned 1 exit status
ccomp: error: linker command failed with exit code 1 (use -v to see invocation)
$ /opt/compiler-explorer/compcert/CompCert-x86_64-3.12/bin/ccomp -o /tmp/test /tmp/test.c -L/opt/compiler-explorer/compcert/CompCert-x86_64-3.12/lib/compcert
/usr/bin/ld: warning: /tmp/compcert908440.o: missing .note.GNU-stack section implies executable stack
/usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
```
I guess nobody should have to add this extra `-L` by default and I must have done something wrong.

**Comment by bschommer** [comment]
> @valoran-M how am I supposed to build and link with cc?
> 
> ```
> $ /opt/compiler-explorer/compcert/CompCert-x86_64-3.12/bin/ccomp -o /tmp/test /tmp/test.c                                                  
> /usr/bin/ld: cannot find -lcompcert: No such file or directory
> collect2: error: ld returned 1 exit status
> ccomp: error: linker command failed with exit code 1 (use -v to see invocation)
> $ /opt/compiler-explorer/compcert/CompCert-x86_64-3.12/bin/ccomp -o /tmp/test /tmp/test.c -L/opt/compiler-explorer/compcert/CompCert-x86_64-3.12/lib/compcert
> /usr/bin/ld: warning: /tmp/compcert908440.o: missing .note.GNU-stack section implies executable stack
> /usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
> ```
> 
> I guess nobody should have to add this extra `-L` by default and I must have done something wrong.

The problem is that the path to the library is hard coded during configure in the generated `compcert.ini` file as: `stdlib_path=...`. You probably need to patch the path after unpacking the tarball.

**Comment by dkm** [comment]
Yes, that's what @valoran-m has found. He's working on updating the install/build script. Thanks @bschommer .

Any reason why this setting can't be made relative to the compiler proper?

**Comment by bschommer** [comment]
Since the location does not need to be always the same relative to the install location since one can configure the install location of the library separately with the `-libdir` configure option.

**Comment by dkm** [comment]
Thanks for the explanation. I would have expected the simple case to produce an easily relocatable toolchain, but that was easily fixed for our specific setup.

**Comment by dkm** [comment]
@valoran-m fyi, latest build works correctly now. I'll proceed with the config update and let you know when I have something :)

**Comment by dkm** [comment]
This is now live :rocket:
