### ISSUE TITLE
[BUG]: Boost 1.84 produces linker errors when using the boost cobalt library

### ISSUE THREAD

**Issue by arun5309** [compiler-explorer/compiler-explorer#5960]
### Describe the bug

Code using boost 1.84 compiles fine (tested with different versions of gcc and clang with standard c++20 or higher) with boost 1.84 selected but produces linker errors when 'link to binary' or 'execute the code' options are enabled. I don't think this bug is OS/browser specific but I have included information about those just for completeness sake.

### Steps to reproduce

1. Visit godbolt.org
2. Select gcc 13.2 x86-64 compiler for c++
3. Select the boost library version 1.84
4. Enable the 'Execute to code' option from the output drop down
5. Pass the compiler option '-std=c++20'
6. Paste the following code snippet in the source pane

```cpp
#include <boost/cobalt.hpp>
#include <boost/asio.hpp>
#include <chrono>

using namespace boost;

cobalt::main co_main(int argc, char * argv[]) 
{
  asio::steady_timer tim{co_await asio::this_coro::executor, 
                         std::chrono::milliseconds(5)}; 
  co_await tim.async_wait(cobalt::use_op); 
  co_return 0; 
}
```

7. Once the code has compiled and the linker has been invoked observe linker errors in the output pane

### Expected behavior

There should be no linker errors. The output pane must have result of executing the code (in this just program returned 0 and nothing printed to STDOUT).

### Reproduction link

https://godbolt.org/z/fhGME8f6Y

### Screenshots

Not applicable

### Operating System

void Linux  (Kernel version 6.6.10_1)

### Browser version

Brave Browser 1.61.114 (Flatpak) x64

**Comment by arun5309** [comment]
I built cobalt and attempted to build the above example on my machine it results in the same linker errors when GNU ld or GNU gold linkers are used but links fine and produces the desired executable when the lld or mold linkers are used.

**Comment by arun5309** [comment]
Appears to be linking order issue that affects GNU `ld` and `gold` linkers. As discussed [here](https://github.com/boostorg/cobalt/issues/152).

**Comment by partouf** [comment]
hi, we don't actually have the boost binaries, that's all it is, it doesn't have anything to do with the types of linker

**Comment by partouf** [comment]
From boost 1.85 and on we'll (try) to build binaries.
You can try it out now https://godbolt.org/z/3ox19ev1b

You do need to pass the exact lib files that you need (in this case `-lboost_cobalt`)
