### ISSUE TITLE
[BUG]: Compiling with fmt 10.2.1 does not link properly

### ISSUE THREAD

**Issue by tupaschoal** [compiler-explorer/compiler-explorer#5970]
### Describe the bug

When trying to use fmt 10.2.1 the linking fails, with the following error:

```
/opt/compiler-explorer/gcc-13.2.0/bin/../lib/gcc/x86_64-linux-gnu/13.2.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -lfmtd: No such file or directory
collect2: error: ld returned 1 exit status
```

### Steps to reproduce

1. Run [small example](https://godbolt.org/z/zsWvMja8M) on Godbolt.
2. See error described above.
3. Switch to fmt 10.1.1 and see that error goes away.

### Expected behavior

Program should link and execute properly

### Reproduction link

https://godbolt.org/z/zsWvMja8M

### Screenshots

Not applicable

### Operating System

Windows 10

### Browser version

Version 120.0.6099.131 (Official Build) (64-bit)

**Comment by partouf** [comment]
Thanks for the bugreport, it seems we have run out of diskspace on our conan instance which made it crash.
We're currently fixing it, but might be a few hours

**Comment by partouf** [comment]
The conan server is back online, but we have not built any of the fmt binaries yet because of this issue. It should build in a few hours, otherwise I'll manually try to get it done tomorrow.

**Comment by tupaschoal** [comment]
Thanks, take your time!

**Comment by partouf** [comment]
this is now fixed

**Comment by tupaschoal** [comment]
Thank you!
