### ISSUE TITLE
[BUG]: mp-units library version 2.0.0 and 2.1.0 do not compile due to missing headers

### ISSUE THREAD

**Issue by svz71195** [compiler-explorer/compiler-explorer#5975]
### Describe the bug

When trying to use mp-units library, compilation fails with the following error using various compilers:

`<source>:6:10: fatal error: mp-units/systems/si/si.h: No such file or directory
    6 | #include <mp-units/systems/si/si.h>`

### Steps to reproduce

1. Run small example on Godbolt
2. See error message

### Expected behavior

Headers should be there and compilation should not fail

### Reproduction link

https://godbolt.org/z/1sjG61ha3

### Screenshots

Not applicable

### Operating System

Ubuntu LTS 22.04

### Browser version

Firefox for Linux v.121.0.1 (64-bit)

**Comment by partouf** [comment]
It looks like the paths for both 2.0 and 2.1 are configured incorrectly https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/c%2B%2B.amazon.properties#L3910

I missed this in the review for the PR https://github.com/compiler-explorer/compiler-explorer/pull/5949

**Comment by svz71195** [comment]
Thank you for looking into it so quickly!

**Comment by partouf** [comment]
fix is now live

**Comment by svz71195** [comment]
Thank you!
