### ISSUE TITLE
[BUG]: Abseil fails to link

### ISSUE THREAD

**Issue by jpan127** [compiler-explorer/compiler-explorer#5982]
### Describe the bug

Hi I'm having a similar problem to this older issue https://github.com/compiler-explorer/compiler-explorer/issues/2512.

On `clang 10.0.1` I get `cannot find -labsl_flags`.
`clang trunk` I get some undefined references. Same with `GCC trunk`.

### Steps to reproduce

1. #include <absl/container/flat_hash_map.h>
2. Instantiate any `flat_hash_map` template. 

### Expected behavior

I expect linking to succeed.

### Reproduction link

https://godbolt.org/z/x5PKzbs67

### Screenshots

Not applicable

**Comment by FranklinYu** [comment]
https://github.com/abseil/abseil-cpp/commit/4038192a57cb75f7ee671f81a3378ff4c74c4f8e converted `absl_flags` to header-only. I suppose we simply remove it from

https://github.com/compiler-explorer/compiler-explorer/blob/07f54a67217f73da6fc99f5b1d998b795bc4d2df/etc/config/c%2B%2B.amazon.properties#L3151

right?

**Comment by partouf** [comment]
Ahh that explains it
