### ISSUE TITLE
[BUG]: Conformance viewer looks awful in pink theme

### ISSUE THREAD

**Issue by Alcaro** [compiler-explorer/compiler-explorer#5985]
### Describe the bug

Conformance viewer looks awful in pink theme

### Steps to reproduce

- Enable pink theme
- Add new - Conformance viewer

### Expected behavior

Doesn't look like it was designed by Medusa

### Reproduction link

https://godbolt.org/z/sMxWhq6nz

### Screenshots

![image](https://github.com/compiler-explorer/compiler-explorer/assets/5085186/87bef748-0d1c-40ed-b91a-1a4148e666b3)

**Comment by OfekShilon** [comment]
Do you mean the green-pink contrast is too low?   If so - that holds for the status icon and maybe elswhere.
 
@jeremy-rifkin FYI

**Comment by jeremy-rifkin** [comment]
Thanks, we have a million different colors on CE so updating everything takes a while
