### ISSUE TITLE
[LIB REQUEST] Fortran stdlib

### ISSUE THREAD

**Issue by jalvesz** [compiler-explorer/compiler-explorer#6025]
Hi, I just discovered that there is a possibility to request for libraries being available in the platform. Would it be possible to add the standard library built by the fortran-lang community for testing with Fortran compilers? https://github.com/fortran-lang/stdlib

Thanks

**Comment by gnikit** [comment]
Hi all, I suspect you would need us to publish `stdlib` to conan.io for you to be able to fetch it. Is that all that would be required on our end?

**Comment by jeremy-rifkin** [comment]
This should be possible. Option one would be to add it as a third party library which we have documented here https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/AddingALibrary.md. Another option would be to add this to the files installed as part of the compilers themselves if the library is widely used and adopted.

**Comment by partouf** [comment]
Fortran library support is not complete yet, but I will probably get it integrated at the latest next month.

The implementation is currently based on building with fpm, so if the library supports that it should be possible.

**Comment by gnikit** [comment]
@partouf Yes, the library can be built using `fpm`, it is classified as a metapackage (see our [docs](https://fpm.fortran-lang.org/spec/metapackages.html#fortran-lang-standard-library-stdlib)). FYI there is a limitation with fpm right now, we basically can only compile static libraris (no shared library support yet), would that be a problem?

**Comment by partouf** [comment]
our library support is now live, so we can start adding this the "easy way"

If someone wants to make it happen:
* Add here https://github.com/compiler-explorer/infra/blob/main/bin/yaml/libraries.yaml#L2324
* And here https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/fortran.amazon.properties#L905

**Comment by jalvesz** [comment]
Brilliant!! If I want to help out with that should I fork and PR?

**Comment by gnikit** [comment]
Hi @partouf 

This is the infra repo PR https://github.com/compiler-explorer/infra/pull/1233
This is the compilier-explorer PR https://github.com/compiler-explorer/compiler-explorer/pull/6116

I am not entirely convinced that the proposed changes in the PRs are correct.

**Comment by partouf** [comment]
this is now live

**Comment by partouf** [comment]
You're correct, it's only built for 13.2, trunk and ifx latest / ifort 2021.11.0 currently.
It will be built for the less popular compilers this sunday, I believe.
