### ISSUE TITLE
[COMPILER REQUEST]: .NET 8.0.100

### ISSUE THREAD

**Issue by colejohnson66** [compiler-explorer/compiler-explorer#6044]
### Compiler name

Roslyn (.NET)

### Compiler version

8.0.100

### Compiler language

C#

### Compiler homepage

https://dot.net

### Motivation

Current options include 6, 7, and trunk/main, but not 8.

**Comment by hez2010** [comment]
@partouf This issue has been fixed and can be closed.

**Comment by colejohnson66** [comment]
Thanks.
