### ISSUE TITLE
[REQUEST]: Light-parse on local client to defer updates on uncompilable code

### ISSUE THREAD

**Issue by sh1boot** [compiler-explorer/compiler-explorer#6045]
### Is your feature request related to a problem? Please describe

While I'm changing code it spends much of it's time in a state where it _obviously_ won't build but the compiler output starts updating anyway, and then when I'm done editing I often have to wait for the last failure to come back before it'll update again with the intdended code.

### Describe the solution you'd like

A light parse of the code on my local machine for the most basic sanity checks (eg., matching parentheses) which will increase the update delay while it's obviously not valid (but still falling through eventually in case the test is wrong).  And a minimal delay after I stop typing with code that's more likely to succeed.

### Describe alternatives you've considered

Editing externally and pasting the update into the site's editor.

### Additional context

Not applicable

**Comment by mattgodbolt** [comment]
Parsing the 50+ languages we support is not really feasible. If you need to slow down the rate of compilation, or disable "compile as source changes", consider changing the options in More->Settings and then "Compilation".

If you disable compile as you type, then you can press ctrl-enter to force a compile.
