### ISSUE TITLE
[BUG]: Failure to serialize RegExpr

### ISSUE THREAD

**Issue by CharlieJiangXXX** [compiler-explorer/compiler-explorer#6053]
### Describe the bug

Special types, such as ``RegExpr``, are not processed before getting serialized to JSON, and hence would be sent as empty dictionaries. One such example is the ``previewFilter`` field in ``Languages``.

### Steps to reproduce

1. Use a simple Python HTTP client, such as ``aiohttp``, to send a get request to ``/api/languages`` with ``Accept`` set to ``application/json``
2. Inspect the ``previewFilter`` field, which would be an empty dictionary

### Expected behavior

``previewFilter`` should be sent as specified in the source code, possibly serialized to strings before transmission.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by partouf** [comment]
I don't think this is worth supporting, it's not part of the default fields and I'm not sure what anyone would do with it

**Comment by CharlieJiangXXX** [comment]
Yeah, I understand. I'm personally attempting to create a comprehensive Python client for CE, which is why this popped up. But I do agree that this is a pretty marginal issue.
