### ISSUE TITLE
[COMPILER REQUEST]: Pythran

### ISSUE THREAD

**Issue by serge-sans-paille** [compiler-explorer/compiler-explorer#6079]
### Compiler name

Pythran

### Compiler version

0.15.0

### Compiler language

Python

### Compiler homepage

https://pypi.org/project/pythran/

### Motivation

Pythran is a Python to native code used by (at least) scipy to speedup numeric kernels written in Python. It ca n use either GCC or Clang as a backend.

Having it on compiler explorer would help for both performance exploration and bug reporting.

**Comment by serge-sans-paille** [comment]
Side note: I am the core developer of the project and the talk of @dkm at Fosdem 2024 and the discussions we had afterward are also a reason why I'm creating this issue. I'm obviously ready to provide the help / guidance to achieve the above!

**Comment by dkm** [comment]
> Side note: I am the core developer of the project and the talk of @dkm at Fosdem 2024 and the discussions we had afterward are also a reason why I'm creating this issue. I'm obviously ready to provide the help / guidance to achieve the above!

Oh, I didn't know that was for Pythran, nice. I also didn't know I was talking to a fellow DLFP ;)

**Comment by dkm** [comment]
I know absolutely nothing about Pythran, except that it's compiling to native code. What do you expect from compiler-explorer? As you're using both GCC and clang, I get you are really emitting C? So, should we display the produced C code? Or do you want to push it until the final step of using a C compiler ? We have other similar use case, like `mrustc` and we stop at the C. We don't have a mechanism for this kind of use case. But we may be able to hack something if that's really what we want. But that will require bespoke code, so probably a bit longer to do (compared to simply having a pane with C).

**Comment by serge-sans-paille** [comment]
We *could* show the intermediate C++ code, but I think that the native code would be more interesting, eventually with some filtering

**Comment by dkm** [comment]
Ok.The "best" behavior, I guess would be to treat the C as the assembler and allow for "compile to object" and "link to binary" to call the C compiler. I'll have a thought about that

**Comment by serge-sans-paille** [comment]
If that's easier for you, the assembler could also be the result of the clang++ / g++ compilation, that way it would match other native compiler behavior

**Comment by dkm** [comment]
Not quite. For common C++ compiler, the default is to get the assembler (some text) and when you select "compile to object" or "link to bin", we execute something else to get the text to display (`objdump` + something to parse its output, etc). I think it might be easier to map assembler to C++ and then craft something to compile/link. Is pythran handling everything, or do we need to call the C++ compiler? That way, we may be able to simple fit pythran in the common case. What about the backend selection? Do you want to let the user chose between GCC and clang? Or both work and we can simply pin latest gcc (or clang) in the config file?

**Comment by serge-sans-paille** [comment]
`pythran some.py` generates a shared library (`some.so`, but potentially with extra suffix, `-o` changes the default behavior)

`pythran -E some.py` generates the intermediate C++ file (`some.cpp`).

`pythran some.cpp` generates a shared library.

compiler invocation is sensible to `CXX` (among other things!)

**Comment by dkm** [comment]
Ohhh, even easier then. The only difference from the common case would be that you have either the C++ code or the linked library, but no intermediate object (at least nothing you would like to show)... Correct?

We don't provide a "default" C/C++ compiler, so we need to either package one with pythran (probably not a good option), or point to one we have installed. Is the backend is selected by CXX? There's a way to override environment variable, so as a first step we could set something in the config (e.g. latest gcc or latest clang), that a user can override (with a non trivial value... e.g. "CXX=/opt/compiler-explorer/gcc-11.1.0/bin/g++`).

**Comment by partouf** [comment]
> Ohhh, even easier then. The only difference from the common case would be that you have either the C++ code or the linked library, but no intermediate object (at least nothing you would like to show)... Correct?
> 
> We don't provide a "default" C/C++ compiler, so we need to either package one with pythran (probably not a good option), or point to one we have installed. Is the backend is selected by CXX? There's a way to override environment variable, so as a first step we could set something in the config (e.g. latest gcc or latest clang), that a user can override (with a non trivial value... e.g. "CXX=/opt/compiler-explorer/gcc-11.1.0/bin/g++`).

I would recommend perhaps re-using the Toolchain override, that has all the gcc's that can produce binaries, could later expand that with clang's

**Comment by dkm** [comment]
Ah forgot about that! Thanks @partouf !

**Comment by dkm** [comment]
@serge-sans-paille My notes while reading a bit about your Pythran.

- for a regular setup (no compile to binary nor exec), CE calls pythran with `-E` and displays the C++ code
- when "link to binary" is selected.... CE calls Pythran and objdumps the resulting `.so`
- we should probably disable "compile to binary", unless you can stop pythran before calling the linker.
- when "execute" is selected.... What are we supposed to do? It depends on the language. For C/C++, you need a `main`, for Ada you need a special top level procedure (no particular name), etc. What about Pythran? IIUC, you need to call `python -c 'import bla'` to import the module. How can we easily execute anything there automatically?

**Comment by serge-sans-paille** [comment]
My understanding matches you notes. Considering the "executing part" you're right: there's no direct way to execute something automagically as of now, but that's something we could add in pythran quite easily, let me think about it and come back to you.

**Comment by serge-sans-paille** [comment]
(and I don't think this should block us from moving forward for the other steps and just don't have any execute option)

**Comment by dkm** [comment]
The next step is to find a way to package/install the compiler in our infra. Do you know if that's something we can do with python? Like doing a pip incantation to get the closure of all deps, create an archive that we can install elsewhere (and possibly relocate it somehow if some paths need tuning).

**Comment by serge-sans-paille** [comment]
`pip install pythran` + `my-native-package-manager install gcc` should be enough

**Comment by dkm** [comment]
> `pip install pythran` + `my-native-package-manager install gcc` should be enough

The thing is, we don't run any packaging script/install anything on the runner nodes. We do that in various docker images (e.g. https://github.com/compiler-explorer/gcc-cross-builder for building the cross gcc, we have many other '*-builder' repositories), copy an archive in some s3 storage, and then install these archives using scripts from https://github.com/compiler-explorer/infra to have the compiler installed in some file system that gets mounted over the network on the node that are executing the compilers...

All that to say that `pip install` is probably not the way to go. Same applies to installing the distribution's system compiler (even less because we are executing everything inside a jail, so this `gcc` would probably not be available).

We do have lots of compilers, so getting gcc is not an issue. I simply need to learn how to package the closure of an arbitrary python program.

**Comment by serge-sans-paille** [comment]
I can only trust you on this :-) How can I help?

**Comment by dkm** [comment]
I think the ball is in my court now, we have laid out most of the needed steps. For the python package, @apmorton suggested to try unpacking the wheel package (I have yet to try, but I'm confident :p). I'll let you know when I have something you can test. Thanks!

**Comment by dkm** [comment]
@serge-sans-paille We are looking at your conda package, and were wondering about the dep on the c++ compiler. In particular, there's a comment about ABI we're not sure we fully understand:
https://github.com/conda-forge/pythran-feedstock/blob/main/recipe/meta.yaml#L45
I can't find any compiled file in the pythran install path that could explain this. Can you give more details?

**Comment by serge-sans-paille** [comment]
+1 for the absence of any compiled file in pythran install path. I am not quite sure which kind of ABI compatibility this could be, maybe with the conda-built native part of numpy or libcpython, but really I don't know.

And the original commit message is rather... terse :-) https://github.com/conda-forge/pythran-feedstock/commit/dc16a8acd6bed1a54c93379d44b234759f2c59e2

**Comment by dkm** [comment]
I've been playing a bit with conda/mamba. Funnily enough, when searchin for "conda ignore package", the first result points to https://stackoverflow.com/questions/71302220/how-to-hack-conda-for-anaconda3-python-to-ignore-package-dependencies-modified .. which seems to work. I've been able to stub most of the gcc dep. It's still installing several packages that should probably not be there in our case, like libstdc++, libgcc, etc. Making some progress :)

**Comment by dkm** [comment]
Making some (slow, sorry) progress....
![image](https://github.com/compiler-explorer/compiler-explorer/assets/87603/c3f96742-ede1-4404-98f7-c3376ffb87e6)

**Comment by serge-sans-paille** [comment]
Nice :-) Seeing the guts of the generated code is always a bit frightening, event to me ^^!

**Comment by dkm** [comment]
@serge-sans-paille do you have a logo or something that we could freely use in the dropdown menu?

**Comment by serge-sans-paille** [comment]
https://github.com/serge-sans-paille/pythran/blob/master/logo.svg

**Comment by dkm** [comment]
First successful build: https://github.com/compiler-explorer/infra/actions/runs/8040098089/job/21957808042
I'll proceed with the infra change needed to install the compiler.

**Comment by partouf** [comment]
this is now live thanks to @dkm :tada:
