### ISSUE TITLE
[BUG]: bytecode lines missing when using `switch` with negative numbers in java

### ISSUE THREAD

**Issue by fbarbari** [compiler-explorer/compiler-explorer#6091]
### Describe the bug

When writing a simple java's switch expression (like [this one](https://godbolt.org/z/G5757xMnY)) the output should be a `tableswitch` bytecode instruction with a bunch of `goto`-ended sections afterwards.
When adding negative numbers in the switch expression (like in [this example](https://godbolt.org/z/bhG6KEYrr) or in [this one](https://godbolt.org/z/G6azsz7nf)), anything after the `tableswitch` bytecode instruction is missing.

### Steps to reproduce

1. Visit godbolt.org
2. Select Java
3. Select jdk >= 14.0.2
4. Write a `switch` expression in which one of the `case` clauses includes a negative number

### Expected behavior

The `switch` expression should be entirely visible like in [this example](https://godbolt.org/z/G5757xMnY).

### Reproduction link

https://godbolt.org/z/bhG6KEYrr

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
Thanks for reporting this! We will update here when the fix is deployed to the live site.
