### ISSUE TITLE
Use special version of the binutils for the cross-BPF gcc

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#6110]
Use a patched binutils that offers BTF (https://jemarch.net/binutils-btf/ ) support for the cross-BPF compiler.

Patches are avail: https://jemarch.net/binutils-btf/

**Comment by dkm** [comment]
@jemarch, any update on this?

**Comment by jemarch** [comment]
Sorry, no updates yet re. putting these patches upstream.

**Comment by dkm** [comment]
But do you want us to have this build of binutils  with the GCC cross BPF compiler?

**Comment by jemarch** [comment]
> But do you want us to have this build of binutils with the GCC cross
> BPF compiler?

I guess it wouldn't hurt to have it supported in compiler-explorer, as a
temporary clutch.  If at some point objdump switches to use libctf for
dumping BTF then the hack can be removed.

Thanks!

**Comment by dkm** [comment]
Any chance you have a public git repository with above patches applied or a tarball @jemarch ?

**Comment by dkm** [comment]
Next nightly should use a patch binutils. As I have no idea about the change, I've applied it over a binutils from Nov 2023. Let me know if I need to use a different base version.
