### ISSUE TITLE
assembly instruction descriptions for RISCV

### ISSUE THREAD

**Issue by mkflan** [compiler-explorer/compiler-explorer#6112]
I was using Compiler Explorer to view some RISCV assembly. I realized that I could not get descriptions of instruction mnemonics by hovering over the mnemonic like when viewing x86 assembly. Is this planned and going to be implemented in the future?

**Comment by dkm** [comment]
You mean, like this one ? https://github.com/compiler-explorer/compiler-explorer/pull/5121 :D

**Comment by dkm** [comment]
Closing, as it's a dup :)

**Comment by mkflan** [comment]
> You mean, like this one ? #5121 :D

yeah, that's great thanks
