### ISSUE TITLE
[BUG]: The order of registers seems to be reversed.

### ISSUE THREAD

**Issue by gouyt13** [compiler-explorer/compiler-explorer#6144]
### Describe the bug

![1707987887470](https://github.com/compiler-explorer/compiler-explorer/assets/65775090/424ba1e3-d15f-4a70-8158-61edf6746713)
I tested several versions of clang for c and c++.

### Steps to reproduce

1. Visit https://godbolt.org/
2. Try the simple program showed in the picture.

### Expected behavior

The order of the registers should be 
mov 	%edi, %eax

### Reproduction link

Not applicable

### Screenshots

Not applicable
![1707987887470](https://github.com/compiler-explorer/compiler-explorer/assets/65775090/c294bc67-a12a-4481-a6da-a0af4386f133)

### Browser version

Google Chrome Version 121.0.6167.160 (Official Build) (x86_64)

**Comment by partouf** [comment]
To get the order you want you will need to uncheck the Intel setting here:
![image](https://github.com/compiler-explorer/compiler-explorer/assets/442630/c2d68f54-45e5-464e-9ca2-dc4d540bcaf3)

By default we use the Intel notation because that's more readable and what most people tend to use.
