### ISSUE TITLE
[BUG]:  Blank page except for header

### ISSUE THREAD

**Issue by jaggedblades** [compiler-explorer/compiler-explorer#6150]
### Describe the bug

All i get is a blank page and the header, the header buttons don't work. 
Inspecting the page it says there's a syntax error.
This is on a HP Chromebook 14 G4, which is EOL.

### Steps to reproduce

visit https://godbolt.org/

### Expected behavior

The editor loads, and header buttons work. 

### Reproduction link

https://godbolt.org/

### Screenshots

![Screenshot 2024-02-15 5 48 36 PM](https://github.com/compiler-explorer/compiler-explorer/assets/143829582/a759ae23-6e0d-4a0f-bdc9-661c04a34cc6)
Uncaught SyntaxError:
![Screenshot 2024-02-15 5 54 20 PM](https://github.com/compiler-explorer/compiler-explorer/assets/143829582/abaf7091-fcfa-400d-9869-f5182d464506)

### Operating System

Google Chrome OS

### Browser version

Google Chrome Version 93.0.4577.107 (Official Build) (64-bit)

**Comment by mattgodbolt** [comment]
This looks like a compatibility issue in our dependent monaco (the vendor.js thing). We _may_ be able to transpile it, but it's hard to know what we need to target to fix the issue.

**Comment by mattgodbolt** [comment]
Presumably it being EOL means you can't update Chrome to a newer version?

**Comment by jaggedblades** [comment]
yes, unfortunately.

**Comment by wztvm** [comment]
Some extra data points:
- The same issue (blank page, header, buttons don't work, same console message) reproduce in `Safari Version 15.6.1 (15613.3.9.1.16, 15613)` on `MacBook Air (13-inch, Mid 2012)` running `Catalina version:10.15.7`.  
- However `Firefox 117.0 (64-bit)` on the same laptop works fine.

**Comment by mattgodbolt** [comment]
Thanks. Some upstream packages we use have apparently broken with older browsers. We're looking at what we can do, short of not upgrading packages (which of course has its own problems)

**Comment by jaggedblades** [comment]
Any plans to fix?

**Comment by mattgodbolt** [comment]
No, I'm sorry. We don't have the time to look in to this and it may be a fool's errand given our fundamental editor library (Monaco) uses these features.

One (bad) alternative is to hit our noscript version: https://compiler-explorer.com/noscript

**Comment by jaggedblades** [comment]
Ok, thanks.
