### ISSUE TITLE
[REQUEST]: Does online ide perform online debugging function? It is C++  breakpoint debugging.

### ISSUE THREAD

**Issue by Tiang-88** [compiler-explorer/compiler-explorer#6158]
### Is your feature request related to a problem? Please describe

Does online ide perform online debugging function? It is C++  breakpoint debugging.

### Describe the solution you'd like

1

### Describe alternatives you've considered

1

### Additional context

Not applicable

**Comment by partouf** [comment]
No, this is not possible

**Comment by jeremy-rifkin** [comment]
@Tiang-88 It would be really nice to be able to offer debugging. Some day maybe we can offer that. But at the moment the way we do execution and complication does not lend itself to such a thing. Our API is entirely RESTful and we'd have to completely rework how execution is done. Not to mention that implementing the debugger frontend would be a fair bit of work :)
