### ISSUE TITLE
[BUG]: arm64 msvc points to the wrong documentation (it points to x64 documentation)

### ISSUE THREAD

**Issue by Haiderahandali** [compiler-explorer/compiler-explorer#6189]
### Describe the bug

The `view assembly documentation` feature in arm64 with msvc points to x64 instead of arm64, and thus can not actually return the documentation. For example for the `b` instruction it returns:
> There was an error fetching the documentation for this opcode (Error: Unknown opcode 'B').
as seen here:
https://godbolt.org/z/894YxGo6T

### Steps to reproduce

It is available in the godbolt link

### Expected behavior

To actually mention it is a branch instruction

### Reproduction link

https://godbolt.org/z/894YxGo6T

### Screenshots

Not applicable

### Operating System

MSVC arm64

### Browser version

brave v1.63.162

**Comment by jeremy-rifkin** [comment]
Confirmed on our new hosting of msvc compilers

**Comment by jeremy-rifkin** [comment]
Dup of #4788
