### ISSUE TITLE
.NET: Document the available compiler options

### ISSUE THREAD

**Issue by hez2010** [compiler-explorer/compiler-explorer#6199]
The dotnet support for compiler-explorer provides lots of options to be used by the compiler, we should document them somewhere so that people won't get confused like #6180 and #6181.

We have two modes for compilation: JIT and AOT, where JIT is the default mode, while AOT mode need to be enabled by using either switch of followings:

- `--crossgen2`: use the crossgen2 compiler for a ReadyToRun image
- `--aot`: use the ilc compiler for a NativeAOT image (not working now)

For JIT mode, we support options:
- `-e Name=Value`, `--env Name=Value`: passing coreclr flags by environment variables to the compiler
- `-p Name=Value`, `--property Name=Value`: passing properties to coreclr

For AOT mode, we support options:
- `-e Name=Value`, `--env Name=Value`: passing coreclr flags by environment variables to the compiler
- `--targetos OS`: target operating system, eg. `--targetos windows`
- `--targetarch Arch`: target architecture, eg. `--targetarch arm64`
- `--instruction-set Ins...`: available instruction set, eg. `--instruction-set base,sse4.2,avx,avx2,fma,popcnt`, `--instruction-set skylake` or `--instruction-set x86-x64`
- `--singlemethodtypename Name`: single method compilation: name of the owning type
- `--singlemethodname Name`: single method compilation: method name
- `--singlemethodindex Index`: single method compilation: index of method if there are multiple with the same name
- `--singlemethodgenericarg Args...`: single method compilation: generic arguments to the method
- `--codegenopt Name=Value`, `--codegen-options Name-Value`: passing codegen options to the compiler
- `--maxgenericcycle Number`: number of nested occurrences of a potentially cyclic generic type to cut off, eg. `--maxgenericcycle 4`
- `--maxgenericcyclebreadth Number`: total number of occurrences of potentially cyclic generic types within a generic type to cut off, eg. `--maxgenericcyclebreadth 2`
- `--max-vectort-bitwidth Width`: the maximum width, in bits, for `System.Numerics.Vector<T>`, eg. `--max-vectort-bitwidth 256`

and switches:
- `-O`, `--optimize`: optimize code, enabled by default
- `-Od`, `--optimize-disabled`: disable optimization
- `-Os`, `--optimize-space`: optimize for size
- `-Ot`, `--optimize-time`: optimize for speed
- `--enable-generic-cycle-detection`: enable recursive generic cycle detection
- `--inputbubble`: form all assemblies a version bubble instead of per-assembly
- `--compilebubblegenerics`: compile instantiations from reference modules used in the code

Also note that code will be compiled as a library instead of an executable if `Link to binary` is not checked.

**Comment by partouf** [comment]
I would first suggest to put this is a custom `--help` implementation, it's generally where one would get that information. You could also then maintain that along with the code.
Later you could put some things in a `doc`

**Comment by MichalPetryka** [comment]
> We have two modes for compilation: JIT and AOT, where JIT is the default mode, while AOT mode need to be enabled by using either switch of followings:
> 
> * `--crossgen2`: use the crossgen2 compiler for a ReadyToRun image
> * `--aot`: use the ilc compiler for a NativeAOT image (not working now)

I think those should be exposed as separate compiler options instead, just like #5668 and #5669 would be.

**Comment by hez2010** [comment]
> I think those should be exposed as separate compiler options instead, just like #5668 and #5669 would be.

Sounds reasonable but it would require building separate images for a same dotnet version.

**Comment by hez2010** [comment]
The options documented here are outdated. Closing.
I'm planning to allow passing `--help` to the compiler.
