### ISSUE TITLE
[REQUEST]: Move the Executors horizontal scrollbar to the enclosing frame

### ISSUE THREAD

**Issue by TedLyngmo** [compiler-explorer/compiler-explorer#6210]
### Is your feature request related to a problem? Please describe

I'm always frustrated when a very wide error message requires me to scroll sideways, because the horizontal scrollbar is not visible when the output is thousands of lines long.

### Describe the solution you'd like

I'd like for the Executors horizontal scrollbar to always be available even when I haven't used the vertical scrollbar to scroll all the way down to the end of the output window. It (visually) looks like moving the horizontal scrollbar to the same frame where the vertical scrollbar resides could work.

### Describe alternatives you've considered

-

### Additional context

Not applicable

**Comment by jeremy-rifkin** [comment]
I think this sounds reasonable to me, it's more in-line with how other panes behave.
