### ISSUE TITLE
[LIB REQUEST]: Add nix Rust crate

### ISSUE THREAD

**Issue by canova** [compiler-explorer/compiler-explorer#6212]
### Library name

nix

### Library description

 Rust friendly bindings to *nix APIs.

### Library repository

https://crates.io/crates/nix

### Motivation

It provides a very easy way of using *nix APIs. It's a safe alternative to the unsafe APIs exposed by the libc crate. It's the 101th crate at the moment in crates.io, I guess that's why it missed the top 100 by one. 

Example simple snippet for testing:
```rust
use nix;

fn main() {
    println!("tid: {}", nix::unistd::gettid());
}
```

**Comment by OfekShilon** [comment]
We'd welcome a PR for this! Today we rely almost entirely on contributions for compiler/library requests, and (we hope) the contribution process isn't very painful.
[Docs](https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/AddingALibrary.md), example PR: https://github.com/compiler-explorer/compiler-explorer/pull/6253,https://github.com/compiler-explorer/infra/pull/1253. We'll also be happy to try and help in our [discord](https://discord.gg/r9XASD3q).

**Comment by canova** [comment]
Sure, I wanted to contribute sooner but couldn't get a chance. I will send a PR soon.
