### ISSUE TITLE
[BUG]: 'Detailed compiler flags' causes 'Add a new pane' dropdown to open 

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#6225]
### Describe the bug

See repro and screenshots.

### Steps to reproduce

1. Click 'More / Reset code and UI' (just to be sure)
2. Click the compiler options right dropdown and select 'Detailed compiler flags'
3. Observe the unrelated 'Add pane' dropdown opens at seemingly random location.  Sometimes it even covers the dropdown button that is required to close it...

### Expected behavior

No unrelated UI changes, when opening detailed compiler flags.

### Reproduction link

Not applicable

### Screenshots

(1)
![image](https://github.com/compiler-explorer/compiler-explorer/assets/73080/e336617f-c00c-4b9e-9745-95d585d27d1b)
(2)
![image](https://github.com/compiler-explorer/compiler-explorer/assets/73080/aed94c79-c994-47f2-b852-f6d7eaf8d1e2)

**Comment by OfekShilon** [comment]
Not sure whether related or a different bug, but when opening 'Detailed compiler flags' a duplicate 'close' icon appears. It's missing a hover text but closes the detailed-flags pane, same as its proper close button.
![image](https://github.com/compiler-explorer/compiler-explorer/assets/73080/d1dd62a7-1d61-49c4-b030-08ac57da5240)

**Comment by OfekShilon** [comment]
Oh dear (1): This happens when I 'click' "Detailed compiler flags" by tapping my laptop's pad. Or - when I click with a regular mouse button but leave it pressed for a while.

Oh dear (2): This looks intentional! 
https://github.com/compiler-explorer/compiler-explorer/blob/10c6074073c307ae0ac4bf9aa893188ef602ae0e/static/panes/compiler.ts#L730C1-L735C67

Why would such a behavior coded?  I'd really like to delete all occurences of `._dragListener.on('dragStart', togglePannerAdder)` in compiler.ts.

**Comment by jeremy-rifkin** [comment]
If you remove the togglePaneAdder, does anything break with the behavior we want of being able to open a detailed compiler options window and drag it to where it should go.

**Comment by jeremy-rifkin** [comment]
Ah I see. The toggle is misleading, it’s just meant to close the add new dropdown, but in this case the drag source doesn’t start at the add new dropdown so the dropdown to the right of the options should instead be closed.

**Comment by OfekShilon** [comment]
> Ah I see. The toggle is misleading, it’s just meant to close the add new dropdown, but in this case the drag source doesn’t start at the add new dropdown so the dropdown to the right of the options should instead be closed.

Oh I see, thanks. I'll submit a fix then. Maybe it's also safer to close instead of toggle everywhere.
