### ISSUE TITLE
[BUG]: [Vim mode] Last letter not selected in Visual mode

### ISSUE THREAD

**Issue by YanzhaoW** [compiler-explorer/compiler-explorer#6230]
### Describe the bug

Last letter is not selected in the visual mode. For example, to select a word "include" in visual mode, if the cursor is moved from 'i' to 'e' (cursor position is at 'e') and press `y` and `p` to copy and paste. Then only "includ" is pasted.

A similar bug also exists when navigate in Visual mode. For example, in Visual mode, if the cursor position is at 'i' of the word "include", press `e` moves the cursor position not at 'e' at the end of the word, but rather at the blank space after 'e', like "include_" ('_' is the cursor position).

### Steps to reproduce

 1. Visit compiler explorer and open the Vim mode
 2. Press `v` to enter visual mode and select a word from its first letter to the last letter using `l` for the navigation.
 3. Press `y` to copy and press `p` to paste
 4. Last letter of the word is not copied.

### Expected behavior

1. Last word of a letter should be also selected in the visual mode.
2. Press `e` should also jump the last letter of a word in the visual mode.

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

MacOS 14.3.1

### Browser version

Safari 17.3.1

**Comment by mattgodbolt** [comment]
This seems to be an issue in the vim mode we use: brijeshb42/monaco-vim#114  - thanks for noting this; we will follow up on that project.
