### ISSUE TITLE
[REQUEST]: Add bloaty tool to compiler-explorer

### ISSUE THREAD

**Issue by andre-rosa** [compiler-explorer/compiler-explorer#6240]
### Is your feature request related to a problem? Please describe

I would like to quickly evaluate the sizes of different sections and symbols of a binary.
Bloaty creates a map of the binary where every byte has a label attached to it. It's great to find out more about relocations, static memory usage, and the overall size of the compiled code.

### Describe the solution you'd like

It would be nice to have bloaty as a newly available tool in compiler-explorer:
  - https://github.com/google/bloaty

### Describe alternatives you've considered

Using `readelf` and other utilities is not as simple as using `bloaty`. The bloaty diff feature is especially nice to have. It would be great if there was a way to compile two binary outputs out from two differently modified sources and compare them both using bloaty as in: `bloaty new_binary -- old_binary`, highlighting the differences in the generated binaries from the modifications of the sources.

### Additional context

Bloaty:
- User documentation: https://github.com/google/bloaty/blob/main/doc/using.md
- How it works: https://github.com/google/bloaty/blob/main/doc/how-bloaty-works.md

**Comment by detjonmataj** [comment]
Submitted PR #6790
