### ISSUE TITLE
[BUG]: Library support for Rust broke down.

### ISSUE THREAD

**Issue by TDecking** [compiler-explorer/compiler-explorer#6250]
### Describe the bug

As of now, the library functionality for Rust no longer works, see the link for an example.

### Steps to reproduce

0. Go to godbolt.org
1. Select Rust as a language.
2. Add any library.
3. Try to import the selected library.

### Expected behavior

I expected zero errors.

### Reproduction link

https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:rust,selection:(endColumn:1,endLineNumber:4,positionColumn:1,positionLineNumber:4,selectionStartColumn:1,selectionStartLineNumber:4,startColumn:1,startLineNumber:4),source:'//extern+crate+anyhow%3B%0A%0Ause+anyhow::*%3B%0A'),l:'5',n:'0',o:'Rust+source+%231',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:r1760,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:rust,libs:!((name:anyhow,ver:'1057')),options:'-O',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+rustc+1.76.0+(Editor+%231)',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'rustc+1.76.0',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+rustc+1.76.0+(Compiler+%231)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

### Screenshots

![grafik](https://github.com/compiler-explorer/compiler-explorer/assets/15847799/05a96217-ab04-4a12-93c7-1520805fd6d6)
![grafik](https://github.com/compiler-explorer/compiler-explorer/assets/15847799/aeed135b-5355-4e97-8ba1-a758f6075909)

**Comment by mattgodbolt** [comment]
Forgive my naive question: is the expectation that you shouldn't need the `extern crate` ?

**Comment by TDecking** [comment]
For newer versions yes. IIRC it _was_ a requirement in Rust 2015 that got dropped in Rust 2018. It is certainly not a requirement when running code on the Rust playground.

Incidentally, this issue seems to be toolchain dependent. I do get an error when using Rust nightly, even if `extern crate` is used.
![grafik](https://github.com/compiler-explorer/compiler-explorer/assets/15847799/7d1521a2-58fd-4f2a-b9c6-06632721c4b4)

However, going back to stable Rust ensures successful compilation.
![grafik](https://github.com/compiler-explorer/compiler-explorer/assets/15847799/c0c47559-596b-4381-a279-d344bc8ae001)

**Comment by partouf** [comment]
> Incidentally, this issue seems to be toolchain dependent. I do get an error when using Rust nightly, even if `extern crate` is used. ![grafik](https://private-user-images.githubusercontent.com/15847799/313430568-7d1521a2-58fd-4f2a-b9c6-06632721c4b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MjMzNjEsIm5iZiI6MTcxMDYyMzA2MSwicGF0aCI6Ii8xNTg0Nzc5OS8zMTM0MzA1NjgtN2QxNTIxYTItNThmZC00ZjJhLWI5YzYtMDY2MzI3MjFjNGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDIxMDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZDRmODY2MTBkYTI4MzY2ZGNiNzQyMzU5OTA0MzU0ZjkyNjZiOWRiOTQ5NTNiODcwNGFiMjU5MDRlYzE2MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nfJr1UK-UkpZDNtX1WQcDbZ0E9r9lgPL79B9Avgv9Ek)
> 

We're not building libraries for Rust Nightly just yet, so that's expected. Here's the issue for that https://github.com/compiler-explorer/compiler-explorer/issues/3766

**Comment by TDecking** [comment]
Thanks for the info.
If nightly libraries are not (yet) supported, is it possible to add this information somewhere? Like a tooltip over the libraries button?

Provided that there are no objections, I will be closing this issue then.
