### ISSUE TITLE
[BUG]: Linker attempting to access an inaccessable file on msvc

### ISSUE THREAD

**Issue by Rinzii** [compiler-explorer/compiler-explorer#6274]
### Describe the bug

When using x64 MSVC on any version the following error message is outputted with the following code:

Code providing error:
```cpp
#include <cmath>

int main()
{
    double temp = std::exp(128.0);
}
```

Error message:

```
example.cpp
LINK : fatal error LNK1181: cannot open input file 'C:\Users\ContainerAdministrator\AppData\Local\Temp\compiler-explorer-compiler2024223-3204-xsppgp.htgl\output.s.obj'
Compiler returned: 2
```

It appears this issue only effects the x64 version of msvc and is specifically effecting `<cmath>`

### Steps to reproduce

1. Visit godbolt.org
2. Enter problem code provided in issue
3. Select x64 msvc-latest
4. View output pane

### Expected behavior

Assembly output should be provided with no linker error.

### Reproduction link

https://godbolt.org/z/G9Yn3qhe7

### Screenshots

Not applicable

### Operating System

Arch Linux

### Browser version

Firefox 124.0.1 (64-bit)

**Comment by partouf** [comment]
Similar to https://github.com/compiler-explorer/compiler-explorer/issues/4953
Sometimes it does work, sometimes it doesn't

**Comment by Rinzii** [comment]
Tried the issue again and this time its a completely random selection of variations of compiler versions for MSVC. Quite strange of an issue. Any clue on timeline for when this may be researched further into the cause of the problem?

**Comment by partouf** [comment]
> Tried the issue again and this time its a completely random selection of variations of compiler versions for MSVC. Quite strange of an issue. Any clue on timeline for when this may be researched further into the cause of the problem?

Not any time soon. Maybe this year, maybe later.

**Comment by jeremy-rifkin** [comment]
This no longer reproduces with our hosting of msvc compilers, I think this is safe to close
