### ISSUE TITLE
[BUG]: Assembly output does not work for Rust 1.75 and higher

### ISSUE THREAD

**Issue by stepantubanov** [compiler-explorer/compiler-explorer#6288]
### Describe the bug

Assembly not shown when `-O` option is used. Problem started with Rust 1.75.0.

### Steps to reproduce

1. visit godbolt.org
2. paste

```rust
pub fn basic_function(a: f64, b: f64) -> f64 {
    a * b
}
```

3. add "rustc 1.75.0" compiler output
4. specify "-O" compiler option
5. get "<No assembly to display (~6 lines filtered)>" instead of actual assembly

### Expected behavior

Switching to rust 1.74.0 correctly shows this assembly:
```
example::basic_function:
        mulsd   xmm0, xmm1
        ret
```

### Reproduction link

https://godbolt.org/z/1c9j8YEch

### Screenshots

Not applicable

**Comment by partouf** [comment]
In the default example you can read the reason for this:

```
// As of Rust 1.75, small functions are automatically
// marked as `#[inline]` so they will not show up in
// the output when compiling with optimisations. Use
// `#[no_mangle]` or `#[inline(never)]` to work around
// this issue.
// See https://github.com/compiler-explorer/compiler-explorer/issues/5939
#[no_mangle]
pub fn square(num: i32) -> i32 {
    num * num
}
```

There's not much else that we can do
