### ISSUE TITLE
[COMPILER REQUEST]: update Java toolchain

### ISSUE THREAD

**Issue by fbarbari** [compiler-explorer/compiler-explorer#6289]
### Compiler name

OpenJDK

### Compiler version

22

### Compiler language

Java

### Compiler homepage

https://openjdk.org/projects/jdk/22/

### Motivation

The main request is about adding the latest JDK version (22), however I wanted to ask about the possibility of adding some more OpenJDK compilers:
 - the ones older than JDK 11, or at least the LTS JDK 8
 - the latest version for the LTS ones like 21.0.1 and 17.0.2

**Comment by mattgodbolt** [comment]
If it's a fairly simple "it installs the same as the other compilers" you might want to consider submitting a couple PRs yourself: https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/AddingACompiler.md has the overall idea and https://github.com/compiler-explorer/infra/pull/1094 shows the infra PR (with a link to CE PR too)

**Comment by fbarbari** [comment]
Thank you very much for the pointers, would you prefer a single PR for everything or one for each compiler?

**Comment by junlarsen** [comment]
Hi, one PR for all of them should be fine :)
