### ISSUE TITLE
[BUG]:RISC-V (32-bits) gcc 12.2.0 license is wrong

### ISSUE THREAD

**Issue by Jimmynycu** [compiler-explorer/compiler-explorer#6292]
### Describe the bug

Compile result use '<' which cause this error 
```
  sudoku_2x2_asm.S:45: Error: invalid operands (*ABS* and .text sections) for `<'
  sudoku_2x2_asm.S:58: Error: invalid operands (*ABS* and .text sections) for `<'
  sudoku_2x2_asm.S:60: Error: invalid operands (*ABS* and .text sections) for `<'
  sudoku_2x2_asm.S:66: Error: invalid operands (*ABS* and .text sections) for `<'
  sudoku_2x2_asm.S:86: Error: invalid operands (*ABS* and .text sections) for `<'
  sudoku_2x2_asm.S:95: Error: invalid operands (*ABS* and .text sections) for `<'
  sudoku_2x2_asm.S:98: Error: invalid operands (*ABS* and .text sections) for `<'
  sudoku_2x2_asm.S:101: Error: invalid operands (*ABS* and .text sections) for `<'
  sudoku_2x2_asm.S:104: Error: invalid operands (*ABS* and .text sections) for `<'
  sudoku_2x2_asm.S:117: Error: invalid operands (*ABS* and .text sections) for `<'
  sudoku_2x2_asm.S:119: Error: invalid operands (*ABS* and .text sections) for `<'
  sudoku_2x2_asm.S:133: Error: invalid operands (*ABS* and .text sections) for `<'
```

### Steps to reproduce

1. I am trying to match result with c code and assembly
2. My commnad : 
 ```riscv64-unknown-elf-gcc -march=rv32im -mabi=ilp32 -nostartfiles -Tvirt.lds boot.S main.c sudoku_2x2_c.c sudoku_2x2_asm.S -o sudoku```

### Expected behavior

To be compilable

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
It isn't clear what you're trying to do. Can you please share a link to a compiler-explorer page demonstrating the problem?
![image](https://github.com/compiler-explorer/compiler-explorer/assets/73080/b43ae197-f809-4d43-a486-f3821dedfd10)

**Comment by dkm** [comment]
I think we can close this one. @Jimmynycu do not hesitate to provide us with more info, so that we can better understand the issue.
