### ISSUE TITLE
[BUG]: string view bug

### ISSUE THREAD

**Issue by sibi-venti** [compiler-explorer/compiler-explorer#6294]
### Describe the bug

It printing extra character
![image](https://github.com/compiler-explorer/compiler-explorer/assets/85477641/d06c298c-3711-4de5-afe4-e13556dfbf3b)
character

### Steps to reproduce

https://godbolt.org/z/cP1qb8eqs

### Expected behavior

```
Printing std::string: Hello, World!
Printing std::string_view: Hello, World!
Modified std::string: Hello, World! Welcome!
Modified std::string_view:  orld!
```

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by partouf** [comment]
You modified the original source of my_string_view, this behavior is not very surprising.

https://en.cppreference.com/w/cpp/string/basic_string_view

("For a basic_string_view str, pointers, iterators, and references to elements of str are invalidated when an operation invalidates a pointer in the range [str.data(), str.data() + str.size()).")

This is not a bug
