### ISSUE TITLE
[BUG]: llvm-dwarfdump is broken

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#6315]
### Describe the bug

Activating the tool gives:
```
llvm-dwarfdump (trunk) requires an executable or binary object
```

### Steps to reproduce

1. Select any clang compiler 
2. In the compiler pane 'Add tool'/'llvm-dwarfdump
3. The pane that opens contains only the output "llvm-dwarfdump (trunk) requires an executable or binary object"

### Expected behavior

Dwarf-dump visible.

### Reproduction link

https://godbolt.org/z/PxEe9948h

### Screenshots

Not applicable

**Comment by 167rgc911** [comment]
I'm relatively new to CE, and have a local instance running.

What I do:

- Edit code
- Open a "Compiler"
- In the "Compiler", I select the gear button. Select "Link to binary" or "Compile to binary object".
- Select screwdriver, and select "llvm-dwarfdump".

This gives me an output in the 'llvm-dwarfdump' pane.

**Comment by OfekShilon** [comment]
> I'm relatively new to CE, and have a local instance running.
> 
> What I do:
> 
> * Edit code
> * Open a "Compiler"
> * In the "Compiler", I select the gear button. Select "Link to binary" or "Compile to binary object".
> * Select screwdriver, and select "llvm-dwarfdump".
> 
> This gives me an output in the 'llvm-dwarfdump' pane.

You're right of coursed, I think I was slightly intoxicated when opening this :(
Closing now.
