### ISSUE TITLE
[BUG]: On iPhones Real Dark mode blocks user input

### ISSUE THREAD

**Issue by aDifferentJT** [compiler-explorer/compiler-explorer#6317]
### Describe the bug

Once Real Dark is enabled on an iPhone user input is blocked making it difficult to change back, I had to go into Safari settings and delete the website data.

### Steps to reproduce

Change to Real Dark on iOS Safari

### Expected behavior

The UI should still be functional, if hard to see

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

iOS 17.3.1

**Comment by partouf** [comment]
This should no longer be the case, as real-dark has now been forcefully disabled if it was on before.
