### ISSUE TITLE
[BUG]: Not all identifiers are demangled

### ISSUE THREAD

**Issue by narpfel** [compiler-explorer/compiler-explorer#6348]
### Describe the bug

Some identifiers are not demangled, for example
```asm
        jmp     qword ptr [rip + _ZN4core3fmt3num3imp54_$LT$impl$u20$core..fmt..Display$u20$for$u20$usize$GT$3fmt17h7bbbd896a38dcccaE@GOTPCREL]
        mov     edx, OFFSET FLAT:_ZN1a1gEi
```

### Steps to reproduce

Write some code that (for example) is compiled to a `rip`-relative jump: https://godbolt.org/z/5zWGxhxKq

### Expected behavior

The identifiers should be demangled.

I believe these regexes are too restrictive?
https://github.com/compiler-explorer/compiler-explorer/blob/a47d3c68fc98b5c3a17298aa121e13665bb7245a/lib/demangler/base.ts#L47
https://github.com/compiler-explorer/compiler-explorer/blob/a47d3c68fc98b5c3a17298aa121e13665bb7245a/lib/demangler/base.ts#L55

### Reproduction link

https://godbolt.org/z/5zWGxhxKq

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
Confirmed

**Comment by jeremy-rifkin** [comment]
Oddly locally `_ZN1a1gEi` demangles fine with g++ 11 but not with g++ 12
