### ISSUE TITLE
[BUG]: Missing gcc arm demangler

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#6383]
### Describe the bug

```
Error executing demangler /opt/compiler-explorer/gcc-arm-unknown-13.2.0/arm-unknown-eabi/bin/arm-unknown-eabi-c++filt 
{
  "code": 255,
  "execTime": "41",
  "okToCache": true,
  "stderr": "[F][2024-04-22T23:01:35+0000][1] runChild():487 Launching child process failed\n",
  "stdout": "",
  "timedOut": false,
  "truncated": false
}
```

### Steps to reproduce

-

### Expected behavior

-

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
Oh, that's probably me in PR [#6080](https://github.com/compiler-explorer/compiler-explorer/pull/6080).  
Can you please share a repro link?  Naive code demangles fine: https://godbolt.org/z/7rGYE45n3

**Comment by partouf** [comment]
I don't really know, I just happened to see it accidentally in papertrail

**Comment by dkm** [comment]
> Oh, that's probably me in PR [#6080](https://github.com/compiler-explorer/compiler-explorer/pull/6080). Can you please share a repro link? Naive code demangles fine: https://godbolt.org/z/7rGYE45n3

Because it's the arm-elf that is failing, not arm-linux, see https://godbolt.org/z/7rKvo6oMP

**Comment by dkm** [comment]
Yes, paths are wrong. Let me fix that.

**Comment by partouf** [comment]
thanks!
