### ISSUE TITLE
`UseDynamicNumberOfCompilerThreads` command-line option not present in java <11

### ISSUE THREAD

**Issue by fbarbari** [compiler-explorer/compiler-explorer#6388]
As stated in the title, the command-line option `UseDynamicNumberOfCompilerThreads` was added in java 11 and AFAIK there is no equivalent in older java releases, so I think it should be removed.

Happens with [java 8](https://godbolt.org/z/xdMcWe8qG), [java 9](https://godbolt.org/z/3YK8j7nWq) and [java 10](https://godbolt.org/z/Ea69x39Yd).

**Comment by partouf** [comment]
Referring to https://github.com/compiler-explorer/compiler-explorer/blob/1646eed4e7235d86792b35a60a8f896968a4417b/lib/compilers/java.ts#L138

Could make use of reading and comparing the version like done here https://github.com/compiler-explorer/compiler-explorer/blob/1646eed4e7235d86792b35a60a8f896968a4417b/lib/compilers/zig.ts#L65

**Comment by fbarbari** [comment]
Opened #6397.
