### ISSUE TITLE
[BUG]: debug labels are not hidden on GCC MIPS and LoongArch

### ISSUE THREAD

**Issue by jf2048** [compiler-explorer/compiler-explorer#6392]
### Describe the bug

When using gcc mips, gcc mips64, or gcc loongarch64, many debug labels beginning with `$LVL` `$LBE` and `$LBB` are present in the assembly output. This makes the output very hard to read. The problem is pronounced when using optimization flags as they add a lot more of these labels.

As a workaround, the labels can be disabled by manually passing the `-g0` flag, but that also prevents the line colouring from working.

### Steps to reproduce

1. Visit gcc.godbolt.org
2. Select any of the mips gcc, mips64 gcc or loongarch64 gcc compilers
3. Write a function with a few statements
4. Add the `-O` flag to compiler options
5. Look in the assembly output

### Expected behavior

I expect the output to match the behavior of the other compilers, where these labels are hidden.

### Reproduction link

https://gcc.godbolt.org/z/qvr915Ysz

### Screenshots

![Screenshot](https://github.com/compiler-explorer/compiler-explorer/assets/93952137/7a026716-b51b-4ffd-810d-6a26c879b736)

**Comment by partouf** [comment]
fix is live
