### ISSUE TITLE
[BUG]: `tail call void @llvm.dbg.value` not ignored in LLVM IR

### ISSUE THREAD

**Issue by dzaima** [compiler-explorer/compiler-explorer#6416]
### Describe the bug

A line of e.g.

```llvm
  tail call void @llvm.dbg.value(metadata i32 %0, metadata !23, metadata !DIExpression())
````
isn't hidden in an LLVM IR pane with Filters → "Hide Debug Info" enabled.

Note that in versions of clang where the `tail` keyword isn't present, it is successfully hidden.

### Steps to reproduce

1. Visit the reproduction link
2. Observe the line in question being visible even though Filters → "Hide Debug Info" is enabled

### Expected behavior

The debug information line isn't visible

### Reproduction link

https://godbolt.org/z/Mah88cTv7

### Screenshots

Not applicable

**Comment by partouf** [comment]
Will require a change of some sort to https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/llvm-ir.ts#L70

**Comment by jeremy-rifkin** [comment]
Thanks for the report, should be an easy fix

**Comment by dkm** [comment]
This is live :rocket:

**Comment by partouf** [comment]
this is now live
