### ISSUE TITLE
[BUG]: 'Overrides' stay highlighted after switching language

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#6427]
### Describe the bug

Reported on discord by @Alcaro 

### Steps to reproduce

1. Select rustc,
2. Open 'Overrides' and select edition 2021:
![image](https://github.com/compiler-explorer/compiler-explorer/assets/73080/c4292c0e-5db0-40fd-aece-acda97ea4909)
Observe 'Overrides' is now highlighted in green:
![image](https://github.com/compiler-explorer/compiler-explorer/assets/73080/ac158ab2-dc41-45d6-94a1-60fea61384aa)

3. Change language selection to 'C++',
4. observe 'Overrides' is still highlighted in green, although no C++ compiler override is selected.

### Expected behavior

'Overrides' should be highlighted only if there are currently active overrides

### Screenshots

Not applicable

**Comment by partouf** [comment]
Dupe of https://github.com/compiler-explorer/compiler-explorer/issues/5755

**Comment by OfekShilon** [comment]
Right.
