### ISSUE TITLE
[BUG]: When locally hosting, `dis_all.py` is not found.

### ISSUE THREAD

**Issue by GitHimanshuc** [compiler-explorer/compiler-explorer#6431]
### Describe the bug

I was trying to locally host the compiler explorer for python, compiler explorer finds the python executable because I can see the message:
```
info: compilers/python-3.12.1/bin/python3.12 Python 3.12.1 is ready
```
But when I try to use it I get the error that `dis_all.py` is not found. 
```
compilers/python-3.11.0/bin/python3.11: can't open file 'compiler-explorer/out/dist/etc/scripts/disasms/dis_all.py': [Errno 2] No such file or directory
Compiler returned: 2
```

Now if **I change to the dev mode then everything works**. I see the same behavior with Julia as well if that matters.

### Steps to reproduce

1. Using locally hosted version of compiler explorer for python

### Expected behavior

Not applicable

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Not applicable

### Browser version

Not applicable

**Comment by aw32** [comment]
Found the same thing here: #4225

**Comment by OfekShilon** [comment]
A fix was merged, should be publicly visible at the next deploy.
