### ISSUE TITLE
[REQUEST]: CFG rendered with AT&T syntax rather than Intel syntax

### ISSUE THREAD

**Issue by andyhhp** [compiler-explorer/compiler-explorer#6490]
### Is your feature request related to a problem? Please describe

I've just discovered the CFG view (which is an awesome feature btw).  However, there's no ability to choose the asm syntax used.

### Describe the solution you'd like

An option, similar to (disabling) the compiler view's "Output > Intel asm syntax" flag.

### Describe alternatives you've considered

N/A

### Additional context

Not applicable

**Comment by jeremy-rifkin** [comment]
Hi @andyhhp, if you set the assembly syntax on the main compiler pane you can change the assembly syntax in the CFG too.

![image](https://github.com/compiler-explorer/compiler-explorer/assets/51220084/9325e633-aebb-4373-8f1e-e9c42a2678a4)

I realize this may be slightly surprising that settings in one pane affects another, however, in this case I think it's the best option as ultimately everything in the CFG is controlled by the compiler.

I'm going to mark completed for now but please let us know if you have a use-case where you'd want the assembly syntax to differ between a compiler and a CFG view for a compiler.
