### ISSUE TITLE
[BUG]: code compiles to either infinite loop or nothing with -O3

### ISSUE THREAD

**Issue by zBeeble42** [compiler-explorer/compiler-explorer#6505]
### Describe the bug

So... I'm trying to compare int vs. size_t for indexing integers.  I think it's easiest to just paste in what I see:

![image](https://github.com/compiler-explorer/compiler-explorer/assets/8474734/8483a3d2-af2a-409b-a81d-b7a8b0494b4f)

Let's try some other compiler settings:

![image](https://github.com/compiler-explorer/compiler-explorer/assets/8474734/87f8ff3e-339e-4b39-89ba-437a733fae9a)

Interesting (w.r.t. the last one) if I change -O3 to nothing:

![image](https://github.com/compiler-explorer/compiler-explorer/assets/8474734/33c874bb-ee75-4993-ad10-460882a8d420)

... which is more what I expect.

### Steps to reproduce

1. visit godbolt.com;
2. setup as in images;
3. observe bug.

### Expected behavior

My function should compile to neither the infinite loop nor the empty function.

### Reproduction link

https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAM1QDsCBlZAQwBtMQBGAFlJvoCqAZ0wAFAB4gA5AAYppAFZdSrZrVAB9LclIj2yAnjqVMtdAGFUrAK4BbWiABMpU%2BgAyeWpgBydgEaYxCAAnKQADqhChEa0ljb2TuGR0XQeXr62AUGhepgGMQwEzMQEcXYOzrn5dIXFBGk%2B/oEhukUlZQmVbfWejZnNwQCUuqjWxMgcUp4EANRCdhDTM7R2QgCkAKwAQpsAIqQzS7QaK7ZCg2syAIJrAOw71zNPh/QzxJjzrARrAMy7Mr8HjdHs8aMQIIDlidVjNfthfrsZgCflsoachABaDEXEHPZ7vT6zNaOHZ/ZarTZbY7ovaAy7Aq5494EMa0N4faxfOnXO67KTDVjSDbyBxSTjyVDScxzUbjTCwxw/cWkAjSOSDYYAaycPwAdMEeLcAGzBRymmS3TicRy8QVSbgitUS6TyIQgGQqp3DOCwJBoWxhPDsMgUCD%2BwPBlDIVTqTgADk4HqoQYIgTdED8TtIfk8xQAntJlTnaPmAPJ%2BBR5VVi%2BT%2B2ymAil2isAuyeRYPzWYDmNisN010hYWxqYDsLP4d75ABuHyzmHEeWsqcL8mmmDtchUeD8xHzliwWYIxDwthXpBnxD8kUwu0ww/UrE8oDbwyoqmAQgAanhMAB3UthKYZ78IwLBjjwfB0AQwhiJIbaKMoMaaNoW5%2BG6kDDKgYSGHQ/YYqWPwShex5YOhEDDFUOEOBArgdA4nAuGYDQZFkygRFEVF0WxyRUcxTRBAxlEFN0XGCeuVbCXUfH9AJrR1KJcklNJrGcBRsoTFwApCo68GSlIMziHGRoYka3AzNGI4zPGuqcLqMgzBAuCECQCpKoM8jVuqWpOBsurcI4cZxj8tyOIqGxBT8RkqNIDqkKKm56a67qei%2BpA%2BogKCoAGQaBOQlDhjlQTIBZsYJkmKZppQmbwcW%2BZnrVxB5uWlYGGedYNk2Lbjpgnbdr2/bKkOI5jvBE4STO/abvOi7LgOa4bvIj47nuGCTJuR4nmeF5XiIt73qOT5enw75fj%2B/6AaKyogUwbAcBBIEwRIWZKM4SEgFoGg6EtZGYdhMR4QRRGBCRs4Ybo4nVNRtFWOUyiuMpzQMexKSxDDCRIzxMQI7JQk1CJaP0eD%2BhUbUSm9CxiOKaUBPKEI3TY5pIxjBpjhaVIwpxVmekGUZJlmSVwBWXGNl2Q5TlEMQrmsx5XrDAgmDMFgQTkaQ2qOL5wS3D8MjcHGMgbNaRoyAmGzRfaOkJS6ujJZ5/JpTAGVoFg4skHl1BQTd4G8A9IhPfBL0qCO70objUNmFxzjw%2BT/FcBjHExBHSTx6k0cybHRMSXj8k05UEMk/TqcqYJ%2BPxBUVMM1aanM5MxI/J40bWFgsI/OY1i0HgdPoLqCBwvS9JLLYebzLYiyvDS2x7AcUQAF6YBoszUqsOI3Pc9J4ksBKct8fzIkCa%2BgiQEIomiMK92Su8n2cWLL3iTIcl8Cqkoi49UtCZy0iife4uyLLEGym9ck/jyW4fI2Yc3is6KQ0ohDqXlLXRwMsXxywVkrSg3kbS6iNBFbgGxuA/G1nGbgWCjRm1ihA0giVrYelthqM2CDOa6StjQ4YF4ojGG4EAA

### Screenshots

see above.

### Operating System

I'm browsing on Win10

### Browser version

I'm using up-to-date firefox.

**Comment by partouf** [comment]
The function contents are not there with `-O3`, not sure what's going on, also in the binary modes the code is eliminated.
The same code in c++ mode works just fine.

It looks like a Clang bug to me.

**Comment by partouf** [comment]
Actually, wait, isn't `size_t` unsigned? Hence the loop would never end

**Comment by partouf** [comment]
I'm not really a C expert, so I don't know what the rules are. But considering a loop written as `for (;;)` "works" (as in, it is implemented as an infinite loop without other implementation https://stackoverflow.com/questions/15595493/is-an-empty-infinite-loop-undefined-behavior-in-c), I could imagine your loop being one of those throw hands in the air give up kind of situations.

**Comment by zBeeble42** [comment]
OK fair enough... I was trying to minimize my argument and ... well ... got nowhere, but this is entertaining:

![image](https://github.com/compiler-explorer/compiler-explorer/assets/8474734/fb091bf4-6ddd-4f22-bf31-6867dca0a8a5)

**Comment by jeremy-rifkin** [comment]
I'm surprised by this but the infinite loop appears to be intentionally optimized away by clang here: https://godbolt.org/z/4q8qYGj5s. The example on the left appears to be not an infinite loop (though, tangentially, `nums[n_nums]` may be out of bounds access on the first iteration), so no surprising behavior there. Loop deletion itself and the transformation/analysis to discover that the loop can be deleted would only be done with optimizations enabled, hence the absence of surprising behavior without -O3. I'll go ahead and close this for now since I think all is fine on the Compiler Explorer side of things.
