### ISSUE TITLE
[BUG]: Mobile mode can't be edited?

### ISSUE THREAD

**Issue by yazigegeda** [compiler-explorer/compiler-explorer#6521]
### Describe the bug

When I switch to mobile mode, I can't edit and can only browse in read-only mode.

https://github.com/compiler-explorer/compiler-explorer/assets/63853093/1303eb97-c2ef-44ea-8287-2322eecb835c

### Steps to reproduce

I use the edge mobile browser to access it and it becomes uneditable when I set the phone mode

### Expected behavior

I can't pop up the phone's soft keyboard for me to edit

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by RubenRBS** [comment]
Hi, thanks a lot for taking the time to report the issue - this is unfortunately a known issue. Our editor of choice, Microsoft's Monaco Editor - does not currently support phone views (And it's an stated non-goal)

While more can always be done to ease the pain, our current solutioin is to recommend adding a `/noscript/` bit before the URL, which will bring you to a plain html site that allows editing (So for example https://godbolt.org/z/bqefKzzxW would become https://godbolt.org/noscript/z/bqefKzzxW)

I hopen this helps a bit :)

**Comment by leosat** [comment]
@AbrilRBS , @mattgodbolt , greetings. Have been looking for relevant tickets and found this one... I know it's closed, but so many times there was a need to edit code on your service via mobile android phone and - it just doesn't work because of the reasons described in this ticket. **Question**: is it possible to make for android users some clickable link leading to this "/noscript/" path  telling something like "Editing on Android is not supported in main mode, if you can't edit - go to HTML-only iface "...

**Comment by mattgodbolt** [comment]
You can also try telling your browser for the "desktop site" and try and see how it works for you?

**Comment by leosat** [comment]
Sure it has been done, and while editor area becomes editable, the behavior of the interface is next to unusable: it gets randomly "focused-in" some area of editor without inability to get back to normal scales  and other places of interface (i use Chrome) , gets randomly stuck when clicking on "add compiler/execution" ... etc. So, every ~9 out of 10 times just have to switch to desktop or use some other tool. Just FYI,in case something can be done to have a mobile-friendly iface also.

**Comment by mattgodbolt** [comment]
@leosat as we've said this is unfortunately a non-goal for CE. Trying to get our big and complex UI working on small form factors, especially with the editor widget we use (Moncao) explicitly not supporting mobile - we just don't have the time or skill. See #4571

**Comment by leosat** [comment]
Actually the /noscript/ variant does the job! (at least it works for editing,allows switching between languages and shows compiler output). So, returning to the original message, maybe it would be feasible just to show it by-default for mobile clients (or show the bold link leading to it for those who dont know). Just a suggestion. But given the editor's "non-goal" to support mobile that could be a more user-friendly experience, than a non-working service.
