### ISSUE TITLE
[BUG]: Browser tab refresh resets all renamed CE tabs

### ISSUE THREAD

**Issue by bsdooby** [compiler-explorer/compiler-explorer#6525]
### Describe the bug

If a Browser tab refresh happens (forcefully or not), then all renamed CE tabs are reset to their default values. 

However, if a file is restored/loaded from the filesystem, then the CE tab gets renamed acc. to the name of that file; and such a CE tab name persists, even after a Browser tab refresh.

### Steps to reproduce

As described above:
1) create new session
2) add new Source Editor
3) rename/relable tab
4) refresh Brower (tab)
5) label gone 

### Expected behavior

Renamed tabs should be persistent.

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

all tested (Windows, Ubuntu, macOS) [current[

### Browser version

all tested (Firefox, Edge, Chrome) [current]

**Comment by jeremy-rifkin** [comment]
Confirmed

**Comment by RubenRBS** [comment]
Fix is now live, thanks again for reporting it :)

**Comment by bsdooby** [comment]
Hey Abril, CE team,

Absolute pleasure! Thank you for your great product and your great support.
And all this basically for free! Keep up the good work.

Cheers
