### ISSUE TITLE
[BUG]: preprocessor output is empty when using MS compiler

### ISSUE THREAD

**Issue by pps83** [compiler-explorer/compiler-explorer#6537]
### Describe the bug

Here's the link: https://godbolt.org/z/cfPxecM13

both gcc/msvc should produce identical results, but godbolt shows empty output for msvc.
Manual compilation with `/P`on my pc shows that the result is ok, and not empty as shown by godbolt

### Steps to reproduce

... link has all the info

### Expected behavior

msvc output should be identical to gcc

### Reproduction link

https://godbolt.org/z/cfPxecM13

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
/E works (which writes to stdout), /P is writing to some file with a name other than what CE reads for assembly output. A better alternative to these flags is to use the preprocessor view, which msvc now supports: https://godbolt.org/z/7ejo8WMda.
