### ISSUE TITLE
[BUG]: Internal Compiler Explorer error: Error: Unexpected basic block terminator:

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#6545]
### Describe the bug

https://godbolt.org/z/GoTqaaYPW

LLVM-IR cfg doesn't handle a `callbr` IR instruction.
Investigation started with this Sentry case:
https://compiler-explorer.sentry.io/issues/5436839106/?alert_rule_id=180927&alert_timestamp=1717231977289&alert_type=email&environment=prod&notification_uuid=64d0666f-7c16-4f47-b2e6-08196f4c3ca4&project=102028&referrer=alert_email

### Steps to reproduce

-

### Expected behavior

-

### Reproduction link

https://godbolt.org/z/GoTqaaYPW

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
A number of more rare llvm branch instructions have been a TODO in the code, partly because I didn’t have a repro for their use. Shouldn’t be too hard to implement callbr.

**Comment by OfekShilon** [comment]
> A number of more rare llvm branch instructions have been a TODO in the code, partly because I didn’t have a repro for their use. Shouldn’t be too hard to implement callbr.

`callbr` was actually implemented, but indeed it's rare enough to have some yet-undetected rough edges. I also don't know how to repro the unimplemented ones.
