### ISSUE TITLE
[BUG]: Incorrect C++ std::optional behavior

### ISSUE THREAD

**Issue by dbiswas2808** [compiler-explorer/compiler-explorer#6561]
### Describe the bug

Not sure why but a nullopt variable doesn't throw on accessing the underlying type's members. Pasting the short link here.
https://godbolt.org/z/EafE3PqY7
I'm using compiler `x86-64 gcc 14.1`

### Steps to reproduce
Please execute the following.
https://godbolt.org/z/EafE3PqY7

### Expected behavior

Should be throwing on access of nullopt value.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
Hi, this isn’t a CE bug or incorrect std::optional behavior. It’s UB to access the contents of a std::optional that does not hold a value, the standard library is not required to throw: https://en.cppreference.com/w/cpp/utility/optional/operator*.

**Comment by dbiswas2808** [comment]
Ah I see. Makes sense, thanks for clarifying.
