### ISSUE TITLE
[BUG]: Cannot parse 'constexpr' in editor

### ISSUE THREAD

**Issue by Minsecrus** [compiler-explorer/compiler-explorer#6568]
### Describe the bug

Language: C
The editor Cannot parse `constexpr` as a C **keyword**

### Steps to reproduce

1. visit godbolt.org
2. select language **C**
3. key the code
   ```c
   int main(void){
      constexpr int N = 1;
   }
   ```

### Expected behavior

parse `constexpr` as a C **keyword**

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
Hi, `constexpr` was added to C in C23, which is relatively recent and not the default for gcc. If you want to use C23, use `-std=c23`.

**Comment by Minsecrus** [comment]
I've already add `-std=c23` to **Compiler Options** but it didn't work.

**Comment by Minsecrus** [comment]
I've already add `-std=c23` to **Compiler Options** but it didn't work.

However, the compiler could run effectively, so it only caused a **decreased visual perception** but have nothing about the normal use.

**Comment by partouf** [comment]
Works fine https://godbolt.org/z/Wrq6vaKqf

**Comment by jeremy-rifkin** [comment]
It occurred to me last night, are you referring to syntax highlighting of the keyword?
