### ISSUE TITLE
[REQUEST]: [LLVM]Add ability to search pass name in Opt pass pipeline view

### ISSUE THREAD

**Issue by madhur13490** [compiler-explorer/compiler-explorer#6569]
### Is your feature request related to a problem? Please describe

Opt pass pipeline is a great feature but the number of passes are quite large and it is cumbersome to scroll. 

### Describe the solution you'd like

It would be nice if you can add a search box in the panel to allow users to search the pass name and jump to it.

### Describe alternatives you've considered

NA

### Additional context

Not applicable

**Comment by RubenRBS** [comment]
Thanks a lot for your request @madhur13490, I'm proposing #6570 for this, let's see what the rest of the team thinks :)
