### ISSUE TITLE
[BUG]: GCC crash could not be reproduced in local

### ISSUE THREAD

**Issue by RungeCC** [compiler-explorer/compiler-explorer#6602]
### Describe the bug

Godbolt gcc 13.2.0 crashed with no stack trace (see https://godbolt.org/z/xGTrchqd4) this behavior could not be reproduced locally.

### Steps to reproduce

```c++
// reproducer source code

template < typename... Ts >
struct list {};

template < typename... Ts >
constexpr
bool ice = []( list<decltype([](Ts){})...> x = {}) { 
        return true;
    }();

constexpr auto r = ice<int>;
```

with
- flag: `-std=c++20`
- gcc 13.2.0, full version `g++ (Compiler-Explorer-Build-gcc--binutils-2.40) 13.2.0`

### Expected behavior

compiling successfully (may have a linker error since there's no main function, but that's irrelevant). However it crashed.

- Notice that if add flag `-fsyntax-only` then everything looks good (https://godbolt.org/z/E5vx9d46M)

### Reproduction link

https://godbolt.org/z/xGTrchqd4

### Screenshots

Note that the linker error is expected since there's no `main` function.

![image](https://github.com/compiler-explorer/compiler-explorer/assets/50059102/ffb51be6-d603-449f-a522-1372648578d8)

### Operating System

NixOS 24.11.20240605.e8057b64

### Browser version

firefox 126.0.1 (64-bit)

**Comment by narpfel** [comment]
I can reproduce this locally with when passing `-g` (Arch Linux, GCC 14.1.1):
```console
$ g++ -g -std=c++20 t.cxx
g++: internal compiler error: Segmentation fault signal terminated program cc1plus
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <https://gitlab.archlinux.org/archlinux/packaging/packages/gcc/-/issues> for instructions.
```

Clicking on the green check mark/red x next to the compiler flags input area shows the complete set of flags compiler-explorer passes to the compiler, in this case
```
-g -o /nosym/tmp/compiler-explorer-compiler2024514-7882-zw24zo.hs13k/output.s -masm=intel -S -fdiagnostics-color=always -std=c++20 /nosym/tmp/compiler-explorer-compiler2024514-7882-zw24zo.hs13k/example.cpp 
```
So this should probably be reported to GCC.

**Comment by jeremy-rifkin** [comment]
Good call on -g. I'll go ahead and close since it sounds like the mystery has been solved.
