### ISSUE TITLE
[BUG]:  MSVC not working

### ISSUE THREAD

**Issue by AyameNero** [compiler-explorer/compiler-explorer#6603]
### Describe the bug

Choosing MSVC compiler results in the following error:

<Compilation failed: Request failed: HTTP error code 502>

Applies for both 32-bit and 64-bit versions of MSVC.

### Steps to reproduce

1. Visit godbolt.org
2. select c or c++ lang and any of msvc compiler

### Expected behavior

.

### Reproduction link

Not applicable

### Screenshots

![others](https://github.com/compiler-explorer/compiler-explorer/assets/143188470/4d00f8e6-ff9e-40ff-ac2a-98e16d11f28b)
![3](https://github.com/compiler-explorer/compiler-explorer/assets/143188470/d8bf818a-4b58-4cc8-aec1-26d575b2f7c9)
![2](https://github.com/compiler-explorer/compiler-explorer/assets/143188470/1e4e73cf-a54d-4bee-9116-9c61267fe4ae)
![1](https://github.com/compiler-explorer/compiler-explorer/assets/143188470/165a76cd-f496-4e64-9992-e9ffd5cc3608)

**Comment by jeremy-rifkin** [comment]
MSVC compilers are down right now, hopefully they'll be back sometime soon. Not a bug per-se, at least not on our side (microsoft hosts their compilers on godbolt.ms), but thanks for letting us know.

**Comment by OfekShilon** [comment]
Back online - and even from a CE-managed instance.
