### ISSUE TITLE
[BUG]: #include<vector> stopped working in clang on frontend

### ISSUE THREAD

**Issue by ranaanoop** [compiler-explorer/compiler-explorer#6607]
### Describe the bug

I've noticed that `#include<vector>` stopped working in clang in conformance view as well as execution mode. [Demo](https://godbolt.org/z/cqeMM14Gh)

The clang error says:

```
In file included from <source>:1:
In file included from /opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/15.0.0/../../../../include/c++/15.0.0/vector:62:
In file included from /opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/15.0.0/../../../../include/c++/15.0.0/bits/stl_algobase.h:64:
In file included from /opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/15.0.0/../../../../include/c++/15.0.0/bits/stl_pair.h:60:
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/15.0.0/../../../../include/c++/15.0.0/type_traits:549:30: error: use of class template '__is_pointer' requires template arguments; argument deduction not allowed in function return type
  549 |     : public __bool_constant<__is_pointer(_Tp)>
      |                              ^~~~~~~~~~~~
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/15.0.0/../../../../include/c++/15.0.0/bits/cpp_type_traits.h:368:12: note: template is declared here
  368 |     struct __is_pointer : __truth_type<_IsPtr>
      |            ^
1 error generated.
Compiler returned: 1
```
Below is also attached the screenshot for reference. 

### Steps to reproduce

1. Open this [demo](https://godbolt.org/z/Phj9EP1G3)

### Expected behavior

Expected behavior is that the program should compile in clang.

### Reproduction link

https://godbolt.org/z/Phj9EP1G3

### Screenshots

![image](https://github.com/compiler-explorer/compiler-explorer/assets/93918384/044395c3-6b88-49ac-8fbd-a1c1a503a674)

### Browser version

Firefox

**Comment by partouf** [comment]
This happens occasionally as clang trunk uses gcc's trunk stdlib. It will usually be fixed by someone, but you can also file the issue at [llvm-project](https://github.com/llvm/llvm-project/issues)

**Comment by partouf** [comment]
Double check that this is indeed somewhere in Clang trunk. (although the issue appears more complicated than just a quick fix for them probably, but I'm no expert)
https://godbolt.org/z/6M1jMKT3j

**Comment by jeremy-rifkin** [comment]
Clang trunk fixed itself so I think we can close
