### ISSUE TITLE
[REQUEST]: Option to present assembly code as a static text (for mobile)

### ISSUE THREAD

**Issue by Explorer09** [compiler-explorer/compiler-explorer#6608]
### Is your feature request related to a problem? Please describe

This is a humble UI request even if you have no plan to implement a full mobile friendly interface (#4571) right now.

Compiler Explorer has two output panels, one for assembly or preprocessed code, and the other for compiler logs and execution output (`stdout`). I mark these in the screenshot below as (B) and (C) respectively.

![Compiler Explorer screenshot](https://github.com/compiler-explorer/compiler-explorer/assets/2487263/ca5f63db-a657-47c3-9e02-a3688ae48df4)

(B) is presented as an interactive text box, while (C) looks like static text with fixed-width font. I understand why (B) can be interactive here (to get a quick mapping to the source line, or to look up assembly documentation via a context menu). However, the interactive functionality severely breaks in mobile. The cause is something to do with it being a text box:

* Tapping any part of the text get unnecessary zoom in from the browser.
* Two-finger zooming don't work in the box (very difficult to zoom out - I have to place fingers outside the text box in order to zoom out).
* The "right-click" context menu can sometimes pop in and further blocks what I can do with the finger action (it distracts reading, too, as that menu weren't designed well for mobile or tablet use).

### Describe the solution you'd like

So what I personally wish is this simple UI feature: To **disable all interactivity** for the assembly code panel. Make the (B) panel work no differently from the compiler/execution log (C) panel. This quick hack/option would at least make it _workable_ in mobile, even though full mobile support won't come in.

### Describe alternatives you've considered

(none)

### Additional context

Brave browser 1.66.120 (Chromium 125.0.6422.165)
Android 10

**Comment by jeremy-rifkin** [comment]
Mobile would be nice but it would be a lot of work. In the meantime https://godbolt.org/noscript is the best way to go for mobile.

**Comment by Explorer09** [comment]
@jeremy-rifkin Unfortunately the "noscript" version can't compile certain code. I try to copy this snippet (https://gitlab.com/-/snippets/3718423) and compile it in https://godbolt.org/noscript , it produces error that wouldn't appear in the normal version.
It might be a separate issue to report, but I don't have time for reporting that yet.

**Comment by partouf** [comment]
> @jeremy-rifkin Unfortunately the "noscript" version can't compile certain code. I try to copy this snippet (https://gitlab.com/-/snippets/3718423) and compile it in https://godbolt.org/noscript , it produces error that wouldn't appear in the normal version. It might be a separate issue to report, but I don't have time for reporting that yet.

This code is only valid in C, you will have to select C on noscript first, the default is C++

**Comment by jeremy-rifkin** [comment]
Closing in favor of #4571
