### ISSUE TITLE
[LANGUAGE REQUEST]: Lean4

### ISSUE THREAD

**Issue by nuudlman** [compiler-explorer/compiler-explorer#6609]
### Language name

Lean

### Language version

4

### Language homepage

https://lean-lang.org/

### Compiler homepage

Binaries: https://github.com/leanprover/lean4/releases/latest, Build instructions: https://lean-lang.org/lean4/doc/make/index.html

### Compiler version

4.8.0

### Motivation

It would be nice to be able to see the generated code from a very high-level language and see optimization quality, and compare it against more traditional langauges.

**Comment by ojeda** [comment]
https://github.com/compiler-explorer/compiler-explorer/issues/5634?

**Comment by jeremy-rifkin** [comment]
Yeah, closing in favor of that issue
