### ISSUE TITLE
[BUG]: Cannot find library -lfmtd on compiler explorer web during compilation

### ISSUE THREAD

**Issue by 19Trunx96** [compiler-explorer/compiler-explorer#6619]
### Describe the bug

The error message is the following: "ASM generation compiler returned: 0 /opt/compiler-explorer/gcc-13.2.0/bin/../lib/gcc/x86_64-linux-gnu/13.2.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -lfmtd: No such file or directory collect2: error: ld returned 1 exit status Execution build compiler returned: 1"

### Steps to reproduce

Just waiting for the code to compile

### Expected behavior

It should me return something

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by partouf** [comment]
Sorry, we had a wrong setting somewhere. It should be now fixed
