### ISSUE TITLE
[BUG]: .NET executor is broken

### ISSUE THREAD

**Issue by 0f-0b** [compiler-explorer/compiler-explorer#6620]
### Describe the bug

.NET executor fails to run the program. Most of the time it gives an error saying “runChild():487 Launching child process failed”. Last saw it working 3 days ago.

### Steps to reproduce

1. Visit <https://csharp.godbolt.org/>.
2. Add an executor.

### Expected behavior

The program runs.

### Reproduction link

https://csharp.godbolt.org/z/39b6Eh1rT

**Comment by CodeByAidan** [comment]
Please be a bit more specific, next time when creating an issue, it asks for a screenshot...

![image](https://github.com/compiler-explorer/compiler-explorer/assets/67598470/48787a1b-73cb-49eb-9f63-809393d46d5c)

Console:
```
Program returned: 255
Program stderr
[F][2024-06-17T03:33:37+0000][1] runChild():487 Launching child process failed
```

**Comment by hez2010** [comment]
Probably related: #6413

**Comment by partouf** [comment]
> Probably related: #6413

Not impossible, but I did test it extensively when i pushed those changes.

I think started after this went live though https://github.com/compiler-explorer/compiler-explorer/pull/6522

Ah, I see it. You removed `executionEnvironmentClass=local-dotnet` from the properties files https://github.com/compiler-explorer/compiler-explorer/pull/6522/files#diff-2efd9e45c85dd18ef7bd3dd01bc194f4c2b3bf92d3e465bf914f5c57ea60bca1L6
