### ISSUE TITLE
[BUG]: clang 7-9 linkage produces warnings

### ISSUE THREAD

**Issue by Alcaro** [compiler-explorer/compiler-explorer#6622]
### Describe the bug

![image](https://github.com/compiler-explorer/compiler-explorer/assets/5085186/f4a83484-3f82-416f-9c08-e9727de5d67d)

### Steps to reproduce

1. clang 7
2. execute
3. int main() {}

### Expected behavior

don't know but it's not
```
ASM generation compiler returned: 0
/opt/compiler-explorer/gcc-8.2.0/lib/gcc/x86_64-linux-gnu/8.2.0/../../../../x86_64-linux-gnu/bin/ld: warning: /lib/x86_64-linux-gnu/crt1.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
/opt/compiler-explorer/gcc-8.2.0/lib/gcc/x86_64-linux-gnu/8.2.0/../../../../x86_64-linux-gnu/bin/ld: warning: /lib/x86_64-linux-gnu/libm.so.6: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
/opt/compiler-explorer/gcc-8.2.0/lib/gcc/x86_64-linux-gnu/8.2.0/../../../../x86_64-linux-gnu/bin/ld: warning: /lib/x86_64-linux-gnu/libmvec.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
/opt/compiler-explorer/gcc-8.2.0/lib/gcc/x86_64-linux-gnu/8.2.0/../../../../x86_64-linux-gnu/bin/ld: warning: /lib/x86_64-linux-gnu/libc.so.6: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
Execution build compiler returned: 0
Program returned: 0
```

### Reproduction link

https://godbolt.org/z/v6zrr6aWa

### Screenshots

Not applicable

**Comment by dkm** [comment]
Yes, probably a too-old binutils.

**Comment by dkm** [comment]
Note that linker probably ignores these properties and proceed with the link. So these are "only" extra warnings, coming from the past :D

**Comment by OfekShilon** [comment]
The problem persists until clang 9.0.1, including.

**Comment by dkm** [comment]
We may want to use a more recent gcc toolchain, but that may have extra side effects...
