### ISSUE TITLE
[BUG]: Saved template link uses wrong compiler

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#6632]
### Describe the bug

Post our move to MSVC on prem, template links seem to refer to the wrong compilers

### Steps to reproduce

1. https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIaa4AMngMmAByPgBGmMQgAGykAA6oCoRODB7evv5JKWkCwaERLNGxCXaYDulCBEzEBJk%2BftIVVQI1dQSF4VEx8ba19Y3ZLYNdIT0lfXEAlLaoXsTI7BwA1KsAbqh46KtUEDOrJgDsVhoAguvrIQSrqiYAzGeXVyYArFZmce8AIkenJguVyuxEwBEWDDujwswKuAHo4UczA8uICXusTj9oWiMccfhw5rROG9eH5uLxUJw3NZrKsFAslpgkSjeARNAS5gBrEAPB4AOjMkkkAE4uHENBoHm8HnE4sLpESOJJSezSJSOLwFCANKQ2RwtHM4LAYIgUKgWIk6DFyJQ0BarbFkAYjFwABxcHU0WgEGJaiCRVWREJ1ACenB4pCDzGIIYA8pFtJU9RG7WxBLGGLQw/reFhIl5gG4xLQteTSFgWIZgOIc%2BW8KCqhtMKWtKRMKpKl4feHeDdMIrW7Q8JFiKGPFhVQRiHgWD3SE3iJEUpgfphK0Yh0Z2XMqAZgAoAGp4TAAd1jiUYc/4ghEYnYUhkgkUKnUtd0XH0VZQNMs%2BmHWsgOZUESRwBFLABaBQCHQR4flMSxrDMZAKQXacsAAg5bH7JN0hcBh3E8Jo9CCCZilKPRklSUCMkI7IP0o/IGG6Mi%2Bg/VpqI6IZaL8NjsLaBhOPGIpeliNixmGHiBk6ZiRIkOZ6UWZY5P0YkVVrdU7ldOJwLiSRVidKtVjdPkuD5DRVggXBCBIZkuBmVlty5Hl%2BV5Vy3PclSlV4WcuDMPk4jMY5hS0h5JHdMwzC045SDJVt1U1bVdW3UgjVNBYCESLsbQgO1LXoYgwlYFZVC0nS9IMowLKnLwGE5ey23wIg0L0a9hFEcQH1a581FVd9SBPUdEh7QlVJi1V1VjLtMtuVAqE07TdP051gCM10TLMiyPHtfLbPqvUDTmBBMCYLBYkwxVlVIWdQr5N5kTMN5JGOV0XriN1XWkWKKU4BKdX2gkUpNCAkFyh1stB/KQEwdBgB0gB9bSsCoJgvG9cCuAePg6B9Yg/QDWso1DOdCZjeNEwcOdU0YAgMyzVU8wLItaBLOcKyrGtW3wBtHCbFteHbTtuzLPsB14IcRzHDAVlbKcZznBclyUVd12rEJQBzHc90PY8zwvMkI1a28OukLqlB6t8eU/Ld4M%2BGxxYwoCQPSCDwJtxCHhQmI0ObeB5L46i8IIrJJJI4SplE3IqPSCSKLyaiZPDvR2OqcTuKT/2U%2Bk0jZLEzoY9z%2BoE/Iuz5kU%2B8Ro4EkxvUzhVmwH4AHFVjifyLKsprdocjXDuO07KAry6fOOPljhRB5RS0h6ZWODRoq%2BtUftsRL/sNIGkHS6bwfNPKYkKthOBKha9OAZBkCMyQTP5xqSB2FrZCN%2B8TdkbrX1bXRMYGpghvJCuq/niappdlWLNOujdm6twgFtHexBmQPD2o5Tyg8eRvBMlwUecQZ4Sieq6R61c4qLy1H9BB3JeR8kkGYNBbwNCyhRGYYUwUFScA9ng76Gokoa0BvAVKwMzTbWtBQHK28HQgGAFID8XocZ40DMGGMxMZFxgTEmSm5o0w00zNmTmmB8yFmLKWCMbMNzS1zPWHCvNVQC2QF2FYEYRaqnFqOGM44jG6mnLOMsCtlzK3ZmrZKu4mD7iPKec8l4yyG3ao/R88gzavx0CAMwVtjA/jtv%2BX2aonZgU4JBaCsE3aWCQp7Yg3sHZYXsAHCArh85tnwkXVikdGKVIYvHbOideKlMzlxYO6c2ntDGDUiOUE85pwLkJSYxd5IMiUiXRUf9xq10PmVVYJ8z5SBMm3a%2BMDzAongd3UgJCXLuQObyRB3kJB%2BWFHKSKDxAq6SoW8LgbwWELzYYQ9hBpOGwHXoAggW8%2BEFSKgfUqi0lnn0vg1ayzVxH33CRIJ%2BT5om9Tif1Qaw1PIzJrhwSaGUgEgPmUC0%2BIKuCbSETtTZZhtkHVIEdE6fRzqcCQTdN0GguDCg0B9Y4GCmVfEefFJeRCOHcJBsS/htohWxA2MgRIiQ4YbGZXDB4ro4Z1BYLpLG3pfSUHxq2Em2YIzarJkossVN0zqPploxmujWZrnZs4rmpifa1gsVYuctjaz2MlhOWsss3ERg8UrK1G4fEcL8QEnWwT9a8DCXeGFkSX4IoVF%2BXJyTIjFOAtRUscIoLoG/AhSwBgfRQQKUU1JydnDlPwpU0OozamNOjkMupTSw7FxKThHpgzOmtJbQJXpzSm0DI6URYZfTlIKUZMpaZal8FrCVYtFgChxWbGZXyeVazwWd1eRySlvcaUDxOWgkeKIGHHDFHdN4wpjgPP/gQ5eyUBUgA3llARENd7/I4Li4%2B%2BKVkRmhuC2%2BkKbzQs6s/eFFtpCf2/jwX%2BE7WGYumsAua069KzvnTK4US7XREt%2BcySQ5KN0XROVKVBODJBcHucKKUvJhTcqvXyileyl2HIOZ5Zhl62ErwrmYKDTyu4UoXKkZwkggA
2. observe bottom right is "arm64" not "x64" as before

### Expected behavior

should be x64

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by Alcaro** [comment]
That link decompresses to
<details>
g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:4,endLineNumber:6,positionColumn:4,positionLineNumber:6,selectionStartColumn:4,selectionStartLineNumber:6,startColumn:4,startLineNumber:6),source:'++void+f()+%7B%0A++++int+x%3B%0A++++%5B%26%5D+%7B%0A++++++return+x%3B+++++++//+%231%0A++++%7D%3B%0A++%7D'),l:'5',n:'1',o:'C%2B%2B+source+%231',t:'0')),k:33.244916003536694,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:clang1810,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-std%3Dc%2B%2B2c',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+clang+18.1.0+(Editor+%231)',t:'0')),k:33.33333333333333,l:'4',m:12.627986348122867,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+clang+(trunk)',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+clang+18.1.0+(Compiler+%231)',t:'0')),header:(),l:'4',m:34.523254788861884,n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:edg-6_6-default-13,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:3,lang:c%2B%2B,libs:!(),options:'--c%2B%2B23',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+EDG+6.6+(Editor+%231)',t:'0')),header:(),l:'4',m:17.731391862536707,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+gcc+14.1',editorid:1,fontScale:14,fontUsePx:'0',j:3,wrap:'1'),l:'5',n:'0',o:'Output+of+EDG+6.6+(Compiler+%233)',t:'0')),l:'4',m:35.11736700047854,n:'0',o:'',s:0,t:'0')),k:33.421750663129984,l:'3',n:'0',o:'',t:'0'),(g:!((g:!((h:compiler,i:(compiler:g141,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:2,lang:c%2B%2B,libs:!(),options:'-std%3Dc%2B%2B2c',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+14.1+(Editor+%231)',t:'0')),k:33.33333333333333,l:'4',m:12.969283276450515,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+gcc+14.1',editorid:1,fontScale:14,fontUsePx:'0',j:2,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+gcc+14.1+(Compiler+%232)',t:'0')),header:(),l:'4',m:34.180190847670126,n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:vcpp_v19_38_arm64,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:4,lang:c%2B%2B,libs:!(),options:'/std:c%2B%2Blatest',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+arm64+msvc+v19.38+(Editor+%231)',t:'0')),header:(),l:'4',m:17.731984716525975,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+gcc+14.1',editorid:1,fontScale:14,fontUsePx:'0',j:4,wrap:'1'),l:'5',n:'0',o:'Output+of+arm64+msvc+v19.38+(Compiler+%234)',t:'0')),l:'4',m:35.11854115935339,n:'0',o:'',s:0,t:'0')),k:33.33333333333333,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4
</details>
Note the substrings compiler:clang1810, compiler:edg-6_6-default-13, compiler:g141 and compiler:vcpp_v19_38_arm64.

Either the compiler identifiers were screwed up on godbolt.ms, or this is a false alarm.

**Comment by mattgodbolt** [comment]
Closing as "probably misremembered" or else the godbolt.ms was mucked up (as @Alcaro says), and we can't fix that.
