### ISSUE TITLE
[BUG]: abort results in segmentation fault

### ISSUE THREAD

**Issue by hvdijk** [compiler-explorer/compiler-explorer#6634]
### Describe the bug

When a program aborts, it is supposed to end with SIGABRT, but it insteads ends with SIGSEGV.

### Steps to reproduce

1. Visit godbolt.org
2. Enter the program

       #include <stdlib.h>
       int main() { abort(); }

3. Tick Output > Execute the code

### Expected behavior

I would expect this to result in

> Program returned: 134
> Program terminated with signal: SIGABRT

Instead it results in

> Program returned: 139
> Program terminated with signal: SIGSEGV

### Reproduction link

https://godbolt.org/z/8bbbvbGo3

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
Indeed, #5224

**Comment by hvdijk** [comment]
Ah, thanks! I should have searched for SIGABRT, not just for abort. Let's close this, then, one issue is enough.
