### ISSUE TITLE
[BUG]: `godbolt.ms` is not resolved without `www.`

### ISSUE THREAD

**Issue by bersbersbers** [compiler-explorer/compiler-explorer#6657]
### Describe the bug

http://godbolt.ms should work, but it does not (`ERR_NAME_NOT_RESOLVED`)

### Steps to reproduce

```
C:\>nslookup www.godbolt.ms 8.8.8.8
Server:  dns.google
Address:  8.8.8.8

Non-authoritative answer:
Name:    www.godbolt.ms
Address:  20.80.183.114


C:\>nslookup godbolt.ms 8.8.8.8
Server:  dns.google
Address:  8.8.8.8

Name:    godbolt.ms
```

### Expected behavior

Both work

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment]
Hi!

The godbolt.ms site was always an internal name, administrated by Microsoft and not part of Compiler Explorer directly.

We do not support that site and in fact no longer use it in any way. So unfortunately we can't fix anything there.

Is this causing you issues? At a push we can put you in touch with Microsoft but it's unlikely they'll be able to do anything to help, sorry.
