### ISSUE TITLE
[BUG]: output of msvc is blank when using anonymouse structure

### ISSUE THREAD

**Issue by fekir** [compiler-explorer/compiler-explorer#6660]
### Describe the bug

The code for anonymous structure is generally not shown.

Consider following program

~~~~
struct {} a;


auto bar(){
    return a;
}
~~~~

The msvc compiler compiles it successfully, but no generated code is shown.

If the program is changed to

~~~~
struct s {} a;


auto bar(){
    return a;
}
~~~~

then the generated code is shown.

### Steps to reproduce

Copy-paste the code snippets on godbolt.org and verify what stated in the description

### Expected behavior

The assembly output should be there also for the anonymous structure

### Reproduction link

https://godbolt.org/z/5GnTMfdd3

### Screenshots

Not applicable

**Comment by partouf** [comment]
When it's not used (by `main` or by a `__declspec(dllexport)` function or something similar), MSVC just decides to omit it.
When it is used you can see it.

To me this seems like normal behaviour.

In any case not a CE bug.

**Comment by fekir** [comment]
@partouf yes, adding a main and calling a function is the workaround I've used until now.

I see now that if I change the code to

~~~~
struct {} a;


auto bar(){
    return sizeof(a);
}
~~~~

then the assembly is shown.

It seems you are right; if the parameters or return value depend on the anonymous structure, then msvc realizes that it cannot be used from another translation unit, and thus is able to optimize it out.

In afterthought, it's a pity that GCC and clang do not perform a similar optimization.

> In any case not a CE bug.

Yes, seems to be the case; can be closed.
Thanks for investigating.
