### ISSUE TITLE
[BUG]:  Compiler Explorer - Missing "hello nasm" Example

### ISSUE THREAD

**Issue by TaiHusk** [compiler-explorer/compiler-explorer#6668]
### Describe the bug

The "hello nasm" example is missing from the "Save/Load" options under "Source Assembly" in Compiler Explorer. 

### Steps to reproduce

1. Visit [https://godbolt.org/](https://godbolt.org/)
2. Navigate to the "Source Assembly" tab.
3. Click on the "Save/Load" button.

### Expected behavior

The "hello nasm" example should be listed as an available option to load.

**Actual Behavior:**

The "hello nasm" example is not listed.

**Additional Information:**

* I do not believe the issue is related to the filename, but I could be mistaken.

### Reproduction link

Not applicable

### Screenshots

![Screenshot](https://github.com/compiler-explorer/compiler-explorer/assets/171867146/303087d9-c3df-469a-8826-b428929f451e)

### Operating System

N/A

### Browser version

N/A

**Comment by partouf** [comment]
The change you made is merged but is not live yet. When it is live, we will inform you in the PR
