### ISSUE TITLE
[BUG]: Code example of CUDA C++ compiles failed with clang rocm hipcc

### ISSUE THREAD

**Issue by Looong01** [compiler-explorer/compiler-explorer#6680]
### Describe the bug

The initial code example of CUDA C++ compiles failed with clang rocm hipcc

### Steps to reproduce

1. Visit https://godbolt.org/
2. choose UDA C++
3. choose compiler NVCC 12.4.1 and clang rocm-6.1.2
4. Compile the initial code example from the website and it shows Failed

### Expected behavior

Compiling successfully

### Reproduction link

https://godbolt.org/z/j6vjx8Wzz

### Screenshots

![image](https://github.com/compiler-explorer/compiler-explorer/assets/69568351/0d18229f-53f8-406c-8c74-14e13f00c741)

**Comment by partouf** [comment]
there was an issue with the libraries,
i managed to fix 6.0.2
but 6.1.2 remains broken, i do not know why

**Comment by partouf** [comment]
this was fixed a couple of days ago
