### ISSUE TITLE
Filter for Cfg-able compiler too strict

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#669]
base-compiler.js:
```
Compile.prototype.isCfgCompiler = function (compilerVersion) {
    return compilerVersion.includes("clang") || compilerVersion.indexOf("g++") === 0;
};
```

The second part could probably be made more correct by accepting any clang/gcc flavor, instead of having «any clang or g++».

**Comment by mattgodbolt** [comment]
Maybe related to #591?

**Comment by partouf** [comment]
Has been addressed a while ago but never closed.
