### ISSUE TITLE
[BUG]: llvm-mca uses -march from compiler invocation and fails

### ISSUE THREAD

**Issue by vient** [compiler-explorer/compiler-explorer#6709]
### Describe the bug

llvm-mca uses `-march` value from clang it was added from. Setting `-march=x86-64` in llvm-mca command line does not help. This makes using llvm-mca with any x86-64 architecture other than `x86-64` itself impossible.

### Steps to reproduce

1. write any c++ code on godbolt
2. use x86-64 Clang 18.1.0 with `-march=skylake -O2` options
3. add llvm-mca tool from clang pane

### Expected behavior

Expected: llvm-mca works
Actual: it shows error `/llvm-mca: invalid target 'skylake'` even with explicit options `-march=x86-64 -mcpu=skylake`

### Reproduction link

https://godbolt.org/z/15veYKoYa

### Screenshots

![image](https://github.com/user-attachments/assets/082618f9-3dc9-4871-9b47-9b107aede10a)

**Comment by partouf** [comment]
This was changed in https://github.com/compiler-explorer/compiler-explorer/pull/6682

Skylake is not an architecture. Clang might have some automatic detection of cpu's in -march, but it's not meant for that.

* You can get the possible options for `-march` by passing `-print-targets`
* You can get the possible options for `-mcpu` by passing `-mcpu=help`

**Comment by partouf** [comment]
Ah but Clang refuses to accept `-mcpu`

**Comment by partouf** [comment]
@peterwaller-arm I think we have to revert this change, unless you see a solution here

**Comment by vient** [comment]
Yes, for Clang the compiler, `-march` is a proper and only way to set specific x86-64 target. llvm-mca options do not match clang in that sense. Guess #6682 was not tested with x86-64 targets - I see that arm targets have `-mcpu` option but x86-64 ones do not, cpu is set via `-march` for them.

**Comment by peterwaller-arm** [comment]
Oh dear, this detail of X86 handling the flags differently (and not consistently between clang and MCA) isn't something I had accounted for, apologies.

This combination [of flags appears to work](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIM6SuADJ4DJgAcj4ARpjEEgEADqgKhE4MHt6%2B/qRJKY4CIWGRLDFxXAF2mA5pQgRMxAQZPn4VmPb5DLX1BIUR0bHxtnUNTVkVwz2hfSUD5QCUtqhexMjsHOYAzKHI3lgA1CYbbvXETACeh9gmGgCCm9u7mAdHyAoE6LR4UZfXd7deKSMewAblUAPoEZ4AET2b3QIBAJ3OhzcVFoqCYBFIey4ADYfhsrLdfsDUHh0HsqBBQcgIeZcXsmNi0Aw3iDwQR6XsonMDgB2Ik3PbC9m0yHETAKQ6CkWUkh7CApABemAhezw0L2Gml6uebkZADplZgIHMddZrHheSYBb9ZbKJVKAKwWPAmJ0ww4wpju13umEAKm5vrdHuldpFNqhEeFTE1jvDxL5UI4C1onCdvD83F4qE4bgtllhSxWT02PFIBE0qYWAGt/JIDbiAJzNrgADjMGg0zb5uI2XA2Tv0nEkWerpDzHF4ChAGkr1YWcFgSDQLASdFi5Eoa439DiwCkXD4dAIsVnECiE6ioXqZ04FZvzGIZwA8lFtFUqznSGu2IJXwYWh7w4LRSCwKIvGAY5aFoWcfywFhDGAcRQN4fAJWqUF4LAzBVCqLwzwfXhQjPdM0P0L5ThfDwsAnAhiDwFhiNIUFiCiZJMChTAkKMT4jEXPgDGABQADU8EwAB3V8EkYFj%2BEEEQxHYKQZEERQVHUCjdGPAwBNMSxrEoqJZ0gBZUASDp4NzNjGKwUzTVsNovzSFwGHcTxmj0YIpmKUo9FyVIBFGPxj0Cjpej82YnPaGoJhCvRKmqAQugaSL%2BjKIZugS483m6dKZjKBYFBLVYJDTDNxwoqc9lUdtcQAWlxSQ9mAZBkBxRsuAVXBCHlcs5l4b8tCXVdUHXTcyAoCBd0mlA9MPdsuHnGhaDPYgLyvCinzvFidpfd9PwcFi/0YAhAOAicIKgmC4JYxDkNQsCMJc7CJzwgiiJ/Ui2gnT4omos5aLWMCGKYli2I4pRuN4lDQlANCFjRJgRPEqSZLkn8FOEURxFU7GNLUCddACBaUELGx/oc8zLLSeCGqQlYEC9OrGuavYGoa4ZgEwTkNihVmwWahqvAYWsGFQSSGAa/ivFUBrgAYLwbNiOzJXgYrnOSvwIFcHLAncgr/LC5IgvSTyshNvI0iN6Kko6VLGgt0KYpclKJltzK8pGZ3Eo93yMvKxZljKrgKo4TNSGzMCatZpqWp2ZCcXbA0uANDQevwIhiAOMwB0GhdEbrfwnQNDZuyWvlWw0PPcXbPlSdHXhmOW%2Bdo9zTgZz0YbU1IZdEBAIhPG3CB6hEzgGeQBIvC9BRazOAxayeBn6mQZn%2Bbj5reDHhRlEMNohAQSX29/ca91icJWDWTeE4W5PU/T3hMCzkhyT0bGlLx6QCaUIntOyFgAgmBoF6tnAAEkwBQFhMCMBuIRVAGMwjwh/IA5gICX7EEQSxVBwDUC1HwNmCscJQidyGAQveYRaCH2PixIetAACS8JYLAhYJPTExBRa1krBKTAb95ySVOAkQS5FI4nynMw1hLBRAKgYpw3kN89iJyBB2B%2BGcICgP6nnY8ewPATX3LnDYZgC49zmMXMwjZWyWKsdY3EI4OBjijhOKcXd5wmL7jAAeSwCDTyxNNWa%2B5L5sE4AopRwB75p1whgt%2Bx4P64xUt/WQhMtJgRJqQARTAhE5nDqIpxnBXyER8XsVAVBar1Xjoou%2BKiIkKl0efHOmwjFDUXGY4c5EHFiNIbOVxzS7FmCqjHUhJiFhsRSM4SQQA%3D), as a workaround:

* compiler: `-march=x86-64 --target=x86_64-unknown-linux-gnu-
* MCA: --mcpu=skylake -march=x86-64`

Per the recommendation from https://maskray.me/blog/2022-08-28-march-mcpu-mtune:

> For the simplest case where only one option is desired, use -march= for x86 and -mcpu= for other targets.

... it appears x86 is the odd one out, so perhaps @vient's suggestion of doing something special on x86 is warranted. One minor thing though is that MCA won't accept all values you might pass to `march`, it really requires an -mcpu passed there.

**Comment by vient** [comment]
Yes, the problem is differentiating x86 targets from non-x86 ones. Don't know how to do it with `clang -march=xxx ...` alone, but maybe we already know it from godbolt context - llvm-mca has `x86-64` written after it.

> One minor thing though is that MCA won't accept all values you might pass to march, it really requires an -mcpu passed there.

Yes, for x86 and x86-64 targets you use compiler `-march` value if present, and change `march` to `mcpu` in it before passing to llvm-mca. llvm-mca does not need `-march` option in this case since it is just `x86` or `x86-64` for these targets, which is a default if using `x86` or `x86-64` toolchain respectively.

Besides, it might be nice to be able to override such deduced options (and also see them). For example, if I compile a generic `x86-64-v3` code, and want to see llvm-mca output for it with different target CPUs to understand how it performs on different machines. It is both a feature and a way to bypass this issue - manually overriding `march` would've helped me here.

**Comment by peterwaller-arm** [comment]
Candidate fix is up at #6710. No problem if you want to revert, I'll come and fix things up next week.

**Comment by topperc** [comment]
This also broke RISC-V where clang uses strings like -march=rv64gcv to specify the ISA. llvm-mca does not accept this for -march.

**Comment by vient** [comment]
Guess the best that can be done here is setting default parameters `-mtriple=xxx -mcpu=generic` then, where triple is already known or taken from compiler `-v` invocation.

**Comment by peterwaller-arm** [comment]
> This also broke RISC-V where clang uses strings like -march=rv64gcv to specify the ISA. llvm-mca does not accept this for -march.

Thanks for leaving this comment, it made me realise that clang's -march handling is quite different from that of llvm's -march handling, and passthrough of -march is not desired, so I'll drop that in #6710.

The logic that is needed is to pass through mcpu (it would also make sense to prefer mtune if specified, passing it to MCA as -mcpu).

> Guess the best that can be done here is setting default parameters -mtriple=xxx -mcpu=generic then

The intent in #6710 will now be to pass -mcpu=generic if -mcpu is not otherwise specified to neither MCA nor the compiler.
