### ISSUE TITLE
[BUG]: unifex/config.hpp seems to be out of date

### ISSUE THREAD

**Issue by ispeters** [compiler-explorer/compiler-explorer#6711]
### Describe the bug

[This link](https://godbolt.org/z/v1vYxreeW) is unexpectedly broken.

It looks like godbolt.org's copy of Unifex has most of [PR 616](https://github.com/facebookexperimental/libunifex/pull/616), but not the change to `include/unifex/config.hpp`.

It _could_ be because Unifex used to generate `config.hpp` from `config.hpp.in` while running CMake, but that changed in April with [PR 606](https://github.com/facebookexperimental/libunifex/pull/606).

### Steps to reproduce

1. browse to https://godbolt.org/z/v1vYxreeW

### Expected behavior

`#include <unifex/task.hpp>` ought to work

### Reproduction link

https://godbolt.org/z/v1vYxreeW

### Screenshots

Not applicable

**Comment by ispeters** [comment]
Looks like it's not just `config.hpp` that's out of date; https://godbolt.org/z/YfKva4qan shows that there are linker errors, too. The linker errors suggest that godbolt.org doesn't have `source/async_stack.cpp`, which was added in PR 616.

**Comment by partouf** [comment]
config issue is fixed as described in https://github.com/compiler-explorer/infra/pull/1395

issue described by @ispeters is caused by outdated binaries, possibly because of failing builds

The source is updated to August 5th, our latest build was at August 6th and failed on GCC trunk because of these errors: https://conan.compiler-explorer.com/getlogging/20240806072748

**Comment by ispeters** [comment]
@partouf, can you elaborate a little on what you think the current state of https://godbolt.org ought to be with respect to Unifex? [This link](https://godbolt.org/z/hGq44K7T6) is now much more broken than before compiler-explorer/infra#1395 was merged.

**Comment by partouf** [comment]
It depends on what the error was. I have physically deleted the config file from disk a couple minutes ago, so I can't see what error you mean

**Comment by partouf** [comment]
Ok, I see there should still be a config, but is supplied by the git repo. I have restored that version now.
New builds may or may not appear tommorrow.

**Comment by ispeters** [comment]
This excerpt of the error log from the linked build log suggests that `unifex/config.hpp` isn't being included:
```
In file included from /opt/compiler-explorer/libs/unifex/trunk/source/async_stack.cpp:17:
/opt/compiler-explorer/libs/unifex/trunk/include/unifex/tracing/async_stack.hpp:273:23: error: missing binary operator before token "("
  273 | #if UNIFEX_HAS_BUILTIN(__builtin_return_address)
      |                       ^
/opt/compiler-explorer/libs/unifex/trunk/include/unifex/tracing/async_stack.hpp:311:23: error: missing binary operator before token "("
  311 | #if UNIFEX_HAS_BUILTIN(__builtin_frame_address)
      |                       ^
```

I would expect [this preprocessor logic](https://github.com/facebookexperimental/libunifex/blob/main/include/unifex/config.hpp#L295-L299) to define `UNIFEX_HAS_BUILTIN`. `unifex/tracing/async_stack.hpp` doesn't directly include `unifex/config.hpp`, which I should probably fix, but it does include `unifex/coroutine.hpp`, which in turn includes the config header.

Also, you said this while I was composing this comment:
> I have physically deleted the config file from disk a couple minutes ago, so I can't see what error you mean

Maybe we just need a refresh of the source from Unifex's GitHub repo? We still need `unifex/config.hpp` to exist, it's just that it's now a file that's checked into our repo rather than being generated at cmake time from `unfiex/config.hpp.in`.

**Comment by partouf** [comment]
yes that

**Comment by ispeters** [comment]
> Ok, I see there should still be a config, but is supplied by the git repo. I have restored that version now. New builds may or may not appear tommorrow.

Thanks! What's the best way for me to check on the status? Just try to use Unifex from https://godbolt.org?

**Comment by partouf** [comment]
You can use the headers, but you won't be able to link/execute against it for about 10-12 hours. Our buildsystem will kick off in about 5 hours and it will take some time to grind through all the libraries and compilers.

**Comment by partouf** [comment]
Build failed because of warnings being treated as errors: https://conan.compiler-explorer.com/getlogging/20240817054731

For Boost we recently "solved" this by search and replacing through the cmake files https://github.com/compiler-explorer/infra/blob/main/bin/yaml/libraries.yaml#L123

Though I'm not a fan of that approach, we could do that here too

I think it's only set here https://github.com/facebookexperimental/libunifex/blob/main/cmake/unifex_env.cmake#L27

**Comment by ispeters** [comment]
@partouf, I hope that facebookexperimental/libunifex#625 will fix your build of Unifex; please let me know the results of the next automated build that you notice. If there's a way for me to check on the status myself, I'd be happy to do that, too.

**Comment by ispeters** [comment]
@partouf, I *think* this is resolved, but I can't be certain I've checked on all your builds of Unifex.

I poked around at https://conan.compiler-explorer.com/ and it looks like the Unifex builds are good; I also tried a couple of godbolt.org links that used to be broken but are now working.

If you don't see any broken builds then I'm happy to close this issue.

**Comment by partouf** [comment]
Right. I see issues with Clang, but I believe that might be my fault and will attempt to fix that the coming days.
