### ISSUE TITLE
CMake support for MSVC

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#6715]
Mentioned in https://hachyderm.io/@DanielaKEngert/112830956778655615

> In most cases, there seems to be no output generated in the MSVC compile (CMake once complained about a missing C compiler while the C++ compiler is detected). In all cases, the compile process times out.

Seems only related to CMake (wihch may not yet be supported?) Am asking the OP for more details.

**Comment by mattgodbolt** [comment]
Confirmed CMake only: https://godbolt.org/z/14qMdr7qW -

**Comment by partouf** [comment]
Cmake for Windows is insanely slow, also with mingw. It's a hard problem to solve, I've already attempted some workarounds, but I'm not sure it's doable without hacking cmake

**Comment by mattgodbolt** [comment]
Thanks Partouf; I'll let Dani know. Much appreciated!

**Comment by mattgodbolt** [comment]
Closing as this isn't a lack of support, but just a performance issue that we'll no doubt have to solve for a number of things.
