### ISSUE TITLE
[BUG]: Cppfront compiles failing apparently due to new header 

### ISSUE THREAD

**Issue by gregmarr** [compiler-explorer/compiler-explorer#6721]
### Describe the bug

Attempting to build any code on cpp2.godbolt.org results in this error when compiling the cpp1 code.
```
raw.githubusercontent.com/hsutter/cppfront/main/include/cpp2util.h:2594:10: fatal error: 'cpp2regex.h' file not found
```
This file was newly created on Saturday.

### Steps to reproduce

* Go to cpp2.godbolt.org and enter any valid cpp2 code, such as `main: () = {}`.
* View the (Compiler # 2 output) pane.

### Expected behavior

Successful build.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by partouf** [comment]
cppfront has a bit of an awkward buildstep where we have to manually compile a cpp and copy some headers

https://github.com/compiler-explorer/misc-builder/blob/main/misc/build-cppfront.sh#L65

The new file will need to be added there

**Comment by gregmarr** [comment]
It's probably better going forward to copy the entire directory.

**Comment by gregmarr** [comment]
It's still broken, unfortunately.  There must be something else needed.

**Comment by gregmarr** [comment]
It's working now.
