### ISSUE TITLE
[REQUEST]: View Rust's LLVM IR and MIR in the diff view

### ISSUE THREAD

**Issue by tgross35** [compiler-explorer/compiler-explorer#6726]
### Is your feature request related to a problem? Please describe

Rust has "LLVM IR" and "Rust MIR" options that can be enabled from the compiler. Sometimes it would be convenient to view IR in the diff view, but there isn't a convenient option:

<img width="466" alt="image" src="https://github.com/user-attachments/assets/8395e4f5-03eb-4845-b25b-7bc6ca5a317f">

### Describe the solution you'd like

Add additional dropdown option alongside "assembly", "compiler stdout", etc, that can select the LLVM IR or Rust MIR for a compiler.

### Describe alternatives you've considered

If flags like `--emit=llvm-ir -o-` could be passed, that would allow printing the data to compiler stdout, which can then be viewed in the diff. However, `-o` is rejected since it is already given, and only `--emit=llvm-ir` is rejected because it doesn't 

### Additional context

Not applicable

**Comment by narpfel** [comment]
`--emit=llvm-ir` works for me: https://godbolt.org/z/dzW8cWvPd

Could you share a link where it doesn’t work?

**Comment by dkm** [comment]
@narpfel that works yes, but it's more a workaround than the intended use. If you also want to see assembly, you'd need to create a new compiler...

**Comment by tgross35** [comment]
> `--emit=llvm-ir` works for me: https://godbolt.org/z/dzW8cWvPd
> 
> Could you share a link where it doesn’t work?

...I have no clue, I must have done something differently because I was getting errors before.

In any case thanks for the fix, that is great to have!
