### ISSUE TITLE
Add Crystal support

### ISSUE THREAD

**Issue by faustinoaq** [compiler-explorer/compiler-explorer#673]
Hi I like this tool 👍 

Would be possible to add support for [The Crystal Programming Language](https://crystal-lang.org).?

Crystal is a self-hosted programming language with friendly syntax, static type checking and modern stdlib. It compiles into efficient, easy-to-distribute native code.

![crystal](https://i.imgur.com/pHwLnIp.gif "crystal")

**Comment by mattgodbolt** [comment]
Thanks for this request, and the kind words.

We're in the process of making it easier to add languages. That said, adding a language is usually fairly straightforward. We've recently added Pascal in only a few pull requests. We have made a document explaining some of the things needed here: https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/AddingACompiler.md if that helps.

Hopefully you'll be inspired to give making a PR both for this site and for the `compiler-explorer-image` site that hosts all the compilers!

**Comment by r00ster91** [comment]
I would like to try this but I'm a bit confused by what guide to follow.
https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/AddingALanguage.md
or https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/AddingACompiler.md?
Crystal is both a compiler and a language.
