### ISSUE TITLE
[BUG]: Carbon (tcmalloc) needs access to /sys/devices/system/cpu/possible

### ISSUE THREAD

**Issue by jonmeow** [compiler-explorer/compiler-explorer#6734]
### Describe the bug

Carbon is trying to use tcmalloc. That reads `/sys/devices/system/cpu/possible` at startup. (if you're curious, [here](https://github.com/google/tcmalloc/blob/8febb4b4da2ab3b04862a8676fb5b506ef90aa42/tcmalloc/internal/sysinfo.cc#L112))

Since the file is not whitelisted, https://carbon.compiler-explorer.com/ will currently crash.

This was reported to us in https://github.com/carbon-language/carbon-lang/issues/4176, and we've temporarily disabled tcmalloc in https://github.com/carbon-language/carbon-lang/pull/4177, but would like to figure out a long-term fix compatible with compiler explorer.

I think this involves adding to https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/nsjail/compilers-and-tools.cfg:

```
mount {
    src: "/sys/devices/system/cpu"
    dst: "/sys/devices/system/cpu"
    is_bind: true
}
```

This particular suggestion stems similar whitelisting in:
https://github.com/google/sandboxed-api/blob/main/sandboxed_api/sandbox2/policybuilder.cc#L884 [and so hopefully is low-risk]

An alternative would be to modify https://github.com/compiler-explorer/carbon-builder/blob/main/build/build.sh to disable tcmalloc, but that's not straightforward... Also, we'd ideally like to have compiler explorer shift towards using Carbon release builds, which should have tcmalloc enabled going forward.

tcmalloc was about a 10% improvement for Carbon, so we'd like to keep it. I'd also checked with tcmalloc about adding a fallback if the /sys file was unavailable, but they're concerned that could lead to silent memory corruption (related discussion: https://github.com/google/tcmalloc/issues/245)

### Steps to reproduce

1. Go to https://carbon.compiler-explorer.com/
2. Look at compiler output

### Expected behavior

Should compile

### Reproduction link

https://carbon.compiler-explorer.com/z/aPq4jW934

### Screenshots

Just copying compiler output:

```
1 external/tcmalloc~/tcmalloc/internal/sysinfo.cc:124] CHECK in NumPossibleCPUsNoCache: cpus.has_value() (false) 
Program terminated with signal: SIGSEGV
Compiler returned: 139
```

**Comment by chandlerc** [comment]
Sent a PR implementing the suggestion in case that helps.

**Comment by mattgodbolt** [comment]
Thanks all; will do a release shortly to pick this up.

**Comment by mattgodbolt** [comment]
@jonmeow @chandlerc this change and fix is now live

**Comment by chandlerc** [comment]
Awesome, re-landing tcmalloc, hopefully without the breakage this time!

**Comment by jblazquez** [comment]
Thanks for the fixes, Chandler! We just run into this issue when trying to run an application that uses `tcmalloc` in an AWS Lambda.

Your commit from Aug 3 solved it.

**Comment by jonmeow** [comment]
@jblazquez Glad it helped! FWIW, ckennelly
 also added a workaround to tcmalloc (https://github.com/google/tcmalloc/commit/883c38cdb04bda6918583282563d955e421db623), so it's possible now that updating the tcmalloc version would help.

**Comment by jblazquez** [comment]
Yeah, we updated the version of `tcmalloc` to the latest commit as of today and that fixed it.
