### ISSUE TITLE
[BUG]: Disassembly is showing unsigned entities as signed 

### ISSUE THREAD

**Issue by mark4th** [compiler-explorer/compiler-explorer#6752]
### Describe the bug

The disassembly for the following code has the 0xa5 disassembled as -91.  The disassembly should honor the data type and display the value unsigned.

#include <stdint.h>

int foo(uint8_t c)
{
    if (c == 0xa5)
    {
        return -1;
    }
}

### Steps to reproduce

enter the above code into the compiler explorer page

### Expected behavior

foo(unsigned char):
        push    rbp
        mov     rbp, rsp
        mov     eax, edi
        mov     BYTE PTR [rbp-4], al
        cmp     BYTE PTR [rbp-4], 0xa5 or 165 but asm IMHO should *ALWAYS* be printed in hex.
        jne     .L2
        mov     eax, -1
        jmp     .L4
.L2:
        ud2
.L4:
        pop     rbp
        ret

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by partouf** [comment]
We're only relaying here what the compiler says (by default it is not disassembly, it is assembly as the compiler would send to the assembler).
Aside from filtering we do not alter it's contents.
(Regardless, for the assembler it does not matter if something is signed or unsigned, it's all the same)

You can use the option under `Output` -> `Compile to binary object` to see how it looks like to `objdump` which will disassemble and show you the hex value.

**Comment by jeremy-rifkin** [comment]
Hi, just to add on to partouf's comments here gcc is deciding to output that as -91 in its output (you can test this locally with `gcc -c test.c -S -o test.s -masm=intel`). We could maybe update the tooltip to show an 8-bit signed value
![image](https://github.com/user-attachments/assets/4939eefc-29df-4048-86ba-2c0a4a8ef4bc)
