### ISSUE TITLE
[COMPILER REQUEST]: Show dump of the Triton JIT compiler in PyTorch.

### ISSUE THREAD

**Issue by aregm** [compiler-explorer/compiler-explorer#6778]
### Compiler name

Triton 

### Compiler version

3.x

### Compiler language

Triton/PyTorch

### Compiler homepage

https://github.com/openai/triton

### Motivation

For DL model optimizations, it will be very helpful to get the LLVM and MLIR dumps of the Triton JIT compiler, as they are dumped into the .triton/cache directory and controlled by MLIR_ENABLE_DUMP=1 (or kernelName) and LLVM_IR_ENABLE_DUMP=1 for all LLVM passes.

**Comment by parsifal-47** [comment]
It looks like a duplicate of:
https://github.com/compiler-explorer/compiler-explorer/issues/5530

**Comment by aregm** [comment]
> It looks like a duplicate of: #5530

Yes, you're correct - let's close it as a duplicate.
