### ISSUE TITLE
[COMPILER REQUEST]: New architecture LoongArch LLVM support

### ISSUE THREAD

**Issue by specialpointcentral** [compiler-explorer/compiler-explorer#6794]
### Compiler name

LLVM Clang

### Compiler version

17.0.1

### Compiler language

C++, LLVM IR, C, ASM

### Compiler homepage

https://releases.llvm.org/17.0.1/docs/ReleaseNotes.html

### Motivation

LoongArch is a new RISC ISA, which is a bit like MIPS or RISC-V, and today Linux/GCC/LLVM etc. support LoongArch. So I want to support this new architecture.

GCC has been added in #4162.

**Comment by dkm** [comment]
Should be a trivial change to the builder + some config.

**Comment by dkm** [comment]
In fact, only a config change is needed for trunk and probably since 17 as pointed at in PR description.

**Comment by specialpointcentral** [comment]
> In fact, only a config change is needed for trunk and probably since 17 as pointed at in PR description.↳

I have added some config settings in #6793, but I am not sure if any other parts need to be modified. :)
