### ISSUE TITLE
[BUG]: mp-units examples do not compile

### ISSUE THREAD

**Issue by mjacobse** [compiler-explorer/compiler-explorer#6802]
### Describe the bug

The examples https://compiler-explorer.com/z/81Ev7qhTd and https://compiler-explorer.com/z/Tsesa1Pvq given in the description of the mp-units library do not compile. Those examples use mp-units trunk which since the creation of the examples appears to have introduced breaking changes. Manually changing the version to 2.1.0 makes the examples compile again.

### Steps to reproduce

Search for the mp-units library and follow the link to either of the examples.

### Expected behavior

The examples compile.

The first example seems easy enough to fix, only the path of the header appears to have changed: https://compiler-explorer.com/z/d4qWza16q
The second example seems to need a few more changes as it looks like text output was changed quite a bit. Appears to work with https://compiler-explorer.com/z/7xGe6zvYs but I am not entirely confident this is exactly in the spirit of the example. Perhaps @mpusz has some input.

Would it perhaps be an idea to fix the library version in the examples to a specific version instead of using trunk to avoid breakage in the future?

### Reproduction link

https://compiler-explorer.com/z/81Ev7qhTd

### Screenshots

Not applicable

**Comment by partouf** [comment]
The example links can be changed here: https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/c%2B%2B.amazon.properties#L4727

But yes, it would be more ideal to have links that have fixed versions of the library selected in them.

**Comment by mpusz** [comment]
@mjacobse, Those two examples were taken from our docs. A working version can always be found at https://mpusz.github.io/mp-units/2.3/getting_started/look_and_feel.
