### ISSUE TITLE
[BUG]: gcc 8 on x86 linker warnings unsupported GNU_PROPERTY_TYPE

### ISSUE THREAD

**Issue by Arghnews** [compiler-explorer/compiler-explorer#6803]
### Describe the bug

An `int main() { return 0; }` c++ program on gcc 8.1-8.5 compiles fine but produces these warnings

```
ASM generation compiler returned: 0
/opt/compiler-explorer/gcc-8.5.0/bin/../lib/gcc/x86_64-linux-gnu/8.5.0/../../../../x86_64-linux-gnu/bin/ld: warning: /lib/x86_64-linux-gnu/crt1.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
/opt/compiler-explorer/gcc-8.5.0/bin/../lib/gcc/x86_64-linux-gnu/8.5.0/../../../../x86_64-linux-gnu/bin/ld: warning: /lib/x86_64-linux-gnu/libm.so.6: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
/opt/compiler-explorer/gcc-8.5.0/bin/../lib/gcc/x86_64-linux-gnu/8.5.0/../../../../x86_64-linux-gnu/bin/ld: warning: /lib/x86_64-linux-gnu/libmvec.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
/opt/compiler-explorer/gcc-8.5.0/bin/../lib/gcc/x86_64-linux-gnu/8.5.0/../../../../x86_64-linux-gnu/bin/ld: warning: /lib/x86_64-linux-gnu/libc.so.6: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
Execution build compiler returned: 0
Program returned: 0
```

https://godbolt.org/z/h16o7195z

This is the same as issue #6622 (not sure if policy here is to comment on old bug or open new one, so opened a new one)

### Steps to reproduce

Visit https://godbolt.org/z/h16o7195z and observe output

### Expected behavior

Expected not to produce this

### Reproduction link

https://godbolt.org/z/h16o7195z

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
These warnings will most probably be solved by using a more modern binutils (same as #6622). 
One could have reasonable doubts about this course of action as we stop 'faithfully reproducing' the old gcc 8 toolchain, but personally I'm ok with it: the old linker complains about being unable to fully process *modern* binaries, from `/lib/x86_64-linux-gnu` (outside any `/opt/compiler-explorer` environment).

**Comment by dkm** [comment]
Yes that's a common issue with old binutils on recent system. Updating should be ok :+1:
