### ISSUE TITLE
widberg nightly has been failing for a long time

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#6829]
https://github.com/compiler-explorer/compiler-workflows/actions/runs/10692531173/job/29641120035

```
4840   │ 2024-09-04T00:32:12.5006221Z CMake Error at /root/llvm-project/libcxxabi/CMakeLists.txt:51 (message):
4841   │ 2024-09-04T00:32:12.5007453Z   LIBCXXABI_USE_LLVM_UNWINDER is set to ON, but libunwind is not specified in
4842   │ 2024-09-04T00:32:12.5008433Z   LLVM_ENABLE_RUNTIMES.
4843   │ 2024-09-04T00:32:12.5009155Z -- Configuring incomplete, errors occurred!
4844   │ 2024-09-04T00:32:12.5009734Z 
4845   │ 2024-09-04T00:32:12.5009741Z 
```

I guess we need to adjust something. @widberg do you have an idea? Looks like `libunwind` needs to be enabled...

**Comment by widberg** [comment]
I'll take a look at this soon

**Comment by widberg** [comment]
Oops I rebased my fork onto a newer Clang and didn't realize libunwind is required to build libc++ now (https://github.com/compiler-explorer/clang-builder/commit/ce1b0554ba6fad6d6a574f667aa39176f6f9cb5d). Adding `LLVM_ENABLE_RUNTIMES+=";libunwind"` should hopefully fix it. I can make a PR on [clang-builder](https://github.com/compiler-explorer/clang-builder) now.

**Comment by dkm** [comment]
Thanks @widberg for fixing it :+1:

**Comment by dkm** [comment]
Still KO :(
```
6116   │ 2024-09-06T00:23:25.5330297Z /root/llvm-project/libcxx/src/ryu/d2fixed.cpp:85:27: error: expected '('
6117   │ 2024-09-06T00:23:25.5332019Z    85 |   const uint32_t __shifted = static_cast<uint32_t>(__multiplied >> 29);
6118   │ 2024-09-06T00:23:25.5332946Z       |                           ^
6119   │ 2024-09-06T00:23:25.5333804Z       |                           (
6120   │ 2024-09-06T00:23:25.5334972Z /root/llvm-project/libcxx/src/ryu/d2fixed.cpp:85:28: error: expected unqualified-id
6121   │ 2024-09-06T00:23:25.5336260Z    85 |   const uint32_t __shifted = static_cast<uint32_t>(__multiplied >> 29);
6122   │ 2024-09-06T00:23:25.5337307Z       |                            ^
6123   │ 2024-09-06T00:23:25.5338463Z /root/llvm-project/libcxx/src/ryu/d2fixed.cpp:87:54: error: expected expression
6124   │ 2024-09-06T00:23:25.5339784Z    87 |   return static_cast<uint32_t>(__vLo) - 1000000000 * __shifted;
6125   │ 2024-09-06T00:23:25.5340684Z       |                                                      ^
6126   │ 2024-09-06T00:23:25.5341387Z 3 errors generated.
```
https://github.com/compiler-explorer/compiler-workflows/actions/runs/10729978726/job/29757584693

**Comment by widberg** [comment]
The identifier name used there, `__shifted`, is a keyword when my extensions are enabled. Annoying but should be easy to fix. Clearly I need to be more thorough when testing and do a libc++ bootstrap build.

**Comment by dkm** [comment]
No worries, I'm just trying to keep track of nightlies that are failing. If it's handled then that's fine. We can disable the build for some time if you know you won't have time to fix, easy :+1: . If you're going to fix this in the coming days, then we don't change anything and wait for the build to pass again :+1: . The goal being to avoid having useless build wasting resource for something that won't ever be fixed.
Thanks !

**Comment by widberg** [comment]
I think I fixed the build error but now I am seeing

```console
2024-09-09T00:40:26.5731934Z ##[warning]You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 0 MB
2024-09-09T00:40:26.7752456Z CMake Error at tools/clang/tools/driver/cmake_install.cmake:57 (file):
2024-09-09T00:40:26.7753453Z   file INSTALL cannot copy file "/root/build/bin/clang-18" to
2024-09-09T00:40:26.7757477Z   "/root/staging/bin/clang-18": Success.
```
https://github.com/compiler-explorer/compiler-workflows/actions/runs/10764130000/job/29846483875

What do I need to do to fix this?

**Comment by partouf** [comment]
Ah so thats the CI instance we've been getting alerts about.
I think you should have 128GiB, so I'm curious as to how you managed to fill that up.

@mattgodbolt is the expert on the ce-ci instances, I'm not sure what the options are here

**Comment by mattgodbolt** [comment]
Oh yikes. I can update the amount of disk space on our CI instances for sure though

**Comment by widberg** [comment]
If the limit is 128GiB I am also confused about how I managed to fill that. On my local machine the entire repository with built clang and libc++ included is ~34GiB and the clang-18 executable is ~3.4G. Assertions are enabled and the build type is RelWithDebInfo so I would expect some bloat but not that much. The last few runs all failed on that same install copy step. Is there some configuration I need to set or are artifacts getting left over from previous runs? If it's too much trouble you can disable the build.

**Comment by partouf** [comment]
I added a `df -h /` just before building:

```
  Filesystem      Size  Used Avail Use% Mounted on
  overlay         124G   10G  114G   9% /
```

**Comment by mattgodbolt** [comment]
This is super weird: what on earth has this branch got checked in that's so huge? When we run out of disk space we've just checked out the code it seems (like Partouf shows above).

I'm going to try and repro on my local workstations.

**Comment by mattgodbolt** [comment]
Locally; just after a checkout but before cmake:
```
# du -sh llvm-project/
1.3G	llvm-project/
```

before `ninja build`
```
root@8ffff63dd9ee:~# du -sh llvm-project/ build
1.3G	llvm-project/
25M	build
```

**Comment by mattgodbolt** [comment]
Building just fine on my laptop; weird!!

Spotted in the `papertrail` logs for the node:
```
Sep 12 00:29:40Z [ip-172-30-5-153](https://my.papertrailapp.com/systems/ip-172-30-5-153/events?focus=1770683139808313345&selected=1770683139808313345) [systemd](https://my.papertrailapp.com/groups/1243314/events?q=program%3Asystemd&focus=1770683139808313345&selected=1770683139808313345) Finished Daily apt upgrade and clean activities.
Sep 12 00:31:06Z [ip-172-30-5-153](https://my.papertrailapp.com/systems/ip-172-30-5-153/events?focus=1770683499205640193&selected=1770683499205640193) [kernel](https://my.papertrailapp.com/groups/1243314/events?q=program%3Akernel&focus=1770683499205640193&selected=1770683499205640193) [ 1694.207280] INFO: task cmake:29445 blocked for more than 120 seconds.
Sep 12 00:31:06Z [ip-172-30-5-153](https://my.papertrailapp.com/systems/ip-172-30-5-153/events?focus=1770683499205640194&selected=1770683499205640194) [kernel](https://my.papertrailapp.com/groups/1243314/events?q=program%3Akernel&focus=1770683499205640194&selected=1770683499205640194) [ 1694.209665]       Not tainted 5.15.0-1050-aws #55~20.04.1-Ubuntu
Sep 12 00:31:06Z [ip-172-30-5-153](https://my.papertrailapp.com/systems/ip-172-30-5-153/events?focus=1770683499205640195&selected=1770683499205640195) [kernel](https://my.papertrailapp.com/groups/1243314/events?q=program%3Akernel&focus=1770683499205640195&selected=1770683499205640195) [ 1694.211884] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Sep 12 00:31:06Z [ip-172-30-5-153](https://my.papertrailapp.com/systems/ip-172-30-5-153/events?focus=1770683499218223109&selected=1770683499218223109) [kernel](https://my.papertrailapp.com/groups/1243314/events?q=program%3Akernel&focus=1770683499218223109&selected=1770683499218223109) [ 1694.214707] task:cmake           state:D stack:    0 pid:29445 ppid: 29443 flags:0x00000220
```

**Comment by mattgodbolt** [comment]
disc space log:
![image](https://github.com/user-attachments/assets/a4aa73c3-86e1-4665-8114-eb2f4f45cc01)

**Comment by mattgodbolt** [comment]
so it looks like it's slowly losing disk space over 20m, not just the chekcout (I thnk? maybe?)

**Comment by mattgodbolt** [comment]
(still building localy, and we'll see how it goes...)

**Comment by mattgodbolt** [comment]
```
[991/3795] Building CXX object lib/Transforms.../CMakeFiles/LLVMObjCARCOpts.dir/ObjCARC.cpp.o^Z
[1]+  Stopped                 ./build.sh widberg-main
root@8ffff63dd9ee:~# du -sh *
1.5G	build
5.0K	build-circt.sh
5.0K	build-parmexpr.sh
9.0K	build.sh
1.3G	llvm-project
29K	patches
9.0K	staging
```

**Comment by mattgodbolt** [comment]
so far so no pathological disk space, which is super odd!

**Comment by partouf** [comment]
maybe /tmp nonsense?

**Comment by mattgodbolt** [comment]
I dunno - my laptop OOmed half way through and no more than 42GB of HD used at all

**Comment by mattgodbolt** [comment]
noting in /tmp either. I don't know what's going on here! I'll try again...

**Comment by mattgodbolt** [comment]
Tactically I'll bump the size to 200GB though

**Comment by partouf** [comment]
Hi @widberg - Matt's been doing some tests, and we temp increased diskspace to 200gigs, but it still looks to go beyond that because of:
* Massively large binaries built (total somewhere around 80G)
* Installing (so copy everything to put everything in its place ready to zip up)
* Tarxzipping those large binaries

So basically by the time it's done installing, there's only 17GiB left to zip up the binaries and it goes out of space there at the moment

Our question is; do you really need RelWithDebInfo? Do you get something out of that that you can't get with Release?

Because even if we did do some trickery; enlarge disk, make clean after install, something like that, I'm not sure the actually installed version of the compiler on our instances is going to play nice with CE.

**Comment by widberg** [comment]
I suppose Release would be fine if that's the problem. I can always run the compiler locally to get a better trace if it crashes on the site.

**Comment by partouf** [comment]
Release works without any issues, have installed the latest now

**Comment by widberg** [comment]
Thank you all for resolving this and sorry for the trouble.
