### ISSUE TITLE
[BUG]: code that uses Unifex won't link

### ISSUE THREAD

**Issue by ispeters** [compiler-explorer/compiler-explorer#6832]
### Describe the bug

This might be a regression of #6711, although it might be worse than that.

A relatively simple TU that uses Unifex fails to link with Clang 18 (see https://godbolt.org/z/WEGo49TPG):
> `/opt/compiler-explorer/gcc-13.2.0/lib/gcc/x86_64-linux-gnu/13.2.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -lunifex: No such file or directory`

With Clang (trunk), the same TU complains about -fPIE (see https://godbolt.org/z/WdM7dEPox):
> `/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/15.0.0/../../../../x86_64-linux-gnu/bin/ld: /app/unifex/lib/libunifex.a(inplace_stop_token.cpp.o): relocation R_X86_64_32 against '.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE`
> `/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/15.0.0/../../../../x86_64-linux-gnu/bin/ld: failed to set dynamic section sizes: bad value`

Clang 14 does better with a simpler TU (see https://godbolt.org/z/9KEbaTT1x, the error output is expected because the program is broken), but breaks again with the earlier TU (see https://godbolt.org/z/7xG65qsb6):
> `/opt/compiler-explorer/gcc-11.2.0/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../x86_64-linux-gnu/bin/ld: /opt/compiler-explorer/gcc-11.2.0/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../x86_64-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 50`
> `/tmp/example-3b4cb2.o: in function '_root_and_frame_ref':`
> `/opt/compiler-explorer/libs/unifex/trunk/include/unifex/tracing/inject_async_stack.hpp:98: undefined reference to 'unifex::detail::ScopedAsyncStackRoot::ScopedAsyncStackRoot(unifex::frame_ptr, unifex::instruction_ptr)'`
> `/opt/compiler-explorer/gcc-11.2.0/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../x86_64-linux-gnu/bin/ld: /tmp/example-3b4cb2.o: in function '~_root_and_frame_ref':`
> `…`

Disabling async stack support allows Clang 14 to get further (see https://godbolt.org/z/WP8rEr3MT), but fixing the program bug by adding more code (see https://godbolt.org/z/hrcGza36G) reintroduces the linker errors:
> `/opt/compiler-explorer/gcc-11.2.0/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../x86_64-linux-gnu/bin/ld: /opt/compiler-explorer/gcc-11.2.0/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../x86_64-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 50`
> `/tmp/example-820d67.o: in function 'initial_stack_root':`
> `/opt/compiler-explorer/libs/unifex/trunk/include/unifex/sync_wait.hpp:125: undefined reference to 'unifex::detail::ScopedAsyncStackRoot::ScopedAsyncStackRoot(unifex::frame_ptr, unifex::instruction_ptr)'`
> `/opt/compiler-explorer/gcc-11.2.0/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../x86_64-linux-gnu/bin/ld: /tmp/example-820d67.o: in function '~initial_stack_root':`

GCC trunk breaks (with what looks like a bug in Unifex), but GCC 14.2 works (https://godbolt.org/z/14xW1z6x6).

The linker errors make it look like maybe the Compiler Explorer CI is failing to produce `libunifex.a` (or, in the case of Clang trunk, maybe producing it incorrectly), but I'm not sure if/how I can check on recent build status.

### Steps to reproduce

There are a bunch of godbolt.org links in the description that all show the bug, but they boil down to:
1. visit https://godbolt.org
2. add the libunifex library
3. choose your favourite Clang as the compiler
4. make any non-trivial use of Unifex, for example:
```
#include <unifex/async_scope.hpp>
#include <unifex/task.hpp>

unifex::task<int> asyncMain(unifex::async_scope& scope_) {
    co_return 42;
}
int main() {
    unifex::async_scope scope;
    return 0;
}
```

### Expected behavior

Uses of Unifex should not prevent linking with supported versions of Clang (i.e. Clang 12+).

### Reproduction link

https://godbolt.org/z/WEGo49TPG

### Screenshots

Not applicable

**Comment by partouf** [comment]
this is fixed for clang18, the rest of the clang compilers will fix themselves over the rest of the week

**Comment by ispeters** [comment]
Thanks!
