### ISSUE TITLE
[BUG]: Attributes filtered out when rustc prints source code

### ISSUE THREAD

**Issue by bjorn3** [compiler-explorer/compiler-explorer#6847]
### Describe the bug

If I tell rustc to produce source code, by all attributes are filtered out unless the "comments" filter is disabled.

### Steps to reproduce

1. Select Rust as language
2. Use `#[inline] fn foo() {}` as source.
3. Pass `-Zunpretty=expanded` as rustc argument.
4. The output strips all attributes when the "comments" filter is enabled as is the default:

```rust
use std::prelude::rust_2021::*;
extern crate std;
fn foo() {}
```

### Expected behavior

The following is shown:

```rust
#![feature(prelude_import)]
#[prelude_import]
use std::prelude::rust_2021::*;
#[macro_use]
extern crate std;
#[inline]
fn foo() {}
```

### Reproduction link

https://rust.godbolt.org/z/qqzWs5fdd

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
I'm afraid the compiler-pane filters are tailored to filter *assembly* in various ISAs. 
IIUC this is an undocumented switch that does macro expansion? Something like the C/C++ preprocessor?   If so - perhaps the right thing to do would be add a 'preprocessor' item to the rust 'Add..' dropdown:
![image](https://github.com/user-attachments/assets/20ccf201-8772-4b09-8caf-08e06480eee0)

Can you say what is the status of this switch? Is there a supported way to achieve the same effect?

**Comment by OfekShilon** [comment]
> It is a `-Z` flag, which means that it is unstable and only available on nightly. 

That could be a problem. We change dropdown contents for different languages and compiler groups, but currently not for a single compiler. It might be hackable in some odd way (like separating 'nightly' to its own group) but not sure whether the added value justifies it.

I'll wait for some more opinions.

**Comment by OfekShilon** [comment]
> It is a `-Z` flag, which means that it is unstable and only available on nightly. 

This could have been a problem, but now I'm not sure this is the case.  Here's `-Zunpretty=expanded` on rust 1.72: https://rust.godbolt.org/z/dG1G8zo6x

**Comment by bjorn3** [comment]
For me that link shows an error about using unstable options, as expected.

**Comment by OfekShilon** [comment]
The flag seems operational since rust 1.25. Maybe we can work with that.

**Comment by OfekShilon** [comment]
Actually in my local instance I do get `error: the option `Z` is only accepted on the nightly compiler`, I'm guessing rust was installed differently somehow? Checking.

**Comment by bjorn3** [comment]
Did you use a nightly rustc?

**Comment by OfekShilon** [comment]
@bjorn3 , your repro link uses non-nightly rust. Turns out that for nightly rust we already expose macro expansion: 
![image](https://github.com/user-attachments/assets/1ef9acca-b2a0-4763-9cb0-67335b983b64)
