### ISSUE TITLE
carbon is failing

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#6855]
```
 498   │ 2024-09-14T00:15:39.5584321Z Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
 499   │ 2024-09-14T00:15:39.5595949Z In file included from testing/base/global_exe_path.cpp:9:
 500   │ 2024-09-14T00:15:39.5597034Z In file included from ./common/check.h:8:
 501   │ 2024-09-14T00:15:39.5598786Z ./common/check_internal.h:40:24: error: unknown attribute 'noinline' ignored [-Werror,-Wunknown-attributes]
 502   │ 2024-09-14T00:15:39.5617932Z [[noreturn, gnu::cold, clang::noinline, clang::preserve_most]] auto CheckFail(
 503   │ 2024-09-14T00:15:39.5619566Z                        ^~~~~~~~~~~~~~~
 504   │ 2024-09-14T00:15:39.5620681Z 1 error generated.
 505   │ 2024-09-14T00:15:39.7000877Z Use --verbose_failures to see the command lines of failed build steps.
 506   │ 2024-09-14T00:15:39.7288371Z INFO: Elapsed time: 65.346s, Critical Path: 4.02s
 507   │ 2024-09-14T00:15:39.7422707Z INFO: 1144 processes: 811 internal, 333 processwrapper-sandbox.
 508   │ 2024-09-14T00:16:00.5530219Z ERROR: Build did NOT complete successfully
 509   │ 2024-09-14T00:16:00.5540864Z ##[error]Process completed with exit code 1.
```

https://github.com/compiler-explorer/compiler-workflows/actions/runs/10857767031/job/30134751061

@jonmeow, as a Carbon folk, do you have an idea of how we can fix this? Looks like a compiler option issue... Maybe we should use a different version or "vendor" (not sure if we're using gcc here)

**Comment by jonmeow** [comment]
It looks like you're using clang-14 to build (in the log, `/home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/clang++`). Is there an easy way to replace that with clang-16 or later?

While we could hide the attribute as a workaround, we're trying to use C++20 features, so clang-14 might encounter more issues.

@chandlerc FYI

**Comment by dkm** [comment]
@jonmeow oh yes, we can probably switch clang version. Thanks for the reply, I'll fix that shortly!

**Comment by dkm** [comment]
Hopefully, next run is :heavy_check_mark:

**Comment by dkm** [comment]
(simple confirmation that the build is happy again: https://github.com/compiler-explorer/compiler-workflows/actions/runs/10913114930 )
