### ISSUE TITLE
[BUG]: Last file in a cmake project tree morphs into "Unknown file"

### ISSUE THREAD

**Issue by Asperamanca** [compiler-explorer/compiler-explorer#6859]
### Describe the bug

The last (bottommost) file of a cmake project turns into an unreadable "Unknown file" when changing options in an attached compiler.

### Steps to reproduce

1. Import a cmake C++ project containing multiple files. In my case, I use c++23 stacktrace, which requires special compiler and linker flags on gcc
2. Add a compiler (default is currently GCC 14.1)
3. Change compiler options (in my case: add the necessary -lstdc++exp)
4. Compiler reports "One or more files do not have a filename"
5. Initially, the tree view looks innocent
6. When opening the last file, it is now empty
7. After this, the last file is shown as "Unknown file" in the tree

### Expected behavior

File name and content does not get lost in space and time.

### Reproduction link

Not applicable

### Screenshots

1. Initial tree on import
![image](https://github.com/user-attachments/assets/0c235776-8041-493f-9181-c31c18537757)
2. Error from compiler after adding the option
![image](https://github.com/user-attachments/assets/51ac7ff7-5f2f-40a0-8561-3e5465914cc5)
3. Tree after trying to open the last file
![image](https://github.com/user-attachments/assets/b7ffff48-e245-4a98-8cc4-833c085c26c1)

### Operating System

Windows 11 (10.0.22631)

### Browser version

Firefox 130.0

**Comment by OfekShilon** [comment]
@Asperamanca  thank you for reporting this!
I wasn't able to reproduce. As a first step, could you please paste a short-link to CE with your project, right before the change that messes up the last file?
If that won't help reproduce: would you be willing to attach (or send privately) an archive with your project, so I could import myself?

**Comment by Asperamanca** [comment]
Here is the link just before adding the compiler:
https://godbolt.org/z/WGvoTbo63
and here it is, just after adding the compiler. It already complains that a file is missing (utils.h has become Unknown File):
https://godbolt.org/z/earYb8G9j

But you can try using the attached project
[04c_expectedmonad.zip](https://github.com/user-attachments/files/17606799/04c_expectedmonad.zip)
It's from [my public repo](https://github.com/Asperamanca/monadic_operations_cpp23) anyway

Could the browser (Firefox) cause this issue?

**Comment by partouf** [comment]
cannot reproduce this either chrome or firefox, how exactly are you Adding the compiler?

(sidenote, I'm super confused about not being able to close the "C++ source #1", that's one annoying bug)

**Comment by Asperamanca** [comment]
I'll show what I do in a dia show:

![image](https://github.com/user-attachments/assets/59026065-133e-4ce8-91e2-c69ebf91f4be)

![image](https://github.com/user-attachments/assets/26faf979-5ad3-4473-a1c4-b9351069be9d)

![image](https://github.com/user-attachments/assets/437765a5-8139-4510-90ee-af3bbfe76d54)
(now select the zip file I uploaded in my previous post)

![image](https://github.com/user-attachments/assets/cb42a2a9-566e-41ec-a324-04caa2a7421e)
(this is how the tree now looks)

![image](https://github.com/user-attachments/assets/702d3155-2aef-4092-9c46-79e9a414865b)


![image](https://github.com/user-attachments/assets/4d00a546-546d-4f95-bc88-d91b644b23fb)
(now it's already broken)

BTW, I posted a separate bug report about not being able to close source #1

**Comment by OfekShilon** [comment]
The link to the bug about not being able to close source is broken...
That is likely a side effect of an intentional fix introduced here: #6465 . Once we reproduce it should probably take some refining.

**Comment by Asperamanca** [comment]
Oh sorry, that was no link. Just a markdown artifact. You found the right one, thanks.

Is there a different way to add a cmake project that will not have this bug? (i.e. a workaround)?

**Comment by partouf** [comment]
For some reason I can only reproduce this live and not locally, very confusing

**Comment by partouf** [comment]
Found the culprit

**Comment by partouf** [comment]
Fix is live
