### ISSUE TITLE
HPPA support in gcc

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#6878]
First step in https://github.com/compiler-explorer/gcc-cross-builder/pull/71

Next steps

gcc-cross-builder:
- [ ] try enable Go
- [x] try enable Ada
- [x] try enable Objc/Objc++
- [ ] try enable JIT

infra:
- [x] add config

ce:
- [ ] add config for all enabled langs
- [ ] test
- [ ] deploy

**Comment by dkm** [comment]
cc @thesamesam

**Comment by dkm** [comment]
GO is KO:
```
[ALL  ]    checking how to hardcode library paths into programs... immediate                                                                                                  
[ALL  ]    checking for gawk... (cached) gawk                                        
[ALL  ]    checking for --enable-version-specific-runtime-libs... no                                                                                                          
[ERROR]    configure: error: "could not determine GOARCH from hppa-unknown-linux-gnu"                                                                                         
[ERROR]    make[3]: *** [Makefile:16126: configure-target-libgo] Error 1                                                                                                      
[ERROR]    make[3]: *** Waiting for unfinished jobs....    
```

**Comment by thesamesam** [comment]
> GO is KO:
> 

Yeah, unfortunately it needs a fair bit of love. The initial work was at https://lore.kernel.org/linux-parisc/7013a3e7d6c9c77c5010bc1c72971758@matoro.tk/ but lost steam.

> try enable Ada

Never tried on hppa (as we discussed, I hope to get our infra downstream in a better place on this soon) but Debian appears to have had it built in the past: https://packages.debian.org/sid/hppa/gnat-11/filelist.

> try enable Objc/Objc++

Never tried on hppa. I expect it might work, only risky bit is the runtime.

> try enable JIT

This should work! I've even used Emacs with it on hppa.

**Comment by dkm** [comment]
The JIT is also KO, but it's probably because of some setting in ct-ng. Not critical, I'm only enabling it because at some point, I thought I could enable rustc_cg_gcc for all these cross targets. In fact, we're far from that, so disabling it.

**Comment by dkm** [comment]
A build with only JIT and GO disabled went fine. I'll commit that and trigger a new build.

**Comment by dkm** [comment]
build process: https://github.com/compiler-explorer/infra/actions/runs/10982256119

**Comment by dkm** [comment]
Compiler is OK, now moving to do the config updates (later tonight)

**Comment by thesamesam** [comment]
Try this:
```
@@ -647,7 +629,7 @@
 CT_CC_GCC_HAS_LIBMPX=y
 CT_CC_GCC_ENABLE_CXX_FLAGS=""
 CT_CC_GCC_CORE_EXTRA_CONFIG_ARRAY=""
-CT_CC_GCC_EXTRA_CONFIG_ARRAY=""
+CT_CC_GCC_EXTRA_CONFIG_ARRAY="--enable-shared"
 CT_CC_GCC_STATIC_LIBSTDCXX=y
 # CT_CC_GCC_SYSTEM_ZLIB is not set
 CT_CC_GCC_CONFIG_TLS=m
@@ -696,7 +678,7 @@
 #
 CT_CC_LANG_CXX=y
 CT_CC_LANG_FORTRAN=y
-# CT_CC_LANG_JIT is not set
+CT_CC_LANG_JIT=y
 CT_CC_LANG_ADA=y
 CT_CC_LANG_D=y
 CT_CC_LANG_OBJC=y
```

**Comment by dkm** [comment]
Yes, I've added the JIT option in ct-ng, so it should add the `--enable-host-shared`. But as I said above, it's currently not used at all, so very very not required :D

**Comment by dkm** [comment]
I'll finish the config update later tonight, but it's mostly ready

**Comment by dkm** [comment]
> I'll finish the config update later tonight, but it's mostly ready

obviously not finished, I should not give engagement :sweat_smile: I promise I'll finish this in a reasonable manner. I need to test it and then deploy.

**Comment by dkm** [comment]
Not really closed, need to test and release first.

**Comment by dkm** [comment]
```
hppa ADA gnathppa1420 ASM--------------- [OK]
hppa ADA gnathppa1420 ASM+BINARY-------- [OK]
hppa D gdchppa1420 ASM------------------ [OK]
hppa D gdchppa1420 ASM+BINARY----------- [OK]
hppa FORTRAN fhppag1420 ASM------------- [OK]
hppa FORTRAN fhppag1420 ASM+BINARY------ [OK]
hppa CXX hppag1420 ASM------------------ [OK]
hppa CXX hppag1420 ASM+BINARY----------- [OK]
hppa C chppag1420 ASM------------------- [OK]
hppa C chppag1420 ASM+BINARY------------ [OK]
hppa OBJC objchppag1420 ASM------------- [OK]
hppa OBJC objchppag1420 ASM+BINARY------ [OK]
hppa OBJCXX objcpphppag1420 ASM--------- [OK]
hppa OBJCXX objcpphppag1420 ASM+BINARY-- [OK]
hppa GIMPLE gimplehppag1420 ASM--------- [OK]
hppa GIMPLE gimplehppag1420 ASM+BINARY-- [OK]


#### Fake tests, they should FAIL or be SKIPPED, but never PASS

hppa D gnathppa1420 ASM----------------- [FAIL]
hppa D gnathppa1420 ASM+BINARY---------- [FAIL]
#### End of fake tests

```

Looks ok :+1:

**Comment by dkm** [comment]
The changes will be live with next release, but it's part of multiple changes, and some are causing issues, so not sure when.

**Comment by dkm** [comment]
It's live :rocket:
