### ISSUE TITLE
[LIB REQUEST]: Add Fortran Package Manager (library)

### ISSUE THREAD

**Issue by ivan-pi** [compiler-explorer/compiler-explorer#6884]
### Library name

fpm

### Library description

Fpm is the Fortran Package Manager (which is itself an fpm package and can build itself)

### Library repository

https://github.com/fortran-lang/fpm

### Motivation

Fpm exports several useful functions for string handling, dealing with Fortran code, etc. Having fpm available would also make it easier to debug issues (and compiler bugs) in fpm.

To test the package is working as intended run:
```
program test_fpm
    use fpm_release, only: version_t, fpm_version
    associate(v => fpm_version())
        print *, "fpm version: " // v%s()
    end associate
end program
```

**Comment by ivan-pi** [comment]
The library appeared but I'm guessing something is wrong with the paths: https://godbolt.org/z/cKzf41qrv

I see the error,
```
f951: Warning: Nonexistent include directory '/app/libfpm/mod' [-Wmissing-include-dirs]
/app/example.f90:2:9:

    2 |     use fpm_release, only: version_t, fpm_version
      |         1
Fatal Error: Cannot open module file 'fpm_release.mod' for reading at (1): No such file or directory
compilation terminated.
```

(cc @partouf)

Perhaps the dependencies are missing? Is there a log where I can check the installation process?

**Comment by partouf** [comment]
It looks like it's incorrectly configured, ah yes, the `v` should be removed from the version number :woman_facepalming:

**Comment by ivan-pi** [comment]
Thanks for the help and review!

**Comment by partouf** [comment]
fix is live

the library doesn't work for all compilers, some errors occured when building with gfortran 14 https://conan.compiler-explorer.com/getlogging/libfpm/0.10.1/x86_64/20240928154215

most others should work https://conan.compiler-explorer.com/libraries_fortran.html#fpm/0.10.1

**Comment by ivan-pi** [comment]
Thanks. The error with gfortran 14 is a known one: https://github.com/fortran-lang/fpm/issues/1059; it has been already fixed for the next fpm version.
