### ISSUE TITLE
[BUG]: x86-64 Clang 19.1 fails to compile supported C++23 code (wrong compiler?)

### ISSUE THREAD

**Issue by Zingam** [compiler-explorer/compiler-explorer#6899]
### Describe the bug

The following should compile in Clang 19.1:

```
#include <cassert>
#include <memory>
#include <print>

void get_ptr(int** p) {
    *p = new int{42};
}

int main() {
    std::unique_ptr<int> p;
    get_ptr(std::out_ptr<int*>(p));
    assert(*p == 42);
    std::print("value is {}", *p);
}
```

Instead I get:

```
x86-64 clang 19.1.0
x86-64 clang 19.1.0
-std=c++23
Could not execute the program
Compiler returned: 1
Compiler stderr
<source>:3:10: fatal error: 'print' file not found
    3 | #include <print>
      |          ^~~~~~~
1 error generated.
```

Clang Trunk compiles the above code succefully. It seems as if Clang 19.1 isn't Clang 19.1.

### Steps to reproduce

1. Visit gotbold
2. Execute above example with `-std=c++23`

### Expected behavior

The code compiles properly.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by partouf** [comment]
Clang 19.1 is definitely Clang 19.1, but the stdlib that's being used is from 13.2 at the moment. We'll need to update that to 14.2

**Comment by partouf** [comment]
fix is now live

**Comment by Zingam** [comment]
> Clang 19.1 is definitely Clang 19.1, but the stdlib that's being used is from 13.2 at the moment. We'll need to update that to 14.2

Oops, then is my fault? Why would Clang use GCC's 14.2 by default? Wouldn't be the goal of Compiler Explorer to use the compiler's own library, e.g. libc++ in that case? That's what I would expect. Wasn't that the case so far or I never noticed that Clang is using libstdc++?

**Comment by partouf** [comment]
> > Clang 19.1 is definitely Clang 19.1, but the stdlib that's being used is from 13.2 at the moment. We'll need to update that to 14.2
> 
> Oops, then is my fault? Why would Clang use GCC's 14.2 by default? Wouldn't be the goal of Compiler Explorer to use the compiler's own library, e.g. libc++ in that case? That's what I would expect. Wasn't that the case so far or I never noticed that Clang is using libstdc++?

Clang always (except on OSX and BSD) uses the systems' libstdc++, this is to remain binary compatible with other programs and libraries on that system. Libc++ is not ABI compatible with libstdc++. And so we do the default as well, but you can always switch to libc++ by passing `-stdlib=libc++` to Clang.

See https://github.com/compiler-explorer/compiler-explorer/issues/3682 if you wanna add to the conversation about it.

**Comment by Zingam** [comment]
> > > Clang 19.1 is definitely Clang 19.1, but the stdlib that's being used is from 13.2 at the moment. We'll need to update that to 14.2
> > 
> > 
> > Oops, then is my fault? Why would Clang use GCC's 14.2 by default? Wouldn't be the goal of Compiler Explorer to use the compiler's own library, e.g. libc++ in that case? That's what I would expect. Wasn't that the case so far or I never noticed that Clang is using libstdc++?
> 
> Clang always (except on OSX and BSD) uses the systems' libstdc++, this is to remain binary compatible with other c++ programs and libraries on that system. Libc++ is not ABI compatible with libstdc++. And so we do the default as well, but you can always switch to libc++ by passing `-stdlib=libc++` to Clang.
> 
> See #3682 if you wanna add to the conversation about it.

I know that but by default I'd assume that Clang uses libc++ in an tool like Compiler explorer. I think that if somebody (a random person) decides to use Compiler Explorer they wouldn't be thinking about Compiler Explorer runs on Linux, etc, therefore it usles libstdc++, which is easy to forget. IMO. they'd assume Clang uses Clang's Standard Library... which is libc++.

I'll check the discussion. Thanks!
