### ISSUE TITLE
[BUG]: Overrides broken

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#6905]
### Describe the bug

Very odd results

### Steps to reproduce

Example: https://godbolt.org/z/86rb4aGj8
Look at Compilation options

### Expected behavior

* Should be passing `-std=c++23`
* Should be passing something like: `--gcc-toolchain=/opt/compiler-explorer/mipsel/gcc-14.2.0`

(note: still probably won't compile)

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
I'm guessing it carried state from some previously used compilers. I tried making overrides maintain per-compiler state, should return to it:  https://github.com/compiler-explorer/compiler-explorer/pull/6497

**Comment by partouf** [comment]
I don't think it has anything to do with that, it's just not emitting `-std=..` flags as soon as you have another setting set.

**Comment by partouf** [comment]
fixed by https://github.com/compiler-explorer/compiler-explorer/commit/bafe4f19697425b7a95edfd1b7985dc47d4a3c14

**Comment by partouf** [comment]
fix is live
