### ISSUE TITLE
[COMPILER REQUEST]: Add clang 19.1.0 for RISC-V, ARM, AArch64, MIPS, etc.

### ISSUE THREAD

**Issue by topperc** [compiler-explorer/compiler-explorer#6912]
### Compiler name

LLVM clang

### Compiler version

19.1.0

### Compiler language

C++ and C

### Compiler homepage

https://releases.llvm.org/19.1.0/docs/ReleaseNotes.html

### Motivation

Compiler explorer has clang 19.1.0 for X86, but not RISC-V, ARM, AArch64, or MIPS. The previous version 18.1.0 is supported for these targets.

**Comment by partouf** [comment]
I added these yesterday

**Comment by topperc** [comment]
@partouf When can I expect to see these on the website?

**Comment by topperc** [comment]
> @partouf When can I expect to see these on the website?

Nevermind it shows up after doing "reset code and ui layout". I guess the list of compilers is cached in my browser somewhere?

**Comment by topperc** [comment]
@partouf I see clang 19.1.0 for RISC-V for C++ but not for C.
