### ISSUE TITLE
[BUG]: Address Sanitizer is literally insane for Clang16

### ISSUE THREAD

**Issue by HazyMrf** [compiler-explorer/compiler-explorer#6926]
### Describe the bug

SIGSEGV on a simple code snippet with like 

```
#include <iostream>

int main() {
     int a = 1, b = 2;
}
```

with Clang16 under -fsanitize=address

### Steps to reproduce

Select Clang16 with Address Sanitizer and try to reroll execution for 10-20 times, you will see SIGSEGV sooner or later

### Expected behavior

Expected behaviour is to have a successful execution without SIGSEGV

### Reproduction link

https://godbolt.org/z/GzW5P8TPe

### Screenshots

<img width="934" alt="image" src="https://github.com/user-attachments/assets/7c5d143b-88bd-4bc9-ab23-780818b8059f">

### Operating System

macOS Sonoma 14.4

### Browser version

Safari Version 17.4

**Comment by OfekShilon** [comment]
This appears to be a clang-16 issue: https://github.com/llvm/llvm-project/issues/87754 .
As [a comment in the llvm repo thread ](https://github.com/llvm/llvm-project/issues/87754#issuecomment-2141182203) says (and by my own attempts) this doesn't reproduce for clang 17+.
