### ISSUE TITLE
[BUG]: uBlock Origin addon breaks compilation

### ISSUE THREAD

**Issue by stevehoover** [compiler-explorer/compiler-explorer#6933]
### Describe the bug

CE was broken for me in Chrome, and I found that the uBlock Origin addon was the culprit.
(Not going to debug it, but I thought I'd share. CE is awesome!)

(There's mention of uBlock Origin in Issue #3443 as well.)

### Steps to reproduce

1. In Chrome, install uBlock Origin from https://chromewebstore.google.com/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm.
2. Open godbolt.org.

### Expected behavior

 Compilation fails (does not complete). If not reproducible, feel free to close this issue.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment]
Can you try debugging a bit? There's some way to get ublock origin output (I've done it before somehow but I forget). I have ublock origin and it's (currently) working for me:
![image](https://github.com/user-attachments/assets/b59bd041-e1ee-4790-8138-2b90c9934f52)

**Comment by mattgodbolt** [comment]
I htink you click "open the logger" and then reload the site. Failing that can you open up the javascript console and paste any error you see there? thanks

**Comment by stevehoover** [comment]
I'm actually finding now that uBlock Origin may not be to blame. It may just be failing randomly 2/3 of the time. I'll share more when I have a chance to do more testing....

**Comment by stevehoover** [comment]
Yeah, I looked through the console before and the error was very mysterious. After reinstalling Chrome the error seems to have cleared up, so I'm going to close this. Thanks for an amazing tool!

**Comment by mattgodbolt** [comment]
Thanks for taking the time to dig in, Steve!
