### ISSUE TITLE
.NET fails to compile

### ISSUE THREAD

**Issue by xtqqczze** [compiler-explorer/compiler-explorer#6945]
```log
error CS2001: Source file '/nosym/tmp/compiler-explorer-compiler202498-8478-lenqdj.tcm8i/example.cs' could not be found.
error CS2001: Source file '/nosym/tmp/compiler-explorer-compiler202498-8478-lenqdj.tcm8i/AssemblyInfo.cs' could not be found.
Compiler returned: 1
```

https://csharp.godbolt.org/z/qdqjq46Wc

**Comment by xtqqczze** [comment]
https://github.com/compiler-explorer/compiler-explorer/pull/6928#issuecomment-2398361491

**Comment by mattgodbolt** [comment]
@hez2010 has already pushed a fix! I will look to update the site shortly.

**Comment by mattgodbolt** [comment]
The fix is rolling out to productino: will take ~1h or so and then you may need to click the "force recompile" button at the bottom of any affected compiler windows
