### ISSUE TITLE
[BUG]: rror C1060: compiler is out of heap space

### ISSUE THREAD

**Issue by majunjunquan** [compiler-explorer/compiler-explorer#6970]
### Describe the bug

rror C1060: compiler is out of heap space

### Steps to reproduce

C++ TO  x86 msvc v19.29 VS16.11
#include <cstdint>

// Helper macros for operations
#define S_ror(x, n) (((x) >> (n)) | ((x) << (32 - (n))))
#define S_rol(x, n) (((x) << (n)) | ((x) >> (32 - (n))))
#define S_bswap(x)                                            \
    ((((x) & 0xFF000000) >> 24) | (((x) & 0x00FF0000) >> 8) | \
     (((x) & 0x0000FF00) << 8) | (((x) & 0x000000FF) << 24))
#define S_xor(x, y) ((x) ^ (y))
#define S_not(x) (~(x))
void aa() {
    uint32_t r1 = 0x12345678;  // Initialize registers with some values
    uint32_t r2 = 0x87654321;
    uint32_t r3 = 0;
    uint32_t r4 = 0;
    uint32_t r5 = 0;
int v1=S_rol(S_xor(S_rol(S_xor(S_not(S_bswap(S_ror(S_rol(S_rol(S_rol(S_xor(S_not(S_bswap(S_xor(S_ror(S_rol(S_rol(S_ror(S_bswap(S_not(S_bswap(S_bswap(S_xor(S_rol(S_ror(S_xor(S_xor(S_not(S_xor(S_bswap(S_xor(S_xor(S_bswap(S_not(S_bswap(S_not(S_bswap(S_bswap(S_xor(S_ror(S_ror(S_not(S_ror(S_rol(S_xor(S_rol(S_xor(S_xor(S_bswap(S_bswap(S_bswap(S_xor(S_xor(S_bswap(S_xor(S_rol(S_xor(S_not(S_xor(S_rol(S_rol(S_not(S_bswap(S_ror(S_not(S_xor(S_ror(S_xor(S_bswap(S_rol(r1, 73406)), r1), 84135), r2)), 29048))), 84616), 64053), r2)), r5), 87537), r3)), r2), r4)))), r3), r1), 56414), r1), 25313), 20054)), 17531), 3648), r2))))))), r2), r2)), r5)), r4), r1), 36283), 5411), r3))))), 86870), 45352), 34966), 51771), r3))), r3), 81363), 68532), 98325), 40103))), r1), 21950), r5), 92539);
}

### Expected behavior

example.cpp
<source>(17): fatal error C1060: compiler is out of heap space
Compiler returned: 2

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
All compilers seem to fail with this particular program, this isn't a CE issue: https://godbolt.org/z/f9fvoaxGv

**Comment by OfekShilon** [comment]
We impose both time and memory limits on compilation jobs, and this particular program breaks both...

**Comment by mattgodbolt** [comment]
Here's the repro link for Windows: https://compiler-explorer.com/z/54dE3PY9n
Fails on GCC: https://compiler-explorer.com/z/oGoG9545M too
