### ISSUE TITLE
Show the compiler 'id' somewhere in the UI

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#6985]
Is there a way to see the compiler "id" (used in the client state) in the compiler explorer UI?

_Originally posted by @goto40 in https://github.com/compiler-explorer/compiler-explorer/discussions/6984_

**Comment by goto40** [comment]
Yes. For me it is ok. You can discard my pr https://github.com/compiler-explorer/compiler-explorer/pull/6988 (i prepared a similar pr).

Thank you.

**Comment by OfekShilon** [comment]
@goto40 Sorry! your PR wasn't referenced here and I missed it. I think such details are better shown under the 'full compiler version'. Do you want to modify your PR and I'll merge it instead?

**Comment by OfekShilon** [comment]
@goto40  you can use my code from here if you want: https://github.com/compiler-explorer/compiler-explorer/compare/main...ofek/compilerid

**Comment by goto40** [comment]
No. It is ok for me. Just go ahead

Ofek ***@***.***> schrieb am Do., 24. Okt. 2024, 12:57:

**Comment by goto40** [comment]
I closed my pr

Pierre Bayerl ***@***.***> schrieb am Do., 24. Okt. 2024,
12:59:

**Comment by goto40** [comment]
(see issue: double pr)

**Comment by goto40** [comment]
Thank you for your work. Go ahead. I am looking forward for the feature 👍 good work!!
