### ISSUE TITLE
[BUG]: Clang trunk gets compiler errors due to GCC's libstdc++

### ISSUE THREAD

**Issue by carlosgalvezp** [compiler-explorer/compiler-explorer#6989]
### Describe the bug

It seems the Clang trunk build is picking a bad commit of GCC trunk's libstdc++, simply including `<vector>` leads to a compiler error. This does not happen on GCC trunk:
https://godbolt.org/z/4orzoYssY

### Steps to reproduce

https://godbolt.org/z/4orzoYssY

### Expected behavior

No compiler errors

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment]
This seems like a clang bug - you can file it with them, unless you think it's specific to Compiler Explorer's build somehow?

**Comment by carlosgalvezp** [comment]
I thought I had seen it in GCC trunk as well and was later fixed, but maybe it was only on Clang. Anyhow this seems to be the culprit:

https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=cba80691251efccf44ab9aecb26558319605c9ea

It was pushed 7 hours ago. How often is GCC trunk updated by Compiler Explorer? Also, does Clang trunk and GCC trunk use the same version of libstdc++?

**Comment by carlosgalvezp** [comment]
Great to hear, thank you for the quick replies!

**Comment by partouf** [comment]
new nightly GCC has been installed and this has disappeared
