### ISSUE TITLE
[LIB REQUEST] kotlinx.coroutines

### ISSUE THREAD

**Issue by chaoren** [compiler-explorer/compiler-explorer#6997]
https://github.com/Kotlin/kotlinx.coroutines

`kotlinx.coroutines` is the standard library for Kotlin coroutines.

**Comment by junlarsen** [comment]
Hi @chaoren thanks for showing interest in Kotlin libraries. We currently don't support libraries for any of the JVM languages, but if you are interested in looking into it we happily accept PRs!

(closing as duplicate of https://github.com/compiler-explorer/compiler-explorer/issues/5942)
