### ISSUE TITLE
[BUG]: objdump+parser weird "discriminator" nonsense

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#7000]
### Describe the bug

-

### Steps to reproduce

-

### Expected behavior

-

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
To reproduce: https://godbolt.org/z/7qxWv9n4T

Doesn't reproduce for me locally: 
![image](https://github.com/user-attachments/assets/fcdf31f5-6a90-4569-b8e5-f943dbf0252b)


My local objdump is `/opt/compiler-explorer/gcc-14.2.0/bin/objdump`, version `Compiler-Explorer-Build-gcc--binutils-2.42`. Maybe the live site is different?

Also, maybe a workaround would be to change the objdump to, say, `/opt/compiler-explorer/clang-19.1.0/bin/llvm-objdump` ?

**Comment by OfekShilon** [comment]
A similar (arguably worse) thing happens for clang 17+ : https://godbolt.org/z/j6MMvGhWG
Which increases the suspicion it's an objdump thing.

**Comment by partouf** [comment]
So the "discrimator" text comes from file source comments, so it should never be visible in the assembly
But I also cannot reproduce with the latest version of asm-parser

So I have deployed a new version of asm-parser, but it still needs to propagate through the instances. I might force a restart today.

**Comment by partouf** [comment]
have restarted prod, but problem remains

**Comment by partouf** [comment]
Might have reproduced in the wrong way, not entirely sure what the exact objdump command line is

**Comment by partouf** [comment]
ahh I don't have gcc 14.2 so used 14.1's objdump

**Comment by partouf** [comment]
can reproduce after installing 14.2

**Comment by OfekShilon** [comment]
> can reproduce after installing 14.2

Weird.. I do have 14.2 and couldn't reproduce. Anyway, leaving this in your capable hands.

**Comment by mattgodbolt** [comment]
Super odd! Thank you both so much for diging into this weird problem!

**Comment by jeremy-rifkin** [comment]
7000 🎉

**Comment by OfekShilon** [comment]
It seems the reason it didn't reproduce locally for me is that I didn't have a local build of the external asm-parser.  Need to investigate what ran instead - but makes me wonder if it is even necessary.

**Comment by partouf** [comment]
> It seems the reason it didn't reproduce locally for me is that I didn't have a local build of the external asm-parser. Need to investigate what ran instead - but makes me wonder if it is even necessary.

By default it runs the "old" `parsers/asm-parser.ts`, but for bigger binaries the JS quickly becomes super slow.

**Comment by partouf** [comment]
this seems fixed, not sure if propagated through all nodes, but refresh seems to give a better asm listing

**Comment by partouf** [comment]
Considering this fixed
