### ISSUE TITLE
[BUG]: In rustc, LLVM-IR pane + `--emit llvm-ir` clash sporadically

### ISSUE THREAD

**Issue by OfekShilon** [compiler-explorer/compiler-explorer#7012]
### Describe the bug

If you select any rustc compiler, open an LLVM-IR pane and add `--emit llvm-ir` to the compiler switches, after several re-builds one of two things can happen:

 1. The IR pane will show 'Failed to run compiler to get IR code':
![image](https://github.com/user-attachments/assets/bf57ce2c-04a6-423f-9f6e-e480f4d87ede)

 2. The compiler pane will show '\<Compilation failed\>' and the output pane will show something like: `error: could not copy "/app/output.example.b75e7786252e4c9a-cgu.0.rcgu.ll" to "/app/output.s": No such file or directory (os error 2)`
![image](https://github.com/user-attachments/assets/4fcdb95d-d9d1-4440-8240-fa892531bf91)

First mentioned in #6996.

### Steps to reproduce

https://godbolt.org/z/cfPGsvTTc

Rebuild a few times

### Expected behavior

Both panes should show good results. AFAICT this is what happens for clang.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment]
I've been unable to reproduce locally on Linux too. I'm going to setup the nsjail as I suspect an interaction with that.

**Comment by mattgodbolt** [comment]
Nsjail works ok: so now I suspect something like cacheing differences (will poke about). Basically anything that changes the relative timing of the various compilations etc.

**Comment by mattgodbolt** [comment]
Now firing up branch `mg/instrument_7012` in staging as I can't repro locally despite everything I could think of.

Consider me totally nerd-sniped @OfekShilon

**Comment by mattgodbolt** [comment]
Heavily instrumented code yielded a failure to run the llvm-ir with:
Failed with 
```js
{"code":1,"execTime":2817,"inputFilename":"/nosym/tmp/compiler-explorer-compiler2024112-8835-8xm3r8.wos5/example.rs","instructionSet":"amd64","okToCache":true,"stderr":[{"tag":{"column":37,"line":6,"severity":2,"text":"warning: unused variable: `c`"},"text":"warning: unused variable: `c`"},{"tag":{"column":37,"line":6,"severity":3,"text":""},"text":" --> <source>:6:37"},{"text":"  |"},{"text":"6 | pub unsafe fn write_characteristics(c: u16) {"},{"text":"  |                                     ^ help: if this is intentional, prefix it with an underscore: `_c`"},{"text":"  |"},{"text":"  = note: `#[warn(unused_variables)]` on by default"},{"text":""},{"tag":{"column":13,"line":3,"severity":2,"text":"warning: `extern` block uses type `str`, which is not FFI-safe"},"text":"warning: `extern` block uses type `str`, which is not FFI-safe"},{"tag":{"column":13,"line":3,"severity":3,"text":""},"text":" --> <source>:3:13"},{"text":"  |"},{"text":"3 |     fn f(x: &str);"},{"text":"  |             ^^^^ not FFI-safe"},{"text":"  |"},{"text":"  = help: consider using `*const u8` and a length instead"},{"text":"  = note: string slices have no C equivalent"},{"text":"  = note: `#[warn(improper_ctypes)]` on by default"},{"text":""},{"text":"error: could not copy \"/app/output.example.b75e7786252e4c9a-cgu.0.rcgu.ll\" to \"/app/output.ll\": No such file or directory (os error 2)"},{"text":""},{"text":"error: aborting due to 1 previous error; 2 warnings emitted"},{"text":""}],"stdout":[],"timedOut":false,"truncated":false} 
```

so it died with the same "could not copy ... to /app/output.ll" equivalent to the "other" failure mode.

**Comment by mattgodbolt** [comment]
Looking in the output of the "succeeding" compiler:
```
!DIFile(filename: \"/app/example.rs/@/example.b75e7786252e4c9a-cgu.0\"
```

the _same_ unique-looking ID as the other.

So I'm now 80% sure that `--emit-llvm` unconditionally outputs to a _well defined_ name and THEN copy/deletes it over to the output file.

That means the two compilers will fight with each other in this case.

I'm not quite sure how to avoid this. @ojeda is a rust expert and might be able to clarify if indeed this is the case.

**Comment by mattgodbolt** [comment]
See https://github.com/rust-lang/cargo/issues/6899 for example; looks like the hash is pretty hardcoded internally?

**Comment by mattgodbolt** [comment]
neither passing ` -C extra-filename=""` nor `-C incremental=false` fixes it.

**Comment by bjorn3** [comment]
> i wonder if rust uses the same internal temporary filename
> then copies it to the output
> then removes it

Right, that is indeed what rustc does.

One solution I think would be to pass a different `-Cmetadata` argument to both rustc invocations. This would change the filenames they emit, though it can also affect codegen and definitively affects the hash in mangled symbol names itself which could be confusing. The other option is to run both rustc invocations in a separate directory.

**Comment by mattgodbolt** [comment]
Thanks @bjorn3! I just tested with
```ts
 newOptions.push('--codegen', 'extra-filename=llvm-ir-gen');
```

in the case of one of the compilations.

I was trying to avoid running in a different directory but if you think that's a better way please let me know. Is it guaranteed that the intermediate files will end up in the `out-dir` ? Does that _only_ affect the intermediate files? If I specify a full path to the output name of the `.ll` I'd like it to make, is the `out-dir` only used for intermediates?

**Comment by bjorn3** [comment]
> Is it guaranteed that the intermediate files will end up in the out-dir ?

There is no documented guarantee, but I don't recall any version that didn't do this. IMO it would make sense to put temporaries in a subdirectory with a randomly generated name to avoid the clash even without `--out-dir`, but that would still work if `--out-dir` is used.

> Does that only affect the intermediate files? If I specify a full path to the output name of the .ll I'd like it to make, is the out-dir only used for intermediates?

Aside from the temporary files I think it only affects outputs for which you haven't explicitly specified a filename. If you do specify a filename for an output, the `--out-dir` is guaranteed to not have any effect on said output though.

**Comment by mattgodbolt** [comment]
```
Failed with {"code":1,"execTime":85,"inputFilename":"/nosym/tmp/compiler-explorer-compiler2024112-8834-1uoyzu3.e9hv/example.rs","instructionSet":"amd64","okToCache":true,"stderr":[{"text":"warning: ignoring --out-dir flag due to -o flag"},{"text":""},{"tag":{"column":37,"line":6,"severity":2,"text":"warning: unused variable: `c`"},"text":"warning: unused variable: `c`"},{"tag":{"column":37,"line":6,"severity":3,"text":""},"text":" --> <source>:6:37"},{"text":"  |"},{"text":"6 | pub unsafe fn write_characteristics(c: u16) {"},{"text":"  |                                     ^ help: if this is intentional, prefix it with an underscore: `_c`"},{"text":"  |"},{"text":"  = note: `#[warn(unused_variables)]` on by default"},{"text":""},{"tag":{"column":13,"line":3,"severity":2,"text":"warning: `extern` block uses type `str`, which is not FFI-safe"},"text":"warning: `extern` block uses type `str`, which is not FFI-safe"},{"tag":{"column":13,"line":3,"severity":3,"text":""},"text":" --> <source>:3:13"},{"text":"  |"},{"text":"3 |     fn f(x: &str);"},{"text":"  |             ^^^^ not FFI-safe"},{"text":"  |"},{"text":"  = help: consider using `*const u8` and a length instead"},{"text":"  = note: string slices have no C equivalent"},{"text":"  = note: `#[warn(improper_ctypes)]` on by default"},{"text":""},{"text":"error: could not copy \"/app/output.example.b75e7786252e4c9a-cgu.0.rcgu.ll\" to \"/app/output.ll\": No such file or directory (os error 2)"},{"text":""},{"text":"error: aborting due to 1 previous error; 3 warnings emitted"},{"text":""}],"stdout":[],"timedOut":false,"truncated":false} 
```

It appears that `--out-dir` is ignored with `-o` :( so I can't separately control the final output from the intermediates

**Comment by bjorn3** [comment]
> Is this a recommendation for rustc or our use of it?

For rustc.

> It appears that --out-dir is ignored with -o :( so I can't separately control the final output from the intermediates

Can you use `--out-dir some_dir --emit llvm-ir=some_file.ll` instead of `--out-dir some_dir --emit llvm-ir -o some_file.ll`?

**Comment by mattgodbolt** [comment]
The codegen param appears to work: https://godbolt.org/staging/z/7TPcrfrPK -- @bjorn3 if you happen to spot something awry with the code generation due to this "extra filename" let me know please and/or if you feel this is just morally wrong :)

**Comment by bjorn3** [comment]
Codegen shouldn't be affected by `-Cextra-filename`. The only place where it changes output should be in the crate metadata, which isn't used anywhere by compiler explorer anyway. Using `-Cextra-filename` seems like a good solution to me.

**Comment by mattgodbolt** [comment]
Thank you so much for your time and help in this @bjorn3!

**Comment by bjorn3** [comment]
And thank you for making this really useful tool!
