### ISSUE TITLE
New version of KVX compiler

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#7013]
https://github.com/kalray/build-scripts/pull/68#issuecomment-2431518988

Add the 5.2.0 ACB

**Comment by dkm** [comment]
@XavierRaynaud we're missing 5.1.0, but maybe it's expected and 5.1.0 has never seen the outside world ? :)

**Comment by dkm** [comment]
Everything is ready, should be made online during next release (once every few days).

**Comment by XavierRaynaud** [comment]
Thanks a lot @dkm
