### ISSUE TITLE
[REQUEST]: Override `-EHsc` for MSVC

### ISSUE THREAD

**Issue by cpplearner** [compiler-explorer/compiler-explorer#7053]
### Is your feature request related to a problem? Please describe

Currently CE passes the `-EHsc` option to MSVC compilers.

https://github.com/compiler-explorer/compiler-explorer/blob/6c8f9aed5a363903b1123b61101a2ef3442755ae/etc/config/c%2B%2B.amazonwin.properties#L72

This is sometimes annoying. For example, because `/clr` is incompatible with `/EHs`, one needs to explicitly pass `/EHs-` to override `-EHsc` in order to fiddle with `/clr`, and this leads to a compiler warning D9025 : overriding '/EHs' with '/EHs-'.

### Describe the solution you'd like

Do not implicitly pass `-EHsc` to MSVC. Maybe add it to the "compiler override" panel instead.

### Describe alternatives you've considered

N/A

### Additional context

related: #2969

**Comment by OfekShilon** [comment]
Unfortunately this can't really be solved without potentially breaking existing links. See the discussion at https://github.com/compiler-explorer/compiler-explorer/pull/7164#issuecomment-2511084168.

The workaround you specified will have to do for now.
