### ISSUE TITLE
[BUG]: Quoted arguments are not treated as single argument

### ISSUE THREAD

**Issue by HarryRust** [compiler-explorer/compiler-explorer#7083]
### Describe the bug

command line argument containing spaces typed in quotes getting passed to c++ program incorrectly

### Steps to reproduce

https://godbolt.org/z/Gqc5PeKz8

### Expected behavior

argument containing spaces within quotes should be treated as single argument instead of multiple arguments separated by spaces

https://stackoverflow.com/questions/66724341/how-can-i-pass-a-command-line-argument-which-contains-space-character-to-my-c

### Reproduction link

Not applicable

### Screenshots

![image](https://github.com/user-attachments/assets/633eb64e-10c1-4857-a283-48d5db70646a)

**Comment by partouf** [comment]
Broken by https://github.com/compiler-explorer/compiler-explorer/pull/6941

**Comment by partouf** [comment]
Should be fixed now
