### ISSUE TITLE
[BUG]: NASM incorrect instructions in 64 bit mode

### ISSUE THREAD

**Issue by NathanSnail** [compiler-explorer/compiler-explorer#7095]
### Describe the bug

When compiling assembly with NASM in x86_64 mode the instructions view shows the assembly output as x86_32 assembly resulting in garbage instruction output, but the machine code is correct for the assembly.

### Steps to reproduce

1. visit godbolt.org
2. select NASM 2.16.01as the compiler (other versions also seem to have this bug)
3. write 64 bit code such as:
 ```asm
BITS 64

main:
    mov rax, 0x0123456789ABCDEF
    jmp [rax]
 ```
 4. note the editor window has incorrect instruction output 

### Expected behavior

The assembly output should be for x86_64 if 64 bit mode was used.

### Reproduction link

https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:assembly,selection:(endColumn:2,endLineNumber:6,positionColumn:1,positionLineNumber:1,selectionStartColumn:2,selectionStartLineNumber:6,startColumn:1,startLineNumber:1),source:'BITS+64%0A%0Amain:%0A++++mov+rax,+0x0123456789ABCDEF%0A++++jmp+%5Brax%5D%0A+'),l:'5',n:'0',o:'Assembly+source+%231',t:'0')),k:35.40229885057472,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:nasm21601,filters:(b:'0',binary:'0',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:assembly,libs:!(),options:'',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+NASM+2.16.01+(Editor+%231)',t:'0')),k:25.708812260536398,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'clang-cl+18.1.0',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+NASM+2.16.01+(Compiler+%231)',t:'0')),k:38.888888888888886,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

### Screenshots

![image](https://github.com/user-attachments/assets/01b14424-a360-4c04-bcb9-09043551ad38)

**Comment by partouf** [comment]
You need to pass `-felf64` to the compiler, the default is 32bits. https://godbolt.org/z/o4Tc48G4P

**Comment by NathanSnail** [comment]
Thanks!
