### ISSUE TITLE
[BUG]: wrong output when not using "Compile to binary object"

### ISSUE THREAD

**Issue by royger** [compiler-explorer/compiler-explorer#7108]
### Describe the bug

The output assembly in the default (when not using "Compile to binary object" option) is wrong for GCC and seems to strip some assembly directives (like .if) without those being parsed.  The output for clang is correct, as I assume the integrated assembler has been used, and so the assembly directives are correctly parsed.

### Steps to reproduce

See the example, it involves using assembly with `.if` directives for example and any gcc version.  Note how in the given example the 'cmc' instruction appears in the output, but the .err assembly directive is stripped, making it even more confusing.

### Expected behavior

The assembly presented in the default view should either have the directives, or those should have been parsed (but not stripped) to generate the correct output.

### Reproduction link

https://godbolt.org/z/6zGeWfnEG

### Screenshots

Not applicable

**Comment by partouf** [comment]
GCC does not parse and re-generate inline assembly for their `-S` mode, we have countless bugreports about it and we can't do anything about it, sorry.
