### ISSUE TITLE
[BUG]: Most clang compilers gives an error 'cstddef' file not found

### ISSUE THREAD

**Issue by yvoinov** [compiler-explorer/compiler-explorer#7123]
### Describe the bug

Most clang compilers gives an error 'cstddef' file not found when trying to compile C++ code with Clang and this include. See attached screenshot.

### Steps to reproduce

1. Visit godbolt.
2. Choose Clang, for example, x86_64
3. Paste code with #include <cstddef>
4. View compiler error

### Expected behavior

Successfully compilation.

### Reproduction link

Not applicable

### Screenshots

![изображение](https://github.com/user-attachments/assets/a3c8cb2f-8bf2-4a91-b9cc-d9d43955a239)

### Browser version

No matter

**Comment by dkm** [comment]
Hello!

When opening an issue, it's easier for us if you provide a link (top right >> share) instead of a screenshot ;)

You are having an issue because you are using "C" as language. Using "C++" works as expected:
https://c.godbolt.org/z/vPK53n3hj
