### ISSUE TITLE
Remove body-parser in favor for express.json()

### ISSUE THREAD

**Issue by junlarsen** [compiler-explorer/compiler-explorer#7158]
Newer express versions including ours ship express.json so we don't need to explicitly depend on body-parser anymore

**Comment by sikehish** [comment]
I'd like to take this up :)

**Comment by mattgodbolt** [comment]
Thanks! Feel free to give it a go! Be aware there might be some surprising edge cases, but it _should_ be straightforward! The things I'd worry about working the most are the "proxy" things we use when passing on compilations downstream to other nodes. I might be misremembering though.

Either way I suggest you give it a go @sikehish and see how you get on: we'll be happy to help guide!

**Comment by sikehish** [comment]
> Thanks! Feel free to give it a go! Be aware there might be some surprising edge cases, but it _should_ be straightforward! The things I'd worry about working the most are the "proxy" things we use when passing on compilations downstream to other nodes. I might be misremembering though.
> 
> Either way I suggest you give it a go @sikehish and see how you get on: we'll be happy to help guide!

Thank you! Will get started with it

**Comment by sikehish** [comment]
Hi @mattgodbolt  @junlarsen 
Do I need to replace bodyparser's methods with the corresponding express's methods or just replace the usage of bodyParser.json with express.json() ?

**Comment by mattgodbolt** [comment]
> @junlarsen @mattgodbolt I have made the required changes and raised a PR under "Remove body-parser dependency #7176" Please look into it. Thanks !!

Hi @atharvarai - did you see that @sikehish had already offered to look into this? I see you made a PR: thank you very much. It seems your PR has a number of issues though that you're working through with @junlarsen . I'm sorry to mention this but picking up a bug where the most recent message is a few hours earlier saying "please go ahead @sikehish"  is unfortunate. We'll try and be more clear in future and apologies to @sikehish if they've already started looking in to this.

I'll take a look at the PR myself now, but if you're looking to help with an issue please do check the issue in case someone else has offered to do it, and, if it's a big issue (luckily this is not) please consider mentioning you're starting to work on it so we don't duplicate effort in future.

Thanks!

**Comment by atharvarai** [comment]
> > @junlarsen @mattgodbolt I have made the required changes and raised a PR under "Remove body-parser dependency #7176" Please look into it. Thanks !!
> 
> Hi @atharvarai - did you see that @sikehish had already offered to look into this? I see you made a PR: thank you very much. It seems your PR has a number of issues though that you're working through with @junlarsen . I'm sorry to mention this but picking up a bug where the most recent message is a few hours earlier saying "please go ahead @sikehish" is unfortunate. We'll try and be more clear in future and apologies to @sikehish if they've already started looking in to this.
> 
> I'll take a look at the PR myself now, but if you're looking to help with an issue please do check the issue in case someone else has offered to do it, and, if it's a big issue (luckily this is not) please consider mentioning you're starting to work on it so we don't duplicate effort in future.
> 
> Thanks!

I apologize for the confusion regarding the PR. I mistakenly took on the work that was already assigned to @sikehish . I appreciate the effort everyone has put into this issue and I'm sorry for any inconveniences this may have caused. Please let me know how I can assist moving forward!
Thank you!

**Comment by junlarsen** [comment]
> Thank you for putting it out there! I saw the PR comment earlier in the day and was a bit confused as I had started working on it. I didn't want to raise a PR because someone else had raised a PR. Let me know if you'd like me to continue with this or if there's any other issue that you'd want me to work on :)

Thank you for handling this well despite the miscommunication :) If you're interested in helping out with other issues that would be very welcome!

I know our issues list is a bit of a mess, so if you could let me know if you have any specific interests or preferences I can provide some guidance

**Comment by junlarsen** [comment]
Fixed in https://github.com/compiler-explorer/compiler-explorer/pull/7176
