### ISSUE TITLE
[BUG]: Old shortlinks sometimes silently swap compilers

### ISSUE THREAD

**Issue by lunasorcery** [compiler-explorer/compiler-explorer#7169]
### Describe the bug

Loading an old shortlink that used certain versions of MSVC will silently replace the compiler with the first available compiler in the dropdown (currently 6502-c++).

### Steps to reproduce

1. Visit https://gcc.godbolt.org/z/QtaT4m which was authored on 2019-09-18 with the compiler set to 'x64 msvc v19.22'
2. Observe that the loaded compiler is 6502-c++ instead
3. Note that in the serialized editor state, the compiler id string was `vcpp_v19_22_x64` - the id string for the same compiler now seems to be `vcpp_v19_22_VS16_2_x64` instead

### Expected behavior

Expected behavior is that the compiler should be 'x64 msvc v19.22', or 'x64 msvc v19.22 VS16.2' as it now seems to be named. Alternatively, if the original compiler is no longer available, CE should prompt the user as such instead of silently swapping.

### Reproduction link

https://gcc.godbolt.org/z/QtaT4m

**Comment by mattgodbolt** [comment]
This is just my subtle way of pushing 6502 onto everyone... 😁 

Thanks for the report; this is probably a simple configuration fix on our side.

**Comment by partouf** [comment]
Hi @lunasorcery - if there are more links that you know of, please share them or the id's that are missing.

**Comment by lunasorcery** [comment]
these are the others I was able to find (please forgive the ungodly code in each of these)
https://gcc.godbolt.org/z/4jmWFf (`vcpp_v19_16_x64`)
https://gcc.godbolt.org/z/qCoavb (`vcpp_v19_20_x64`)
https://gcc.godbolt.org/z/T6pgh- (`vcpp_v19_21_x64`)

**Comment by mattgodbolt** [comment]
Fix is now live as much as we can do. Thanks all
