### ISSUE TITLE
[BUG]: Enabling a tool returns error 400

### ISSUE THREAD

**Issue by Alcaro** [compiler-explorer/compiler-explorer#7195]
### Describe the bug

see title

json contains `"tools":[{"id":"PVS-Studio","args":[],"stdin":""}]`

### Steps to reproduce

see title v2.0

hitting the recompile button, or making any other change, makes it send `"tools":[{"id":"PVS-Studio","args":"","stdin":""}]` which works

### Expected behavior

200 ok

### Reproduction link

Not applicable

### Screenshots

![image](https://github.com/user-attachments/assets/fc996094-64d5-4f4b-afed-101939f5dcc3)

**Comment by mattgodbolt** [comment]
Thanks so much for filing this and taking the time to debug it to this point. Really appreciated, and also thanks for the "live support" on Discord :walrus: (boo, Github doesn't have this)

**Comment by partouf** [comment]
The API was changed to be more consistent, but obviously there are many moving parts and some paths of entry lost backwards compatibility. Though for this particular one it might just be a frontend issue that can just be fixed there in the tool pane / compiler service ?
