### ISSUE TITLE
[BUG]: Comment Editor Action Not Working in alive2

### ISSUE THREAD

**Issue by veera-sivarajan** [compiler-explorer/compiler-explorer#7196]
### Describe the bug

In https://llvm-ir.godbolt.org/, I'm able to comment a line by pressing `C-/`.

But the same key stroke does not comment a line in https://alive2.llvm.org/ce/.

### Steps to reproduce

1. Visit https://alive2.llvm.org/ce/
2. Enter some text in the source pane. 
3. Try to comment it with `C-/`.

### Expected behavior

The character `;` is inserted at the beginning of the line and the entire line is commented.

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Ubuntu Linux

### Browser version

Firefox 133.0

**Comment by mattgodbolt** [comment]
Hi! We are not responsible for https://alive2.llvm.org/ce/ - which I _think_ is run by @regehr - I'm hoping he sees this and corrects me as to where these things can go. John: I can share the bits I think make the difference :)
