### ISSUE TITLE
[BUG]: gccrs version error issue

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#7220]
### Describe the bug

`info: /opt/compiler-explorer/gcc-14.1.0/bin/gccrs gccrs: error: unrecognized command-line option '-vV'; did you mean '-v'? is ready`

### Steps to reproduce

-

### Expected behavior

-

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by dkm** [comment]
Wooops. Comes from the config file. I'll fix that so that gccrs doesn't inherit
