### ISSUE TITLE
[REQUEST]: Remove the "short link" if the host doesn't support url shortening

### ISSUE THREAD

**Issue by Tal500** [compiler-explorer/compiler-explorer#7231]
### Is your feature request related to a problem? Please describe

There are some conditions to when a url shortening is denied by the compiler-explorer backend server, but in these cases, the "short link" button is still displayed.

### Describe the solution you'd like

If the configuration/checks states in the backend that URL shortening isn't available for this server instance, remove the "short link" button from the HTML.

### Describe alternatives you've considered

-

### Additional context

Based on #7209

**Comment by Tal500** [comment]
> Thanks for suggesting this! Can you please explain what conditions inhibit url-shortening for you?

In my case, URL-shortening is blocked by the server, because of the default configuration specified here: https://github.com/compiler-explorer/compiler-explorer/blob/42607b4afae4e805e0581fc24950d65a26dc10ec/etc/config/compiler-explorer.defaults.properties#L17

The local instance I'm running is not from this pattern of course, and therefore shortening is disabled in the backend, but not in the frontent HTML - which I wish to be fixed.

Note: I do like this default behaviour of the configuration very much and I wish not to change it, but to make the HTML button disappear in that case(and also in the other cases that shortening isn't available).

**Comment by partouf** [comment]
To remove the short link link, you need to set `storageSolution=null` (in `compiler-explorer.local.properties` etc)

**Comment by partouf** [comment]
(just for reference in case you want to disable more things, a lot of general website things are turned off on the website with pug templating magic, example: https://github.com/compiler-explorer/compiler-explorer/blob/main/views/index.pug#L76 with an `if` on storageSolution to turn off short link, and then you can do a search in the code to find the spot fairly easily how its determined)

**Comment by Tal500** [comment]
Thank you very much! This solution worked for me
