### ISSUE TITLE
[REQUEST]: Support hosting compiler explorer instances in sub-url

### ISSUE THREAD

**Issue by Tal500** [compiler-explorer/compiler-explorer#7232]
### Is your feature request related to a problem? Please describe

As I see in the conf and in the code, compiler explorer supports only URLs in the form `http(s)://{hostname'}:{port}/`, but I like to be able to config also sub-URLs in the form of `http(s)://{hostname'}:{port}/{path}/`. The reason of course is to be able to put many services URLs under the same main website.

### Describe the solution you'd like

Support urls in the form of `http(s)://{hostname'}:{port}/{path}/`

### Describe alternatives you've considered

-

### Additional context

Not applicable

**Comment by partouf** [comment]
There is support for different paths through the `httpRoot` property like used in https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/compiler-explorer.aarch64prod.properties#L1 and https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/compiler-explorer.gpu.properties#L1 and https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/compiler-explorer.staging.properties#L2 for example.

But they are intended only as urls forwarded by a proxy, they are not intended to host multiple configurations on the same server.

**Comment by Tal500** [comment]
> There is support for different paths through the `httpRoot` property like used in https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/compiler-explorer.aarch64prod.properties#L1 and https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/compiler-explorer.gpu.properties#L1 and https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/compiler-explorer.staging.properties#L2 for example.
> 
> But they are intended only as urls forwarded by a proxy, they are not intended to host multiple configurations on the same server.

Thanks! Proxy is all I need.
So just to make sure I understand correctly - the url in the server (say, the "long link" code share button, and css&js resources) will go to the url by `httpRoot`? Can `httpRoot` be a full URL like `http://foo/bar` and not just the sub-path `/bar`?

**Comment by partouf** [comment]
> Thanks! Proxy is all I need. So just to make sure I understand correctly - the url in the server (say, the "long link" code share button, and css&js resources) will go to the url by `httpRoot`? Can `httpRoot` be a full URL like `http://foo/bar` and not just the sub-path `/bar`?

I don't think you can use a full URL, I do not believe our code supports that.

It does add the subpath to all links.

**Comment by Tal500** [comment]
> > Thanks! Proxy is all I need. So just to make sure I understand correctly - the url in the server (say, the "long link" code share button, and css&js resources) will go to the url by `httpRoot`? Can `httpRoot` be a full URL like `http://foo/bar` and not just the sub-path `/bar`?
> 
> I don't think you can use a full URL, I do not believe our code supports that.
> 
> It does add the subpath to all links.

OK, and I guess it is not needed because it anyway is always relative to the domain as seems to be by the client.
