### ISSUE TITLE
clang -fopenmp error

### ISSUE THREAD

**Issue by mikaoP** [compiler-explorer/compiler-explorer#795]
If you try to include omp.h to get for example `omp_get_num_threads()` clang does not find it.

**Comment by mattgodbolt** [comment]
The CE nodes don't have OpenMP installed, which I suspect is a prerequisite to get this working.

**Comment by mattgodbolt** [comment]
Though curiously, omp.h is available in all the GCC distributions: `/opt/gcc-explorer/gcc-6.3.0/lib/gcc/x86_64-linux-gnu/6.3.0/include/omp.h` for example.

**Comment by RabsRincon** [comment]
Releated: #751

**Comment by damageboy** [comment]
To get clang to support compiling with openmp, we'd need to add the openmp project to the list of enabled projects:

```
-DLLVM_ENABLE_PROJECTS="...;openmp"
```

Would it be OK to submit a PR for this?

Being able to do so allows developers to see the outcome of various openmp code-rewriting artifacts like breaking up a for loop with `#pragma omp parallel for reduction ((+):sum)` into separate function(s) for the compute and reduction parts etc.

Right now, anything openmp fails on not having the `omp.h` header available:

https://godbolt.org/z/nJTKAK

```
<source>:1:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
Compiler returned: 1
```

**Comment by apmorton** [comment]
Just FYI, that now lives at https://github.com/compiler-explorer/clang-builder/blob/master/build/build.sh

I don't see any issues with adding that to see if it resolves this issue. At bare minimum it will take effect for the daily trunk builds. If it resolves the issue we could discuss recompiling old clang versions with it enabled.

**Comment by damageboy** [comment]
> I don't see any issues with adding that to see if it resolves this issue.

FWIW, this did the trick on my machine.

**Comment by damageboy** [comment]
I can report that clang trunk with `#include <omp.h>` now works for me on godbolt.org

**Comment by apmorton** [comment]
good to hear - now the only question is whether or not we want to recompile old clang versions to pick this change up.

And if so, how far back should we go?

@mattgodbolt
Thoughts?

**Comment by damageboy** [comment]
I don't personally think it is super critical to go lots of versions into the past,
but for what it's worth, it seems to have been there for a long time:

https://clang-omp.github.io/

> OpenMP 3.1 is fully supported in clang/llvm 3.7

**Comment by mattgodbolt** [comment]
Thanks folks; I'm thinking we should go back a couple major revisions' worth to be useful...and then if we get that far we'll need to automate it anyway, in which case "just" doing the lot might be useful. I'lll take a look later :)
