### ISSUE TITLE
Have debug builds of clang

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#799]
Might add further confusion to the drop-down box but when compiler bugs are found it might be useful to be able to see if the debug build also has the problem, or if it asserts in some way.

**Comment by danilaml** [comment]
This would be also really useful for when you want to debug specific optimization pass. Even build with just asserts enabled would be good.

**Comment by partouf** [comment]
I'm inclined to close this, as we now have a clang-assertions-trunk
