### ISSUE TITLE
Consider decompiler output?

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#818]
Avast have open sourced their decompiler. https://blog.avast.com/avast-open-sources-its-machine-code-decompiler - wonder whether it would make an interesting view?

**Comment by RabsRincon** [comment]
If we add this, I think we could also do http://storm-country.com/blog/evo-deco . Maybe add a new "language" category called "Decompilers"!

**Comment by mattgodbolt** [comment]
See also #1340

**Comment by jeremy-rifkin** [comment]
Closing in favor of https://dogbolt.org/ for now 😄
