### ISSUE TITLE
Add examples for CUDA

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#921]
e.g. https://godbolt.org/g/Ce6Mhe from Christian Mazakas on slack

**Comment by partouf** [comment]
To add an example to the website, all you need is to send us a PR with a new file in the folder `examples/cuda` (https://github.com/compiler-explorer/compiler-explorer/tree/main/examples/cuda)

The linked source is a good example to include in a new file.

Some rules about the filename:
* Underscores are translated to spaces in the UI
* The name is case-sensitive
* Be descriptive, but short

Example of how the filenames will look in the UI:
![image](https://user-images.githubusercontent.com/442630/112906506-9156d280-90ec-11eb-84a9-3974202aaec9.png)

**Comment by Bhartirana2812** [comment]
hey!! can i take this issue

**Comment by partouf** [comment]
> hey!! can i take this issue

Excellent! Please do!

**Comment by Bhartirana2812** [comment]
yes sure @partouf

**Comment by Arsenic-ATG** [comment]
hey 
**Is this issue still up for grabs ?**

I still can't find examples being added in [examples/cuda](https://github.com/compiler-explorer/compiler-explorer/tree/main/examples/cuda) subdir ( other than default one of-course) 

---- 
If I can still work on it, then I have some basic cuda examples in mind that might work ( looking at other examples from the [examples](https://github.com/compiler-explorer/compiler-explorer/tree/main/examples) subdir of other supported languages ). 

I intend to add 3 different example program with functions that does the following :

1. Finding max in a subarray ( using parallel reduction )
2. Calculate sum over subarray ( again parallel reduction )
3. Add 2 arrays into a third array

**Comment by partouf** [comment]
> hey **Is this issue still up for grabs ?**
> 
> I still can't find examples being added in [examples/cuda](https://github.com/compiler-explorer/compiler-explorer/tree/main/examples/cuda) subdir ( other than default one of-course)
> 
> If I can still work on it, then I have some basic cuda examples in mind that might work ( looking at other examples from the [examples](https://github.com/compiler-explorer/compiler-explorer/tree/main/examples) subdir of other supported languages ).
> 
> I intend to add 3 different example program with functions that does the following :
> 
> 1. Finding max in a subarray ( using parallel reduction )
> 2. Calculate sum over subarray ( again parallel reduction )
> 3. Add 2 arrays into a third array

Please do

**Comment by jinder1s** [comment]
I think this issue is done. @Arsenic-ATG added examples in https://github.com/compiler-explorer/compiler-explorer/commit/9a75a7a1d686b3f5a59a20fa4426cc79e5bcb0bd
