### ISSUE TITLE
Support both host and device code on cuda

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#922]
Maybe by doubling up the compilers and having `nvcc (host)` and `nvcc (device)`

**Comment by partouf** [comment]
We have some device code handling here https://github.com/compiler-explorer/compiler-explorer/blob/2f56da5f926f7e639b74a184937bd72941b06e8e/lib/compilers/clang.js#L105 - originally from this PR https://github.com/compiler-explorer/compiler-explorer/pull/2836/files

But obviously some things are commented out and we haven't applied it to NVCC/CUDA yet.

We really need someone to invest some time and aftercare into this to get some human understandable code and UI going for this.

**Comment by partouf** [comment]
Link to it in action (from Clang > 12 / trunk it broken) https://godbolt.org/z/KMK3PKhbb

**Comment by jeremy-rifkin** [comment]
Thank you!

**Comment by partouf** [comment]
Mostly supported now
