### ISSUE TITLE
Help for registers

### ISSUE THREAD

**Issue by vors** [compiler-explorer/compiler-explorer#947]
Thank you for the great project! ❤️ 

I really like the help on hover and extended help in "View asm doc" menu. Find it very valuable. I'd love to see the same for the registries like `rbp`, `rsp` and such.
It would help asm noobs like myself a lot.

**Comment by RabsRincon** [comment]
Hi! Thanks for the kind words 😃 

While your idea sounds really useful, I don't think we could be able to pull it off, mainly due to the amount of different targets the compilers can build for.

I do have one question: Which kind of info would you like to get if we were to have something like what you suggest available?

:)

**Comment by vors** [comment]
I was thinking about something basic like `rbp points to the current stack frame`.

Here is the demo of what I tried and was hoping to get some info on
![godbolt](https://user-images.githubusercontent.com/816680/41066859-55d49cb6-6998-11e8-8924-cdcf6cb229bc.gif)

I understand that it's pretty huge work to make it comprehensive, but maybe we can
1. Lay down the framework support for that type of help
2. Start with few common registry
3. Expanding it with community contributions

**Comment by mattgodbolt** [comment]
Right: that's a problem with this really. Only a few of the registers (on x86) have well defined meanings, `rsp`. We might be able to write something for each register that gives some clues, e.g. (`eax - used to store return integral values`), but even that's confusing (e.g. with RVO). Noting that `rdi` is also the first parameter (containing the `this` pointer for method calls) is sort of useful, but with any optimization turned on `rdi` is quickly recycled to mean something else, specific to the function being called.

I had some ideas in #28 but it doesn't look like there's much information available there either.

Perhaps a general page of "this is what x86_64 registers are, roughly" might help.

**Comment by partouf** [comment]
let's close this in favor of https://github.com/compiler-explorer/compiler-explorer/issues/2616
