### ISSUE TITLE
For LLVM IR, "Filter Unused Labels" incorrectly filters used labels.

### ISSUE THREAD

**Issue by LebedevRI** [compiler-explorer/compiler-explorer#957]
https://godbolt.org/g/ftkuov
I initially incorrectly reported that as https://bugs.llvm.org/show_bug.cgi?id=37800

As you can see from the diff view, it filtered out `bb` label, even though it is used in 
`%tmp1 = phi i32 [ %tmp2, %.preheader ], [ 0, %bb ]`.

That results in invalid IR.

**Comment by mattgodbolt** [comment]
This fix is now live.

**Comment by LebedevRI** [comment]
Thank you!
