### ISSUE TITLE
std c++ library missing in clang trunk

### ISSUE THREAD

**Issue by pps83** [compiler-explorer/compiler-explorer#962]
... if `-target arm64` or `-target armv7a`. This problem has been there forever I think

https://godbolt.org/g/HkpW1y

**Comment by mattgodbolt** [comment]
Any help on how to install the std c++ library for these targets appreciated.

**Comment by pps83** [comment]
I have no idea, the only access to clang that I have is the one that goldbolt provides :)
Some clang experts who could help? Perhaps something is missing and needs to be installed, or compilation cmd misses something

**Comment by mattgodbolt** [comment]
Confirmed this is an issue even if `-stdlib=libc++` is added. Curious. Definitely need a clang expert's help here. https://godbolt.org/z/e7oWtD

**Comment by partouf** [comment]
I think we fixed this problem a while ago by adding separate compilers for these architectures.
Only -float=hard doesn't work, but most of the rest of stdlib does.

Closing this in favor of https://github.com/compiler-explorer/compiler-explorer/issues/2359 to add support for more things arm.
