### ISSUE TITLE
Add GCC RISC-V Support

### ISSUE THREAD

**Issue by palmer-dabbelt** [compiler-explorer/compiler-explorer#965]
RISC-V is an open standard ISA that's maintained by the non-profit RISC-V orginization, which has over 100 members today. More information can be found at https://riscv.org/ . Our GCC port is pretty solid as of 7.3.0 -- we recently got more packages built in our Debian port than IA64 has, for example!

We've got a RISC-V setup running already https://cx.rv8.io/, but we'd love to be part of the official compiler explorer site.

Right now the blocker is the latest crosstool-ng release doesn't have support for RISC-V, and upstream master only supports rv32.

**Comment by chandlerc** [comment]
Should #334 be dup-ed here?

Is there anything others can do to help support this? Myself, @jyknight, and @jorgbrown are probably pretty interested in this. I'm specifically interested if there is anything we could do to Clang and LLVM to make it easier to get a Clang trunk mode supporting RISC-V. You should be able to build a single Clang-based toolchain install which supports all the CPUs supported in Clang and LLVM, and just requires a `--target=....` flag to select them.

**Comment by mattgodbolt** [comment]
Good point @chandlerc - while I think this captures more of the GCC-side work that needs to be done. Will rename this bug and #334 too to clarify this somewhat retro-fitted interpretation :) (It will be useful to have separate issues for GCC and Clang anyway).

**Comment by Wren6991** [comment]
Awesome that this is being worked on :+1: spent a happy while playing with the gcloud-hosted site.

Any idea why I'm getting this when I go for binary disassembly? Can't seem to get hold of the actual objdump stderr.

`<No output: objdump returned 1>`

I was interested in how the `li` pseudo-op actually gets assembled, e.g. when your 1 bits are confined to a narrow range, does it assemble as `addi` followed by `slli` rather than `lui` followed by `addi`.

**Comment by Ferdi265** [comment]
@Wren6991: yes, it does that. at least for small ranges.

For larger constants (having bits all over the register) GCC opts to use `lui`/`auipc` + `ld` from a constant pool, while CLANG likes to use long `lui`/`slli` chains

**Comment by mattgodbolt** [comment]
I just tried a "simple" attempt at building GCC for RISCV5 and got crosstool errors `Build failed in step 'Installing kernel headers'`. That was using the settings I had set up in the https://github.com/compiler-explorer/gcc-cross-builder/ repo. Next time I have a bunch of time to debug I'll look in to it, but it was "just" pick the most recent option in all cases during menu setup of crosstool.
