### ISSUE TITLE
Add support for Movfuscator compiler

### ISSUE THREAD

**Issue by ThadHouse** [compiler-explorer/compiler-explorer#985]
We were teaching some assembly and had some of our students seeing how much can be done with just a `Mov` instruction. There exists a compiler that can compile C with only mov instructions, and it would be cool to have in compiler explorer. I would be happy to help with a PR if I could get some help on where and how to add a new compiler.

https://github.com/xoreaxeaxeax/movfuscator

**Comment by RabsRincon** [comment]
Hi! Thanks for the suggestion. We usually don't have the needed time to add new compilers, so thanks for wanting to do the work yourself. What we can sure do is to help as much as we can.

You can read our doc on how to add a new compiler https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/AddingACompiler.md, which should explain most things.
Do not hesitate on asking, and we'll get back to you as soon as possible

:)
