### ISSUE TITLE
C# support?

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#999]
I know I've been reluctant to add any JITted language. But a friend asked me... so I'm raising this!

https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x

dotNet core should install...and maybe there's a way to coax it to generate object code?

**Comment by TomSmartBishop** [comment]
Or just build the code and use ildasm to generate .net assembler (a bit ugly I know)

**Comment by jaredwy** [comment]
Do you want assembler or IL?

**Comment by tsafin** [comment]
FWIW - today I've discovered there is similar tool, formerly known as TryRoslyn https://sharplab.io/

**Comment by mattgodbolt** [comment]
See also #882

**Comment by Mistuke** [comment]
@mattgodbolt I would want Assembly and not IL (though I can see IL being useful), and would like CoreCLR support ideally.

This seems to have stalled a bit so here's some ideas to hopefully revive this somewhat :)

One of the things you mentioned in #882 is that you want the output to represent the best of what the compiler has to offer.  I think you can get that in one of two ways:

1. Turn off Tiered compilation, so you get the "best" code always from the JIT. (see https://docs.microsoft.com/en-us/dotnet/core/run-time-config/compilation)
2. Use Ahead-of-time compilation to produce the native code.
    https://github.com/dotnet/runtimelab/tree/feature/NativeAOT which should produce the "best" version

the accuracy of disassembly for no# 2 is higher, but you'd need no# 1 if you want to support debug dumps (I think, not sure if the native compiler supports it).

no# 1 requires you to either have a debug build of the JIT itself in order to get the dumps, or catch the code in memory (like perf etc do). So no# 2 may be more practical.

**Comment by gfoidl** [comment]
> Turn off Tiered compilation, so you get the "best" code always from the JIT

This is not (entirely) true, and won't be true in the future.
With tiered compiliation
* the JIT knows that static constructors ran at Tier-0, so `static readonly` fields can be seen as constants for Tier-1 (without the boilerplate code to check if they are already run)
* Tier-0 can collect a profile to to use some form of PGO for Tier-1 (will come in the .NET 6+)

**Comment by Mistuke** [comment]
@gfoidl Ah I didn't know that. Which approach would you recommend?

**Comment by gfoidl** [comment]
That's a good question...

Current JIT-config promotes code (a method) from Tier-0 to Tier-1 when it is called 30 times, and after the "startup delay" of 100ms beginning from the last JIT-operation.

For your # 2 above (Native AoT) I can't speak, as I'm not very familiar with.

For # 1 according the versioning policy I use a script that helps me and it's based on [Viewing JIT dumps][jitdump].
This script is parametrized, so the methods to disassembly can be set. Example given below (collapsed).
Relevant is `export COMPlus_JitDisasm="$methodName"`

<details>
  <summary>scripts</summary>

Notice: the app which contains the method(s) to disassemble is called "Jitdump_Test" and the folders are layed out accordingly.

```bash
#!/bin/bash

set -e

frameWork="net5.0"
methodName="Main Do Add"

dotnet publish -c Release
chmod +x /home/gfoidl/test/Jitdump_Test/bin/Release/"$frameWork"/linux-x64/publish/Jitdump_Test

#cp -rT   /home/gfoidl/dotnet-repos/runtime/artifacts/bin/coreclr/Linux.x64.Release            /home/gfoidl/test/Jitdump_Test/bin/Release/"$frameWork"/linux-x64/publish
#cp       /home/gfoidl/dotnet-repos/runtime/artifacts/bin/coreclr/Linux.x64.Debug/libclrjit.so /home/gfoidl/test/Jitdump_Test/bin/Release/"$frameWork"/linux-x64/publish
 cp -rT   /home/gfoidl/dotnet-repos/runtime/artifacts/bin/coreclr/Linux.x64.Checked            /home/gfoidl/test/Jitdump_Test/bin/Release/"$frameWork"/linux-x64/publish

export COMPlus_JitDisasm="$methodName"
# export COMPlus_TieredCompilation=0
# export COMPlus_JitPrintInlinedMethods=1
# export COMPlus_JitDump="$methodName"
# export COMPlus_JitDiffableDasm=1
# export COMPlus_EnableAVX=0
# export COMPlus_EnableSSE=0

/home/gfoidl/test/Jitdump_Test/bin/Release/"$frameWork"/linux-x64/publish/Jitdump_Test | tee jit_dump.asm
```

```c#
using System;
using System.Runtime.CompilerServices;
using System.Threading;

namespace Jitdump_Test
{
    class Program
    {
        static void Main(string[] args)
        {
            int[] arr = { 1, 2, 3, 4, 5 };

            int s0 = Do(arr);
            s0 = Add(s0, 0);

            Sleep(2 * 100);                         // 100ms is the timer used is tiered-jit

            int s1 = 0;
            for (int i = 0; i < 30 - 1; ++i)        // 30 is the threshould for triggering tier-1, one call is already done
            {
                int tmp = Do(arr);
                s1 = Add(s1, tmp);
            }

            Sleep();                                // wait a bit, so that the JIT can produced tier-1 and the code-versionmanager can update the method

            int s2 = Do(arr);
            s2 = Add(s2, 0);

            if (s0 != s1 || s0 != s2) Environment.Exit(1);
        }

        private static void Sleep(int ms = 100) => Thread.Sleep(ms);

        // Methods with loops are optimized by default
        [MethodImpl(MethodImplOptions.NoInlining)]
        private static int Do(int[] arr)
        {
            int s = 0;

            for (int i = 0; i < arr.Length; ++i)
                s += arr[i];

            return s;
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static int Add(int a, int b) => a + b;
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
        <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    </PropertyGroup>

    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

</Project>
```
</details>

Locally (to be precise: in a VM) therefore I have a build of the JIT.
To make this manageable for the compiler explorer, one should check if docker images are helpful / can be used from the dotnet-org, so it's easier to keep up-to-date. I didn't investigate this so far, as AFAIK only images from release-builds are available, and for disassembling either a "checked" build or the combination debug+release is needed (in the script above they're commented out, depending on which approach I use, and the one for checked-builds I didn't know some time ago).

---

For completeness some options to view disassembly from C# code / .NET assemblies:
* https://sharplab.io/ (mentioned above), but it has .NET Core 3.1 version of the JIT, so not always the latest JIT-bits
* [Viewing JIT Dumps][jitdump] -- actual "log" from the JIT itself
* [Disassembler from BenchmarkDotNet](https://benchmarkdotnet.org/articles/features/disassembler.html)
* [Disasmo](https://github.com/EgorBo/Disasmo) VS extension
* https://godbolt.org/ ? (this issue)

[jitdump]: https://github.com/dotnet/runtime/blob/master/docs/design/coreclr/jit/viewing-jit-dumps.md

**Comment by gfoidl** [comment]
@EgorBo I'm pretty sure you can provide some meaningful input here, so please have a look.

**Comment by partouf** [comment]
now live!

**Comment by Alexis-Martial** [comment]
Exceptional!
I tried and failed to successfully set C# compiler options in the Compiler Options UI Text Box.
What is the trick?
